### ISSUE TITLE
[BUG] Can't interact with the Boat Seller

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#1000]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

Can't interact with the boats down at Postal 349 to buy a boat.

### Steps to Reproduce the Bug

1. Go to Postal 349
2. Use third eye on Boat
3.  Vehicle Interaction doesn't show options

### Expected Behavior

The menu opens to buy vehicle or change vehicle.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98053772/210177522-297da963-f675-4984-a3f1-d3def7d38766.png)

**Comment by ithegreatgatsby** [comment]
https://cdn.discordapp.com/attachments/926424477049438258/1069421275547697212/g9z7xVFKVB.png
