### ISSUE TITLE
[ENHANCEMENT] Keybind addition =

### ISSUE THREAD

**Issue by pulsevr34** [ParadoxGamingRP/bugs-and-suggestions#1004]
**Your Discord Name**
Pulse+#5769

**Describe the annoyance**
Would like a  keybind for the = button, I have that set for my recording software and I'd like to change it to something easily accessible so I dont keep having to change my recording keybinds

**To Reproduce**
[Steps to reproduce the annoyance]
1. look for = keybind
2. nada

**Requested behavior**
Be able to set the ID checker to a different button in the Keybinds menu

**Screenshots**
N/A

**Additional context**
N/A

**Comment by JnKTechstuff** [comment]
Its in a shitty position so its hard to abuse. Letting you keybind it to whatever you want only leads to more abuse.
