### ISSUE TITLE
[ENHANCEMENT] Promote More RP with Tow

### ISSUE THREAD

**Issue by OwlCherry** [ParadoxGamingRP/bugs-and-suggestions#1010]
**Your Discord Name**
OwlCherry#6969

**Describe the annoyance**
Although impound as it stands works well, when you have say and accidental pump explosion affecting say 20 people and several vehicles, it would be really cool to offer a discounted impound fee if you contact a tow operator instead. this will offer more opportunities to RP out impound, while saving slightly on impound fee's

**To Reproduce**
1.  go to impound
2.  pay anywhere from $30 - over $2k 
3.  drive off

**Requested behavior**
1. Contact Tow
2. Request a Impound Release
3. Have a tow driver attend impound, gather the information.
4. Have tow operator accept payment (Discounted from current rates)
5. Vehicle is released from impound giving both parties RP

**Comment by JnKTechstuff** [comment]
I don't think tow wants this lol

**Comment by OwlCherry** [comment]
thats fair, i figured it was a good idea and id bring it up anyways but if they dont want it thats cool too! we just had a few issues yesterday that costed a shit ton in impound fee's when someone tried to rp it out with tow but nothing could be done cuz car was broke broke

**Comment by ithegreatgatsby** [comment]
gas pumps dont blow up  any longer as well as cars poof more often then they get blown up.
