### ISSUE TITLE
[BUG] <Bikini Automotive paychecks are not going through and the shift log isn't recording>

### ISSUE THREAD

**Issue by TeddyNM** [ParadoxGamingRP/bugs-and-suggestions#1014]
### Your Discord Name

TeddyMercury#4685

### A clear and concise description of what the bug is

The prompt showing you getting paid is not showing up and neither is the money showing up when they go to the bank nor is it showing up in the logs. Shift logs are also not showing up when they clock in and out. 

### Steps to Reproduce the Bug

1. Clock in  
2. Wait for paycheck tick 
3. Clock out 

### Expected Behavior

1. Clock in 
2. Get paid every 20ish minutes 
3. Clock out 
4. Time card show up in discord
5. pick up check at bank 

### Screenshots/Videos

na

### Log File

[CitizenFX_log_2023-01-10T015812.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10378846/CitizenFX_log_2023-01-10T015812.log)

**Comment by ithegreatgatsby** [comment]
is this still a issue?
