### ISSUE TITLE
[BUG] Boost's not giving drop off location

### ISSUE THREAD

**Issue by JonnieSlay** [ParadoxGamingRP/bugs-and-suggestions#1018]
### Your Discord Name

yeaaaaa#9829

### A clear and concise description of what the bug is

On 2 separate occasions, I have completed the 3 hacks (currently on the first class). On the 3rd hack, the 3/3 phone notification goes away , however I get no drop off location. I also did notice that on the F8 console, there is a consolelog loop that states like "Current hack : 0 out of :3 ." or something along the lines, and this is looped non stop even if get hacks right / you cancel the contract. It's not breaking out of that loop. 

The first time I thought it was just scuffed and the 2nd scuff, I just gave a ring to somebody over who does these a lot and told me it was currently scuffed. 
The only thing is that I didn't see a bug report, So i figure I would put it in to make sure you guys are aware. 

### Steps to Reproduce the Bug

1. Get a boosting contract. 
2. Complete the gps disabler hacks. 
3. Get no drop off location. 

### Expected Behavior

Expected behavior is after the final hack, you should get a drop off location so that you can complete your boost. 
I did usually get successful drop off locations pre phone-hack-notification update. I think the notifications are super cool, but ever since that update 100% of my boosts have been scuffed. I am afraid to try another one as the risk is always high, and the current reward is null. 

### Screenshots/Videos

I have no clips on me, I will check it when i get back home. I think I have a clip of finishing the 3rd hack + f8 console loop. I will update this bug report. I am afraid of doing another boost as the risk is high and the reward would be null. 

### Extra Notes (Optional)

Ill add more info on this as soon as I get home in roughly 4 hours.

**Comment by JnKTechstuff** [comment]
I need logs...

Its on the form for a reason

**Comment by JonnieSlay** [comment]
> I need logs...
> 
> Its on the form for a reason

Hey apologize for not getting a log, at the time I didn't know if it was going to be a recurring issue and After I was informed of it being a known bug, i figured there was already a git-hub report. 

However check this clip. I opened the console and scrolled all the way to the top of the loop.
Also you'll see the on the 2nd hack i get it right(you can confirm by seeing when the timer stops as i pressed enter) but the numbers kept moving for another second or so, and the notification on the phone disappeared. It re-appeared when i get the hack right again. 

https://medal.tv/games/gta-v/clips/PxwP7g5dX6Opb/d13375Mwf7iv?invite=cr-MSxNR28sMTUzNzcyODUwLA

I can do another boost but i am afraid of loosing the valuable laptop/disabler in the process of getting your logs.
