### ISSUE TITLE
Dremel durability [BUG] 

### ISSUE THREAD

**Issue by RedDarthMawl** [ParadoxGamingRP/bugs-and-suggestions#1019]
### Your Discord Name

RedDarthMawl#9096

### A clear and concise description of what the bug is

The durability of the dremel doesn't go down if I have it to the right of a broken one

### Steps to Reproduce the Bug

1. buy 2 dremels from mine person
2. use one dremel to where it breaks
3. put broken dremel in a far left spot in your inventory
4. put unused dremel to the right of it
5. use dremel to cut gems

### Expected Behavior

I was testing out different jobs that required tools to do stuff to see if it did the same thing that happened with the watering can and animal feed and it did the exact same thing before they got fixed. I did unintentionally abused the bug a bit because I hadn't realized what was going on at first but then I dumped the broken dremel along with the gems I cut when it was in my inventory because I didn't find it fair to keep them  after I had recorded the bug

### Screenshots/Videos

![Screenshot (320)](https://user-images.githubusercontent.com/68886995/212481430-975493f0-64f0-4978-a6e0-db76bebb209b.png)

https://user-images.githubusercontent.com/68886995/212483899-c4662ecf-23b4-4cb2-a99b-9151781fef3b.mp4

### Log File

[CitizenFX_log_2023-01-13T234622.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10418260/CitizenFX_log_2023-01-13T234622.log)
[CitizenFX_log_2023-01-14T060116.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10418261/CitizenFX_log_2023-01-14T060116.log)
[CitizenFX_log_2023-01-14T152203.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10418262/CitizenFX_log_2023-01-14T152203.log)

**Comment by tusktheshrew** [comment]
Can Confirm this bug, this bug also doesn't need the 2nd dremmel. If there is just 1 broken dremmel it will still cut.
