### ISSUE TITLE
[ENHANCEMENT] Burning grows

### ISSUE THREAD

**Issue by LitrlyD3ad** [ParadoxGamingRP/bugs-and-suggestions#1022]
**Your Discord Name**
D3ad#2545

**Describe the annoyance**
The ability for cops to "burn" grows (weed, etc.) when finding them, whether that be by using a gas can or a flame thrower (probably not a flame thrower but it would be neat)

**To Reproduce**
[Steps to reproduce the annoyance]
1. find a grow 
2. catch the guy and take your photos
3.  spend 30 min or more picking them one by one
4. 

**Requested behavior**
For PD to have a option in our belt to "burn" a grow either by just 3rd eyeing the plant and burning it or by using a tool (such as a flame thrower) to burn the plant, and when we burn it have it be unharvest-able, I think this could add some pressure to growers to be a bit smarter and it could also make picking up the plants much easier for PD

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by Darahz** [comment]
Should be live now!
