### ISSUE TITLE
[ENHANCEMENT] Coke Lab-PD relations 

### ISSUE THREAD

**Issue by LitrlyD3ad** [ParadoxGamingRP/bugs-and-suggestions#1024]
**Your Discord Name**
D3ad#2545

**Describe the annoyance**
When we raid a coke lab we need to use lockpicks in order to get in.

**To Reproduce**
[Steps to reproduce the annoyance]
1. find lab
2. go to door
3. realize you need a lockpick
4. only 1 officer has one
5. officer lockpicks the door open and goes in alone

**Requested behavior**
To be able to use either the rambar we have or the breaching charge we have, due to the lack of usecase for the breaching charge id like to see that be used instead. Maybe make it take x amount of time to "charge" and notify the owners of the lab so they can come and maybe fight for it? I think making pd wait for the door to blow would put pressure on both PD to get setup and crims to protect their labs. Could lead to some solid rp on both sides.

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by JnKTechstuff** [comment]
In next restart:
- You can use an enforced to bust a door down
- After lockpicking/busting a door down it will simply unlock it now allowing all officers to enter at the same time
