### ISSUE TITLE
[ENHANCEMENT] Tackle cooldown

### ISSUE THREAD

**Issue by pulsevr34** [ParadoxGamingRP/bugs-and-suggestions#1025]
**Your Discord Name**
Pulse+#5769

**Describe the annoyance**
Anyone can spam tackle people continuously and keep them from getting up, also in foot chases way too many cops are still tackling people as soon as they get up after a million announcements about it, would be nice to get a cooldown of 10-15 seconds to prevent spam tackling and make foot chases last longer.

**To Reproduce**
[Steps to reproduce the annoyance]
1. Tackle someone
2. tackle again with no cooldown
3. person can now not get up / foot chase ruined

**Requested behavior**
Long-ish cooldown on tackling to encourage longer police foot chases and stop spam tackling 

**Screenshots**
Can get a clip if needed but its pretty self explanatory 

**Additional context**
N/A

**Comment by ithegreatgatsby** [comment]
this was added a day or so ago
