### ISSUE TITLE
[ENHANCEMENT] Add Breathalyzer Prop

### ISSUE THREAD

**Issue by jplink420** [ParadoxGamingRP/bugs-and-suggestions#1028]
**Your Discord Name**
J_plink#1691

**Describe the annoyance**
It would be awesome to have a breathalyzer prop for DUI traffic stops or even for PD to set up DUI checkstops. We can of course use /me's to RP this out, but an actual prop would give it that extra touch of Paradox magic. Currently, you have to do this purely through /me's.

**To Reproduce**
[Steps to reproduce the annoyance]
1. Be a Cop or Civilian
2. Pull someone over for driving drunk/get pulled over for driving drunk
3. Have no prop for a breathalyzer, so just hold your hand out straight and point at the suspect's face

**Requested behavior**
Add an emote/prop for a Breathalyzer, possibly making people more likely to give their characters DUI charges, and giving PD more to do in down times.

**Comment by ithegreatgatsby** [comment]
After Talking to high command about their drinking and driving SOP, We are going to review this at a later time once PD has redone the SOP for checkpoints and DUI checks and once they get more interest from it. Closing for now
