### ISSUE TITLE
[BUG] Boost issues

### ISSUE THREAD

**Issue by richard19999** [ParadoxGamingRP/bugs-and-suggestions#1029]
### Your Discord Name

Zeal_Undy

### A clear and concise description of what the bug is

C class boost scuffed 2 times in a row, We accepted contract. We found vehicle. We lockpicked into it, and the tracker was never able to be removed. The purple circle also didnt go away as if we wernt in the right vehicle. I double check it both times and it was the right vehicle. 

### Steps to Reproduce the Bug

Get contract
accept contract
break into car
try to start the hacks

### Expected Behavior

I should be able to use the gps disabler in the vehicle that we are trying to boost

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/97858607/214231281-77765e84-1c37-4312-bbfb-9ad5fd82f21d.png)

### Log File

[CitizenFX_log_2023-01-24T063545.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10487101/CitizenFX_log_2023-01-24T063545.log)

**Comment by xXJamieXx** [comment]
Script was updated. Open a new issue if bugs persist.
