### ISSUE TITLE
[BUG] Trunk Issue

### ISSUE THREAD

**Issue by Ashleyfur** [ParadoxGamingRP/bugs-and-suggestions#1042]
### Your Discord Name

Ashleyfur#0001

### A clear and concise description of what the bug is

Tried to open the trunk of my pounder custom. However, instead of the trunk opening I just get the grounds inventory. I walked around the vehicle to see if that would cause the trunk to open but still just got the grounds inventory. I did relog to see if that would fix the issue but that did not work. Edit: Also tried opening from ontop of the vehicle. 

### Steps to Reproduce the Bug

Get a Pounder Custom commercial vehicle.
Try to open trunk. 

### Expected Behavior

I expected to open my trunk so I could transport ores for smelting. 

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/123538135/214502095-e9269176-01fa-4011-8dfd-83daed0c1ec5.png)

### Log File

[CitizenFX_log_2023-01-25T063530.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10497002/CitizenFX_log_2023-01-25T063530.log)

**Comment by emeraldleo1982** [comment]
I experienced this pre-update as well, and found that it was due to a difference in height between myself and the rear door, it worked in some low spots, or if I got above the rear door.

**Comment by Ashleyfur** [comment]
Was unable to access this evening when I pulled the pounder out. Mabey I'm doing something wrong my end? Again tried walking all around it and walking inside to open the trunk.
