### ISSUE TITLE
[BUG] Unable to process coca leaves in coke table

### ISSUE THREAD

**Issue by Gasoa** [ParadoxGamingRP/bugs-and-suggestions#1055]
### Your Discord Name

Gasoa#6137

### A clear and concise description of what the bug is

Unable to process coca leaves in coke table. 

### Steps to Reproduce the Bug

1. Place coke table down
2. Place coca leaves in table 
3. Process them, then get hit with the ol' *No plants to break down*

### Expected Behavior

Process Soaked Coca Leaves on the coke table and get Cured Coca Leaves. 

### Screenshots/Videos

N/A

### Log File

[CitizenFX_log_2023-01-25T170248.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10503212/CitizenFX_log_2023-01-25T170248.log)

**Comment by JnKTechstuff** [comment]
Works fine for me
