### ISSUE TITLE
[BUG] Cocaine Brick Not Drying 

### ISSUE THREAD

**Issue by LtNathan235** [ParadoxGamingRP/bugs-and-suggestions#1057]
### Your Discord Name

Lnathan#2764

### A clear and concise description of what the bug is

When leaving cocaine bricks in a stash/inventory to dry while not being in server they do not degrade in moisture/dry.

### Steps to Reproduce the Bug

1. Make cocaine bricks
2. Put them in a stash to dry
3. logout
4. Wait some time
5. Load into server and view bricks
6. Notice they do not dry/degrade in moisture

### Expected Behavior

For bricks to slowly dry while in server or out.

### Screenshots/Videos

na

**Comment by JnKTechstuff** [comment]
Fixed
