### ISSUE TITLE
[BUG] Paleto Bank Robbery Ped Broken

### ISSUE THREAD

**Issue by LtNathan235** [ParadoxGamingRP/bugs-and-suggestions#1058]
### Your Discord Name

Lnathan#2764

### A clear and concise description of what the bug is

When interacting with the ped to reserve a Paleto bank heist you are given the option to "rent a boat" or to "talk, the renting a boat option will allow you to rent a dinghy while the "talk" option has no affect.

### Steps to Reproduce the Bug

1. Talk to ped
2. Notice he rents out boats
3. Try to "talk" to him
4. Notice nothing happens

### Expected Behavior

To be able to reserve the bank heist properly and not be given the option to rent a boat

### Screenshots/Videos

na

**Comment by JnKTechstuff** [comment]
Fixed
