### ISSUE TITLE
[BUG] Garbage job

### ISSUE THREAD

**Issue by currysauce8myass** [ParadoxGamingRP/bugs-and-suggestions#1060]
### Your Discord Name

corriehume#6821

### A clear and concise description of what the bug is

so a issue i believe to be a bug is that i went to do the garbage job and after one collection on a single bin which would allow me to collect it twice for some reason  a message would come up saying you are to far away from the depot head back to the depot i logged out for a couple hours and that didnt fix the issue  

### Steps to Reproduce the Bug

im not to sure as im not really a admin so its out of my hands to make a judgment 

### Expected Behavior

im not to sure as im not really a admin so its out of my hands to make a judgment 

### Screenshots/Videos

https://cdn.discordapp.com/attachments/942177119411240980/1067914728657129472/bug.png

**Comment by ithegreatgatsby** [comment]
duplicate issues of #1027
