### ISSUE TITLE
[BUG] Wages not being removed from Business Accounts 

### ISSUE THREAD

**Issue by natashajoan** [ParadoxGamingRP/bugs-and-suggestions#1065]
### Your Discord Name

its_ahsatan#7098

### A clear and concise description of what the bug is

Was keeping an eye on the Glazed & Glorious bank account because of another issue,  and it came across that wages weren't being removed from the business account, we currently have 6 people clocked in and the bank hasn't reduced in amount since tsunami. 

### Steps to Reproduce the Bug

1. Clock on duty
2. Earn money
3. Money not being taken from business account 

### Expected Behavior

For the money we pay employees to be removed from our business bank account per paycheck. 

### Screenshots/Videos

n/a

### Log File

[CitizenFX_log_2023-01-25T230043.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10505214/CitizenFX_log_2023-01-25T230043.log)

**Comment by xXJamieXx** [comment]
Determined not to be the case
