### ISSUE TITLE
[BUG] Till receipts not actually depositing into bank accounts 

### ISSUE THREAD

**Issue by natashajoan** [ParadoxGamingRP/bugs-and-suggestions#1066]
### Your Discord Name

its_ahsatan#7098

### A clear and concise description of what the bug is

I was in city this morning and made note of what the Glazed & Glorious bank account was at, after the evening Tsunami, I deposited $42,000 worth of till receipts into the bank, I got the notification that they were successfully deposited, but once I checked the Glazed & Glorious bank account, the money hadn't actually deposited into the bank account, meaning we just lost $40k. 

### Steps to Reproduce the Bug

1. Work at job 
2. Take till receipt once people bought stuff
3. check bank balance
4. deposit till receipt into bank
5. check bank balance again and notice the money hasn't deposited 

### Expected Behavior

For the money we earned through sales to actually be deposited into the bank account once we deposit the till receipt. 

### Screenshots/Videos

N/A

### Extra Notes (Optional)

[CitizenFX_log_2023-01-25T230043.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10505436/CitizenFX_log_2023-01-25T230043.log)

**Comment by tusktheshrew** [comment]
I also had a Manager who deposited 8000 dollars from a sale he made. And the bank didnt increase
