### ISSUE TITLE
[ENHANCEMENT] Picture For sugar 

### ISSUE THREAD

**Issue by tommytwoshotty** [ParadoxGamingRP/bugs-and-suggestions#1073]
**Your Discord Name**
tommytwoshotty#0666]

**Describe the annoyance**
 PIcture for sugar does not exist or is not working]

**To Reproduce**
[Steps to reproduce the annoyance]
1. Open  the open road ingredient stash
2. See sugar without picture
3. 

**Requested behavior**
 See sugar with picture]

**Screenshots**
https://i.imgur.com/7zdbHrL.png

**Additional context**
[Add any other context about the enhancement here]

**Comment by JnKTechstuff** [comment]
Fixed
