### ISSUE TITLE
[BUG] Boost Issues v20193812083

### ISSUE THREAD

**Issue by Charby99** [ParadoxGamingRP/bugs-and-suggestions#1075]
### Your Discord Name

Charby99

### A clear and concise description of what the bug is

I was doing a boost and after i disabled the tracker the drop off location was in the reapers storage facility and locked. I got ahold of them and they let me in to dro it off at the location but now it has been sitting there for 30 mins and will not complete the boost

### Steps to Reproduce the Bug

Start boost ( Car - Khamelion Class D )
Find and steal boost car then disable the GPS
Drop off location is at postal 3020
Drive there and contact reapers to let you into storage area because it is all locked up and fenced off.
Drop car off directly on top of drop off location then get out and leave the area

### Expected Behavior

After dropping the car off at the drop off and leaving the area you get a notification that will tell you how much PDX you got from boost after it completes

### Screenshots/Videos

Video file is too big

### Log File

[Log Files for Boost Bug.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10506587/Log.Files.for.Boost.Bug.txt)

**Comment by xXJamieXx** [comment]
Script was updated. Open a new issue if bugs persist.
