### ISSUE TITLE
[BUG] Fishing box

### ISSUE THREAD

**Issue by NineteenDangam** [ParadoxGamingRP/bugs-and-suggestions#1081]
### Your Discord Name

nineteen

### A clear and concise description of what the bug is

when i try to use a fishing box in all 3 ways possible (dragging it over use, right clicking and clicking use, and using it in a muscle) it closes my inventory if its the first two i said and if its in my muscle it doesnt open up either

### Steps to Reproduce the Bug

put a fishing ice box in your muscle and try to use it and also try to open it from your inventory

### Expected Behavior

it wont open when it should

### Screenshots/Videos

N/A

### Log File

every session

**Comment by JnKTechstuff** [comment]
Go buy a new one
