### ISSUE TITLE
[BUG] taxi options

### ISSUE THREAD

**Issue by RedDarthMawl** [ParadoxGamingRP/bugs-and-suggestions#1083]
### Your Discord Name

RedDarthMawl#9096

### A clear and concise description of what the bug is

You cannot use your third eye on the taxi vehicle when clocked in but if you are clocked out or a regular civilian you can but you also see 5 pay for order options.

### Steps to Reproduce the Bug

1. Clock out of taxi
2. Use third eye on taxi
3. You see the options 

### Expected Behavior

I thought I would be able to use third eye on taxi when clocked in so I could set up orders but I can't 

### Screenshots/Videos

![PXL_20230126_215430932](https://user-images.githubusercontent.com/68886995/214959291-1c079558-07da-48ac-95ff-ad0ad936d595.jpg)

**Comment by xXJamieXx** [comment]
Combining with #1054
