### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by richard19999** [ParadoxGamingRP/bugs-and-suggestions#1087]
### Your Discord Name

Zeal_Undy

### A clear and concise description of what the bug is

Coca plants arent working properly. If i pull my plants at 64 growth and 87 health it wont give me the appropriate amount back. I usually pull my plants at this stage and it would yield around 11 or 12 dried coca leaves. Now it gives me 15 coca leaves which is the max if your plants are 100 health and 87 growth. So when i pull my plant at 87 health that should be 87 purity once it get soaked in gas. 

### Steps to Reproduce the Bug

Grow plant
pull after 50% growth just so you get the plant. If you pull any earlier you wont get a plant.
soak them in gas and the heath of the plant now becomes the durability and the purity gets set to 100.

### Expected Behavior

When i pull my plants at 87 health the purity should be the same after they are washed with gasoline.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/97858607/215033157-3a63e8e0-3cb4-4e9f-88a4-6648690de52d.png)
 
The image above is what the plant was when i pulled it.^

![image](https://user-images.githubusercontent.com/97858607/215035852-10c978f5-06a6-4fb2-a329-cddfc3550d8b.png)

This is after the plant is soaked in gasoline. The purity should be 87 not the durability. 

### Log File

[CitizenFX_log_2023-01-27T022151.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10516607/CitizenFX_log_2023-01-27T022151.log)

This is the log of me pulling the plants at 87 health ^

[CitizenFX_log_2023-01-27T022151.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10516686/CitizenFX_log_2023-01-27T022151.log)

These are the logs of after soaking them in gas

**Comment by JnKTechstuff** [comment]
Should be fixed
