### ISSUE TITLE
[BUG] Modshop options not saving properly

### ISSUE THREAD

**Issue by Northingbud** [ParadoxGamingRP/bugs-and-suggestions#1088]
### Your Discord Name

North#6863

### A clear and concise description of what the bug is

Certain modshop options still do not save properly, have had a few reports on the subject, and after a vehicle is stored these options will revert to what is default in the vehicles carcols for newly spawned vehicles.
Affected categories seem to be: 
Extras
Respray > Dashboard Colour

### Steps to Reproduce the Bug

1.) Purchase appropriate mod
2.) Store vehicle
3.) When getting vehicle out mod option reverts/changes

### Expected Behavior

Pretty self-explanatory

### Screenshots/Videos

N/A

**Comment by ithegreatgatsby** [comment]
should be fixed with the last few server updates
