### ISSUE TITLE
[BUG] third eye for taxi 

### ISSUE THREAD

**Issue by RedDarthMawl** [ParadoxGamingRP/bugs-and-suggestions#1089]
### Your Discord Name

RedDarthMawl#9096

### A clear and concise description of what the bug is

When SADOT tried using third eye on the taxi vehicle it caused their third eye to get stuck on their screen causing them to have to quit the entire application to fix it and sometimes it fixes itself

### Steps to Reproduce the Bug

1. Clock in as SADOT
2. Try and use third eye on taxi 
3. Third eye either is stuck or goes away it's inconsistent 

### Expected Behavior

Bubba was trying to do something to the taxi because it red engined but couldn't.

### Screenshots/Videos

Ask bubba Johnson for this I'm not SADOT

**Comment by xXJamieXx** [comment]
You are in charge of retrieving evidence for your bug report, you should have asked Bubba Johnson for screenshots/videos before submitting. Can't reproduce this myself so need more info. Screenshots/videos, logs etc.

**Comment by JnKTechstuff** [comment]
Closed; no response
