### ISSUE TITLE
[BUG] Ammo Nation is not checking gun license / Prison stash opens without a needle

### ISSUE THREAD

**Issue by JonnieSlay** [ParadoxGamingRP/bugs-and-suggestions#1090]
### Your Discord Name

yeaaaaa#9829

### A clear and concise description of what the bug is

I went to an ammunation at 200 and saw the P226 despite not having a license. I thought maybe it would not allow me to purchase it , but it did. 

I went to another Ammo nation and it was also available. I do not know if its not checking it. The people that were with me also had no gun license and could see the p226/ sns . 

BUG2: 
Prison bunks currently do not require a needle to be pried open. 

### Steps to Reproduce the Bug

1. Go to ammo nation w/out a gun license 
2. See P226 
3. Try to buy it 
4. Purchase successful 

Bug2
1. Go to prison
2. Try to open bunk without a needle
3. Opens up

### Expected Behavior

I shouldn't see the gun or if i am allowed to see it, it should not allow me to buy it. 

Bug2:
I should have a needle to open the bunk.

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/SAF9NDzmS7zZK/d1337eNfPtIu?invite=cr-MSxRb0csMTUzNzcyODUwLA

Bug 2:
https://medal.tv/games/gta-v/clips/SAs8wJj6rYNhO/d1337LgVsB6w?invite=cr-MSxGT2QsMTUzNzcyODUwLA

### Log File

bug 1 & 2 happened in same session, 

[CitizenFX_log_2023-01-28T003453(no gun license).txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10525239/CitizenFX_log_2023-01-28T003453.no.gun.license.txt)

**Comment by xXJamieXx** [comment]
Can't reproduce either of these bugs.

**Comment by JonnieSlay** [comment]
I think the gun issue has been fixed (Github report #1093). 

Ill check the prison stash next time i go , it might have also been fixed already. Not sure.
