### ISSUE TITLE
[BUG] Can't open glovebox or trunk

### ISSUE THREAD

**Issue by denverw1993** [ParadoxGamingRP/bugs-and-suggestions#1091]
### Your Discord Name

denver#9114

### A clear and concise description of what the bug is

i am unable to access or store things in both my glovebox and/or trunk. i am also having issues with selling fish to the person who buys them i add them to the deposit and congirm sale and it backs out and they remain in the deposit. fishing cooler is also buggy not allowing me to use/store fish in it. thanks

### Steps to Reproduce the Bug

1. get into my car? and open inventory/try to store item. repeat for trunk except dont get in it.
2. i guess try selling fish to the fish market and also try using the cooler 
3. idk im not a code writer? i tried my best.

### Expected Behavior

when trying to use the glovebox/trunk you wont be able to store thing or retrieve them from either.
when depositing fish at the fish buyer and trying to confirm the sale it will just back out and nothing will sell. the items will remain in the deposit.

### Screenshots/Videos

i dont know how to do this.

**Comment by JnKTechstuff** [comment]
The issue is you have setup your inventory keybind to be something else.
