### ISSUE TITLE
[BUG] Moonjuice over the shoulder

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1092]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

When trying to drink the Moon juice from SOTW I'm just throwing it over my shoulder, getting my clothes all wet. I had more people test it out and they got the same result. 

### Steps to Reproduce the Bug

Buy yourself a delicious Moonjuice from SOTW. 
Drink it 
BUT THEN REALISE YOU ARE POURING IT ON YOUR SHOULDER
Change clothes and take a shower since it's now wet and sticky
(Yes you are still drinking it, it just looks weird)

### Expected Behavior

To drink the delicious drink from SOTW. 

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98127638/215284915-b6531391-a51b-4c2e-9b96-bd0429d92810.png)

**Comment by ithegreatgatsby** [comment]
next restart
