### ISSUE TITLE
[BUG] Can't buy items in stacks.

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#1095]
### Your Discord Name

Jojos n Mustard#4959

### A clear and concise description of what the bug is

Can't buy more than 1 item of any kind at a time, the amount box seems to be ignored.

### Steps to Reproduce the Bug

Try to buy Seed/bandage/snacks/etc. without amount more than 1 entered in to amount box.
Only receive a single item.
Repeat process 500 times to stock up on plant seeds.

### Expected Behavior

Buying stackable items should respect the amount input field.

### Screenshots/Videos

Can provide video if bug is not reproducible.

### Extra Notes (Optional)

Could we please get the ability to quick buy with ctrl+click or right click or something again? having to drag tons of individual items is painful on the wrist.

### Log File

No related log data.

**Comment by xXJamieXx** [comment]
Works fine for me.

**Comment by Ashleyfur** [comment]
Tried purchasing a stack of 10 water bottles and sandwiches at a store. Had to purchase each individually.

**Comment by xXJamieXx** [comment]
Resolved next restart!
