### ISSUE TITLE
[BUG] Can't sell Jewels or Jewelry

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#1097]
### Your Discord Name

Jojos n Mustard#4959

### A clear and concise description of what the bug is

Still unable to sell Jewels or Jewelry to the lady at Vangelico. The box opens to let us(myself and other people I've met) deposit items, but when trying to sell the items it says nothing found to sell.

### Steps to Reproduce the Bug

1: Place Handmade Jewelry items in to the Jewelry sell box .
2: Talk to the jewelry lady and click Sell Items
3: Stuff doesn't sell.
4: Remove jewelry from jewel sell box.

### Expected Behavior

To be able to sell Jewels and Jewelry.

### Screenshots/Videos

None

### Log File

No applicable F8 or Log output.

**Comment by JnKTechstuff** [comment]
This remains unconfirmed as I just sold 10 diamond necklaces fine.

**Comment by SpiceF0x** [comment]
I can confirm this in live 👀  I think logs are useless, but I've included. 

https://streamable.com/6u66xd

[CitizenFX_log_2023-01-29T133155.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10530211/CitizenFX_log_2023-01-29T133155.log)
