### ISSUE TITLE
[BUG] Hair disappearing 

### ISSUE THREAD

**Issue by Bloobe** [ParadoxGamingRP/bugs-and-suggestions#1099]
### Your Discord Name

Booty Sniffa #0563

### A clear and concise description of what the bug is

I just got tats in server and my hair has started to bug out, im not sure if they are correlated but it happened right after I got the tats and cant seem to figure out a fix for the hair. 

https://gfycat.com/InsignificantFaithfulHochstettersfrog

### Steps to Reproduce the Bug

Use hair style 73
Add tattoos to character

### Expected Behavior

Half of the hair will disappear with seemingly no fix.

### Screenshots/Videos

https://gfycat.com/InsignificantFaithfulHochstettersfrog

**Comment by Bloobe** [comment]
Or even if its possible to get a refund on the tattoos and I can remove them would be nice, they were around 5k

**Comment by JnKTechstuff** [comment]
This should be fixed now

**Comment by JnKTechstuff** [comment]
Fixed
