### ISSUE TITLE
[BUG] Garage Issues.

### ISSUE THREAD

**Issue by LitrlyD3ad** [ParadoxGamingRP/bugs-and-suggestions#1108]
### Your Discord Name

D3ad#2545

### A clear and concise description of what the bug is

When trying to park a vehicle in the Davis/MRPD pd parking it doesnt allow me to with certain vehicles, it acts as though there is no parking at that location. As of now it seems only to be happening with one vehicle i have, my Porsche 911. Any other vehicle works just fine. i am also able to park the 911 in any other parking spot such as public ones and the parking spot at my house

### Steps to Reproduce the Bug

1. Clocked onto PD
2. have a 911
3. go to park it in the parking lot
4. nothing happens, no option to park vehicle

### Expected Behavior

Being able to park it.

### Screenshots/Videos

Will add a video/ss shortly

**Comment by LitrlyD3ad** [comment]
Add Townhall garage to the list of places i cant park the car

**Comment by ithegreatgatsby** [comment]
Give me more details on this. Photos etc of placement of the cars when you try to park or able to park.  We had no other reports of anything related to this

**Comment by LitrlyD3ad** [comment]
Ill send them tomorrow, it seems to only be happening with ONE car, the porsche

**Comment by LitrlyD3ad** [comment]
https://i.imgur.com/e5D4nf6.jpeg
https://i.imgur.com/4o4xK65.jpeg
https://i.imgur.com/POaweav.jpeg
https://i.imgur.com/0RDkeg3.jpeg

Both of these cars are owned by me, and located in the same spot. this is the same result i get at MRPD, and the TownHall

**Comment by LitrlyD3ad** [comment]
Same result at SPD as i get with MRPD and DPD
https://i.imgur.com/kbuHttq.jpeg
https://i.imgur.com/Te4wquY.jpeg

**Comment by LitrlyD3ad** [comment]
At first i assumed it might have been a issue with WL parking spots but below is going to be for 10-42, this location works fine.
https://i.imgur.com/zOdMVs0.jpeg
https://i.imgur.com/FZxSbfu.jpeg

**Comment by ithegreatgatsby** [comment]
its just that car?

**Comment by LitrlyD3ad** [comment]
> its just that car?

Correct, ive tried all spots with another personal vehicles and they work without issues.

**Comment by JnKTechstuff** [comment]
Something is wrong in the vehicle config

**Comment by LitrlyD3ad** [comment]
I can also park this at other peoples houses i have keys to, so it seems to be exclusively public safety parking spots
