### ISSUE TITLE
[BUG] Weapon Degradation

### ISSUE THREAD

**Issue by BrotherDayZ** [ParadoxGamingRP/bugs-and-suggestions#1115]
### Your Discord Name

BDZ#0001

### A clear and concise description of what the bug is

Guns are no longer degrading over time making gun cleaning kits useless. 

### Steps to Reproduce the Bug

1. Have gun
2. Gun dont get dirty
3. Dont need gun cleaning kits

### Expected Behavior

Degrade over time so there is a need for gun cleaning kits.

### Screenshots/Videos

N/A

**Comment by JnKTechstuff** [comment]
You sure? My stuff seems to be going down

**Comment by BrotherDayZ** [comment]
Yes, had my Sig for a week and it was staying at 3% the whole week. My AK and AP Pistol dont seem to be going down either

**Comment by JnKTechstuff** [comment]
Fixed
