### ISSUE TITLE
[BUG] <losing harvested items when your inventory slots are full>

### ISSUE THREAD

**Issue by xXvolcanoXx** [ParadoxGamingRP/bugs-and-suggestions#1117]
### Your Discord Name

volcano#3927

### A clear and concise description of what the bug is

harvest a cocaine plant when your inventory slots are full so because cocaine doesn't stack up you will lose the cocaine and you wont get notified that your inventory is full because the inventory is not full , only the slots are 

### Steps to Reproduce the Bug

1. harvest a cocaine plant 
2. if yout inventory slots are full you will get nothing

### Expected Behavior

1. harvest a cocaine plant 
2. if your inventory slots are full drop the harvested coca leave on the ground and get notified 

### Screenshots/Videos

..

### Extra Notes (Optional)

when it happened to me my recorded was off and it takes an hour to grow a cocaine and you need to fill all your inventory slots to reproduce the bug so i didn't record it

**Comment by JnKTechstuff** [comment]
Grinder problems huh
