### ISSUE TITLE
[BUG] <cocaine table processing bugged >

### ISSUE THREAD

**Issue by xXvolcanoXx** [ParadoxGamingRP/bugs-and-suggestions#1118]
### Your Discord Name

volcano#3927

### A clear and concise description of what the bug is

mainly after you wash your cocaine leaves with gasoline and it dry out if you try to process it in the coca table it says "no plants to break down" take a soft nap it will work correctly but if u use 1 dry coca leave that dried before the nap and 9 coca leaves that dried after the nap it will give back 10 cured coca leaves instead of 100 and take away all 10 dry coca leaves 

### Steps to Reproduce the Bug

1. grow a cocaine 
2. wash it in gasoline
3. process the dry leaves in cocaine table 
4. the table acts like the cocaine is not dry 
5. take a nap 
6. process it again it will work but don't use the cocaine that dried after the nap or you will lose it

### Expected Behavior

1. process dry cocaine leaves 
2. get cured cocaine leaves 

### Screenshots/Videos

https://youtu.be/hJ7utW7OnxM

**Comment by Tobjaks** [comment]
I had the same issue yesterday. It gave me 18 cured coca leaves from 20 plants.

**Comment by JnKTechstuff** [comment]
Either this was fixed already or I am unable to replicate; multiple times with different variables.
