### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by xPorscha** [ParadoxGamingRP/bugs-and-suggestions#1123]
### Your Discord Name

Porscha#5395

### A clear and concise description of what the bug is

When planting cocaine plants, i am waiting until they reach 100% growth and 100% health and they are coming out at a purity of, the lowest being 36% and the highest being 75%. wasn't sure if this is something that is to do with the update or if its something that im doing wrong. 

### Steps to Reproduce the Bug

grow a cocaine plant. 
harvest it when it reaches 100% growth and health

### Expected Behavior

to get 100% purity and the bonus reward. 

### Screenshots/Videos

https://i.imgur.com/asIMlwt.png
https://i.imgur.com/nih0XBN.png
https://i.imgur.com/AbvDqIj.png

### Log File

[CitizenFX_log_2023-02-02T014933.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10568541/CitizenFX_log_2023-02-02T014933.log)

**Comment by JnKTechstuff** [comment]
Fixed next restart
