### ISSUE TITLE
[BUG] Fertilizer cannot be applied to plants

### ISSUE THREAD

**Issue by cararedragos** [ParadoxGamingRP/bugs-and-suggestions#1125]
### Your Discord Name

Drake#8286

### A clear and concise description of what the bug is

Once a can of Plant Fertilizer is empty, new fertilizer can no longer be applied to plants

### Steps to Reproduce the Bug

1. Have multiple Plant Fertilizers in your inventory
2. Plant several plants (cocaine in my case)
3. Fertilize the plants until one Plant Fertilizer from the inventory is empty 
4. Try to use fertilizer again (from one of the other Plant Fertilizers left in your inventory)

### Expected Behavior

User should be able to apply fertilizer until all the Plant Fertilizers in his inventory are empty.

### Screenshots/Videos

https://youtu.be/KIJD5W09baw

https://youtu.be/JNb_ONvs95M

### Extra Notes (Optional)

I saw the changelog regarding farming, but didn't notice anything about a fertilizer cooldown. Please let me know if this is intended as well, and how it works exactly if that's possible. Although, if it is intended, it should prompt a message like "you cannot use this item yet" when trying to use it.

**Comment by Darahz** [comment]
This should be fixed already
