### ISSUE TITLE
[BUG] crafting bench not showing blueprints

### ISSUE THREAD

**Issue by saberontop** [ParadoxGamingRP/bugs-and-suggestions#1126]
### Your Discord Name

saber#2860

### A clear and concise description of what the bug is

the crafting bench at 590 wont open

### Steps to Reproduce the Bug

1. open the crafting bench
2. see no recipes

### Expected Behavior

the crafting bench wont show any recipies

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/TspDqVQol_1RA/d1337YHag7OH?invite=cr-MSw0dHgsMjYwODE0NjYs

**Comment by madsskyy** [comment]
i'm having the same issue.
![FiveM® by Cfx re - Paradox Gaming RP _ 4+ years _ discord gg_paradoxgaming 2_2_2023 9_06_38 PM](https://user-images.githubusercontent.com/103598492/216495660-8b69766e-2b64-44ff-884f-39b569b9897c.png)
[CitizenFX_log_2023-02-03T010114.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10574962/CitizenFX_log_2023-02-03T010114.log)

**Comment by madsskyy** [comment]
friend is having the same, here's her logs
[Log.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10575003/Log.txt)

**Comment by JayRik0** [comment]
im Having the same Issue 
Here Are the Logs:
![2023-02-03 21_01_24-FiveM® by Cfx re - Paradox Gaming RP _ 4+ years _ discord gg_paradoxgaming](https://user-images.githubusercontent.com/121770162/216710045-345d1bbe-70a6-4973-901c-cee18212411a.png)

**Comment by JayRik0** [comment]
Having the same Problem Here's the logs-
[CitizenFX_log_2023-02-03T204122.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10582811/CitizenFX_log_2023-02-03T204122.log)
