### ISSUE TITLE
[BUG] cant let people in my house

### ISSUE THREAD

**Issue by Dez505** [ParadoxGamingRP/bugs-and-suggestions#1127]
### Your Discord Name

Dez505#1103

### A clear and concise description of what the bug is

if someone wants to enter my house they hit the doorbell i than hit "open Door" inside the house and they cant enter the house.

### Steps to Reproduce the Bug

1. have someone push the doorbell
2. hit "open Door" 
3. the cant enter the house

### Expected Behavior

the player trying to enter the house cant come in the house.

### Screenshots/Videos

https://cdn.discordapp.com/attachments/994353907516059689/1070860224073834506/image.png

**Comment by xXJamieXx** [comment]
Duplicate of #1113
