### ISSUE TITLE
[BUG] Problem with lockpicks

### ISSUE THREAD

**Issue by currysauce8myass** [ParadoxGamingRP/bugs-and-suggestions#1130]
### Your Discord Name

corriehume#6821

### A clear and concise description of what the bug is

so im having issues with the new lock picking system i have spent like 2k on  lockpick because the system is super glitchy i have logged out nothing has changed and ik for sure it isnt my wifi or pc.

when lock picking the red indicator would instantly appear past the white square and the times i would get one by a off chance it would just do it over and over i dont understand why this is happening  but its stressing out to the point i jsut dont want to bother playing   

### Steps to Reproduce the Bug

possibly change the system back to the old system as it worked perfectly fine 
increase the durability on lockpicks to increase the chance of lock picking successfully 

### Expected Behavior

please deal with this issue as soon as possible as it makes it difficult for people to lock pick  

### Screenshots/Videos

i cant seem to get the link or document to attach

**Comment by JnKTechstuff** [comment]
So don't play
