### ISSUE TITLE
[BUG] I'm carrying so many tools

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1131]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

Hi, it's your FAVOURITE bug-reporter, coming to you LIVE yet again from the mines in Los Santos. 
While I have to admit, I've always been strong and working out down at Muscle Beach, I found it very hard to mine while holding both a hammer and a drill. I sometimes do like to challenge myself while doing so, but as you can see, the hammer does absolutely nothing. 
I will soon have spent my entire Slurp&Go paycheck on stone drills using them as hammers. 
Over to you, dev-team! 

### Steps to Reproduce the Bug

Go to mine with all of your expensive tools
Drill in your stone
Use drill as a fucking sledge hammer and beat that shit up like I did with Pretzel the other day.

### Expected Behavior

Hammer the stone with my hammer.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98127638/216675821-2851a054-e2e1-41fb-b38f-2fbb85e54b41.png)

**Comment by Darahz** [comment]
Multitasking tools no more. Thank you for letting us know!
