### ISSUE TITLE
[BUG] It's raining blueprints, halleluljah! 

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1132]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

We are back in the mines, entering the smelter room. We arrive up to the smelting station where the fire is crakling and making the mine EXTREMELY unsafe, unhealthy and so hot. Nontheless - here we are. I love getting blueprints. I love them so much. But I don't love them THIS much. If you get one specific blueprint, it keeps poppin' up every time you smelt. 

Think of the following text in Cascada - Everytime we touch
Everytime I smelt, I get a blueprint
And everytime I drill, I'm hammering too
I can see you are working hard, but my pockets are full
I need your help right now

### Steps to Reproduce the Bug

Get the steel dremmel blueprint while smelting
And get the steel dremmel blueprint
And get the steel dremmel blueprint
And get the steel dremmel blueprint
And get the steel dremmel blueprint
And get the steel dremmel blueprint
Etc.

### Expected Behavior

Idk, Maybe get like 1 or 2. Not 54

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98127638/216685992-bfff1291-48f2-46bf-8784-414d65339090.png)
![image](https://user-images.githubusercontent.com/98127638/216686036-85dbbd79-719a-4b71-9900-3b226bc1f331.png)
![image](https://user-images.githubusercontent.com/98127638/216686067-1104a913-6dd1-4d7d-aae3-fb73f899a6e8.png)

**Comment by emeraldleo1982** [comment]
These blueprints that were left on the ground are showing inside other peoples mines.
