### ISSUE TITLE
[BUG] Gun license smun smicense 

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1133]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

I was just out walking my imaginary parrot on a sunny International Rebecka Black day, when I decided I needed a new bat for my newly found baseball interest that me and my parrot now have. Whilst in there, this gentleman behind the desk offered me to buy whatever weapon he has, including gun. With that being said I must add that I did get my license revoked for allegedly doing a Vangelico robbery. 
Even so, he did not ask to check my license, he just handed me the option to buy his weapons. 

### Steps to Reproduce the Bug

Get license revoked
Pull up to Steve down at ammunition
He gives you everything you want and THEN SUM

### Expected Behavior

Not be able to buy a gun since my parrot snitched on me and getting license revoked.

### Screenshots/Videos

N/A

**Comment by JnKTechstuff** [comment]
Was your license actually revoked? And was it revoked in the same play session as you going to the store

**Comment by SpiceF0x** [comment]
I had mine revoked a month ago and I managed to purchase a gun.

**Comment by SaraLef** [comment]
Eh, yes it was revoked on the 27th by Malfo. Had Evans check it yesterday as well, it said revoked so I handed him my gun that I just bought.

**Comment by SaraLef** [comment]
![lzBF8Tx](https://user-images.githubusercontent.com/98127638/216772604-e0e9e04a-8c83-4694-a5af-870ac4bd5ca6.png)

**Comment by JnKTechstuff** [comment]
Is this still an issue?

**Comment by SpiceF0x** [comment]
Nope, it failed this morning so we all gucci. Not sure why it worked back then :)
