### ISSUE TITLE
[BUG] Digging for Treasure Everywhere

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#1137]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

I can metal detect anywhere, people be leaving treasure chests and all kind of metals all over the place. So much metal scrap was found in South side in the picture.

### Steps to Reproduce the Bug

1. Have a metal detector
2. use metal detector in place where you can metal detect
3. drive to somewhere like south side.
4. get out of car
5. metal detect again

### Expected Behavior

Metal detection back on the beaches.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98053772/216746869-7ee5fbed-b788-4184-84ea-5d39f1e9d7af.png)

**Comment by Darahz** [comment]
No more digging up the pavestone.
