### ISSUE TITLE
[ENHANCEMENT] Be able to put Pearl's cards into my wallet. 

### ISSUE THREAD

**Issue by jplink420** [ParadoxGamingRP/bugs-and-suggestions#1139]
**Your Discord Name**
J_plink#1691

**Describe the annoyance**
I was very happy to find wallets added into the city to hold all of (my own) IDs, however, I would love to also be able to slip my Pearl's Seafood cards into my wallet rather than having to just throw them away, or keep them in an awkward stack in my stash. It'd also be really nice to be able to open up my wallet and show my Membership card when I go to the restaurant! 

**To Reproduce**
[Steps to reproduce the annoyance]
1. Own a wallet with your own (and nobody else's) ID.
2. Open wallet
3. Try to slide my Pearl's Cards into my wallet.
4. Wallet is too small to fit my Pearl's Cards. 

**Requested behavior**
Be able to put Pearl's Seafood cards into my wallet.

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
Understandable if this can not be added for balance reasons, but the cards are quite easy to obtain.

**Comment by Darahz** [comment]
Added to the wallet
