### ISSUE TITLE
[BUG] Notepads dont work

### ISSUE THREAD

**Issue by AndrewFlee** [ParadoxGamingRP/bugs-and-suggestions#1141]
### Your Discord Name

Worst Nightmare #5569

### A clear and concise description of what the bug is

Notepads don't work for me in the city, not sure if it is a me issue or if everyone has this issue, also we have no message indicator still inside the phones, and DMS never gets notified if someone gets a text message, phone issue has been an issue for 4 months I think?
But since that big upstate with the new HUD/Inventory style I've been seeing more bugs recently, I've also bought a new Notepad to see if it'll work but it didn't.

### Steps to Reproduce the Bug

I've been using my Desktop or IRL Phone notepad to Reduce the issue

### Expected Behavior

I expected DMS to be fixed once again and the notepad issue to be resolved not just for me but for everyone in the city.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/117454713/216831630-fd0c9e36-7dcb-48f2-81d7-c8c1d16e1d60.png)
![image](https://user-images.githubusercontent.com/117454713/216831634-bd1ce5c6-3d07-4598-a554-3c08f5797a87.png)

### Extra Notes (Optional)

No further questions 

### Log File

[CitizenFX_log_2023-02-05T143459.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10611551/CitizenFX_log_2023-02-05T143459.log)

**Comment by Darahz** [comment]
Problem is now fixed and is live.
As for the notifications its already been reported in ticket #902
