### ISSUE TITLE
[BUG] Paleto Issues

### ISSUE THREAD

**Issue by D4rkStr1der** [ParadoxGamingRP/bugs-and-suggestions#1146]
### Your Discord Name

D4rkStr1der#3393

### A clear and concise description of what the bug is

In Paleto Bay between postal 3019 and 3020, there is an invisible hill that is causing people to wreck

### Steps to Reproduce the Bug

Im not sure it was just here.

### Expected Behavior

I don't know how to answer this question.

### Screenshots/Videos

![Screenshot 2023-02-07 132746](https://user-images.githubusercontent.com/108428107/217333692-f1be4a00-995d-4175-9860-42b489b1bace.png)
![Screenshot 2023-02-07 132758](https://user-images.githubusercontent.com/108428107/217333737-728a7454-a56a-4770-88ba-1f5a41213a35.png)
![Screenshot 2023-02-07 132806](https://user-images.githubusercontent.com/108428107/217333765-c745b281-aab7-4f91-803f-266f92061d95.png)
![Screenshot 2023-02-07 132813](https://user-images.githubusercontent.com/108428107/217333789-b9136d1b-9d0a-4185-928e-1bc76b61b134.png)

**Comment by ithegreatgatsby** [comment]
fixed next restart
