### ISSUE TITLE
[BUG] Milking cows too much? & pretty much infinite pocket room from local traders.

### ISSUE THREAD

**Issue by dombpw** [ParadoxGamingRP/bugs-and-suggestions#1147]
### Your Discord Name

Brulism#2818

### A clear and concise description of what the bug is

Honestly unsure if this is as intended or not, I just want to put this here so you may be aware.

Whenever you go to milk cows, and properly feed and water them to the acceptable milking level and start to milk them. The purple bar shows up reading "Milking cow" while this is happening you can third eye the cow during that phase and remilk the cows ~8 times. 8 times per 5 cows, then you feed and water them again and you can just do it again. 

Ontop of that whenever you are interacting with any of the local traders, you can carry pretty much infinite weight in your pockets. You can pretty much infinitely milk cows since there is no weight restriction. You can carry upwards of 500 milk cartons on you at a time while running around.

I got 51 milk from a single cow. That times 5 (per cow). Milking each heard 2-3 times. A lot of milk 

### Steps to Reproduce the Bug

1. Go milk a cow
2. Third eye bug and infinite milk
3. Carry as much milk as you want as you are milking.

### Expected Behavior

Not to milk the cow as much as you want and carry an infinite amount of obtained items through NPC traders.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/97014302/217468968-37d1323a-04b1-43e0-a22b-df4c6dd79cd3.png)

![image](https://user-images.githubusercontent.com/97014302/217469668-8140f534-b892-4236-a2ef-fba3410f9598.png)

https://youtu.be/ptWhPyYEIgY 

While you are standing still, you cannot move and you have to wait. but during that waiting time you can just continuously milk your other 4 cows and just continue to stand there and wait.

### Extra Notes (Optional)

Again, Idk if any of this is intentional. but you can also doing it while feeding and watering them. As you are in the first animation just quickly third eye and do the other option and you can bypass the few second wait. 

Also happens whenever you butcher cows and pigs, you can just hold an infinite amount of meat. 

I was told this by someone else, as they felt it probably was not as intended. I informed them it may not be and to just refrain from doing that for the time being.

**Comment by JnKTechstuff** [comment]
Weight stuff needs more investigating

**Comment by dombpw** [comment]
on my end ?
