### ISSUE TITLE
[BUG] "pothole" in paleto 

### ISSUE THREAD

**Issue by OwlCherry** [ParadoxGamingRP/bugs-and-suggestions#1152]
### Your Discord Name

OwlCherry#6969

### A clear and concise description of what the bug is

postal 3019 crosswalk has bushes and dirt roads that are invisible that cant be removed.

### Steps to Reproduce the Bug

drive down paleto blvd and hit pothole

### Expected Behavior

should drive normally

### Screenshots/Videos

https://streamable.com/a33b4z

**Comment by ithegreatgatsby** [comment]
this was fixed liek a day or so ago? Someone else put in a report about it

**Comment by OwlCherry** [comment]
its still broken
