### ISSUE TITLE
[BUG] Diving coral collection

### ISSUE THREAD

**Issue by Dr-Zef** [ParadoxGamingRP/bugs-and-suggestions#1153]
### Your Discord Name

Dr.Zef#5062

### A clear and concise description of what the bug is

![coralbug](https://user-images.githubusercontent.com/124932128/217929573-246e4b47-2e5c-4ea3-bc66-5dfcecca1e84.png)

Your unable to collect corals. I have tried with all the corals at the area and most of them doesn't even have the third-eye pop up but those who have doesn't even work. You can press it but nothing happens.

### Steps to Reproduce the Bug

1. Get diving gear
2. Get to the diving spot 
3. Find corals
4. Third eye the corals and try to collect them 

### Expected Behavior

I haven't done diving before but from what I know it's supposed to start a bar and collect the coral and give it to my inventory.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/124932128/217930129-659d35e9-209a-4205-9ea8-a7f73cbcb20f.png)

### Log File

[CitizenFX_log_2023-02-09T170211.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10701286/CitizenFX_log_2023-02-09T170211.log)

**Comment by xXJamieXx** [comment]
Can't reproduce this.

**Comment by xXvolcanoXx** [comment]
i've seen this bug before 
it spawns extra fake corals so there is some corals you can collect and some of them is fake ,and it happens only in 1 of the diving spots , i'll check it tomorrow and get more details on it
