### ISSUE TITLE
[BUG] <Door Lock Issue>

### ISSUE THREAD

**Issue by CyrusMancini** [ParadoxGamingRP/bugs-and-suggestions#1154]
### Your Discord Name

NtotheJ#3159

### A clear and concise description of what the bug is

The doors to the Reaper's Clubhouse can be accessed by anyone. 

### Steps to Reproduce the Bug

1. Anyone walks up to the door and can unlock it with the E key.

### Expected Behavior

Only members of the MC can unlock the door. 

### Screenshots/Videos

[https://cdn.discordapp.com/attachments/856710271933218817/1073346781955502162/2023-02-09_15-56-16.mkv]

**Comment by xXvolcanoXx** [comment]
same issue happens in prison doors and grove gate but haven't figure out how it happens
