### ISSUE TITLE
[ENHANCEMENT] Beards 

### ISSUE THREAD

**Issue by Martyfly200** [ParadoxGamingRP/bugs-and-suggestions#1155]
Discord Name: Martyfly2005#1123

Hello Paradox Team! This is Martyfly2005 aka Colin McKinley in city and I was wondering if there could ever be a possibility of adding beards into the server as I would like to think it could add more rp to people's story's and it could make it more diverse for characters. I understand if this is not possible, and I think you guys have been doing an amazing job as of recent with cleaning up and fixing a lot of issues within the server. Thank you for your time and keep doing what you guys do!

**Screenshots**
![image](https://user-images.githubusercontent.com/116933716/217941888-476cf6a1-ddaf-41aa-9dc2-c9f13294ad73.png) 
![image](https://user-images.githubusercontent.com/116933716/217942270-a1902d18-3c2d-4936-997e-d23ef35d7c9a.png)

**Comment by ithegreatgatsby** [comment]
closing for now until someone releases better beards or options that replace the current GTA beards and not just make them a clothing item
