### ISSUE TITLE
[BUG] <Ore Smelting Issue>

### ISSUE THREAD

**Issue by AndrewFlee** [ParadoxGamingRP/bugs-and-suggestions#1156]
![Screenshot 2023-02-10 102150](https://user-images.githubusercontent.com/117454713/218128664-b96a25c5-164b-4237-8ffb-cf4ff24ffebb.png)
![Screenshot 2023-02-10 101220](https://user-images.githubusercontent.com/117454713/218126539-b151c7e9-9199-4d7f-bc31-f25ee53af4a7.png)
### Your Discord Name

Worst Nightmare #5569

### A clear and concise description of what the bug is

So when I'm mining ore, and I've cleared majority of the cave, when it's time for me to go smelting after I'm done smelting the items doesn't go into my inventory and I lost almost around 1k- 2k aluminum and iron I get for Finns taxi

### Steps to Reproduce the Bug

After smelting it just doesnt give me the item
nothing much else to it unless if caused but failing a ore or just after smelting

### Expected Behavior

Just fixing the issue so no one else gets they're time wasted spending in the mine working they're ass off for it just to be gone like i had happen to me, but yea.

### Screenshots/Videos

At the top, i've tried both Power Smelt + Normal Smelt

### Extra Notes (Optional)

after im done mining i just stash it now till it gets fixed

### Log File

[CitizenFX_log_2023-02-09T220251.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10703392/CitizenFX_log_2023-02-09T220251.log)

**Comment by JnKTechstuff** [comment]
Literally the least amount of information possible
