### ISSUE TITLE
[BUG] Coke Table Won't Break Down Cocaine Plants

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#1157]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

After Soaking the Plants. they need to be broken down into buds, through the table. Which the table says no plants broken.

### Steps to Reproduce the Bug

1. Get some fully soaked coco plant
2. Put into table storage
3. try to break down plant

### Expected Behavior

Make into buds from the soaked plant.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98053772/218000382-0739966a-9be2-47d4-a753-f2aaaf63b693.png)

**Comment by ithegreatgatsby** [comment]
Doing the correct steps with the correct items it still wont let me in dev

**Comment by tusktheshrew** [comment]
Was doing fully dry coca on the table.
