### ISSUE TITLE
[BUG] Metals disappearing when melted down

### ISSUE THREAD

**Issue by RoseiiNaytool** [ParadoxGamingRP/bugs-and-suggestions#1158]
### Your Discord Name

Roseii#7904

### A clear and concise description of what the bug is

When melting down metals I lost all of them, they don't show up in my pocket, they just disappear. Iron, gold, copper, and aluminum are all doing it.  It's also doing the same thing to jewels when you cut them to use them for jewelry. 

### Steps to Reproduce the Bug

1. Third eye the smelter
2. smelt any ore
3. it takes the ore out but doesn't give you the copper plates, iron, gold, nothing

### Expected Behavior

To get the metal that I smelted

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/Uxm3INb109HAA/d1337LS9FfMF?invite=cr-MSwxYjMsMzY4OTU4NzQs

**Comment by JnKTechstuff** [comment]
I couldn't replicate this no matter how hard I tried

**Comment by RoseiiNaytool** [comment]
And here I thought you fixed it, a lot of people reported the issue but oddly enough it started working right again, at least for me and one other. I'm not sure about the others that had the issues.
