### ISSUE TITLE
[BUG] Accessing pounder trunk

### ISSUE THREAD

**Issue by iitsPantherzTV** [ParadoxGamingRP/bugs-and-suggestions#1159]
### Your Discord Name

iitsPantherz#8933

### A clear and concise description of what the bug is

When trying to access my trunk on the Pounder Truck. It still does not let me access it from ground level. I know there have been a few reports of this and a possible fix. But, I am still unable to access it. 

### Steps to Reproduce the Bug

1. Get a pounder
2. Try to access the trunk

### Expected Behavior

To be able to open the trunk to collect my items

### Screenshots/Videos

https://user-images.githubusercontent.com/89363844/218237450-e45e148b-0a5c-4c0e-a17f-2d6121e3d151.mp4

**Comment by Darahz** [comment]
Works if you stand in the middle of the back wheels

https://user-images.githubusercontent.com/35222814/218253301-87a1efb6-ce82-438f-a0be-7539494d417b.mp4
