### ISSUE TITLE
[BUG] Fertilizer Use

### ISSUE THREAD

**Issue by RoseiiNaytool** [ParadoxGamingRP/bugs-and-suggestions#1164]
### Your Discord Name

Roseii#7904

### A clear and concise description of what the bug is

You are going through 1 1/2 fertilizer for 10 plants at the moment, I put in a bug report about this before and thought that it was fixed but haven't been farming in awhile. 

### Steps to Reproduce the Bug

1. Plant
2. use water
3. use fertilizer
4. repeat

### Expected Behavior

It used to be that you could use one can of fertilizer for several rounds of growing. I'm not sure if this was an intended change or not but I wanted to report the issue again. I don't know how to check old reports that I put in. I'm going to send the same video I did last time because it's doing the same thing. 

### Screenshots/Videos

Picture link:

https://cdn.discordapp.com/attachments/1049113517749456998/1074457579364819124/image.png

Video link: 

https://medal.tv/games/gta-v/clips/SL0ynnwBYA07p/d1337wlaEaEx?invite=cr-MSxZeVcsMzY4OTU4NzQs

**Comment by ithegreatgatsby** [comment]
We might of nerfed it. That seems fair for use.. but if you get me total amount of money put into it and then amount you get back from it. I will adjust

**Comment by emeraldleo1982** [comment]
On this topic, it's 2 full fertilizers for 20 plants, but sometimes it uses more, I'm pretty sure I'm being very careful not to double fert a plant then skip one, but I'm always like 1-2 fertilizer uses short on a 20 plant grow.

**Comment by RoseiiNaytool** [comment]
Nerfing something is fine, but that was a huge nerf for people that go out to grow to make their money. Out of the grows that i have done, it's been 1 1/2 per 10 plants. So for 20 plants that's using 3 fertilizer. That's $1125 for 20 plants at the moment. The number of crops you get varies, it's never the same so I can't give you the total that you would get every time. It is $25.00 per plant when you sale up in paleto. If you go through an actual 20 crops per 1 fertilizer would be fair compared to what it is now, even if it's just by a little. Most people don't have the room to carry more than one in their pocket/trunk at a time and still have room to collect, or put the crops in the truck with the weight of them. And are having to run up to get another one before they have finished growing it. Having to run up and get more when you're plants need them makes the health go down, which in turn means you get less back from it if it cannot be recovered. So you are losing out on that much more money. I'm just reporting what I am getting, as well as a couple others.
