### ISSUE TITLE
[BUG] pd camera zoom causes crash

### ISSUE THREAD

**Issue by x2Andrew** [ParadoxGamingRP/bugs-and-suggestions#1166]
### Your Discord Name

g unit#3667

### A clear and concise description of what the bug is

PD Camera Zooming in causes whole fivem to crash

### Steps to Reproduce the Bug

1 PULL OUT PD CAMERA
2 ZOOM IN
3 GAME CRASH

### Expected Behavior

FIVEM CRASHES

### Screenshots/Videos

https://i.imgur.com/y1oqFrc.png

**Comment by xXJamieXx** [comment]
You expect FiveM to crash? OK LMAO

**Comment by xXJamieXx** [comment]
But in all seriousness, are you running NVE and if so is it up to date. Others have suggested it is fixed on newer NVE versions.
