### ISSUE TITLE
Blueprints not showing up 

### ISSUE THREAD

**Issue by Rac-coder** [ParadoxGamingRP/bugs-and-suggestions#1168]
### Your Discord Name

super raccoon#0863

### A clear and concise description of what the bug is

when I open the table to see my blueprints there's nothing there. I have tried replacing them but even then they don't show and it allows me to use them when in my inventory leading me to believe i don't even have them and the data isn't saving at all. 

### Steps to Reproduce the Bug

1. get a blueprint 
2. use the blueprint 
3.open a bench 
4. not have any blueprints show up 

### Expected Behavior

be able to use my blueprints to make cool things

### Screenshots/Videos

![bp issue](https://user-images.githubusercontent.com/100735667/218889550-11b7062f-e379-4cf3-8a8e-5722b0a8ee01.png)

### Log File

[CitizenFX_log_2023-02-14T235410.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10737839/CitizenFX_log_2023-02-14T235410.log)

Logs after hard logout 

[CitizenFX_log_2023-02-14T235925 blueprints 2.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10737856/CitizenFX_log_2023-02-14T235925.blueprints.2.txt)

**Comment by Rac-coder** [comment]
i know yall probably already know about the bug i just saw there wasn't an open report and the bug is still on going so figured id make one with logs and stuff

**Comment by JnKTechstuff** [comment]
Spent another 1.5 hours trying to replicate this bug and I was unable to still. Its definitely confirmed but I have no information as to what is causing it. 

I do see what the actual error is but I cannot determine what would cause the table to nest 15 times

**Comment by Rac-coder** [comment]
i gotchu is there any specific info i could supply to you ?
