### ISSUE TITLE
Ability to pull duplicate car out of garages[BUG] 

### ISSUE THREAD

**Issue by dombpw** [ParadoxGamingRP/bugs-and-suggestions#1169]
### Your Discord Name

Brulism#2818

### A clear and concise description of what the bug is

You are able to pull the same vehicle out of garages if you just look in the garage through f1 prior to someone else pulling the same car. 

### Steps to Reproduce the Bug

1. Get two people
2. One look in the garage at at a car and the other pull the car out after the one is already looking
3. Have the original one that looked pull the car
4. Have two cars

### Expected Behavior

Not have two cars

### Screenshots/Videos

https://user-images.githubusercontent.com/97014302/218943781-3909fdb5-90cc-4009-8f35-95477473bf2c.mp4

**Comment by JnKTechstuff** [comment]
Always been a thing tbh
