### ISSUE TITLE
[BUG] MINING Spawn to high

### ISSUE THREAD

**Issue by Mac-ceo** [ParadoxGamingRP/bugs-and-suggestions#1170]
### Your Discord Name

mac_ceo#4908

### A clear and concise description of what the bug is

The ore/emerald spawns to high/ in a location which cant be third eyed

### Steps to Reproduce the Bug

1. open up a mine
2. start mining 
3. reach the crossroad cave room and turn left into that room
4. hope a gem doesnt spawn there

### Expected Behavior

low enough to be third eyed

### Screenshots/Videos

![20230215162514_1](https://user-images.githubusercontent.com/103427821/219092323-078efc9f-225c-4692-b9b5-6bb5f0334ce2.jpg)

### Log File

n/a

**Comment by Darahz** [comment]
Ore spawn has now been changed and is live after server restart. Thank you letting us know.
