### ISSUE TITLE
[BUG] Can't pull out cars

### ISSUE THREAD

**Issue by jkaejkae888** [ParadoxGamingRP/bugs-and-suggestions#1171]
### Your Discord Name

jkaejkae888

### A clear and concise description of what the bug is

Cars aren't pulling out the garages just get a script error in the f8

### Steps to Reproduce the Bug

try to a pull a car

### Expected Behavior

car to pull out

### Screenshots/Videos

https://i.imgur.com/L8qBMMR.jpeg

**Comment by Darahz** [comment]
Should be fixed now. Thank you for letting us know.
