### ISSUE TITLE
[BUG] Doors are Not Locking

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#1175]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

I can unlock doors I shouldn't have keys to. I.E. The Nizmos Tuning Shop.

### Steps to Reproduce the Bug

1. Go to a door without a job
2. unlock door with e
3. lock door with e

### Expected Behavior

Only be allowed to unlock and lock doors with the job for it.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98053772/219824631-4723cc82-68e0-4d55-923c-00fd47ada93e.png)

**Comment by JnKTechstuff** [comment]
This is an unrepeatable bug at this time which we don't have any clear leads on
