### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by iitsPantherzTV** [ParadoxGamingRP/bugs-and-suggestions#1177]
### Your Discord Name

iitsPantherz#8933

### A clear and concise description of what the bug is

Coke tables are not Breaking down the coco leaves. I have tried on multiple different days as I was informed that it could just be with flying in and messing up. But, it still does not want to function.

### Steps to Reproduce the Bug

1. Grow coco seeds
2. get coco leaves
3. douse them in gasoline
4. wait for them to dry
5. try to break them down on a coke table
6. and it says "No plants to break down"

### Expected Behavior

To break down into cured leaves for processing

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/89363844/219884127-19026f9b-40a5-47b0-a0fc-9815fcfae564.png)

![image](https://user-images.githubusercontent.com/89363844/219884137-5cdd82dd-905a-4bf3-9111-f7be307ca715.png)

![image](https://user-images.githubusercontent.com/89363844/219884148-5fdf6ed0-4b5e-49e1-b666-cdb8ba4ae4bb.png)

![image](https://user-images.githubusercontent.com/89363844/219884168-b6c066d1-4c2d-48dd-8f6f-00b8b3dc5b22.png)

**Comment by JnKTechstuff** [comment]
Fixed
