### ISSUE TITLE
[BUG] Penelope hates tills

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1180]
### Your Discord Name

Ssara#7821

### A clear and concise description of what the bug is

Reporting to you live from the main bank in Los Santos where the local banker REFUSES to do any paperwork hence to her not opening her deposit box for tills to be dropped in. This b hates her job and wants us to stop going there.
Please force her to take my business tills so I can pay my employees.
Back to you, dev. 

### Steps to Reproduce the Bug

Have a till
Go to Penelope
She SCREAMS BLOODY MURDER THAT SHE HATES PAPERWORK
She refuses to open her deposit box
You are SOL man. 

### Expected Behavior

For her to do her job, that little banana fly.
Just open the damn box, Penelope. 

### Screenshots/Videos

No cause km at work

**Comment by JnKTechstuff** [comment]
While I appreciate you making bug reports lively can you at least keep the "Steps to Reproduce the Bug" in a serious note

**Comment by JnKTechstuff** [comment]
Should be fixed an extra comma was found
