### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Caydenmwalters** [ParadoxGamingRP/bugs-and-suggestions#1181]
### Your Discord Name

CayyWright#5131

### A clear and concise description of what the bug is

NPC will not let the user purchase any crops at the farmers market.

### Steps to Reproduce the Bug

First, locate the NPC at the farmer's market.
Second, use your third eye and click "buy crops."
Afte that, you will notice nothing at all happens.

### Expected Behavior

Typically, I'd expect the NPC to give a GUI on what crops to buy and such, howver upon clicking nothing happens.

### Screenshots/Videos

![FiveM® by Cfx re - Paradox Gaming RP _ 4+ years _ discord gg_paradoxgaming 2_20_2023 6_30_44 AM](https://user-images.githubusercontent.com/125880086/220094608-63ad22f4-da83-45ea-8465-3072af552d18.png)

### Log File

[CitizenFX_log_2023-02-20T104902.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10783937/CitizenFX_log_2023-02-20T104902.log)

**Comment by JnKTechstuff** [comment]
Unable to replicate
