### ISSUE TITLE
[BUG] <Class D low jack reports as House robery>

### ISSUE THREAD

**Issue by M1ngh** [ParadoxGamingRP/bugs-and-suggestions#1186]
### Your Discord Name

Minghee#0876

### A clear and concise description of what the bug is

There was a low jack situation, and it reports it as a 10-43 house robbery instead of 10-16 low jack or a 10-95 about a stolen car

### Steps to Reproduce the Bug

1. criminal starts a lowjack
2. dispatch send a 10-43 call about a house robbery on the lowjack location
3. dispatch send a 10-95 call about a stolen vehicle
4. dispatch send another 10-43 call, house robbery on the lowjack location

### Expected Behavior

1. criminal starts a lowjack
2. Dispatch send a 10-99 call about a stolen vehicle if is a low class lowjack or a 10-16 lowjack call if is a higher class vehicle

### Screenshots/Videos

![FiveM_b2699_GTAProcess_XaNfRHqRDl](https://user-images.githubusercontent.com/107653844/220475590-a68e754c-846d-4218-8020-7a6a70e7dca0.png)
https://medal.tv/games/gta-v/clips/WnH11yqvrTLev/d1337BK6jpQq?invite=cr-MSxjaWksMzgwMzUxODEs

**Comment by xXJamieXx** [comment]
Pushed a fix that likely resolves this but if not them i'm not sure.
