### ISSUE TITLE
Paleto Impound on Strike 

### ISSUE THREAD

**Issue by TeddyNM** [ParadoxGamingRP/bugs-and-suggestions#1188]
### Your Discord Name

TeddyMercury#4685

### A clear and concise description of what the bug is

Paleto Impound will charge you to pull your car out but not actually give you the vehicle. 

### Steps to Reproduce the Bug

1. Go into impound
2. Third eye the guy behind the counter
3. Get robbed of  money
4. Do not receive vehicle

### Expected Behavior

Expected to receive my vehicle after paying my fee but just got left was less money and sadness.

### Screenshots/Videos

na

### Extra Notes (Optional)

was reported in a staff ticket but went and tested it. The other two impounds are working fine just not Paleto

### Log File

[CitizenFX_log_2023-02-22T040504.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10800141/CitizenFX_log_2023-02-22T040504.log)

**Comment by ithegreatgatsby** [comment]
I think something randoms happens that stops impound working for a bit or to the next restart.  If it happens again please make a new report with logs. Thanks

**Comment by TeddyNM** [comment]
I blame Cherry

**Comment by OwlCherry** [comment]
> I blame Cherry

You only blame me cuz I haven't had issues. Lmao
