### ISSUE TITLE
[BUG]  Impound Lot Broken

### ISSUE THREAD

**Issue by Skeletal-KC** [ParadoxGamingRP/bugs-and-suggestions#1189]
### Your Discord Name

Skeletal-KC#0611

### A clear and concise description of what the bug is

The Impound lot (specifically the one in paleto - I'm not sure if the others are also affected) is taking money for the impounded cars but not releasing them.

I went in, payed the $250 twice and didn't get my car back

I also tried with another vehicle that I had in there for $10 and it didn't release that one either.

### Steps to Reproduce the Bug

1. Get vehicle impounded
2. Try to get vehicle out of impound
3. Impound lot takes money
4. Impound doesn't spawn vehicle and vehicle stays in the impound list

### Expected Behavior

I expected to be able to get my vehicle out of the impound lot

### Screenshots/Videos

N/A

**Comment by ithegreatgatsby** [comment]
I think something randoms happens that stops impound working for a bit or to the next restart.  If it happens again please make a new report with logs. Thanks
