### ISSUE TITLE
When opening the boosting laptop you freeze up[BUG] <short description>

### ISSUE THREAD

**Issue by MilesMarvin** [ParadoxGamingRP/bugs-and-suggestions#1194]
### Your Discord Name

MilesMarv#7962

### A clear and concise description of what the bug is

So when you open a boosting laptop to get in queue or for whatever reason. 
After you try to close it.
You are only able to move your mouse nothing else. Also able to use push to talk but that's it.

### Steps to Reproduce the Bug

Open boosting laptop
Exit boosting laptop
Get stuck

### Expected Behavior

Open & closing the boosting laptop without any issues.

### Screenshots/Videos

![image (2)](https://user-images.githubusercontent.com/113292606/221426345-26fea712-e659-4259-9c12-4bca447b2942.png)

### Log File

[CitizenFX_log_2023-02-26T171832.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10834287/CitizenFX_log_2023-02-26T171832.log)

**Comment by JnKTechstuff** [comment]
Fixed
