### ISSUE TITLE
[ENHANCEMENT] MRPD Evidence Room

### ISSUE THREAD

**Issue by Skillz242** [ParadoxGamingRP/bugs-and-suggestions#1198]
**Your Discord Name**
Aidan#1862

**Describe the annoyance**
The Evidence room in MRPD's "interaction zone" is just a lil too small to grab it from the back as well as widening it to the other side would allow for multiple officers to file evidence without a traffic jam being created

**To Reproduce**
1. Walk to back of MRPD evidence room

A. Walk to the other aisle in the evidence room

**Requested behavior**
OMEGA cool Evidence Locker on both sides and all the way back to the wall

**Comment by Darahz** [comment]
Changed the position and size a tiny bit so it can be accessed on both sides of the shelves
