### ISSUE TITLE
[ENHANCEMENT] CID Evidence Locker at Davis PD

### ISSUE THREAD

**Issue by LitrlyD3ad** [ParadoxGamingRP/bugs-and-suggestions#1200]
**Your Discord Name**
D3ad#2545

**Describe the annoyance**
When needing to stash case items in a CID locker i have to drive to MRPD. it smells like patrol and dogs over there. Id like to completely separate myself from the captain (he is mean) and have all my tools I need over at Davis (Which doesn't have a mean captain or smell like dogs).

**To Reproduce**
[Steps to reproduce the annoyance]
1. Need to place something in a case locker for CID
2. Drive to MRPD
3.  do this everyday for the last 4 months

**Requested behavior**
Have a place in Davis for a CID locker. My idea is placing it in the lab room. Picture of possible placement is below

**Screenshots**
https://i.imgur.com/Yq942sj.jpeg

**Additional context**
[Add any other context about the enhancement here]

**Comment by JnKTechstuff** [comment]
A: What the fuck is a "CID Locker"
B: There is a stash place in Davis, look harder
