### ISSUE TITLE
[BUG] PD Repair bench

### ISSUE THREAD

**Issue by erniexhamer** [ParadoxGamingRP/bugs-and-suggestions#1205]
### Your Discord Name

Ernie Hamer#5237

### A clear and concise description of what the bug is

I attempted to repair my glock at the repair bench at MRPD. The bench took my Gun, but at the completion, it showed an unnamed item added to the repair bench list but, i could not take the item back.

### Steps to Reproduce the Bug

1. use repair bench
2. Select weapon to repair
3. Wait for repair completion

### Expected Behavior

Expect to receive my repaired weapon back

### Screenshots/Videos

https://i.imgur.com/vC5zBv9.jpeg

**Comment by Drunkle716** [comment]
Can confirm. Ate my flashlight.
![FiveM_b2699_GTAProcess_C0qpKd6Rjw](https://user-images.githubusercontent.com/100391224/221705644-5414975f-7287-4bac-9409-c807ea186289.jpg)
