### ISSUE TITLE
[BUG] Radial Menu options

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#1209]
### Your Discord Name

Jojos n Mustard#4959

### A clear and concise description of what the bug is

When attempting to access a parking spot to pull or store a vehicle, I'm met by 2 pages of "Repair Vehicle" options.

### Steps to Reproduce the Bug

1: Go to parking spot
2: use radial menu
3: skip past 2 pages of Repair Vehicle to access garage.

### Expected Behavior

Normal Behavior.

### Screenshots/Videos

![Screenshot_22](https://user-images.githubusercontent.com/29337315/221694305-8de69ef6-afc7-490b-a933-9f935431be84.png)

### Log File

No applicable log or F8 data.

**Comment by SpiceF0x** [comment]
Additional Radial Menu error, unable to add garage to newly created house:
![FiveM_b2699_GTAProcess_xpMx60cfD7](https://user-images.githubusercontent.com/96963965/221697477-acf203a4-332d-481d-b745-72071fa5e48f.jpg)

![FiveM_b2699_GTAProcess_V3aLWn3VjL](https://user-images.githubusercontent.com/96963965/221697488-6d1b3bdd-a2dd-445f-ab3e-8faa4ebeaa3f.jpg)

**Comment by xXJamieXx** [comment]
@SpiceF0x should create a separate issue instead of adding multiple issues to the same one.
