### ISSUE TITLE
[BUG] HUD disappearing 

### ISSUE THREAD

**Issue by RoseiiNaytool** [ParadoxGamingRP/bugs-and-suggestions#1210]
### Your Discord Name

Roseii#7904

### A clear and concise description of what the bug is

Emi help me bind hidehud into my f10 since then seeing my hunger, thirst, armor, when I talk, how fast I am going, if I'm belted in, my gas..... they all go in and out with me seeing it. If I pull out my phone or use my 3rd eye it can go away too, though not all the time. It's been going on for about 3 hours now, I already took off the bind but it's still doing it. I have had to restart several times until I realized that if I did hidehud in the T menu then it brings it back for a short time. 

### Steps to Reproduce the Bug

1. I put hidehud into my keybinds f10 form T menu(it started happening after I did that)
2. use phone/third eye/get in or out of a car
3. all of the above goes in or out randomly and can stay for a bit just to disappear
4. errors from f8 are in pictures below

### Expected Behavior

To me able to see my food, armor, drink, speed, belt, etc... and it not disappear anytime I use my 3rd eye, get in and out of a car, or use my phone. 

### Screenshots/Videos

https://cdn.discordapp.com/attachments/1079858869238513686/1079862769647624415/image.png

https://cdn.discordapp.com/attachments/1079858869238513686/1079862902636433510/image.png

**Comment by Darahz** [comment]
Could you re-add these pictures?

**Comment by ithegreatgatsby** [comment]
closing due to no other response
