### ISSUE TITLE
[ENHANCEMENT] Waist Holster Function

### ISSUE THREAD

**Issue by LitrlyD3ad** [ParadoxGamingRP/bugs-and-suggestions#1211]
**Your Discord Name**
D3ad#2545

**Describe the annoyance**
Allow for the Holster in 255 undershirt to be useable so we dont have to have a second holster that works. 
**To Reproduce**
[Steps to reproduce the annoyance]
1. have undershirt 255 put on
2. look really cool
3. get shot
4. try to pull the nines out
5. takes too long
6. dies

**Requested behavior**
Be able to quick pull a firearm when this piece of clothing.

**Screenshots**
https://i.imgur.com/6O0HquH.jpeg
https://i.imgur.com/W2vZIox.jpeg

**Additional context**
[Add any other context about the enhancement here]

**Comment by ithegreatgatsby** [comment]
the way everything is set up and the script works only hoisters in the neck category can work as a working holster
