### ISSUE TITLE
[BUG] Broken business joint recipe - SOTW

### ISSUE THREAD

**Issue by CecilButler** [ParadoxGamingRP/bugs-and-suggestions#1212]
### Your Discord Name

Cecil#1962

### A clear and concise description of what the bug is

i have all the right ingredients in my inventory to craft the mid shelf joints but the name in the recipe looks wonky and wont let me make those joints anymore

### Steps to Reproduce the Bug

grab stuff to roll mid shelf joint 
use crafting table in the middle room
look at the recipe for mid shelf and try to roll some 
stay sober cause the table wont let you roll joints

### Expected Behavior

being able to roll my joints

### Screenshots/Videos

![broken hawick haze](https://user-images.githubusercontent.com/109994121/221722795-eb260886-a55f-4301-8f4e-db59856dfd22.jpg)

### Extra Notes (Optional)

thanks for looking into this folks!

**Comment by ithegreatgatsby** [comment]
fixed next update
