### ISSUE TITLE
[ENHANCEMENT] Dice Roll Limit

### ISSUE THREAD

**Issue by LitrlyD3ad** [ParadoxGamingRP/bugs-and-suggestions#1218]
**Your Discord Name**
D3ad#2545

**Describe the annoyance**
/roll is currently limited to 100 sides. However with the business i am working on id like to host dice nights, Playing a game called "Devils Dice" which requires a 666 sided dice. Not realistic in the slightest but its a surprisingly fun game. 

**To Reproduce**
[Steps to reproduce the annoyance]
1. want to roll for the title of your house
2. can only roll up to 100 sides
3. is sad (and also houseless)

**Requested behavior**
Maybe increase the limit to 1000 sides, as i said its not very realistic but could lead to some fun rp. and id also like to see the message contain how much the person rolled for, for example "Dice rolled 65 | 12" with the first number (65) being how many sides they rolled and the second number (12) being what they landed on, that would help limit possible cheating. this 666 sided dice could also be a item that you carry, only allowing you to roll over 100 if you have that item in your pocket, or something along those lines. 

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by Darahz** [comment]
Made it possible to roll from 1 to 1000. And changed up the text to show "current numer | rolled numer"
