### ISSUE TITLE
[BUG] Gps Disabler not working 

### ISSUE THREAD

**Issue by richard19999** [ParadoxGamingRP/bugs-and-suggestions#1221]
### Your Discord Name

Zeal_Undy#5506

### A clear and concise description of what the bug is

Cannot use gps disabler in boost vehicle 

### Steps to Reproduce the Bug

Go into que for boosting
Get contract. In this case it was a  D class boost.
Lockpick and hotwire vehicle
Get the vehicle up to 60 mph and try to hack
You get a promp that says "Cannot do that in this vehicle"

### Expected Behavior

be able to use disabler in vehicle to get the tracker off

### Screenshots/Videos

n/a

### Log File

[car boosts.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10876390/car.boosts.txt)

**Comment by Tobjaks** [comment]
Same thing happened to me!

**Comment by Ogre-rated** [comment]
![error](https://user-images.githubusercontent.com/96964896/222587081-596313a7-d5eb-46b8-ae2f-15a8691ae2f1.png)

**Comment by JnKTechstuff** [comment]
Fixed in live
