### ISSUE TITLE
[BUG] Blueprints are still fucky

### ISSUE THREAD

**Issue by Weebait** [ParadoxGamingRP/bugs-and-suggestions#1223]
### Your Discord Name

Weeb#5266

### A clear and concise description of what the bug is

Whenever I access the workbench to use my blueprints I see nothing, this is not the case of my blueprints reset as I've gotten new blueprints and attempted to learn them since this has become an issue with no changes to what I can see at the workbench.

### Steps to Reproduce the Bug

1. Attempt to use workbench.
2. Be unable to see anything in it.

### Expected Behavior

Be able to use my blueprints after acquiring them.

### Screenshots/Videos

https://cdn.discordapp.com/attachments/706608087255089182/1080996352265302056/FiveM_b2699_GTAProcess_YZFVW6rqrn.jpg

### Log File

[CitizenFX_log_2023-03-02T233000.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10876780/CitizenFX_log_2023-03-02T233000.log)

**Comment by ithegreatgatsby** [comment]
This in general was fixed a week ago. If you still dont see prints now you will have to reach out to staff to get them back and after that they should save.  Let me know if that dont work

**Comment by Weebait** [comment]
Will do

**Comment by Weebait** [comment]
The issue has been resolved thank you for the help.
