### ISSUE TITLE
[BUG] Sprinter Van fail to load model

### ISSUE THREAD

**Issue by Kromlec** [ParadoxGamingRP/bugs-and-suggestions#1225]
### Your Discord Name

Kromelc#3389

### A clear and concise description of what the bug is

When you attempt to pull a sprinter van out of a garage it fails to pull out and goes straight to impound where you also can't retrieve it. You pay the $550 but no vehicle.

### Steps to Reproduce the Bug

Go to a parked Sprinter van
Pull out van
Van goes poof

### Expected Behavior

Sprinter van should poof into existence 

### Screenshots/Videos

https://i.imgur.com/mbkaLjw.jpeg

### Log File

[sprintervan.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10879162/sprintervan.log)

**Comment by ithegreatgatsby** [comment]
wait for the restart. I pushed a livery update and it might of broke it till then

**Comment by ithegreatgatsby** [comment]
this still a issue?

**Comment by Kromlec** [comment]
Nope, seems to be good to go. Thanks
