### ISSUE TITLE
[BUG] Unable to access clinic storage.

### ISSUE THREAD

**Issue by BreColourful** [ParadoxGamingRP/bugs-and-suggestions#1226]
### Your Discord Name

Bre#5286

### A clear and concise description of what the bug is

Whilst clocked in for clinic no one can access the clinic storage. Restarting the game does not seem to fix this. 

### Steps to Reproduce the Bug

1. Clock on for clinic.
2. Go to the clinic storage and 3rd eye.

### Expected Behavior

Clinic storage should open.

### Screenshots/Videos

N/A

### Extra Notes (Optional)

Other storages work. EMS Storage is accessible.

**Comment by sahiiiie** [comment]
Its the same with the Glizzys storage, I cannot access it at all.
