### ISSUE TITLE
[BUG] The new colour dried the storage!

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1230]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

This lovely Rebecka Black-day we finally got our Slurp&Go truck re-painted. It was a B-E-A-UUUTIFUL job made by Jonnie. However! I think that when he decided to repaint the car, he painted the locks on the storage as well. I just wanted to sling some slushies maaaaan!! So I'm here requesting a new lock on my storage, please.

### Steps to Reproduce the Bug

Take out the truck
Cant access the storage

### Expected Behavior

Open the truck
Access storage

### Screenshots/Videos

Man, I wish, it was a beautiful paintjob. Everybody should see it.

**Comment by ithegreatgatsby** [comment]
This should be fixed

**Comment by SaraLef** [comment]
It is not 
![image-31](https://user-images.githubusercontent.com/98127638/222958766-08898ce3-fc81-47e5-9ecf-6fb7eb976c81.png)
