### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by BBstud44** [ParadoxGamingRP/bugs-and-suggestions#1231]
### Your Discord Name

BBstud27#5956

### A clear and concise description of what the bug is

I go into a friends storage by entering the Locker ID then the password I put something in there then close out of the storage. When i go back into the storage I cant see what I put in there. Also when I put something in there close out and go back in i cant see what i put in there.

### Steps to Reproduce the Bug

1. go into locker by looking up locker ID
2. Put something in there
3. Close locker
4. open locker
5. no one can see anything you put in there they just poofed

1. go into locker by looking up locker ID
2. Take something out
3. close locker
4. open locker
5. the items you took out are still there for everyone

### Expected Behavior

Its expected for the items you take out of the locker to actually come out and not duplicate. It's also expected for the items you put in there to stay in the locker and not pull a Houdini on you

### Screenshots/Videos

NA

**Comment by Darahz** [comment]
Thank you for letting us know! Should be fixed next restart
