### ISSUE TITLE
[BUG] <Missing Animation (atms)>

### ISSUE THREAD

**Issue by tommytwoshotty** [ParadoxGamingRP/bugs-and-suggestions#1232]
### Your Discord Name

tommytwoshotty#0666

### A clear and concise description of what the bug is

When using an atm or the bank teller to access bank account the emote is missing and in the top corner it says invalid emote.

### Steps to Reproduce the Bug

1. Third eye atm or bank
2. Access bank
3. See no animation

### Expected Behavior

Access atm and see animation

### Screenshots/Videos

https://i.imgur.com/Iu4SplK.jpeg

### Log File

[CitizenFX_log_2023-03-05T040612.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10890850/CitizenFX_log_2023-03-05T040612.log)

**Comment by Darahz** [comment]
Thank you for letting us know. It'll be fix after next restart.
