### ISSUE TITLE
[BUG] Business Till Not Depositing

### ISSUE THREAD

**Issue by andythewookie** [ParadoxGamingRP/bugs-and-suggestions#1234]
### Your Discord Name

andythewookie#0798

### A clear and concise description of what the bug is

Tried to deposit business till 03/05 Approx 1800 GMT, Tills reciepts were placed into the deposit box and then attempted to deposit the 3 till reciepts disappeared from the tellers box however checked the business account and no money had been deposited into our account.

### Steps to Reproduce the Bug

1. Head to Bank with till receipts (these have been from individual days takings, spread across 2/3 tsunami's)
2. open tellers business receipt box
3. select to deposit your till receipts
4. check business account if money has correctly deposited

### Expected Behavior

Money should arrive in business account after depositing tills from the Receipts box

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/YcjQru28KJkfe/d1337Kv19IMt?invite=cr-MSxkalMsNDM2ODM0MTQs

### Log File

[bug logs.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10892826/bug.logs.txt)

**Comment by xXJamieXx** [comment]
Pushed a couple tweaks that might fix it but honestly not sure since I can't reliably reproduce the issue.
