### ISSUE TITLE
[BUG] Non-emergency Panic buttons bugged

### ISSUE THREAD

**Issue by pulsevr34** [ParadoxGamingRP/bugs-and-suggestions#1236]
### Your Discord Name

Pulse+#5769

### A clear and concise description of what the bug is

LEO/EMS non emergency buttons are not working atm, when you press it it puts in a call that says "Undefined" in the title and description and puts the undefined call twice. 

### Steps to Reproduce the Bug

1. Press Non-Emergency panic
2. Other LEO and EMS get "undefined" call

### Expected Behavior

The non emergency panic should be telling LEO and EMS what officer is down/where.

### Screenshots/Videos

https://user-images.githubusercontent.com/97071437/223202264-05024480-479b-45dd-9cd3-58759f7bfdc0.mp4

### Extra Notes (Optional)

Can confirm with confidence this is happening with EMS and all LEO

### Log File

[CitizenFX_log_2023-03-06T183039.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10901841/CitizenFX_log_2023-03-06T183039.log)

**Comment by Darahz** [comment]
Just got this tested and its working now. Thank you for letting us know!
