### ISSUE TITLE
[BUG] Boosts un-hackable

### ISSUE THREAD

**Issue by JonnieSlay** [ParadoxGamingRP/bugs-and-suggestions#1237]
### Your Discord Name

yeaaaaa#9829

### A clear and concise description of what the bug is

I attempted to do a C-Class boost today, I accepted the contract, located the vehicle and I started to drive. The usual notification on the phone didn't appear, and at high speeds the vehicle was completely un-hackable. 

On the F8 console, there was a "Script Error" in red which I believe might be related to this bug. 

### Steps to Reproduce the Bug

1. Get a boost contract.
2. Locate the vehicle 
3. Attempt to start the hack 

### Expected Behavior

Expected is once you get into the vehicle, your phone usually comes up and shows you the number of boosts remaining. You hack it and if successful the hack counter goes down. 

### Screenshots/Videos

https://i.imgur.com/S0WuefB.jpeg

### Log File

[CitizenFX_log_2023-03-06T194403.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10902716/CitizenFX_log_2023-03-06T194403.log)

**Comment by richard19999** [comment]
This just happened to me as well. The gps disabler was not working in the A class Kamota we did about 5 minutes ago.
