### ISSUE TITLE
[BUG] F1 repair options everywhere

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1241]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

So my past work with both Automotive and NS Tuner Shop has given me the power and strength to repair my car at my house. I mean, I knew I was good to begin with. But that I got promoted to home mechanic?! I mean YEEEZ, it's an honour! Anyways, I feel like the others might be too jealous of my home repairing (even tho they can do it too) and it doesnt seem fair. 

### Steps to Reproduce the Bug

Have a house or apartment
PULL UP to the garage
Repair

### Expected Behavior

Have a house or apartment
PULL UP to the garage
Park it

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/YuOD83GoeA-a_/d1337t7uDzgo?invite=cr-MSwybDQsNDU3NjU0MzAs

**Comment by tusktheshrew** [comment]
As well as getting multiple repair options in the F1 menu. That follow you wherever you go.
