### ISSUE TITLE
[BUG] Fleeca Bank Trolleys error 

### ISSUE THREAD

**Issue by JonnieSlay** [ParadoxGamingRP/bugs-and-suggestions#1242]
### Your Discord Name

yeaaaaa#9829

### A clear and concise description of what the bug is

Currently the Fleeca Heist bank trolleys are "un grabbable" . I checked F8 and saw a script error which I will attach. 

### Steps to Reproduce the Bug

1. Start a Fleeca heist
2. Get to the back room with the trolleys 
3. Attempt to grab the Gold/Cash piles 
4. No success

### Expected Behavior

Usually you can third eye the trolleys and start picking it up. 

### Screenshots/Videos

https://i.imgur.com/vv0v0QP.jpeg

https://i.imgur.com/4A13Rb6.jpeg

### Log File

[bank trolleys.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10914948/bank.trolleys.txt)

**Comment by ithegreatgatsby** [comment]
should be fixed
