### ISSUE TITLE
[BUG] Not enough radio traffic

### ISSUE THREAD

**Issue by ninzwinz** [ParadoxGamingRP/bugs-and-suggestions#1243]
### Your Discord Name

ninz#5911

### A clear and concise description of what the bug is

Tried to look for a bank truck and kept hearing "not enough radio traffic" from scanner. There are plenty of cops on duty.

### Steps to Reproduce the Bug

1. Hit radio scanner in Sandy/Paleto with plenty of cops around
2. Hear "Not enough radio traffic" on scanner

### Expected Behavior

1. Hit radio scanner in Sandy/Paleto with cops around
2. Find bank truck

### Screenshots/Videos

N/A

**Comment by emeraldleo1982** [comment]
Not a bug, ask around IC.
