### ISSUE TITLE
[BUG] <Issue with pigs>

### ISSUE THREAD

**Issue by AndrewFlee** [ParadoxGamingRP/bugs-and-suggestions#1249]
### Your Discord Name

Worst Nightmare #5569

### A clear and concise description of what the bug is

Today, I went into the farm fields to help G&G get materials, when i stubbled across a bug, when i bought pigs and the pigs acting as cows giving me the option to milk them and actually giving me 3 milk and the giving me 4 pork, when i just bought it and was already at 100%

### Steps to Reproduce the Bug

Buying a pig.
Then milk it.
Turn the pigs into pork.

### Expected Behavior

Fixed, and it goes back to normal

### Screenshots/Videos

![20230310135447_1](https://user-images.githubusercontent.com/117454713/224410062-077795d9-4e1e-4fad-840c-21072e7c8016.jpg)
![20230310135526_1](https://user-images.githubusercontent.com/117454713/224410085-9fa37f07-28ba-497c-82c5-82075f6010f9.jpg)
![20230310135743_1](https://user-images.githubusercontent.com/117454713/224410107-f64458b5-8fc0-4ea7-898f-0c3a29f7ed46.jpg)

### Log File

[CitizenFX_log_2023-03-10T180446.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10945318/CitizenFX_log_2023-03-10T180446.log)

**Comment by ithegreatgatsby** [comment]
Spent about a half hour trying to reproduce this with not outcome and everything was working as it should. Im going to guess that since multiple people was farming yesterday something just randomly scuffed out. Open a new report if anything changes.
