### ISSUE TITLE
[BUG] Bank Heist carts scuffed

### ISSUE THREAD

**Issue by Charby99** [ParadoxGamingRP/bugs-and-suggestions#1250]
### Your Discord Name

Charby99#0124

### A clear and concise description of what the bug is

While doing bank job, Fleeca or Paleto, the carts with money or gold bars on them that accessible as soon as main vault door is opened from hack are scuffed and you are unable to third eye them and take the items on the cart. 

### Steps to Reproduce the Bug

Hack into bank vault and wait for the door to open
Once Vault door opens you are unable to loot the two carts that have either money or gold bars on them.

### Expected Behavior

You should be able to third eye the two carts and collect items from them

### Screenshots/Videos

https://user-images.githubusercontent.com/118241311/224411489-18347725-0a64-4b94-b059-d428631517c7.mp4

### Log File

[CitizenFX_log_2023-03-09T184155.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10945383/CitizenFX_log_2023-03-09T184155.log)

**Comment by ithegreatgatsby** [comment]
Should be fixed
