### ISSUE TITLE
[BUG] Lisa just want to drop the 9's man.

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1253]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

So I went to do some yardwork mkay. And they asked me to blow some leafes or something, man. I said FUCK THAT MAN! THAT IS ELECTRONIC MAN I CANT USE THAT THEY ARE GONNA GUN ME DOWN MAN. 
But for reals - Can't do any work in prison that does not have a prop behind it as you can see in the beautiful movie I worked hard on. 

### Steps to Reproduce the Bug

Start yard work
Get a job on the ground with nothing around it
It's in the air and can't be accessed.

### Expected Behavior

Lose my 9's to all the hard yard work I'm doing

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/Z2H5QuwHcK6LO/d1337wXDGW2Q?invite=cr-MSxUbmcsNDU3NjU0MzAs

**Comment by SaraLef** [comment]
This is also for the jobs in the cells. Havent met this issue with canteen.

**Comment by ithegreatgatsby** [comment]
If u come across others just make a bug report. I fixed this one but there is like 50 zones for the outside job so its hard to test them when u dont get all the zones all the time since its random

**Comment by SaraLef** [comment]
They are everywhere, man. It's legit everyone that doesnt have a prop under or around them. I'll make 50 buygreports if thats what you want, I guess.
