### ISSUE TITLE
[BUG] Selling Plushies through G&G tills

### ISSUE THREAD

**Issue by natashajoan** [ParadoxGamingRP/bugs-and-suggestions#1257]
### Your Discord Name

its_ahsatan#7098

### A clear and concise description of what the bug is

Tried to sell the new plushies through the till, it shows up in the till as the plushie with the price 0, if you add an "extra item" at the price its to be sold at, when it's purchased, it will say -0 in the top right, but actually the price is taken from your bank. The plushie also doesn't go into your inventory and isn't in the till draw. 

### Steps to Reproduce the Bug

1. Place plushie in till
2. Try purchase
3. Item poofs

1. Place plushie in till
2. add extra item
3. purchase
4. -0 is shown on top right
5. Money is actually taken from bank and shown purchased at Glazed & Glorious
6. Item poofs again
7. 

### Expected Behavior

place item in till
purchase for price
money removed and notified as normal
plushie in pocket 

### Screenshots/Videos

N/A

### Log File

[](url)
[CitizenFX_log_2023-03-11T170624.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10949101/CitizenFX_log_2023-03-11T170624.log)

**Comment by ithegreatgatsby** [comment]
done
