### ISSUE TITLE
[BUG] Unable to do any heists

### ISSUE THREAD

**Issue by SpicyWB** [ParadoxGamingRP/bugs-and-suggestions#1259]
### Your Discord Name

Spicy#5426

### A clear and concise description of what the bug is

While attempted to start any of the jobs we are met with the same error in the top right of the screen "too much/little police activity"
We tried Bank truck, Vangelico, Store robbery,and a fleeca all with the same response

### Steps to Reproduce the Bug

1.use a scanner or attempt to smash glass or even hack the vault door
2.get met with the "too much/little activity" error
3.you cannot rob the things

### Expected Behavior

i can rob the things

### Screenshots/Videos

https://i.imgur.com/udcC7Cp.png 
https://i.imgur.com/ad6jf1b.png

### Log File

[CitizenFX_log_2023-03-12T023553.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10950046/CitizenFX_log_2023-03-12T023553.log)

**Comment by JnKTechstuff** [comment]
New system working correctly
