### ISSUE TITLE
[ENHANCEMENT] QOL Idéa - An actual fridge

### ISSUE THREAD

**Issue by Tobjaks** [ParadoxGamingRP/bugs-and-suggestions#1264]
**Your Discord Name**
tobjak#4191

**Describe the annoyance**

After you've been around for a while there's plenty of items you collect throughout the time that you want to keep, there's also collectibles and the day-to-day items that take up a lot of the storage. To the point where you really don't wanna put food in the stash for example. 

Just an idea - If it would be possible to have a "fridge" option where you could store food/drink items.  

Not sure if it's something doable or even wanted/needed, but thought I'd put it in here.

Cheers!

**Comment by ithegreatgatsby** [comment]
As of recent there has been a item added to server to store food items. So will need to figure out how to get that item in server
