### ISSUE TITLE
[ENHANCEMENT] Chopping Cars

### ISSUE THREAD

**Issue by SwickMachine** [ParadoxGamingRP/bugs-and-suggestions#1265]
SwickMachine#6355

At the moment, chopping cars is a very bland and mundane activity in the city. The simple process of... get contract, find car, steal car, drive to one location and the "contact" takes your car an drives off with it.. just seems too simple. There is no chance for any real police interaction besides the initial stealing of the vehicle. Us actually having to break down the vehicles ourselves in discrete (and some not so discrete) locations around the city would lead to some great interactions. Some locations may be hidden in a back alley and some may be right off of a main strip of road. It's a gamble once you take the job. The opportunities of being seen or even caught go up *drastically*.   This would lead to more individuals getting chop shop charges. 

The process would be as follows. 

- Go to contact at the current location (or moved) and receive an email list of 3-5 vehicles. 
- Once you receive this list, a location will be marked on your GPS. This is your "chop spot".
- You and some friends drive around until you have found one or a few of the vehicles. 
- Steal vehicles and make sure not to be seen.
- Drive vehicles to the chop spot. This location will be identifiable by the toolcart (/p trolley) an various other items laying around the location related to chopping vehicles.
- Drive into the designate location and press designated key or f1 menu selection to open all vehicle doors. 
- Begin disassembling vehicle. (This can either be done by just a simple "E" press to /e weld or maybe an item obtainable from a hardware store, other activity around the city. Either a torch or a saw. Tool option would degrade over time)
- Once a specific piece of the vehicle is removed, you would take that part (could be as simple as /e box) and walk it to the toolcart. Once entered into the tool cart, you would be given a random item from the loot pool.
- Continue process until vehicle is disassembled. 
- Once last item is put into the toolcart, the vehicle chassis will despawn. Final items found inside vehicle would be given.
- Read email to see remaining vehicles on list and repeat process. 

Items that could be included would be...
- random food items, snacks from around the city.
- single bags of illicit substances
- lockpicks, tools
- car parts (either same item as now or new, individual car parts to be scrapped.. batteries, oil filters, tires, etc. Special items like catalytic converters, radios/CD players etc. can be sold to an secretive individual somewhere random in the city for small amounts of crypto)

I feel like this would not only give a new, exciting activity to the city but also improve police RP interactions for smaller crimes such as this one. 

- Find car and bring to spot.
![FiveM_b2699_GTAProcess_uBwbFQFWZV](https://user-images.githubusercontent.com/110204569/224795106-72033996-851f-4e4a-916f-b11dca2b4d19.png)

- F1 menu an all doors open. 
![FiveM_b2699_GTAProcess_N3DPeOrbwN](https://user-images.githubusercontent.com/110204569/224795270-4afa1b37-cd27-428f-9407-9c00496ee790.png)

- Dissassemble.
![FiveM_b2699_GTAProcess_fWUo9mM2pw](https://user-images.githubusercontent.com/110204569/224795455-330842ca-4b6b-45bc-8898-95344f26061c.png)

![FiveM_b2699_GTAProcess_0OPZf9ACoX](https://user-images.githubusercontent.com/110204569/224795709-a17e8145-7377-4c79-8bad-bd49a6bbfe92.png)

- Place box into toolbox. Receive an item from loot pool or nothing. 
![FiveM_b2699_GTAProcess_Y04C4P9aoi](https://user-images.githubusercontent.com/110204569/224795797-e37f95a1-d867-4d13-854e-5c69de3d16c1.png)

- Repeat.
![FiveM_b2699_GTAProcess_oZy0zghLed](https://user-images.githubusercontent.com/110204569/224796084-14f005a1-b4a9-4964-8573-66425b98cb0c.png)

![FiveM_b2699_GTAProcess_CpEJyM2tMj](https://user-images.githubusercontent.com/110204569/224796264-f7e94469-61e6-40db-9a5a-466c9c75a36f.png)

- Once final box is placed, vehicle despawns. Profit. 
![FiveM_b2699_GTAProcess_3tRrJxMX1Q](https://user-images.githubusercontent.com/110204569/224797020-204b798a-bf85-4cbd-85f6-7e9a28de3f57.png)

**Comment by emeraldleo1982** [comment]
That would be amazing!
