### ISSUE TITLE
[BUG] Man's stealing all my watches

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1269]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

Went down to my boy to smelt some watches into gold coins. But ths mf is a greedy one. No matter how many watches I give him, he makes sure to only give me one coin back. He takes all my watches right away, makes me wait 300 seconds then ONLY GIVES ME A FUDGING COIN BACK. 
Cheap mf.

### Steps to Reproduce the Bug

Have 2+ gold watches
Smelt them
Get 1 coin back

### Expected Behavior

Smelt 2+ watches and get back 2+ coins

### Screenshots/Videos

N/A

**Comment by Darahz** [comment]
Done some changes to the returns
