### ISSUE TITLE
[BUG] All door keys are broken

### ISSUE THREAD

**Issue by Mac-ceo** [ParadoxGamingRP/bugs-and-suggestions#1276]
### Your Discord Name

mac_ceo#4908

### A clear and concise description of what the bug is

can open a door. Baller gates kildare doors davis pd and pilbox are the locations i tested

### Steps to Reproduce the Bug

1. go to locatio
2. press e on door
3. door opens

### Expected Behavior

Only able to be unlocked by workers

### Screenshots/Videos

https://medal.tv/?premium-invite=mac%20ceo

### Log File

[CitizenFX_log_2023-03-16T100451.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10992380/CitizenFX_log_2023-03-16T100451.log)

**Comment by Darahz** [comment]
Fixed
