### ISSUE TITLE
[BUG] Unable to plant seeds

### ISSUE THREAD

**Issue by RipleyKensignton** [ParadoxGamingRP/bugs-and-suggestions#1278]
### Your Discord Name

Riply.KPlays#8032

### A clear and concise description of what the bug is

Any time im at any field in paleto or grapeseed, It refuse's to let me plant seed, fertilize or water the plants, Please help

### Steps to Reproduce the Bug

I just walk up to the Field and try to plant

### Expected Behavior

that it would plant but no it keeps saying  impossible

### Screenshots/Videos

n/a

### Extra Notes (Optional)

n/a

**Comment by ithegreatgatsby** [comment]
I cant reproduce this.   But try to leave the area and go back and see if that helps.

**Comment by Cordovagc** [comment]
I also was having an issue with this. When I was having the issue it would say unable to plant seed to steep. I would then have to fly out an fly back into the city for this issue to be fixed.
the screenshot that is attached to this post is the logs at which the incident happened.
![Screenshot 2023-03-20 210358](https://user-images.githubusercontent.com/128448932/226518248-a1b81cc8-5db0-4d89-9c08-40f40e616a32.jpg)
