### ISSUE TITLE
[BUG] Bank Truck Scuff

### ISSUE THREAD

**Issue by canno89** [ParadoxGamingRP/bugs-and-suggestions#1279]
### Your Discord Name

Doubleshake#2314

### A clear and concise description of what the bug is

Attempting to do a bank truck, find truck parked on the side of the road, guards standing in the street, with the truck unable to be thermited or robbed.

### Steps to Reproduce the Bug

1. Use Scanner to find bank Truck
2. Traffic was heard and Truck was found
3. Guards Spawned in street with 0 Aggro
4. Truck Unable to be thermited.

### Expected Behavior

For truck to be able to drive away & or interacted with

### Screenshots/Videos

https://cdn.discordapp.com/attachments/1058628549382254632/1086039702089519174/Moments-clip-from-Mar-16-2023.mp4

^ Video

### Log File

[CitizenFX_log_2023-03-16T195229.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10996099/CitizenFX_log_2023-03-16T195229.log)

**Comment by JnKTechstuff** [comment]
Prolly already hit, added removal for already hit trucks
