### ISSUE TITLE
[BUG] Plastic not stacking?

### ISSUE THREAD

**Issue by seatonmyth** [ParadoxGamingRP/bugs-and-suggestions#1280]
### Your Discord Name

seatonmyth

### A clear and concise description of what the bug is

So the bug is to do with fishing, the plastic you get from fishing is fine, but the ones you get from the wooden boxes dont stack in the pile, i contacted support in discord and they have asked me to come here, i have attached a picture from my stash circling the two different piles.

### Steps to Reproduce the Bug

Catch plastic while fishing
catch a wooden box, open it and try putting that plastic with the others 

### Expected Behavior

they will keep seperate 

### Screenshots/Videos

![plastic](https://user-images.githubusercontent.com/128152691/225910874-70c77756-a3ea-4823-979f-a99cd924fcef.jpg)

**Comment by kingtortle** [comment]
If it helps both items have different descriptions and more than just those activities give you the two different types of plastic

**Comment by seatonmyth** [comment]
Then i think i must have an issue because for me they both say "RECYCLE!"
