### ISSUE TITLE
[BUG] Some issue with liverys saving

### ISSUE THREAD

**Issue by iineedmyjuul** [ParadoxGamingRP/bugs-and-suggestions#1282]
### Your Discord Name

pchimpinn#2087

### A clear and concise description of what the bug is

Whenever the BMW F10 M5 is parked and pulled back out it automatically applies the livery on the car.

### Steps to Reproduce the Bug

1. Park the F10
2. Pull the F10 back out

### Expected Behavior

It shouldn't be applying the livery as I never purchased the livery on the car. It began doing this after there was a server update regarding vehicle modifications saving.

### Screenshots/Videos

https://user-images.githubusercontent.com/48487840/226081415-ef6f3e9f-7b6d-49ab-be3f-47eedb195df9.mp4

**Comment by iineedmyjuul** [comment]
All good, just wanted to let you know in case no one had made a report!

**Comment by Darahz** [comment]
Same problem with the Elegy RH7
