### ISSUE TITLE
[BUG] Test drive cars forever

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#1284]
### Your Discord Name

Jojos n Mustard#4959

### A clear and concise description of what the bug is

You can keep the test drive cars as long as you want until it gets impounded/wrecked.

### Steps to Reproduce the Bug

1: Test Drive car.
2: Open Trunk.
3: Get in Trunk.
4: Wait for timer to expire.
5: Drive out backdoor of testing area.
6: Cruise the state/do crime in your unregistered vehicle.

### Expected Behavior

Script takes you back to the car dealership when timer expires even if you're inside the trunk.

### Screenshots/Videos

n/a

**Comment by emeraldleo1982** [comment]
Tried it a 2nd time to confirm, with a different car, and it placed me under the world.

**Comment by Darahz** [comment]
I was not able to reproduce this at all
