### ISSUE TITLE
[ENHANCEMENT] Suggestion

### ISSUE THREAD

**Issue by RipleyKensignton** [ParadoxGamingRP/bugs-and-suggestions#1285]
**Your Discord Name**
Riply.KPlays#8032

**Describe the suggestion**
Hello I've got an Idea that could improve the Apparel Bag & Make it more useful The Idea of the Apparel bag I have in mind 
Would Hold your mask's & hats
Also be able to hold 2 or 3 Outfits  that u choose from instead of constantly having to go back to the apartment to get the exact outfit.

**Comment by emeraldleo1982** [comment]
I feel like that might be too convenient for people running from cops to just hotswap entire outfits on the go.

**Comment by ithegreatgatsby** [comment]
It would create to many things to be able to abuse it and also its a exclusive business item set up to how they wanted it to be
