### ISSUE TITLE
[BUG] Missing Storage and Stuff in Garage

### ISSUE THREAD

**Issue by RoseiiNaytool** [ParadoxGamingRP/bugs-and-suggestions#1289]
### Your Discord Name

Roseii#7904

### A clear and concise description of what the bug is

I went into my garage to continue building the wall I have been working on and nothing was in there. Everything was there yesterday when I logged, including everything in my storage. When I go into decorate mode everything that is in my house under my objects is showing in my garage. 

### Steps to Reproduce the Bug

1. Came into garage
2. everything was gone
3. I went in and out of the garage several times and everything was still gone
4. when I go into my objects everything that is in my house is showing as objects in my garage

### Expected Behavior

To have everything that was in my garage back in there, including everything that was in my storage. 

### Screenshots/Videos

https://youtu.be/_ATyPNttu-A

### Extra Notes (Optional)

No errors showing in F8 menu

**Comment by RoseiiNaytool** [comment]
Just in case anyone else has this issue, though it really sucks to have to redo anything, if yo put the storage back down then everything should still be in it. They also have to rebuild everything that they put down, including walls.

**Comment by ithegreatgatsby** [comment]
anything to do with house decorating is on hold until a new script is made by a third party. No ETA

**Comment by RoseiiNaytool** [comment]
Understandable. will that delete anything that you have built once it goes into place?

**Comment by ithegreatgatsby** [comment]
refer to #841 for all future updates with anything housing/decorating
