### ISSUE TITLE
[BUG] Tattoo lady doesn't want to tattoo me, man

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1290]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

So I was walking down FUDGE Lane where I stumbled upon a tattoo shop. While I looked through the window on some of the beautiful art she had created, I went in and booked myself an appointment. I was directly seated in the chair when she suddenly screamed that I wasn't getting any tattoos, it was gonna hurt like a mother trucker. I told her that I can handle the pain, and to just get on with it! 
She said she has had enough with tattoing and left me in the shop, stole my clothes and ran away.
IE: Went in to shop, pressed E, didn't get a menu and couldnt leave the shop. F8 relog and couldn't open the menu again.
Happened multiple times and I havent been able to add tattoos for a while.

### Steps to Reproduce the Bug

Walk in Tattoo lady on east side - FUDGE LANE, maybe others too
Press E
Do not get a menu
Do not be able to leave the shop.
Relog.

### Expected Behavior

Get some legitness tattoos, man

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98127638/226735125-6e671c12-c137-47ab-b5f3-a2b4543e613c.png)

### Log File

[legitness.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11033417/legitness.txt)

**Comment by ithegreatgatsby** [comment]
cant reproduce this if you are able to get more info when or if it happens again please open a new report thanks
