### ISSUE TITLE
[BUG] Food and drink is weird rn

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1291]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

So I was superhungry, ate some popcorn from Reaper shop and it filled me up well well well, I wasn't even feeling thirsty anymore. THEN like a lightning from a clear sky im dying of thirst.

IE: Eat - it will fill your hunger and fake fill your thirst
Drink - it will fill your thirst and fake fill your hunger
It will also fake reset the other one, making it look like you need to eat / drink. 

### Steps to Reproduce the Bug

Eat or drink
Die

### Expected Behavior

Eat/drink
Live

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/10MG5oZQMZdtDX/d1337xOBqRv3?invite=cr-MSx6TGgsNDU3NjU0MzAs

### Log File

[food.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11039536/food.txt)

**Comment by JnKTechstuff** [comment]
Fixed
