### ISSUE TITLE
[BUG] Bank Eating Till Slips

### ISSUE THREAD

**Issue by Drunkle716** [ParadoxGamingRP/bugs-and-suggestions#1292]
### Your Discord Name

Drunkle716#7571

### A clear and concise description of what the bug is

you go deposit your tills and they don't go in the account.

### Steps to Reproduce the Bug

Deposit a business till
It says you have none.

### Expected Behavior

Deposit a business till
It goes in your acct.

### Screenshots/Videos

none

### Extra Notes (Optional)

[    857828] [b2699_GTAProce]             MainThrd/ PAYCHECK BUG (Job Update)	glazedandglorious	Manager	385
[    858547] [b2699_GTAProce]             MainThrd/ 
[    869500] [b2699_GTAProce]             MainThrd/ 

### Log File

[CitizenFX_log_2023-03-22T214458.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11045151/CitizenFX_log_2023-03-22T214458.log)

**Comment by JnKTechstuff** [comment]
Since apparently people read bug reports and go "let me loose my money too" so this should be fixed now.
