### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by D4rkStr1der** [ParadoxGamingRP/bugs-and-suggestions#1293]
### Your Discord Name

D4rkStr1der#3393

### A clear and concise description of what the bug is

If you have armor equipped when you close the game or softnap (/logout) the armor will disappear.

### Steps to Reproduce the Bug

1. close game
2. /logout

### Expected Behavior

I expected that the armor that I had put on would still be there when I logged back in

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/108428107/227321584-9f38ea67-c14c-47b2-8de3-1894ff987cdd.png)

### Log File

![image](https://user-images.githubusercontent.com/108428107/227321419-b12c5a11-fc46-4763-9bf8-cbf50aa95bcd.png)
![image](https://user-images.githubusercontent.com/108428107/227321436-5c396a1e-9695-4181-bb0e-9098fa582915.png)
![image](https://user-images.githubusercontent.com/108428107/227321459-401983fd-56f5-49f3-96c1-479c361de9a6.png)

**Comment by JnKTechstuff** [comment]
Fixed
