### ISSUE TITLE
[BUG] <short description>

### ISSUE THREAD

**Issue by Zeus608** [ParadoxGamingRP/bugs-and-suggestions#1294]
### Your Discord Name

Zeus608#9355

### A clear and concise description of what the bug is

I went into a coke lab and was unable to leave, my friend couldn't enter it either. I looked at the command log and it says we are getting script errors.

### Steps to Reproduce the Bug

don't go into coke labs

### Expected Behavior

I was expecting to be able to leave the lab.

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/112aZw-4g9os1T/d1337eVEzzU5?invite=cr-MSxWSEwsMTY0MjkxNzE5LA

### Extra Notes (Optional)

soft naps don't work

**Comment by JnKTechstuff** [comment]
Fixed
