### ISSUE TITLE
[ENHANCEMENT] Canis GATOR could use some tune checking.

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#1297]
**Your Discord Name**
Jojos n Mustard#4959

**Describe the annoyance**
Look, I'll happily admit it was overtuned, it had like 10-15mph too much top speed on turbo, and turned like a sports car. But now It has 40 year old brakes, can't take an easy turn at 70, and tops at like 110 on turbo+full upgrade and no passengers. I feel like it should at least be on par with the Draugr's specs for the price. And before someone says "It seats 7 people!" so does the Declasse Granger XL for wayyyy less money.

**To Reproduce**
[Steps to reproduce the annoyance]
1. Buy fancy truck for 90k.
2. Use it for 1 crime.
3. It gets completely gutted.

**Requested behavior**
Maybe something a bit more viable for ~$108k.

**Comment by ithegreatgatsby** [comment]
tested the nerf and its fair for the type of car it is 110 is fine for top speed for a 4x4 car when most other also the price of this car is due to the amount of seats it has and how much it can be abused in general

**Comment by emeraldleo1982** [comment]
What about the lack of brakes, and so little traction that it spins the rear wheels in either direction with the slightest throttle even though it's AWD?
