### ISSUE TITLE
[BUG] Paleto Recycling doesnt work on knife kits

### ISSUE THREAD

**Issue by OwlCherry** [ParadoxGamingRP/bugs-and-suggestions#1301]
### Your Discord Name

OwlCherry#6969

### A clear and concise description of what the bug is

place the knife kit in the recycling and receive no materials for it 

### Steps to Reproduce the Bug

open box

place kit one at a time

click sell

receive nothing

sell again 

no items

### Expected Behavior

should get back materials after recycling 

### Screenshots/Videos

https://i.imgur.com/1Wa5xrA.jpeg

### Log File

[CitizenFX_log_2023-03-25T210013.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11070258/CitizenFX_log_2023-03-25T210013.log)

**Comment by ithegreatgatsby** [comment]
next update
