### ISSUE TITLE
[BUG] Health System - Bleeding really easily.

### ISSUE THREAD

**Issue by xPorscha** [ParadoxGamingRP/bugs-and-suggestions#1307]
### Your Discord Name

Porscha#5395

### A clear and concise description of what the bug is

Since the health system has been changed, every time something minor happens like falling over, hitting a sign post going a mediocre speed or something mild, you start bleeding. This also happens when people tackle you, you start bleeding or sometimes your leg gets fractured. This is costing ALOT of money when we have to go to hospital many times a day and continuously going down over little things. I ride passenger in a vehicle and they headache, crash on my end and i die, or the other way around.  Its really frustrating. Also when i fly out at full health, when i fly back in, im always at 3/4 of health. it just seems like little things that happen to you cause an extreme reaction. You ragboll to get unstuck from a position and you loose help. This also doesn't help when there are no EMS around and we still have to pay the full amount of $250 even if EMS check you in. 

### Steps to Reproduce the Bug

injure your character in a variety of low impact ways. E.g, 

- tackling somebody
-hitting signs and lamposts (not at full speed)

### Expected Behavior

you will start bleeding (you will feel warm blood)
or your leg will fracture. 

### Screenshots/Videos

https://i.imgur.com/WtBzvyi.jpeg

### Log File

[CitizenFX_log_2023-03-26T212659.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11083830/CitizenFX_log_2023-03-26T212659.log)
[CitizenFX_log_2023-03-27T233239.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11083831/CitizenFX_log_2023-03-27T233239.log)
[CitizenFX_log_2023-03-27T233333.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11083832/CitizenFX_log_2023-03-27T233333.log)

**Comment by JnKTechstuff** [comment]
Fixed
