### ISSUE TITLE
[BUG] Not being downed still after crashing/Flying out and coming back in

### ISSUE THREAD

**Issue by BBstud44** [ParadoxGamingRP/bugs-and-suggestions#1308]
### Your Discord Name

BBstud27#5956

### A clear and concise description of what the bug is

If you get downed and either crash or fly out, when you fly back in you will be able to run around like you were never downed but you wont be able to access your inventory or use any of your hotkeys.

### Steps to Reproduce the Bug

1. Get downed
2. Crash or Fly out
3. Fly back in
4. Be able to walk and run around because you aren't physically downed but the system recognizes that you are downed

### Expected Behavior

I expect to fly in downed if i crash or fly out downed

### Screenshots/Videos

N/A

**Comment by Darahz** [comment]
Should not be an issue anymore. Thanks for letting us know
