### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by canno89** [ParadoxGamingRP/bugs-and-suggestions#1312]
### Your Discord Name

Doubleshake#2314

### A clear and concise description of what the bug is

Upon attempting to eat food, the food action occurs, but no benefit is gained and no food is lost. This action also applies to gun cleaning kits and reloading a weapon

### Steps to Reproduce the Bug

1. Attempt to eat food from inventory
2. Food animation occurs
3. No food is consumed or lost from inventory

Same applies to weapon cleaning kit or ammo

### Expected Behavior

Expected food to be consumed and to provide the appropriate effect
Expected weapon cleaning kit to be used and provide effect
Expected Ammo to be reload into firearm

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/102138934/228912003-26eb84f5-def4-4d54-baf5-96d4e03e0dfc.png)

![image](https://user-images.githubusercontent.com/102138934/228912082-a96bab5d-bbf2-4274-8e70-05dac18ecd2b.png)

### Log File

[CitizenFX_log_2023-03-30T164713.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11114114/CitizenFX_log_2023-03-30T164713.log)
[CitizenFX_log_2023-03-30T163906.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11114115/CitizenFX_log_2023-03-30T163906.log)

**Comment by emeraldleo1982** [comment]
Confirmed +3, food animation occurs, but we don't gain hunger/thirst stat, we are however slowly dehydrating and starving to death. Applies to all consumables so far.
