### ISSUE TITLE
[BUG] Possible opperator error

### ISSUE THREAD

**Issue by palex2018** [ParadoxGamingRP/bugs-and-suggestions#1325]
### Your Discord Name

Payton#0002

### A clear and concise description of what the bug is

Water and food machines no longer work.

At PD, I am unable to buy new equipment due to "insufficient funds", however I have the money to cover it in my bank account.

### Steps to Reproduce the Bug

1.Try to access Water/food dispenser
2. No 3rd eye available

1. Attempted to buy any PD equipment
2. "You cannot afford that"

### Expected Behavior

To be able to buy food and water.

To be able to buy PD equipment.

### Screenshots/Videos

N/A

**Comment by JnKTechstuff** [comment]
Do you have cash on you?
