### ISSUE TITLE
[BUG] unlimited hunting bait

### ISSUE THREAD

**Issue by unforgiven8233** [ParadoxGamingRP/bugs-and-suggestions#1326]
### Your Discord Name

Forgotten#6518

### A clear and concise description of what the bug is

you can use a empty bag of hunting bait

### Steps to Reproduce the Bug

1. empty bag of bait
2. use empty bait
3. kill animal that comes

### Expected Behavior

not be able to use empty bait

### Screenshots/Videos

https://www.youtube.com/watch?v=xVqrI7PctNc

**Comment by ithegreatgatsby** [comment]
this should be fixed
