### ISSUE TITLE
[BUG] Unable to do prison jobs

### ISSUE THREAD

**Issue by Bloobe** [ParadoxGamingRP/bugs-and-suggestions#1331]
### Your Discord Name

Fat Dabs#0563

### A clear and concise description of what the bug is

This didnt happen on my first job so it might take a couple of tries, but on my second job one of them was under the table and I couldnt reach therefor lead to me being unable to finish the job. Also someone I was in with said they did not get any time taken off but I personally did not experience this.

### Steps to Reproduce the Bug

Go to prison
Start canteen job
Go through jobs and wait for one to be unreachable or invisible
Might not happen on the first job

### Expected Behavior

You will not be able to do the job.

### Screenshots/Videos

![bugreport](https://user-images.githubusercontent.com/123845058/229310726-a35f460b-b6e3-4e0c-a5c6-c40822fcf17e.PNG)

**Comment by Darahz** [comment]
Jobs is fixed with the new prison update coming up
