### ISSUE TITLE
[BUG] Roger is a thief! 

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1333]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

I went down to Roger at Rogers Salvage & Scrap to see if he wanted some things to recycle. He said sure, and took a looong look at my things. 
I gave him a wrench, advanced lockpick, 2 knifes, a flashlight and a bat. This dude took it ALL and only gave me 3 metal scraps back. If I had my knife still I would've stabbed a b-word, but he stole that shit. 
IE: Recycle, he keeps your things and gives you almost nothing back,

### Steps to Reproduce the Bug

Recycle said items
Roger says SIKE and gives nothing

### Expected Behavior

Recycle said items
Get things back

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/12zbAJpQt6r1dR/d1337udd2Ybw?invite=cr-MSw4N0UsNDU3NjU0MzAs

**Comment by Darahz** [comment]
This issue should now be fixed
