### ISSUE TITLE
[ENHANCEMENT] Update City Handbook

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#1337]
**Your Discord Name**
Jojos n Mustard#4959

**Suggestion**
Some of the rules and general bad etiquette's that we're expected to know about aren't listed in the city handbook, but made in old announcements. I feel like it's not a reasonable expectation for people to have to read and memorize years worth of announcements to know about obscure rules, especially if they're newer people to the city. It just creates an enjoyment barrier for everybody involved.

**Comment by xXJamieXx** [comment]
Not a development suggestion.
