### ISSUE TITLE
[BUG] Local shops are Cash Only

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#1339]
### Your Discord Name

Jojos n Mustard#4959

### A clear and concise description of what the bug is

Can't buy anything from any shops unless you have cash on you.

### Steps to Reproduce the Bug

1: Try to buy item with debit card.
2: Declined card, must pay with cash.

### Expected Behavior

1: Buy item with debit card from local shops.
2: Receive item.

### Screenshots/Videos

n/a

**Comment by JnKTechstuff** [comment]
Debit cards don't exist; this is intended and will remain.

Sorry you have to go to an ATM :)
