### ISSUE TITLE
[BUG] Old tills deposit money into bank account

### ISSUE THREAD

**Issue by Kromlec** [ParadoxGamingRP/bugs-and-suggestions#1340]
### Your Discord Name

Kromlec#3389

### A clear and concise description of what the bug is

When I go to big bank to deposit tills for Bikini Auto there are sometimes old tills still sitting in the box that were previously deposited. It used to just delete them when I would deposit them but lately it has been depositing the till and giving me the money.

### Steps to Reproduce the Bug

Go to big bank and open till deposit box
Old tills are still there 
deposit old tills and watch money go to account again

### Expected Behavior

Old tills should never show up in deposit box once they have been deposited. 

### Screenshots/Videos

Didn't have medal running at the time, will try to grab video next time I pull tills.

### Log File

[bank tills.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11143594/bank.tills.txt)

**Comment by ithegreatgatsby** [comment]
cant reproduce this if you are able to get more info when or if it happens again please open a new report thanks
