### ISSUE TITLE
[BUG] Queueing system or radio scanner troubles

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#1342]
### Your Discord Name

Jojos n Mustard#4959

### A clear and concise description of what the bug is

I finally caught it on recording. The queueing system when using a radio scanner is going straight from "Too much/Little police activity" to "Traffic was overheard about a previous robbery attempt". In the footage below there's a ~12 second window where it transitions, so if it's working properly that means somebody is sitting directly where it spawns (which uhh, how!? it has multiple spawns.) and blowing it open the second it spawns because it doesn't say "Traffic was overheard..." until the doors blow open in my experience.

### Steps to Reproduce the Bug

1: destroy many radio scanners
2: wait for radio static
3: radio static doesn't come

### Expected Behavior

1: use radio scanner
2: find radio static when police are available
3: have a chance at finding a bank truck

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/12WHPJFxJJpnWU/d13377OjxVQK?invite=cr-MSw2U3EsMTUzNDM4NTc5LA

### Log File

[CitizenFX_log_2023-04-04T163047.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11153408/CitizenFX_log_2023-04-04T163047.log)

**Comment by JnKTechstuff** [comment]
Its not a bug what is happening is that the check for police activity is before the cooldown check

So what is happening is there was a bank truck recently then another robbery went off. So it went from not enough cops to cooldown like it should.
