### ISSUE TITLE
[BUG] Giving weapons to others repair them

### ISSUE THREAD

**Issue by D4rkStr1der** [ParadoxGamingRP/bugs-and-suggestions#1343]
### Your Discord Name

D4rkStr1der#3393

### A clear and concise description of what the bug is

Guns repairing themselves 

### Steps to Reproduce the Bug

1. transfer guns between 2 people's inventory. Didn't repair sigs or compact rifles. don't know what other items it does this to. I've heard it does it to watering cans as well.

### Expected Behavior

I expected to hand them a broken gun.

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/138ED85wPzpkOM/d1337Drjjoze?invite=cr-MSxidFYsMTUzNDM4NTc5LA

**Comment by M1ngh** [comment]
Also, PD weapons are not degrading, i repaired mine when the bench was repaired and it instalty repair the firearms and now none of them have dregrade from there
