### ISSUE TITLE
[BUG] When Checking Out Items Duplicated

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#1344]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

When checking out of prison all of my items i got back doubled.

### Steps to Reproduce the Bug

1. Spend Jail Time
2. Get Out Of Jail Time

### Expected Behavior

Gets only one pair of your items back

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98053772/230754477-77468065-760f-4f56-849e-e16ead4681d7.png)
2 art pieces now

### Extra Notes (Optional)

Prison Jobs are also offline.

**Comment by emeraldleo1982** [comment]
+1, this happened to me as well. Got sent to prison with my stuff still in my pockets, checked out and it doubled it.

![](https://cdn.discordapp.com/attachments/355423419078279178/1097359012728688721/image.png)


![](https://cdn.discordapp.com/attachments/355423419078279178/1097360238790852659/image.png)

[CitizenFX_log_2023-04-17T024509.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11245896/CitizenFX_log_2023-04-17T024509.log)

**Comment by ithegreatgatsby** [comment]
cant reproduce this if you are able to get more info when or if it happens again please open a new report thanks
