### ISSUE TITLE
[BUG] Can't Track Which Garage Your Car Is In

### ISSUE THREAD

**Issue by Drunkle716** [ParadoxGamingRP/bugs-and-suggestions#1346]
### Your Discord Name

Drunkle716#7571

### A clear and concise description of what the bug is

When trying to track what vehicle your garage is in, the app does not actually give you a location which makes finding it at a home difficult.

### Steps to Reproduce the Bug

have a car in a garage
hit the track button in your vehicle app
tracks nothing

### Expected Behavior

have a car in a garage
hit the track button in your vehicle app
it gives you direction to the garage

### Screenshots/Videos

![FiveM_b2699_GTAProcess_TzCJ6jYS8Y](https://user-images.githubusercontent.com/100391224/230784600-48fa24b3-9c7c-4245-bcf6-fc63b4d2e309.jpg)

### Log File

[CitizenFX_log_2023-04-09T160354.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11185865/CitizenFX_log_2023-04-09T160354.log)

**Comment by Darahz** [comment]
You can now track your cars!
