### ISSUE TITLE
[BUG] Self Actions not working on F1 menu

### ISSUE THREAD

**Issue by PatrykX904** [ParadoxGamingRP/bugs-and-suggestions#1347]
### Your Discord Name

Help Me Choose A Name#0175

### A clear and concise description of what the bug is

When I try to use the Self Actions on the F1 menu it doesnt let me use it

### Steps to Reproduce the Bug

1. Press F1
2. Try to press Self Actions
3. Doesnt Work

### Expected Behavior

To be able to use Self Actions

### Screenshots/Videos

https://user-images.githubusercontent.com/81855046/230789991-0959f9b4-6dbc-4df8-9f8c-f36477b916c8.mp4

### Log File

[Log.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11186069/Log.txt)

**Comment by xXJamieXx** [comment]
Should be fixed.
