### ISSUE TITLE
[BUG] All Our Tattoos Are Gone

### ISSUE THREAD

**Issue by Drunkle716** [ParadoxGamingRP/bugs-and-suggestions#1348]
### Your Discord Name

Drunkle716#7571

### A clear and concise description of what the bug is

Woke up and they were all gone.

### Steps to Reproduce the Bug

Have tattoos.
Exist today.
They gone.

### Expected Behavior

Have tattoos
Exist today
They are on your body

### Screenshots/Videos

https://i.imgur.com/X887ZJX.jpeg

### Log File

[CitizenFX_log_2023-04-09T225608.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11186646/CitizenFX_log_2023-04-09T225608.log)

**Comment by madsskyy** [comment]
Are they still gone for you? Mine came back after a soft nap.

**Comment by ithegreatgatsby** [comment]
think this was a one off thing. make new report if it happens today
