### ISSUE TITLE
[BUG] Notepads being erased

### ISSUE THREAD

**Issue by Zeus608** [ParadoxGamingRP/bugs-and-suggestions#1349]
### Your Discord Name

Zeus608#9355

### A clear and concise description of what the bug is

I was using a note pad and when I got off of it and back on, it had my friends notes on it and I deleted it and it erased it from his note pad as well.

### Steps to Reproduce the Bug

IDK

### Expected Behavior

Annoyed 

### Screenshots/Videos

N/A

**Comment by Darahz** [comment]
I'm not able to reproduce this. If you experience this again open up another report, and include your logs. Thanks for letting us know.
