### ISSUE TITLE
[BUG] Alright, somebody stole my garage.

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1352]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

So I have a house down at Bay city Avenue 3, and the garage disappeared. I cannot place a new one either. The other garages at the other houses works perfectly. It's been missing for a few days, and for more people than me that have their car parked there. 

### Steps to Reproduce the Bug

Go to my house
See no garage

### Expected Behavior

Go to my house
See garage

(picture for where the garage was placed)

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98127638/230973483-75ee6b67-3881-46c3-972b-816845e27c2d.png)

**Comment by Darahz** [comment]
Problem solved.
