### ISSUE TITLE
[BUG] Garbage Blueprints not working

### ISSUE THREAD

**Issue by StealthyRiot** [ParadoxGamingRP/bugs-and-suggestions#1353]
### Your Discord Name

Stealthy_Riot#9382

### A clear and concise description of what the bug is

Started Garbage job as Normal, after hitting about 3-4 stops I saw the blueprint message appear but it never went into my inventory. I have attached the short clip where it actually occurred. Below log is for the time period the blueprint failed spawn in. 

### Steps to Reproduce the Bug

1. Start Garbage Job
2. Continue route as normal

### Expected Behavior

After completing garbage pickup at the dumpster, blueprint should appear in inventory. It currently does not appear to be working. 

### Screenshots/Videos

https://streamable.com/1rhjp8

### Log File

[CitizenFX_log_2023-04-10T191310.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11194308/CitizenFX_log_2023-04-10T191310.log)

**Comment by Darahz** [comment]
Fix is now live
