### ISSUE TITLE
[BUG] Gas cans not soaking leaves

### ISSUE THREAD

**Issue by BBstud44** [ParadoxGamingRP/bugs-and-suggestions#1357]
### Your Discord Name

BBstud27#5956

### A clear and concise description of what the bug is

I grew cocaine after pulling leaves i went to use my gas can i already had and it said "gas can seems to be empty" so i refueled it and got the same thing so i went and got another one of my gas cans and it did the same thing

### Steps to Reproduce the Bug

1. pull cocaine plant to get dry leaves
2. try to soak leaves in gas and get "gas can seems to be empty"
3. refuel gas can
4. try to soak leaves again get the same message

### Expected Behavior

I expect to be able to soak my leaves in gas when i have a full can

### Screenshots/Videos

[https://i.imgur.com/LoivHMi.jpeg](url)

[https://i.imgur.com/u6v7G4y.jpeg](url)

**Comment by Tobjaks** [comment]
I had the same issue last time I did it. Actually, it's been like that for a long time, for certain people/cans. It works for me if I refuel the can and use it before holstering it. If I holster it and bring it back out, it's empty again and does not work.

**Comment by BBstud44** [comment]
Ya anytime it gets holstered i can no longer soak them but if i soak them right after filling a already full can it works. The issue is just when holstering it
