### ISSUE TITLE
[ENHANCEMENT] Re-Add ability to keep engine running when getting out of a car.

### ISSUE THREAD

**Issue by jplink420** [ParadoxGamingRP/bugs-and-suggestions#1361]
**Your Discord Name**
J_plink#1691

**Describe the annoyance**
Currently, the only way to step out of your car and have your engine stay running when you are outside of the car is to scoot over to the passenger seat and then get out. It looks and feels a bit janky, and also makes keeping the engine running when stepping off of a single-seat vehicle impossible; unless of course you eject yourself out of the vehicle.. Previously, we could hold the exit vehicle button in the driver seat and the engine would stay running. This was especially nice for those cool nighttime car meets, or for a late night traffic stop on PD, being able to keep my headlights and engine on while I have a car pulled over.

**To Reproduce**
1. Want to keep my lights on engine running while I mingle around at a night time car meet, or have a car pulled over in the middle of the desert at night.
2. Have to pull up, scoot over the centre console, and then use the passenger side door to get out of the car to keep my lights and engine running.
3. Look like a bit of a dweeb.

**Requested behavior**
Be able to hold the exit vehicle button to exit my vehicle from the driver seat and not remove the key from the ignition like we could before, rather than having to move to the passenger seat and then get out of the car.

**Comment by ithegreatgatsby** [comment]
I would bring this up in the feedback section of the discord and get community feedback on it but i will close this for now
