### ISSUE TITLE
[BUG] House man is an egotistical soab.

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1368]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

We went up to the house dude Rodney to see if he had any houses he needed cleared. He said SURE, LEMME MAIL YA! I said THANKS ROD-DOD!
We then headed out and waited.. And waited.. Aaand.. You guessed right - waited.
Rod-dod lied and never gave me the contract. Nor did he do it to either of my friends who were also there. 
Rod-dod needs a stern talking to!

IE: Rodney the house guy don't give you a house but lets you wait for his email that never pops up. Happened for all of us who were there.

### Steps to Reproduce the Bug

Talk to Rod-dod. 
Get confirmation that you want a house and to await an email
Get nothing, not even a ping on the map.

### Expected Behavior

Rob a house man. That's all I wanted.

### Screenshots/Videos

No cause Rod-Dod is ugleh enough as it is.

**Comment by SaraLef** [comment]
[roddod.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11261396/roddod.txt)
Forgot the logs man

**Comment by Darahz** [comment]
This problem is now solved. Thank you!
