### ISSUE TITLE
[BUG] Fractional item moving?

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#1370]
### Your Discord Name

Jojos n Mustard#4959

### A clear and concise description of what the bug is

Since today's tsunami, moving items in my pockets seems to be ignoring the Amount, and just moving half of the stack each time I try to move it, until it gets down to 3 then it's 1 item at a time.

### Steps to Reproduce the Bug

1: Move stack of items
2: It only moves part of it

### Expected Behavior

1: Move stacks of items
2: Stack is in new spot

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/15soJJU7sYWxmf/d1337gRPC6wF?invite=cr-MSxleHgsMTUzNDM4NTc5LA

### Extra Notes (Optional)

Also ignores amount when set to 1 instead of 0.

### Log File

[CitizenFX_log_2023-04-19T160243.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11275596/CitizenFX_log_2023-04-19T160243.log)

**Comment by Darahz** [comment]
Unable to reproduce. Splitting the stack works as intended.
