### ISSUE TITLE
[BUG] Rob or shrug?! 

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1371]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

So I was at my job just going on about my day when this Nolan-dude showed up. I told this fave person of mine that he most def should put his hands up so I could rob him and rearrange his pockets (he hates it btw, so just create chaos in his pockets). But my shoulders were more shrugging than helping me rob man. Idk, I don't know a whole lot in life, but I do know that when I for future references rob Nolan, It should also look like I'm not shrugging, but robbing.

IE: Robbing looks like shrugging and doesn't make sense.

### Steps to Reproduce the Bug

Make Nolan (or anyone, but mostly Nolan) put his hands up
Rob
But shrug instead

### Expected Behavior

Make Nolan /or anyone, but mostly Nolan) put his hands up
Rob
Looks like you are robbing

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/15t2M4Tsju1sqj/d1337vdjjYcZ?invite=cr-MSx3ZzIsNDU3NjU0MzAs

**Comment by Darahz** [comment]
This is now live! Thank you for letting us know
