### ISSUE TITLE
[BUG] Metaldetecting queen! 

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1372]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

Yo dudes, whats poppin my guys?! This yo girl Steph reporting live from the surfers second fave place man - THE BEACH! Duuude, I was so stoked heading to the beach today man to clean it up for some turtle hatching bro. And broooo, lemme tell ya. Steph did not get disappointed my dude! Bro, I was walking and people just threw their trash at me instead of the beach LOVE THAT, MAN! 
But dude, I feel like.. Bro this is rad and all, but I need to get going I SEE A TURTLE BABY NOW MAN! STEPH OUT, BRO! /e shaka

IE: Double digging when metaldetecting

### Steps to Reproduce the Bug

Metaldetect
Dig
Dig some more
Get multiple things

### Expected Behavior

Metaldetect
Dig
Get things

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/15yHdtxrOchVwk/d1337LwH7FG9?invite=cr-MSxVQTMsNDU3NjU0MzAs

**Comment by Darahz** [comment]
Redone how the meta detecting is done. Should be coming soon.
