### ISSUE TITLE
[ENHANCEMENT] My joint keep dropping man.

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1373]
**Your Discord Name**
ssara#7821

**Describe the annoyance**
Sah duh. Was rolling up my joint bro, and when I was about to light that shit up I dropped it. I just want it to stay in my mouth man! /e shaka
IE: Make joint prop stick if possible please! 

**To Reproduce**
[Steps to reproduce the annoyance]
1. Do /e joint
2. Take out Joint
3. Joint goes away

**Requested behavior**
I need to have a J man! 

**Screenshots**
[[If applicable, add screenshots to help explain your enhancement]](https://medal.tv/games/gta-v/clips/15yPy9R16seRSM/d1337cdZfG5F?invite=cr-MSwzSEwsNDU3NjU0MzAs)

**Additional context**
Stay rad, dudes!

**Comment by Darahz** [comment]
Fixed. Thank you for letting us know
