### ISSUE TITLE
[BUG] Unable to use the boat purchase menu at the dock

### ISSUE THREAD

**Issue by ShyKitsuness** [ParadoxGamingRP/bugs-and-suggestions#1374]
### Your Discord Name

ShyKitsuness#6811

### A clear and concise description of what the bug is

The bug: Unable to use the boat purchase menu at the dock

As you go to the dock to buy the boat using the "third eye" ALT key clicking on the "vehicle interactions" the menu doesn't show up as meant to and only can see your mouse no movement can be done with the keyboard or press "ESC" Key only way to get out is to end task using task manager 

### Steps to Reproduce the Bug

1. go to the dock
2. "alt key" third eye the boat 
3. click "vehicle integrations"
4. enjoy not being able to move with your keyboard or being able to escape 

### Expected Behavior

i expected to be able to purchase the boat from the docks

### Screenshots/Videos

unable to get video or screen shot of it happening as it randomly fixed it self 

### Log File

[CitizenFX_log_2023-04-21T110939.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11295392/CitizenFX_log_2023-04-21T110939.log)

**Comment by ithegreatgatsby** [comment]
next restart
