### ISSUE TITLE
[BUG] unable to fill boat with fuel or very little amount

### ISSUE THREAD

**Issue by ShyFox77** [ParadoxGamingRP/bugs-and-suggestions#1375]
### Your Discord Name

ShyKitsuness#6811

### A clear and concise description of what the bug is

unable to fill boat with fuel or very little amount 

### Steps to Reproduce the Bug

1. have a jerry can of fuel 
2. procedure to fill boat 
3. check the amount of fuel is going up
4. realise its not going up or it is in very small amounts 

### Expected Behavior

wanted fuel in my boat

### Screenshots/Videos

says video file size is too big i can send it via discord if needed 

### Log File

[CitizenFX_log_2023-04-21T111621.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11295523/CitizenFX_log_2023-04-21T111621.log)

**Comment by JnKTechstuff** [comment]
Make boats have unlimited fuel

**Comment by ithegreatgatsby** [comment]
next restart/update
