### ISSUE TITLE
[BUG] Unlimited ammo/Unable to reload

### ISSUE THREAD

**Issue by DimitriWasTaken** [ParadoxGamingRP/bugs-and-suggestions#1376]
### Your Discord Name

`Dimitri#5992

### A clear and concise description of what the bug is

My gun has max ammo

### Steps to Reproduce the Bug

my gun wasn't shooting so because of that i was trying to load it with ammo but i didnt know how
I put the ammo in my 4 slot and pulled my gun out and spammed it
still couldn't shooot

relogged into the city and the gun was maxed and could shoot

### Expected Behavior

to have the bullets i put in it not max

### Screenshots/Videos

i don't have one

### Log File

I don't have a log file

**Comment by Darahz** [comment]
What kinda gun are you talking about. And what ammo did you try to use?
