### ISSUE TITLE
[ENHANCEMENT] Dilletante DX camera annoyance

### ISSUE THREAD

**Issue by RoguIsAwesome** [ParadoxGamingRP/bugs-and-suggestions#1379]
**Your Discord Name**
rogue#5265

**Describe the annoyance**
When driving the car the camera is placed super high in the air which makes it annoying and just unappealing to drive as a driving car to cruise around the city.

**To Reproduce**
[Steps to reproduce the annoyance]
1. Step into car
2. Camera is placed high
3. Boom camera is placed in the sky 

**Requested behavior**
Maybe if its possible , can the camera be placed lower like a normal car camera placement.

**Screenshots**
![image](https://user-images.githubusercontent.com/114842052/233813121-fd352c53-3005-477e-9452-4670d49de543.png)

**Comment by ithegreatgatsby** [comment]
Made a few adjustments but from what I saw it was not that bad. So if you could send me more photos or feedback after next restart thanks
