### ISSUE TITLE
[BUG] Pay the workers in prison some more? 

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1380]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

I ended up in jail after beating Malfo up allegedly. When I was in there Michael in the canteen had left a note saying that they wont return unless you give them a raise. I went around - couldn't find George, Alex or the last 2 dudes that I do not know the name of either??? Please pay them more, we are starving in here. We get no food and we cannot work. 

IE: Peds are gone from prison.

### Steps to Reproduce the Bug

Go to jail
See no work-peds.

### Expected Behavior

Get away from cops ofc. But if not - 

Go to jail
See work-peds.

### Screenshots/Videos

N/A since they're not there

**Comment by Darahz** [comment]
The guys has been payed! Should be back in
