### ISSUE TITLE
[BUG] Bank truck lockbox issue

### ISSUE THREAD

**Issue by LocoAqua** [ParadoxGamingRP/bugs-and-suggestions#1382]
### Your Discord Name

LocoAqua#5448

### A clear and concise description of what the bug is

When you do a bank truck and get the box and drive around for about 5 minutes it does not unlock or at all for that matter i waited about 15 minutes and got nothing

### Steps to Reproduce the Bug

1 do a bank truck.

2 get the box

3 The box does not unlock nor give you the money

### Expected Behavior

1 do a bank truck.

2 get the box

3 have the box unlock and get the money

### Screenshots/Videos

![](https://cdn.discordapp.com/attachments/1099787811864973332/1099807588754931782/image.png)

**Comment by ithegreatgatsby** [comment]
If this is still a issue please put in another bug report.
