### ISSUE TITLE
[BUG] House robberies a bit squiff

### ISSUE THREAD

**Issue by SpiceF0x** [ParadoxGamingRP/bugs-and-suggestions#1383]
### Your Discord Name

spicedf0x#2127

### A clear and concise description of what the bug is

Problems with the house robbery script:

- Every person is being given the same house
- This means the house shows as empty if you are the 2nd to receive it
- I was in a house, and got kicked when another person requested a robbery - this meant I could not finish the job
- I checked if they received the same house, and they did (yeah noclip!)

### Steps to Reproduce the Bug

1 - Visit the guy
2 - Get a house
3 - Have someone else visit the guy
4 - They get the same house

### Expected Behavior

I'd like the house robbery guy to do his job better and give a variety of houses each night, preferably a different one to each citizen because there's gotta be more than one person who needs robbed

### Screenshots/Videos

There's nothing in logs. Images or videos wouldn't be helpful for this imo but I can grab the video if needed.

**Comment by tusktheshrew** [comment]
Did a house yesterday thought I had the same house. Tried the house next to it and it worked. Kicked me out after a bit. Tried reentering and got stuck. Did a logout and went to legion. After a few moments it brought me back outside the house.

**Comment by SpiceF0x** [comment]
https://i.imgur.com/VPsvL8z.png

- couldn't lock pick here
- occasionally get kicked from a house
- sometimes drawers / etc are 'empty' (ok it by design)
- if someone owns the house, you're unable to rob it

**Comment by xXJamieXx** [comment]
> couldn't lock pick here
worked fine for me

> occasionally get kicked from a house
haven't been able to reproduce this

> sometimes drawers / etc are 'empty' (ok it by design)
by design

> if someone owns the house, you're unable to rob it
how so? I was able to enter an owned house

> ummm this interior didnt load - was in 3010 area
haven't run into this issue myself
