### ISSUE TITLE
[BUG] Armor again..

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1385]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

I don't have the energy for a story so here ya go - short and to the point.
Apply any type of armor. When you take a nap, it gets yeeted to infinity and beyond. Thanos just snaps that shit away. 

### Steps to Reproduce the Bug

Use armor-items
Nap
Wake up without armor.

### Expected Behavior

Use armor-items
Nap
Wake up with armor.

### Screenshots/Videos

N/A

**Comment by ithegreatgatsby** [comment]
this was fixed i think at one point. if not re bug report it please
