### ISSUE TITLE
[BUG] Bodi2 will not hook up to trailers

### ISSUE THREAD

**Issue by LocoAqua** [ParadoxGamingRP/bugs-and-suggestions#1387]
### Your Discord Name

LocoAqua#5448

### A clear and concise description of what the bug is

Use the Bravdo Bohi and try and attach, a trailer it does not attach even though it has a hitch for it to attach but it gives u the camera like its going to but does not

### Steps to Reproduce the Bug

1 get a Bravado Bohi truck.

2 try and attach a trailer.

3 The trailer does not go on but gives u the camera angle like its going too 

### Expected Behavior

1 get a Bravado Bohi truck.

2 attach a trailer

3 it works and goes on 

### Screenshots/Videos

N/A

**Comment by ithegreatgatsby** [comment]
Took a bit to get working but next restart
