### ISSUE TITLE
[ENHANCEMENT] More jobs! 

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1388]
**Your Discord Name**
Ssara#7821

**Describe the annoyance**
Right now the city is in a repetitive mood and I feel like adding maybe a civ job or 5 could help with that. The ideas I was having could be:
Selling hotdogs at the different stands around city to locals. 
Gardener (as in get a house assigned to you where you trim hedges and rake leafs and what not. When it's snow you could shovel that too).  
Pest control where you get assigned a car and a house to clear. 
Life guard where you have to save locals since they are silly and can't swim but will try. 
Limo driver from Cockatoos or somewhere else. 
Construction work at the different construction sites. 

Hopefully some of these will be located in Grapeseed, Sandy or Paleto to get people moving around the island and not just stay in the city.

**Comment by tusktheshrew** [comment]
Oil Drilling for Carbon waste up in Sandy. Bringing the gas to a specific gas station.

**Comment by SaraLef** [comment]
Open up Burger shot to make it a Civ job could also be a possibility.

**Comment by xXJamieXx** [comment]
Jobs have been on the list forever just different priorities and finding time to do it. Not a simple thing to do.

**Comment by JnKTechstuff** [comment]
> Open up Burger shot to make it a Civ job could also be a possibility.

This is actually an idea

**Comment by ithegreatgatsby** [comment]
Gonna close this with the recent add of the pest control job. But there will be others in the works when time allows it.
