### ISSUE TITLE
[ENHANCEMENT] Alcohal effect last longer and become more severe the more you drink.

### ISSUE THREAD

**Issue by PadawanPepsi** [ParadoxGamingRP/bugs-and-suggestions#1390]
**Your Discord Name**
PadawanPepsi#6898

**Describe the annoyance**
It is hard to tell when someone is drinking and it doesn't affect their driving that much. I would find it much more immersive if the effects of alcohol were more severe the more you drink.

**To Reproduce**
[Steps to reproduce the annoyance]
1. Drink alcohol
2.  drive a car
3. 

**Requested behavior**
Driving becomes more erratic and walking becomes more staggered

**Comment by JnKTechstuff** [comment]
They get longer, we tend to avoid this now as it genuinely makes people nauseous
