### ISSUE TITLE
[BUG] Jobs Don't Take Off Prison Time

### ISSUE THREAD

**Issue by Drunkle716** [ParadoxGamingRP/bugs-and-suggestions#1396]
### Your Discord Name

Drunkle716#7571

### A clear and concise description of what the bug is

When you do prison prison jobs, it doesn't take any time off.

### Steps to Reproduce the Bug

Go to prison
Do job

### Expected Behavior

You get some time off for doing jobs.

### Screenshots/Videos

nothing to screen shot

**Comment by xXJamieXx** [comment]
Reducing jail time is not guaranteed.
