### ISSUE TITLE
[BUG] PD Equipment not working when 100% on derability

### ISSUE THREAD

**Issue by unforgiven8233** [ParadoxGamingRP/bugs-and-suggestions#1400]
### Your Discord Name

Forgotten#6518

### A clear and concise description of what the bug is

cant use a new IFAK
cant use a new Remote monitor
can only use items with a durability of 99 or below

### Steps to Reproduce the Bug

1 use a new ifak and it do nothing
2 use a new remote monator and it do nothing

### Expected Behavior

1 use a new ifak and it works
2 use a new remote monitor and it works

### Screenshots/Videos

n/a

**Comment by unforgiven8233** [comment]
sorry new items dont have a durability https://i.imgur.com/4Fge4Bx.png

**Comment by unforgiven8233** [comment]
I relogged and still it does not work https://youtu.be/tSCVXyemC8c

**Comment by xXJamieXx** [comment]
My bad, forgot changes weren't pushed yet.
