### ISSUE TITLE
[BUG] AK Vs PD Ar/Swat AR

### ISSUE THREAD

**Issue by pulsevr34** [ParadoxGamingRP/bugs-and-suggestions#1402]
### Your Discord Name

Pulse+#5769

### A clear and concise description of what the bug is

So as far as I know the ARs and AKs should be the same. It appears the AK in first person has little to no recoil while the AR/SWAT AR has an insane amount of recoil to the point where it's uncontrollable no matter the skill. This has been an issue for a while and its apparent criminals have been using it as an advantage. This is a huge issue for two reasons, 1. Criminals have a severe advantage considering the recoil is less than when they're not aimed in compared to our ARs, 2. When SWAT or regular officers want to use the heli as a height advantage that first-person recoil makes it incredibly hard to shoot from a heli. All I'm asking is the AK finally be ACTUALLY the same as the AR so we all have a level playing field. 

### Steps to Reproduce the Bug

1. Take a AR15b or MK18 and shoot it in first person
2. Take an AK and shoot it in first person
3. huge difference and clear advantage to the AK

### Expected Behavior

Both AR and AK are the same (pay attention to the swat ar too please we use them alot now)

### Screenshots/Videos

https://streamable.com/zpozjg

### Extra Notes (Optional)

The AR and the SWAT AR are the same, PLEASE dont forget to do the swat ar too, we carry them now and use them too, it does matter

**Comment by JnKTechstuff** [comment]
Basically copied the exact config for AR and tuned slightly better
