### ISSUE TITLE
[ENHANCEMENT] Make Fishing Great Again (Low-Priority) 

### ISSUE THREAD

**Issue by jplink420** [ParadoxGamingRP/bugs-and-suggestions#1403]
**Your Discord Name**
J_plink#1691

**Describe the annoyance**
Who doesn't love loading up the truck and going out on a fishing trip? Though, Since it has been added to the city as a hobby/job, fishing has not changed much. It has been the same thing for nearly a year. And while in it's current state, it is fine, I think it could use a bit of a facelift to make it a more attractive job for people to do, as well as increase the amount of interaction and RP you can get out of it, and encouraging your friends to go for a profitable trip out to nature. I have a few ideas on how this could be implemented and balances to counter potential changes.

**Suggestions**
-Slighty increase the payout of illegal fish, with lowered drop rates, while increasing the frequency that Pearl takes your cards. Maybe add a low (5% or so, which really isn't that low considering the amount of illegal fish you can pull) chance that catching an illegal fish will ping cops as a suspicious person (or another appropriate call). This would also give risk to people solely catching illegal fish, as well as give more RP for cops, BCSO specifically, to check fishing permits and check fishing chests for illegal fish, and utilize the "environmental crime" section of the Penal Code more. (This would also make illegal fish more of a bit of "bonus" cash, rather than a main goal for fishing, forcing people to fish for longer if they want more illegal fish, in turn leading to more calls for PD.) Also discouraging people from fishing right nearby the illegal fish buyer.

-Increase the price of fishing bait from $5 to $10 and give fishing rods durability that decreases with a certain amount of attempts to catch fish. 

-Add a more difficult secondary "optional" skill check like with jewelry crafting. First one is to "set the hook", second one is to "reel in", second skillcheck would determine if you get multiple fish from a drop, which would be the purpose of increasing the price of bait. This would also make the job less AFK-friendly. 

-Encourage appropriate businesses to add fish related food items to their menus that utilize legal fish (Think; Koi [Asian-Fusion], Skull Island [Latino], Open Road [American style dive Bar that is right next to a Sea]. We live in a metropolis that is on the coast of a Pacific Island, Fish as a diet staple makes sense. These items would have to use fish, or fish-derived items. (Perhaps you convert one salmon into 2 pieces of raw salmon). With this, decrease the price of legal fish (10-20%) sold to locals to encourage people to sell their fish to businesses.

-Adding on to the previous point; remove the raw fish items from Commercial Imports, add all of the legal fish as an item to GoPostal so businesses can always have a reliable source of fish.

-Give treasure chests a chance to actually have treasure rather than an old soaked business card and some plastic. These treasures could be anything, like jewelry, gems, gold coins, or even maybe an old rusted murder weapon that a local hastily got rid of in the water, like a Knife, Sig, SNS Pistol, etc. (This could either be called in as a 911 call by the fisherman, or, more likely, used in the course of another crime, while being unregistered and untraceable, maybe the serial number of the gun would even be unreadable due to years of sitting in the salty water, increasing it's street value significantly.)

-Yes, there is a lot of plastic in the ocean, and this is a serious issue, both in-game and IRL, but there isn't THAT much plastic in the ocean, clean up the oceans and let me wrap my fish in plastic myself, I don't need every fish pre-wrapped in plastic before I even plan on selling it! (Decrease Plastic drops to discourage people from using fishing solely as a source of plastic.)  

It would be interesting to see more RP brought to fishing, and I think the above ideas would add quite a bit to the job. It would be interesting to hear ideas from other community members.

**Comment by JnKTechstuff** [comment]
I have updated the fishing script to fall in line with your ideas. However, I made it a bit different than you suggested. Try it out and let me know what you think
