### ISSUE TITLE
[BUG] Cant process coke

### ISSUE THREAD

**Issue by PatrykX904** [ParadoxGamingRP/bugs-and-suggestions#1410]
### Your Discord Name

Help Me Choose A Name#0175

### A clear and concise description of what the bug is

So I got to process some coke but after a bit it told me there was no coke to process

### Steps to Reproduce the Bug

1. Put soaked coke in there while when the bar is red
2. Can process some
3. After a bit it doesn't let me process anymore

### Expected Behavior

To be able to process all the coke

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/81855046/236687238-112f9f3c-68d4-43d4-a5ca-e893750d290c.png)
![image](https://user-images.githubusercontent.com/81855046/236687276-75e96532-1582-4e08-a1b3-1950ea9fc8bf.png)
![image](https://user-images.githubusercontent.com/81855046/236687306-59b348f6-4cc8-403b-87db-774b6fec0be8.png)

### Log File

[Log 3.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11415371/Log.3.txt)

**Comment by kingtortle** [comment]
It happens when the coca leaves dry in your pocket next time just take a nap after they are dry and put them in the table it will work.
