### ISSUE TITLE
[BUG] When removing keys it doesnt go away from list.

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1417]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

When removing keys the key it self goes away but its still in the owners list on the phone and still on the keylist of the reciever.

### Steps to Reproduce the Bug

Remove key from someone (Chris Golf in my case)
Person  is not removed from keylist.
Person still has access to the house in the phone, not physical 

### Expected Behavior

Person should be removed from keylist 
Person should not have the house in their keylist

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/18Iiq5sTV4hXK4/d1337D5GUJOO?invite=cr-MSwzNDYsNDU3NjU0MzAs

**Comment by xXJamieXx** [comment]
Just tested this, if you close the app and re-open it should update. Please confirm?

**Comment by SaraLef** [comment]
It did not work for me yesterday, he was still in the list before I gave the key back.
