### ISSUE TITLE
[BUG] Fire is forcing me to put people on stretchers

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1420]
### Your Discord Name

Ssara#7821

### A clear and concise description of what the bug is

Whenever fire is on and available something they are doing is forcing everyone to load people on stretchers. It's just not me and it's only when fire is around. 

### Steps to Reproduce the Bug

Exist when fire is clocked on
Load patient on to stretcher which is cancelling anything you're doing. 

### Expected Behavior

Not to load patient on tk stretcher since I'm not ems. 

### Screenshots/Videos

N/a cause I'm on phone but can grab tmrw.

**Comment by xXJamieXx** [comment]
Was just an artifact of testing the script.
