### ISSUE TITLE
[BUG] Phone not saving photos

### ISSUE THREAD

**Issue by BlazinNut** [ParadoxGamingRP/bugs-and-suggestions#1421]
### Your Discord Name

Blazin Nut#1776

### A clear and concise description of what the bug is

Try to take a picture on phone and wont save photo and will have a red message. Multiple peaople have said it including Jon Cord

### Steps to Reproduce the Bug

1. Pull out phone
2. Take a photo
3. No save photo bad

### Expected Behavior

The phot Saves

### Screenshots/Videos

![20230516173935_1](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/130942230/71f87f99-1726-4be1-b38c-289ed1f07f9b)

### Extra Notes (Optional)

N/A

### Log File

N/A

**Comment by JnKTechstuff** [comment]
Blame imgur
