### ISSUE TITLE
[BUG] Can't view/buy a boat

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#1423]
### Your Discord Name

Jojos n Mustard#4959

### A clear and concise description of what the bug is

Can't buy or view one of these super awesome boats without your brain melting.

### Steps to Reproduce the Bug

1: Go to Marina
2: Third Eye Boat
3: Brain freezes and needs hard nap

### Expected Behavior

Be able to buy boat.

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/29337315/301927ac-b147-4980-a206-1d9af49c084f)

**Comment by ithegreatgatsby** [comment]
next restart
