### ISSUE TITLE
[ENHANCEMENT] /swat command for swat officers

### ISSUE THREAD

**Issue by pulsevr34** [ParadoxGamingRP/bugs-and-suggestions#1425]
**Your Discord Name**
Pulse+#5769

**Describe the annoyance**
With the current way SWAT works, we sometimes need to activate in risky situations quickly and don't have time to go down to the station to grab our gear. We'd love a way to get outfits from the back of cars restricted to swat with a /swat command like 2.0 or a new way if you can think of a better one, preferably the way to do this would just have your outfit locker open instead of a preset outfit for customizability sake. 

**To Reproduce**
N/A

**Requested behavior**
/swat opening a locker at the back of officers' vehicles (or anywhere but have strict guidelines on where we can use the command)

**Screenshots**
N/A

**Additional context**
N/A

**Comment by unforgiven8233** [comment]
or make it so when your trunk is open you can change into any of your outfits

**Comment by pulsevr34** [comment]
Keeping the suggestion to SWAT to prevent abuse, no reason to have an entire locker of outfits in the back of your trunk unless you need tac gear.

**Comment by unforgiven8233** [comment]
cid or other officers swiping to and from under cover outfits in a quick scene is one other thing it could be used for

**Comment by xXJamieXx** [comment]
Was added to F1
