### ISSUE TITLE
[ENHANCEMENT] Prominent Cigar/Cig Emotes 

### ISSUE THREAD

**Issue by LitrlyD3ad** [ParadoxGamingRP/bugs-and-suggestions#1428]
**Your Discord Name**
D3ad#2545

**Describe the annoyance**
Currently we have emotes that we can do that will place a item in your mouth (IE Cigar Cigarettes) that you can do with their respective /e's, when you do it however if you unlock/lock or do really any other emote it poofs the cigar away and you have to redo the emote to bring it back, for characters that have these accessories as a large part of their character it can be pretty annoying to constantly do /e's to place the cigar back over and over. 

**To Reproduce**
[Steps to reproduce the annoyance]
1. do a prop emote like /e cig/cigar/cigar2/smoke3
2. unlock a car/door/or really any other emote
3. cigar poofs
4. redo step 1
5. repeat

**Requested behavior**
make the props stick a bit more prominent, bypass other emotes and make it so the only real way to remove them is by pressing X or another way such as a command.

there is a really clean cigar emote that we just recently got, smoke3, it has a cigar with a smoke effect attached. its super clean and i think making it stick a bit better would just put it over that edge and make it a go to for peoples characters (it would also play nicely with my cigar related biz im trying to start).

**Screenshots**
I can supply a recording on command if needed however i dont have one on hand at this time.

**Additional context**
[Add any other context about the enhancement here]

**Comment by Darahz** [comment]
This should be good now!
