### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by saberontop** [ParadoxGamingRP/bugs-and-suggestions#1429]
### Your Discord Name

saber#2860

### A clear and concise description of what the bug is

The mask number 178 makes you bald unless you have modded hair 

### Steps to Reproduce the Bug

put on the mask 
have vanilla gta hair

### Expected Behavior

it will just make you bald 

### Screenshots/Videos

https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/124313620/0cb143de-ba60-4107-ab5e-1644c5bd9438

**Comment by saberontop** [comment]
sorry about the clip length, i couldnt cut it skip towards the end to actually see it happen :)

**Comment by JnKTechstuff** [comment]
Thats a GTA bug not us
