### ISSUE TITLE
[BUG] The Prison jobs are removing too much time, too fast off the sentence

### ISSUE THREAD

**Issue by Ogre-rated** [ParadoxGamingRP/bugs-and-suggestions#1435]
### Your Discord Name

OgreRated#9309

### A clear and concise description of what the bug is

the jobs inside the mess hall are extremely fast right now and take too much time off the sentence of the inmate. An inmate got sent for 40 min and was able to be released in under 10. 

Ideally, I would like it to be if you did the jobs your time should be cut in half of what you were sent for. If I was sent for 30 months then 15 min of labor I can get released. 

I am unsure if it is just mess hall jobs or outside jobs too. But the mess hall is where I noticed it. 

### Steps to Reproduce the Bug

1. Get sent to jail for 60 min
2. Do 10-15 min of work
3. Get released

### Expected Behavior

Every min of work you do is a min of time off your sentence. 

30min of work = 60 min sentence

### Screenshots/Videos

None

**Comment by Darahz** [comment]
Done some changes to the job. Let's see if it does a difference.
