### ISSUE TITLE
Red Engine

### ISSUE THREAD

**Issue by BlazinNut** [ParadoxGamingRP/bugs-and-suggestions#1436]
### Your Discord Name

Blazin Nut#1776

### A clear and concise description of what the bug is

Was Racing with a few people. We would hit a wall or a tree once going like 30-60mph with no stalls before and instantly dead car or red engine

### Steps to Reproduce the Bug

Hit a wall or anything going above 35mph

### Expected Behavior

not to be a red engine right away

### Screenshots/Videos

N/A

### Extra Notes (Optional)

Others having same problem

**Comment by JnKTechstuff** [comment]
0 information will result in immediate closure
