### ISSUE TITLE
Underglow

### ISSUE THREAD

**Issue by BlazinNut** [ParadoxGamingRP/bugs-and-suggestions#1437]
### Your Discord Name

Blazin Nut#1776

### A clear and concise description of what the bug is

Underglow will not stay on car except for drivers side

### Steps to Reproduce the Bug

Buy Underglow
Park Car
Get Car Out
Underglow only on drivers side

### Expected Behavior

Underglow stay on. Or lower price of underglow to like $10 so dont have to pay $400 each time I want to put underglow on

### Screenshots/Videos

NA

**Comment by Darahz** [comment]
Should be good now
