### ISSUE TITLE
[BUG] Attachments not working in cars

### ISSUE THREAD

**Issue by Baljeet00** [ParadoxGamingRP/bugs-and-suggestions#1438]
### Your Discord Name

Baljeetoo#2648

### A clear and concise description of what the bug is

Pistol suppressors don't work when shooting out of cars

### Steps to Reproduce the Bug

put a suppressor on your pistol 
Shoot out of your car
see that it doesn't work

### Expected Behavior

For the pistol to be suppressed when shooting from a car

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/1aNmqpTN7jGntP/d1337C8FsZKH?invite=cr-MSxiOHcsMjUxNTU4ODMs

**Comment by ithegreatgatsby** [comment]
Confirmed. Looks like it removes attachments when you enter a car. And adds them back when you get out of car

**Comment by xXJamieXx** [comment]
GTA issue.
