### ISSUE TITLE
[BUG] AFK WARNING WHEN MOVING AND TALKING

### ISSUE THREAD

**Issue by Islaq** [ParadoxGamingRP/bugs-and-suggestions#1439]
### Your Discord Name

dazed#4461

### A clear and concise description of what the bug is

Was in the Vangie breaking glass when half way through it, I noticed the 10 minute AFK warning. 

### Steps to Reproduce the Bug

1. walking from case to case
2. breaking glass
3. got the warning

### Expected Behavior

when walking around and having movement shouldnt be getting AFK warning

### Screenshots/Videos

![afk](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/118240669/92ba6efc-6172-466a-96f9-66496fd4afdf)

**Comment by xXJamieXx** [comment]
Probably not moving far enough and/or not talking for long enough. A video would be more helpful to tell though...

**Comment by EvanAnderson49** [comment]
its the same for farming rubber i will water and feed the tree and i will get the same 10 mins afk and the only time i dont move is when watering and feeding/ fertilizer and than walking to the next one and even tried running around to see if it will reset and it wont go back and it will be the same time got kicked already and go did a friend on mine as well in the middle of a rubber farm of 20 trees

**Comment by xXJamieXx** [comment]
Tweaks have been made to improve the QOL of the AFK timer.
