### ISSUE TITLE
[BUG] Issues with crashing when sent to prison

### ISSUE THREAD

**Issue by natashajoan** [ParadoxGamingRP/bugs-and-suggestions#1441]
### Your Discord Name

its_ahsatan#7098

### A clear and concise description of what the bug is

So I craashed when I was sent to prison, I don't have the crash log for that, but when I flew in and after doing jobs to check out, when I checked out, All the items in my pockets had doubled, and I didn't switch back to my normal clothes, I was wearing the prison outfit which needs to be fixed. 

### Steps to Reproduce the Bug

1. Be sent to jail
2. Crash as soon as sent 
3. Fly back in 
4. Check out of prison, items doubled and wearing same outfit you get into prison on

### Expected Behavior

When exiting prison after crashing, items to not be doubled and to wear normal clothes again. 

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/97318080/7d8966ce-6d2d-47c4-a44c-6e323944cdbf)
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/97318080/5586182a-8cfe-4462-bef6-58a081218847)
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/97318080/8d785bc4-8348-44ce-83ae-eb472c2216ae)

### Log File

[CitizenFX_log_2023-05-25T234138.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11570147/CitizenFX_log_2023-05-25T234138.log)

**Comment by xXJamieXx** [comment]
Unsure how to reproduce this as I can't force myself to crash at the exact right moment to have this issue happen.
