### ISSUE TITLE
[ENHANCEMENT] turn on the printers at mrpd and davis pd

### ISSUE THREAD

**Issue by unforgiven8233** [ParadoxGamingRP/bugs-and-suggestions#1442]
**Your Discord Name**
Forgotten#6518
**Describe the annoyance**
the printers at mrpd and davis pd are not turned on and cant print documents at them

**Requested behavior**
to be able to create and print documents

**Screenshots**
https://i.imgur.com/5uGTgHY.jpeg
https://i.imgur.com/XQ6ZbDw.jpeg

**Comment by ithegreatgatsby** [comment]
next restart
