### ISSUE TITLE
[BUG] Double Barrel can't be cleaned

### ISSUE THREAD

**Issue by Drunkle716** [ParadoxGamingRP/bugs-and-suggestions#1443]
### Your Discord Name

MainCharacter716#7571

### A clear and concise description of what the bug is

When cleaning with a military kit it says "error: no weapon". When cleaning with a regular kit it says "you don't have the right tools".

### Steps to Reproduce the Bug

have a double barrel
try to clean it

### Expected Behavior

It is cleaned

### Screenshots/Videos

N/A

### Log File

[CitizenFX_log_2023-05-25T223420.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11570536/CitizenFX_log_2023-05-25T223420.log)

**Comment by ithegreatgatsby** [comment]
This works fine for me. Maybe it was a bad day and things were just bugged. Can you test this again and let me know? thanks!
