### ISSUE TITLE
[BUG] unable to target people and things thought cell bars at sandy and Davis pd

### ISSUE THREAD

**Issue by unforgiven8233** [ParadoxGamingRP/bugs-and-suggestions#1444]
### Your Discord Name

Forgotten#6518

### A clear and concise description of what the bug is

when you have a suspect in sandy pd you cant 3rd eye them though the bars or gate

when at davis pd you cant 3rd eye suspects though the bars 
you are only able to 3rd eye them though the gate

### Steps to Reproduce the Bug

1. put a person or prop inside the cell 
2. exit cell
3. try to target it though the bars
4. not being able to target it 

### Expected Behavior

1. put a person or prop inside the cell 
2. exit cell
3. try to target it though the bars
4. being able to target it 

### Screenshots/Videos

https://youtu.be/AawNv4VBFjo
https://youtu.be/6JbCY-VAZ7I

**Comment by ithegreatgatsby** [comment]
I doubt we can fix this at this time. It's going to be a modeling issue that probably has an invisible wall through the whole prop and just the bars as well as davis PD is locked so we really cant do much with that either

**Comment by JnKTechstuff** [comment]
Use F1 to do stuff. It works the same way

F1 > Police > Interactions
