### ISSUE TITLE
[ENHANCEMENT] Chop Shop

### ISSUE THREAD

**Issue by BrotherDayZ** [ParadoxGamingRP/bugs-and-suggestions#1445]
**Your Discord Name**
BDZ#0001

**Describe the annoyance**
No one does Chop Shop, trying to get this up and running and make more incentive for people to want to do chop shop. 
In my mind a simple solution is add a "crypto dealer" that buys car parts for crypto. Maybe 10 parts for 5 crypto (equal to 1 D class Boost). Still have the option for car parts in case people like to work with the materials

**To Reproduce**
[Steps to reproduce the annoyance]
1. Get a chop shop mission
2. Find the car and chop the car
3. Get the Car parts
4. Find the Car part dealer
5. Exchange car parts for crypto (2 for 1 ratio would be somewhat balanced imo)

**Comment by ithegreatgatsby** [comment]
This is on the list to be redone at some point once other projects are completed as well

**Comment by xXJamieXx** [comment]
Duplicate of #1265
