### ISSUE TITLE
[ENHANCEMENT] PD Briefcase ++

### ISSUE THREAD

**Issue by LitrlyD3ad** [ParadoxGamingRP/bugs-and-suggestions#1446]
**Your Discord Name**
D3ad#3069

**Describe the annoyance**
After spending the last couple hours messing with the awesome new document script i now have a very large amount of templates to carry around, and everytime i look into my pockets i see a nice looking Briefcase that would fit this stuff perfectly, Unfortunately for me the briefcase only fits other pd things and not documents/templates, or filled evidence bags, however i feel something like that would be very valuable.

**To Reproduce**
[Steps to reproduce the annoyance]
1.  spend some time making a document
2. need somewhere to store your template
3. briefcase is too full of other cool stuff

**Requested behavior**
give the briefcase a additional pocket inside that can house my documents/templates, and full evidence bags.

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by xXJamieXx** [comment]
The bookbag is made for this purpose and is available at convenience stores, hardware stores and leisure stores.
