### ISSUE TITLE
[BUG] Aiming in cars

### ISSUE THREAD

**Issue by pulsevr34** [ParadoxGamingRP/bugs-and-suggestions#1447]
### Your Discord Name

Pulse+#5769

### A clear and concise description of what the bug is

Sometimes you can or can't shoot out of your vehicle. I have tried to figure out what is actually causing it and I still have no idea. Sometimes I can aim my gun out of my car, sometimes I can't. Sometimes I can point my middle finger out the window, and sometimes I can't. I've debunked a couple of theories, it doesn't matter whether or not you have your gun out when you get in or if you pull it out when you're in already. It doesn't matter if you aim while you're pulling your gun out or if you wait for the animation to finish before aiming in.

### Steps to Reproduce the Bug

1. Pull out a gun while in a car
2. aim in
3. Either works or doesn't.

### Expected Behavior

I should be able to aim/shoot out of my car anytime I pull my gun out in the car.

### Screenshots/Videos

N/A

### Extra Notes (Optional)

N/A

**Comment by xaroht** [comment]
From what I've observed. I lose the ability after I run out of ammo in my gun. Specifically my tazer.

**Comment by pulsevr34** [comment]
Confirmed this is caused by pulling a tazer in a car and/or using a gun with no ammo in it
