### ISSUE TITLE
Loading in as an NPC[BUG] 

### ISSUE THREAD

**Issue by HereticsEnd** [ParadoxGamingRP/bugs-and-suggestions#1448]
### Your Discord Name

HereticsEnd#0107

### A clear and concise description of what the bug is

Unable to load in as my character. My player character always gets stuck as one of the loading NPCs. Have tried adjusting graphical settings, deleting my entire game cache (2x), relogging, going to apartment to change my outfit, and changing at a store. Also, this happens with both of my characters, Jayce Kent and Kyle Lambert. Also, I can't seem to see any other players on the server.

### Steps to Reproduce the Bug

1. Fly in
2. Profit

### Expected Behavior

I expected to be able to fly in and not roleplay as an NPC character.

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/45932862/33fde110-2dce-4c26-b3de-90521027aff7)
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/45932862/a1c1d822-21e9-40ce-9479-c31f1bf448bb)
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/45932862/5dc3ca56-2048-4791-8d16-f03674b4e475)
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/45932862/fb6d57ed-86ee-4c2c-9078-14525e1e554b)
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/45932862/79c7f351-af09-4bbb-8c08-e9319e247c1f)

### Log File

[CitizenFX_log_2023-05-27T011846.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11580728/CitizenFX_log_2023-05-27T011846.log)

**Comment by JnKTechstuff** [comment]
Open a staff ticket and have them set you to a MP ped
