### ISSUE TITLE
[BUG] Cant see plant when growing coke

### ISSUE THREAD

**Issue by PatrykX904** [ParadoxGamingRP/bugs-and-suggestions#1451]
### Your Discord Name

Help Me Choose A Name#0175

### A clear and concise description of what the bug is

So me and Pal were trying to grow coke and when we planted the seeds we werent able to see the plant itself

### Steps to Reproduce the Bug

1. Plant coke
2. Plant is invisible

### Expected Behavior

To be able to see the coke plant

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/81855046/062dfe05-ca10-44dd-a721-5b57e2c920e5)

### Log File

[Coke bug.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11581860/Coke.bug.txt)

**Comment by Darahz** [comment]
Unable to reproduce this
