### ISSUE TITLE
[BUG] <Davis PD doors not blowing>

### ISSUE THREAD

**Issue by xPorscha** [ParadoxGamingRP/bugs-and-suggestions#1452]
### Your Discord Name

Porscha#5395

### A clear and concise description of what the bug is

Not being able to blow locked doors at Davis PD with thermite.

### Steps to Reproduce the Bug

get thermite
go to davis and walk up to locked doors
try to use the thermite on the doors.

### Expected Behavior

nothing will happen

### Screenshots/Videos

https://youtu.be/nha7sS2_yPI

### Extra Notes (Optional)

We wasn't sure if Davis was supposed to be like this as we can blow the doors open at MRPD just fine, so we are just making this report just incase that is not the case. 

### Log File

[davis PD.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11588913/davis.PD.txt)

**Comment by ithegreatgatsby** [comment]
We don't want all doors being able to be thermite able. That way you have to go looking for which doors work. With that being said I will look into davis PD and check on things
