### ISSUE TITLE
[ENHANCEMENT] More minigames like tennis?

### ISSUE THREAD

**Issue by Ashiieee** [ParadoxGamingRP/bugs-and-suggestions#1457]
**Your Discord Name**
Ashii#9384

**Describe the annoyance**
So, i know we have Tennis! and its great. but after a fun game yesterday wiht some fellas in city, we thought it would be cool to maybe see some others out there to mess with?  Such As : Golf, Baseball, Soccer, Or a go kart track?  ETC. would be neat to have more things like this but i know its not really necessary. :)

**Comment by ithegreatgatsby** [comment]
Golf and others can be very buggy and do not sync right per players. Also those things honestly die off after a couple weeks. Go kart track stuff might come in the future depending on some other business ideas that are in the works. But I will note this down and see if we can come up with anything.
