### ISSUE TITLE
[ENHANCEMENT] NS Tuning F1 Repair

### ISSUE THREAD

**Issue by SwickMachine** [ParadoxGamingRP/bugs-and-suggestions#1459]
**Your Discord Name**
SwickMachine#6355

**Describe the annoyance**
Currently, the only spot you can repair inside of the shop is the paint booth. We are not able to repair in the front parking lot consistently. There are also spots behind the building that random people are using as a Bennys for a quick fix. I am requesting that we are able to repair anywhere inside of the shop and in the parking lot in front of the shop bay doors. That way, people can not just repair behind the shop and leave.  

**To Reproduce**
1. Random person drives up behind the building.
2. Gets a quick repair.
3. Leaves without talking to any of the employees.

**Requested behavior**
1. Random person now has to pull up to where employees are standing.
2. Person now has to ask to get a repair.
3. RP.

**Comment by ithegreatgatsby** [comment]
Fixed next restart
