### ISSUE TITLE
[BUG] Im always hungry

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1460]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

I had 5 twerks and 3 ice creams and this is all it does.
I get that the 24/7 things get nerfed but the ice cream should still do more than this. 

### Steps to Reproduce the Bug

Eat
Eat
Eat
Almost nothing happening

### Expected Behavior

Eat ice creams from Slurp 

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/98127638/1d033eb8-4341-4a5b-9f79-a746fb0c2c06)

### Log File

[creams.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11603613/creams.txt)

**Comment by ithegreatgatsby** [comment]
All slurp items are 50% food or hunger  and reduce stress by 25%     This is in line with all other business.  All 24/7 and LTD stuff now is all set to 10%.   So all player ran businesses has way more benifits
