### ISSUE TITLE
[BUG] Prison outfits sux nowadays!

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1462]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

I was sent to jail and my outfit looks like shiyet man.

### Steps to Reproduce the Bug

Go to jail
Be ugliest 

### Expected Behavior

(Not) go to jail
Be pretty

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/98127638/8c21bad5-0323-4530-b181-bb0484b14133)

**Comment by ithegreatgatsby** [comment]
Next restart. I did the best i could. Females do not have the same clothing as males do.
