### ISSUE TITLE
[BUG] Kraken (Sub) Needs Gas

### ISSUE THREAD

**Issue by ninzwinz** [ParadoxGamingRP/bugs-and-suggestions#1464]
### Your Discord Name

ninz#5911

### A clear and concise description of what the bug is

The Kraken (submarine) needs gas to move (see video). I opened a ticket to ask where I can fill the gas cause I could not find a spot to put gas into it with my full jerry can in my hands. I was told boats should not need gas any longer (thank you for that btw), but the Kraken still requires gas to move. 

Note- Could possibly have to do with the Kraken being listed as a "vehicle" instead of a boat in the Insurance app on the phone maybe? Or, could be due to having the Kraken parked originally with 0 gas.

Potential fixes: 
1- Move Kraken from "car" list to "boat" list if it is not already. See if that solves the problem since boats should not need gas anymore.
2- Allow Kraken to move without gas.
3- Configure a spot to refill gas on submarine, preferably one that is reachable by standing on top of it (not sure if this is something you guys can do or if its a R* issue).

### Steps to Reproduce the Bug

1. Have Kraken that is parked with 0 gas
2. Have dock guy pull your submarine out of the boat garage
3. Try to move forward/backward, but fail

### Expected Behavior

1. Drive forward/backward without gas OR be able to refill the gas in Kraken

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/1bY8jx3eKcN1E2/d1337V8xbP2v?invite=cr-MSxSbkQsNzk0OTUyODUs

**Comment by Darahz** [comment]
Fixed to the Kraken shows up under the right category. Haven't looked into the fuel issue yet. Just to give you an update
