### ISSUE TITLE
[BUG] Oxy Only Doing 20/25% Instead of 75%

### ISSUE THREAD

**Issue by Nicklmfao** [ParadoxGamingRP/bugs-and-suggestions#1465]
### Your Discord Name

nicklol#2510

### A clear and concise description of what the bug is

Over the last few weeks I as well as some others have noticed issues with using Oxy wither it be in gun fights or day to day usage, it was only doing a little bit. I asked around if anyone else was having issues and came to the conclusion it's not doing what it's normally suppose to. I did some testing over a hour to get a idea on what's doing as of 6/1/23 with that being 20/25% health and armor, wouldn't get passed that point. Even waiting an extra few minutes to twenty minutes in case it was just slow did nothing.

### Steps to Reproduce the Bug

1. Take Oxy
2. Wait out the two minutes
3. 20% Extra Health Peak & 20% Extra Armor Peak

### Expected Behavior

Going off of what I was told by others IC over the last few months, it's suppose to be doing 75% Armor and 75% health. Currently at the moment when I tested it over a hour or so in different ways, it was only doing 20/25% max for both health and armor, no matter what you were at before it wouldn't change past that point.

### Screenshots/Videos

![oxy test](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/97563178/6b82fcc6-22c8-4997-ab8c-37041b677aef)

### Extra Notes (Optional)

Oxy Tests

Full Health No Armor:

95% Toxicity Upon Use
95% Food and Water Upon Use

Ending Result: Full Health 20% Armor

2 Minutes for toxicity to go away.

45% Health
95% Toxicity Upon Use
95% Food and Water Upon Use

Ending Result: 65% Health 20% Armor

**Comment by ithegreatgatsby** [comment]
next restart
