### ISSUE TITLE
[BUG] Registers not working

### ISSUE THREAD

**Issue by Kromlec** [ParadoxGamingRP/bugs-and-suggestions#1466]
### Your Discord Name

Kromlec#3389

### A clear and concise description of what the bug is

You can't open the register at business to put food in to sell. window never pops up

### Steps to Reproduce the Bug

Go to business clocked in
Try to open register

### Expected Behavior

register opens and allows the putting of items into it

### Screenshots/Videos

n/a

### Log File

[glizzys.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11630837/glizzys.log)

**Comment by xXJamieXx** [comment]
Fixed in short term, added to list to fix permanently when time allows.
