### ISSUE TITLE
[BUG] Glizzys boss menu

### ISSUE THREAD

**Issue by Kromlec** [ParadoxGamingRP/bugs-and-suggestions#1467]
### Your Discord Name

Kromlec#3389

### A clear and concise description of what the bug is

No matter what rank you hold with Glizzys you are unable to open the boss menu

### Steps to Reproduce the Bug

Clock into Glizzys
Open computer
Try to access boss menu

### Expected Behavior

Boss menu should open allowing us to do boss stuff

### Screenshots/Videos

n/a

### Log File

[glizzys.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11630858/glizzys.log)

**Comment by xXJamieXx** [comment]
Fixed in short term, added to list to fix permanently when time allows.
