### ISSUE TITLE
[BUG] Can't go past character selection

### ISSUE THREAD

**Issue by Kromlec** [ParadoxGamingRP/bugs-and-suggestions#1469]
### Your Discord Name

Kromlec#3389

### A clear and concise description of what the bug is

When creating a new character, you type in your name and info and click continue, but you get stuck in the loading screen with music still playing. 

### Steps to Reproduce the Bug

Create new character
Click continue
Get stuck in black screen with loading circle in bottom right

### Expected Behavior

Should be able to create a new character

### Screenshots/Videos

https://i.imgur.com/132ggpP.jpeg 

### Log File

[character.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11632844/character.log)

**Comment by JnKTechstuff** [comment]
I'ma guess this is the broken player shit @xXJamieXx
