### ISSUE TITLE
[BUG] Refill NOS? Forget about it

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1470]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

I'm trying to refill all these bottles but the menu isnt opening when I third-eye the NOS tank at the tuner shop. Don't know how it is at SADOT.
I get to the point where it says "Open NOS refill station" and then theres nothing more. I cant press it or anything.

### Steps to Reproduce the Bug

Thirdeye the NOS tank
Nothing

### Expected Behavior

Third eye the NOS tank
Be able to refill bottles and tank

### Screenshots/Videos

N/A

**Comment by ithegreatgatsby** [comment]
yea this was my bad I did not make the zone big enough to include the nos tank when i fixed the repair issue but fixed next restart
