### ISSUE TITLE
[BUG] pd evidence stash 2 inaccessible / does not show up

### ISSUE THREAD

**Issue by unforgiven8233** [ParadoxGamingRP/bugs-and-suggestions#1471]
### Your Discord Name

Forgotten#6518

### A clear and concise description of what the bug is

have not been able to accesses pd's second stash in the lab at mrpd since the pd upgrade we had a few weeks ago

### Steps to Reproduce the Bug

1. go to the stash in the lab
2. not be able to open it or see it

### Expected Behavior

1. go to the stash in the lab 
2. be able to see and open it

### Screenshots/Videos

https://i.imgur.com/a2UKmKc.jpeg

### Extra Notes (Optional)

also would be nice if we could also get a command to open it

**Comment by ithegreatgatsby** [comment]
I dont know if you meant personal stash or evidence but i added both to the lab.  next restart
