### ISSUE TITLE
[BUG] Fire Extinguisher makes you stressed fast

### ISSUE THREAD

**Issue by NightX43** [ParadoxGamingRP/bugs-and-suggestions#1474]
### Your Discord Name

NightX#9581

### A clear and concise description of what the bug is

You get very stressed when using a fire extinguisher and you keep having to take medicine or any other product to reduce it especially for Firefighters.

### Steps to Reproduce the Bug

1. Take out fire extinguisher
2. Spray the fire extinguisher
3. wait till the stress level go up

### Expected Behavior

I want to be able to use the fire extinguisher and not get really stressed easily fast from it

### Screenshots/Videos

Don't have it

**Comment by xXJamieXx** [comment]
Needs testing but a fix was pushed.
