### ISSUE TITLE
[ENHANCEMENT] Make Marketplace great again

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1475]
**Your Discord Name**
ssara#7821

**Describe the annoyance**
If it was possible to have marketplace for businesses and aanother app for selling and buying vehicles. With the way it is now it looks so clustered to have all the different type of adds in the same place. Understand if it's not possible as well.

**Comment by xXJamieXx** [comment]
Plan from the beginning was to use the advertisements app which was designed for the phone but I'm not sure if its in a usable state and if not how hard it would be to make it usable.
