### ISSUE TITLE
[BUG] Everyone has keys to every building

### ISSUE THREAD

**Issue by PatrykX904** [ParadoxGamingRP/bugs-and-suggestions#1484]
### Your Discord Name

Help Me Choose A Name#0175

### A clear and concise description of what the bug is

Everyone in the city has keys to every business etc 

### Steps to Reproduce the Bug

1. Have business locked
2. Danny can unlock door
3. Danny can pretend to be a bartender

### Expected Behavior

Only workers that work at the specific can lock/unlock doors

### Screenshots/Videos

N/

**Comment by Darahz** [comment]
I've been checking every lock now, on live and on dev and im not able to unlock any of them.
