### ISSUE TITLE
[BUG] Fruit/Avocado seed weight

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#1485]
### Your Discord Name

Jojos n Mustard#4959

### A clear and concise description of what the bug is

Fruit and Avocado seeds are clocking in at a hefty 1 pound per seed. Not sure if this is intended behavior as it's 10x the weight of any other seed.

### Steps to Reproduce the Bug

1: Try to buy seeds for Fruit and Avocado
2: Realize they some thiccums

### Expected Behavior

1: Be able to carry seeds for farming.

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/29337315/dc199492-5c94-4bf2-a9f2-db0095696742)

**Comment by Darahz** [comment]
Did a little tweaking. Hopefully that'll help a little

**Comment by Darahz** [comment]
Closing this for now. But if its not enough just reopen the ticket
