### ISSUE TITLE
[BUG] Unable to print state ID

### ISSUE THREAD

**Issue by AssassinJT** [ParadoxGamingRP/bugs-and-suggestions#1488]
### Your Discord Name

JamoJT

### A clear and concise description of what the bug is

City Hall has a bug where the action of printing a new state ID does not work. You can click it but it does nothing.

### Steps to Reproduce the Bug

N/A

### Expected Behavior

Being able to print and pay for a new State ID

### Screenshots/Videos

n/a

**Comment by Darahz** [comment]
Not able to reproduce this. Do you have any logs from when this happen? Screenshots etc?
