### ISSUE TITLE
[BUG] Phones can be heard within range

### ISSUE THREAD

**Issue by Kromlec** [ParadoxGamingRP/bugs-and-suggestions#1496]
### Your Discord Name

Kromlec

### A clear and concise description of what the bug is

When you are within the vicinity of anyone in the = menu you can hear them make phone calls and end phone calls, not able to hear the phone call though.

### Steps to Reproduce the Bug

Be within range of the = of someone else
Make a phone call
Anyone within the range can hear it ringing and ending

### Expected Behavior

no one else should be able to hear this

### Screenshots/Videos

I forgot to clip while doing testing

### Extra Notes (Optional)

Tested this theory with Elex, Emily, Nick and Xavier. As soon as you leave the range of the = the sounds would stop but as soon as you drove back into range you could hear them again.

### Log File

[phones.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11750728/phones.txt)

**Comment by SpiceF0x** [comment]
https://streamable.com/70v7fv

**Comment by xXJamieXx** [comment]
Was an intended feature but like a lot of things, it sounds better on paper than in practice.
