### ISSUE TITLE
[BUG] Animal Cruelty for profit.

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#1497]
### Your Discord Name

Jojos n Mustard#4959

### A clear and concise description of what the bug is

When ranching animals, especially when ranching animals for byproducts, eggs milk, mushrooms, they refuse to give the byproduct unless they're being starved. Specifically in the case of chickens and cows they have to be at or below 40% Nutrition before they start producing eggs, once they hit around 23% nutrition they're also taking health damage at that range. 

But if you feed them at the 20% mark so they stop losing health, then the nutrition goes up over the threshold and they stop producing byproducts. So you end up in a cycle of Let animal starve and take damage for a few cycles, feed them, wait until they're starving again, collect byproduct, etc.

I'm not sure if this the intended behavior or not as a tradeoff for getting meat vs byproducts since the meat received goes down with animal health. But it is animal cruelty.

### Steps to Reproduce the Bug

1: Raise happy little farm animals to try and get some breakfast products.
2: Animal decides to be naughty.
3: Punish animal by starvation.
4: Profit!

### Expected Behavior

1: Happy Animals make happy breakfast products.

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/29337315/8f09d4ce-d594-4db9-bbc2-d963b80aca85)

### Log File

No relative log data.

**Comment by emeraldleo1982** [comment]
Addon, they also don't seem to give byproducts under 50% health, but that makes sense.

**Comment by JnKTechstuff** [comment]
No to all this:

```lua
if CattleData[k].health > 0.65 then
                    local seed = math.randomseed(os.time())
                    local RandomChance = math.random(1, 100)
                    if CattleData[k].animal == 'Cow' then
                        if RandomChance <= 35 then -- 45 % chance of milk
                            CattleData[k].milk = true
                        end
                    elseif CattleData[k].animal == 'Chicken' then
                        if RandomChance <= 25 then -- 45 % chance of eggs
                            CattleData[k].egg = true
                        end

                    elseif CattleData[k].animal == 'Pig' then
                        if RandomChance <= 35 then -- 45 % chance of eggs
                            CattleData[k].mushrooms = true
                        end
                    end
                end
                ```
