### ISSUE TITLE
[BUG] PD calls inaccurate 

### ISSUE THREAD

**Issue by unforgiven8233** [ParadoxGamingRP/bugs-and-suggestions#1499]
### Your Discord Name

Forgotten

### A clear and concise description of what the bug is

each officer gets a call radius but they are not the same and make for some confusion as when a officer arrives and starts looking in part of there radius they could / will be out of other officers radius 

### Steps to Reproduce the Bug

1. have a call come in that gives a radius
2. have every officer get a different slash unique radius for themselves

### Expected Behavior

1. have a call come in that gives a radius
2. have every officer get the same radius

### Screenshots/Videos

https://i.imgur.com/kdG1Q4b.png
https://i.imgur.com/7IZqM4D.jpg

**Comment by unforgiven8233** [comment]
I checked if I had cliped it but I did not
so only me and Belmont were on and we both got only 1 shots fired call the shots came for the area of where the 2 zones overlapped and that was the only area bullet casings were found

**Comment by xXJamieXx** [comment]
Yeah weird just not sure why they would be different because all officers get sent the same location at the same time.

**Comment by unforgiven8233** [comment]
is the code that makes the random radius around the call client or server?
if it is client then each officer would have their own random radius on the original call

this is just my thought and I may be wrong as I am pretty new to fivem coding

**Comment by xXJamieXx** [comment]
The coordinates of the call get sent from the criminals client to the server to be distributed to the officers so its the same one set of coordinates.

**Comment by unforgiven8233** [comment]
just tested it with another ofiicers this is what they got https://cdn.discordapp.com/attachments/895068875991949314/1121928564523143288/FiveM_b2802_GTAProcess_FnWYcQZHMm.png
and this is what i got from a 911a call

**Comment by xXJamieXx** [comment]
Anonymous calls were different and were setup to have a bit of randomness but while testing it appears its not always accurate and can cause confusion so i'm updating it to be consistent for all officers.
