### ISSUE TITLE
[ENHANCEMENT] Font scaling too small on new UI

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#1501]
**Your Discord Name**
jojosnmustard

**Describe the annoyance**
On the new inventory UI, everything is just a hair too small, people with eyesight issues are going to have problems with it. My eyesight is pretty good, often preferring small fonts and images for aesthetics but I think the font could use like 5-10% upscaling, if not the entire inventory UI. 

An alternative to font scaling is perhaps an addition 1-2 pixel padding between each slot so it feels less cluttered to the eyes and offers a bit more ease of reading. The inventory doesn't feel too bad cause there's lots of space, but the storage pane feels extremely cluttered.

**To Reproduce**
[Steps to reproduce the annoyance]
1. Open storage
2. Squint at all the tiny items mashed together.

**Requested behavior**
5-10% upscale of Inventory UI size or item font size, or possibly more padding between cells.

**Comment by JnKTechstuff** [comment]
Has to do with your monitor. Was tested for compatibility on 1080p and 1440p screens

**Comment by emeraldleo1982** [comment]
But I'm on 1080p fullscreen. no windows text scaling etc.
