### ISSUE TITLE
[BUG] Cash disappearing on purchase

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#1503]
### Your Discord Name

jojosnmustard

### A clear and concise description of what the bug is

If you pull out cash, and buy anything from a local shop, all your cash disappears.

I.E.: Withdraw $500, buy a single bandage, you now have no cash.

Also some people are complaining of cash being missing in general since the update earlier today.

### Steps to Reproduce the Bug

1: Withdraw Cash
2: Buy Item
3: No cash remaining

### Expected Behavior

1: Withdraw Cash
2: Not lose it

### Screenshots/Videos

N/A

### Log File

No applicable log data.

**Comment by JnKTechstuff** [comment]
fixed
