### ISSUE TITLE
[BUG] Crims not being able to see fingerprint scanner

### ISSUE THREAD

**Issue by WATSON4321** [ParadoxGamingRP/bugs-and-suggestions#1507]
### Your Discord Name

reeree123

### A clear and concise description of what the bug is

when i arrested someone they said they couldn't see the finger print scanner so i tested it clocked of and saw nothing

clip https://youtu.be/8jYEJnHtLIA

### Steps to Reproduce the Bug

have someone not cloked in as pd try to use it 

### Expected Behavior

to finger print suspects

### Screenshots/Videos

https://youtu.be/8jYEJnHtLIA

**Comment by xXJamieXx** [comment]
They shouldn't need to access it. It should run it on the nearest person automatically.
