### ISSUE TITLE
[BUG] PD stash double items

### ISSUE THREAD

**Issue by agentspooky19** [ParadoxGamingRP/bugs-and-suggestions#1509]
### Your Discord Name

spooky_6464

### A clear and concise description of what the bug is

When going off duty to put my weapons up in my stash there was duplicates of each item. I haven't touched them nor done anything with them so you can accurately see what's happening. Below is a screenshot of what is going on with my PD stash as an example.
 

### Steps to Reproduce the Bug

n/a

### Expected Behavior

n/a

### Screenshots/Videos

![Screenshot (113)](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/117245051/c9024c6e-9e68-4384-8d45-aff54ae28ee7)

### Log File

[CitizenFX_log_2023-06-15T211631.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11763935/CitizenFX_log_2023-06-15T211631.log)

**Comment by xXJamieXx** [comment]
Potential fix pushed for this. Let me know if its still happening @agentspooky19!

**Comment by agentspooky19** [comment]
@xXJamieXx I went in just now to see and the items are still in the PD stash for me. I don't know if you're able to go in and remove them so I'm able to give you accurate feedback on if it is still doing it?

**Comment by xXJamieXx** [comment]
@agentspooky19 you should contact paradox mail to get the items removed.
