### ISSUE TITLE
[BUG] Dinka Nexus has GTA:O Rocket Boosters!

### ISSUE THREAD

**Issue by jplink420** [ParadoxGamingRP/bugs-and-suggestions#1512]
### Your Discord Name

j_plink

### A clear and concise description of what the bug is

So I recently purchased a new shiny Lime Green Dinka Nexus from Kildare Auto's the other day. It's a great car, and I love it. However, I think the manufacturer may have given me more than I had asked for. As when I was driving it around today, I noticed a random "X" button in the car I hadn't pushed yet, and all of a sudden, I feel myself get pinned back into my seat and notice two massive afterburner style flames shooting out the back of my car like I am flying an F-18 Hornet! I went ahead and set up a drone to capture this, and I will attach a video of it here. Its quite spectacular. This surprised me as I haven't even had a NOS kit installed. The system even made a strange noise when it would appear the rockets were burnt out. I am not sure if Dinka intended to sell this booster kit in the car, but I just figured I would make sure here.

### Steps to Reproduce the Bug

1. Buy a Dinka Nexus
2. Notice the strange button in the car
3. Tap GTA:O boost button while accelerating (Mine was X)
4. Fly down the road like an F-18

### Expected Behavior

The Dinka Nexus to not have NASA grade rocket boosters in it.

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/1er78bBwCS-Xy1/d1337uvwpBpa?invite=cr-MSxQT3MsNDE0NDgwNjEs

### Log File

[CitizenFX_log_2023-06-16T021346.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11765591/CitizenFX_log_2023-06-16T021346.log)

**Comment by JnKTechstuff** [comment]
Fixed
