### ISSUE TITLE
[BUG] Watering can not fillable

### ISSUE THREAD

**Issue by RePeAtZz** [ParadoxGamingRP/bugs-and-suggestions#1515]
### Your Discord Name

RePeAtZz

### A clear and concise description of what the bug is

The watering cans have a bug where if you deplete all the water out of it you are unable to refill it. When you go and try to refill it, it says "watering can durability depleted" and you have to buy a completely new one and that one will also do the same thing.

### Steps to Reproduce the Bug

1. Fill up the can for the first time
2. Plant any plant (rubber, weed etc) 
3. Water that plant until the watering can is empty 
4. Try to refill it

### Expected Behavior

To be able to refill the watering can.

### Screenshots/Videos

![218_20230616202332_1](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/109673739/8d0e0d6c-77cc-46e6-b7e1-c49fc14ca7ed)

### Log File

[CitizenFX_log_2023-06-17T010556.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11777674/CitizenFX_log_2023-06-17T010556.log)

**Comment by JnKTechstuff** [comment]
Fixed with new right click action
