### ISSUE TITLE
[SUGGESTION] 6STR Tunershop Ruiner

### ISSUE THREAD

**Issue by RoguIsAwesome** [ParadoxGamingRP/bugs-and-suggestions#1517]
**Your Discord Name**
rogue_69

I think that the vehicle team should add this vehicle to the server since its a cool af car and I dont see enough people suggesting cars into the server so.... 

The link for the car is https://www.gta5-mods.com/vehicles/6str-imponte-ruiner-450-custom-add-on-tuning

Again I dont want to be a nuisance and put this in the wrong place but I couldent find a suggestions report anywhere so I figured this would probably be the best place to put it?

**Comment by ithegreatgatsby** [comment]
Closing this. This has been moved to the vehicle to-do list to be looked into and may come into a future update with other DLC cars.
