### ISSUE TITLE
[BUG] Delay in everything when being detained.

### ISSUE THREAD

**Issue by xPorscha** [ParadoxGamingRP/bugs-and-suggestions#1519]
### Your Discord Name

Porscha#5395

### A clear and concise description of what the bug is

Over the course of these last few days, myself and my friends have been running into an issue when being arrested where, when we are cuffed, searched and taken, there is delay in everything that we do. When we speak, people hear us 10 minutes later. When we get searched, we're not being searched until later on. We take naps and we are frozen in the loading screen and when we fly back in, 9 times out of 10 it doesn't fix it. 

### Steps to Reproduce the Bug

get arrested
get cuffed
go to MRPD
go to pillbox.

(it happens anywhere between being cuffed and being sent to jail)

### Expected Behavior

When you talk, you voice box lights up 10 minutes later. 
When searched, it'll tell you way after it happened. 
Everything you do will be laggy.
When taking a nap, you will stay frozen in the load in screen.

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/124258625/ea52d7b2-cb88-436c-a325-800fa3227bf0)

### Extra Notes (Optional)

There are 2 logs, 1 is mine, the other is my friends. 

### Log File

[lagging.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11780629/lagging.txt)

[jeb lagging.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11780631/jeb.lagging.txt)

**Comment by pulsevr34** [comment]
From what I've observed this is caused by cuffing, tested it with someone and I was fine up until I was cuffed. Possibly caused by other police actions but cuffing is 100% confirmed.

**Comment by JnKTechstuff** [comment]
Tested with provided replication methods and found nothing.
