### ISSUE TITLE
[BUG] Hood not opening

### ISSUE THREAD

**Issue by omelette44** [ParadoxGamingRP/bugs-and-suggestions#1521]
### Your Discord Name

omelette#8986

### A clear and concise description of what the bug is

Car: Landrover Range Rover (import obvs) 
Bonnet (Hood) doesn't open up, either from the interactive menu from sitting inside or when outside third eyeing on the hood.

### Steps to Reproduce the Bug

Just try and open the Bonnet.

### Expected Behavior

The bonnet to open.

### Screenshots/Videos

I do not have anything for this.

### Extra Notes (Optional)

You can hear it opening but can't see it, I've had multiple people tr it and have restarted to make sure its a bug.

### Log File

[CitizenFX_log_2023-06-18T160510.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11782092/CitizenFX_log_2023-06-18T160510.log)

**Comment by xXJamieXx** [comment]
Works for me? 
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/11248045/90776768-6575-4fa2-adb8-f4c90397ad46)

**Comment by omelette44** [comment]
Still not working for my car ic 🤷, not a biggie though appreciate you looking into it !!
