### ISSUE TITLE
[BUG] <short description>

### ISSUE THREAD

**Issue by Jarome435** [ParadoxGamingRP/bugs-and-suggestions#1522]
### Your Discord Name

coach_ghosty

### A clear and concise description of what the bug is

no one can fly in Detailed info: HTTP 530

### Steps to Reproduce the Bug

1 Try and fly in
2 Detailed info: HTTP 530

### Expected Behavior

to fly in 

### Screenshots/Videos

![FiveM® by Cfx re 6_18_2023 2_08_13 PM](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/136755819/d85bb99c-993e-4dd1-aa63-d1bb6a842130)

**Comment by xXJamieXx** [comment]
FiveM outage. Please check FiveM status before opening a bug report for someone out of our control.
