### ISSUE TITLE
[ENHANCEMENT] MWGA (Make Weed Great Again)

### ISSUE THREAD

**Issue by RoguIsAwesome** [ParadoxGamingRP/bugs-and-suggestions#1524]
**Your Discord Name**
rogue_69

I believe that weed in paradox is just overlooked and everyone has just left weed for cocaine and now grinding cocaine everyday , I feel we should atleast try to balance out weed, for example increasing the sale of each weed bag or also balancing cocaine out. 
 
**Requested behavior**
Weed being balanced out
Cocaine being balanced out so that not only everyone does cocaine and so that there is still people growing weed in the city. 
We could also change the process of weed similar to coke where we can make weed bricks in the same kind of environment as cocaine.

**Comment by xXJamieXx** [comment]
The sale of each drug seems balanced based on the amount of time it takes to produce each one. Would need some research completed to prove whether this needs changing or not.
