### ISSUE TITLE
[BUG] Phone stuck halfway on screen after boost. 

### ISSUE THREAD

**Issue by Flora45** [ParadoxGamingRP/bugs-and-suggestions#1528]
### Your Discord Name

Flora40

### A clear and concise description of what the bug is

When finishing a boost it seems your phone is stuck in the animation of showing you how many hacks you're on. It's not fully pulled up but it's just kind of stuck halfway pulled out. Taking a nap fixes it but I've tried other things like taking it out of my pockets and putting it back in and it doesn't seem to work. 

### Steps to Reproduce the Bug

1. Do a boost
2. Observe phone not going away properly 

### Expected Behavior

1. Do a boost
2. Phone gets put away properly 

### Screenshots/Videos

![FiveM® by Cfx re - Paradox Gaming RP _ 4+ years _ discord gg_paradoxgaming 19_06_2023 17_07_11](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/79613077/b99f1083-92ae-4af2-832c-75516499c9c4)

### Log File

[CitizenFX_log_2023-06-19T173052.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11793167/CitizenFX_log_2023-06-19T173052.log)

**Comment by xXJamieXx** [comment]
Possibly fixed this but haven't tested it with boosts to confirm.

**Comment by Flora45** [comment]
I can confirm at some point today. Will update as soon as I can.

**Comment by xXJamieXx** [comment]
After restart of course.

**Comment by Flora45** [comment]
indubitably

**Comment by Flora45** [comment]
Looks like the issue persists after asking around.

**Comment by xXJamieXx** [comment]
https://github.com/project-error/npwd/issues/906
