### ISSUE TITLE
[ENHANCEMENT] Checking payslip amount possibly

### ISSUE THREAD

**Issue by Mambaa19** [ParadoxGamingRP/bugs-and-suggestions#1529]
**Your Discord Name**
Mambaa_19#4871

**Describe the annoyance**
Not really an issue but a way to check how much money is in the bank before withdrawing your payslip as I feel like a lot of people in city treat it like a savings account. Or even add the addition of a savings account possibly?

**Comment by ithegreatgatsby** [comment]
You can check cash or bank at any time by pressing T  and /cash or /bank

**Comment by xXJamieXx** [comment]
A way to check has been added. Savings accounts may come in the future.
