### ISSUE TITLE
[BUG] After returning from headpop, You are required to start the contract for the 2nd time.

### ISSUE THREAD

**Issue by xaroht** [ParadoxGamingRP/bugs-and-suggestions#1533]
### Your Discord Name

_mk.

### A clear and concise description of what the bug is

After returning from headpop, You are required to start the contract for the 2nd time, which consequentially makes you spend double the amount of PDX on the boost, and it restarts your hacking progress.

### Steps to Reproduce the Bug

1. Do A Boost
2. At any point, headpop or restart your game.
3. Fly back in after step 2.
4. If you have hacking progress, It will show that you are on the same amount of hacks. After completing those, your drop off won't  show. 
5. Restart your boost, spending all (X) amount of crypto again.
6. Complete hacks and then go to drop off point

### Expected Behavior

1. Do A Boost
2. At any point, headpop or restart your game.
3. Fly back in after step 2.
4. If you have hacking progress, It will show that you are on the same amount of hacks. After completing those, your drop off WILL show up instead of not showing up as mentioned previously.  

### Screenshots/Videos

N/A

### Extra Notes (Optional)

N/A

**Comment by xaroht** [comment]
This has became a bigger issue now that the cooldown on boosts have been fixed. Sometimes you cannot accept the boost for some time after headpopping, possible causing you to lose the contract.

**Comment by JnKTechstuff** [comment]
Idk what you want us to do about your game crashing but nothing we can do on your game shitting itself everytime you do a boost
