### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by jkaejkae888** [ParadoxGamingRP/bugs-and-suggestions#1534]
### Your Discord Name

jkaejkae888#6530

### A clear and concise description of what the bug is

Guns duplicating from the cleaning bench.

### Steps to Reproduce the Bug

Put your gun in the bench like a AP pistol then let it clean you take it and then go back to the bench and it's still there

### Expected Behavior

Once it's gone it's gone from the bench

### Screenshots/Videos

N/A

### Extra Notes (Optional)

I cleaned a AP pistol and took it as usual I then came back after storm and the ap was still in the bench and it duplicated with the same serial number.

**Comment by xXJamieXx** [comment]
Leftover from past bug. Dispose of any duped weapons.
