### ISSUE TITLE
[ENHANCEMENT] Remove flatbed controls from Game Controllers

### ISSUE THREAD

**Issue by CorFinn** [ParadoxGamingRP/bugs-and-suggestions#1536]
**Your Discord Name**
GrandNagus

**Describe the annoyance**
When driving a tow flatbed, the Left Analog stick controls steering, like it should. However, the flatbed controls are also attached to the same analog stick, but on the vertical axis. Also, unlike steering, where the analog stick provides a gradient turn, the vertical use is binary, so even the slightest tap in the U/D directions on the analog stick make drastic movements. This results in occasionally having your flatbed fly out behind the vehicle suddenly, and is potentially a safety hazard.

**To Reproduce**
[Steps to reproduce the annoyance]
1. Use controller.
2. Use Tow Flatbed.
3. Move left analog stick

**Requested behavior**
I would like the script to be modified to remove the controller bindings from the controller, or allow them to be bound to a different key on the controller.

**Screenshots**
N/A

**Additional context**
I have attempted to resolve this problem via keybinding, both in the game and with an external tool, reWASD. I have also attempted to rebind the WASD keys to my left analog stick. This *does* work, but it removes the steering gradient, which is a non-starter.

**Comment by ithegreatgatsby** [comment]
We cant really edit the flatbed script due to it being in another code and parts of its locked. other then LUA. Their is only very little things we are able to edit. I can see if we can find something else that will work
