### ISSUE TITLE
[BUG] Flash GT has its speed capped at 118

### ISSUE THREAD

**Issue by ZOIMBIE3** [ParadoxGamingRP/bugs-and-suggestions#1545]
### Your Discord Name

ZOIMBIE#5888

### A clear and concise description of what the bug is

IM not sure if this change was intentional. I had a engine swap Subaru engine in my flash gt it was only going 118 max so i had decided to get in contact with Nismo to switch it into a sultan rs. Now that i have the engine out of the flash gt the car is still capped at 118. Im not sure if this speed cap was intentional on the flash gt but i thought id inquire about just to make sure.

### Steps to Reproduce the Bug

you will need to get a flash gt fully upgraded with turbo and nos and will see it does not go above 118

### Expected Behavior

the car will red line in 5th gear and not go above 118.

### Screenshots/Videos

if needed let me know i can supply one for you guys

**Comment by ithegreatgatsby** [comment]
This seems balanced with its current speed and acceleration vs other cars in the server.
