### ISSUE TITLE
[BUG] Weird down messages/ EMS Alert Missing

### ISSUE THREAD

**Issue by pulsevr34** [ParadoxGamingRP/bugs-and-suggestions#1546]
### Your Discord Name

pulseinator

### A clear and concise description of what the bug is

When you go down, sometimes it will give you a weird message like "aleto Hospital, illbox Hospital", and the message to alert EMS  and the prompt telling you whether or not EMS around is gone. This is the first time it has happened to me but I've heard it from other people a few times in the past week or so.

### Steps to Reproduce the Bug

1. Go down
2. Sometimes get the weird prompt, sometimes not

### Expected Behavior

I should be able to see the down message that tells me when ems is around and also see the Airlift/Bleed out countdown.

### Screenshots/Videos

![Screenshot 2023-06-24 153752](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/97071437/6a6f111e-2788-4704-8e74-7b29619525c1)

### Extra Notes (Optional)

I believe this only happens when EMS is on duty but I can't confirm

### Log File

[CitizenFX_log_2023-06-24T190936.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11858021/CitizenFX_log_2023-06-24T190936.log)

**Comment by xXJamieXx** [comment]
Cannot reliably be reproduced.
