### ISSUE TITLE
[BUG] Weed baggies dont get used when rolling joints

### ISSUE THREAD

**Issue by RoguIsAwesome** [ParadoxGamingRP/bugs-and-suggestions#1548]
### Your Discord Name

rogue_69

### A clear and concise description of what the bug is

Whenever you roll joints with rolling paper , it takes away the rolling paper but not the weed baggies for some reason?

### Steps to Reproduce the Bug

1. Roll Joints with weed baggies
2.  Weed baggies dont disappear from pockets
3.  Infinite joints #snoopdog 

### Expected Behavior

Weed baggies taken away when rolling joints?

### Screenshots/Videos

N/A

### Extra Notes (Optional)

N/A

**Comment by xXJamieXx** [comment]
You can't combine weed baggie with rolling paper, its not a valid recipe and I can't reproduce this?
