### ISSUE TITLE
[ENHANCEMENT] Make Pillbox Better

### ISSUE THREAD

**Issue by LitrlyD3ad** [ParadoxGamingRP/bugs-and-suggestions#1549]
**Your Discord Name**
deadttv

**Describe the annoyance**
As of now if PD goes to lower Pillbox to securely give medical treatment the suspects are sent to upper Pillbox, this makes PD have to split up to secure not only upper, but lower aswell. As of now we have a bunch of beds on lower that could be used.

**To Reproduce**
[Steps to reproduce the annoyance]
1. someone signs in to medical on lower pillbox (refer to photo)
2. they get sent to upper pillboxes emergency room instead of lower

**Requested behavior**
When you submit yourself to medical on lower pillbox, either the one at the main entrance (https://i.imgur.com/JfSx5Wn.jpeg) or the one in the garage (https://i.imgur.com/WFLFwTd.jpeg) it would then place you on one of the beds on the lower level (https://i.imgur.com/HCkpLH8.jpeg) , it would make sense plus make PDs lives much easier.

**Screenshots**
https://i.imgur.com/WFLFwTd.jpeg
https://i.imgur.com/JfSx5Wn.jpeg
https://i.imgur.com/HCkpLH8.jpeg

**Additional context**
[Add any other context about the enhancement here]

**Comment by ithegreatgatsby** [comment]
I can make the beds work at lower also but they will still check out upstairs.  Just how the script is set up its just one wake-up spot at each hospital.

**Comment by unforgiven8233** [comment]
> I can make the beds work at lower also but they will still check out upstairs. Just how the script is set up its just one wake-up spot at each hospital.

could you just add lower pillbox as a separate hospital so that way people that check-in at lower pillbox check out at lower pillbox

**Comment by ithegreatgatsby** [comment]
its on the list to be reworked once time allows
