### ISSUE TITLE
[BUG] i keep randomly falling thru the map in a very specific area, and only that area.

### ISSUE THREAD

**Issue by Ashiieee** [ParadoxGamingRP/bugs-and-suggestions#1550]
### Your Discord Name

ashiiie

### A clear and concise description of what the bug is

So, its happend about 4/5 times now, in this very specific area i keep falling thru the map and its only in that area and nowhere else so far it seems its just me out of all the people i know who have driven down that area, cant really tell if its my pc or if its something with the city. it wasnt like this until up to a week or two or more ago.

in the clip provided below, i did have headaches before i fell but, that isnt the reason, as the other times i haven fallen thru the map in that generalized area, i wanst headaching. second clip i guess i dint catch in time but it still shows that generalzied area on postal where i seem to fall thru

### Steps to Reproduce the Bug

idk i just be drivin to that area sorta fast and i be fallin

### Expected Behavior

to not fall thru the map tbh

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/126841982/0e49b1c5-f7aa-44f6-9e98-1cffbaba5ca8)
https://medal.tv/games/gta-v/clips/1fZQqQs1gYweeS/d1337SF00NjO?invite=cr-MSxsUFosMTg1MTU4NTU0LA
https://medal.tv/games/gta-v/clips/1dHvYZqxqBRcM2/d1337Q7JDpKX?invite=cr-MSxhYlIsMTg1MTU4NTU0LA

### Log File

[CitizenFX_log_2023-06-25T010232.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11858884/CitizenFX_log_2023-06-25T010232.log)

**Comment by Ashiieee** [comment]
so just to update this real quick , iwent back to test after a hard nap, and it did it again and i wasnt headaching as i got there i got a bigger snip of the generalized area i get it in its up this part of hte highwya and into under mirror park where my waypoint is  also a clip wiht it happening again lol
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/126841982/09f3c86c-9afb-4366-9650-3abfe599a4fe)

https://medal.tv/games/gta-v/clips/1g092KRmTexrCB/d1337r2AgrGY?invite=cr-MSxibmIsMTg1MTU4NTU0LA

**Comment by ithegreatgatsby** [comment]
I cannot recreate this. And we have had no other reports about this. Please reach out in the discord via a support ticket on help with adjusting your settings.
