### ISSUE TITLE
[BUG] Anna's Caramel Cake not going into bento box

### ISSUE THREAD

**Issue by tommytwoshotty** [ParadoxGamingRP/bugs-and-suggestions#1551]
### Your Discord Name

tommytwoshotty

### A clear and concise description of what the bug is

When attempting to put some food into my bento box i quickly found out that you can not store the Annas Caramel Cake into the bento box. 

### Steps to Reproduce the Bug

open bento box to put food in it
Try to put caramel cake into box
Food goes back into your pockets 

### Expected Behavior

Be able to put food item into bento box

### Screenshots/Videos

https://i.imgur.com/Omo0ZRW.png

**Comment by Darahz** [comment]
Changes done
