### ISSUE TITLE
[BUG] Warehouses

### ISSUE THREAD

**Issue by BrotherDayZ** [ParadoxGamingRP/bugs-and-suggestions#1555]
### Your Discord Name

BDZ#0001

### A clear and concise description of what the bug is

Multiple bugs going to be listed within this report.

1. Previous or other warehouses are linked to the current warehouse. When entering at a different/wrong location, you actually enter into the warehouse that is active and can take it over even if the active location is being held by whoever currently owns it. 
EX: Warehouse location is XYZ, and Gang Blue is holding it. Gang Green enters location ABC and hacks into the ATM. 

2. When exiting the location, you pop out near MRPD, to me this makes no sense and you should exit out to the same location you enter. 

### Steps to Reproduce the Bug

(1)
1.Gang 1 owns warehouse at location A
2. gang 2 enters different warehouse at location B
3. They both have access to the warehouse instance and location

(2)
1.Enter warehouse at location A
2. Leave the warehouse
3. Appear at a different location (near Smoke on the water, another spot is near MRPD)

### Expected Behavior

1 warehouse and 1 entrance.

Leave the warehouse and appear where you entered.

### Screenshots/Videos

N/A

**Comment by xXJamieXx** [comment]
Closing this since warehouses have been updated lately. Open a new issue with any further issues.
