### ISSUE TITLE
[BUG] Flying in unable to hear people and some seeing me as a Danny

### ISSUE THREAD

**Issue by Sicusans** [ParadoxGamingRP/bugs-and-suggestions#1556]
### Your Discord Name

SetMeOff

### A clear and concise description of what the bug is

When flying in everything seems normal up until I try and speak with people. I can't hear them unless they are on the phone. Some also seem to see me as a Danny. It's not an issue of flipping my audio input/outputs because I've tried that as well as tried clearing cache. Hard Napping doesn't fix it either. The only way I am able to hear people again is by fully resetting my PC. Which shouldn't be the case. No other audio is messed up, just people talking in the city. However this has happened to me again and again nearly every time I fly into the city. I know quite a few other people have had this happen to them as well. I am aware that Jamie is aware of this issue since it was brought up before. 

UPDATE 6/27/2023: 
I flew in and couldn't even hear people on the phone this time... 
### Steps to Reproduce the Bug

I genuinely don't have any idea as to how to reproduce the bug. 
But it's repeatedly happening to me.

### Expected Behavior

When flying in, I should be able to hear people properly without having to restart my PC every time for it to work. 

### Screenshots/Videos

https://cdn.discordapp.com/attachments/1061220868837101599/1122779595364638740/image.png

### Log File

[CitizenFX_log_2023-06-26T063858.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11865459/CitizenFX_log_2023-06-26T063858.log)

**Comment by Sicusans** [comment]
Any news???

**Comment by xXJamieXx** [comment]
Cannot reproduce. Best bet is opening a support ticket and figuring out what the issue is on your end.
