### ISSUE TITLE
[BUG] Bulletproof Windows

### ISSUE THREAD

**Issue by kevstax** [ParadoxGamingRP/bugs-and-suggestions#1558]
### Your Discord Name

kevstax

### A clear and concise description of what the bug is

Enus Jubilee windows are bulletproof to a certain extent they break after about 20 shots from an AK.

### Steps to Reproduce the Bug

1. Shoot the windows or windshield of the Jubilee
2. Windows will reject the bullets then eventually break.

### Expected Behavior

Windshield or windows should break instantly.

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/1gixOo3wUSXy1n/d13373YnqKdQ?invite=cr-MSxIUmssMjI2ODEyNDks

**Comment by Bac0nRamen** [comment]
if people abuse this please report it. We will continue to try to fix all the cars with this issue its mostly from a certain gta dlc
