### ISSUE TITLE
[ENHANCEMENT] More Motor at the Tuner Shop

### ISSUE THREAD

**Issue by ColKing** [ParadoxGamingRP/bugs-and-suggestions#1562]
Colt__

Just wanted to know as management at the Tuner shop if there is a way we can bring in more engines for every category. I know the current person we use is https://www.gta5-mods.com/users/Aquaphobic I was curious if we are allowed to explore other Creators as well. I'm just curious if not I understand just wondering on how to go about it if we can.

**Comment by Bac0nRamen** [comment]
Link me a few that you like and make a script ticket in the dev discord and I will look into it.

**Comment by ColKing** [comment]
https://www.gta5-mods.com/vehicles/chevrolet-corvette-camaro-lt4-engine-sound
