### ISSUE TITLE
[BUG] low riders using hydraulics are super fragile!

### ISSUE THREAD

**Issue by Ashiieee** [ParadoxGamingRP/bugs-and-suggestions#1563]
### Your Discord Name

ashiiie

### A clear and concise description of what the bug is

So, not sure if its intentional or not, but using hydraulics on lowriders, are really fragile, you can only bounce a few times before the engine gets all fucked up, if this is intentional I can also understand from a perspective that it may have to be this way just so its fair with how other vehicles are. it also seems to depend on how high i bounce the low rider.

### Steps to Reproduce the Bug

1. get a lowrider
2. get hydraulics (any kind)
3. start bouncing a few times

### Expected Behavior

this question always confuses me so im gonna attach 2 expects, if it were not like this, id expect it to be fine if i bounce it so many times, but with what happens right now after a couple of bounces the engine goes orange/red but it matters on how high you get the bounce.

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/1gmNRiL8NqhAuk/d13375cY4Bk6?invite=cr-MSxKTDEsMTg1MTU4NTU0LA

**Comment by xXJamieXx** [comment]
Not sure what much we can do about this. You're causing damage to the vehicle by bouncing it which makes sense. Decreasing damage to the vehicle class would just affect usual crashes. Feels like this is just a side effect of over-using hydraulics.
