### ISSUE TITLE
[BUG] Cross character

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1566]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

My gorgeous Abcde can wake up in Nismo Apartments, and she doesnt even know them crimers. 
Cross character wise - i have keys to Nismo Apartment on my other characters. Don't know if this can be fixed but I'll give it a shot. OOOOOOOH WERE HALFWAY THERE OOOOOOOOOOH SQUIDWARD ON A BEAR! 

Anyways, thank you goodbye.

### Steps to Reproduce the Bug

Get keys to Nismo apartments IE recruited to gang
Log in to other character
Be able to wake up in Nismo Apartment

### Expected Behavior

That Abcde wouldnt have keys to Nismo

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/98127638/d76fe39b-1ab7-45da-9482-94ad57773f47)

**Comment by xaroht** [comment]
This appears to only ever be an issue for me when I do /logout and I can spawn in at my gang's HQ
