### ISSUE TITLE
[BUG] <airlift bug>

### ISSUE THREAD

**Issue by Jarome435** [ParadoxGamingRP/bugs-and-suggestions#1567]
### Your Discord Name

coach_ghosty

### A clear and concise description of what the bug is

while someone is carrying you if you try and airlift you won't airlift, and will be healed 

### Steps to Reproduce the Bug

1. be down
2. air lift while someone is carrying you
3. be okay 

### Expected Behavior

be sent to hospital 

### Screenshots/Videos

video wont upload

**Comment by ithegreatgatsby** [comment]
not really a bug. More so just something you should not do while being carried for multiple reasons. But we will look into it a bit
