### ISSUE TITLE
[BUG] No chop guy at postal 3027

### ISSUE THREAD

**Issue by BBstud44** [ParadoxGamingRP/bugs-and-suggestions#1569]
### Your Discord Name

BBstud27#5956

### A clear and concise description of what the bug is

I got my chop mission grabbed the car and took it to the location given. Upon arriving at the 3027 I realized that T. Anon's guy had flaked on us and didnt show. 

### Steps to Reproduce the Bug

1. get a mission
2. get the correct car from the given search grid
3. take the car to where Mr. T. Anon's friend is at postal 3027
4.  Find out his friend is a flake and doesnt show up to give you car parts

### Expected Behavior

I expect his friends to be trustworthy and show up at the location im given so i can recieve my payment

### Screenshots/Videos

N/A

**Comment by jkaejkae888** [comment]
I've also had the same issue when finding the car in grapeseed and getting the drop off at postal 721 the old chopping location the ped doesn't spawn.

**Comment by Ashiieee** [comment]
so, i just had a similar problem but the chop person was there, i managed to give them 2 car parts before they just... got scared of nothing and ran off.... lol

**Comment by xXJamieXx** [comment]
Tweaked slightly. Let me know if its still an issue.

**Comment by jkaejkae888** [comment]
done 4 chops today all have worked so far and postal 721 worked
