### ISSUE TITLE
[ENHANCEMENT] Blinker Fluid 

### ISSUE THREAD

**Issue by SamB1997** [ParadoxGamingRP/bugs-and-suggestions#1570]
**Your Discord Name**
davefromsunderland

**Describe the annoyance**
It's not exactly fun when you are chasing someone on foot and they chain drink blinker fluid one after another. There is no downside to drinking them other than the toxicity which goes away when the effect ends anyway so it counteracts it. It just ends up as a game of whoever has the most blinker fluid on them. 

**To Reproduce**
1. Drink Blinker Fluid
2. Wait Until The effects end
3. Drink another

**Requested behavior**
It would be nice if there would be a downside to drinking it (e.g Being extremely thirsty after eating a doughnut). Or if the toxicity effect was a bit higher so you could drink ~2 before being too toxic. The toxicity also needs to last longer than the effect because its kinda pointless having it wear off at the same time.  

**Screenshots**
I do not have a screenshot

**Additional context**

**Comment by ithegreatgatsby** [comment]
made it the same as the donuts with more toxicity.
