### ISSUE TITLE
[ENHANCEMENT] Enter QOL report title

### ISSUE THREAD

**Issue by canaansk8** [ParadoxGamingRP/bugs-and-suggestions#1571]
**Your Discord Name**
canaansk8

**Describe the annoyance**
It really sucks having to drive to sandy or chumash to go to the hardware store. Would it be possible to turn the MegaMall into one? It could give a reason for people to go to the southside a little more often.

**To Reproduce**

1. 
2. 
3. 

**Requested behavior**
Turn MegaMall into a hardeware store. 

**Screenshots**
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/122759353/3ad998d5-c331-4099-b13d-12e9885881a7)

**Additional context**
[Add any other context about the enhancement here]

**Comment by ithegreatgatsby** [comment]
Will look into. But we do not want everything being super easy to get or right around the corner
