### ISSUE TITLE
[BUG] store robbery registers not working right

### ISSUE THREAD

**Issue by shadhearts** [ParadoxGamingRP/bugs-and-suggestions#1573]
### Your Discord Name

shadhearts

### A clear and concise description of what the bug is

So I know the recent changes to store robberies were that if you wanted to do a quick and fast cash grab you could by simply walking into the store lock picking the register and then leaving with the money from the register. When this change was made day one it was working properly for me. Me and my friend walked into the 24/7 and I was able to lock pick the register. Fast forward a few days later I wasn't able to and get a message saying something like "the registers appear to be jammed" I thought this just meant that not enough LEO's were online and let it be. Fast forward now and for the past 3-4 days me and my friends have been wanting to rob 24/7's and we just can't start it. We don't even get a prompt whether or not its "jammed" or anything in response at all. I created a ticket thinking that I might have missed an update, that the old local who gives the job is back or something. But the response I received was that that isn't the case and it seems I am encountering a bug.

### Steps to Reproduce the Bug

1. Head to register
2. Try to lock pick
3. No response

### Expected Behavior

I assumed when I lock pick a register I would either get a response notifying me that it is jammed, or a skill check appearing letting me know that I am in the process of opening the register.

### Screenshots/Videos

https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/138297554/f28f1061-d329-4de7-b364-ebd4cd830da2

### Extra Notes (Optional)

I wanna note and say that for me and a few other friends they are having the same exact issues as me. But for others they aren't having this issue at all and either receive a prompt that its "jammed" or are able to successfully get inside the register. I also want to note that I heard from a friend that they tried lock picking into a register they got no notification that they were in, didn't receive any items or skill check, and a few minutes later the police ended up arriving and arrested him for robbing the store. Even though he did not gain any items and got no confirmation that he got into the register at all. 

Overall I just think its very buggy I'm not to sure why but it seems everyone I talk to it either works for them completely or it doesn't work for them at all.

### Log File

[CitizenFX_log_2023-07-02T112752.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11929393/CitizenFX_log_2023-07-02T112752.log)

**Comment by xXJamieXx** [comment]
Tweaked slightly. Let me know if its still an issue.

**Comment by shadhearts** [comment]
Still encountering the same issues.

Not getting a response when lock picking registers.

![image5](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/138297554/50e45d6b-907f-46f2-83fd-c895a25d7b1e)

Police are online, and even if there isn't enough for a store robbery to take place I should still receive a prompt letting me know that there aren't enough units online and or the registers are jammed.


https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/138297554/353f6249-d91c-4d41-980d-2aa484606024


This is my logs from the session today:

[CitizenFX_log_2023-07-03T085444.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11935615/CitizenFX_log_2023-07-03T085444.log)

**Comment by xXJamieXx** [comment]
Closing this as haven't heard of any more reports of this.
