### ISSUE TITLE
[BUG] Floating structure

### ISSUE THREAD

**Issue by SketchyNath** [ParadoxGamingRP/bugs-and-suggestions#1574]
### Your Discord Name

SketchyNath#6455

### A clear and concise description of what the bug is

There appears to be a floating structure above the impound at postal 394, best seen when approached from postal 200

### Steps to Reproduce the Bug

1. Head to postal 394 from 'Power Street & Adams Apple Blvd'
2. You will see the floating structure above the impound building

### Expected Behavior

I expected there to not be a floating structure

### Screenshots/Videos

https://i.imgur.com/J3OxEQx.jpeg

**Comment by ithegreatgatsby** [comment]
Fixed for next restart
