### ISSUE TITLE
[BUG] V plushi wont go into collectible pouch

### ISSUE THREAD

**Issue by tommytwoshotty** [ParadoxGamingRP/bugs-and-suggestions#1575]
### Your Discord Name

tommytwoshotty

### A clear and concise description of what the bug is

The V plushie that was sold at glizzys will not go into the glizzy collectors puch

### Steps to Reproduce the Bug

1. Obtain V Plushie
2. Open glizzy collectibles Pouch 
3. Attempt to put V plushie into pouch
4. Plushie goes back into pocket instead of pouch

### Expected Behavior

Be able to put the plushie into pouch with the rest of the plushies i put there

### Screenshots/Videos

![FiveM_b2802_GTAProcess_YrPCNvdGQ2](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/92126060/c4b5c60f-032f-4601-ad9e-c8326968c029)

**Comment by ithegreatgatsby** [comment]
next restart
