### ISSUE TITLE
[BUG] Chopping Local Not Taking Car 

### ISSUE THREAD

**Issue by Flora45** [ParadoxGamingRP/bugs-and-suggestions#1576]
### Your Discord Name

Flora40

### A clear and concise description of what the bug is

I seems when attempting to drop off the car I was chopping to the local at postal 1050 I could not third eye him to turn in the car. Not sure of this is an issue at multiple locations. Could just be that location. 

### Steps to Reproduce the Bug

1. Attempt to turn car in to chopping local
2. Cannot third eye local to turn car in 

### Expected Behavior

Turn car into local be using your third eye. 

### Screenshots/Videos

https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/79613077/a0a03bb1-e4fc-429f-b2bf-39f23862e2c7

### Log File

[CitizenFX_log_2023-07-03T064937.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11935483/CitizenFX_log_2023-07-03T064937.log)

**Comment by xXJamieXx** [comment]
@Flora45 You're not holding a car part... You need to disassemble one from the car first...

**Comment by Flora45** [comment]
Oh damn lmao that's embarrassing. I'll figure it out in city, thanks!
