### ISSUE TITLE
[ENHANCEMENT] Class 2 Weapons showing on back of body 

### ISSUE THREAD

**Issue by RoguIsAwesome** [ParadoxGamingRP/bugs-and-suggestions#1578]
**Your Discord Name**
rogue_69

Make it so that if someone has a class 2 on them that it shows on the back of their character 

Obviously this makes it more realistic and also will allow fairness for both criminals and cops

**Comment by ithegreatgatsby** [comment]
been requested before and its, not something we are fond of or are willing to add right now and all the scripts for it just make it jank like a floating gun
