### ISSUE TITLE
[BUG] cant park imports at 178 fire station

### ISSUE THREAD

**Issue by Dez505** [ParadoxGamingRP/bugs-and-suggestions#1587]
### Your Discord Name

dez505

### A clear and concise description of what the bug is

whenever i try and park my mustang GT or my Porsche 911 turbo at the fire station it says "cant store this vehicle" or it doesn't give me the option to park it in the F1 menu.

### Steps to Reproduce the Bug

1. get a mustang GT or a 911 turbo
2. try parking it at 178 fire station
3. dosnt work

### Expected Behavior

be able to park all vehicles

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/1ihQivaO63C-Yh/d1337kSaZk1K?invite=cr-MSx3Tk8sMzQ3OTM3MTAs

**Comment by ithegreatgatsby** [comment]
made some tweaks for next restart should fix the issue
