### ISSUE TITLE
[ENHANCEMENT] Glass for Sale

### ISSUE THREAD

**Issue by H0lyPika** [ParadoxGamingRP/bugs-and-suggestions#1589]
**Your Discord Name**
holypika#9815

**Describe the annoyance**
So have you ever done metal detecting and gotten some glass bottles recycled them for the raw broken down glass but then had no where to sell it would be nice for the hard working Civs to have a place to just sell there over abundance of glass much like how your able to sell your other materials?

**To Reproduce**
Metal Detect get glass bottle
recycle glass bottle 
Get Glass

**Requested behavior**
Being able to take Recycled Raw Glass to a Local buyer and Sell the over abundance you have to said local helps give Civs another form of income and gives more of a reason to let go of the tens or thousands of glass people are hoarding

**Comment by ithegreatgatsby** [comment]
next restart

**Comment by H0lyPika** [comment]
Thank you!
