### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by SHoover80** [ParadoxGamingRP/bugs-and-suggestions#1591]
### Your Discord Name

Whiskey Sheppard

### A clear and concise description of what the bug is

I'm no longer recieving texts from the guy that gives you missions (cars to steal) for Chop Shop. 

### Steps to Reproduce the Bug

I used to be able to go to guy who give out jobs requesting what cars to find and steal. 
I had deleted out old text messages from my phone. 
I went back to guy (T-ANON I Believe was his name) and requested job for chop shop. 
I recieved notification stating I recieved a text but no new texts showed up on my phone. I clicked on notification to see if it would take me directly to new text from T-ANON listing what car to go find and have chopped. 

### Expected Behavior

Suppose to recieve a text message with details on which car to find and steal. 

### Screenshots/Videos

![Screenshot 2023-07-09 162625](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/43644167/b3574851-3336-44be-af67-deb8b87e351d)

### Extra Notes (Optional)

I've restarted firewall and PC, I also cleared out cache in FiveM folder following directions provided in Discord. I also tried to reset phone ingame.  Issue still persists. 

### Log File

[CitizenFX_log_2023-07-09T204902.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/11996099/CitizenFX_log_2023-07-09T204902.log)

**Comment by xXJamieXx** [comment]
create a conversation with T. ANON and you'll receive the messages again.

**Comment by SHoover80** [comment]
How would I go about doing that? Just send a text to T.ANON? Or does he have a number?

**Comment by xXJamieXx** [comment]
T. ANON is the number

**Comment by SHoover80** [comment]
Thank you for response, I'll give that a try and let you know if it worked.

**Comment by SHoover80** [comment]
Yup, that worked. I see the list now. Thank you again.
