### ISSUE TITLE
[BUG] C class boost

### ISSUE THREAD

**Issue by NickNubbz** [ParadoxGamingRP/bugs-and-suggestions#1592]
### Your Discord Name

NickNubbz

### A clear and concise description of what the bug is

Every time i try to do a C class boost the car is nowhere to be found. Ive only been able to try a C class on 2 different occasions and both times were in the same location with the car no where to be found. I also had staff confirm the car was not there. D class seems to work fine from my experience. Im not sure if the C class is bugged or if its the location.

### Steps to Reproduce the Bug

Start C class boost
Search for car

### Expected Behavior

All boost cars should spawn and be obtainable.

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/74627555/9a6690be-fffb-4af7-8b4e-f7f845b995d0)

### Extra Notes (Optional)

The image above is the location i got twice where the car would not spawn. assuming its the location thats it.

**Comment by NickNubbz** [comment]
UPDATE: just did a C class, different location and was able to find the car just fine.

**Comment by NickNubbz** [comment]
UPDATE #2: Got c class in the location showed above and was able to find the car. im now not sure what causes it.

**Comment by JnKTechstuff** [comment]
Ima be honest, 90% of the time its operator error. If you cannot find the car and think its a bug open a staff ticket and a staff member can check the area for the plate. If they find it they will simply inform you whether it exists or not.
