### ISSUE TITLE
[BUG] empty gas tank on boost cars

### ISSUE THREAD

**Issue by NickNubbz** [ParadoxGamingRP/bugs-and-suggestions#1595]
**Your Discord Name**
NickNubbz

**Describe the annoyance**
It’s not so much a issue with D class boosts but C and above getting a almost empty gas tank upon retrieving the vehicle is frustrating. It’s difficult to stop and gas up when the cops are getting a ping to your location every 5 seconds. 

**To Reproduce**
[Steps to reproduce the annoyance]
1. Start C class boost
2. Lock pick the targeted car
3. Have almost no gas

**Requested behavior**
All boosts should come with a full tank of gas or at least half.

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by xXJamieXx** [comment]
Should have full gas so not sure.

**Comment by NickNubbz** [comment]
well i guess its a bug then lol. multiple occasions we got the car with barely any gas.

**Comment by xXJamieXx** [comment]
Can't reproduce this. They've all had full gas for me.

**Comment by NickNubbz** [comment]
I don’t understand then because still like 4 boosts yesterday had less than a quarter of a tank and even led to me getting arrested cause we didn’t have enough gas for the persuit.
