### ISSUE TITLE
[ENHANCEMENT] checking strikes on a vehicle

### ISSUE THREAD

**Issue by NickNubbz** [ParadoxGamingRP/bugs-and-suggestions#1596]
**Your Discord Name**
NickNubbz

**Describe the annoyance**
I’m not sure if it is possible to check strikes on a vehicle outside of being a Leo but it would be nice if we could check strikes by thinking “/strikes” followed by the plate number or something along those lines. Assuming strikes carry over with selling the car to someone else it would also be useful to check it before purchasing a car off someone. 

**To Reproduce**
[Steps to reproduce the annoyance]
1. 
2. 
3. 

**Requested behavior**
Be able to check strikes somehow.

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
Like I said I’m not sure if there is a way to check strikes as a civilian. It’s just a suggestion.

**Comment by unforgiven8233** [comment]
maybe go ask someone Like a lawyer or a police officer and rp it out
