### ISSUE TITLE
[BUG] Controller Driving FPS issue

### ISSUE THREAD

**Issue by JonnyB371** [ParadoxGamingRP/bugs-and-suggestions#1597]
### Your Discord Name

Johnny_B

### A clear and concise description of what the bug is

while driving with a controller the left bumper/aim button does not force first person but the left trigger/brake does force first person when you have a weapon out, it shows a crosshair for both buttons

### Steps to Reproduce the Bug

drive with a controller, pull out weapon, and Aim and Brake 

### Expected Behavior

I expected to be put into first person while aiming not braking

### Screenshots/Videos

https://streamable.com/b9954h

**Comment by xXJamieXx** [comment]
Left trigger is the aim button on controller so confused on this one?

**Comment by LittleH751** [comment]
> Left trigger is the aim button on controller so confused on this one?

Not when in a vehicle. When you're driving, left trigger is break/reverse and the bumpers act as shoot and aim.

**Comment by JnKTechstuff** [comment]
Added additional control mappings to keybind activation
