### ISSUE TITLE
[ENHANCEMENT] Increasing Vehicle Tracker Range

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#1598]
**Your Discord Name**
Shrew#1219

**Describe the annoyance**
With recent car theft, finding your car where they left it is nigh impossible with 0.2 mile tracking radius. And has led to some sour hours trying to find the car to no avail.

**To Reproduce**
[Steps to reproduce the annoyance]
1. Car gets stolen
2. >0.2 miles car can not be found try impound.
3.  Car doesnt disappear even if ocean dumped.

**Requested behavior**
1. An increase on tracker range to 0.5- 1 mile.
2.  Bring back cars that are lost for >1 hour to be county towed.

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by xXJamieXx** [comment]
There is no range on it...?

**Comment by tusktheshrew** [comment]
You have to be within 0.2 miles of the vehicle to track it.

**Comment by xXJamieXx** [comment]
Theres nothing to limit the range on it so confused.

**Comment by tusktheshrew** [comment]
So I had to search for a car for 2 hours and just gave up trying to find it. Because the car was not nearby nor was in the impound. . Due to someone stealing it. Cars do not disappear, and I travelled up and down the city trying to find it to no avail as the phone to track the vehicle said You are not close enough to track, try the impound.

**Comment by tusktheshrew** [comment]
While testing how far I could go from another vehicle to track it. I couldn't go further than 0.2 miles away from the car or it would say it was too far to be tracked.

**Comment by xXJamieXx** [comment]
Alright let me do some investigation.
