### ISSUE TITLE
[BUG] Bugstars Can't park or take out stored Vehicles etc

### ISSUE THREAD

**Issue by cythioan** [ParadoxGamingRP/bugs-and-suggestions#1599]
### Your Discord Name

liltikitorch

### A clear and concise description of what the bug is

For the past 2 days I ahve been having issues with parking. I have a Bison stored at Bugstars but when I step onto the platform to take out said Vehicle , the parking icon does not appear. I have tried several vehicles seeing if any would trip the sensor none worked. I also can't park a tuner or a bike at the mines. I tired two different vehicles thinking maybe since its a quarry that only a truck can park there but couldn't test because my Bison is here at Bugstars. So I parked the bike at Alta (where I can access all stored vehicles that are parked at that location same can be said for the trucking depot.) I ran to bugstars thinking maybe with out a vehicle insight it won't have any interfearence but it stil didn't trip. I made sure that the Location that the Bison was stored was indeed bugstars but still cant see the park icon or on the wheel. Deadles tried helping me after I submitted a ticket and they tried as best as they could to figure it out and suggested I submit a bug report. Right now I can't store any vehicles anywhere excpet trucking depot and alta  street, unsure what i can store at mines since I can't try my truck since I can't get to it.

### Steps to Reproduce the Bug

1. Relog several times ( at different time periods )
2. Letting a few days go by for a couple server resets
3. Tried different vehicles at different locations
4. stored all vehicles and ran to bison location hoping that would help did not
5. relogged
6. Finally submitted ticket and was told to submit bug report

### Expected Behavior

To be able to store vehicle and take it back out.

### Screenshots/Videos

I can get a vid if needed it is not formatted yet
![bugreport](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/30983170/e876a33a-a342-4db7-8436-2e3934d993c5)

### Extra Notes (Optional)

Not sure if this provides anything but this happened right before a tsunami and it was raining out when i went into my apt at alts st the apt was flooded everywhere i then logged out and the next day noticed all this stuff then waited the 2 days and tried all those steps above . 

### Log File

[CitizenFX_log_2023-07-13T075233.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12037131/CitizenFX_log_2023-07-13T075233.log)
[CitizenFX_log_2023-07-13T075152.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12037132/CitizenFX_log_2023-07-13T075152.log)

[CitizenFX_log_2023-07-13T075152.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12037134/CitizenFX_log_2023-07-13T075152.log)
[CitizenFX_log_2023-07-13T075233.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12037135/CitizenFX_log_2023-07-13T075233.log)

**Comment by SaraLef** [comment]
Can confirm, I cannot park at Slurp&Go or mines with my car.
