### ISSUE TITLE
SUGGESTION - car

### ISSUE THREAD

**Issue by omelette44** [ParadoxGamingRP/bugs-and-suggestions#1600]
Discord: @greasy44

Car suggestion - sentinel sg4, https://www.gta5-mods.com/vehicles/ubermacht-sentinel-sg4-add-on-liveries

Understand this won't be near the list of priorities but after learning about this I thought I'd be a nice addition to Kildares and would most likely be very popular.

![db5680-0](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/131989733/ed848869-028e-4f86-98be-b45d583b9274)

**Comment by ithegreatgatsby** [comment]
Will add it to the car team list to be looked into.
