### ISSUE TITLE
[BUG] No trash Bin for Trash Job

### ISSUE THREAD

**Issue by DraconicRebel** [ParadoxGamingRP/bugs-and-suggestions#1604]
### Your Discord Name

draconicrebel

### A clear and concise description of what the bug is

So when I am doing the trash job, I was just minding my own business when one of the locations has no trash bin for me to pick up trash.

### Steps to Reproduce the Bug

N/A

### Expected Behavior

It was expected to pick up the trash when the bin should be there.

### Screenshots/Videos

Heres the proof.
![Screenshot 2023-07-15 062809](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/100647205/80ea5600-c3ff-47b5-8623-43a9de73c78d)
![Screenshot 2023-07-15 062825](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/100647205/e0b8ff4b-d29c-4b7b-ad6b-c6e8bf850d75)

**Comment by xXJamieXx** [comment]
#1740
