### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by JamosesCrust** [ParadoxGamingRP/bugs-and-suggestions#1606]
### Your Discord Name

Hood TM#0260

### A clear and concise description of what the bug is

You are able to park cars at the mirror park parking, but are unable to pull them out.

### Steps to Reproduce the Bug

Park your car at mirror park.

### Expected Behavior

Be able to pull your car out.

### Screenshots/Videos

![Screenshot 2023-07-15 134727](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/107367589/2f74bd44-e87f-4071-a694-b48a7087c5a3)

**Comment by JamosesCrust** [comment]
I just found it, its just in a wierd spot.

**Comment by ithegreatgatsby** [comment]
I fixed it better for next restart
