### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Trouble05** [ParadoxGamingRP/bugs-and-suggestions#1608]
### Your Discord Name

Trouble D

### A clear and concise description of what the bug is

I went to the commercial lot to buy a vehicle with more storage space. I test drove several vehicles and checked the trunk during the test drive and they all said 7500 for storage. I ended buying the lurcher hearse and after i purchased it i checked the trunk and it 380 for storage.

### Steps to Reproduce the Bug

Test drive lurcher at the commercial lot
Get out of vehicle and check trunk during test drive should say 7500
Purchase vehicle then check trunk again and the storage isnt the same

### Expected Behavior

If possible i would like a refund along with the upgardes since i wont be able to use the vehicle for intended purposes.

### Screenshots/Videos

I didnt take a screen shot or video

### Log File

CitizenFx_log_2023-07-16T020156

**Comment by ithegreatgatsby** [comment]
no way to really make it show since a lot of things are tweaked individually
