### ISSUE TITLE
[BUG] S Class Swaps

### ISSUE THREAD

**Issue by jkaejkae888** [ParadoxGamingRP/bugs-and-suggestions#1609]
### Your Discord Name

jkaejkae888

### A clear and concise description of what the bug is

S class boosts are giving out standard engines instead of swaps like intended.

### Steps to Reproduce the Bug

Start A class boost and it will be stock.

### Expected Behavior

Start and have a swap in the cars

### Screenshots/Videos

N/A

### Extra Notes (Optional)

I've personally done an S class today and it was stock (D10) and other crew members have also done S classes and they've all been stock cars. A few of these S class we have feel no different then an A class because at stock there very similar on speed but only difference you tend to get a whole lot more attention from PD plus the much larger PDX pay in risks.

**Comment by JnKTechstuff** [comment]
fixed
