### ISSUE TITLE
[ENHANCEMENT] Mustaches for girls

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1612]
**Your Discord Name**
ssara

**Requested behavior**

I've seen that males have fake mustaches as masks. Would appreciate it if it wasnt locked behind gender. 
That's all folks, thank you!

**Comment by ithegreatgatsby** [comment]
They are designed for the male model only and do not work on female peds with out looking jank. From looking around does not look like any are really made for females
