### ISSUE TITLE
[ENHANCEMENT] PD notepads

### ISSUE THREAD

**Issue by unforgiven8233** [ParadoxGamingRP/bugs-and-suggestions#1618]
**Your Discord Name**
Forgotten

**Describe the annoyance**
can't put the torn papers from the pd notepad into the pd briefcase

**To Reproduce**
[Steps to reproduce the annoyance]
1. tare a page out
2. try to put page into the investigations briefcase
3. not be able to fit it in

**Requested behavior**
let the briefcase be able to hold the torn papers

**Comment by Darahz** [comment]
Added yesterday
