### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by XeloGaming** [ParadoxGamingRP/bugs-and-suggestions#1620]
### Your Discord Name

xelogaming

### A clear and concise description of what the bug is

after finishing the tutorial I drove back to my apartment and locked it on the street and went back inside. When I came back out it was not there and not in my impound despite saying it was there.

### Steps to Reproduce the Bug

1. finished tutorial and went back to my apartment leaving my car locked outside. 
2. came back out and car was gone.
3. went to impound to try to pay the fee and it was not there.

### Expected Behavior

car should have gone to the impound and I should have been able to pay the fee to pull it out

### Screenshots/Videos

n/a

**Comment by Darahz** [comment]
In the tutorial it tells you to park your car at a parking spot just for this reason. The car was still "out" on the same place as you left it but in another bucket/dimension. It will probably be in the impound by now.
