### ISSUE TITLE
[BUG] Headbags missing

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#1623]
### Your Discord Name

jojosnmustard

### A clear and concise description of what the bug is

It seems a few days ago all the headbags grew legs and walked away, and the knowledge to make them went along for the ride.

### Steps to Reproduce the Bug

1: Try to craft headbag blueprint
2: It's just a blank square at the crafting bench
3: It does nothing
4: Submit ticket
5: Realize all the existing bags that were made are missing as well
6: Come to github to annoy devs

### Expected Behavior

Be able to craft/store Headbags

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/29337315/c8c09812-9c9d-4ad6-92db-690826d2618c)

The blank square was the Headbag blueprint

**Comment by ithegreatgatsby** [comment]
Waiting on emily to reissue blueprints to double check saving issues
