### ISSUE TITLE
[BUG] Weapon Blueprints

### ISSUE THREAD

**Issue by BrotherDayZ** [ParadoxGamingRP/bugs-and-suggestions#1629]
### Your Discord Name

BDZ

### A clear and concise description of what the bug is

Weapon blueprints are still broken, both discord commands and in-city the weapon blueprints do not work. You can "teach" them the blueprint but it does not show up on the crafting table. No errors in F8 that are related.

### Steps to Reproduce the Bug

1. Receive the blueprint (if already "learned", you must remove the blueprint first before getting the new one)
2. Use the blueprint
3. Check a crafting bench
4. Still not smart enough to make the weapon

### Expected Behavior

n/a

### Screenshots/Videos

n/a

**Comment by JnKTechstuff** [comment]
Should be fixed
