### ISSUE TITLE
[BUG] LFA Hovercraft Handling

### ISSUE THREAD

**Issue by SaintSeven31** [ParadoxGamingRP/bugs-and-suggestions#1630]
### Your Discord Name

seven_prime

### A clear and concise description of what the bug is

The LFA is handling like a peanut/hovercraft/boat again, it lifts with little effort and the weight/gravity of the car feels SUPER off

### Steps to Reproduce the Bug

1. Get a LFA
2. Get in LFA
3. Try to drive
4. Dubai Mode

### Expected Behavior

The LFA to handle like it does normally.

### Screenshots/Videos

https://www.youtube.com/watch?v=T1gwETWKvLc

https://www.youtube.com/watch?v=NbieI6RxTR0

**Comment by ZOIMBIE3** [comment]
Yea i made a bug report too sorry i didn't notice someone had already made one. I am experiencing the same thing.
