### ISSUE TITLE
[BUG] Engine Swaps Transferring speed to other cars

### ISSUE THREAD

**Issue by SamB1997** [ParadoxGamingRP/bugs-and-suggestions#1631]
### Your Discord Name

davefromsunderland

### A clear and concise description of what the bug is

If you get into an engine swap and then get into any other car it will give the car the same speed as an engine swap. 

### Steps to Reproduce the Bug

1. Get into an engine swap
2. Get into any other non swapped car

### Expected Behavior

Not this

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/1lmR1oL8PcfuRP/d1337qgn5kFy?invite=cr-MSxLWXMsNDc3MTczNjAs

**Comment by JnKTechstuff** [comment]
Fixed
