### ISSUE TITLE
[BUG] store robbery payout

### ISSUE THREAD

**Issue by fillingspaces** [ParadoxGamingRP/bugs-and-suggestions#1638]
### Your Discord Name

517

### A clear and concise description of what the bug is

rob store get 26 money bags or about 40k

### Steps to Reproduce the Bug

rob store
wait for timer
open safe 
get 26 money bags 

### Expected Behavior

not to get so much money from a 5 minute robbery

### Screenshots/Videos

.

**Comment by xXJamieXx** [comment]
Thanks for reporting.
