### ISSUE TITLE
[BUG] Bravado Gauntlet Classic R/T NOS

### ISSUE THREAD

**Issue by SharpieOSM** [ParadoxGamingRP/bugs-and-suggestions#1639]
### Your Discord Name

thechosensharpie

### A clear and concise description of what the bug is

On the vehicle "Bravado Gauntlet Classic R/T" the nos purge will not work, the gas coming out of the engine doesn't show up but it says that I am using the nos.

### Steps to Reproduce the Bug

Got Nos installed on car.
Purge doesn't work.

### Expected Behavior

Nos to spray out from under the hood.

### Screenshots/Videos

Dont have any.

### Log File

[CitizenFX_log_2023-07-26T192429.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12176951/CitizenFX_log_2023-07-26T192429.log)

**Comment by Bac0nRamen** [comment]
This is a zmoddler thing which we do not own that program right now
