### ISSUE TITLE
[BUG] SADOT AI Call Bugs

### ISSUE THREAD

**Issue by KretnGaming** [ParadoxGamingRP/bugs-and-suggestions#1640]
### Your Discord Name

KretnGaming

### A clear and concise description of what the bug is

Issues with new jobs..

   - If the job sits past the expired time period, it remains on location. Though the NPC's will multiply several times over and kill each other causing a dead ped pile.
   - If you try to clear the vehicle out after the lets say Roadside call ends, ands you impound the vehicle just to clear the obstruction, it still rewards you with $1k payout.
   - Above is the same if you do like a fuel call & you need to clear the vehicle because its blocking, it will pay you the $1k payout.

So far I've only had fuel calls, no tow or repair calls yet, but figured these needs to be mentioned so it can be corrected.
NOTE: I have only done the above Glitch once per each section that I mentioned, once I noticed the issue I stopped to type this up, if needed I will forfeit the $2k cash.

### Steps to Reproduce the Bug

1. Accept one of the new SADOT Calls.
2. If on one of the calls either let the call expire OR complete the call.
3. IF Call left to expire, NPCs will reproduce ontop of each other & end up killing each other.
4. IF above as well, you try to impound the vehicle to clear an obstruction, you still receive payout.
5. IF you complete call before expire, and impound the vehicle to clear a protentional blockage, will give ADDITIONAL $1k payout

### Expected Behavior

Not give additional payouts.
Peds don't end in an orgy of death.

### Screenshots/Videos

N/A

### Log File

N/A

**Comment by SpiceF0x** [comment]
weeeeeeeeeeeeeee

https://streamable.com/jlxaec
