### ISSUE TITLE
[ENHANCEMENT] Put people in vehicle delay

### ISSUE THREAD

**Issue by SamB1997** [ParadoxGamingRP/bugs-and-suggestions#1642]
**Your Discord Name**
davefromsunderland

**Describe the annoyance**
Putting people in vehicles is instant and can create some very annoying/weird situations where someone shows up on a scene. Gets out of their car for 2 seconds and drives away with somebody now in their car. 

**To Reproduce**
1. Put someone in your vehicle
2. 
3. 

**Requested behavior**
Some sort of delay/timer for putting someone in a vehicle even if its just a second or two it will allow cops/anyone to stop people from just randomly showing up and instantly putting someone in their car giving the cops no chance to stop them. 

**Screenshots**

**Additional context**

**Comment by JnKTechstuff** [comment]
This seems like it needs discussions. Post this in the feedback section of the discord and see what the community thinks and what an appropriate amount of time would be.

**Comment by xXJamieXx** [comment]
Closing this as no feedback post made.
