### ISSUE TITLE
[BUG] icepacks is a can

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1645]
### Your Discord Name

ssara

### A clear and concise description of what the bug is

when you apply icepacks it looks like youre holding a can instead

### Steps to Reproduce the Bug

apply ice pack
hold a can 

### Expected Behavior

apply ice pack
not hold a can

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/98127638/ac7e349d-e5cc-4b83-8f08-3bce6a663a26)

**Comment by Darahz** [comment]
Changed it to a package instead
