### ISSUE TITLE
[ENHANCEMENT] "Deposit Only" permission option for gang bank accounts. 

### ISSUE THREAD

**Issue by jplink420** [ParadoxGamingRP/bugs-and-suggestions#1650]
**Your Discord Name**
j_plink

**Describe the annoyance**
Right now, there is no way for a gang to allow their non-commanding members to directly make deposits (and not withdrawals) into their gang fund. IRL, its possible to have "Deposit Only" cards for bank accounts, that only allow that cardholder to deposit into that account. I was also let know that to add a person to a gang bank account, it requires devs to go in and manually add that person. Perhaps this is something that could also be remedied with this? 

**To Reproduce**
1. Have some completely legal and clean cash
2. Want to contribute to your group's ledger and fund
3. Have to give the money to your leader
4. Rely on the trust of criminal delinquents to deposit all of the money you gave them into your group's bank account.

**Requested behavior**
Be able to see the fund of the gang I am in and only have an option to "Deposit" into the account. Be able to adjust these permissions via Boss Menu, rather than needing a dev to manually go in an edit the permissions. Let the leaders of a gang set what Ranks/Grade can make deposits and/or withdrawals and/or see the account altogether.

**Comment by Bac0nRamen** [comment]
I would bring this up in the table under discussions. Since it would effect all gangs

**Comment by JnKTechstuff** [comment]
Completed
