### ISSUE TITLE
[ENHANCEMENT] Make Weed Great Again

### ISSUE THREAD

**Issue by jplink420** [ParadoxGamingRP/bugs-and-suggestions#1652]
**Your Discord Name**
j_plink

From the cop side, I have not investigated somebody selling weed to locals in quite some time. And from the crim side, there is almost no point in running weed when the alternative option of drugs to pedal to locals is much more fun and lucrative. While this makes sense, as the alternative requires more steps and more risk, it would be nice to give a reason for us to start supplying the locals with Sungrown, San Andreas Cannabis again. With the changes made to make drugs take longer to grow, it would be nice to have weed be slightly more in-depth. As well, with K9 implemented, it would be cool to have more uses for the K9 on calls like this. 

Suggestions for making weed great again:

-Decrease how much locals pay to slightly lower than what they were when weed was first introduced, but increase the amount of bags locals are willing to buy at one time to encourage people to actually do it and not have to sit on 200 bags of weed for tens of hours on end. 

-Optionally, Be able to choose to use the weed table to roll joints of the weed with rolling papers that you buy from the gas station and resell them as prerolls to locals at a slight increase in price and quantity. You could for example, bag half of what you grow, and roll the other half.
 
-Alternatively, be able to smoke these joints that you roll, and to ensure that business is not taken away from the regulated, taxed cannabis at Smoke On The Water, have each joint you smoke have an effect that is totally random, positive or negative. (Could be anything random, from draining your hunger fast with no visual effect, as the weed you grew was trash, to a visual effect with no other effect, as you didn't cure your weed properly ; to giving you a burst of speed for a few seconds, maybe you grew some chronic Sour Diesel; or draining your thirst, giving you drymouth from the mid-grade weed you grew; Or maybe you get super stressed off of weed that was grown with harsh chemicals.) Since the plants we grow are an "unknown strain", this makes sense. This would make it so if people want good, high-quality weed that will act like the consumer wants it to, they have to fork over the money at Smoke On The Water. This would also be a way for crims to try and cover up that they are selling illegal weed. They could, for example, claim that the weed was bought from Smoke on The Water, and they rolled it themselves. Or maybe some people just want to smoke the weed they grow for the pure RP of it.

-Tweak suspicious persons call to come in for selling weed to locals slightly more, but less than coke, as locals in San Andreas probably aren't going to be too pressed over somebody selling untaxed weed on the corner.

-Add a longer cooldown timer for when people move away from the area they were selling in to encourage people to stay in the same place and work the corner longer. Giving PD more time to respond. 

--Make stress level go up slightly with every sale you make, people could try smoking the joints they have on them to try and relieve this stress, or they would need to use something else that could be an indicator of stress to an onlooker.

Things that are probably too big of an ask, but figured I would throw in anyway to try and encourage some sort of optional conflict with weed;

-Use the Meth lab interior from GTA Online to act as a Lab to make cannabis concentrates like shatter, resin, distillate, vape cartridges, etc. These would spawn and act in similarly to coke labs, one location per restart with a slightly different indicator of the location. Could even make it so you need Glass and Steel to make Vape Cartridges after you make the distillate in the lab, or use glass and plastic to make a container for the concentrate, much like how you need to make bags to bag the weed, then fill the vape cartridges or the package in the lab. In a similar fashion to coke labs, have a multi-step process that requires time and holding down the lab, and have it like Coke labs where it is a KOS zone. Afterward, you can sell a single vape cartridge, gram of shatter, gram of resin, etc. to locals for about the same amount of raw buds that you put in with a small bonus of 10-25%. This would also give PD another thing to investigate and give DTF more content, investigating, staking out and busting these labs. This would be a completely optional step to weed, allowing people who don't want conflict with weed to avoid it if they wish. The payout for working the lab would obviously have to be worth it.

-Make local gang peds agro on you as a form of "pressing" you when you are trying to sell any type of drugs on their turf. (FDF Peds on Fourm, Balla Peds on Grove, Triad Gang peds in Little Seoul, Lost MC peds at the Lost MC compound, etc.) You can choose how to respond to this, you can try and take them down for pressing you, or you can run away. If they decide to shoot, it is more likely for PD to respond. 

These were just a few ideas I had that I wanted to throw here before I forgot about them, but it would be interesting to see what could be made out of weed as it stands currently.

**Comment by JnKTechstuff** [comment]
We have implemented some of your suggestions and hopefully this breathes some life back into the weed game
