### ISSUE TITLE
[BUG] Fishing rod duping

### ISSUE THREAD

**Issue by tommytwoshotty** [ParadoxGamingRP/bugs-and-suggestions#1653]
### Your Discord Name

tommytwoshotty

### A clear and concise description of what the bug is

When attempting to stack bait in my apartment  stash onto each other it acts as if im baiting a hook then gives me a fishing rod thats broken even when you have no fishing rod

### Steps to Reproduce the Bug

1. Open apartment stash
2. Combines two stacks of the same bait into one stack to save room
3. Get broken fishing rod in pocket even when no fishing rod  is in hand

### Expected Behavior

Be able to stack the bait without issues

### Screenshots/Videos

https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/92126060/2fe8f65f-66a3-409c-94ba-e1986fbdf500

### Log File

[CitizenFX_log_2023-07-29T191447.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12208057/CitizenFX_log_2023-07-29T191447.log)

**Comment by JnKTechstuff** [comment]
Fixed
