### ISSUE TITLE
[BUG] Sultan RS  is a glass cannon

### ISSUE THREAD

**Issue by ZOIMBIE3** [ParadoxGamingRP/bugs-and-suggestions#1655]
**Your Discord Name**
ZOIMBIE#5888

**Describe the annoyance**
I have a sultan RS with a Subaru swap. Apparently the car is classified as a super car, which is making it a glass cannon. The car is not good enough to be a glass cannon and there is no need for it. Once u hit 50mph and u tap something it will just 100% red engine. If no one can fix the car im going to see if nismo's will swap it out because the car is undrivable. you hit something going above 50mph even side swipe something and its red engine right away.
**To Reproduce**
[Steps to reproduce the annoyance]
1. get a sultan rs
2. set limit to 50mph
3. crash into wall

**Requested behavior**
The car will red engine every time something is hit.

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by ZOIMBIE3** [comment]
https://medal.tv/games/gta-v/clips/1mfXBjKrS_-5BY/d1337ekk9kBW?invite=cr-MSxZd08sMTk1MjU5MTY3LA

**Comment by Bac0nRamen** [comment]
next restart should be better. The car will stall tho but wont break with just one crash now
