### ISSUE TITLE
[ENHANCEMENT] Allow Civ/Crim Use of LEO Cuffs

### ISSUE THREAD

**Issue by xaroht** [ParadoxGamingRP/bugs-and-suggestions#1659]
**Your Discord Name**
_mk.

**Describe the annoyance**
It doesn't really make sense that if I have LEO cuffs I can't just use em, feel like it's a simple enough concept. Even for the dumbest of criminals.

**To Reproduce**
[Steps to reproduce the annoyance]
1. Be cuffed for being a goofy goober
2. Run around like a mad man trying to be uncuffed
3. Go to use LEO handcuffs but to no avail, you have no success and cannot uncuff your friend.

**Requested behavior**
For everyone, not just people clocked into LEO to be able to use handcuffs 

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by Bac0nRamen** [comment]
Pd cuffs are just there for the item they need to be able to cuff and uncuff.  As far as criminal goes these things in the server that will allow u to do what u want
