### ISSUE TITLE
[BUG] haligans and breaching charges broken

### ISSUE THREAD

**Issue by Dez505** [ParadoxGamingRP/bugs-and-suggestions#1660]
### Your Discord Name

dez505

### A clear and concise description of what the bug is

when using haligans or breaching charges you cant open anything 

### Steps to Reproduce the Bug

1. have haligan in hand
2. hit Break down door
3. nothing happens

### Expected Behavior

be able to unlock doors with the tools we have

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/1mmcz28uMkfIuI/d1337eyhlSUb?invite=cr-MSxEY28sMzQ3OTM3MTAs

https://medal.tv/games/gta-v/clips/1mmtV8ndVVuwPU/d1337TdIWSAZ?invite=cr-MSw3THYsMzQ3OTM3MTAs

**Comment by Bac0nRamen** [comment]
should be fixed
