### ISSUE TITLE
[BUG] Drauger and Outlaw dont Spawn

### ISSUE THREAD

**Issue by PadawanPepsi** [ParadoxGamingRP/bugs-and-suggestions#1663]
### Your Discord Name

padawanpepsi

### A clear and concise description of what the bug is

When i try to take out the new drauger or outlaw, after about 10-15 seconds i get told i get the keys but the car never appears. The car is also taken out of the motor pool numbers. 

### Steps to Reproduce the Bug

Try to take out drauger

### Expected Behavior

spawn new car i want to play with

### Screenshots/Videos

https://i.imgur.com/7Wh0JRb.png

https://i.imgur.com/kQZJ8Pa.png

### Log File

[CitizenFX_log_2023-08-01T011616.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12223679/CitizenFX_log_2023-08-01T011616.log)

**Comment by Bac0nRamen** [comment]
This was working fine earlier for others. Im gonna guess since its new its taking a bit to load on your end

**Comment by PadawanPepsi** [comment]
i was thinking the same but it just never showed does that F8 error tell you anything?

**Comment by PadawanPepsi** [comment]
tried deleting my cache and did nothing
