### ISSUE TITLE
[ENHANCEMENT] Enter QOL report title

### ISSUE THREAD

**Issue by Zeus608** [ParadoxGamingRP/bugs-and-suggestions#1665]
**Your Discord Name**
[zeus608]

**Describe the annoyance**
[For our fires alarms they aren't working for a lot of our calls when we get on a call and when we leave the building the smoke lingers to long so it takes like 30 seconds for it to clear]

**To Reproduce**
[Steps to reproduce the annoyance]
1. Turning down the time smoke stays in our eyes
2. Fixing the alarm
3. 

**Requested behavior**
[I want the smoke in our eyes to be cleared in 5 seconds and to be cleared when were far enough away from the burning building, and to fix the alarms in the buildings so that they are going off when we get on site.]

**Comment by JnKTechstuff** [comment]
This is confusing and incorrectly filled out.
