### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by joaeeeea** [ParadoxGamingRP/bugs-and-suggestions#1666]
### Your Discord Name

eggos

### A clear and concise description of what the bug is

ragdolling through walls and doors

### Steps to Reproduce the Bug

1. Jump towards a wall or door anything will work (DEPENDS ON THICKNESS OF WALL)
2. Ragdoll when you touch the wall midair
3. If work you should start to spaz out like crazy
4. If worked you will be on the other side (may lose hp)
extra: only works with some walls like kildares

### Expected Behavior

I expected it to just make me ragdoll onto a wall but one day i was bored and tried it at the modshop and it just happenedw

### Screenshots/Videos

N/A

### Extra Notes (Optional)

N/A

**Comment by JnKTechstuff** [comment]
Thats a GTA thing and if you are caught doing anything to glitch through walls you can be banned. There are a few ways to break GTA that we all know.
