### ISSUE TITLE
[BUG] House Not Loading in

### ISSUE THREAD

**Issue by RoseiiNaytool** [ParadoxGamingRP/bugs-and-suggestions#1670]
### Your Discord Name

Roseii/Sen

### A clear and concise description of what the bug is

The Yellow Jack apartment stays on a black screen that shows as loading, no matter if you try loading in there when you come into the city, or from within the city already loaded in. 

### Steps to Reproduce the Bug

1. Try to Enter House
2. Black screen for about 20 seconds
3. Black screen with loading constantly in the bottom right corner

### Expected Behavior

Being able to use the house so that I can access the storage and clothing to open the yellow jack. 

### Screenshots/Videos

Black Loading Screen Image: https://cdn.discordapp.com/attachments/1049113517749456998/1136418232702611636/image.png

f8 Error script: https://cdn.discordapp.com/attachments/1049113517749456998/1136418205179588636/image.png

### Extra Notes (Optional)

I had to force shut down, it didn't kick me from the game.

**Comment by RoseiiNaytool** [comment]
I just thought of this, I started having these issues after trying to place items up there. I got the storage and clothing put down, I had to restart after both of these because it froze, when I came back in and placed a carpet I left the apartment and neither I or Alex Ghost/ Diggie Diggie could get into it, we got the same issue.

**Comment by SwickMachine** [comment]
I am having the same issues as well. After placing a clock down, it was not the direction I had placed it. After attemting to fix it, I relogged. After attempting multiple times by logging in and selecting the house and also by logging in somewhere else and entering, still same result.  
![FiveM_b2802_GTAProcess_8fOPYz3zey](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/110204569/78cbd4b6-0d4e-4732-bf0f-6c89e8cce5e8)

**Comment by erniexhamer** [comment]
I am having the same issue. The last thing i attempted was to delete a table. i then exited and when i reentered, i got the same loading screen state 
[CitizenFX_log_2023-08-03T004849.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12245821/CitizenFX_log_2023-08-03T004849.log)
![FiveM_b2802_GTAProcess_YOY0vCxwgQ](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/66091924/21ef9815-fc28-4834-8873-bc5cf67ab4e5)

**Comment by xXJamieXx** [comment]
> I am having the same issue. The last thing i attempted was to delete a table. i then exited and when i reentered, i got the same loading screen state [CitizenFX_log_2023-08-03T004849.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12245821/CitizenFX_log_2023-08-03T004849.log) ![FiveM_b2802_GTAProcess_YOY0vCxwgQ](https://user-images.githubusercontent.com/66091924/257972773-21ef9815-fc28-4834-8873-bc5cf67ab4e5.jpg)

Already fixed in dev as stated by labels.

**Comment by erniexhamer** [comment]
> 

Sorry! Roseii asked me to put in a bug report on it just a few minutes ago
