### ISSUE TITLE
[BUG] House garages

### ISSUE THREAD

**Issue by Bendog1957** [ParadoxGamingRP/bugs-and-suggestions#1672]
### Your Discord Name

BenDog57

### A clear and concise description of what the bug is

I can not access the cars in the garage that I share with a friend. I can see the parking garage with my f1. I hit open garage and nothing happens.

### Steps to Reproduce the Bug

Tried to restart multiple times
tried different houses with garages owned by friends that I have keys to
I can see the ones at my house that I own, but not at other friends' houses.

### Expected Behavior

F1 to open the parking garage, open garage, take out car.

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/120426151/6e7b4bff-3fbd-46f4-80c8-74ac8cd274f5)

**Comment by JnKTechstuff** [comment]
Fixed v2 in dev and added error prevention in the meantime.
