### ISSUE TITLE
[ENHANCEMENT] Storage & Wardrobe pre-requisite requests

### ISSUE THREAD

**Issue by SpiceF0x** [ParadoxGamingRP/bugs-and-suggestions#1675]
**Your Discord Name**
spicedf0x

**Describe the annoyance**
Hopefully this is possible! Currently only one option of each, can we please get a few for individuality? I've seen some of these used, they are in no particular order but I think are a nice range.

**Storage**
Cabinet - Large
https://i.imgur.com/H12ivdH.jpeg

Bottoman Unit
https://i.imgur.com/fxEEOSQ.pngcw

Mason Unit
https://i.imgur.com/NJetbfs.jpeg

Book Unit
https://i.imgur.com/IEJHPI2.png

Wood Unit
https://i.imgur.com/4VWj76d.png

Mil Crate 1
https://i.imgur.com/JF5e4N7.png

Safe
https://i.imgur.com/3H21hab.png

Bike Locker
https://i.imgur.com/ZtMpvzo.png

**Wardrobe**
Dressing Table
https://i.imgur.com/Fj2BaJp.png

Armoire Unit
https://i.imgur.com/5edjq0v.png

Coat Rack
https://i.imgur.com/VwZXQec.png

Chest of drawers
https://i.imgur.com/WnJF8Zq.png

or

Chest of drawers 2
https://i.imgur.com/e2jg862.png

**Comment by Bac0nRamen** [comment]
Ohh anyway you can get me prop names?

**Comment by SpiceF0x** [comment]
YES!!

**Storage**
Cabinet - Large
https://i.imgur.com/H12ivdH.jpeg
 "v_res_cabinet"

Bottoman Unit
https://i.imgur.com/fxEEOSQ.pngcw
"v_res_mbottoman"

Mason Unit
https://i.imgur.com/NJetbfs.jpeg
"v_res_msoncabinet"

Book Unit
https://i.imgur.com/IEJHPI2.png
"v_res_tre_smallbookshelf"

Wood Unit
https://i.imgur.com/4VWj76d.png
 "v_res_tre_wdunitscuz"

Mil Crate 1
https://i.imgur.com/JF5e4N7.png
"prop_mil_crate_01"

Safe
https://i.imgur.com/3H21hab.png
"prop_ld_int_safe_01"

Bike Locker
https://i.imgur.com/ZtMpvzo.png
 "bkr_prop_biker_garage_locker_01"

**Wardrobe**
Dressing Table
https://i.imgur.com/Fj2BaJp.png
"v_res_d_dressingtable"

Armoire Unit
https://i.imgur.com/5edjq0v.png
"v_res_m_armoire"

Coat Rack
https://i.imgur.com/VwZXQec.png
"prop_coathook_01"

Chest of drawers
https://i.imgur.com/WnJF8Zq.png
"apa_mp_h_bed_chestdrawer_02"

or

Chest of drawers 2
https://i.imgur.com/e2jg862.png
"hei_heist_bed_chestdrawer_04"
