### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by RandyTowlie420** [ParadoxGamingRP/bugs-and-suggestions#1676]
### Your Discord Name

TrippyTitty

### A clear and concise description of what the bug is

After I process and bag all of my weed that I grew. When I go to the corner with locals near by and i open the men u with z and click on corner selling it says no drugs when i have over 70 bags of weed and it was working yesterday. I have also tried restarting 5m and it doesnt work.

### Steps to Reproduce the Bug

i dont know not that familiar

### Expected Behavior

i didnt expect it it was random 

### Screenshots/Videos

![IMG_4636](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/141373196/733b5da9-8b96-4472-98c8-7e972f263dbe)

**Comment by JnKTechstuff** [comment]
Operator error: Not a bug. You broke it down into joint roll able bags only.
