### ISSUE TITLE
[BUG] <short description>

### ISSUE THREAD

**Issue by KretnGaming** [ParadoxGamingRP/bugs-and-suggestions#1678]
### Your Discord Name

KretnGaming

### A clear and concise description of what the bug is

Houses that you have keys to, you cannot access the garages. 
I attempted this by having the owner of the property remove the keys, then grant me keys back as well, did not correct. In the F8 an error code is thrown, logfile is attached for reference.
[CitizenFX_log_2023-08-04T004447.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12256159/CitizenFX_log_2023-08-04T004447.log)

### Steps to Reproduce the Bug

Attempt to open garage.
No garage prompts.

### Expected Behavior

Garages to work

### Screenshots/Videos

N/A

### Log File

[CitizenFX_log_2023-08-04T004447.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12256163/CitizenFX_log_2023-08-04T004447.log)

**Comment by JnKTechstuff** [comment]
Fixed next restart
