### ISSUE TITLE
[BUG] Goverment employees show as judges if a judge clocks in

### ISSUE THREAD

**Issue by ShaymusSavage** [ParadoxGamingRP/bugs-and-suggestions#1679]
### Your Discord Name

Shay.mus

### A clear and concise description of what the bug is

Clocked in government shows up under judges if an actual judge is clocked in. https://i.imgur.com/tm3IzSW.png

### Steps to Reproduce the Bug

Have someone clocked in as government first. 

Then have a judge clock in.

### Expected Behavior

It show up normally.

Government be under a government tab.

### Screenshots/Videos

https://i.imgur.com/tm3IzSW.png

**Comment by xXJamieXx** [comment]
Shows up fine for me 
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/11248045/1fe77bdb-304e-4fbd-a4c1-aa1d1bd998e3)
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/11248045/1b7da60b-877f-40f5-8fbb-d2e10cc23a13)
