### ISSUE TITLE
[BUG] Yacht AirDrop Not Working

### ISSUE THREAD

**Issue by ColKing** [ParadoxGamingRP/bugs-and-suggestions#1684]
### Your Discord Name

Colt__

### A clear and concise description of what the bug is

When we finished the yacht heist, we got our AirDrop and threw it however after I threw it after a while, my head popped. Then was given an error code and I don't know if it is related but I saved it anyways. However, the AirDrop never came down 

### Steps to Reproduce the Bug

1. Throw AirDrop 
2. Possibly F8 quit counting as a head pop
3. See if AirDrop was still delivered to the Area
4. Loot AirDrop

### Expected Behavior

1. Throw AirDrop 
2. Wait for AirDrop to come
3. Start AirDrop Timer after color match hack
4. Wait for timer 
5. Then Loot

### Screenshots/Videos

N/A

**Comment by JnKTechstuff** [comment]
Yeah I mean idk what you want me to do about your game crashing and the thing your game is controlling failing to execute.

**Comment by ColKing** [comment]
The drop should come its just bad timing head pop that caused it not to come down. Shouldn't it still come down if my crew was still around the area?

**Comment by ColKing** [comment]
Alright, we had it refunded, and I had Jacob throw it this time. Shit is fucked I don't know what to do.

**Comment by JnKTechstuff** [comment]
No one else is reporting issues so maybe operator error idk
