### ISSUE TITLE
[BUG] Items are duping/house stashes keep on duping and removing stuff

### ISSUE THREAD

**Issue by PatrykX904** [ParadoxGamingRP/bugs-and-suggestions#1685]
### Your Discord Name

thisiscorruption

### A clear and concise description of what the bug is

So, yesterday after storm happened my AK duped from my house stash and I didnt think of it much, I put in a staff ticket to get it removed and went on with the rest of my day. Now that another restart has happened my stash duped another AK and I lost some car parts from car scrapping I did yesterday.

### Steps to Reproduce the Bug

1. Put new items into house stash/take an item from house stash and wait til next restart
2. Stash gets rid of anything new put in there and dupes an item that you have taken out

### Expected Behavior

Not to get a dupe of an item you take out/not have an item disappear in stash

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/81855046/61b78c5e-632d-41ee-9bb5-de2065849111)
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/81855046/85611bb6-9604-48f0-ad30-a66e181f9bd6)

### Log File

[Item Dupe report.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12267664/Item.Dupe.report.txt)

**Comment by JnKTechstuff** [comment]
Should be fixed as of the late PM restart yesterday. If it happens after today make a new report
