### ISSUE TITLE
[BUG] /P Prop Issues

### ISSUE THREAD

**Issue by LitrlyD3ad** [ParadoxGamingRP/bugs-and-suggestions#1688]
### Your Discord Name

deadttv

### A clear and concise description of what the bug is

When pulling out certain props (Coke Table, Water Pump) basically anything that has a corresponding item associated with it and then putting them away you receive that item in your pockets, basically making infinite items.

### Steps to Reproduce the Bug

1. Open the prop menu
2. Pull out a coke table
3. press R to put it away
4. receive a brand new coke table

### Expected Behavior

receive no item for something that you don't have.

### Screenshots/Videos

N/A

**Comment by JnKTechstuff** [comment]
Fixed
