### ISSUE TITLE
[BUG]  Glizzys figurine bag issue

### ISSUE THREAD

**Issue by D4rkStr1der** [ParadoxGamingRP/bugs-and-suggestions#1689]
### Your Discord Name

D4rkStr1der#3393

### A clear and concise description of what the bug is

when someone goes into their figurine bag and moves stuff around it moves my stuff around as well. 

### Steps to Reproduce the Bug

1. Go into the figurine bag
2. Have someone else go into their figurine bag.
3. Have them move figurines around inside the bag.

### Expected Behavior

Them being in their bag to not affect my bag.

### Screenshots/Videos

https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/108428107/48dd03c1-6191-4b08-8ad7-16a81089bda7

**Comment by Bac0nRamen** [comment]
This makes no sense since those things are all individual storages
