### ISSUE TITLE
[ENHANCEMENT] Methanol in Paleto please

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#1693]
**Your Discord Name**
jojosnmustard

**Describe the annoyance**
With the recent rise in engine swap sales, would it be possible to get a fuel pump in Paleto for Methanol, or at least someplace we can buy methanol cans so if we run out of gas in Paleto/nearby areas we aren't stuck impounding the car.

**To Reproduce**
[Steps to reproduce the annoyance]
1. Get engine swap
2. Live in Paleto
3. Have to go to Zancudo or the city for fuel

**Requested behavior**
[A clear and concise description of what you want to happen]
Methanol pump in Paleto so I can melt tires in my obnoxiously loud toy all night.

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by Bac0nRamen** [comment]
next restart
