### ISSUE TITLE
[BUG] LFA has feels like a hovercraft

### ISSUE THREAD

**Issue by Baljeet00** [ParadoxGamingRP/bugs-and-suggestions#1695]
### Your Discord Name

Baljeetoo

### A clear and concise description of what the bug is

The Lfa handles all odd and feels like a hovercraft getting air on every corner it takes

### Steps to Reproduce the Bug

Get a LFA
Try to go around corners 

### Expected Behavior

for the lfa to drive like it used to

### Screenshots/Videos

na

**Comment by Kromlec** [comment]
Duplicate of Bug Report #1630
