### ISSUE TITLE
[BUG] Cant take cars out of house garages 

### ISSUE THREAD

**Issue by Timtim412** [ParadoxGamingRP/bugs-and-suggestions#1698]
### Your Discord Name

ghostdragon23

### A clear and concise description of what the bug is

I Just bought a house and have 2 Vehicles stuck in my house garage becasue i do not have keys to the garage. 

### Steps to Reproduce the Bug

put a car in and you cant take it out

### Expected Behavior

I should be able to access my garage freely. to be able to put cars in and take them out. 

### Screenshots/Videos

dont have any

**Comment by Kromlec** [comment]
Have you reached out and talked to Wolfs? Also include your logs please so we can see what's going on.

**Comment by Timtim412** [comment]
they said i need to make a bug report

**Comment by Timtim412** [comment]
how do i get my logs?

**Comment by Bac0nRamen** [comment]
need more info than what you have given. You said you have no keys? Is it actually ur house? If its not then reach out to staff and they can move ur cars to another garage. But from what you are telling us this is not really a bug from the info you have provided

**Comment by Timtim412** [comment]
it is really my house.  I bought it from Wolfs. The worker named sugar. said they cant do anything.  The house is in my name but i do not have keys to the garage for some reason.

**Comment by Timtim412** [comment]
i bought the house 2-3 days ago.  from wolfs.

**Comment by Timtim412** [comment]
when i try to access the garage thats in my name.  it says you do not own keys to the house garage.

**Comment by Timtim412** [comment]
I talked to wolfs about it.  they said i need to make a bug report.

**Comment by TheAzian47** [comment]
[](url)
[CitizenFX_log_2023-08-11T044454.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12318678/CitizenFX_log_2023-08-11T044454.log)

**Comment by Timtim412** [comment]
I am still not able to access my vehicles in my garage at my house.
