### ISSUE TITLE
[BUG] TV Menus

### ISSUE THREAD

**Issue by agentspooky19** [ParadoxGamingRP/bugs-and-suggestions#1699]
### Your Discord Name

spooky_6464

### A clear and concise description of what the bug is

When using the TV's to place the menus it causes MASSIVE headaches when entering and leaving the buildings. It is quite literally impossible to function with the TV menus up. 

### Steps to Reproduce the Bug

1. Place a menu link onto the TV's and the lag will happen

### Expected Behavior

Place the menu and experience little to no lag

### Screenshots/Videos

n/a

### Extra Notes (Optional)

It wasn't this bad when they first were implemented, so I'm unsure what the issue could be

**Comment by xXJamieXx** [comment]
Not experiencing this so assuming its fixed.
