### ISSUE TITLE
[BUG]Car stuck in garage no access.   

### ISSUE THREAD

**Issue by BoDittle** [ParadoxGamingRP/bugs-and-suggestions#1703]
### Your Discord Name

CarnageOP’#4394

### A clear and concise description of what the bug is

Just bought a house in my gang's compound and don't have access to my garage, stored my cars and can't pull them back out. 

### Steps to Reproduce the Bug

Store car or bike in owned house 
try an pull the car or bike out
cant take vehicle out due to no access 
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/126412350/a84469c7-4697-49d2-8a6e-272d2bc5a0b0)

### Expected Behavior

Should be able to access vehicles from owned property. 

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/126412350/0783ff86-b040-4933-8691-f913fa63bee7)

### Log File

[CitizenFX_log_2023-08-09T000741.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12297340/CitizenFX_log_2023-08-09T000741.log)

**Comment by JonnyB371** [comment]
I am having the exact same issue. Johnny_B.#4003 is my Discord name, Garage was working flawlessly then i stored a bike and now no longer have keys to garage
