### ISSUE TITLE
[BUG] Not being able to fly in at prison

### ISSUE THREAD

**Issue by PatrykX904** [ParadoxGamingRP/bugs-and-suggestions#1704]
### Your Discord Name

thisiscorruption

### A clear and concise description of what the bug is

Yesterday I got sent to prison but I had to fly out and just now when I started to try fly in it doesnt let me spawn in at prison

### Steps to Reproduce the Bug

1. Be sent to prison
2. Fly out 
3. Fly back in a later time
4. Not be able to fly back into prison

### Expected Behavior

Be able to wake up at prison

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/81855046/5521c77c-f55f-4bca-a996-f65a2865e0aa)

### Log File

[Prison Bug.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12302940/Prison.Bug.txt)

**Comment by PatrykX904** [comment]
Works all of a sudden now

 Will close report

**Comment by PatrykX904** [comment]
just got sent to prison and same thing happened, probably will work in a sec since its been an hour. 

Will reopen issue

**Comment by Darahz** [comment]
This seems to be fixed
