### ISSUE TITLE
[ENHANCEMENT] Car driving through wall at Bikini Auto

### ISSUE THREAD

**Issue by SketchyNath** [ParadoxGamingRP/bugs-and-suggestions#1705]
**Your Discord Name**
[SketchyNath]

**Describe the annoyance**
[Every so often, whether there is 1 person there or 100 people, a car will pull up to the wall and attempt to drive through. Sometimes if there are other cars there or even people stood in the way, the car will jump through the wall and destroy anything in it's parth]

**To Reproduce**
[Steps to reproduce the annoyance]
1. Head on down to SADOT/Bikini Auto
2. Stand anywhere near the front of the Automotive building or anwhere around the SADOT Office
3. Wait for local to come to wall
4. Sometimes you have to turn around and they will go through the wall

**Requested behavior**
[It would be nice for the locals path to be changed as the original MLO has an entrance there but the pathway was never removed]

**Screenshots**
https://medal.tv/games/gta-v/clips/1o1jh2O9D-OSvV/d1337cNJXzAG?invite=cr-MSw5UlAsMTk0ODMwMjk0LA

**Additional context**
[Add any other context about the enhancement here]

**Comment by Bac0nRamen** [comment]
Tried to edit this stuff before. had it working but the script was crashing the server but I will try to look into it again when I get a min
