### ISSUE TITLE
[BUG] Can't Pull Cars Out of House Garage

### ISSUE THREAD

**Issue by TheAzian47** [ParadoxGamingRP/bugs-and-suggestions#1708]
### Your Discord Name

theazian47

### A clear and concise description of what the bug is

So I bought a house and parked my car in the house garage. When I went to pull it out, there was an error which says that I don't have keys to this house garage. 

### Steps to Reproduce the Bug

1. Have a house with a garage.
2. Park your car in that garage.
3. Try to pull your car out of the garage and see that you can't. 

### Expected Behavior

Hopefully this issue can be fixed so that you can pull/park cars at your property without any issue. 

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/1ojGaVnejsfuGC/d13374RB07vM?invite=cr-MSx3b2QsNjEwODMyODYs
(sorry for the poor video quality)

**Comment by Kromlec** [comment]
Can you please put the video and your logs in this bug report please., logs are more needed than anything. Want to keep them all in one place.

https://github.com/ParadoxGamingRP/bugs-and-suggestions/issues/1698

**Comment by TheAzian47** [comment]
[    270156] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "defaultHouseItems". This is a FATAL ERROR in
[    270156] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270156] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270156] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "houseItem". This is a FATAL ERROR in
[    270156] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270156] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270156] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "houseItem__withFallback". This is a FATAL ERROR in
[    270156] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270156] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270156] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "defaultMyKeys". This is a FATAL ERROR in
[    270156] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270156] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270156] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "myKeys". This is a FATAL ERROR in
[    270156] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270156] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270156] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "myKeys__withFallback". This is a FATAL ERROR in
[    270156] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270156] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270156] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "selectedHouse". This is a FATAL ERROR in
[    270156] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270156] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270156] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "houseListModal". This is a FATAL ERROR in
[    270156] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270156] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270156] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "modalType". This is a FATAL ERROR in
[    270156] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270156] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270156] [b2802_GTAProce]        CrBrowserMain/ Successfully loaded external app "npwd_qb_housing" (@npwd/dist/html/75.js:1)
[    270172] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "defaultMailItems". This is a FATAL ERROR in
[    270172] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270172] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270172] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "mailItem". This is a FATAL ERROR in
[    270172] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270172] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270172] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "mailItem__withFallback". This is a FATAL ERROR in
[    270172] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270172] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270172] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "selectedMail". This is a FATAL ERROR in
[    270172] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270172] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270172] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "mailModalVisible". This is a FATAL ERROR in
[    270172] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270172] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270172] [b2802_GTAProce]        CrBrowserMain/ Successfully loaded external app "npwd_qb_mail" (@npwd/dist/html/75.js:1)
[    270187] [b2802_GTAProce]        CrBrowserMain/ Successfully loaded external app "npwd_qb_services" (@npwd/dist/html/75.js:1)
[    270203] [b2802_GTAProce]        CrBrowserMain/ Successfully loaded external app "npwd_qb_garage" (@npwd/dist/html/75.js:1)
[    270219] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "defaultBankBalance". This is a FATAL ERROR in
[    270219] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270219] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270234] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "bankBalance". This is a FATAL ERROR in
[    270234] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270234] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270234] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "bankBalance__withFallback". This is a FATAL ERROR in
[    270234] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270234] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270234] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "defaultAccountNumber". This is a FATAL ERROR in
[    270234] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270234] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270234] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "accountNumber". This is a FATAL ERROR in
[    270234] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270234] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270234] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "accountNumber__withFallback". This is a FATAL ERROR in
[    270234] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270234] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270234] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "defaultContacts". This is a FATAL ERROR in
[    270234] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270234] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270234] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "contacts". This is a FATAL ERROR in
[    270234] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270234] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270234] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "contacts__withFallback". This is a FATAL ERROR in
[    270234] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270234] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270234] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "defaultInvoiceList". This is a FATAL ERROR in
[    270234] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270234] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270234] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "invoiceList". This is a FATAL ERROR in
[    270234] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270234] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270234] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "invoiceList__withFallback". This is a FATAL ERROR in
[    270234] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270234] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270234] [b2802_GTAProce]        CrBrowserMain/ Successfully loaded external app "npwd_qb_banking" (@npwd/dist/html/75.js:1)
[    270250] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "npwd-advertisements:defaultAdvertisements". This is a FATAL ERROR in
[    270250] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270250] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270250] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "npwd-advertisements:advertisements". This is a FATAL ERROR in
[    270250] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270250] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270250] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "npwd-advertisements:advertisements__withFallback". This is a FATAL ERROR in
[    270250] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270250] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270250] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "npwd-advertisements:defaultUser". This is a FATAL ERROR in
[    270250] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270250] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270250] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "npwd-advertisements:user". This is a FATAL ERROR in
[    270250] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270250] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270250] [b2802_GTAProce]        CrBrowserMain/ Duplicate atom key "npwd-advertisements:user__withFallback". This is a FATAL ERROR in
[    270250] [b2802_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[    270250] [b2802_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[    270250] [b2802_GTAProce]        CrBrowserMain/ Successfully loaded external app "npwd_advertisements" (@npwd/dist/html/75.js:1)

**Comment by TheAzian47** [comment]
not sure where exactly which part to log

**Comment by Kromlec** [comment]
Duplicate.
