### ISSUE TITLE
[BUG] Calico GTF Speed Lock

### ISSUE THREAD

**Issue by jkaejkae888** [ParadoxGamingRP/bugs-and-suggestions#1710]
### Your Discord Name

jkaejkae888#6530

### A clear and concise description of what the bug is

The Calico seems to be locked at 124 I've used it in A class cars and just normal owned ones it locks at 124 even if you hit the NOS which is weird because then the NOS loses a bit of it's value of course.

### Steps to Reproduce the Bug

Drive The calico On flat or down hill the results are the same.

### Expected Behavior

to at least have some extra kick when using the NOS

### Screenshots/Videos

N/A

**Comment by Kromlec** [comment]
limited by game.
