### ISSUE TITLE
[BUG] Gems Are not Cutting Normally

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#1711]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

Going up to the gem cutter. You can't cut the gems, as it never starts the cut after the menu.

### Steps to Reproduce the Bug

1. get dremmel and drill bit
2. go to the gem table in the furnace room
3. try to cut gem thats in your inventory
4. doesn't cut

### Expected Behavior

Gives you a minigame to cut the gem.

### Screenshots/Videos

https://cdn.discordapp.com/attachments/1139695043725230140/1139750651774120106/image.png

**Comment by Bac0nRamen** [comment]
should be fixed
