### ISSUE TITLE
[BUG] Danny-itis

### ISSUE THREAD

**Issue by omelette44** [ParadoxGamingRP/bugs-and-suggestions#1712]
### Your Discord Name

greasy44

### A clear and concise description of what the bug is

Its seems to be when changing outfits can cause danny-itis

### Steps to Reproduce the Bug

change through preset saved outfits

### Expected Behavior

to not catch such a nasty disease while changing clothes

### Screenshots/Videos

.

### Extra Notes (Optional)

hopefully this can help the ongoing battle against danny-itis 🫡

### Log File

[CitizenFX_log_2023-08-12T090555.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12327179/CitizenFX_log_2023-08-12T090555.log)

**Comment by Darahz** [comment]
Seems like this is fixed
