### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by TheAzian47** [ParadoxGamingRP/bugs-and-suggestions#1714]
### Your Discord Name

theazian47

### A clear and concise description of what the bug is

The PD Moto unit needs either a speed buff or a durability buff because the motorcycle can't keep up with any other PD cars, let alone a criminal's car. On top of that, the durability is so bad, if you hit one thing, your bike will red engine no matter how fast you're going or if a local hits out a little bit. 

### Steps to Reproduce the Bug

1. Grab a moto unit from the pd motorpool
2a. Try to chase someone 
2b. Drive into anything at any speed

### Expected Behavior

I'm not asking for moto to be OP. Just buff the durability and/or speed of the bike so it's more practical. 

### Screenshots/Videos

https://clips.twitch.tv/KathishEagerMosquitoRlyTho-rM2cJZamV0wL3Pb1
https://medal.tv/games/gta-v/clips/1oFE0fHgTax3Lf/d1337aNC0QUt?invite=cr-MSxUc0UsNjEwODMyODYs
https://medal.tv/games/gta-v/clips/1oLWwXfnpGDggN/d1337hGcIQFb?invite=cr-MSx2SlYsNjEwODMyODYs

**Comment by Bac0nRamen** [comment]
Closing this and will update in the dev ticket once done when time allows
