### ISSUE TITLE
[ENHANCEMENT] Airport Parking

### ISSUE THREAD

**Issue by Kromlec** [ParadoxGamingRP/bugs-and-suggestions#1716]
Kromlec

The aircraft hanger parking at LSIA doesn't have a place to park your car if you want to take your plane or helicopter out. There is a parking down by the dealership but that is at the opposite end of the airport as where you pull out your aircraft.

**Comment by Asaineur** [comment]
I think all airports need one

**Comment by Bac0nRamen** [comment]
next restart
