### ISSUE TITLE
[BUG] K9 related 

### ISSUE THREAD

**Issue by M1ngh** [ParadoxGamingRP/bugs-and-suggestions#1717]
### Your Discord Name

minghee

### A clear and concise description of what the bug is

Dog will attack anyone near them if they shoot.

Searching cars or people are finicky if you touch the dog during the search it cancels it,

You rip driver out of cars if you are trying to be passenger

### Steps to Reproduce the Bug

1. There is a shooting situation between cops and criminals.
2. dog bite the closest person shooting.

1. You send the dog to search a vehicle or a person.
2. The dog starts sniffing, and someone touches the dog.
3. The dog stops the search.

1. The driver and the dog are in the car.
2. Someone try to enter the passenger seat.
3. Runs around the car and gets the driver off .

### Expected Behavior

1. There is a shooting situation between cops and criminals.
2. dog stay with the handler unless the handler sends him to bite.

1. You send the dog to search a vehicle or a person.
2. The dog starts sniffing, and someone touches the dog.
3. The dog keeps searching until it's done.

1. The driver and the dog are in the car.
2. Someone try to enter the passenger seat.
3. It successfully allows you to enter the passenger seat.

### Screenshots/Videos

n/a

### Extra Notes (Optional)

This were the ones noticed so far later.
All the rest seems to work fine
Thank you.

### Log File

n/a

**Comment by xXJamieXx** [comment]
Fixed the biting. The rest I can't reproduce.
