### ISSUE TITLE
Box Truck

### ISSUE THREAD

**Issue by OtisMowle** [ParadoxGamingRP/bugs-and-suggestions#1718]
### Your Discord Name

bimmyr7

### A clear and concise description of what the bug is

The box truck has 7500 storage but only has 10 slots

### Steps to Reproduce the Bug

add more slots to box truck

### Expected Behavior

As many slots as a house storage has

### Screenshots/Videos

https://i.imgur.com/5hnY0My.png

**Comment by Bac0nRamen** [comment]
They are balanced to how we would like them so people cant store a million things in a garage as well wanna push people to housing and storage lockers
