### ISSUE TITLE
[BUG] <hair Variation bug>

### ISSUE THREAD

**Issue by CROWSER75** [ParadoxGamingRP/bugs-and-suggestions#1720]
### Your Discord Name

Crowser

### A clear and concise description of what the bug is

when you use the hair command in the f1 menu or type hair in the T menu another hair appears, then you can't go back to the original hair you had

### Steps to Reproduce the Bug

1

### Expected Behavior

1

### Screenshots/Videos

https://youtu.be/_A79e2od4TQ

**Comment by Bac0nRamen** [comment]
should be fixed and in live
