### ISSUE TITLE
[BUG] Gun holsters not pulling guns

### ISSUE THREAD

**Issue by RoseiiNaytool** [ParadoxGamingRP/bugs-and-suggestions#1721]
### Your Discord Name

Roseii

### A clear and concise description of what the bug is

The gun holsters are not quick drawing, they are pulling the fun from your back waist

### Steps to Reproduce the Bug

1. Pull gun
2. gun comes out of lower back instead of quick drawing from holster
3. Gun is put up at lower back where it came from

### Expected Behavior

To be able to quick draw from your holster again

### Screenshots/Videos

Video: https://medal.tv/games/gta-v/clips/1ph6svZA-H4XsT/d1337BQ54Xj8?invite=cr-MSxUM20sMzY4OTU4NzQs

no seen errors in F8

**Comment by Bac0nRamen** [comment]
Next restart
