### ISSUE TITLE
[BUG] Fire Extinguishers broke

### ISSUE THREAD

**Issue by Epic-Almond** [ParadoxGamingRP/bugs-and-suggestions#1722]
### Your Discord Name

Epic Almond

### A clear and concise description of what the bug is

When clocked on fire and trying to use a fire extinguisher. Nothing happens when trying to use them. Mine had 96 durability and ammo and all it did was click. Up on the top right of my screen it shows 0 ammo, but in my pocket it shows 97

### Steps to Reproduce the Bug

1. Grab a fire extinguisher
2. Go attempt to put out a fire or just spray it on the ground.
3. Nothing happens

### Expected Behavior

The fire extinguisher should work and be able to put out fires not just click

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/1piIeNXih5mxsO/d1337ITpzfBf?invite=cr-MSxuYzcsMTg1ODQzMjMxLA

**Comment by xXJamieXx** [comment]
Works fine in dev but not live. Not sure about this one honestly...
