### ISSUE TITLE
[BUG] Trucking Job

### ISSUE THREAD

**Issue by OtisMowle** [ParadoxGamingRP/bugs-and-suggestions#1725]
### Your Discord Name

bimmyr7

### A clear and concise description of what the bug is

when you start the trucking job and get a truck out there is an outline stuck around the truck that will not go away 

### Steps to Reproduce the Bug

get a truck out 
get in truck 
outline disappears 

### Expected Behavior

no outline around truck after you get in the truck 

### Screenshots/Videos

https://i.imgur.com/gIHmAhX.jpeg

**Comment by OtisMowle** [comment]
Also cannot attach to this type of trailer https://i.imgur.com/HUHyuqp.png

**Comment by OtisMowle** [comment]
Also some of the delivery drop off outlines do not appear so you don't know where to drop the trailer https://i.imgur.com/ufi38Wu.jpeg

**Comment by Bac0nRamen** [comment]
Fixed attaching to the trailer shown above next restart

**Comment by xXJamieXx** [comment]
Closing in favor of rewrite in the works.
