### ISSUE TITLE
[BUG] Mining Dremmel Breaks Quickly

### ISSUE THREAD

**Issue by RoseiiNaytool** [ParadoxGamingRP/bugs-and-suggestions#1728]
### Your Discord Name

Roseii

### A clear and concise description of what the bug is

I'm not sure if this was intended to do this, but one mining dremmel breaks after it's 4th use with cutting stones. I'm putting this in as a bug report in the hopes that it can be fixed so that it doesn't die that quick of a death. These cost $728 per dremmel, and you only get 4 uses out of it. 

Thank you for taking a look at this. 

### Steps to Reproduce the Bug

1. Buy Dremmel from mines
2. Use dremmel 4 times on uncut stones
3. dremmel breaks
4. buy new dremmel at $728 to cut more jewels

### Expected Behavior

I'm hoping that it's fixed so that it doesn't break so quickly. That is a huge amount of money to spend to cut the stones and then have to turn around and do it every 4 stones. Either make it last longer, or make the dremmel a bit cheaper for people to purchase. 

### Screenshots/Videos

Video: https://medal.tv/games/gta-v/clips/1pCIiuJOI0XT4l/d1337caX7ryk?invite=cr-MSx3YjksMzY4OTU4NzQs

**Comment by NickNubbz** [comment]
you need steel bits to bring the dremmel to 100% again but it is currently bugged where it wont let you put the bits on.

**Comment by Bac0nRamen** [comment]
#1724
