### ISSUE TITLE
[BUG] Unable to purchase the Inductor bicycle from bicycle shop. 

### ISSUE THREAD

**Issue by jplink420** [ParadoxGamingRP/bugs-and-suggestions#1729]
### Your Discord Name

j_plink

### A clear and concise description of what the bug is

So I wanted to purchase one of those new nifty electronic assist bikes from the bike shop to reduce my carbon footprint and reduce the climate warming and all that jazz. It costs about 10x the amount of your standard BMX, but it gets you around nice I've heard. I went to the bicycle shop, cash in hand ready to purchase one, but the clerk at the store simply wouldn't let me purchase one, he had the display model in stock, but I think the button on his register for this bicycle specifically was broken or something, as I was able to purchase any other bicycle besides the Inductor or its Livery-ed counterpart. 

### Steps to Reproduce the Bug

1. Want to buy an e-bike to save the turtles or something like that
2. Go to the bicycle shop and try to purchase an Inductor bicycle
3. Clerk doesn't sell me one even though I have the money.

### Expected Behavior

To be able to purchase the Inductor to save the polar bears in the arctic from Los Santos! 

### Screenshots/Videos

N/A

### Log File

[CitizenFX_log_2023-08-19T091807.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12385503/CitizenFX_log_2023-08-19T091807.log)

**Comment by Bac0nRamen** [comment]
next restart
