### ISSUE TITLE
[BUG] Walls & Doors missing from housing decoration

### ISSUE THREAD

**Issue by SpiceF0x** [ParadoxGamingRP/bugs-and-suggestions#1731]
### Your Discord Name

spicedf0x

### A clear and concise description of what the bug is

There was an option for walls and doors when the housing was relaunched but it seems to be missing. I enjoyed using the walls. A lot.

### Steps to Reproduce the Bug

1. Open F1
2. Go to furniture or whatever it is
3. Walls / Doors are missing as options along the top, also cannot search for the item.

### Expected Behavior

I want more wall tiles please, can you put them back?

### Screenshots/Videos

NA

**Comment by Bac0nRamen** [comment]
next restart
