### ISSUE TITLE
[BUG]   Cars Stuck in garage

### ISSUE THREAD

**Issue by Timtim412** [ParadoxGamingRP/bugs-and-suggestions#1732]
### Your Discord Name

ghostdragon23

### A clear and concise description of what the bug is

I am still not able to access  the cars that are stuck in the garage at my house.   Wolfs. says its above their heads and to make a bug report about it. 

### Steps to Reproduce the Bug

1. put a car into the garage.
2.  attempt to pull car out of garage
3.  says you to not have keys to house garage. 

### Expected Behavior

I expected to be able to use my garage freely and put away cars and pull them out anytime i want.  

### Screenshots/Videos

https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/141691204/d22bd40a-320a-420c-a57f-098f009ee071

### Extra Notes (Optional)

I hope we can figure out whats going on so I can start using my garage. 

### Log File

[CitizenFX_log_2023-08-20T185630.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12389238/CitizenFX_log_2023-08-20T185630.log)

**Comment by Bac0nRamen** [comment]
#1698 refer to this report for anyupdates
