### ISSUE TITLE
[BUG] <short description>

### ISSUE THREAD

**Issue by ZackR93** [ParadoxGamingRP/bugs-and-suggestions#1733]
### Your Discord Name

Zack Rising

### A clear and concise description of what the bug is

just bought a new house earlier today and had to fly out. when returning back to the city i went to the garage and tried to get my car and it says I don't have the keys to this garage.

### Steps to Reproduce the Bug

just buy a new house i guess

### Expected Behavior

get it fixed maybe?

### Screenshots/Videos

N/A

### Extra Notes (Optional)

It's annoying and detours ppl away from wanting to be in the city because they don't have their own vehicle to drive.

### Log File

N/A

**Comment by Kromlec** [comment]
Duplicate #1732.
