### ISSUE TITLE
[BUG] Installing engines without being a mechanic

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1738]
### Your Discord Name

ssara

### A clear and concise description of what the bug is

So I was working at the tuner shop and someone asked if he could see in the engine how it looked. I said I don't think you can, but you can try. And sure enough he could see all the parts, drop the engine, install the engine and everything a mechanic can. I tried it myself with clocking out and having someone pull the engine and I could install the engine, pull the engine and drop it as well. 

### Steps to Reproduce the Bug

Not be a mechanic
Be able to see in the engine and to all the work a mechanic can do without being one

### Expected Behavior

Not be a mechanic
Not do mechanic things

### Screenshots/Videos

N/A

### Log File

[engine.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12413308/engine.txt)

**Comment by Kromlec** [comment]
Can also confirm this works at Bikini Auto..
