### ISSUE TITLE
[BUG] Seatbelt Shenanigans

### ISSUE THREAD

**Issue by CorFinn** [ParadoxGamingRP/bugs-and-suggestions#1743]
### Your Discord Name

GrandNagus

### A clear and concise description of what the bug is

Seatbelt/Racing harness interaction is currently bugged. Once you put a harness on, you can still exit the vehicle. Once back inside, you are unable to buckle your seatbelt until you use the harness again. 

### Steps to Reproduce the Bug

1. Enter vehicle
2. Attach racing harness
3. Exit vehicle (no need to remove harness)
4. Re-enter vehicle
5. Attempt to buckle seatbelt

You are now unable to engage your seatbelt until you re-use your harness. 

### Expected Behavior

Harness should prevent you from exiting vehicle.
Harness should not prevent you from engaging a seatbelt. 

### Screenshots/Videos

Unneeded. Easy to reproduce.

**Comment by JnKTechstuff** [comment]
Should be fixed
