### ISSUE TITLE
[BUG] Housing Props blow up

### ISSUE THREAD

**Issue by LitrlyD3ad** [ParadoxGamingRP/bugs-and-suggestions#1744]
### Your Discord Name

deadttv

### A clear and concise description of what the bug is

The following props blow up when your character model touches them.

The Salvage Infernus and the Salvage Elegy. 

### Steps to Reproduce the Bug

1. Add either of these props into your house
2. walk into them
3. the car blows up
4. you die
5. open a staff ticket
6. Olivia shames you for dying to a parked car
7. revives you
8. you leave the house and come back in
9. die again
10. gets sentenced to 100 hours of Rebeca Black. 

### Expected Behavior

to look good but not blow up when i touch them, but honestly its okay bc the way they look makes it worth it tbh.

### Screenshots/Videos

https://i.imgur.com/lb7K9jt.jpeg

**Comment by Bac0nRamen** [comment]
Nothing I can do about it sense there are no settings to the props for the housing script so I will remove those two props next restart.
