### ISSUE TITLE
[BUG]  House not loading 

### ISSUE THREAD

**Issue by NataliaGallo96** [ParadoxGamingRP/bugs-and-suggestions#1745]
### Your Discord Name

Carebear#9564

### A clear and concise description of what the bug is

I try to enter house and my house doesn't load remains black the whole time. Happens randomly and to random people when they enter my house. I go to my other house which is right beside that house and I am able to load in.

### Steps to Reproduce the Bug

1. enter my house on paleto blvd

### Expected Behavior

1. enter my house 
2. be able to see the interior of my house

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/1r3dyX-FtDFQFV/d1337uAFYjSf?invite=cr-MSxnZ3MsMTU4OTk3MTcxLA

### Log File

[house not loading.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12447525/house.not.loading.txt)

**Comment by xXJamieXx** [comment]
It's failing to load a piece of furniture in a reasonable timeframe. I've made the timeframe longer but if it still fails then its due to a slow PC/connection to the server.
