### ISSUE TITLE
[ENHANCEMENT] Range Rover Carbon Hood

### ISSUE THREAD

**Issue by SketchyNath** [ParadoxGamingRP/bugs-and-suggestions#1746]
**Your Discord Name**
[SketchyNath]

**Describe the annoyance**
[I was wondering if there is a possiblity of removing the carbon fibre skin on the hood of the Range Rover and reverting it to a standard paint to match the bodywork. There's many times where people try to create a paint scheme to find that it doesn't go well with a carbon fibre hood. The rest is fine like the roof and spoiler. Also the IRL Range Rover Sport SVR Mansory Edition doesn't have a carbon hood.]

**Requested behavior**
[All is above]

**Screenshots**
[In game model https://i.imgur.com/MJ1hHD5.png
 IRL model https://i.imgur.com/JnfIcXz.png]

**Additional context**
[Add any other context about the enhancement here]

**Comment by Bac0nRamen** [comment]
I will look into this but this will be model work so I cant promise anything
