### ISSUE TITLE
[BUG] Chop shop spawning issues

### ISSUE THREAD

**Issue by shriekingenius** [ParadoxGamingRP/bugs-and-suggestions#1749]
### Your Discord Name

shriekingenius

### A clear and concise description of what the bug is

The car does not spawn when in the circle

### Steps to Reproduce the Bug

1. request chop job from NPC at postal code 61
2. once circle appears head to circle

### Expected Behavior

a car is supposed to appear, a red dot will appear on the minimap letting you know the car is in your area

### Screenshots/Videos

![Chop messages](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/143467730/2950b044-bcea-4007-82a1-b72ceb3a3bc8)

### Extra Notes (Optional)

I have done chops successfully in the past. Usually when I am in the circle the car will appear after driving through the circle. For the past few days it has not worked for me, I have requested chops and the yellow circle appears. I will drive around the yellow circle for about 20-30 minutes and cannot find the car and it will not spawn. I have tried relogging, I have even uninstalled and reinstalled GTA and FiveM with no luck. The chop has worked for people I have been with, but not for me.

**Comment by BlazinNut** [comment]
Learn where the cars spawn at lol but only issue I've been having with chopping is the place where you go after getting the car the guy would be missing after about 3 chops he wont be at the next one so you have to completely exit fivem and come back in.
