### ISSUE TITLE
[BUG] Infinite loading

### ISSUE THREAD

**Issue by Patemob** [ParadoxGamingRP/bugs-and-suggestions#1755]
### Your Discord Name

patemob

### A clear and concise description of what the bug is

After you create a new character and choose your apartment location, you get stuck on a infinite black loading screen. Loading symbol in the bottom right and mic symbol in the bottom left.

### Steps to Reproduce the Bug

Create a new character
Click Continue
Choose your location
Black screen happens

### Expected Behavior

you should be able to choose the physical characteristics of your character and enter the city

### Screenshots/Videos

![35a72395d4e8da21b77a1ad9f349e79a](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/114136119/62a44b92-cf4f-48d2-8d73-140d774d3fff)

### Extra Notes (Optional)

Only way to enter the city is to exit during the infinite black screen, and choose the character you just created. Once you choose your location you spawn in instantly but are given random physical features.
Opened 2 support tickets about this and was sent a github link of someone else submitting a report for this 5 days ago, and was told to clear cache which did not work either

### Log File

[message.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12481328/message.txt)

**Comment by xXJamieXx** [comment]
Log file does not appear to be from this session. It doesn't show any evidence of you selecting a character or anything.

**Comment by Patemob** [comment]
I will resend it today when I get home.

**Comment by Patemob** [comment]
[CitizenFX_log_2023-09-01T012621.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12492047/CitizenFX_log_2023-09-01T012621.log)

**Comment by NataliaGallo96** [comment]
https://github.com/ParadoxGamingRP/bugs-and-suggestions/issues/1745

I opened a ticket a week ago and issue for me still remains when I enter house I get the loading screen.
