### ISSUE TITLE
[BUG] Black Screen When Entering House

### ISSUE THREAD

**Issue by LitrlyD3ad** [ParadoxGamingRP/bugs-and-suggestions#1756]
### Your Discord Name

deadttv

### A clear and concise description of what the bug is

When entering house you get a infinite loading screen yet again, this goes for anyone you let in aswell as yourself.

### Steps to Reproduce the Bug

try to enter your house after having alot of stuff in it, and then get a blacked out screen with infinite loading.

### Expected Behavior

be able to enter without issues, aswell as have friends/customers be able to enter aswell.

### Screenshots/Videos

https://i.imgur.com/X7oczv8.jpeg

**Comment by xXJamieXx** [comment]
Screenshot means nothing, this is the reason we ask for log files...

**Comment by NataliaGallo96** [comment]
[house not loading 9.1.2023.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12501074/house.not.loading.9.1.2023.txt)


i have the same issue

**Comment by xXJamieXx** [comment]
@LitrlyD3ad @NataliaGallo96 an update on this would be great after restart

**Comment by LitrlyD3ad** [comment]
Ill have to have a friend try as the issue only happened to me once and was resolved after i cleared cache, I assume mine was from colliding cache resources.
