### ISSUE TITLE
[BUG] Vehicles Driving Weird

### ISSUE THREAD

**Issue by SwickMachine** [ParadoxGamingRP/bugs-and-suggestions#1759]
### Your Discord Name

SwickMachine#6355

### A clear and concise description of what the bug is

Bravado Vulture is still having weird steering issues. Try to turn and it wants to accelerate without hitting the gas. 

### Steps to Reproduce the Bug

1. Try to drive Bravado Vulture.
2. Can't turn at all without accelerating. 
3. Hit everything trying to get back to a garage. 

### Expected Behavior

1. Hop in Bravado Vulture.
2. Have a good, smooth ride. 

### Screenshots/Videos

N/A

**Comment by Kromlec** [comment]
fixed next restart.
