### ISSUE TITLE
Speedo Custom Van ( NOT BUGSTARS VAN ) Shooting MG out of Grill

### ISSUE THREAD

**Issue by cythioan** [ParadoxGamingRP/bugs-and-suggestions#1762]
### Your Discord Name

Tikibar

### A clear and concise description of what the bug is

I wasn't sure if there was something added to the speedo custom but I was picking it out of the lot at Bugstars and I seem to have turrests now equipped in the grill? I dont know where to do this at and bennys I dont think does this. Im thinking it must be bugged.  The van was normal when parking it at bugstars. Pulling it changed it I guess?

### Steps to Reproduce the Bug

Park Speedo Custom veh at bugstars 
Pull Veh at bugstars 
Click R MB Should be able to see Reticle for aim

### Expected Behavior

Pull van and not have turrets inside grill 

### Screenshots/Videos

https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/30983170/717a7d1c-5b52-4b09-a41c-da4fdf61f8fe

**Comment by Bac0nRamen** [comment]
I need more info. Works fine for me when i do it.

**Comment by cythioan** [comment]
I did leave it there for a few hours until I woke back up , after being told to submit a bug report I took it to city hall parked it there for a few hours. Pulled it again it had Mg's still but after sitting for 2-3 mins the reticle and mg's went away with out needing to park and pull. i'm sorry i don't have better info for you the vid is the best i could do

**Comment by Bac0nRamen** [comment]
did you buy this van from somewhere?   I dont think its anything to do with bugstars. Do you know what kind of van it is? hard to tell from the pic since many look the same

**Comment by Bac0nRamen** [comment]
figured it out be fixed next restart
