### ISSUE TITLE
[BUG] Minimap is now zoomed in rather than zoomed out.

### ISSUE THREAD

**Issue by RoguIsAwesome** [ParadoxGamingRP/bugs-and-suggestions#1763]
### Your Discord Name

rogue_69

### A clear and concise description of what the bug is

In the update which was released yesterday, it stated that the minimap was zoomed out so that we can see more when driving, well when I joined the server the minimap was set back to the old zoomed in version and when its on rocky terrain such as offroad the minimap gets blurred out. 

First I thought this could be a issue on my end so I reset the hud and it still is the same.

### Steps to Reproduce the Bug

1. Hop on Server
2.  Start Driving
3.  Minimap Acting up

### Expected Behavior

Minimap goes back to zoomed out.

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/114842052/dfc639fe-0d38-4ac0-a152-0b352c3aeef0)

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/114842052/d49b1f2d-918e-4c01-baee-5db9953cc0a0)

### Extra Notes (Optional)

N/A

### Log File

[CitizenFX_log_2023-09-02T190033.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12504591/CitizenFX_log_2023-09-02T190033.log)

**Comment by CorFinn** [comment]
To add to this, it's also causing waypoints and GPS paths to not appear on the minimap. Destination is still visible, but how to get there is not.
