### ISSUE TITLE
[BUG] the Wearhouse trucks Randomly have Guns and rockets to shoot 

### ISSUE THREAD

**Issue by Jarome435** [ParadoxGamingRP/bugs-and-suggestions#1764]
### Your Discord Name

coach_ghosty

### A clear and concise description of what the bug is

the Wearhouse trucks and a few others Have rockets on them some pic's in the description 

### Steps to Reproduce the Bug

1 Get a truck 
2 shoot out of truck 

### Expected Behavior

For it not to have Rockets and LMGS 

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/136755819/6f7f0fe3-0c0c-4a95-811e-78cbac0d6960)
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/136755819/deb207f4-5581-4f70-b271-bab29c3b4af7)

**Comment by Bac0nRamen** [comment]
fixed next restart
