### ISSUE TITLE
Mule Custom has Rockets and locking system

### ISSUE THREAD

**Issue by BlazinNut** [ParadoxGamingRP/bugs-and-suggestions#1765]
### Your Discord Name

BlazinNut

### A clear and concise description of what the bug is

My mule is shooting missles

### Steps to Reproduce the Bug

Pull our Mule Custom
Click the fire button
Rocets shoot out

### Expected Behavior

No rocket system

### Screenshots/Videos

![20230903044801_1](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/130942230/56e15deb-687f-4b6a-9b0a-af8db90d84f8)

### Extra Notes (Optional)

NA

**Comment by Bac0nRamen** [comment]
fixed next restart
