### ISSUE TITLE
[ENHANCEMENT] Chest Holster Functionality

### ISSUE THREAD

**Issue by LitrlyD3ad** [ParadoxGamingRP/bugs-and-suggestions#1767]
**Your Discord Name**
deadttv

**Describe the annoyance**
I would like to see the chest strap holster (Undershirt 202) be functional and allow players to quickly pull a gun out of it like the hip holsters, i use it a few outfits and as it currently stands "the drip is worth it" when it takes longer to pull the gun out, as i like the style of the holster.

**To Reproduce**
[Steps to reproduce the annoyance]
1. have no hip holster
2. have chest strap holster instead
3. go to pull weapon
4. character pulls from the back of pants

**Requested behavior**
treat the chest holster like a hip holster, thus making it not only the drippy-est (yes thats a word, i just made it up) holster you can get, but also functional.

**Screenshots**
https://i.imgur.com/hwOo6JC.jpeg

**Additional context**
[Add any other context about the enhancement here]

**Comment by Bac0nRamen** [comment]
only holsters in the next category work for this. We may add the chest strap in a future update when we do another clothing update
