### ISSUE TITLE
[ENHANCEMENT] Apartment number shown in city

### ISSUE THREAD

**Issue by SpiceF0x** [ParadoxGamingRP/bugs-and-suggestions#1768]
**Your Discord Name**
spicedf0x

**Describe the annoyance**
After you have flown into the city you are unable to see your apartment number, you have to /logout to see where you live and the number to allow people into your house.

**To Reproduce**
[Steps to reproduce the annoyance]
1. Be an apartment owner
2.  Not be able to see where you live in city

**Requested behavior**
Either to be able to see it on your phone - or put it on your storage inside apartment?

**Comment by LitrlyD3ad** [comment]
I was thinking about putting a QOL in for a command to be added so you can see your number, like /appnum for example
