### ISSUE TITLE
[BUG] Blinking Speedometer

### ISSUE THREAD

**Issue by xPorscha** [ParadoxGamingRP/bugs-and-suggestions#1772]
### Your Discord Name

Porscha#5395

### A clear and concise description of what the bug is

When turning on the speed clock, it is continuously blinking and im unable to clear the clock.

### Steps to Reproduce the Bug

clock on duty
get into vehicle 
turn on speedometer 

### Expected Behavior

starts to blink and does not clear if it clocks something.

### Screenshots/Videos

https://clips.twitch.tv/StrangeFurtiveDumplingsJonCarnage-40JMko6jIVaSerG3

### Log File

[Blinking radar.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12527971/Blinking.radar.txt)

**Comment by xXJamieXx** [comment]
I know I've experienced this but I can't find a way to reliably reproduce it.

**Comment by xPorscha** [comment]
Yeah its very temperamental. I just wasn't sure if it was a bug or not
