### ISSUE TITLE
[BUG] Jester classic custom has bennys nos...

### ISSUE THREAD

**Issue by NickNubbz** [ParadoxGamingRP/bugs-and-suggestions#1773]
### Your Discord Name

NickNubbz

### A clear and concise description of what the bug is

The Jester classic custom has its own nos when you upgrade it at bennys. Ive never purchased it but to my understanding while upgrading at bennys there is a option to add nos. while driving flex your X muscle and some super nos comes out and gives you a crazy boost. This nos does not run out and is over powered. I am not sure if any other cars have the same thing and im not sure if its a intended thing or not.

### Steps to Reproduce the Bug

purchase jester classic custom
upgrade at bennys
drive and flex your X muscle

### Expected Behavior

Should not be any nos type features outside of tuner shops.

### Screenshots/Videos

NA

### Extra Notes (Optional)

I was participating in a street race and someone just kept spamming this nos the whole race to pass everybody and it honestly made the race not even any fun.

**Comment by Kromlec** [comment]
fixed next restart

**Comment by NickNubbz** [comment]
That was fast. I appreciate it!Sent from my iPhoneOn Sep 6, 2023, at 3:06 AM, Kromlec ***@***.***> wrote:﻿
fixed next restart
