### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by SleasySam** [ParadoxGamingRP/bugs-and-suggestions#1775]
### Your Discord Name

''SleasySamW#1089

### A clear and concise description of what the bug is

After I bought a Sadler, I was unable to mod, or fix it, at all.
the prompts that indicate what buttons I need to press did not appear
my already bought cars could be repaired, but were unable to be modded, but I could still access the mod menu, however I could not choose any options (I could see respray, but could actually browse the colors)
A mod told my to reset my keybinds, and that worked for my other cars, but not my sadler

It was a karin sadler to be clear

### Steps to Reproduce the Bug

buy a sadler, I think.

try to mod or repair it

### Expected Behavior

I expected to be able to mod, and fix, my karin sadler.

### Screenshots/Videos

all my screenshots are too big in here, wtf

### Log File

[CitizenFX_log_2023-09-06T231447.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12543341/CitizenFX_log_2023-09-06T231447.log)

**Comment by tusktheshrew** [comment]
I also can't repair my car at any of the shops.

**Comment by Kromlec** [comment]
Both of these vehicles can be repaired/customized at the commercial repair stations.   Tusk I told you what to suggest for your Taxis already.

**Comment by SleasySam** [comment]
? so about my car tho? cuz I can assure you it CANNOT be repaired, its from the regular ass off road car store

**Comment by Kromlec** [comment]
Your truck CAN be repaired and customized at a commercial repair location. These are different than normal bennies.

**Comment by SleasySam** [comment]
? okay... kinda confusing that its at the regular car store, but ill take ur word for it ig.

**Comment by SleasySam** [comment]
alright you were right, but you understand my confusion, I mean cmon man thats some hunky funky stuff right there
