### ISSUE TITLE
[BUG] Boosting - Turismo R not able to be picked into. 

### ISSUE THREAD

**Issue by SwickMachine** [ParadoxGamingRP/bugs-and-suggestions#1776]
### Your Discord Name

SwickMachine#6355

### A clear and concise description of what the bug is

During a boost for the Turismo R, you are not able to get into it without knocking someone out and putting them in the car. 

### Steps to Reproduce the Bug

1. Try to lockpick Turismo R
2. Can't get in.
3. Knock your driver out.
4. Put them in car.
5. Able to continue boost. 

### Expected Behavior

To be able to lockpick car and get into it like a normal boost. 

### Screenshots/Videos

N/A

**Comment by JnKTechstuff** [comment]
There are ways
