### ISSUE TITLE
[BUG] Gas pumps not working

### ISSUE THREAD

**Issue by NataliaGallo96** [ParadoxGamingRP/bugs-and-suggestions#1779]
### Your Discord Name

Carebear#9564

### A clear and concise description of what the bug is

No one can fill up their vehicles. Many people tried

### Steps to Reproduce the Bug

1. Refuel vehicle

### Expected Behavior

1.Refuel vehicle
2. car should fill up with gas

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/1sVZ3HzqUAsu8k/d1337Yw93KNd?invite=cr-MSxRbXosMTU4OTk3MTcxLA

### Log File

[PUMPS NOT WORKING.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12552787/PUMPS.NOT.WORKING.txt)

**Comment by Darahz** [comment]
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/35222814/8660b7c8-611d-4e22-8bd0-f7e38a81c9f7)

**Comment by emeraldleo1982** [comment]
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/29337315/aab5b0d8-c91c-4359-aac2-3f83406bfe8f)
