### ISSUE TITLE
[BUG] Swaps missing

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1780]
### Your Discord Name

ssara

### A clear and concise description of what the bug is

Dropped swapped engines from a few different cars, Jethros sharmann had a S85 drift, RH5 had a 2JZ drift, my nexus alien body had a 2JZ normal, Tokens drag Charger, Tokens M3 2JZ drift, Chimps Stratum had an LS in his stratum, B58 in his Supra.
I do not know what could be a trigger of it since my 2JZ drift Roxanne is working as it should while other that has the same engine isnt. 

### Steps to Reproduce the Bug

Have a swap
Dont hear it
Pull the engine
Looks like a normal engine

### Expected Behavior

Have a swap left

### Screenshots/Videos

N/A

### Log File

[swap.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12553119/swap.txt)

**Comment by emeraldleo1982** [comment]
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/29337315/c26fa229-c205-4a91-9e74-fb0b3158c4e3)
What I get when entering my Scharmann, if that gives any clues.

**Comment by JnKTechstuff** [comment]
Should be resolved
