### ISSUE TITLE
[BUG] Engines dropping Nos and Turbo

### ISSUE THREAD

**Issue by Kromlec** [ParadoxGamingRP/bugs-and-suggestions#1781]
### Your Discord Name

Kromlec 

### A clear and concise description of what the bug is

When you pull and engine and reinstall it drops the turbo and nitrous

### Steps to Reproduce the Bug

Pull engine from car
do repairs to car and or install nos/turbo
Install engine back into car
Get error on screen for tune not being set correctly
No NOS or Turbo in car 

### Expected Behavior

Turbo and nos should stick into car

### Screenshots/Videos

https://i.imgur.com/o7mLx9B.jpeg

### Log File

[Parts fall out.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12555304/Parts.fall.out.txt)

**Comment by Kromlec** [comment]
Engine IDs are also changing everytime you pull an engine, so we aren't able to track installs of turbos or nos. pics below of same motor with 2 different IDs

https://i.imgur.com/QL2rKu8.jpeg

https://i.imgur.com/ZC5J6nq.jpeg

**Comment by JnKTechstuff** [comment]
Fixed; people who lost stuff can request refunds from staff tickets
