### ISSUE TITLE
[BUG] Pull  Engine for repairs at bike shop

### ISSUE THREAD

**Issue by tommytwoshotty** [ParadoxGamingRP/bugs-and-suggestions#1782]
### Your Discord Name

tommytwoshotty

### A clear and concise description of what the bug is

When attempting to pull an engine from a motorcycle to  make repairs option to pull the engine from the bike is not there. 

### Steps to Reproduce the Bug

Receive  a bike in need of repairs
Attempt to pull engine
not be able to pull  engine

### Expected Behavior

Be able to pull the engine and repair it

### Screenshots/Videos

![DJJHTCD](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/92126060/2c281d1c-3391-4d0d-815c-315ed317b4c5)

### Log File

[CitizenFX_log_2023-09-09T213347.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12566948/CitizenFX_log_2023-09-09T213347.log)

**Comment by CyrusMancini** [comment]
This is still an issue. I just tried again after the latest updates that were put through. I have attached the video I have and the log file to help. 

[Video](https://medal.tv/games/gta-v/clips/1tITwuuQrxFY_o/d1337m8ZArFV?invite=cr-MSxpRjQsMTYwNDYzNzM0LA)

[CitizenFX_log_2023-09-12T181740.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12590024/CitizenFX_log_2023-09-12T181740.log)

Thanks for looking into this

**Comment by D4rkStr1der** [comment]
I took my bike down to bikini and it let me pull the engine. Just can't at the bike shop for some reason.

**Comment by Darahz** [comment]
This hasnt been pushed to live yet. But it's fixed in dev

**Comment by D4rkStr1der** [comment]
thank you
