### ISSUE TITLE
[BUG] Can't combine steel dremmel bits into dremmel.

### ISSUE THREAD

**Issue by johnbravo420** [ParadoxGamingRP/bugs-and-suggestions#1784]
### Your Discord Name

lemonsmax

### A clear and concise description of what the bug is

I am unable to combine my steel dremmel bits with my dremmel as of today. I preserve my steel dremmel bits, but my dremmel maintains broken after the "Replacing drill bit..." prompt is finished displaying.

### Steps to Reproduce the Bug

1. Combine a steel dremmel bit with a dremmel.
2. Let the prompt finish.
3. Check your pockets to see if a steel dremmel bit was actually placed into the dremmel.

### Expected Behavior

I expect to be able to replace steel dremmel bits in my dremmel once they are worn.

### Screenshots/Videos

https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/102637351/eddfb22d-1924-4924-bf90-6e127c8d287c

### Log File

[CitizenFX_log_2023-09-10T043546.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12567513/CitizenFX_log_2023-09-10T043546.log)

**Comment by mangi8sh** [comment]
same happening with me and my boy

**Comment by BlazinNut** [comment]
Can confirm

**Comment by johnbravo420** [comment]
Seems to be working again.
