### ISSUE TITLE
[ENHANCEMENT] New scenes great, but a couple suggestions

### ISSUE THREAD

**Issue by SpiceF0x** [ParadoxGamingRP/bugs-and-suggestions#1785]
**Your Discord Name**
spicedf0x

**Describe the annoyance**
Hello! First of all, the changes with the new scenes are great, but there's a couple niggly bits I've found.
- You can't enter to have a second line in the same scene. Some people place multiple line scenes, and also a new line helps make things just look _neater_.
- Once started you can't move the scene, so sometimes the placement looks really off. So you have to start again and some of the customisations don't save
- It's really finnicky on where to place it, you can't start editing until 'Example Text' comes up, and it doesn't seem to show up in quite the amount of places the previous version worked in (I can move it slightly and it'll work?)
- Unable to delete other people's scenes
- Scenes persistent through instances KEKW

**To Reproduce**
[Steps to reproduce the annoyance]
1. Create a scene
2. Have smol issues

I think these are self explanatory, but MORE than happy to get little videos of what's the issue with points 2 and 3. Just let me know! <3

**Comment by JnKTechstuff** [comment]
- Second line: `<br>` will add a new line
- Maybe fixed? You still can't move it right now
- Should no longer be finicky 
- Should be able to delete any scene
- Shouldn't be persistent through buckets
