### ISSUE TITLE
[BUG] S class boosts not being swapped

### ISSUE THREAD

**Issue by dave1880** [ParadoxGamingRP/bugs-and-suggestions#1787]
### Your Discord Name

Davefromsunderland

### A clear and concise description of what the bug is

Earlier today I did an S class boost on a neo and the vehicle wasn't swapped.

### Steps to Reproduce the Bug

1. Start an S class
2. No swap 

### Expected Behavior

I would expect the vehicle to be swapped

### Screenshots/Videos

N/A

**Comment by JnKTechstuff** [comment]
Its there, the audio wasn't
