### ISSUE TITLE
[BUG] Hats

### ISSUE THREAD

**Issue by Mambaa19** [ParadoxGamingRP/bugs-and-suggestions#1789]
### Your Discord Name

Mambaa_19#4871

### A clear and concise description of what the bug is

So when i am on PD i am a deputy with the bcso so one of the hats we wear is the flat brim looking drill sergeant looking hat same as the one state wears or similar and what i have been finding in the last week or so is that i find that some people can't see my character when i put it on, a couple times when i was duoing, people thought it was only my duo partner there until they heard my voice, so it's making me invisible, i don't know if it's only me but people have mentioned it on several occasions, but as soon as i switch to the cowboy hat or any other hat they can see me again.

### Steps to Reproduce the Bug

Find what may be causing it, as i can see myself but they can't see me

### Expected Behavior

Hopefully test the code behind that specific hat?

### Screenshots/Videos

Unfortunately i have non, if it happens again ill grab some

**Comment by Bac0nRamen** [comment]
This should be fixed?

**Comment by xXJamieXx** [comment]
Pretty sure its still happening

**Comment by Drunkle716** [comment]
> Pretty sure its still happening

It's fixed in dev but wonky in live. I have logs I can send ya.

**Comment by Drunkle716** [comment]
![image-19](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/100391224/c58d4f48-be4c-49b9-b383-0b2380e5b63e)

**Comment by Drunkle716** [comment]
![Uploading image-12.png…]()

**Comment by Drunkle716** [comment]
![image-12](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/100391224/2be19ea8-00a9-48ec-944c-382daa2af7ba)

**Comment by Drunkle716** [comment]
[CitizenFX_log_2023-09-15T172310_1.log.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12686739/CitizenFX_log_2023-09-15T172310_1.log.txt)
