### ISSUE TITLE
Unable to roll joints from homegrown weed

### ISSUE THREAD

**Issue by BjornK22** [ParadoxGamingRP/bugs-and-suggestions#1795]
### Your Discord Name

Blitzd11

### A clear and concise description of what the bug is

I tried to combine my own homegrown weed with store bought joint papers for weed and tobacco,  It allows you to combine a bag of weed and the joint paper but you do NOT receive a joint in your pocket.

### Steps to Reproduce the Bug

1. Have 1 weed bag in your pocket
2. Have 1 joint paper in your pocket
3. Combine both the weed bag and joint paper in your pocket 
4. They will start to combine allowing you to roll the joint
5. You receive no joint

### Expected Behavior

Once you have one weed bag and buy one joint paper you should be able to combine them both together in your pocket to roll and receive the joint.

### Screenshots/Videos

Combine both the weed bag and joint paper ![Screenshot 2023-09-15 111658](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/97834363/2689ec2a-56fa-48f8-9e17-a9378171d1c5)
It will combine and start rolling the joint![Screenshot 2023-09-15 113148](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/97834363/79685cfd-02d6-4e58-9e27-5adf2927d8df)
But you receive No joint 
![Screenshot 2023-09-15 113233](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/97834363/46260b3b-6216-46df-b943-a0825a681495)

### Log File

[CitizenFX_log_2023-09-15T144656.log](h
[CitizenFX_log_2023-09-15T144639.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12621135/CitizenFX_log_2023-09-15T144639.log)
ttps://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12621127/CitizenFX_log_2023-09-15T144656.log)

**Comment by Darahz** [comment]
This is now live
