### ISSUE TITLE
[BUG] game crashing in KOI after clocking in

### ISSUE THREAD

**Issue by spookylucy** [ParadoxGamingRP/bugs-and-suggestions#1796]
### Your Discord Name

Spookylucy31#7775

### A clear and concise description of what the bug is

I came into KOI and clocked in and I immediately crashed. I then spawned in the location and crashed again. so i went to my office thats a few streets away, everything was fine. I went inside KOI and clocked on again and a minute later I crashed again. I thought it was just a me issue but another employee had the same issue.  

### Steps to Reproduce the Bug

1. Go into Koi
2. clockon as employee 
3. game crashes/headpop

### Expected Behavior

I expected to clockin and not have the game crash a minute later. you should clockon and start your shift

### Screenshots/Videos

N/A

### Log File

[CitizenFX_log_2023-09-15T190329.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12623399/CitizenFX_log_2023-09-15T190329.log)
[CitizenFX_log_2023-09-15T193329.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12623400/CitizenFX_log_2023-09-15T193329.log)
[CitizenFX_log_2023-09-15T193932.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12623401/CitizenFX_log_2023-09-15T193932.log)

**Comment by xXJamieXx** [comment]
Not able to reproduce this personally.
