### ISSUE TITLE
[BUG] <short description>

### ISSUE THREAD

**Issue by ShaymusSavage** [ParadoxGamingRP/bugs-and-suggestions#1797]
### Your Discord Name

Shay.mus

### A clear and concise description of what the bug is

Not finding Steel Dremmel bits while mining. 

### Steps to Reproduce the Bug

1. Go mining
2. After some time, possibly find a blueprint.
3. Use blueprint and get the steel dremmel bits.

### Expected Behavior

Get a steel dremmel bit blueprint after mining for some time.

### Screenshots/Videos

n/a

**Comment by Darahz** [comment]
Can't seem to reproduce this. There's also no logs attached to this. You might just be really unlucky
