### ISSUE TITLE
[BUG] Not being able to smelt

### ISSUE THREAD

**Issue by cythioan** [ParadoxGamingRP/bugs-and-suggestions#1798]
### Your Discord Name

Tikibar

### A clear and concise description of what the bug is

opend mine after waking up, cleared mine of all minerals, smelted ores. didnt get any metal bars

### Steps to Reproduce the Bug

1. Woke up in Quarry
2. Generated Mine number 18
3. Started Mining to Clear out Mine Shaft
4. Cleared Mine Shaft ( Excluding Gold deposit and Bauxite deposit )
5. Lastly Smelt and see if it shows up in pockets

### Expected Behavior

drill rock get ore smelt ore

### Screenshots/Videos

n/a

### Log File

[CitizenFX_log_2023-09-17T102502.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12642793/CitizenFX_log_2023-09-17T102502.log)
[CitizenFX_log_2023-09-17T102442.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12642794/CitizenFX_log_2023-09-17T102442.log)

**Comment by Darahz** [comment]
Works on dev and not live

**Comment by xXJamieXx** [comment]
Closed in favour of civ job rework #1740
