### ISSUE TITLE
[BUG] Bait doesn't get placed on the fishing rod's hook.

### ISSUE THREAD

**Issue by johnbravo420** [ParadoxGamingRP/bugs-and-suggestions#1801]
### Your Discord Name

lemonsmax

### A clear and concise description of what the bug is

I can not put bait on my fishing rod. I am able to go through the animation of putting the bait on and a piece of bait is removed, but my rod is not baited. When I try to fish I have no bait.

### Steps to Reproduce the Bug

1.Get bait and a rod.
2.Drag the bait onto the fishing rod.
3.Go through the animation and lose a piece of bait.
4.Try to fish and have no bait.

### Expected Behavior

I expect to be able to fish after I put bait onto my rod until the bait is eaten.

### Screenshots/Videos

https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/102637351/dae4e6a5-eea6-4866-8ac2-8b8d2392bebd

### Log File

[CitizenFX_log_2023-09-19T022858.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12655281/CitizenFX_log_2023-09-19T022858.log)

**Comment by BlazinNut** [comment]
Can Confirm
