### ISSUE TITLE
[BUG] Town Hall Guard Person 

### ISSUE THREAD

**Issue by SamB1997** [ParadoxGamingRP/bugs-and-suggestions#1810]
### Your Discord Name

davefromsunderland

### A clear and concise description of what the bug is

The town hall guard steals my things when I'm clocked on as SAST. This issue does not happen with any other department afaik. This issue has happened to me multiple times and is also happening to other people in SAST. 

### Steps to Reproduce the Bug

1. Be clocked on as SAST
2. Adventure through town hall

### Expected Behavior

DONT TAKE MY THINGS IM A POLICE OFFICER

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/1veUhMO7P2Rnpz/d1337DqH7gQk?invite=cr-MSxsR24sNDc3MTczNjAs

**Comment by Bac0nRamen** [comment]
next restart
