### ISSUE TITLE
[BUG] GETTING PUT INTO RANDOM OUTFITS IN PRISON

### ISSUE THREAD

**Issue by NataliaGallo96** [ParadoxGamingRP/bugs-and-suggestions#1812]
### Your Discord Name

carebear9696

### A clear and concise description of what the bug is

Entered prison and was put into a random outfit that I've never saved before

### Steps to Reproduce the Bug

1. get send to prison
2. look at clothes

### Expected Behavior

1. get send to prison
2. wear prison clothes

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/123715929/cd84e263-1765-43c8-b1cc-63c299aca9f7)

### Log File

[prison clothes.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12707363/prison.clothes.txt)

**Comment by Darahz** [comment]
Added a place where you can change into the prisoner uniform.
