### ISSUE TITLE
[ENHANCEMENT] Make Michael take my prison cash!

### ISSUE THREAD

**Issue by jplink420** [ParadoxGamingRP/bugs-and-suggestions#1816]
**Your Discord Name**
j_plink

**Describe the annoyance**
I am currently down bad again, I am spending yet another day in prison, and am working all of these jobs for the few dollars that the fellow prisoners will give me! I am very hungry and thirsty after all of this work! However, I got fined FAT and now I have no money in my bank account to buy myself some prison commissary. The only option is for me to use my (totally legally obtained and not at all crafted within the prison walls) prison phone to have a friend send me some money while I am in prison to be able to eat. 

**To Reproduce**
[Steps to reproduce the annoyance]
1. Work my fingers to the bone repairing fences, fixing electrical boxes, cleaning up the canteen, etc
2. Try and get some prison commissary after a long day of work
3. Michael only takes money from my bank account. 

**Requested behavior**
Be able to give Michael the canteen worker my cash I get from doing jobs in prison. Maybe if he just took my cash before checking my account this could be good for people who don't carry cash around a lot. I just want to eat in prison man!

**Comment by xXJamieXx** [comment]
Not sure where Michael got his card machine from, don't think bollingbroke has moved to cashless yet!

(We should change everything to cash only in prison)

**Comment by Darahz** [comment]
Had a strict talk with Michael and Max about their "card only" mentality. And they decided to move over to cash only.
