### ISSUE TITLE
[ENHANCEMENT] Prison outfits

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1817]
**Your Discord Name**
ssara

I was wondering if this could possibly be added as a pre-set outfit to prison, that way you could create more RP with setting up gangs and seeing the different ones. Right now, everyone's orange and that could be like the "transfer"-outfit and then have these in a locker somewhere.

https://www.lcpdfr.com/downloads/gta5mods/character/42416-prisoner-outfits-eup/

**Comment by Yogurt22** [comment]
Would love to see something like this come to light and would be happy to work on some custom prison fits, but this involves some script work and the prison RP-scene seems a little dead right now.  If the scripting team is willing to set that side of things up I'd be happy to follow through, but with the way things are right now, I'm not too sure this would take much precedence.
