### ISSUE TITLE
[BUG] <short description>

### ISSUE THREAD

**Issue by wallace296** [ParadoxGamingRP/bugs-and-suggestions#1818]
### Your Discord Name

Walleze

### A clear and concise description of what the bug is

Trash job has you do 1 run and does not pay you anything to do it, 

### Steps to Reproduce the Bug

do trash run
has you do 1 stop 
tells you  return truck you are done
return truck and only get deposit and no money happens quite frequently with the RNG 
https://i.imgur.com/IFkdt0G.png proof image

### Expected Behavior

getting paid for working. 

### Screenshots/Videos

https://i.imgur.com/IFkdt0G.png

**Comment by xXJamieXx** [comment]
#1740
