### ISSUE TITLE
[BUG] <Mining Does not work>

### ISSUE THREAD

**Issue by Timtim412** [ParadoxGamingRP/bugs-and-suggestions#1819]
### Your Discord Name

GhostDragon23

### A clear and concise description of what the bug is

When trying to drill ore. It immediately fails and says failed to drill.  it almost never shows the quicktime and even when you succeed the quicktime it still shows failed to drill

### Steps to Reproduce the Bug

1. get drill
2.  go to mine
3. try to drill anything
4. it will fail

### Expected Behavior

I expect the drill to work and to be able to work in the mines and get ore

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/1vRhtWAGP-cy71/d1337hCMynnt?invite=cr-MSxtVmIsMTk5MTc4NjU0LA

**Comment by xXJamieXx** [comment]
#1740
