### ISSUE TITLE
[ENHANCEMENT] Gang HQ alerts

### ISSUE THREAD

**Issue by KNO-1** [ParadoxGamingRP/bugs-and-suggestions#1824]
**Your Discord Name**
Knoalot

**Requested behavior**
With the Warehouses being gone and Cayo drops are out, would be nice to give the Military laptop a new purpose maybe? 
I wanted to suggest getting a ping when your compound is being breached. PD recently got that change and it would be cool to get pinged or notified when your gang HQ is being thermited/breached. Or even a email notification notifying us of a HQ breach?

**Comment by LitrlyD3ad** [comment]
We have a requirement that we must notify gangs OOC prior to a compound raid, unfortunately the same cant be said for crims when they breach a department building, so we get notified IC to make up for it.

Basically what im saying is this feature is pointless bc pd would never go into a compound without telling the gang OOC. Unless you would like that changed? If so i couldnt agree more.

**Comment by jynx-ctk** [comment]
As for Pd what was stated above is true and I think should stick with the letting them know so people can plan around it

But for a criminal side we don’t get any alert or anything if someone breaks into your HQ until someone says something it would be a nice thing for the Military laptops to be able to alert the gang if there hq was breached
