### ISSUE TITLE
Wheelchairs are more fragile then a hacker about to get banned

### ISSUE THREAD

**Issue by PadawanPepsi** [ParadoxGamingRP/bugs-and-suggestions#1829]
**Your Discord Name**
PadawanPepsi
**Describe the annoyance**
Hart is be struggling trying to get around city when every two days his wheel chair breaks and there is no one around to get you a new one

**To Reproduce**
[Steps to reproduce the annoyance]
1. create a wheelcahir arc
2. go to sleep
3. wake up 2 days later
4. no clinic member sill be available TRUST
5. be sad and crawl around city

**Requested behavior**
Can we get a way to fix them ourselves for people serious about the RP and not just trying to goof around in a wheel chair

**Screenshots**
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/96961442/3e8fd24d-4dbd-4998-a872-90c97db52e08)

**Additional context**
The WD-40 idea in the feedback is probably the best approach at the moment

**Comment by PadawanPepsi** [comment]
Also can you change the put down and pickup time to something quicker like 2 seconds. It's kind of a immersion killer when im trying to get in or out of a car and im just standing there for 5 seconds. It doesent seem like a long time but when you are trying to get in and out it feels weird just standing there when you are supposed to be in the wheel chair

**Comment by Bac0nRamen** [comment]
Reduced spawn and pickup times.
