### ISSUE TITLE
[ENHANCEMENT] 'Jewellery' and 'Misc' categorisations

### ISSUE THREAD

**Issue by SpiceF0x** [ParadoxGamingRP/bugs-and-suggestions#1831]
**Your Discord Name**
spicedf0x

**Describe the annoyance**
Customisation of certain jewellery and miscellaneous items primarily in the decals / scarfs & necklaces. I looked through other categories and these seemed most out of place.

I totally realise that the clothing team is a thankless place to be, and categorising things is **hard**. I also do not know the intracies of placing items in the lua.

I have no idea if this idea is even earthly possible. But I have a suggestion to remove certain items from categories that are jewellery and or miscellaneous. I have collated all of them [here](https://www.canva.com/design/DAFwFXnzDHo/LTgUK5xiNf8Vg9s2tSYLuA/edit?utm_content=DAFwFXnzDHo&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) if you wanna see pictures.

But to summarise, this would mean adding a **further 3 decal spots**

Current number - How I'd categorise - where I'd place it

**DECALS**
15 - Ring - Decal 2
191 - Ring(s) - Decal 2
192 - Misc - Decal (stay?) / Decal 3
193 - Nails - Decal 3
195 - Nails - Decal 3
12 & 13 - Misc- Decal (stay?) / Decal 3

**SCARFS & NECKLACES**
1 - Earring - Earrings / Decal 4
2 - Earring - Earrings / Decal 4
3 - Bracelet - Bracelets / Decal 2
5 - Bracelet - Bracelets / Decal 2
10 - Bracelet - Bracelets / Decal 2
14 - Bracelet - Bracelets / Decal 2
25 - Bracelet - Bracelets / Decal 2
37 - Headwear - Hats / Decal 4
41 - Misc - Decal 3
148 - Misc - Decal 3
149 - Headwear - Hats / Decal 4
154 - Ring(s) - Decal 2
155 - Earring - Earrings / Decal 4
158 - Earring - Earrings / Decal 4
166 - Misc - Decal 3
167 - Misc - Decal 3
168 - Misc - Decal 3
169 - Facial Piercing - Decal 3
170 - Facial Piercing - Decal 3
171 - Facial Piercing - Decal 3
172 - Ring(s) - Decal 2
176 - Ring(s) - Decal 2

This means:
Decal 2 - Rings / Bracelets (if no room) (10 total)
Decal 3 - Misc / Facial Piercing (12 total)
Decal 4 - Earrings / Headwear (6 total)

_28 Total_

The bracelets and headwear I presumed were in these categories due to no more room in the correct ones / replacement of an item there? 

I also noticed a bunch of 'empty' or unable to see items in the Scarfs & Necklaces, this could just be me. 
43-52
63 
74-80
99
136-140
163

Personally, I'd leave 181-211 in Scarfs & Necklaces alone as they are PS pretty much.

This could be an absolutely non feasible or terrible idea. It would just be nice to cross customise some of these items :)

**Comment by Bac0nRamen** [comment]
im gonna close this here and move it to clothing to do list for future clothing updates.  We are trying to do clothing updates in bigger updates and not just a few things here and there
