### ISSUE TITLE
[BUG] Ranger parking 

### ISSUE THREAD

**Issue by Dez505** [ParadoxGamingRP/bugs-and-suggestions#1833]
### Your Discord Name

dez505

### A clear and concise description of what the bug is

if you try and get a car out of the Rangers compound parking the car goes inside of the compound 

### Steps to Reproduce the Bug

1. park your car or bike at the Ranger compound
2. try and pull out the car or bike
3. get stuck in under the compound

### Expected Behavior

you get your vehicle out and be it not be stuck

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/1wQ5Jv43jQRxwa/d1337Qxy7tgC?invite=cr-MSwydDgsMzQ3OTM3MTAs

**Comment by Bac0nRamen** [comment]
added spawn points for them to come out instead of random locations
