### ISSUE TITLE
[ENHANCEMENT] Boat repair

### ISSUE THREAD

**Issue by xPorscha** [ParadoxGamingRP/bugs-and-suggestions#1839]
**Your Discord Name**
Porscha#5395

**Describe the annoyance**
Whenever i live up to my pirate life and go to sail the sea's but then realise when i pull my boat out of the docks and it needs a bit of maintenance, there is nowhere for me to take it. There is a guy at the docks that can pimp my boat up but apparently he doesn't fix them. Instead i have to buy a repair kit from either NS, bikini or kildares and repair it that way which is kinda a pain if you forget your repair kit and/or you use all your uses without remembering to restock. 

**To Reproduce**
[Steps to reproduce the annoyance]
1. red engine boat
2. go to pimp ride out at the docks
3. do not get option to repair

I would really like if we could get some more repair stations around the shorelines and dock areas where we can take out sea vehiculars to be repaired

**Comment by Bac0nRamen** [comment]
added repair at the city customs shop and paleto
