### ISSUE TITLE
[BUG] Nitrous unusable

### ISSUE THREAD

**Issue by D4rkStr1der** [ParadoxGamingRP/bugs-and-suggestions#1840]
### Your Discord Name

D4rkStr1der#3393

### A clear and concise description of what the bug is

I have a Nitrous System in my car but when I try to refill or use NOS it says I dont have NOS.

### Steps to Reproduce the Bug

1. try to fill put nos in car

### Expected Behavior

It to put NOS in the car

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/108428107/ed17b031-a4aa-4ea0-bdc7-49943ab19366)

### Log File

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/108428107/8338088e-f6c8-4677-b3de-31bb2de50e1a)

**Comment by Kromlec** [comment]
Fix for this that we have found is to have the motor pulled and reinstalled and install nitrous. Once car is parked and pulled out it will work but only until you get out and get back in again. Then it's "gone" again.

**Comment by JnKTechstuff** [comment]
This should be fixed
