### ISSUE TITLE
[BUG] I mean.. Dress is fine but this is..  

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1842]
### Your Discord Name

ssara

### A clear and concise description of what the bug is

Well i was sent to comunity servce and the clothes are.. yes, see the picture. High heals, leather pants and a dress.

### Steps to Reproduce the Bug

be a female
get sent to jail/community service
get dressed in fancy clothes

### Expected Behavior

be in jail clothes

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/98127638/2fa001eb-4088-47e5-85da-ea3fb4365baa)

**Comment by Darahz** [comment]
Talked to the clothing manager. They are now delivering the fancy orange clothes once again.
