### ISSUE TITLE
[BUG] Government Gets Clocked in to Judge when actual Judge Clocks In

### ISSUE THREAD

**Issue by ShaymusSavage** [ParadoxGamingRP/bugs-and-suggestions#1843]
### Your Discord Name

Shay.mus

### A clear and concise description of what the bug is

When government people are clocked in, and a judge then clocks in. It causes one of the government people to appear under the Judge Tab. Once the actual Judge clocks off, then the person gets placed back into the Government tab.

### Steps to Reproduce the Bug

1. Have someone clocked in as government.
2. check the services tab on the phone.
3. Have a judge clock in.
4. Check the services tab again.

You will notice once a judge clocks in, one of the people from government gets moved into the judges tab, even though they're not a judge.

![8tpngBj](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/3319344/b8d02211-b64d-4e44-92ba-39af2486787c)

### Expected Behavior

Have the people that are clocked in as government not get moved over to the Judge tab under services when a judge clocks in.

### Screenshots/Videos

![8tpngBj](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/3319344/4642fc2a-11e7-4393-bb84-689c03819eb1)

**Comment by xXJamieXx** [comment]
Unable to reproduce this in testing
