### ISSUE TITLE
[ENHANCEMENT] Glizzys Cards to be allowed in Wallets

### ISSUE THREAD

**Issue by BrotherDayZ** [ParadoxGamingRP/bugs-and-suggestions#1851]
**Your Discord Name**
BDZ

**Describe the annoyance**
The cards that you can make at Glizzys be allowed to be inside wallets. 

**To Reproduce**
[Steps to reproduce the annoyance]
1. Have Cards on you
2. Open wallet and put the cards inside the wallet
3. Close Wallet

**Requested behavior**

**Screenshots**
https://i.imgur.com/ucqZrtp.png

**Additional context**
[Add any other context about the enhancement here]

**Comment by Darahz** [comment]
Added to the wallet
