### ISSUE TITLE
[BUG] unable to place mural in lupine manor 

### ISSUE THREAD

**Issue by Rac-coder** [ParadoxGamingRP/bugs-and-suggestions#1863]
### Your Discord Name

super raccoon#0863

### A clear and concise description of what the bug is

specific furniture is unable to be placed in houses when decorating. The example I have found is the mural I'm not sure if there are more but this is the one I have found personally.

### Steps to Reproduce the Bug

go into an interior, in this case lupine manor, and attempt to place a mural, it will not allow you to. 

### Expected Behavior

allow me to look at the mural in my house with the cool reaper and BBL's 

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/1ztUo12zO7c36h/d1337cd9d6Vi?invite=cr-MSxUV20sMTQxMDcwODUs

### Log File

[CitizenFX_log_2023-10-20T052753 - mural.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13050895/CitizenFX_log_2023-10-20T052753.-.mural.txt)

**Comment by Darahz** [comment]
No clue about this one. Tried spawning it in myself, but got the same error.
Model : bkr_int_02_mural_gang
