### ISSUE TITLE
[BUG] Assassin Contracts have been reassigned

### ISSUE THREAD

**Issue by SpiceF0x** [ParadoxGamingRP/bugs-and-suggestions#1867]
### Your Discord Name

spicedf0x

### A clear and concise description of what the bug is

So, Sugar has a GREAT rep with this guy, getting the _good shit_, but suddenly only started getting eyeballs again. It looks like he's assigning Sugar's contracts to other people, and I'm not sure whats happened to his god awful file handling.

### Steps to Reproduce the Bug

1. Grab a mission
2. Get something ya know, good
3. Except I don't because somehow my skills have been lowered and the record of my previous contracts has disappeared

### Expected Behavior

Get the jobs I've worked so hard for 
😢

### Screenshots/Videos

N/A

**Comment by xXJamieXx** [comment]
Unsure why this happens but I've added logs to hopefully track if this happens again.
