### ISSUE TITLE
[BUG] Boat Buyer doesn't exist

### ISSUE THREAD

**Issue by BjornK22** [ParadoxGamingRP/bugs-and-suggestions#1870]
### Your Discord Name

Blitzd11

### A clear and concise description of what the bug is

Once you buy a boat you're stuck with it forever, Unable to sell your boat to boat buyer.

### Steps to Reproduce the Bug

1. Go to the boat docks at postal 348 and buy a boat
2. Take that bought boat and park it at the boat parking spot at 349
3. Take your boat out of parking spot 
4. Take boat to boat buyer area by postal 348
5. You cannot find the area to sell boat
6. Unable to sell boat
7. Stuck with that boat forever

### Expected Behavior

I should be able to sell my boat at the boat buyer at a % of total cost like the car buyer.

### Screenshots/Videos

![Screenshot 2023-10-23 085251](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/97834363/d1395fcf-eac9-41db-a7c7-30133c49eae0)

### Log File

[CitizenFX_log_2023-10-23T124214.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13070557/CitizenFX_log_2023-10-23T124214.log)

**Comment by xXJamieXx** [comment]
Was able to sell just fine.
