### ISSUE TITLE
[BUG] New bike in bike shop breaks seller menu

### ISSUE THREAD

**Issue by tommytwoshotty** [ParadoxGamingRP/bugs-and-suggestions#1871]
### Your Discord Name

tommytwoshotty

### A clear and concise description of what the bug is

When checking out the new shipment of bikes received into the Reapers Bike shop a new bike caught my eye at the  bottom of the list. Hey its a sombrero. It looks nice. But that's just it it looks nice but i cant test drive it  Once you go to swap that bike to something else it swaps the bike but the menu still shows whatever bike you pulled before this bike

### Steps to Reproduce the Bug

!. Clock in to Bike shop.
2. Start looking thru the bike options.
3. Find a cool looking bike called Sombrero
$. Menu breaks

### Expected Behavior

Menu works as it should when testing bikes

### Screenshots/Videos

![FiveM_b2944_GTAProcess_PeG7RBFYo0](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/92126060/fc900545-7ba6-4d84-b707-0b7c64a8e830)

### Log File

[CitizenFX_log_2023-10-23T203338.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13079042/CitizenFX_log_2023-10-23T203338.log)

**Comment by Bac0nRamen** [comment]
be fixed next restart
