### ISSUE TITLE
[ENHANCEMENT] "/kill" Bind or Command 

### ISSUE THREAD

**Issue by Yogurt22** [ParadoxGamingRP/bugs-and-suggestions#1877]
**Your Discord Name**
YoGert

**Requested behavior**
Having a command and/or bind that allows one to instantly down themselves for RP and QOL purposes.   I brought this up in the #Feedback on the discord and instantly was bombarded with agreement from the community.   Personally think the server as a whole (scene-wise) could benefit from adding this seemingly minuscule yet game-changing RP mechanic, especially EMS!

**Comment by Darahz** [comment]
This is now live
