### ISSUE TITLE
[BUG] The opposite of a spraytan

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1878]
### Your Discord Name

ssara

### A clear and concise description of what the bug is

The following pants make you have white legs. 
204
203
202
201
200
197
196
170

### Steps to Reproduce the Bug

Put them on and be a shade darker than white
Get white legs

### Expected Behavior

Put them on and still have my spraytan

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/98127638/ef3bb18a-85f8-475a-88b0-e42334708b07)

**Comment by Bac0nRamen** [comment]
gonna just close this and we will most likely replace those clothing items due to it being a design model issue and not fixable right now but we will keep looking into the issue and this will be added to the clothign todo list
