### ISSUE TITLE
[BUG] not being able to promote to other ranks 

### ISSUE THREAD

**Issue by Drunkle716** [ParadoxGamingRP/bugs-and-suggestions#1879]
### Your Discord Name

MainCharacter716

### A clear and concise description of what the bug is

SAST Captain can't promote people in his department via Boss Menu

### Steps to Reproduce the Bug

Go to the office
Try to promote someone

### Expected Behavior

Be able to promote someone

### Screenshots/Videos

![FiveM_b2944_GTAProcess_07VCPjbBPB](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/100391224/09ecdb35-fb09-4363-9264-f23381a4aa35)
![FiveM_b2944_GTAProcess_mzVW6z5KwC](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/100391224/a1e53709-2425-4ea8-97d0-7ec398ce94e6)

### Log File

[CitizenFX_log_2023-10-26T160333.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13180026/CitizenFX_log_2023-10-26T160333.log)

**Comment by Bac0nRamen** [comment]
Temp fix for this is to back out of the boss menu all the way and go back into it

Its hit or miss when it works but backing out and going back in can fix it as a temp thing
