### ISSUE TITLE
[ENHANCEMENT] Car livery for 10F and 9F 

### ISSUE THREAD

**Issue by hacklv** [ParadoxGamingRP/bugs-and-suggestions#1881]
**Your Discord Name**
[gvido_b]

**Describe the annoyance**
[So iw recently iw both a 10f and iw had 9f and I saw that 10f has some great liveries but all of them are just something that i think its just plain and overused and not so great of course there is some good liveries for 10f but for 9f not so much so 

**To Reproduce**
[Steps to reproduce the annoyance]
1. make new livery for both cars 
2. maybe add some extra liveries to 9f 
3. could be added to different cars as well 

**Requested behavior**
[So i want new and clean liveries for 10f and 9f that include this livery that iw thought of on both cars for 10F only this one but for 9F it needs to have bit more liveries added its just such a great car but boring because of no customizations on the car ]

**Screenshots**
[
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/149176636/3ebbc701-c66d-45ed-a6f1-4d8a75d4d284)

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/149176636/0099e279-f020-4f50-a8ee-485a21af0ac0)

]

**Additional context**
[So iw saw this livery and i thought it looked great and its not something standard so its something different and iw asked some people around and they either liked the livery or already knew about it so I decided to act and possibly make this livery happen on cars like 10F and 9F because it would look the best on those cars + 9F doesn't haw allot of stuff for the car so it would be nice if it has a new livery added to it and this livery could be added to more cars if needed i know this might not be the best but i feal like its something different and would be nice

**Comment by Bac0nRamen** [comment]
Vehicle team will look into this. But in the mean time im going to close this and move this to our to do list to look into and keep a eye on any server updates for info regarding this
