### ISSUE TITLE
[ENHANCEMENT] Max prop

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1882]
**Your Discord Name**
ssara

**Describe the annoyance**
So working at the tunershop the whole max-prop thing is not working with what we are doing. It tells people that there's max prop even if there's 2 only. It will not work even after remove all props. 
I feel like this is a bit too much since we are limited with our work. 
I couldn't even put a single prop down at slurp and go, but someone else could place one and that was it.

**Comment by xXJamieXx** [comment]
Temporarily disabled
