### ISSUE TITLE
[ENHANCEMENT] Vehicle Balancing issues

### ISSUE THREAD

**Issue by Drunkle716** [ParadoxGamingRP/bugs-and-suggestions#1884]
**Your Discord Name**
MainCharacter716

**Describe the annoyance**
Every time there is a meta car discovered in racing, the response is to detune it. The zr390 was detuned to the point of being uncompetitive but costs as much as an RH7, which is probably the new meta car now. I also can't sell my zr390 for more than 35% of it's value.

Basically why are we detuning cars and not just making more cars competitive racers. 

**Requested behavior**
Make racing diverse by making more cars capable of competing.

**Comment by Bac0nRamen** [comment]
moved to the vehicle todo list.  but feel free to put in vehicle tickets in dev discord for car with issues. It can be handled easier there
