### ISSUE TITLE
[BUG] Issue with Opening Engine at the Shop

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#1887]
### Your Discord Name

tusktheshrew

### A clear and concise description of what the bug is

While trying to work at the shop i pulled an engine and was going to change it to the billet motor swap. But the Motor swap wouldn't open.

### Steps to Reproduce the Bug

1. Get Billet engine delivers
2. Pull engine up on jackstand
3. Look into engine.

### Expected Behavior

Opening the Engine should show a small menu to put the parts in.

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/98053772/4596411d-8d5e-4666-a0c5-63fe2df9d481)

### Log File

[EnginePull.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13195914/EnginePull.txt)

**Comment by Kromlec** [comment]
Duplicate of 1886.
