### ISSUE TITLE
[BUG] Not getting stuff back from community service

### ISSUE THREAD

**Issue by PatrykX904** [ParadoxGamingRP/bugs-and-suggestions#1892]
### Your Discord Name

thisiscorruption

### A clear and concise description of what the bug is

Alright, so I got sent for community service but I had to fly out so when I got sent I flew out and came back in the next day. After I finished my community service I didnt get my stuff back

### Steps to Reproduce the Bug

1. Get sent for community service
2. Fly out and come back next day / whenever maybe
3. Finish
4. No items back, not even at city hall

### Expected Behavior

Keep my stuff please

### Screenshots/Videos

NA

### Log File

[Community service bug.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13229368/Community.service.bug.txt)

**Comment by Jarome435** [comment]
[CitizenFX_log_2023-11-08T061722.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13293342/CitizenFX_log_2023-11-08T061722.log)

**Comment by Jarome435** [comment]
[CitizenFX_log_2023-11-08T052540.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13293345/CitizenFX_log_2023-11-08T052540.log)
