### ISSUE TITLE
[BUG] One part of my house is underwater on inside of house.

### ISSUE THREAD

**Issue by turbo-toad** [ParadoxGamingRP/bugs-and-suggestions#1895]
### Your Discord Name

turbotoad

### A clear and concise description of what the bug is

My house is between 905 and 906. Every time I try to enter the part of my house in the picture it makes me swim around my house.  It's near the TV and open area in the house. You walk over to that spot and it instantly puts you in a swimming animation inside the house. 

### Steps to Reproduce the Bug

Walk into House,
Walk over near the TV area,
Starts the swimming animation and won't stop until you've moved almost near where I placed my storage crate.

### Expected Behavior

When walking into my house I expect when I go to the affected area to be able to walk up there and not start swimming.

### Screenshots/Videos

![FiveM_b2944_GTAProcess_3328](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/137903041/502eede9-45f3-4b85-9b39-3225e791f1e9)
![FiveM_b2944_GTAProcess_3329](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/137903041/0149b54f-bd81-4ee7-b2cf-7d8116dfac2c)
![FiveM_b2944_GTAProcess_3331](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/137903041/a538e77d-c93e-47a1-a188-b03e67785ea5)

### Extra Notes (Optional)

Also there seems to be an invisible object on the wall to the left when you walk in that sort of impedes your movement. 

### Log File

[CitizenFX_log_2023-11-03T222146.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13255335/CitizenFX_log_2023-11-03T222146.log)

**Comment by turbo-toad** [comment]
Hello just checking back in. I was told to post this bug report here vs a ticket when I opened a ticket about it. Hoping to get it fixed whenever possible so I can start decorating my house.

**Comment by turbo-toad** [comment]
Hi just checking in again, my apartment is still flooded. Any help would be great.

**Comment by turbo-toad** [comment]
So is my house and everything in it gone now?

**Comment by turbo-toad** [comment]
So, my house is now gone and I can't access any of the items that were in the house. Is there a way for me to get all my food and items back and will I also receive a refund for the amount of time and money I put into the house?

**Comment by turbo-toad** [comment]
Hey so the ticket is closed however my house is still partially underwater. 
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/137903041/2ad70232-27f5-4c08-b533-cc7483e4e69d)

**Comment by xPorscha** [comment]
Hi there, just adding onto this real quick :) after purchasing interiors and storage at postal 348 at the harbour, my places are also partly / mostly underwater too. My property ID's are 

37178 - 2nd storage unit
36985 - Boat shop - Back left corner of building is under water.

Attached are 2 images of the locations for the 2nd storage unit. Picture 1 is where we placed the interior at first but it was under water and was not functionable so we have to move it to the place pictured in image 2 temporarily. I would like the interior to be placed on the door on image 1 for practical purposes, however, if its not possible to do so, i will have to keep it at the door shown in image 2.
![pic 1](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/124258625/6cc55dbd-c67d-4629-bfa7-f1fee9bbc0ad)
![pic 2](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/124258625/df1743eb-c7c9-4924-814e-663175c1ebb2)

**Comment by JnKTechstuff** [comment]
Fixed, also should support if you have multiple water quads in your place now
