### ISSUE TITLE
[BUG] GPU Usage spikes to 100% on select character screen/loading screen (crashes game)

### ISSUE THREAD

**Issue by DaemonCG0** [ParadoxGamingRP/bugs-and-suggestions#1897]
### Your Discord Name

Daemon._.

### A clear and concise description of what the bug is

Whenever I load into the server, when it gets to the "enter city" portion of the screen I get a lot of lag on the screen animation and my GPU spikes to 100% usage. I am not sure why this happens but I recently got a new PC. This was not happening in the old one. 

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/119983134/299f19a8-4384-4feb-8d54-187efb437461)

### Steps to Reproduce the Bug

click fivem
switches over to pure mode
loads into fivem again
loads server trailer cinematic
gpu spikes 100% on "enter city" screen
laggy ui after clicking "enter city"
spike continues but drops towards 90% after clicking character
on spawn select gpu back to normal

### Expected Behavior

I expected the process to not spike my gpu and turn my pc into a jet, no lag at the character select UI. 

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/119983134/352c687d-822a-477c-bc6c-62ae93e4a1c9)

### Extra Notes (Optional)

I'm not sure how to fix this, it might be an issue on my part but I haven't tinkered with my pc too much since getting it. If I could get some help to see if anyone has any better ideas as to how to fix this, it would make joining the server a lot smoother without crashes. Thank you guys for your work, I see the changes every time I get on the server and I appreciate that! 

PC Specs:
Cpu - Ryzen 9 3900x 12 cores / 24 threads
Cooler - Corsair Hydro Series H115i Pro Rgb 280mm Aio
Gpu - Nvidia GeForce Rtx 3090 24gb Gddr6x
Motherboard - AsRock X570 Pro4
Ram - Trident Z Rgb 16gb
Ssd - Samsung 980 512gb Nvme Ssd
Power Supply - Evga 750GQ Gold Rated

### Log File

[CitizenFX_log_2023-10-28T192543.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13257511/CitizenFX_log_2023-10-28T192543.log)
[CitizenFX_log_2023-10-28T211758.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13257512/CitizenFX_log_2023-10-28T211758.log)
[CitizenFX_log_2023-10-28T211822.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13257513/CitizenFX_log_2023-10-28T211822.log)

**Comment by Kromlec** [comment]
So a better option here would be to go to the main discord, go to Help and support and create a support ticket. Our moderator team will be able to assist you in tweeking some settings and assisting you better.
