### ISSUE TITLE
[BUG] ATM Hack Uses Multiple USB A Sticks

### ISSUE THREAD

**Issue by Drunkle716** [ParadoxGamingRP/bugs-and-suggestions#1906]
### Your Discord Name

MainCharacter716

### A clear and concise description of what the bug is

Hacked an ATM with 2 USB A sticks in my pocket and the hack used them both.

### Steps to Reproduce the Bug

Hack an ATM with multiple sticks in your pocket.
The hack uses them both.

### Expected Behavior

The hack only uses one

### Screenshots/Videos

![FiveM_b2944_GTAProcess_gKfYCnKxDZ](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/100391224/7fb34370-c66e-4126-b0c6-1522891a089c)

### Log File

[CitizenFX_log_2023-11-05T194317.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13262720/CitizenFX_log_2023-11-05T194317.log)

**Comment by Drunkle716** [comment]
Also apparently used 6 of the sticks in my storage

**Comment by Drunkle716** [comment]
Did a Hack with one in my pocket. Completed the hack and gave me no rewards.

**Comment by xXJamieXx** [comment]
Works fine for me.

**Comment by Drunkle716** [comment]
Today, it was not an asshole.
