### ISSUE TITLE
[BUG] Diving

### ISSUE THREAD

**Issue by SamB1997** [ParadoxGamingRP/bugs-and-suggestions#1907]
### Your Discord Name

davefromsunderland

### A clear and concise description of what the bug is

When diving I've found that the majority of the time a lot of the coral either refuses to spawn, spawns inside rocks or other terrain or is unable to be picked up. Most of the time I am able to get 1 or 2 pieces of coral and get told that there is X amount left but i am unable to find or interact with the remaining pieces. 

### Steps to Reproduce the Bug

1. Swim With the Fishes
2. No coral for you

### Expected Behavior

Let me contribute to ecocide the way i want to.

### Screenshots/Videos

I do not have any as of this moment but can get some if needed.

### Extra Notes (Optional)

I've found that some zones work better than others.

**Comment by SamB1997** [comment]
Update: I've found that restarting between doing it allows me to pick everything up without any issues

**Comment by Darahz** [comment]
So I've tweaked the locations slightly to hopefully prevent this
