### ISSUE TITLE
[ENHANCEMENT] Ownable Trailers

### ISSUE THREAD

**Issue by SketchyNath** [ParadoxGamingRP/bugs-and-suggestions#1909]
**Your Discord Name**
SketchyNath

**Describe the annoyance**
The new flatbed trailers for the pickups would be great if they were ownable. Me and a couple of other people rented them the other night and changed the colors to match our vehicles and everything looked great and went well. So would it be possible to be able to purchase them and maybe customise more ie: wheels?

**Comment by Bac0nRamen** [comment]
Next restart
