### ISSUE TITLE
[ENHANCEMENT] Additional Keyholders giving keys

### ISSUE THREAD

**Issue by SpiceF0x** [ParadoxGamingRP/bugs-and-suggestions#1911]
**Your Discord Name**
spicedf0x

**Describe the annoyance**
Only the main keyholder to Wolfs interiors can give out additional keys. There was a point in time additional keyholders could give out keys - I think this changed when we moved from giving keys at the door, to giving keys inside.

**To Reproduce**
1. Be inside and not able to give keys unless main keyholder
2. 
3. 

**Requested behavior**
Be able to flex F1 and give out keys as an additional keyholder.

**Comment by JnKTechstuff** [comment]
I think this is just a bad idea for security wise. This heavily prevents abuse and the issues we have seen on the staff side.

**Comment by SpiceF0x** [comment]
Yep, can see that. Two counter property types are my rentals (though infrequently used rn) where I allow the renter to give out keys, and business interiors for them to not have to give out keys to every single employee but also have additional keyholders give out keys
