### ISSUE TITLE
[BUG] Scenes continually persisting and/or not showing

### ISSUE THREAD

**Issue by SpiceF0x** [ParadoxGamingRP/bugs-and-suggestions#1912]
### Your Discord Name

spicedf0x

### A clear and concise description of what the bug is

Smol lil bugs with scenes right now:

**Problem one**
Some scenes are persisting way past their sell by date. I've seen some I set days ago with an expiration hour set, I've also noticed other scenes by others:

Details to 1 set for 1 hour on October 18th, showing up still in the same location

https://discord.com/channels/802676956226912306/802676958130602005/1171267435387691118

**Problem two**

Occasionally, scenes are not visible on placement, or existing ones - and a nap is required to see them. This one is not consistent, I can't figure out why it would or wouldn't but do not have logs. I realise this one is gonna be harder to recreate. (If anyone reading has logs where they can't see scenes they should, please add, I don't have any or know which of mine are relevant rn)

### Steps to Reproduce the Bug

1. Place a scene down
2. Give an expiration date
3. See it a week later even if not set as 'scene never expires'
_____________________
1. Attempt to set a scene down
2. Nothing appears
3. Usually appears on a nap
_____________________
1. Someone tells you to look at a scene menu
2. Can't see it
4. Nap
5. Can see it

### Expected Behavior

1. Set scene
2. Set expiration
3. Scene expires after allotted time
_____________________
1. Set scene
2. Scene appears
3. Joy
_____________________
1. Look at scene placed
2. See it without napping

### Screenshots/Videos

N/A

**Comment by xXJamieXx** [comment]
Fixed problem 1 which may in turn fix the other problems so waiting to hear if there are still issues after next restart.
