### ISSUE TITLE
shyster compact wagon in muscle dealership [BUG] <short description>

### ISSUE THREAD

**Issue by saberontop** [ParadoxGamingRP/bugs-and-suggestions#1913]
### Your Discord Name

fwsaber

### A clear and concise description of what the bug is

the schyster compact wagon (and many other vehicles that dont belong in their dealerships) is in the muscle dealership when its a fwd car 

### Steps to Reproduce the Bug

no steps

### Expected Behavior

compact wagon in muscle

### Screenshots/Videos

.

**Comment by Kromlec** [comment]
compact wagon moved to correct dealership. Could you more a little more specific than "many other vehicles that don't belong in their dealerships". It will help us as there are over 300 cars to look through.
