### ISSUE TITLE
[BUG] <Storage Space is extremely high which is not normal>

### ISSUE THREAD

**Issue by turbo-toad** [ParadoxGamingRP/bugs-and-suggestions#1914]
### Your Discord Name

turbotoad

### A clear and concise description of what the bug is

Mine & a few friends storage is currently higher then the normal limit allows for. Mine is almost 19k where my friend's is at 15k. We had stuff in there that nowhere gives anything that heavy to begin with and before hand was below almost a few hundred. 

### Steps to Reproduce the Bug

Walk into house,
Open Storage
Storage is a very high number which was not there previously.

### Expected Behavior

The expected behavior is that the storage go back to its original weight and everything goes back to the original weight it was when we last opened it. 

### Screenshots/Videos

![FiveM_b2944_GTAProcess_3346](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/137903041/a5fb2cb1-418b-468e-b59a-9819e2733eff)
Posted above is my house with the really high storage weight.
![FiveM_b2944_GTAProcess_3347](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/137903041/8a8888aa-bdc9-406c-95df-36db36dc4e00)
Posted above is my friends house with the really high storage weight.

### Extra Notes (Optional)

As stated above I need to specify it was nowhere near this amount when we previously put stuff in. 

### Log File

[CitizenFX_log_2023-11-07T213643.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13289527/CitizenFX_log_2023-11-07T213643.log)

**Comment by Kromlec** [comment]
Housing weight has been corrected to be what it was intended to be. It was previously not adding the weight correctly and has been corrected as of this morning.

**Comment by turbo-toad** [comment]
Gotcha so the items aren't displaying their real weight right now in city? When I added up the total of my friends storage with every item in there's exact storage it shows 1,515 weight. Is the item weight the one that is showing incorrectly since you guys changed the weight?

**Comment by xXJamieXx** [comment]
Only thing that was changed was the maximum storage capacity of houses so anything else was already the way it is.

**Comment by SaraLef** [comment]
Storages like container is also changed to be extremely tiny and is not being able to be what they used to be.
Makes me guess that warehouses and garages are the same as well.
Don't know if that's intended as well.

**Comment by SpiceF0x** [comment]
It was intended, they were corrected to be what they should have been all along, as stated in the buying guide which is visible to the whole community:

https://tinyurl.com/wolfsbuyingguide

**Comment by SaraLef** [comment]
It is not stated in there about warehouses, garages or container.

**Comment by SpiceF0x** [comment]
All Wolfs interiors were corrected. Those interiors are not residential which is why they're not listed on that guide.

**Comment by SaraLef** [comment]
That doesn't answer anything tho. I was asking about those interiors since our down at the Tuner shop has drastically decreased to 7,5 instead of what it used to be. And I do not know if that was intended for those 3 types of interiors or not, hence to my starting question. It was nothing about interiors for the houses.

**Comment by SpiceF0x** [comment]
It does answer? It was corrected to what it should be. It is now what it should be.
