### ISSUE TITLE
[BUG] <Pounder Custom Back Storage Won't Open>

### ISSUE THREAD

**Issue by turbo-toad** [ParadoxGamingRP/bugs-and-suggestions#1916]
### Your Discord Name

turbotoad

### A clear and concise description of what the bug is

The Pounder Custom's back won't open. Normally to get in the storage of the Pounder Custom you go to the right-hand back side's tires to open it. However now when I go there to open it there is no storage. I've tried opening it all over and it's not working. There seems to be no way to get into the back storage of the Pounder Custom.

### Steps to Reproduce the Bug

Fly Into the city with fresh launch,
Pull out Pounder Custom from parking spot,
Go to the backhand side & make sure the Pounder Custom is unlocked,
Press G like we used to get into the back of the Pounder Custom,
Nothing happens, 
Try to repark and repeat steps,
Same Results,

### Expected Behavior

I expect to go to the back tires to open the storage as has previously been. 

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/137903041/ebae5714-9eb0-4931-b6f2-6ba0c1e46d3a)
Located in the picture is where it normally is able to be opened up.

### Log File

[CitizenFX_log_2023-11-07T235234.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13290422/CitizenFX_log_2023-11-07T235234.log)

**Comment by NickNubbz** [comment]
The only way I managed to get in to my trunk of my pounder is climbing in the back and right at the entrance in let’s you. But if pounder is fully repaired there is no way to get in.
