### ISSUE TITLE
[BUG] Diving again (Sorry)

### ISSUE THREAD

**Issue by agentspooky19** [ParadoxGamingRP/bugs-and-suggestions#1917]
### Your Discord Name

spooky_6464

### A clear and concise description of what the bug is

Went to go diving again as the last bug was fixed but now as I went to go diving again the corals are in the water this time but are floating above everything else not hidden whatsoever. They all were interactive except for two of them and even the treasure chest was floating up above and was also interactive. Below are some pictures of what I experienced to show a bit better than maybe how I'm explaining things. More so opening this so it can get fixed before it's abused. All items I got from Harvesting I just dropped since it didn't feel right keeping them. 

### Steps to Reproduce the Bug

-Dive as normal into given area
-When searching for corals they will be floating in the water just above ground level

### Expected Behavior

-Dive as normal into given area
-Have to search for corals/treasure chest
-Continue with harvesting when found etc. etc. 

### Screenshots/Videos

![kEHfeOV](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/117245051/910d464d-7107-49f4-b62c-7aaded3527fe)
![npeglRW](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/117245051/602df802-191f-4ddf-9876-24d88eb6d195)
![oAorcmT](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/117245051/eb3bcbb3-7589-4b86-868a-d54a8c7b90eb)
![nzBQ7Qc](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/117245051/a8feb786-13c3-4509-8a33-6533a2f3134c)
![XVFTX4B](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/117245051/ced8434b-46f7-495d-a838-56bf70bdc550)

### Log File

[CitizenFX_log_2023-11-08T065727.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13293804/CitizenFX_log_2023-11-08T065727.log)

**Comment by SamB1997** [comment]
Not sure if this was intentional or not but it looks like you get less coral per pickup now?

**Comment by Darahz** [comment]
Nothing has changed other than how the corals are placed down

**Comment by SamB1997** [comment]
Is this something i should open another bug report about? Everybody I've asked is getting less per pickup.

**Comment by Darahz** [comment]
> Is this something i should open another bug report about? Everybody I've asked is getting less per pickup.

Do you get 10 jobs?

**Comment by SaraLef** [comment]
It's RNG. It happens.
