### ISSUE TITLE
[BUG] <PDX races>

### ISSUE THREAD

**Issue by kevstax** [ParadoxGamingRP/bugs-and-suggestions#1918]
### Your Discord Name

KevStax 

### A clear and concise description of what the bug is

PDX races are being thrown up with only one person in the queue.

### Steps to Reproduce the Bug

1. Join race queue
2. race is immediately thrown up

### Expected Behavior

1. join race queue
2. 5 people join queue 
3. race is thrown up

### Screenshots/Videos

https://i.imgur.com/OaPRpHg.png

**Comment by JnKTechstuff** [comment]
Fixed
