### ISSUE TITLE
[BUG] Chop Text Msg issue 

### ISSUE THREAD

**Issue by cythioan** [ParadoxGamingRP/bugs-and-suggestions#1921]
### Your Discord Name

Ghost ( aka lackluster )

### A clear and concise description of what the bug is

Car Chops
1st part of mission notification will come through but txt will not come through but area location of car will show on map.
2nd part of mission once car obtained, notification will come through but txt msg will not, chop location will not display on minimap, or large map.  
When trying to open msg phone gets stuck on loading page. 
( Not sure if this makes a diff but the cat skin is used on the phone ) 
( I think you can still complete the mission if you can find the Chop guy, I was able to find him at one of the locations by chance )

### Steps to Reproduce the Bug

1. Get Chop job
2. Get txt msg ( try and open )
3.  Locate car obtain
4. wait for Chop location
5. Get txt msg ( try and open)
6. Drive and look for Chop guy if you can. 

### Expected Behavior

1. Get job
2. Get txt open txt to get location
3. Obtain Car
4. Get txt msg open to get location of Chop Guy 
5. Drive to chop guy 
6. chop car get stolen parts

### Screenshots/Videos

have to shrink file 

### Log File

[CitizenFX_log_2023-11-02T162142.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13304178/CitizenFX_log_2023-11-02T162142.log)

**Comment by Norgman** [comment]
I would like to add to this report. 
I have had no issues locating the car or locating the chop man, however the chop man refuses to interact with me, leaving me standing there with a tire in my hands and nowhere to put it.

**Comment by shleeyy** [comment]
@Norgman also have the same issue https://medal.tv/games/gta-v/clips/1GJ74INZaHU2ST/d1337mPQett5?invite=cr-MSxYUjEsMTg5NzA2MzQwLA
