### ISSUE TITLE
[BUG] pressing wrong buttons

### ISSUE THREAD

**Issue by joaeeeea** [ParadoxGamingRP/bugs-and-suggestions#1923]
### Your Discord Name

eggos#2023

### A clear and concise description of what the bug is

Whenever i finish a trucking job the complete button just disappears but the cancel button doesnt so i have to cancel it instead of submit it

### Steps to Reproduce the Bug

1. start a job
2. get lucky and get the bug

### Expected Behavior

a

### Screenshots/Videos

a

### Extra Notes (Optional)

a

**Comment by xXJamieXx** [comment]
Closing as working on new trucking job.
