### ISSUE TITLE
[ENHANCEMENT] /killself emote

### ISSUE THREAD

**Issue by Asaineur** [ParadoxGamingRP/bugs-and-suggestions#1925]
**Your Discord Name**
Asaineur

**Describe the annoyance**
I ain't gonna lie I hate how it shows an emote of doing the emote while using the command since server rules and all that. I know a few others are annoyed with it too.

**To Reproduce**
[Steps to reproduce the annoyance]
1. Use Command /killself
2. does an emote of blasting brains
3. dead

**Requested behavior**
Not have an emote and just lets me do it

**Screenshots**

**Additional context**
[Add any other context about the enhancement here]

**Comment by Darahz** [comment]
So you want no way of displaying that ur doing it?
