### ISSUE TITLE
[BUG] Farming Delivieries (Multiple Jobs)

### ISSUE THREAD

**Issue by lPrestonl** [ParadoxGamingRP/bugs-and-suggestions#1932]
### Your Discord Name

soypreston

### A clear and concise description of what the bug is

Bug with the current Farming Deliveries. You can claim multiple of the same jobs and only do them once to receive the payout/xp of multiple jobs.

### Steps to Reproduce the Bug

1. Talk to farmer.
2. Pick a job (For me I did A Helping Hand)
3. Repeat 1 & 2 for your desired amount of times.
4. Do the job Once.
5. Ask for payment.
6. Profit * x amount of times you clicked the job.

### Expected Behavior

To be able to click it only once and get said job or else a "You are already doing that job" to show up. Only receive payout once per job.

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/35425544/dd4c7cc5-b70b-4231-93fd-2b1e6984a887)
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/35425544/6ed71bd4-8473-4ebc-a9a5-66aa74f68ae0)

**Comment by lPrestonl** [comment]
Last time I am doing this, Just wanted to re do the run to get a better photo of the rep aspect.
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/35425544/286b6c38-c240-4c0d-9e6b-931d534c9090)

**Comment by xXJamieXx** [comment]
Job has been pulled until issues are resolved.
