### ISSUE TITLE
[ENHANCEMENT] New Assassination and Hostages

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#1936]
**Your Discord Name**
tusktheshrew

**Describe the annoyance**
When trying to take the hostage route for the Assassination missions there are a couple apparent issues.
1. You can not put a person in a car to take them to the place.
2. I would Rather press E next to the Target instead of missing them over and over with the third eye.

**To Reproduce**
[Steps to reproduce the annoyance]
1. Start Assassination Mission
2.  Use the Hostage method
3. Running across the city because Car can't hold hostage.

**Requested behavior**
Rather An E muscle near the target to help grab the target instead of missing with the third eye causing two extra fingers to be used.
If possible to get the hostage to be able to get in the car.

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by jkaejkae888** [comment]
I can put the target into my cars using the third eye but I'm unable to get them out the car once in the car because the button on the third eye does nothing and if you drag them out the car the car turns into a mini tornado

**Comment by xXJamieXx** [comment]
A couple of things...
1. You can put them in the car, you just third eye the car while holding them? I think I may add an additional check though so it functions like when you're carrying a player where it puts them in the car automatically if you get in one.
2. To get them out of the car again just third eye and use the option to take them out, should put them back in your custody asgain?

**Comment by jkaejkae888** [comment]
For me when I use the third eye and press for them to get out nothing happens

**Comment by xXJamieXx** [comment]
> You just need to step back out the car and comes with? I've had a few successful, any clips guys? or F8?
> 
> I have had that the hostage refused to be a hostage, nothing in F8
> 
> https://streamable.com/kkaco4

You can't knock them out and then take them hostage... they need to be alive...

**Comment by shleeyy** [comment]
this still isnt working properly. 
https://medal.tv/games/gta-v/clips/1FTzoy9kLve_qs/d13371BXjpcv?invite=cr-MSxGZ1csMTg5NzA2MzQwLA

**Comment by xXJamieXx** [comment]
> this still isnt working properly. https://medal.tv/games/gta-v/clips/1FTzoy9kLve_qs/d13371BXjpcv?invite=cr-MSxGZ1csMTg5NzA2MzQwLA

Haha ok I'll look into it
