### ISSUE TITLE
[BUG] assasin

### ISSUE THREAD

**Issue by tfletchskate** [ParadoxGamingRP/bugs-and-suggestions#1937]
### Your Discord Name

tfletch.skate

### A clear and concise description of what the bug is

The assassin missions currently do not produce someone to assassinate

### Steps to Reproduce the Bug

get assassin mission
go to place
no actual target to kill

### Expected Behavior

when i get to the place i have been told to go, there should be someone there to assassinate

### Screenshots/Videos

i dont have one but its pretty obvious

### Extra Notes (Optional)

i dont know if im doing it wrong, but there is also no option to kidnap the target either

### Log File

this is being buggy and not letting me upload - sorry :(

**Comment by xXJamieXx** [comment]
Sounds like you either weren't able to locate them or they escaped without you noticing.
