### ISSUE TITLE
[BUG] Military laptops not working

### ISSUE THREAD

**Issue by NightCrawler706** [ParadoxGamingRP/bugs-and-suggestions#1939]
### Your Discord Name

nightcrawler706

### A clear and concise description of what the bug is

laptops nots counting how many people are holding them

### Steps to Reproduce the Bug

put laptops in your inventory.
it doesnt count them correctly.

### Expected Behavior

its accuratly says how many people are holding laptops

### Screenshots/Videos

N/A

**Comment by xXJamieXx** [comment]
Working as intended. It doesn't count how many players but instead how many groups.
