### ISSUE TITLE
[BUG]  drilling the vault without drill

### ISSUE THREAD

**Issue by PadawanPepsi** [ParadoxGamingRP/bugs-and-suggestions#1943]
### Your Discord Name

padawanpepsi

### A clear and concise description of what the bug is

you can drill in the vault of paleto without a drill in your inventory

### Steps to Reproduce the Bug

start paleto
do hack
do thermite
do drill WITH NO DRILL IN INVENTORY

### Expected Behavior

should not be able to drill without drill

### Screenshots/Videos

no videos sorry

### Log File

[CitizenFX_log_2023-11-21T024225.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13421588/CitizenFX_log_2023-11-21T024225.log)

**Comment by JnKTechstuff** [comment]
Fixed
