### ISSUE TITLE
[BUG] :)))))

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1947]
### Your Discord Name

ssara

### A clear and concise description of what the bug is

You can steal the corals multiple times if youre fast enough with the knife aka hitting that E.

### Steps to Reproduce the Bug

Swim close to coral
Hit E
Swim away and back FASTER THAN AQUAMAN
Hit E again
Gain 2 harvests

### Expected Behavior

Swim close to coral
Hit E
Swim away and back FASTER THAN AQUAMAN
Hit E again
Notice that you are just pressing E for no reason at all cause you're not gaining anything

### Screenshots/Videos

Nah

### Extra Notes (Optional)

Nope

### Log File

Niet

**Comment by JnKTechstuff** [comment]
Should be fixed; I hate people
