### ISSUE TITLE
[ENHANCEMENT] Accessing Pockets when Vehicle has no glovebox

### ISSUE THREAD

**Issue by shleeyy** [ParadoxGamingRP/bugs-and-suggestions#1950]
**Your Discord Name**
Freckles4

**Describe the annoyance**
Hello Hello just had a chat with one of the Mods in regards to an inventory thing with vehicles and not having a glove box. Not sure what kind of coding it would necessarily require or if it would be an easy fix. I own a Trophy Truck on one of my characters and its frustrating to have to pull off to the side of the road to eat or bandage if injured considering I don't usually keep those items in a hot key slot. Is there maybe a way to set the glove box weight to 0 or eve 0.1 with 1 box so your pockets can at least be accessed?

**To Reproduce**
[Steps to reproduce the annoyance]
1. Get in Trophy Truck
2. Reach into pockets
3. NO POCKETS :D

**Requested behavior**
Access to my pockets while driving vehicle with out glovebox. 

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by xXJamieXx** [comment]
Seems fine for me?
https://i.imgur.com/wrZB3fP.png

**Comment by shleeyy** [comment]
not for me :(
https://medal.tv/games/gta-v/clips/1G9dG79Xhbu-u4/d1337PA6oEBZ?invite=cr-MSx6b0wsMTg5NzA2MzQwLA

**Comment by shleeyy** [comment]
ahh i see now 
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/79235795/0bbeb193-0843-4ced-ab46-fd02807125ed)
thank you :D

**Comment by shleeyy** [comment]
@xXJamieXx hey just a heads up because it is different than what was shown in your SS from DEV 
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/79235795/a4b0da7a-38e5-439e-9748-6b9c66979c17)
i can drop things on the floor fr4om the truck

**Comment by CorFinn** [comment]
I believe this is just a side effect of disconnecting the player inventory from a non-existent glovebox inventory. I think it now acts as if you're not in that vehicle and standing in the ground. So it will drop items on the ground like it normally would.

Please don't throw your trash out the window. Littering is bad.

**Comment by xXJamieXx** [comment]
> I believe this is just a side effect of disconnecting the player inventory from a non-existent glovebox inventory. I think it now acts as if you're not in that vehicle and standing in the ground. So it will drop items on the ground like it normally would.
> 
> Please don't throw your trash out the window. Littering is bad.

This is actually intended.

**Comment by shleeyy** [comment]
okay perfect just wanted to make sure :D thank you again for this
