### ISSUE TITLE
[BUG] Aircraft Dealership

### ISSUE THREAD

**Issue by OtisMowle** [ParadoxGamingRP/bugs-and-suggestions#1952]
### Your Discord Name

bimmyr7

### A clear and concise description of what the bug is

When we go down to the Aircraft Dealership at LSIA and attempt to put the Mavrick2 out on the showroom floor to show people it doesn't spawn and just disappears meaning we cannot pull anymore aircrafts out until restart

### Steps to Reproduce the Bug

Open heli menu
click mavrick2
mavrick2 spawns

### Expected Behavior

Open heli menu
click mavrick2
mavrick2 spawns
and we can still use the menu without having to wait for restart

### Screenshots/Videos

https://i.imgur.com/c7mtbtG.jpeg https://i.imgur.com/bJekQyU.jpeg

**Comment by CorFinn** [comment]
Fixed next restart.
