### ISSUE TITLE
[BUG] Aircraft Impound takes money but never gives vehicles.

### ISSUE THREAD

**Issue by ShaymusSavage** [ParadoxGamingRP/bugs-and-suggestions#1953]
### Your Discord Name

shay.mus

### A clear and concise description of what the bug is

After going to the impound, I attempted to get my helicopter out of the impound. It had taken my money, but did not give me my helicopter or spawn it near the impound.

### Steps to Reproduce the Bug

1. Have the Maverick 2 Impounded. 
2. Go to impound third eye the dude.
3. Try to remove it from the impound
4. Get your money taken.
5. Nothing else after that.

### Expected Behavior

1. Have the Maverick 2 Impounded. 
2. Go to impound third eye the dude.
3. Try to remove it from the impound
4. Get your money taken.
5. Be put into your helicopter from impound and be able to fly it away.

### Screenshots/Videos

None.

### Log File

[CitizenFX_log_2023-11-24T001610.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13454090/CitizenFX_log_2023-11-24T001610.log)

**Comment by Bac0nRamen** [comment]
should be fixed next restart its in commits already
