### ISSUE TITLE
[ENHANCEMENT] Some thoughts

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1954]
Ssara 

So some new things that I thought could help some people with their RP in the city would be grave robbing. This could help not only Lunar Angels but also The Plague, or anyone that want's to RP out similar things. 
I wouldn't think this would be any money-giving job but more like the eyeball missions but other organs.

**Comment by tusktheshrew** [comment]
I would love this. I brought this up before I didn't make a report here before.
