### ISSUE TITLE
[BUG] Possible Missing Teleport

### ISSUE THREAD

**Issue by lPrestonl** [ParadoxGamingRP/bugs-and-suggestions#1955]
### Your Discord Name

soypreston

### A clear and concise description of what the bug is

The area where you go to get the mission to Chop Cars has disappeared. I wanted to put this in because I noticed there was change to the teleportation script (Optimizations) wasn't sure if it had moved or the teleport disappeared .

### Steps to Reproduce the Bug

1. Try to enter the area where you go down to the Chop Shop.
2. Do not see the notice to Press E
3. Attempt to press E.
4. No Profit

### Expected Behavior

To be able to enter the garage.

### Screenshots/Videos

No Pic/Video

**Comment by PatrykX904** [comment]
Also happening with SADOT HQ

[SADOT HQ.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13464963/SADOT.HQ.txt)

**Comment by Dez505** [comment]
this is also happening with the Range basement
