### ISSUE TITLE
[BUG] racing tablet not cycling through races

### ISSUE THREAD

**Issue by kevstax** [ParadoxGamingRP/bugs-and-suggestions#1959]
### Your Discord Name

KevStax 

### A clear and concise description of what the bug is

There are 15 race tracks yet it feels like when the tablet throws up races it cycles through the same 5 races.

### Steps to Reproduce the Bug

1. get 5 people in race queue
2. race and finish
3. do another race or two then the same track from the first race gets put back up

### Expected Behavior

1. get 5 people in race queue
2. race and finish
3.  get a different race and only get the same track maybe 5 or so races after

### Screenshots/Videos

no evidence really

**Comment by xXJamieXx** [comment]
Try again after next restart and let me know if its any better.
