### ISSUE TITLE
[BUG] HARNESS ISSUE

### ISSUE THREAD

**Issue by OwlCherry** [ParadoxGamingRP/bugs-and-suggestions#1960]
### Your Discord Name

OwlCherry

### A clear and concise description of what the bug is

odd one, when you get out of your vehicle while wearing seatbelt, it requires you to "undo" seatbelt and refasten it upon getting back into the vehicle without a race harness.

### Steps to Reproduce the Bug

1. put seatbelt on
2. exit car
3. get back in car
4. engage seatbelt (it will not engage and plays unfastened sound)
5 engage seatbelt again

### Expected Behavior

should just require one press of the button instead of several to rebuckle

### Screenshots/Videos

na

**Comment by kevstax** [comment]
I was gonna make a bug about harnesses. When you get in a vehicle with a harness and put it on it says it's on but then you can get out of a car like regular. Seems like the two are flipped.
