### ISSUE TITLE
[BUG] Cuffs

### ISSUE THREAD

**Issue by iamsotorious** [ParadoxGamingRP/bugs-and-suggestions#1965]
### Your Discord Name

sotorious

### A clear and concise description of what the bug is

Some cops when cuffing suspects, does not allow the criminal to break out of cuffs, the animation does not pop up for them. I am one of those cops that people can not resist my cuffs. There is some officers when they cuff that do allow them to break cuffs. Criminal tonight got a bit frustrated about it. This is been on going for over a week now. 

### Steps to Reproduce the Bug

1. cuff the suspect.
2. see if suspect can break out of cuffs
3. if it works when you try it, have someone else try it. it is confirmed everytime. 

### Expected Behavior

criminals should have the chance to break out of cuffs, at least the first time they are cuffed within 30 seconds or more.

### Screenshots/Videos

None. 

### Extra Notes (Optional)

None

**Comment by JnKTechstuff** [comment]
What cuffs (command? 3rd eye? what option?) are you using? Afaik the shackle cuffs don't need a skill-check and are supposed to be used for rule breakers trying to do crazy shit mostly.

**Comment by iamsotorious** [comment]
i use third eye and toggle cuffs the top one on the menu. Seem some officers can super cuff, i mean they are not shackled because they should still move. I think it even happened to you when we were doing our CID case and that one rookie cuffed you and you said i didnt get the skill check. I am one of the officers that can cuff without a skill check as well.     On Friday, December 1, 2023 at 09:08:29 AM CST, JnKTechstuff ***@***.***> wrote:  
 
 


What cuffs (command? 3rd eye? what option?) are you using? Afaik the shackle cuffs don't need a skill-check and are supposed to be used for rule breakers trying to do crazy shit mostly.

**Comment by Dez505** [comment]
I use the cuff command and people can break my cuffs. I’ve been cuffed by cops that use 3rd eye and it dosnt seem like you can break cuffs
