### ISSUE TITLE
[BUG] RC Car Issue

### ISSUE THREAD

**Issue by OwlCherry** [ParadoxGamingRP/bugs-and-suggestions#1969]
### Your Discord Name

OwlCherry

### A clear and concise description of what the bug is

when you pick up and put away your RC car, you can go to the last location and respawn it with no timer. cant pick it up again but does allow you to drive it

### Steps to Reproduce the Bug

1. pick up and put away rc car
2. press f1
3. respawn vehicle
4. get rc car without a timer

### Expected Behavior

should not be able to duplicate.  should not be able to receive back a car after putting it away

### Screenshots/Videos

N/A

### Log File

[CitizenFX_log_2023-11-30T231402.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13518851/CitizenFX_log_2023-11-30T231402.log)

**Comment by JnKTechstuff** [comment]
Fixed
