### ISSUE TITLE
[BUG] Multiple Farmers

### ISSUE THREAD

**Issue by lPrestonl** [ParadoxGamingRP/bugs-and-suggestions#1970]
### Your Discord Name

soypreston

### A clear and concise description of what the bug is

Working for the farmer causes a few issues.. if multiple people are doing the same job it can cause a wide variety of issues. A few times I've had someone else try to deliver something at the same time I am. When I get to the spot to pick up (Whatever I am delivering) there are multiple of them there. Sometimes I have had them explode on me and I can no longer finish the job. Also if enough of it scuffs, people just leave them and they pile up (See screenshot A)

### Steps to Reproduce the Bug

1. Take the job of delivering stuff from the farmer.
2. Someone else also take the job. (However since there is different spawns its not a 100% chance this will happen)
3. Get the same pick up location.

### Expected Behavior

For old trailers to despawn hopefully. As well as the trailers to possible spawn next to each other like trucking does when two people take the same job at the same time.

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/35425544/e39852d9-29ea-4452-9a04-b584c5efebdf)

**Comment by Darahz** [comment]
Did some changes to prevent this
