### ISSUE TITLE
[BUG] SWAT heli go BOOM

### ISSUE THREAD

**Issue by PadawanPepsi** [ParadoxGamingRP/bugs-and-suggestions#1971]
### Your Discord Name

padawanpepsi

### A clear and concise description of what the bug is

This has happened the last two times i flew the swat heli. Ill get it out start flying to and after a little but it explodes for no reason! There is nothing to hit no birds nothing and it just blows HARD.

### Steps to Reproduce the Bug

take out heli at sandy PD
Fly directly to MRPD
Die

### Expected Behavior

dont go boom

### Screenshots/Videos

sorry no have

### Log File

[CitizenFX_log_2023-12-02T031319.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13533277/CitizenFX_log_2023-12-02T031319.log)

**Comment by SaraLef** [comment]
My jet did the same thing, red engined mid-air and then it was ok again after some time. Did it twice.
It was the Luxor
