### ISSUE TITLE
[ENHANCEMENT]  RGB Light Controller

### ISSUE THREAD

**Issue by ColKing** [ParadoxGamingRP/bugs-and-suggestions#1974]
**Colt__**

**Describe the annoyance**
No annoyance; I would like the RGB controller removed from the underground and something we can make at the shop. Just wanted it like this because we do not source the light from the shop, but it's sourced from another thing.  

**To Reproduce**
[Steps to reproduce the annoyance]
1. Remove Lights from the underground
2. Make it something we can craft at the shop 
3. Materials to use are up to you 

**Requested behavior**
Go to our storage, where we craft, and be able to see and craft an RGB controller. 

**Screenshots**

**Additional context**

**Comment by Kromlec** [comment]
Open a scripting ticket in dev.

**Comment by ColKing** [comment]
Sounds good
