### ISSUE TITLE
[BUG] No dropoff marker on map in trucking delivery (PALETO BAY)

### ISSUE THREAD

**Issue by michaelbanks-fivem** [ParadoxGamingRP/bugs-and-suggestions#1976]
### Your Discord Name

feminineboys

### A clear and concise description of what the bug is

The destination is on the map but there is supposed to be a dropoff holographic box where you leave the trailer at. Its in paleto bay in between postal 3017 and 3021.

### Steps to Reproduce the Bug

1.  Take the trucking job, its the one with the most pay usually but I forgot the description. To find which one you can probably check the destination on the map to see if they match up with the postals in the description
2. Go to the location and check if the yellow holobox for dropoff is there

### Expected Behavior

A  box to appear where I can leave my trailer and leave to get paid.

### Screenshots/Videos

I knocked over the trailer in rage after searching for 10 minutes.

### Log File

[CitizenFX_log_2023-12-03T181340.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13540358/CitizenFX_log_2023-12-03T181340.log)

**Comment by xXJamieXx** [comment]
Closing as working on new trucking job.
