### ISSUE TITLE
[BUG] Bossmenu

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#1986]
### Your Discord Name

ssara

### A clear and concise description of what the bug is

Opening bossmenu makes your game freeze

### Steps to Reproduce the Bug

Open bossmenu
Make Otis a greenbean
Can't do anything after closing it
Restart game completely

### Expected Behavior

Open bossmenu
Make Otis a greenbean
Close it and then go on with your life

### Screenshots/Videos

N/A

### Log File

I don't have my logs, forgot to save it

**Comment by Bac0nRamen** [comment]
closing since we had not had any other reports or issues on this
