### ISSUE TITLE
[BUG] Racing tablet

### ISSUE THREAD

**Issue by OtisMowle** [ParadoxGamingRP/bugs-and-suggestions#1987]
### Your Discord Name

bimmyr7

### A clear and concise description of what the bug is

Racing tablet has started to throw up the same races multiple times in a row, we keep having to put up races as the tablet isn't choosing other races, for example we just raced eastside issues, we waited for a new race to pop up and it threw eastside issues up again 

### Steps to Reproduce the Bug

join Queue
wait for race to pop
race that track 
then a different track pop up 

### Expected Behavior

join Queue
wait for race to pop
race that track 
then a different track pop up

### Screenshots/Videos

https://i.imgur.com/4uwwFet.png

**Comment by xXJamieXx** [comment]
Was told about this before and made a change and was then told it was much better so confused by this. But either way its random so occasionally you might see the same track thats just how it is.

**Comment by kevstax** [comment]
yeah it appeared good. but then it kinda went back to throwing up the same tracks again. tbh, no need to really worry about it most of us just end up throwing up whatever track we would like to run next.
