### ISSUE TITLE
chop shop doesn't work 

### ISSUE THREAD

**Issue by tfletchskate** [ParadoxGamingRP/bugs-and-suggestions#1993]
### Your Discord Name

tfletch.skate

### A clear and concise description of what the bug is

when you have finished the stealing the car part of the chop shop mission. it is impossible to third eye the guy you give the car parts to

### Steps to Reproduce the Bug

get chopping mission
steal car
take to drop off location
take off part from car e.g front left tire
go to hand in part 
cant third eye the guy

### Expected Behavior

can third eye the guy and get car parts from him

### Screenshots/Videos

N/A

### Extra Notes (Optional)

[CitizenFX_log_2023-12-12T172738.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677996/CitizenFX_log_2023-12-12T172738.log)

### Log File

[CitizenFX_log_2023-12-12T172817.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677954/CitizenFX_log_2023-12-12T172817.log)
[CitizenFX_log_2023-12-12T192318.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677955/CitizenFX_log_2023-12-12T192318.log)
[CitizenFX_log_2023-12-12T192334.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677956/CitizenFX_log_2023-12-12T192334.log)
[CitizenFX_log_2023-12-14T160315.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677958/CitizenFX_log_2023-12-14T160315.log)
[CitizenFX_log_2023-12-14T160434.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677959/CitizenFX_log_2023-12-14T160434.log)
[CitizenFX_log_2023-12-14T173903.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677961/CitizenFX_log_2023-12-14T173903.log)
[CitizenFX_log_2023-12-14T173928.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677962/CitizenFX_log_2023-12-14T173928.log)
[CitizenFX_log_2023-12-07T183828.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677964/CitizenFX_log_2023-12-07T183828.log)
[CitizenFX_log_2023-12-07T183907.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677965/CitizenFX_log_2023-12-07T183907.log)
[CitizenFX_log_2023-12-07T194904.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677966/CitizenFX_log_2023-12-07T194904.log)
[CitizenFX_log_2023-12-07T194932.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677967/CitizenFX_log_2023-12-07T194932.log)
[CitizenFX_log_2023-12-08T180103.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677968/CitizenFX_log_2023-12-08T180103.log)
[CitizenFX_log_2023-12-08T180156.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677969/CitizenFX_log_2023-12-08T180156.log)
[CitizenFX_log_2023-12-08T195854.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677971/CitizenFX_log_2023-12-08T195854.log)
[CitizenFX_log_2023-12-08T195917.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677972/CitizenFX_log_2023-12-08T195917.log)
[CitizenFX_log_2023-12-09T195420.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677973/CitizenFX_log_2023-12-09T195420.log)
[CitizenFX_log_2023-12-09T195459.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677974/CitizenFX_log_2023-12-09T195459.log)
[CitizenFX_log_2023-12-09T222247.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677975/CitizenFX_log_2023-12-09T222247.log)
[CitizenFX_log_2023-12-09T222315.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677976/CitizenFX_log_2023-12-09T222315.log)
[CitizenFX_log_2023-12-09T223303.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677977/CitizenFX_log_2023-12-09T223303.log)
[CitizenFX_log_2023-12-09T223318.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677978/CitizenFX_log_2023-12-09T223318.log)
[CitizenFX_log_2023-12-09T225925.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677980/CitizenFX_log_2023-12-09T225925.log)
[CitizenFX_log_2023-12-09T230055.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677981/CitizenFX_log_2023-12-09T230055.log)
[CitizenFX_log_2023-12-09T230140.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677982/CitizenFX_log_2023-12-09T230140.log)
[CitizenFX_log_2023-12-09T230200.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677983/CitizenFX_log_2023-12-09T230200.log)
[CitizenFX_log_2023-12-10T173820.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677984/CitizenFX_log_2023-12-10T173820.log)
[CitizenFX_log_2023-12-10T173859.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677985/CitizenFX_log_2023-12-10T173859.log)
[CitizenFX_log_2023-12-10T182604.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677986/CitizenFX_log_2023-12-10T182604.log)
[CitizenFX_log_2023-12-10T182628.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677987/CitizenFX_log_2023-12-10T182628.log)
[CitizenFX_log_2023-12-11T180328.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677988/CitizenFX_log_2023-12-11T180328.log)
[CitizenFX_log_2023-12-11T180357.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677989/CitizenFX_log_2023-12-11T180357.log)
[CitizenFX_log_2023-12-11T182531.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677990/CitizenFX_log_2023-12-11T182531.log)
[CitizenFX_log_2023-12-11T182602.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677991/CitizenFX_log_2023-12-11T182602.log)
[CitizenFX_log_2023-12-11T193955.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677992/CitizenFX_log_2023-12-11T193955.log)
[CitizenFX_log_2023-12-11T194025.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677993/CitizenFX_log_2023-12-11T194025.log)
[CitizenFX_log_2023-12-12T165504.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677994/CitizenFX_log_2023-12-12T165504.log)
[CitizenFX_log_2023-12-12T165601.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13677995/CitizenFX_log_2023-12-12T165601.log)

**Comment by shleeyy** [comment]
can also say ive had this happen recently

**Comment by xXJamieXx** [comment]
Duplicate of #1930
