### ISSUE TITLE
[BUG] Scuba tank, negative oxygen issues

### ISSUE THREAD

**Issue by Norgman** [ParadoxGamingRP/bugs-and-suggestions#1994]
### Your Discord Name

Norgman

### A clear and concise description of what the bug is

There are issues with the normal Diving Gear (and probably with the lightweight one also).
If you run out of oxygen underwater, the timer goes into negative numbers and you essentially have infinite oxygen.
If you un-equip and re-equip a tank with negative oxygen, it reverts back to however much oxygen you started the dive with, again giving you infinite oxygen.

### Steps to Reproduce the Bug

1. Enter water with Diving Gear (and probably Lightweight as well) with 'X' seconds of oxygen left in tank.
2. Stay underwater until you run out of oxygen. The timer will go in to negative numbers. You now have infinite oxygen if you keep the tank equipped. Surfacing and diving back down just continues the negative counter.
3. Unequip tank and re-equip it. The tank goes back to the 'X' amount of oxygen.

### Expected Behavior

When your oxygen tank runs out, it should stay at 0 seconds and you should start using your own lung capacity.

### Screenshots/Videos

![2023-12-15 (3)](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/150081443/8a7e5e07-f92c-4fb7-92cc-73960aa3ed61)

![2023-12-15 (5)](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/150081443/ef6a768a-c728-454a-9833-d7891dad9af6)
This is the diving gear after I took it to negative numbers, un-equipped it, then re-equipped it again.
The timer went right back to where it was at before I started diving.

**Comment by Darahz** [comment]
I had a grace period in there. But 30 was way too much. I changed it to 0
