### ISSUE TITLE
[BUG] Moonshine can't be reopened

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#1995]
### Your Discord Name

tusktheshrew

### A clear and concise description of what the bug is

When trying to do Moonshine, the still gives an error when trying to reopen it.

### Steps to Reproduce the Bug

1. put down still
2. Fill still with stuffs
3. Fill tank with water
4. try to open still up again.

### Expected Behavior

Still opens normally.

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/98053772/7ff34ef8-30ec-4a36-99b0-b28abd8b052f)

### Extra Notes (Optional)

Sharing Script errors below.

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/35222814/86573aa3-b4ed-4147-948f-8195b4437fc2)

### Log File

[Moonshine.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13693375/Moonshine.txt)

**Comment by tusktheshrew** [comment]
As another Note I can't pickup the still either. So i had to leave it.

**Comment by tusktheshrew** [comment]
I picked up the still after taking up my water tank. Gave me double moonshine. Got rid of the extra fake moonshine.

**Comment by Bac0nRamen** [comment]
This was fixed with this a week ago. is this all good now?

**Comment by tusktheshrew** [comment]
Havent tested because Moonshine is moved along with the update.
