### ISSUE TITLE
[BUG] Prison Jobs have some issues.

### ISSUE THREAD

**Issue by jplink420** [ParadoxGamingRP/bugs-and-suggestions#1999]
### Your Discord Name

j_plink

### A clear and concise description of what the bug is

When doing some of the prison jobs (Specifically in this case, repairing fences and electrical boxes), once you get done a few tasks, the green arrow won't seem to move to another point, and the 3rd eye option will also duplicate. You are also able to see spots you have already repaired and also repair those fences, allowing you to quickly finish this job and grind the materials without having to find the next spot.

### Steps to Reproduce the Bug

1. Be a prisoner
2. Go to do a job to find some goodies
3. Be able to do the same task over and over again at the same spot. 

### Expected Behavior

For me to have to go to different spots for every job.

### Screenshots/Videos

N/A

### Log File

[CitizenFX_log_2023-12-18T072252.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13700984/CitizenFX_log_2023-12-18T072252.log)

**Comment by Darahz** [comment]
Fixed now!
