### ISSUE TITLE
[BUG] Chop shop drop off

### ISSUE THREAD

**Issue by Zach2Blame** [ParadoxGamingRP/bugs-and-suggestions#2000]
### Your Discord Name

Zach2Blame

### A clear and concise description of what the bug is

The Chop Missions are completely Scuffed. The cars are not spawning, spawning upside down, Spawning destroyed, then when they do spawn properly, the spot you have to take the car never works. Either the guy to give parts to never spawns, you aren’t able to take parts off of the car, or you can’t give parts to the guy. Then you’re stuck with parts in your hand and have to relog. I have had this issue 7 out of the 8 times I have done chopping. The only time it worked was when someone showed me how to do it. I have tried several different things and it is not working. 

### Steps to Reproduce the Bug

Literally all I am doing is running the Chop missions in the server and it’s not working 

### Expected Behavior

I expected to not have cars actually spawn, and not spawn upside down, destroyed. I also expect the the Guy to give parts to, to actually spawn, and take the parts 

### Screenshots/Videos

I took a video but it wants to take 8 years to upload. 

### Log File

I am on my cell phone and unable to get the log files right now. The problem has been happening the last 3-4 days I want to say

**Comment by xXJamieXx** [comment]
Need log file or screenshot of F8 after trying to hand in the parts because I added debug prints that I need to see.

**Comment by Zach2Blame** [comment]
I wasn't exactly sure which one it was as so i uploaded all of the logs i had for the 17th. I do have a Recording of trying to hand in the parts but i did not open the F8 menu. The does not want to upload either.


[CitizenFX_log_2023-12-17T194706.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13714666/CitizenFX_log_2023-12-17T194706.log)

[CitizenFX_log_2023-12-17T182854.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13714668/CitizenFX_log_2023-12-17T182854.log)

[CitizenFX_log_2023-12-17T182823.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13714671/CitizenFX_log_2023-12-17T182823.log)

[CitizenFX_log_2023-12-17T170635.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13714672/CitizenFX_log_2023-12-17T170635.log)

[CitizenFX_log_2023-12-17T170618.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13714673/CitizenFX_log_2023-12-17T170618.log)

[CitizenFX_log_2023-12-17T165348.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13714674/CitizenFX_log_2023-12-17T165348.log)

[CitizenFX_log_2023-12-17T165320.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13714675/CitizenFX_log_2023-12-17T165320.log)

[CitizenFX_log_2023-12-18T032545.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13714678/CitizenFX_log_2023-12-18T032545.log)

[CitizenFX_log_2023-12-18T032511.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13714681/CitizenFX_log_2023-12-18T032511.log)

[CitizenFX_log_2023-12-18T002326.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13714683/CitizenFX_log_2023-12-18T002326.log)

[CitizenFX_log_2023-12-17T194719.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13714684/CitizenFX_log_2023-12-17T194719.log)

**Comment by Zach2Blame** [comment]
I also attempted to do the Car chopping today with a friend and we found the car which was going Mach 10 backwards running us over and destroying a lot of things. Once we managed to stop the car and get in it, It would not give us a location for the Parts guy. I do not know of any other people who Chop cars, or any other issues other than the ones my friends and i have witnessed and expressed in this report

**Comment by Zach2Blame** [comment]
Here is the Link to the clip I took of the problem happening. No Third eye option on the guy. I did everything exactly as how I was shown to do it the first time and since then I have had zero luck. Before this attempt I tried to chop and the car would not spawn. I literally drove around the whole area multiple times with a friend and couldn't find it. 10 out of the 11 times I have tried something has gone wrong, which sucks given all the time I have put into trying to chop. Then the few times my friends have tried it doesn't work. Hopefully with this clip will help and whatever issue that is happening will be fixed. Let me know if the clips works or not

https://clipchamp.com/watch/F8JtkLnZn30

**Comment by xXJamieXx** [comment]
> Here is the Link to the clip I took of the problem happening. No Third eye option on the guy. I did everything exactly as how I was shown to do it the first time and since then I have had zero luck. Before this attempt I tried to chop and the car would not spawn. I literally drove around the whole area multiple times with a friend and couldn't find it. 10 out of the 11 times I have tried something has gone wrong, which sucks given all the time I have put into trying to chop. Then the few times my friends have tried it doesn't work. Hopefully with this clip will help and whatever issue that is happening will be fixed. Let me know if the clips works or not
> 
> https://clipchamp.com/watch/F8JtkLnZn30

When was this clip taken?

**Comment by Zach2Blame** [comment]
The Clip was taken today between 7:00 - 9:00

**Comment by xXJamieXx** [comment]
Made some changes so might be better now?
