### ISSUE TITLE
[BUG] <merryweather bug>

### ISSUE THREAD

**Issue by kevstax** [ParadoxGamingRP/bugs-and-suggestions#2002]
### Your Discord Name

KevStax 

### A clear and concise description of what the bug is

After getting merryweather job if u headpop/flyout and come immediately back it bugs out when u go to do the actual job and says you were not the person to reserve the hack

### Steps to Reproduce the Bug

1. get job from place
2.  fly out/headpop
3. fly back in and get job again from the place
4. do the job and use the tools on the door
5. get told you were not the person to reserve the job
6. get no payout and lose c4
7. sad 

### Expected Behavior

1. get job from place
2.  fly out/headpop
3. fly back in and get job again from the place
4. do the job and use the tools on the door
5.  door blows open
6. get payout
7. run and either get caught or getaway
8. be happy

### Screenshots/Videos

n/a

### Log File

[CitizenFX_log_2023-12-19T014452.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13711120/CitizenFX_log_2023-12-19T014452.log)

**Comment by JnKTechstuff** [comment]
Yeah it doesn't support crashing in this one area. Not redesigning shit for the 1% cases
