### ISSUE TITLE
[ENHANCEMENT] Fines showing in transaction history

### ISSUE THREAD

**Issue by NightCrawler706** [ParadoxGamingRP/bugs-and-suggestions#2004]
**Your Discord Name**
[nightcrawler706]

**Describe the annoyance**
[GOT FINED 75K by cops and can't prove it]

**To Reproduce**
[Steps to reproduce the annoyance]
1. 
2. 
3. 

**Requested behavior**
[ fines show up in bank history ]

**Screenshots**
[ https://medal.tv/games/gta-v/clips/1IJMpPk_qFADei/d1337kOJZPLz?invite=cr-MSxINnMsMTg3NzY4MjExLA ]

**Additional context**
[Add any other context about the enhancement here]

**Comment by Darahz** [comment]
So... Have you tried a staff report to get your cash back? And what do you want changed with this enhancement?
Fines showing up on the banking statements?

**Comment by NightCrawler706** [comment]
yea
