### ISSUE TITLE
[BUG] Paintball PED

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#2005]
### Your Discord Name

ssara

### A clear and concise description of what the bug is

Paintball ped has gone on strike or sumtin. Can't clock in. 

### Steps to Reproduce the Bug

Go to paintball and try to clock in 
Dude gone
Be sad

### Expected Behavior

Go to paintball and clock in 
Clock in
HAVE FUN

### Screenshots/Videos

N/A cause he aint here

**Comment by JnKTechstuff** [comment]
Should be fixed
