### ISSUE TITLE
[BUG] <rgb headlights reset >

### ISSUE THREAD

**Issue by kevstax** [ParadoxGamingRP/bugs-and-suggestions#2009]
### Your Discord Name

KevStax 

### A clear and concise description of what the bug is

If you pull an engine with RGB headlights when you put it back in the color of the light resets 

### Steps to Reproduce the Bug

1. Pull engine with lights 
2. Put engine back in car 
3.RGB color resets to white 

### Expected Behavior

1.pull engine with lights 
2.put engine back 
3. Light remains color you had it 

### Screenshots/Videos

N/a

**Comment by JnKTechstuff** [comment]
The battery reset all the electronics in the car. Gotta reset all your saved stations. 

Not a problem worth the effort to solve, sorry
