### ISSUE TITLE
[BUG] Chopping

### ISSUE THREAD

**Issue by JamosesCrust** [ParadoxGamingRP/bugs-and-suggestions#2014]
### Your Discord Name

Hood TM#0260

### A clear and concise description of what the bug is

I am unable to third eye the chopping ped.

### Steps to Reproduce the Bug

Bring car to the chopping guy and attempt to third eye him to get car parts.

### Expected Behavior

Third eye him and receive car parts.

### Screenshots/Videos

0

### Extra Notes (Optional)

0

### Log File

[chop bug.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13757301/chop.bug.txt)

**Comment by xXJamieXx** [comment]
@JamosesCrust did you remove a part from the car and third eye the hand in ped while holding it?
