### ISSUE TITLE
[BUG] Unwanted Wedding rings

### ISSUE THREAD

**Issue by agentspooky19** [ParadoxGamingRP/bugs-and-suggestions#2017]
### Your Discord Name

spooky_6464

### A clear and concise description of what the bug is

Super random bug, but all of the women in the city currently are wearing wedding rings. They don't show for us when we look at ourselves, but when looking at other women they are wearing rings when they are not. 

### Steps to Reproduce the Bug

Just got to look at the women, it's the left-hand engagement finger

### Expected Behavior

Only wear ring if we choose to put it on

### Screenshots/Videos

![](https://i.imgur.com/PhRSIxM.png)

![](https://i.imgur.com/hvZB3yX.png)

### Log File

[CitizenFX_log_2023-12-24T023126.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13760791/CitizenFX_log_2023-12-24T023126.log)

**Comment by Drunkle716** [comment]
Set decal to -1

**Comment by Drunkle716** [comment]
![FiveM_b3095_GTAProcess_14qxHig7hi](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/100391224/96817210-a9f4-43de-9345-902b75186849)
Set decal to -1.

**Comment by Drunkle716** [comment]
@agentspooky19

**Comment by agentspooky19** [comment]
@Drunkle716 we sat through and removed and put everything -1 for shirts, pants and shoes etc. etc.  and Sen was still wearing a ring. To myself I wasn't wearing a ring but to others I was. I'm not really sure what it could be.

**Comment by Drunkle716** [comment]
![FiveM_b2944_GTAProcess_LefCXrGNVo](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/100391224/050eac9f-f9ef-4b58-873f-5533f3f34f30)
This one is from live. Seems to be no issue. Would need to see the entire outfit numbers to check it.

**Comment by agentspooky19** [comment]
You're not going to see it on yourself, you'll have to have someone else there with you to see it on them and them see it on you. The outfit/numbers didn't matter Sen went through all of her outfits, one's she's had for ages and it was showing up with those as well. I don't mind popping in if you need someone to show

**Comment by Drunkle716** [comment]
It'll be fixed tomorrow.
