### ISSUE TITLE
[BUG] not able to open chop text

### ISSUE THREAD

**Issue by tbbubz** [ParadoxGamingRP/bugs-and-suggestions#2018]
### Your Discord Name

tbbubz

### A clear and concise description of what the bug is

When doing a chop, I am unable to open the text message from the job guy to get location to bring the vehicle to chop when i try to open it from notifications my messages just show as loading.

### Steps to Reproduce the Bug

1. get chop job
2. find vehicle 
3. get in vehicle and wait for text
4. get text with drop off location
5. open text to have no message and only loading continuously 

### Expected Behavior

1. get chop job
2. find vehicle
3. get in vehicle and wait for text
4. get text with drop off location
5. be able to open text and click on pinged location to bring chopped vehicle

### Screenshots/Videos

![loading](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/154731897/c6daa438-4b40-4a45-a1d7-eb325844322c)

**Comment by Bac0nRamen** [comment]
Chop has been reworked since this bug. This is most likely no longer a issue
