### ISSUE TITLE
[BUG] Vehicle spawn clipping

### ISSUE THREAD

**Issue by SketchyNath** [ParadoxGamingRP/bugs-and-suggestions#2021]
### Your Discord Name

SketchyNath

### A clear and concise description of what the bug is

When you spawn a vehicle with SADOT from the 907 repair garage, it spawns in the tree that's been planted in the middle of the ground next to the garage. 

### Steps to Reproduce the Bug

1. Clock on as SADOT
2. Head to postal 907
3. Go in and see the guy in the office and spawn a SADOT vehicle
4. Clip into tree

### Expected Behavior

Expected behaviour would be to not clip into a darn tree when you collect your glorious tow truck

### Screenshots/Videos

https://i.imgur.com/pCzUIRE.jpeg

**Comment by Bac0nRamen** [comment]
next restart
