### ISSUE TITLE
[BUG] <unable to change license plate on car>

### ISSUE THREAD

**Issue by kevstax** [ParadoxGamingRP/bugs-and-suggestions#2023]
### Your Discord Name

KevStax 

### A clear and concise description of what the bug is

no option in the mod shop to change car license plates.

### Steps to Reproduce the Bug

1. go in mod shop
2. look for plate # change
3. no option found

### Expected Behavior

1. go in mod shop
2. change license plate # 
3.  be happy

### Screenshots/Videos

n/a

**Comment by xXJamieXx** [comment]
Duplicate of #2001
