### ISSUE TITLE
Boosting not spawning the car

### ISSUE THREAD

**Issue by jkaejkae888** [ParadoxGamingRP/bugs-and-suggestions#2024]
### Your Discord Name

jkaejkae888

### A clear and concise description of what the bug is

thermite into the garage and no car appears. 

### Steps to Reproduce the Bug

thermite into the garage and no car shows.

### Expected Behavior

car shows

### Screenshots/Videos

n/a

### Extra Notes (Optional)

when we go back out it puts us in a bubble with no one else, this bug has also happened 3/4 times this week.

### Log File

[CitizenFX_log_2023-12-26T212903.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13773828/CitizenFX_log_2023-12-26T212903.log)

**Comment by JnKTechstuff** [comment]
Leave the garage and re-enter it has a fix built into the script

**Comment by jkaejkae888** [comment]
Thank you
