### ISSUE TITLE
Truck Job Bug

### ISSUE THREAD

**Issue by tof-tof69** [ParadoxGamingRP/bugs-and-suggestions#2025]
### Your Discord Name

tof__tof

### A clear and concise description of what the bug is

When delivering the goods during the truck job I don't get a pop up that tells me to sell them 

### Steps to Reproduce the Bug

Getting the truck job 
Deliver it to the spot in tataviam mountains
once arrived and while standing over the highlighted area the players doesnt get a pop to sell the goods

### Expected Behavior

getting the pop in the top right that says "Press "E" to sell goods or somehting like that i dont remember"

### Screenshots/Videos

![image_2023-12-28_233347867](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/82468585/4de195d5-b54b-48e9-bf48-47f037fb602d)

### Extra Notes (Optional)

just wanted to mention that sometimes while doing the job the truck would just disappear and the job gets bugged cuz i have the goods but not the truck, unfortunately i dont have any screenshots of that happening but will make sure to tale some if that happens

### Log File

[CitizenFX_log_2023-12-28T184519.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13789379/CitizenFX_log_2023-12-28T184519.log)

**Comment by Bac0nRamen** [comment]
Trucking bugs out at times. Just relog and do the job again until we are able to redo the civ jobs
