### ISSUE TITLE
[ENHANCEMENT] Graverobbing is not an Assassination Turn In

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#2027]
**Your Discord Name**
Tusktheshrew

**Describe the annoyance**
If a person turns in a body part into the assassination guy from graverobbing it will poof and not give anything in return.

**To Reproduce**
[Steps to reproduce the annoyance]
1. Go graverobbing and get a body part (tooth)
2.  Go to assasination guy and try to turn in.
3.  

**Requested behavior**
A denial of the item refunding the body part to the person and/or a graverobbing turn in.
**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by emeraldleo1982** [comment]
I kind of like this one for immersion honestly. If some dude walked up and randomly handed me a body part I didn't ask for, I'd throw that shit away too. If the body parts from both jobs are the same I can see an issue.

**Comment by tusktheshrew** [comment]
Update: The new commit only allows the first item to be sold. But no ones after.

Example sold a finger, got 0 dollars for next finger.

**Comment by tusktheshrew** [comment]
Update: Body parts sold are tied to person who got them from the grave. Ex. I got a nail and are allowed to sell a nail, but if i sell nails someone else dug up it will give me no item back and no money.
