### ISSUE TITLE
[ENHANCEMENT/BUG] Mobile Labs

### ISSUE THREAD

**Issue by kingtortle** [ParadoxGamingRP/bugs-and-suggestions#2028]
[parthernax]

**Describe the annoyance**
[When the mobile labs are in production anyone can walk up pick the lock and "cancel" your production and take the supplies. I have not had the chance to test whether you get supplies or not when cancelled because of the deployment issue but I presume so because i've seen it happen a couple times now to different people. This is an issue because of the amount of time the process takes, there is no way to guard it all times and allows you to get robbed with basically zero interaction (Very unlikely you'll get to it before its robbed if you get the alert).]

**To Reproduce**
[Steps to reproduce the annoyance]
1. Find lab, break locks.
2. Walk up to whatever is in production and stop it
3. Either Profit or just fuck over the person producing.

**Requested behavior**
[ I think once you commit you commit and you shouldnt be able to cancel it until the time is done or if it has to be done in a scuff situation it should only be possible by the person who started it/ owner of the lab. If it were done this way it would make you have to fight either fight to take the product when its done producing or hoping the owner isn't nearby.]

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[With the major time investment I feel you should at least be able to stand your ground for what you have. Im open to making this a feedback discussion in the discord but this feels more like a passed over bug than anything.]

**Comment by JnKTechstuff** [comment]
Thats the whole point of them.
