### ISSUE TITLE
[BUG] Where Coral?

### ISSUE THREAD

**Issue by rmanky** [ParadoxGamingRP/bugs-and-suggestions#2029]
### Your Discord Name

rmanky

### A clear and concise description of what the bug is

While doing a coral job, there is no coral to be seen anywhere in the designated area. I noticed in the logs:

```
[   1227407] [b2944_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @prdx_civjobs/client/cl_coralharvest.lua:500: attempt to index a nil value (global 'postion')^7
[   1227407] [b2944_GTAProce]             MainThrd/ ^3> handler^7 (^5@prdx_civjobs/client/cl_coralharvest.lua^7:500)
```

### Steps to Reproduce the Bug

1. Get the thing, do the required steps
2. Go to the area
3. Look for coral

### Expected Behavior

For there to be harvest-able coral in the area

### Screenshots/Videos

![image](https://i.imgur.com/7ssT9FB.jpeg)

### Log File

[CitizenFX_log_2023-12-30T231741.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13799436/CitizenFX_log_2023-12-30T231741.log)

**Comment by Darahz** [comment]
Yup... Thats on me, i forgot to change a thing. Will be fixed next restart

**Comment by rmanky** [comment]
Huzzah, it worked, thanks!

**Comment by Darahz** [comment]
Awesome! Enjoy the diving!
