### ISSUE TITLE
[BUG] <Chop Shop>

### ISSUE THREAD

**Issue by Skeletal-KC** [ParadoxGamingRP/bugs-and-suggestions#2036]
### Your Discord Name

skeletal_kc

### A clear and concise description of what the bug is

The target cars for the chop shop seem to have a consistent issue of either not spawning at all, or spawning without a local driving the car. If the car spawns with no driver and you are somehow able to still gain control of it (extremely difficult unless they happen to get stuck on something) the mission soft locks and won't give you the next location.

The two most common areas where these bugs seem to take place in are Sandy and Grapeseed for some reason.

### Steps to Reproduce the Bug

1. Pick up the mission from the Chop Shop guy
2. Go to the area where the car is supposed to be
3. Cross your fingers.

### Expected Behavior

Expected the car to be in the circle, and expected the car to have a driver?

### Screenshots/Videos

N/A

**Comment by JnKTechstuff** [comment]
On slate to be redone
