### ISSUE TITLE
[BUG] Coral detector gives same location over and over

### ISSUE THREAD

**Issue by NataliaGallo96** [ParadoxGamingRP/bugs-and-suggestions#2037]
### Your Discord Name

carebear9696

### A clear and concise description of what the bug is

When doing coral and using the coral detector it keeps giving you the exact same location over and over again.

### Steps to Reproduce the Bug

1.use coral detector
2. get a spot on the map
3. do job
4. use coral detector again
5. get same spot

### Expected Behavior

1.use coral detector
2. get a spot on the map
3. do job
4. use coral detector again
5. get different spot

### Screenshots/Videos

n/a

**Comment by Darahz** [comment]
Should be fixed now
