### ISSUE TITLE
[BUG] Coral jobs giving less that stated

### ISSUE THREAD

**Issue by Squeekyboi** [ParadoxGamingRP/bugs-and-suggestions#2038]
### Your Discord Name

Squeekyboi

### A clear and concise description of what the bug is

When you arrive at a location that has been scanned it will say there is 10 available in the area but usually I get 4/5 then the rest cannot be harvested after completing a couple of jobs.

### Steps to Reproduce the Bug

1, Speak to coral man to get job
2. go to location 
3. Once at correct location tells you 10 coral in the area including a treasue chest
4. harvest 5 then can't find anymore

### Expected Behavior

1, Speak to coral man to get job
2. go to location 
3. Once at correct location tells you 10 objectives
4. farm 10 objectives not less

### Screenshots/Videos

https://www.youtube.com/watch?v=ubfrndE7LcA

### Extra Notes (Optional)

This was also an issue before the recent changes to the coraling job, other than this I haven't spotted any other issues and everything works as expected.

### Log File

[CitizenFX_log_2024-01-07T101844.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13853954/CitizenFX_log_2024-01-07T101844.log)

**Comment by Darahz** [comment]
Did a change to how the corals spawns. Hopefully this will fix this issue

**Comment by Squeekyboi** [comment]
Awesome, fingers crossed! Appreciate your time looking into it :)

**Comment by Bac0nRamen** [comment]
next restart
