### ISSUE TITLE
[BUG] I can't raid dirty crimers

### ISSUE THREAD

**Issue by Drunkle716** [ParadoxGamingRP/bugs-and-suggestions#2039]
### Your Discord Name

MainCharacter716

### A clear and concise description of what the bug is

Try to raid homes or storefronts and the raid button doesn't work. Also, can't see garages at these homes to raid them as well.

### Steps to Reproduce the Bug

Got to an owned house as a cop
Raid it
Try to find the garage
Can't find it and raid it.

### Expected Behavior

Be a cop and raid houses and garages.

### Screenshots/Videos

None

**Comment by LitrlyD3ad** [comment]
To build off this, if you raid a house you cannot access the houses stash.
