### ISSUE TITLE
[BUG] coral hunter not giving location on map

### ISSUE THREAD

**Issue by NataliaGallo96** [ParadoxGamingRP/bugs-and-suggestions#2040]
### Your Discord Name

carebear9696

### A clear and concise description of what the bug is

tried the coral after tsunami and when using the detector it doesn't give you the mark on the map. the detector is on as I hear the beeping

### Steps to Reproduce the Bug

1. go to coral guy and talk to him
2. use coral detector 
3. look at map

### Expected Behavior

1. go to coral guy and talk to him
2. use coral detector 
3. look at map
4. see location given

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/123715929/e4b625fc-7574-423b-8656-84cf265183c7)
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/123715929/9e5ce4fd-b85f-46a2-9776-e273084f6903)

**Comment by Darahz** [comment]
That's how its ment to be

**Comment by Darahz** [comment]
Find out how it works in city :-)
