### ISSUE TITLE
[BUG] SADOT 'Garage Vehicle' sending vehicles to impound

### ISSUE THREAD

**Issue by SketchyNath** [ParadoxGamingRP/bugs-and-suggestions#2041]
### Your Discord Name

SketchyNath

### A clear and concise description of what the bug is

I have used the 'Garage Vehicle' option a few times now for people, and it doesn't return the vehicle to its last parked garage but instead to the impound.

### Steps to Reproduce the Bug

1. Clock in as SADOT
2. Find civ owned vehicle(s)
3. Use 'Garage Vehicle' option in tow menu
4. Have owner look for vehicle(s) in garage
5. Have owner look for vehicle(s) in impound

### Expected Behavior

Behaviour expected of this script would be to have the vehicle be sent back to its last posted garage instead on impound.

### Screenshots/Videos

N/A

**Comment by xXJamieXx** [comment]
Idk worked on my vehicle so I've changed something that may have caused an issue?

**Comment by SketchyNath** [comment]
> Idk worked on my vehicle so I've changed something that may have caused an issue?

It was a couple of weeks ago now, I've not used it since. Maybe someone fixed it with something else?
