### ISSUE TITLE
[BUG] some emote props disappear

### ISSUE THREAD

**Issue by PadawanPepsi** [ParadoxGamingRP/bugs-and-suggestions#2043]
### Your Discord Name

padawanpepsi

### A clear and concise description of what the bug is

some emotes like e cigar and e walkingstick when you do them the prop for the emote appears for a second and then is gone.

old people cant walk anymore :(

### Steps to Reproduce the Bug

e walkingstick
e cigar

### Expected Behavior

stay there and help the old 

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/96961442/ff41631d-91f6-40d3-888f-63bae59480ed)

**Comment by Bac0nRamen** [comment]
walking stick is fixed   i think i have to find new animations for the smoke ones they are just broke

**Comment by Bac0nRamen** [comment]
There was a update for the emote menu i updated it so looks like its all fixed now after restart
