### ISSUE TITLE
[BUG] Localized Crash

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#2045]
### Your Discord Name

jojosnmustard

### A clear and concise description of what the bug is

When driving a vehicle too close the left side of the front prison building it crashes everyone in the area.

### Steps to Reproduce the Bug

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/29337315/82607c90-dad3-41b7-a07c-8cdd5de3157a)
then get 
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/29337315/daff54d6-c3ef-40a0-926e-6f1f63b5621d)

### Expected Behavior

Not crash.

### Screenshots/Videos

See above.

### Extra Notes (Optional)

It happened with a Patriot Sport, and Issi Sport. Attempts were made to respawn the vehicles after they poofed, led to a crash. Gettin in to an existing vehicle there also causes a crash.

**Comment by HealedDegree** [comment]
it occurs even in the vistior area dont need to be driving for it to occur

**Comment by Bac0nRamen** [comment]
Next restart
