### ISSUE TITLE
[BUG] Can not enter Madrazo Tower Offices

### ISSUE THREAD

**Issue by nrmoser1992** [ParadoxGamingRP/bugs-and-suggestions#2046]
### Your Discord Name

mr._.crane

### A clear and concise description of what the bug is

I have tried to enter the office a few times this week and each time it lets me look at the business directory but go no further than that when I click any of the offices, including my own. 

### Steps to Reproduce the Bug

1. Walk up to the ped at Madrazo Tower (Any of the three,)
2. Third Eye and click the ped.
3. Select an office you wish to enter and click it. Then it will go no further.

### Expected Behavior

When you go to the ped at the offices and speak with him, I wish to be able to enter the office of my choosing.

### Screenshots/Videos

![officebug3](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/147278303/e1c13711-1ee1-4a0c-9375-57a39f63570d)

**Comment by xXJamieXx** [comment]
Works fine for me.
