### ISSUE TITLE
[BUG] Coral not spawning

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#2048]
### Your Discord Name

jojosnmustard

### A clear and concise description of what the bug is

As of today's 1/10/24 update, the coral is not spawning at all now.

### Steps to Reproduce the Bug

Get Job
Use Thing
Find Location
No Coral

### Expected Behavior

Find Coral

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/29337315/dc1376d2-277d-4664-b77a-f1138dc6741a)

**Comment by Darahz** [comment]
Forgot to remove a bit when i re-did the spawning...

**Comment by Bac0nRamen** [comment]
next restart
