### ISSUE TITLE
[BUG] Coral Detector will not reveal location

### ISSUE THREAD

**Issue by Squeekyboi** [ParadoxGamingRP/bugs-and-suggestions#2051]
### Your Discord Name

Squeekyboi

### A clear and concise description of what the bug is

When you accept a job and use the scanner it no longer points towards where it is and only the beeping happens.

### Steps to Reproduce the Bug

1. take job
2. use detector
3. no location with beeping

### Expected Behavior

1. take job
2. use detector
3. get gps location on map with beep

### Screenshots/Videos

https://youtu.be/MQErBpybY6c

### Log File

[CitizenFX_log_2024-01-13T105925.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13927770/CitizenFX_log_2024-01-13T105925.log)

**Comment by Darahz** [comment]
Thats the way it's ment to be. You use the detector to find out where the corals are

**Comment by Squeekyboi** [comment]
> Thats the way it's ment to be. You use the detector to find out where the corals are

Ah ok fair enough just before it was showing them that's why I thought it was a bug 😆 sorry for false report
