### ISSUE TITLE
[BUG] Nos Issue on Drift Swap Karin Ariant

### ISSUE THREAD

**Issue by BigManBehavior** [ParadoxGamingRP/bugs-and-suggestions#2052]
### Your Discord Name

barelykaizen

### A clear and concise description of what the bug is

So since getting my Karin Ariant drift swapped, any time I press "X" it turns on a constant nos effect, while the car does not actually have nos installed. I heard the Sultan Classic Custom had a similar issue in the past and it was fixed.

### Steps to Reproduce the Bug

1. Buy Ariant
2. Drift swap Ariant
3. Press X
4. Nos go brrrrrrrrr

### Expected Behavior

I did not expect the car to have Nos at all.

### Screenshots/Videos

https://i.imgur.com/4YUDryK.png

**Comment by NickNubbz** [comment]
a similar bug was fixed on i think it was the jester classic.
