### ISSUE TITLE
[BUG] Eating the Chili, cannot access inventory afterward

### ISSUE THREAD

**Issue by RoseiiNaytool** [ParadoxGamingRP/bugs-and-suggestions#2053]
### Your Discord Name

Roseii

### A clear and concise description of what the bug is

When you eat the chili in the city it will error out, the action for eating will not stop, and when you do stop you cannot access your pockets

### Steps to Reproduce the Bug

1. eat the chili from glazed and glorious
2. try to access your pockets
3. gives error that you cannot access your pockets right now
4. You have to take a nap afterward to regain ability to get into your pockets again

### Expected Behavior

To be able to eat chili and be able to access your pockets afterward

### Screenshots/Videos

picture of F8: https://cdn.discordapp.com/attachments/1049113517749456998/1196185195372630076/image.png?ex=65b6b546&is=65a44046&hm=6033a99056a9f21f1aa8e681526e17e93941544b27ea8416c9c04e71c0eb96f0&

Picture from someone else from same issue: https://gyazo.com/0b3175de5f0ba040ee2b69803d6969cd

Video of issue: https://gyazo.com/0b3175de5f0ba040ee2b69803d6969cd

**Comment by natashajoan** [comment]
Ramen does it too, here's my F8. 
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/97318080/2c8f0be3-79e6-4786-a78a-d9ef6aed52f7)
