### ISSUE TITLE
[BUG] Colored headlight defaults to xenon after repair

### ISSUE THREAD

**Issue by NickNubbz** [ParadoxGamingRP/bugs-and-suggestions#2054]
### Your Discord Name

NickNubbz

### A clear and concise description of what the bug is

I have the colored headlights in a couple cars and every time i repair my car and put the engine back in the light color gets changed back to default meaning i need to use my light controller again to change it back. (light controllers only has 10 uses before it breaks and costs 10k) I know a few people this happens too but weirdly enough it does not happen to everybody. This is going to get pretty expensive and slowly drain my bank account especially racing in that car.

### Steps to Reproduce the Bug

get colored headlights/set any color
pull engine
install engine
be disappointed (unless you are one of the lucky ones)

### Expected Behavior

Headlights should stay whatever color you set it to even after a engine repair.

### Screenshots/Videos

NA

**Comment by BBstud44** [comment]
This happens with my Comet SR too
