### ISSUE TITLE
[BUG] Hunger and thirst not filling up

### ISSUE THREAD

**Issue by PatrykX904** [ParadoxGamingRP/bugs-and-suggestions#2058]
### Your Discord Name

corruptd3d

### A clear and concise description of what the bug is

Whenever I use drink/food it doesnt fill up in the bar

### Steps to Reproduce the Bug

1. Be hungry/thirsty
2. Eat/Drink
3. It doesnt update

### Expected Behavior

Be able to drink and eat 

### Screenshots/Videos

N/A

### Log File

[Food bug.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13968019/Food.bug.txt)

**Comment by kevstax** [comment]
me too as well
