### ISSUE TITLE
[BUG] Sandstorm liveries no longer work

### ISSUE THREAD

**Issue by Kromlec** [ParadoxGamingRP/bugs-and-suggestions#2060]
### Your Discord Name

Kromlec

### A clear and concise description of what the bug is

The sandstorm, sandstormxl and sandstormEV liveries are not loading in

### Steps to Reproduce the Bug

Have any of the sandstorm truck
Go to any shop and not find liveries

### Expected Behavior

Should be able to choose from the 20+ liveries

### Screenshots/Videos

N/a

### Extra Notes (Optional)

The sandstorm uses yft liveries instead of ytd liveries. The liveries were working before we made changes to the mod shop. When on dev server you can't even access the liveries through the Vmenu either. Will place the carcol file in vehicle-files for easy access.

**Comment by Jacob017483** [comment]
I am having the same problem with my rh7 
![b2b17543-0017-4531-a013-f86339f28015](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/157089474/ec1849ec-133a-4fac-81a2-f092bb434418)
![b2b17543-0017-4531-a013-f86339f28015](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/157089474/508936c9-09a1-4bc5-9eba-87855c0a2d3b)
