### ISSUE TITLE
[BUG] Unable to sell boat to another player 

### ISSUE THREAD

**Issue by SpiceF0x** [ParadoxGamingRP/bugs-and-suggestions#2063]
### Your Discord Name

spicedf0x

### A clear and concise description of what the bug is

I attempted to sell a boat to another citizen using

transfervehicle ID amount

but it said there was no one nearby, they even hopped into the boat with me. No f8 errors. 

Cars & Air vehicles can be sold / transferred

### Steps to Reproduce the Bug

1. Get in boat
2. Attempt to sell / transfer boat
3. Get 'The person isn't near enough' pop up in right hand side

### Expected Behavior

To recognise I'm trying to sell to someone next to me :)

### Screenshots/Videos

n/a

### Log File

[CitizenFX_log_2024-01-19T194448.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/13994500/CitizenFX_log_2024-01-19T194448.log)

**Comment by Darahz** [comment]
So i tried this and i was able to transfer the boat. Is there a specific boat your tried to do it with?

**Comment by SpiceF0x** [comment]
Yeah it was the expensive sail boat, in the end I transferred it at 0 and it worked as gifted and we bank transferred the money. But it definitely didn't work with a monetary input.

**Comment by xXJamieXx** [comment]
Weird oddity with boats, if you're having issues get them to sit in as a passenger and it should work. :)
