### ISSUE TITLE
[BUG] Personal storage/pockets | Yellow Jack Casino Storage causing pocket Break

### ISSUE THREAD

**Issue by RoseiiNaytool** [ParadoxGamingRP/bugs-and-suggestions#2065]
### Your Discord Name

Roseii

### A clear and concise description of what the bug is

Contrary to the video that I am going to post in here it is about the Yellow Jack casino, mostly because it seems to break my pockets when I take a couple items out, put some back in, and then try to take the items and put them in my pocket again. 

### Steps to Reproduce the Bug

1. Open Yellow Jack Casino Storage
2. Take Items out/put in storage
3. Try to put somethin back into your pockets a few times
4. Gives error "Target Inventory cannot hold that much"
5. From that time on rather you are in the casino or not, you cannot put anything into your pockets
6. Take a hard nap to be able to add items to invenory

### Expected Behavior

To be able to take items out of your pocket and put it in Yellow Jack Storage, then put items into your pockets. This only seems to be happening WITH the Yellow Jack Storage that causes the error. I tried doing the same thing with other properties as well as trunk storage and didn't have an issue. 

### Screenshots/Videos

Video: https://medal.tv/games/gta-v/clips/1Qe3dG5q4q_oKb/d1337o9XZKvl?invite=cr-MSxzSDcsMzY4OTU4NzQs Made before I realized it was the Yellow Jack causing the issue. 

Picture 1: https://cdn.discordapp.com/attachments/1077730778856833105/1198016969073512508/image.png?ex=65bd5f3f&is=65aaea3f&hm=f3f82b65971fea5f5ba27c6bee858741ad077a0a8ffd3e99d67bb1c55f7d8436&

Picture 2: (This isn't showing an error but it says NONE constantly, I wanted to give it to you just in case.) https://cdn.discordapp.com/attachments/1077730778856833105/1198017051688697967/image.png?ex=65bd5f53&is=65aaea53&hm=b1f550270fa81db2ef9e385c82cb71157fdd3f4a208eb41c2cc9fafbfa82c0f2&

Picture 3: https://cdn.discordapp.com/attachments/1077730778856833105/1198017082994983063/image.png?ex=65bd5f5a&is=65aaea5a&hm=2453409c50390df0ea16e8f3e951581eea06dbe03d6cec37d76e8bb0b58129e6&

### Extra Notes (Optional)

To be able to move items in and out of casino storage without it breaking my personal pockets in 5 moves.

**Comment by shleeyy** [comment]
im having the same issue with pulling things in and out of EMS locker after shift.

https://medal.tv/games/gta-v/clips/1R073Rg4EovYBS/d1337k4FnOxt?invite=cr-MSxoYnosMTg5NzA2MzQwLA
