### ISSUE TITLE
[BUG] Veto GoKart

### ISSUE THREAD

**Issue by JHAWKS73** [ParadoxGamingRP/bugs-and-suggestions#2066]
### Your Discord Name

Jhawks73.

### A clear and concise description of what the bug is

I fully Benny's and turboed the Veto go-kart and it didn't go any faster then what it did with out the upgrades

### Steps to Reproduce the Bug

Buy go-kart
Buy Benny's and turbo upgrades 
Upgrades not doing anything 

### Expected Behavior

It to gain some sort of better performance out of it

### Screenshots/Videos

N/A

**Comment by Kromlec** [comment]
Performance upgrades go off a % of what the base is, it doesn't always have noticeable increases.
