### ISSUE TITLE
RH7 struggles to pass 120mph [ENHANCEMENT] 

### ISSUE THREAD

**Issue by HealedDegree** [ParadoxGamingRP/bugs-and-suggestions#2067]
**Your Discord Name**
HealedDegree

**Describe the annoyance**
RH7 doesnt seem to be reaching max speed anymore. for 125k car should be reaching 130+

**To Reproduce**
[Steps to reproduce the annoyance]
1. Buy RH7 
2. fully upgrade bennys with turbo as well
3. Drive, reaches around 120

**Requested behavior**
reache a speed of over or equal to 130

**Comment by Kromlec** [comment]
tweeks made.
