### ISSUE TITLE
Tube Kart curb stomping [ENHANCEMENT]

### ISSUE THREAD

**Issue by HealedDegree** [ParadoxGamingRP/bugs-and-suggestions#2068]
**Your Discord Name**
HealedDegree

**Describe the annoyance**
Tube Kart randomly dislikes curbs even on stock suspension. 

**To Reproduce**
[Steps to reproduce the annoyance]
1. Buy tube kart
2. Drive around
3. Attempt to go over a median or sidewalk
4. Depending on angle, Kart will smash into the curb damaging the engine overtime the more it occurs. 

**Requested behavior**
Clear sidewalks and medians with ease 

with spoiler and diffuser
https://medal.tv/games/gta-v/clips/1KmfuTewfG6SkK/d13370gv4IVC?invite=cr-MSw3bFYsMjA5MzA5MTQ0LA

without spoiler and diffuser
https://medal.tv/games/gta-v/clips/1QfN03hqof6wA6/d1337cci4918?invite=cr-MSxVWTUsMjA5MzA5MTQ0LA

**Comment by Kromlec** [comment]
fixed.
