### ISSUE TITLE
[BUG] Locals on AI calls for EMS t-pose once succesfully revived also not being paid upon completion. 

### ISSUE THREAD

**Issue by natashajoan** [ParadoxGamingRP/bugs-and-suggestions#2069]
### Your Discord Name

its_ahsatan

### A clear and concise description of what the bug is

When you show up to the AI calls, once you try to pick the local up to their feet, if you happen to get it to where they can be resuscitated, if you manage to save them, they are stuck in the air in the T-Pose position. This happens every time they are successfully revived. 

Payments also aren't being received once the call is completed. 

### Steps to Reproduce the Bug

1. Be clocked on EMS
2. Receive a local call
3. Go to the call, treat pt attempt to revive them 
4. Once successful, hear the local thank you, but they're stuck 2 feet in the air t-posing. 
5. Once job is completed, notice you don't receive the payment for it. 

### Expected Behavior

1. Once successfully revived the local, for them to not be t-posing and for them to walk off as normal. 

### Screenshots/Videos

https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/97318080/fd3e029b-f674-493d-81f4-637938b66726

**Comment by xXJamieXx** [comment]
Works for me? 

https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/11248045/b1474d8e-0207-427b-ba25-851e4758264b
