### ISSUE TITLE
[ENHANCEMENT] new engine sounds volume

### ISSUE THREAD

**Issue by kevstax** [ParadoxGamingRP/bugs-and-suggestions#2074]
The Mazda 20B, Nissan GTR VR38, Aston Martin V12 , Dodge Viper & the Chevy LT4 could use a bit of a sound increase they are a bit too quiet for an engine swap. Other than that they are all amazing new sounds!

**Comment by Bac0nRamen** [comment]
I made some adjustments a little bit let me know
