### ISSUE TITLE
[ENHANCEMENT] Camera shake when driving and running

### ISSUE THREAD

**Issue by RoguIsAwesome** [ParadoxGamingRP/bugs-and-suggestions#2077]
**Your Discord Name**
rogue_69

**Describe the annoyance**
Camera shakes every time you're driving fast and when you're jogging/running. My Camera Shake is also turned off in the fivem options. There was no camera shake before the restart.

**To Reproduce**
[Steps to reproduce the annoyance]
1. Get in car
2. Go 80+ in car 
3.  Screen starts to shake

**Requested behavior**
I want the camera shake to be gone

**Comment by xXJamieXx** [comment]
FiveM bug. Make sure the option is turned on in FiveM settings and switch to Beta release channel for now.
