### ISSUE TITLE
[ENHANCEMENT] QOL - Annis S-230 Needs some love!

### ISSUE THREAD

**Issue by Vexxzo** [ParadoxGamingRP/bugs-and-suggestions#2079]
**Your Discord Name**

Vexxzo

**Describe the annoyance**

This car, the Annis S-230, is damn near undrivable. It feels like it is supposed to be a drift car outta the box and the car feels almost unrealistic with its handling. Would love to get this car again and drive it but it needs some love.

**To Reproduce**

N/A

**Requested behavior**

I believe this car should handle the same if not, at least very similar to the Annis Remus because they use the same chassis in real life as well. These two cars should be almost identical in performance or maybe even more power in the S-230 due to it having a better engine. If thats the case, maybe a slight increase in price would also be in order as well.

**Screenshots**

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/156739975/f2fe2728-b964-4f39-9076-64a5f61a19e2)

**Additional context**

https://en.wikipedia.org/wiki/Nissan_240SX

**Comment by Bac0nRamen** [comment]
Moved to vehicle team to do list
