### ISSUE TITLE
[BUG] Ns Tuning - Bikini Automotive - Tune up issue/bug

### ISSUE THREAD

**Issue by AndrewFlee** [ParadoxGamingRP/bugs-and-suggestions#2081]
### Your Discord Name

Worst Nightmare#5569

### A clear and concise description of what the bug is

Mechanical error in vehicles, might be a duplication bug found in the system, Tune up bug, Items not working, nos emptying without being used.

### Steps to Reproduce the Bug

1. Originally Ns Tuning helped me get the following Nos, Turbo and Racing Harness for my car but it fell out my car after adding it, weeks prier to having it, has fallen out of my engine
2. I found out about this issue from a good friend of mine, her name is called Kacey, she's a mechanic from bikini automotive, thought she was joking when she said it wasn't there, um, but everything sounded like it was there but it wasn't, after being notified, i took it to Ns Tuning and she was right, um Ns Tuning put it all back into the car, and issued a refund for themselves
3. I said fuck it and i took it back to bikini automotive and decided to take all 3 out of the car because it's being having issues and was gonna sell the arts for the car separately, but days later, the harness icon of the bottom left popped up again when i didn't install the stuff back, not sure with the issue with my Emperor Vectre but
4. There's also a bug where if you added nos to any other vehicle of yours your nos system icon will appear even though you don't have nos in this car or bike

### Expected Behavior

Was looking to getting my Nos and Racing Harness taking away from me and giving me a different one and through away the old copy, or giving me a refund for the items in the city, the turbo i'll keep and add to one of my bikes but if i have a issue with that too, id like to replace that item with the same item in my pocket just switching them out and see if that'll work, or just give me the cash back would be easier 

### Screenshots/Videos

![Screenshot 2024-02-01 233033](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/117454713/4e0c4a06-da5b-4ea3-a768-392c6bb51550)
![Screenshot 2024-02-01 233345](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/117454713/af13a765-7707-470f-a25b-8f62c4f96a37)

### Extra Notes (Optional)

Name in city: Andrew Flee

### Log File

[CitizenFX_log_2024-02-02T035938.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/14135022/CitizenFX_log_2024-02-02T035938.log)

**Comment by Skeletal-KC** [comment]
To clarify Andrew's issue:

1. His Nitrous, Turbo, and Harness disappeared
2. They were replaced
3. We removed them from his car so he could put them in something else
4. The Harness System still appeared to be in the car and functional the following day despite removal
5. Not sure if the physical harness itself is still in the car, or if the car is simply not unflagging the code for harness when it's uninstalled from a vehicle
