### ISSUE TITLE
[BUG] Aleution Headlights messed up

### ISSUE THREAD

**Issue by shleeyy** [ParadoxGamingRP/bugs-and-suggestions#2082]
### Your Discord Name

freckles4

### A clear and concise description of what the bug is

Bought a new car after the release and the headlight on the passenger side is messed up as well as the light bar. 

### Steps to Reproduce the Bug

Get in Vapid Aleution
Turn on headlights
Headlights don't match, one looks like film is on it
Hit high beams, same thing with light bar.

### Expected Behavior

Get in Aleution
Turn on lights
All lights match

### Screenshots/Videos

https://cdn.discordapp.com/attachments/1160904582789079091/1203226206590214175/image.png?ex=65d052ba&is=65bdddba&hm=820838ba543d3adb8b13e07c9869d089f41abc83683cdb252adc8eafbaca13e1&

**Comment by lPrestonl** [comment]
Pushed a fix to this, should be good after today's restart. Headlights are fixed and good as new!
