### ISSUE TITLE
[BUG] LOD on New Dominator is Trash

### ISSUE THREAD

**Issue by Drunkle716** [ParadoxGamingRP/bugs-and-suggestions#2084]
### Your Discord Name

MainCharacter716

### A clear and concise description of what the bug is

Wheels on Dominator9 fall off way too early

### Steps to Reproduce the Bug

Look at the new dominator from across a parking lot

### Expected Behavior

Wheels stay on

### Screenshots/Videos

![FiveM_b3095_GTAProcess_lkjT4caCSz](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/100391224/c58a7d55-16a8-4bfe-be91-8a57d2f09ab0)
![FiveM_b3095_GTAProcess_8usQ69fjxq](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/100391224/60f55f66-9571-4942-9032-5810dce971c8)

**Comment by Skeletal-KC** [comment]
Might be the LOD for the wheels not the Dominator itself if those are the modded widebody wheels, some of the modded in wheels have really poor LODS from a distance compared to vanilla wheels

**Comment by Kromlec** [comment]
fixed
