### ISSUE TITLE
[BUG] Registers not accessible

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#2092]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

Register won't open the order drawer. Extra item doesn't save the pay.

### Steps to Reproduce the Bug

1. Clock onto work
2. Open order Drawer.
3. Add Extra Item

### Expected Behavior

Drawer opens for Sales.

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/98053772/b85490c2-e718-47d3-ba18-50abf6f9920a)

**Comment by Bac0nRamen** [comment]
Should be fixed
