### ISSUE TITLE
[ENHANCEMENT] Coral tweaks

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#2093]
**Your Discord Name**
jojosnmustard

**Describe the annoyance**
Coral was in a good spot from an end-user POV, no markers ok, no gps, ok, anxiety inducing beeping sound, ok. But once it was required that you have to be on a boat to use the device, it killed the will to continue doing it for multiple reasons.

When you get the job you have to go up to Paleto or down to the marina to get your own watercraft. Obviously the shorter path there is Paleto, so you've got your watercraft now. Activate the device, then you've got an almost completely unhelpful beeping sound once every 5-8 seconds to use as your only tool in deciding which side of the island to travel down when you're sitting at the top middle of the map. So you have to boat all the way around the state trying to figure out where the beeps are coming from; you find the coral (but your anchor doesn't work so you have to surface every 10 seconds so your boat doesn't float away); time to take the boat back to Paleto. Now you have to respawn your vehicle and drive back to the guy to turn in the job for 2-4k(ish) because he's in a very awkward spot that's not accessible by boat. Then repeat the whole process.

You might be thinking: "Why not just steal a boat.." well, there's no good access. even if you went to the closest location to steal a boat since you're a criminal doing criminal things. You've now got to leave your vehicle there after alerting the cops, travel down dangerous rapids, hope you don't get stranded, then figure out if you have to travel all the way around the state or not to chase the beeps, then try to find your way back up the rapids after it's all done to get back to your vehicle. Unless you just murder a local and take their car when you're done with the boat, but who's out here murdering people for coral??

It's very inaccessible at the moment. I understand the boating thing, it makes sense that divers would be on a boat. But people also dive from beaches all the time to view coral reefs. I'll list a handful of possible solutions to try and get coraling back on track, if we could get a couple of these implemented that would make it an activity that is much more enjoyable.

1: Move the guy to a more boat accessible location.

2: Add public boat parking (with nearby public access vehicle parking preferably) to the east and west sides of the map probably around Chumash and the Lighthouse areas.

3: Add the markers back to the device and remove the horrible beeping sound, so we don't have to guess which side of the state to travel down. Or if the sound was directional in the sense of "louder relative to the direction you're looking" you'd at least know which direction to travel.

4: Remove the requirement of having to be on a boat to find coral.

5: Keep all the coral jobs on one side of the map to eliminate the 50/50 chance you're on the wrong side.

**Comment by xXJamieXx** [comment]
@emeraldleo1982 I'll let Golf look at this since its his script but I'm personally interested in the following line:
`but your anchor doesn't work so you have to surface every 10 seconds so your boat doesn't float away`
What do you mean by this because I've just used an anchor and the boat is stationary?

**Comment by emeraldleo1982** [comment]
@xXJamieXx I don't know why, some people say anchors work fine, but they're never available for me.

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/29337315/2dfd4e9e-2dbf-4f39-a311-bc567953b4fe)

And there's no notifications or errors in my log. After doing a little testing it seems to be specific to the Dinghy 2 seater model. Not sure if other boats are affected as I only own a 2 seater and a seashark, but the seashark anchor works.

**Comment by Darahz** [comment]
So the script was made so you needed a boat so you wouldn't just drive to a location with a car. So the boat thing will stay. But i can change up the detector to behave differently.

**Comment by emeraldleo1982** [comment]
I feel like the main drawback of those I mentioned is the job givers proximity to open water access. Needing a boat is fine, but where the guy is located at the moment makes it a major headache to go back and forth to a boat then back across the state, then back up, then back to the guy. 

It's appreciated that you're even willing to look in to it :)
