### ISSUE TITLE
[BUG] Crashing near Yellowjack

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#2097]
### Your Discord Name

jojosnmustard

### A clear and concise description of what the bug is

If I drive in the area between Yellowjack and the Harmony on/off ramp, I get a specific crash. Tried clearing my cache and redownloading everything, same crash. Doesn't seem to be affecting other people so not sure.

### Steps to Reproduce the Bug

1: Exist between Yellowjack and harmony on/off ramp area
2: brain explodes

### Expected Behavior

brain not explodes?

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/29337315/e7493066-7e18-484d-97cb-1216eadac724)

### Extra Notes (Optional)

If you check the tail of the logfile there's a couple of physics validation and vertex errors right before the crash report.

### Log File

[CitizenFX_log_2024-02-10T224006.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/14230763/CitizenFX_log_2024-02-10T224006.log)

**Comment by emeraldleo1982** [comment]
[CitizenFX_log_2024-02-10T223308.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/14230768/CitizenFX_log_2024-02-10T223308.log)

and
[CitizenFX_log_2024-02-10T223037.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/14230769/CitizenFX_log_2024-02-10T223037.log)


More examples of crashing in that area.

**Comment by Bac0nRamen** [comment]
I will need more info on this. The problem is the file that is causing ur crash is an unedited vanilla file

**Comment by xXJamieXx** [comment]
@emeraldleo1982 Have you attempted to verify your GTA 5 game files to make sure your game is up to date/not missing any files?

**Comment by emeraldleo1982** [comment]
Forgot all about this bug report sorry. It hasn't happened since that day, the next day I flew in it was fine. I didn't try verifying my vanilla files since they've never been touched but it worked itself out I guess, which is even more confusing that it would randomly have issues, then be fine, which also seems to happen sometimes when I'm racing where I'll just randomly fall through the world on repeat, even after napping, clearing cache etc, but the next day it's fine. Apparently it's something on my end though.
