### ISSUE TITLE
[ENHANCEMENT] Vulcar Hachura R Custom - Tune up

### ISSUE THREAD

**Issue by Vexxzo** [ParadoxGamingRP/bugs-and-suggestions#2098]
**Your Discord Name**
Vexxzo

**Describe the annoyance**
This car costs $90,000 dollars at Kildares. $100,000 is sticker price at the local dealer ship. This car struggles to go over 100 mph while stock and barely goes 110 fully upgraded.

**To Reproduce**
N/A

**Requested behavior**
For a car that costs $100,000 I expect it to at least hit 136. The car is WAY too slow and needs to be tuned up heavily. It handles great, just has absolutely no resemblance of speed.

**Screenshots**
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/156739975/39de6d7f-d901-4355-ae92-aae4749144b2)

**Additional context**
N/A

**Comment by Kromlec** [comment]
added this to the vehicle team to do list.

**Comment by Kromlec** [comment]
Slight adjustment made
