### ISSUE TITLE
[ENHANCEMENT] Annis ZR-150 - Tune Up

### ISSUE THREAD

**Issue by Vexxzo** [ParadoxGamingRP/bugs-and-suggestions#2099]
**Your Discord Name**
Vexxzo

**Describe the annoyance**
This vehicle drives much like it has a default drift handling out of the box and just makes the car undrivable in a normal fashion. It handles much like the S-230 currently does and doesn't feel realistic.

**To Reproduce**
N/A

**Requested behavior**
Change the handling to a more stiffer and proper driving physics. I believe the handling for this car should be more similar to how the ZR-350 or the ZR-250 handles. 

**Screenshots**
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/156739975/4e644dac-1355-473b-8173-b3b56582615a)

**Additional context**
N/A

**Comment by Kromlec** [comment]
will look into fixing suspension

**Comment by Kromlec** [comment]
adjustments made
