### ISSUE TITLE
[ENHANCEMENT] Comet S2 - Tune up

### ISSUE THREAD

**Issue by Vexxzo** [ParadoxGamingRP/bugs-and-suggestions#2100]
**Your Discord Name**
Vexxzo

**Describe the annoyance**
The comet S2 costs around $150,000 but doesn't handle that way. It has a pretty good top end but not only does it take a long time to reach that, it has a lot of bounce issues with its handling along with it spinning out super easily. The Comet SR is better handling and over bumps is faster then the S2 for a fraction of the cost. The same can be said about the Growler. The Growler is just a better S2 for a fraction of the price. 

**To Reproduce**
N/A

**Requested behavior**
Make the handling on the S2 be more in line with a performance car of its standing. I believe the growler or the SR handling would be much more accurate for the S2.

**Screenshots**
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/156739975/17d63bda-9fc2-4221-b788-ae58c2c203a8)

**Additional context**
N/A

**Comment by Kromlec** [comment]
I will look at adjusting price but all the cars you are placing reports for were down graded for a reason.

**Comment by Vexxzo** [comment]
@Kromlec I understand some of these have been tuned down for a specific reason but the point I'm bringing up is I think a lot of them were tuned down TOO much. All of the reports I'm bringing up are a collective of some opinions from other people in the server, not just mine alone. Thanks for taking the time to read and look into them!

**Comment by Kromlec** [comment]
The problem we are having is people aren't making these reports for those "meta" cars, you only make reports after they have been found out and detuned, that doesn't help us keep the cars more balanced across the board.

**Comment by Vexxzo** [comment]
I don't understand why the 'meta' cars are getting tuned down so hard. I believe a lot of the 'meta' cars feel good in terms of where they are for their price points. I think other cars should be brought up slightly to meet them. Why tune them down? Is it easier or? Just trying to understand your prospective.

**Comment by emeraldleo1982** [comment]
The META cars are META for a reason, they're good, and most importantly actually fun to drive. For what it's worth I agree that we need less cars tuned down to oblivion, and more that are brought up so we can defeat the META, if there's lots of tuned up cars people can use varied stuff. 

Detuning cars only strengthens the meta by leaving 1 or 2 that are obviously better than the rest no matter how many you detune there's always going to be some that are better, but if all the cars are good feeling, people will look past what's the absolute best more often.

I don't feel like lowering the price is going to do anything except upset the people that already spent lots of money on cars and now lose that value in addition to the car feeling like grandmas rusted out beater now.

**Comment by HealedDegree** [comment]
I agree with Vexx and Emerald. Plus we've been told to make reports on cars that we think need to be tuned up (which vexxzo has been tasked with as you can tell lol) bringing the META cars down would just get rid of seeing some of these nice cars in the scene, which are also expensive. The META cars should be left as is and try to bring all the other cars up so we can see more variety in the scene yk?

**Comment by Kromlec** [comment]
small adjustments made
