### ISSUE TITLE
[ENHANCEMENT] Annis ZR-390 - Tune up

### ISSUE THREAD

**Issue by Vexxzo** [ParadoxGamingRP/bugs-and-suggestions#2101]
**Your Discord Name**
Vexxzo

**Describe the annoyance**
The ZR-390 used to be a really good car, maybe one of the best cars for racing at the time of its release. Its price point now sits just below $70,000 it has under taken a pretty big nerf. I believe where the car sits now is too low for the price point and needs some attention.

**Steps to reproduce**
N/A

**Requested behavior**
The handling and acceleration is good, it just needs a little bit more on the top end to keep it competing with cars in the same price range. Maybe a top speed similar to the RH7 would fit it more nicely. 

**Screenshots**
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/156739975/641c6a00-3dcf-4cf6-b20a-a4e8a91cfc00)

**Additional context**
N/A

**Comment by Kromlec** [comment]
Will look at adjusting price.

**Comment by Kromlec** [comment]
adjustments made
