### ISSUE TITLE
[ENHANCEMENT] Jester RR & Jester GPR - Tune up

### ISSUE THREAD

**Issue by Vexxzo** [ParadoxGamingRP/bugs-and-suggestions#2102]
**Your Discord Name**
Vexxzo

**Describe the annoyance**
Both the Jester RR and the Jester GPR need some love in terms of performance. The Jester GPR got nerfed into the ground. Yes it used to be super fast and maybe just a little too fast but now its too slow to even use during races and can't keep up with other cars in its price range. The Jester RR is the base car and it performs even worse and feels really weird when cornering. I cant quite put my finger on the reason though.

**To Reproduce**
N/A

**Requested behavior**
The GPR needs more speed to bring it up closer to what it used to be. The Jester RR needs some attention to make it feel better while driving and giving it a little more speed to make it compete and have more people using it. 

**Screenshots**
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/156739975/025532fa-63dd-4c54-9af9-1ee650baa25b)

**Additional context**
N/A

**Comment by Kromlec** [comment]
Will look into the GPR the RR might take longer as its not an addon car.

**Comment by Kromlec** [comment]
adjustments made
