### ISSUE TITLE
[BUG] for the bike Dinka TT-750

### ISSUE THREAD

**Issue by hacklv** [ParadoxGamingRP/bugs-and-suggestions#2106]
### Your Discord Name

gvido_b

### A clear and concise description of what the bug is

the first thing that i noticed the bike showed up next to car section in the phone app then i test drove it i felt the weird steering  while i was leaning and driving while holding shift to accelerate it kept driving to the side ewn thou iw stopped the turning motion then i popped the front wheel and i saw the top speed go from 111 to 136 and holding that speed and that was after i bought the bike after that i went to take the payslip and  when i went to unlock my bike i couldn't and i saw i can only unlock the bike from the back then while trying to unlock the bike i kinda went thrue the bike like it wasn't there but it glitched my character out 

### Steps to Reproduce the Bug

1 buy the bike 
2 pop the front tier up and goo 136
3 turn while holding shift let go of the shift and it will keep turning for a bit 
4 get of the bike and its possible to walk thrue it at some parts of the bike 

### Expected Behavior

i expected for the bike to be allot slower to turn the same way just not whit the leaning glitch the top speed was like an super car 136 whit wheele but for a old looking bike its not right  the when i turned it turns but some times after youw stopped leaning it still dose the turning motion 

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/1UWpDCdS-hqBlY/d1337olNwh6D?invite=cr-MSxWTFMsMTk3MzM3MDg3LA

https://medal.tv/games/gta-v/clips/1UWqfW9w9JRAXM/d1337KvIRFCO?invite=cr-MSxIVWksMTk3MzM3MDg3LA

https://medal.tv/games/gta-v/clips/1UWqHn1pK6zMPQ/d1337dvLvVNH?invite=cr-MSxpRTcsMTk3MzM3MDg3LA

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/149176636/dadb2aa5-fdbe-4f45-9b69-cadeef1fb2e7)

### Extra Notes (Optional)

this is nothing about this bug but some add ones to some other stuff the Sultan RS V8 not is completely bad id make it faster because fully upgraded 110 i don't think is the best speed for 103k car + id wanna remind of the livery for the 9F and the 10F that iw sent in couple months ago

**Comment by lPrestonl** [comment]
Handling Adjusted ✅
Phasing through model Fixed ✅
Showing Up Under Bikes ✅
