### ISSUE TITLE
[BUG] Boost XP

### ISSUE THREAD

**Issue by tbbubz** [ParadoxGamingRP/bugs-and-suggestions#2107]
### Your Discord Name

tbbubz

### A clear and concise description of what the bug is

When boosting the XP does not add up just only replaces with the amount that you get from the boost you do , so there is no way to really gain XP to move to the next level!

### Steps to Reproduce the Bug

1. GET BOOST CONTRACT
2. break into garage and lock pick vehicle
3. complete hacks and run from the weewoos
4. drop off vehicle 
5. XP gain just replaces current amount that you had before the boost

### Expected Behavior

1. GET BOOST CONTRACT
2. break into garage and lock pick vehicle
3. complete hacks and run from the weewoos
4. drop off vehicle
5.  XP gained from successful boost is added to current XP 

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/154731897/7903b306-1857-40be-9aab-9a5795db5bf9)

I have been boosting since the new hack and stuff have come out and before the XP leveling was added definitely should have more than 48 XP

**Comment by jkaejkae888** [comment]
I found from doing many boosts now that taking a contract will cost you 25xp which is completely fine the issue is sometimes you don't even get 25xp as a reward there's been boost when I've only gotten less than 20xp so in total you loose experience for completing a boost.
