### ISSUE TITLE
[BUG] Crashes being caused by something in the area of Glizzys 

### ISSUE THREAD

**Issue by Rac-coder** [ParadoxGamingRP/bugs-and-suggestions#2109]
### Your Discord Name

super raccoon

### A clear and concise description of what the bug is

I crashed going past glizzys and am now stuck in an infinite loop of crashes in that area. 

### Steps to Reproduce the Bug

1. go past glizzys on hawick
2. crash
3. get stuck in loop of crashes

### Expected Behavior

not crash 😔

### Screenshots/Videos

canny get due to the fact it happens so fast but the crash message is just the usual headpop message. 

### Log File

[CitizenFX_log_2024-02-13T232130.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/14273332/CitizenFX_log_2024-02-13T232130.log)

**Comment by Bac0nRamen** [comment]
Going to close this as no other reports have been made. And have no other info to go off of
