### ISSUE TITLE
[BUG] Went down and got frozen

### ISSUE THREAD

**Issue by Martyfly200** [ParadoxGamingRP/bugs-and-suggestions#2110]
### Your Discord Name

Martyfly2005

### A clear and concise description of what the bug is

I was riding a bike and got launched off and hit the dirt it said I was dead as the heart circle was completely red. the usual menu for ems wasnt there either there was no ems at the time. earlier I went down and the menu was there and I was fine.

### Steps to Reproduce the Bug

1. flung of a bike/Motorcycle
2. red circle shows dead but not actually dead.
3. No menu to call ems or get airlifted. 

### Expected Behavior

see the ems menu as soon as I went down.

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/116933716/fca86c0d-f13d-45e0-abcf-7577f3a4adb1)

**Comment by xXJamieXx** [comment]
No log file so unable to see if any errors occurred.
