### ISSUE TITLE
[BUG] Clothing @ Billy's in prison 

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#2113]
### Your Discord Name

ssara

### A clear and concise description of what the bug is

Billy has the option to put on a "Comfy" outfit. As you can see, this is not it, my guys. It's just not it. 

### Steps to Reproduce the Bug

Go up to Billy
Third eye and chose prisoner cclothes
Look FAB AF but in wrong clothes

### Expected Behavior

Wear the right clothes

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/98127638/75cb1f65-8889-408d-a620-91e02ab1e88b)
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/98127638/4107a9ea-5503-4353-aab0-1725643f00d7)

**Comment by Drunkle716** [comment]
Should be fixed at restart.
