### ISSUE TITLE
[BUG] Car Chopping doesn't allow to Chop

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#2114]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

Was trying to chop a car, and the car doesn't have those parts.

### Steps to Reproduce the Bug

1. Get car chop mission
2. Get Car
3. Bring car to chop
4. Try to chop

### Expected Behavior

Being able to chop the parts and turn them in.

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/98053772/3b9ae55b-4e88-4670-b24f-f49b04074b37)

**Comment by tusktheshrew** [comment]
Feedback: Multiple cars in the same area, had to lockpick all of them to find the right car.

**Comment by xXJamieXx** [comment]
> Feedback: Multiple cars in the same area, had to lockpick all of them to find the right car.

The email tells you what car to find, you mean theres multiple of that same model?

**Comment by tusktheshrew** [comment]
Yes there was multiple of the same model car in the area. I went thorugh an entire adv lockpick to find the right one.
