### ISSUE TITLE
[BUG] lock on radio

### ISSUE THREAD

**Issue by Terrylaughlin35** [ParadoxGamingRP/bugs-and-suggestions#2121]
### Your Discord Name

imtwobigdawg35#3143

### A clear and concise description of what the bug is

When you try to lock onto another officers radio it will say its looking for lock but it will not catch anything. 

### Steps to Reproduce the Bug

1. Have an officer talk
2. try to lock on with your keybind (mine being "Y")
3. says "Looking for lock on
4. never gets lock

### Expected Behavior

for it to get lock and track me to the officer

### Screenshots/Videos

N/A

### Log File

[logs.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/14319873/logs.txt)

**Comment by JnKTechstuff** [comment]
@xXJamieXx This functionality needs to be added back to the current new radios

**Comment by xXJamieXx** [comment]
I've seen cops using it since the new radios so unsure

**Comment by Terrylaughlin35** [comment]
seems to work and not work at times
