### ISSUE TITLE
[BUG] Changing clothes killing you

### ISSUE THREAD

**Issue by Flawlessdx** [ParadoxGamingRP/bugs-and-suggestions#2128]
### Your Discord Name

seaside8703

### A clear and concise description of what the bug is

So when you are changing cloths sometimes it can trigger the suicide command that the server has and there is nothing you can do about it. Don't really know what is triggering this to be honest with you

### Steps to Reproduce the Bug

I'm not sure what input i can give on this since i guess it's more a coding thing

### Expected Behavior

Hopefully i dont have to die when i change my cloths again this is not happening everytime

### Screenshots/Videos

Dont have any

**Comment by Kromlec** [comment]
A clip would be very helpful in the devs seeing what is causing this, or at a minimum your logs. If you need help obtaining your logs create a support ticket and the mods can help you with that.
