### ISSUE TITLE
[BUG] Chop-shop

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#2136]
### Your Discord Name

ssara

### A clear and concise description of what the bug is

Tried to drop off the car at the location, but after i was able to press E, nothing happened. Medal didn't work either so I got no clip of it. It gave me a black screen as it was sending me trough, then I was back at the same location and the car was turned around.

### Steps to Reproduce the Bug

Get a car
Go to drop off location
Can't enter drop off location

### Expected Behavior

Be able to drop off car

### Screenshots/Videos

N/A

### Log File

[chopp.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/14410170/chopp.txt)

**Comment by emeraldleo1982** [comment]
Chop shop teleport not working still. Pressing E at the door just blanks the screen for a second and spits me back outside in the car.
