### ISSUE TITLE
[BUG] Registers not working

### ISSUE THREAD

**Issue by PatrykX904** [ParadoxGamingRP/bugs-and-suggestions#2137]
### Your Discord Name

corruptd3d

### A clear and concise description of what the bug is

So when I was repairing cars at NS I tried to put the pricing into the register and the menu was multiplied like 3 times or something and it didnt show the order on neither on the "pay order" section

### Steps to Reproduce the Bug

1. Try put something in register / add extra item
2. Press Confirm if adding extra item
3. Pricing doesn't show up

### Expected Behavior

Pricing to show up and being able to swipe card

### Screenshots/Videos

NA

### Log File

[Register BUG.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/14410324/Register.BUG.txt)

**Comment by lPrestonl** [comment]
Fixed and Live in server.
