### ISSUE TITLE
[BUG] Benny's Menu New Issue/Missing Features After Previous Fix

### ISSUE THREAD

**Issue by Skeletal-KC** [ParadoxGamingRP/bugs-and-suggestions#2140]
### Your Discord Name

skeletal_kc

### A clear and concise description of what the bug is

Stock Wheels and Custom Tires are now available in Benny's however they now display in weird ways, and have pushed the menu out of order (names and things no longer correspond to the correct item) and the Custom Tires, while now being there have a very tricky way of getting them to work (hovering over the first custom tire option, but not the second, and then backspacing out the menu applies them, but hitting enter will apply the tires but also a set of the wrong wheels)

Dashboard/Accent colors were said to have been added in the fix but seem to still be messing in the live menu

And adding neon to a car will now automatically force a random color instead of where previously you could select a color before purchasing neon

### Steps to Reproduce the Bug

1. Enter Benny's
2. Look at the Benny's Menu
3. Have an OCD related aneurysm

### Expected Behavior

N/A

### Screenshots/Videos

![1](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/122247151/a0b8f6dc-adad-45a6-929f-9b91e83c2f26)
![2](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/122247151/df15195e-8445-418b-af60-46c39fa286f9)
![3](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/122247151/8f4b8d2e-cccb-4287-8944-b632e2f2bc48)
![4](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/122247151/02906cd8-7b6f-46c9-b008-214433166a19)

**Comment by lPrestonl** [comment]
@Skeletal-KC Dashboard Colors had not been pushed yet to Live Server until today. They are now there and usable.
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/35425544/2b6c7d0f-65e6-44b9-b391-f8698459f186)

The other issues, I won't comment on, not my area. 👍
