### ISSUE TITLE
[BUG] Airlift putting me in prison

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#2143]
### Your Discord Name

jojosnmustard

### A clear and concise description of what the bug is

Needed to call an airlift from the local EMS, they decided the best place to put me was in prison, which is fair cause I've been there enough it's probably listed as my home address. Upon checking out, I was still in prison, but I was able to check out of prison using the payphone and they let me keep my belongings. Good thing I didn't drop my shotgun in there.

### Steps to Reproduce the Bug

1: Injure yourself
2: Call local EMS for airlift
3: Wake up in prison

### Expected Behavior

1: Not be unjustly sentenced to prison by judgmental locals.

### Screenshots/Videos

n/a

### Log File

no log data.

**Comment by BBstud44** [comment]
This is also happening to a few of us when we check in at upper Pillbox.

https://medal.tv/games/gta-v/clips/1Y5joy3dFKpH_i/d1337INP22oN?invite=cr-MSxKRWIsMjgwMjUyMTAs
