### ISSUE TITLE
[BUG] No option to check bank account or collect paycheck

### ISSUE THREAD

**Issue by xPorscha** [ParadoxGamingRP/bugs-and-suggestions#2145]
### Your Discord Name

Porscha#5395

### A clear and concise description of what the bug is

When checking the phone in prison, there is no longer an option to check your paycheck amount or to collect your payslip.

### Steps to Reproduce the Bug

go to phone
3rd eye
see there is no options

### Expected Behavior

collect paycheck so im not a broke bitch

### Screenshots/Videos

https://i.imgur.com/Sfhrme3.png

### Log File

[no paycheck collection.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/14454653/no.paycheck.collection.txt)

**Comment by Darahz** [comment]
So broke... God damn
