### ISSUE TITLE
[BUG] Coral Device not working.

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#2148]
### Your Discord Name

jojosnmustard

### A clear and concise description of what the bug is

Talk to the guy for the job, get on my watercraft, use the coral device "Scanning for Corals" but no beeps or visual indicators. Rode all the way around the state and no sites triggered, and no beeps.

### Steps to Reproduce the Bug

1: Get Job
2: Use Device
3: ???

### Expected Behavior

Know where to go find corals.

### Screenshots/Videos

.

### Log File

No log output when using device or getting job.

**Comment by Darahz** [comment]
Just tested this and its working. Do you have any logs a video?

**Comment by emeraldleo1982** [comment]
It seems to be working today so I'm not sure what happened, guess it was just one of those magical things, or maybe it was a specific assigned location that was too far. I'll keep at it and let ya know if it happens again.

In the meantime, I got this gem for ya :)
https://medal.tv/games/gta-v/clips/1YnhSzObDPvhGT/d1337c2SFxiU?invite=cr-MSw5Q2IsMTUzNDM4NTc5LA
