### ISSUE TITLE
[BUG] Prison alarm going off when flying in

### ISSUE THREAD

**Issue by PatrykX904** [ParadoxGamingRP/bugs-and-suggestions#2150]
### Your Discord Name

corruptd3d

### A clear and concise description of what the bug is

So when I woke up in prison, I got a little notification telling me I escaped prison and the alarm went off even though I was still in prison.

### Steps to Reproduce the Bug

1. Get sent to prison
2. Fly out
3. Fly back in
4. Alarm goes off
5. Ears bleed

### Expected Behavior

The alarm only goes off when I escape prison

### Screenshots/Videos

N/A

### Log File

[Prison Alarm.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/14469381/Prison.Alarm.txt)

**Comment by Darahz** [comment]
Pushed a change to hopefully fix this. The issue was with the zone i used around prison just randomly disappearing.
Let me know how it goes
