### ISSUE TITLE
[ENHANCEMENT] Taxi

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#2154]
**Your Discord Name**
ssara

**Describe the annoyance**
The taxi that you can get from the commercial shop doesn't have any neon that sticks. I bought it and it says enabled, but there's no lights. Was wondering if it could be added to the car please.

**Comment by Bac0nRamen** [comment]
its a gta thing all commercial cars are not set up to have those upgrades
