### ISSUE TITLE
[BUG] crypto payout for non comp races

### ISSUE THREAD

**Issue by ZOIMBIE3** [ParadoxGamingRP/bugs-and-suggestions#2155]
### Your Discord Name

zoimbie.

### A clear and concise description of what the bug is

It seems that when you do non pdx races. Just a normal race by yourself or with a friend or two it seems to payout crypto when it should not. If one person is in the race it will payout 25 pdx, if there are two racers in the race it will payout 50 crypto, if there are 3 it will payout 75. The crypto will only go to first place though. 

### Steps to Reproduce the Bug

1. Do a non comp race
2. Finish the race
3. get paid out 25 pdx
4. do a non comp race with 2 people
5. finish and get paid out 50 pdx to first place

### Expected Behavior

to pay out crypto when it should not

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/119633434/37e45971-98a7-4e38-aeff-c3143c0a5a49)

### Log File

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/119633434/9f378e7c-01d4-4627-9edd-472b784a8655)

**Comment by xXJamieXx** [comment]
No way to change this as far as I can tell.
