### ISSUE TITLE
[BUG] Gold is missing as a color at the custom shop

### ISSUE THREAD

**Issue by Drunkle716** [ParadoxGamingRP/bugs-and-suggestions#2163]
### Your Discord Name

MainCharacter716

### A clear and concise description of what the bug is

Used to be between bronze and race yellow but it's suddenly gone. Have it as a pearlescent on all my cars.

### Steps to Reproduce the Bug

Try to find gold paint for vehicle
It ain't there.

### Expected Behavior

Be able to paint a car gold

### Screenshots/Videos

NA

**Comment by Bac0nRamen** [comment]
I dont think its missing its just labeled wrong
