### ISSUE TITLE
Sultan Classic Custom 4 Door Health Adjustment

### ISSUE THREAD

**Issue by jkaejkae888** [ParadoxGamingRP/bugs-and-suggestions#2165]
jkaejkae888

So over the past few days myself and a few friends have been driving this car around and have noticed it is very weak to any damage it stalls very easily even the orange cones on the motorways can stall this car and we find it will also orange engine very quickly without hitting a whole lot even at slower speeds. it feels very similar to the old sultan custom that had it's health fixed a few months ago. Also from experience on both sides it gets broken from cop pits etc very easily.

If any clips need to be made of the examples I gave just let me know and I'll get that for you appreciate the time reading this.

**Comment by Bac0nRamen** [comment]
moving this to vehicle team to do list.
