### ISSUE TITLE
[BUG] Selling prison trash to the man gives too much money.

### ISSUE THREAD

**Issue by Norgman** [ParadoxGamingRP/bugs-and-suggestions#2167]
### Your Discord Name

Norman

### A clear and concise description of what the bug is

Selling stuff to the guy in prison is giving too much money. 

Scrolling through his sell list goes on forever, seems to be repeating itself but at different values. (e.g. price of Varnish at the top is $7 but at the bottom is $9) and there are dozens of prices of varnish all down the list.

Then, once you sell stuff, he seems to give the combined total of all those repeated values.

I sold just a few bits of pocket lint and some ABC gum and he paid me over $600 (should have been like $40)

### Steps to Reproduce the Bug

1. Collect materials around prison
2. Sell them to the man
3. PROFITTTT $$$$$$$$$$$$$$$$$$$$$$$$

### Expected Behavior

Selling prison materials should not be worth so much.

### Screenshots/Videos

The sell list is all crazy
![2024-03-01 (3)](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/150081443/b6cf9bd6-a5ac-4803-81c7-72f615fb09f7)
Seems to be duplicating itself, but with different values for the items. Which seems to pay you multiple times for your stuff...
![2024-03-01 (2)](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/150081443/da3afe4a-021f-475e-bb18-73bd9b1caa15)

**Comment by tusktheshrew** [comment]
I also had the same result.
