### ISSUE TITLE
[BUG] Boost Queue Broken

### ISSUE THREAD

**Issue by SamB1997** [ParadoxGamingRP/bugs-and-suggestions#2173]
### Your Discord Name

davefromsunderland

### A clear and concise description of what the bug is

I was in the boost queue for around 4 hours after the restart and didnt get a single boost. During this time there was a lot of robberies and we were even able to rob a bank truck but still no luck getting a boost job. I finally got the job at around the 4 hour mark and lost it 4 minutes later. 

### Steps to Reproduce the Bug

1. Get In Boost Queue
2. Wait for boost
3. Lose the job almost immediately 

### Expected Behavior

Get contracts more often when there are cops available and not lose it in 4 minutes.

### Screenshots/Videos

https://r2.fivemanage.com/images/8xOyN1n6vWcj.png
https://r2.fivemanage.com/images/kgNnPDplqd5S.png

**Comment by xXJamieXx** [comment]
Lots of people have been queuing for boosts and the system wont assign two boost jobs back to back if theres other jobs being queued up. I can see they were being assigned that day but unfortunately with the quantity of people doing them it has increased wait times. I can't explain why you lost it within 4 minutes of being assigned, weird edge case I guess.
