### ISSUE TITLE
[ENHANCEMENT] FR36 Swap

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#2176]
**Your Discord Name**
ssara

This car is awful when it is stage 3 swapped. It does not turn and it barely hits the speed it's supposed to do. It would need a bit adjustment to be as good as it should and could be. I'd love a swapped version of this but as it is now, it will remain in the garage. 
If you could please look at it, I'd appreciate you,

**Comment by Kromlec** [comment]
Cars handling bad after a swap isn't something we can tweak like that.
