### ISSUE TITLE
[ENHANCEMENT] Volume slider

### ISSUE THREAD

**Issue by PatrykX904** [ParadoxGamingRP/bugs-and-suggestions#2177]
**Your Discord Name**
[corruptd3d]

**Describe the annoyance**
[I would like it if when flying into the server we could possibly have a volume slider in the the loading screen? Im not sure if this is for some other people or just me but I like to listen to my things and the music kinda annoys me.]

**To Reproduce**
[Steps to reproduce the annoyance]
1. Play your own music when flying in
2. Fly in
3. The two songs mixing in 

**Requested behavior**
[A possible slider in the loading screen or maybe even just a button to mute the song]

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by Bac0nRamen** [comment]
When you have fivem running, Open your volume mixer and find something called fivem chromium sub-processes and turn that slider down

**Comment by PatrykX904** [comment]
Thanks!
