### ISSUE TITLE
[ENHANCEMENT] Dominator9

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#2179]
**Your Discord Name**
jojosnmustard

**Describe the annoyance**
It was insanely over tuned, then it got detuned, and now it's too painful to drive. The acceleration is way too low, a small uphill through the city stopped it from gaining any speed. I'm told the race swapped version doesn't even hit 140 now. If we could get it somewhere in the middle of where it was, and where it is now I feel like it would be in a good spot.

**Requested behavior**
Cut back the detune changes to the Dominator GT Coupe by about 50%

**Comment by emeraldleo1982** [comment]
Also a price increase to match it's hopefully better performance and stunning looks, maybe like 70-90k range.

**Comment by Bac0nRamen** [comment]
this car was being abused and had to be nerfed for the time being. it will be looked at again when we feel the time is right. Thanks
