### ISSUE TITLE
[ENHANCEMENT] Dominator GT softtop

### ISSUE THREAD

**Issue by Mambaa19** [ParadoxGamingRP/bugs-and-suggestions#2180]
**Your Discord Name**
[Mambaa_19]

**Describe the annoyance**
[So i hopped in my lovely soft top dominator gt, not the crazy overpowered one and noticed it wouldn't even hit 115MPH on a straight, now and i had it repaired yesterday and it was capping out at 127MPH. i understand the hardtop needed a major detune 1000% but the soft top did not, was very unfortunate to get it out my garage today to feel that it had also been detuned, my suggestion would be to take the softtop back to where it was performance and handling wise and also put the hardtop set at the same performance and handling level as what the softtop was at before so theres no difference between the 2 as i believe the softtop was very balenced and was not in need of a detune like its hardtop younger brother. I appreciate ya'll taking your time to read this.]

**To Reproduce**
[Steps to reproduce the annoyance]
1. 
2. 
3. 

**Requested behavior**
[Take the soft top dominator back to where it was before and also put the hardtop there with it also]

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by xXJamieXx** [comment]
Intentional change.
