### ISSUE TITLE
[BUG] Queue Times

### ISSUE THREAD

**Issue by ZOIMBIE3** [ParadoxGamingRP/bugs-and-suggestions#2181]
### Your Discord Name

zoimbie.

### A clear and concise description of what the bug is

It seems that queue times for jobs aren't working very well. Myself has say in que for boost for multiple hours the past two days and have got nothing. Other friends of mine have also sat in queue and got nothing for multiple hours. Also had someone point out that they sat in queue for a fleeca for almost 5 hours and did not get the job. I'm Thinking there is an issue with queue times and this might need to be looked into.

### Steps to Reproduce the Bug

1. Get into Queue for a boost 
2. wait to see if you get the job

### Expected Behavior

To not give you the job after being in queue for exponential amount of time.

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/119633434/885a3eed-7903-4f13-b3e4-96ba6ab83639)
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/119633434/ee8598e7-974d-48ea-921f-afd277fbf379)

### Log File

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/119633434/11c50341-f8d1-40e0-aba3-62a6949f98c5)
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/119633434/beaaa675-f0a3-469b-8a61-44dae45fd120)

**Comment by ZOIMBIE3** [comment]
First picture is a friends that was in que for awhile and second picture is mine and i was in que for while.

**Comment by xXJamieXx** [comment]
Working as intended. Multiple factors play into how jobs are assigned.

**Comment by ZOIMBIE3** [comment]
ok thanks jamie
