### ISSUE TITLE
[BUG] Harness Poofing From Car

### ISSUE THREAD

**Issue by NickNubbz** [ParadoxGamingRP/bugs-and-suggestions#2183]
### Your Discord Name

NickNubbz

### A clear and concise description of what the bug is

The last day a few race harnesses have been poofing. First my ZR-350 then my friends RH8 then my RH7. The only thing they all had in common is it was all after a engine repair and after the car was parked (not sure if that has anything to do with it). They were also all harnesses that were installed before harnesses actually stayed in the engine (also not sure if that has anything to do with it).

### Steps to Reproduce the Bug

pull engine/repair car with harness in it
park car
pull it back out
maybe have a harness??

### Expected Behavior

Harness should stay in car.

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/74627555/560d1652-187b-4ae8-b004-70317e908e8e)

### Log File

NA

**Comment by Kromlec** [comment]
Have you tried to put a new harness in and it still drop out in the last few days? We made a big change to the engine pull script and there were people abusing a part of it previously.

**Comment by NickNubbz** [comment]
My ZR-350 was the first to drop out yesterday and I put in another harness haven't had any issues with it yet. But I also haven't pulled the engine again yet.

**Comment by Kromlec** [comment]
Remember how some cars would have a harness but it wasn't showing in the engine? That has been corrected so cars that had them "dropped" but were still working, will need new ones installed as we found the issues in the scripting that was allowing that to happen. I hope this explains it properly to ya

**Comment by NickNubbz** [comment]
yea that was my theory that it was only happening to old harnesses that were installed that didn't appear in the engine. Just wasn't sure if there was a quick fix so all the harnesses being refunded doesn't kill the business account drastically.

**Comment by Kromlec** [comment]
Considering the cost of the materials it is to make them, the business shouldn't feel it that bad.. If so management can reach out to staff. Gonna go ahead and close this out, let us know if newly installed components are falling out though.
