### ISSUE TITLE
[BUG] Can't see prisoners!

### ISSUE THREAD

**Issue by SpiceF0x** [ParadoxGamingRP/bugs-and-suggestions#2186]
### Your Discord Name

spicedf0x

### A clear and concise description of what the bug is

The information to see the prisoners currently in prison was working, but it is now not. F8 in pics.

### Steps to Reproduce the Bug

1. Go to computer in prison
2. List all prisoners and time they have left
3. software won't load

### Expected Behavior

1. Go to computer in prison
2. List all prisoners and time they have left
3. software load with prisoner info

### Screenshots/Videos

![FiveM_b3095_GTAProcess_1P1xRAWBwF](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/96963965/9cf01cb1-c6a3-40e5-9f13-bd3cd592c07f)

### Log File

[CitizenFX_log_2024-03-14T180046.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/14608329/CitizenFX_log_2024-03-14T180046.log)

**Comment by Darahz** [comment]
Did a fix for this. Let me know how it works on live

**Comment by SpiceF0x** [comment]
all good! ty!
