### ISSUE TITLE
[BUG] Unable to make Prop scenes at 2026

### ISSUE THREAD

**Issue by KingySloth** [ParadoxGamingRP/bugs-and-suggestions#2191]
### Your Discord Name

Kingy Sloth

### A clear and concise description of what the bug is

Hi,
So it appears that im unable to make a Scene at postal 2026. I tried to make one at the  grapeseed house and was successful, Then i moved to postal 2026 where i was unable. I was also not able to make one at the same postal the other night, neither were any of the people i was with. After running back to the grapeseed again making a scene was not possible. I think its something to do with the location 2026 as this is the 3rd of 4th time ive consecutively not been able to make a scene at this location.  

### Steps to Reproduce the Bug

1. Try to create a scene at 2026

### Expected Behavior

I dont expect anything as this is dealt with in your own free time. I would hope you would be able to look into it and see if it is a bug. 

### Screenshots/Videos

None to upload as i cant record currently 

### Extra Notes (Optional)

I hope this is enough information to help - if not please reach out.

**Comment by lPrestonl** [comment]
Can you by any chance show a picture of where you were trying to do it since you can't record? Also logs would also help. Thank you.

I can't seem to find any areas where I can't create a scene.

**Comment by KingySloth** [comment]
Hi,
I managed to get my clips working again and have just made one. 
I did think initially it was just me, but there was a total of 3 people that tried that were unable and i can never seem to make one in this area. 
Id need you to tell me what logs you need? Assuming that is the f8?
https://medal.tv/games/gta-v/clips/22yV602uLy9PXl/d13378qw81MI?invite=cr-MSxFeWcsMjE2NDM1MDY3LA

**Comment by lPrestonl** [comment]
Go any try to do it one more time and then follow these steps right after you try to do it.

a. Find your FiveM logs file by navigating to C:\Users\<your user name>\AppData\Local\FiveM\FiveM.app\logs
b. In the logs folder find the log with the date and time relevent to the session of FiveM you encountered the bug in. (usually the latest one)

That is weird though, I went up to 2026 and tried and had no issue. Hopefully something in logs with show whats going on.

**Comment by KingySloth** [comment]
[CitizenFX_log_2024-03-23T190635.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/14733370/CitizenFX_log_2024-03-23T190635.log)

hopefully this uploads. 

if you need anything else then obviously let me know.
