### ISSUE TITLE
[BUG] PD RADAR NOT WORKING (CTRL M)

### ISSUE THREAD

**Issue by saberontop** [ParadoxGamingRP/bugs-and-suggestions#2193]
### Your Discord Name

fwsaber

### A clear and concise description of what the bug is

i believe this is a known issue and I've talked to some ppl ab it, but for some pd members ctrl+m just doesn't work. 

### Steps to Reproduce the Bug

press ctrl m in pd car w/ radar on

### Expected Behavior

will not work, nothing will happen

### Screenshots/Videos

vids wouldnt do much as i cant show that I'm pressing ctrl m

**Comment by Kromlec** [comment]
Double check your keybinds and ensure you are using the correct ctrl, just tested in live and my left ctrl + m brings up my radar just fine.
