### ISSUE TITLE
[ENHANCEMENT] Trucks with trailors

### ISSUE THREAD

**Issue by Jacob017483** [ParadoxGamingRP/bugs-and-suggestions#2195]
**Your Discord Name**
[James ram]

**Describe the annoyance**
[A lot of trucks the have tow hitches dont work with the race trailer the only trucks that work are the bobcat and the Buffalo i know the sandstorm dose not work]

**To Reproduce**
[Steps to reproduce the annoyance]
1. Get a sand storm truck with a hitch 
2. Rent a race trailer 
3. Try to attach it

**Requested behavior**
[What i would like to happen is eather the it gets fixed or find a trailer that not glitchy like the other trailer]

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by Kromlec** [comment]
The XL works as well, but the EV version was missed for adding the race trailer to it.

**Comment by Jacob017483** [comment]
I will try again on the xl and see what happens

**Comment by Jacob017483** [comment]
Just tested the xl it works I had trouble I'm the past with

**Comment by Jacob017483** [comment]
Bit it looks like that problem was fixed

**Comment by Kromlec** [comment]
Good to hear, the EV however will not be fixed until after the wipe!

**Comment by Jacob017483** [comment]
What about campers

**Comment by Jacob017483** [comment]
Rvs

**Comment by Jacob017483** [comment]
I used to tow with those
