### ISSUE TITLE
[BUG] Local farmer market not paying

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#2201]
### Your Discord Name

jojosnmustard

### A clear and concise description of what the bug is

Sell Rubber to local Farmer's Market guy in Paleto, rubber dissapears, no payout though.

### Steps to Reproduce the Bug

1: Open crop deposit box
2: sell crop
3: no money

### Expected Behavior

Money received for product

### Screenshots/Videos

N/A

### Extra Notes (Optional)

no log output

**Comment by JnKTechstuff** [comment]
Should be fixed if not open a new report
