### ISSUE TITLE
[BUG] Can't open ATM

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#2202]
### Your Discord Name

jojosnmustard

### A clear and concise description of what the bug is

Try to access ATM for normal banking activities and nothing happens I get frozen in spot and have to F8 logout

### Steps to Reproduce the Bug

1: Open ATM
2: Logout through F8

### Expected Behavior

ATM works

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/29337315/f7d8db95-06c9-4170-b85f-db0053c7355b)

**Comment by CorFinn** [comment]
Are you using NVE? If so, remove animated_atm.rpf (or something similar, I can't remember the specific name off-hand but it's the only one referencing ATMs) from your mods folder. 

If you're not using NVE, let us know.

**Comment by JnKTechstuff** [comment]
We are aware of the banking issues and working on resolving them as soon as possible
