### ISSUE TITLE
[BUG] Animal Seller won't talk

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#2203]
### Your Discord Name

jojosnmustard

### A clear and concise description of what the bug is

Try to talk to fatty mcgee at the animal farm and he gives the popup but nothing happens.

### Steps to Reproduce the Bug

1: Try to buy animals
2: Can't talk to guy

### Expected Behavior

Become a cattle magnate and live comfortably for the rest of my days driving a lifted F-350 Lariat

### Screenshots/Videos

No log output

**Comment by JnKTechstuff** [comment]
This should be fixed, if not open a new bug report
