### ISSUE TITLE
[BUG] Finance not updating phone bank info

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#2204]
### Your Discord Name

jojosnmustard

### A clear and concise description of what the bug is

Financed a vehicle through Kildare's, bank app still shows the amount of $ I had before the financing.

### Steps to Reproduce the Bug

1: Finance Vehicle
2: Check Phone bank app

### Expected Behavior

Phone bank app updates on financing.

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/29337315/e54a292d-6d06-45ab-b839-badb19f90495)

### Extra Notes (Optional)

This might be part of the cause of my ticket related to the ATM not opening, the financing might be breaking something in the accounts system. Just a thought.

### Log File

I'm getting a lot of log error spam towards the tail of the log.

[CitizenFX_log_2024-05-26T191615.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/15448964/CitizenFX_log_2024-05-26T191615.log)

**Comment by JnKTechstuff** [comment]
We are aware of these issues and are working to resolve them as soon as possible
