### ISSUE TITLE
[BUG] Financed Cars not showing up in impound

### ISSUE THREAD

**Issue by BBstud44** [ParadoxGamingRP/bugs-and-suggestions#2207]
### Your Discord Name

BBstud27

### A clear and concise description of what the bug is

financed car gets destroyed so you call county to come pick it up when you go to impound its not there even after waiting and/or logging out and coming back. Phone says its parked at Public vehicle Depot but the location on the side says unknown.

staff panel says its > Publicvehicledepot

### Steps to Reproduce the Bug

1. Finance a car
2. destroy said car
3. call county tow 
4. go to impound and find nothing
5. location on the phone say unknown

### Expected Behavior

the car to go to the impound and not dumped in the junkyard for scrap :(

### Screenshots/Videos

https://i.imgur.com/P97Tn3W.jpeg

### Log File

[For Financed cars in impound.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/15449435/For.Financed.cars.in.impound.txt)

**Comment by JnKTechstuff** [comment]
Fixed; was a mixup in SQL statement
