### ISSUE TITLE
[BUG] <sOil rig not resetting after stopping the job>

### ISSUE THREAD

**Issue by tommytwoshotty** [ParadoxGamingRP/bugs-and-suggestions#2208]
### Your Discord Name

tommytwoshotty

### A clear and concise description of what the bug is

After pumping the oil rig to 1000 gallons as is required and cashing the job out i restarted the job. when i restarted the job it didnt clear out the gallons from the pumping beforehand causing me to get a second pay when i stopped the rig.

### Steps to Reproduce the Bug

go to oil rig
Start oil rig job
use the valves to control oil rig to get proper flow of 1000 gallons
cash out  in the rig
restart the rig after cashing out
Get message that says that its full and to cash out

### Expected Behavior

Be able to restart rig at 0 after a full pump

### Screenshots/Videos

Did not take any of the error

### Log File

[CitizenFX_log_2024-05-27T002800.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/15450211/CitizenFX_log_2024-05-27T002800.log)
[CitizenFX_log_2024-05-26T224130.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/15450212/CitizenFX_log_2024-05-26T224130.log)

**Comment by JnKTechstuff** [comment]
This should be fixed
