### ISSUE TITLE
[BUG] Oilrig

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#2211]
### Your Discord Name

ssara

### A clear and concise description of what the bug is

When doing the oilrig job you have to restart it multiple times. It stops giving you gallons when you have fixed the flowrate, ressure and temp once. 

### Steps to Reproduce the Bug

Start oil drilling
Fix temperature, flow rate or pressure
See gallons not moving at all

### Expected Behavior

Be able to get a full job done

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/98127638/b82c0d58-85ea-46f8-9a0b-362e606a343f)

### Log File

[oilrig.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/15452680/oilrig.txt)

**Comment by JnKTechstuff** [comment]
Should be fixed
