### ISSUE TITLE
[BUG] No Truck Rentals

### ISSUE THREAD

**Issue by ZOIMBIE3** [ParadoxGamingRP/bugs-and-suggestions#2212]
### Your Discord Name

zoimbie.

### A clear and concise description of what the bug is

When ever you get a quick job in the trucking it does not supply you with a truck and it says it should.

### Steps to Reproduce the Bug

Get quick trucking job
don't receive truck 

### Expected Behavior

To not get a truck from a quick trucking job.

### Screenshots/Videos

no need for screen shot or video. You just don't get a truck when trying to do the job. 

### Extra Notes (Optional)

I know that for the other jobs you need to buy your own truck but it says its suppose to give you one for quick trucking jobs. 

### Log File

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/119633434/e840b3c4-c40b-4867-b8fa-c9dc2ae56472)

**Comment by JnKTechstuff** [comment]
We are aware of the issues with the trucking job and will have an update for it as soon as possible
