### ISSUE TITLE
[BUG] Farming

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#2213]
### Your Discord Name

ssara

### A clear and concise description of what the bug is

Cant have any farmanimals. 

### Steps to Reproduce the Bug

Talk to the dude.
Nothing

### Expected Behavior

Talk to dude
Get option of pig, chick and cows
Milk'em, feed'em, kill'em

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/98127638/85630b87-71ee-4115-aaa5-0d5eca4ba4b4)

**Comment by JnKTechstuff** [comment]
Somehow the entire script was deleted. It has been re-added
