### ISSUE TITLE
[BUG] K9 area search 

### ISSUE THREAD

**Issue by Dez505** [ParadoxGamingRP/bugs-and-suggestions#2218]
### Your Discord Name

dez505

### A clear and concise description of what the bug is

When trying to use the new K9 area search mechanic it takes the dog around 3-5 minuets to do 4-8 sniffs in different spots . After the dog is done with searching the area a menu pops up and you have to hope that you click the right option or else you have to spend another 3-5 minuets geting that menu back up.

### Steps to Reproduce the Bug

1. pull out AI K9
2. chase someone and have the suspect hide
3. do /k9_search

### Expected Behavior

i would like to see the dog sniff around 2-3 different locations instead of 4-8. I would also like to be able to pull up the menu after i search the area without the dog having to go threw all the animation

### Screenshots/Videos

n/a

### Extra Notes (Optional)

n/a

**Comment by xXJamieXx** [comment]
1. It's always 4 spots
2. Added /k9_searchmenu to bring up last search
