### ISSUE TITLE
[BUG] Planes made out of paper

### ISSUE THREAD

**Issue by Drunkle716** [ParadoxGamingRP/bugs-and-suggestions#2224]
### Your Discord Name

MainCharacter716

### A clear and concise description of what the bug is

Doing the pilot job and it seems as though the engines catch on fire randomly or you pull into the gate and they just explode.

### Steps to Reproduce the Bug

Take the plane job
Pull into the gate
Plane cathes on fire or explodes.

### Expected Behavior

Pull into gate and offload passengers without exploding

### Screenshots/Videos

![FiveM_b3095_GTAProcess_Rqn1PdrSwQ](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/100391224/e7baf9b2-6d14-4d74-8c75-14b64c8351c8)
https://r2.fivemanage.com/images/gQejKKog2dWr.webp

### Log File

[CitizenFX_log_2024-05-27T211058.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/15461962/CitizenFX_log_2024-05-27T211058.log)

**Comment by CorFinn** [comment]
Hey. Currently there's an issue where, if you have a copilot, there's a chance that happens. We're aware, and are working on a fix. Until then, we recommend you fly solo for a bit.

**Comment by Drunkle716** [comment]
All these explosions were solo though
    On Monday, May 27, 2024 at 06:13:28 PM EDT, CorFinn ***@***.***> wrote:  
 
 


Hey. Currently there's an issue where, if you have a copilot, there's a chance that happens. We're aware, and are working on a fix. Until then, we recommend you fly solo for a bit.

**Comment by CorFinn** [comment]
Hmm... Ok, we'll look into it. Ty

**Comment by JnKTechstuff** [comment]
Fixed

**Comment by Drunkle716** [comment]
![FiveM_b3095_GTAProcess_swVZoQHOj6](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/100391224/79fc5cad-a3b1-40ee-8d34-b87c591f224b)

Local spawned inside the plane or disembarked inside the plane.

**Comment by Drunkle716** [comment]
![FiveM_b3095_GTAProcess_sCFZWdaYS7](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/100391224/e928922d-ee39-49ed-b7c1-516c1943a15d)
