### ISSUE TITLE
[BUG]  Payout for a job

### ISSUE THREAD

**Issue by Rac-coder** [ParadoxGamingRP/bugs-and-suggestions#2228]
### Your Discord Name

super raccoon

### A clear and concise description of what the bug is

The payout for farming is currently exceedingly too high compared to other options. 
I grew 10 carrot seeds this gave me over 100 carrots. It took me about 20 minutes to grow the crop. If you min maxed this you could get well over 10k an hour with the carrots selling at 25 dollar per crop. even with the price of fert and seeds being included you still will be FLYING above the rest. 

### Steps to Reproduce the Bug

1. grow crop 
2. sell crop 
3. make bread 

### Expected Behavior

be more balanced to the economy maybe paying closer to 2500 per hour? 

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/2fMiI2jgeYDxHO/d1337kmbKlyY?invite=cr-MSxpV1csMTQxMDcwODUs

### Log File

N/A

**Comment by emeraldleo1982** [comment]
Specifically it's $4875 every 34 minutes before the expenses of $20 worth of seeds, 187.50 worth of fertilizer, and 2 reusable watering cans. This is including the $5 "good bean" bonus for being a civilian. Wtihout the civilian bonus, it's 3900 every 34 minutes, after expenses it comes down to $3692. 

A grand total of $6515.29 per 60 minutes min/max'd without the civ bonus after expenses,  $8236 per 60 minutes with civilian bonus after expenses.

There's the min/max numbers if ya need em.
