### ISSUE TITLE
[BUG] Can't Collect my payslip

### ISSUE THREAD

**Issue by Drunkle716** [ParadoxGamingRP/bugs-and-suggestions#2230]
### Your Discord Name

MainCharacter716

### A clear and concise description of what the bug is

Go to big bank to collect my payslip and you don't get your money

### Steps to Reproduce the Bug

Go to big bank
Collect your payslip

### Expected Behavior

You get money when you collect payslips.

### Screenshots/Videos

N/A

### Log File

[CitizenFX_log_2024-05-28T000806.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/15462917/CitizenFX_log_2024-05-28T000806.log)

**Comment by Kromlec** [comment]
Duplicate of #2229
