### ISSUE TITLE
[BUG] High end houses not feeling high end

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#2233]
### Your Discord Name

jojosnmustard

### A clear and concise description of what the bug is

Not sure if it's a bug or intended behavior, but the high end houses are giving low end stuff it seems.

### Steps to Reproduce the Bug

1: Talk to the guy and get the house location
2: rob high-end house
3: check pockets
4: still poor

### Expected Behavior

1: rob high-end house
2: check pockets
3: can buy a cheeseburger and bottle of vodka and maybe a pack of smokes

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/29337315/26f2c2aa-8625-4c0a-8ada-4e286dfa0bdf)

Loot from a high end house in the hills.

**Comment by Bac0nRamen** [comment]
Its all mostly a random chance for the items you get. I will leave this open for now and we will monitor as well as others can comment on there experience of payouts.
