### ISSUE TITLE
[BUG]  deviant not having full preformance upgrades avaliable 

### ISSUE THREAD

**Issue by DallasKnightwave** [ParadoxGamingRP/bugs-and-suggestions#2234]
### Your Discord Name

DallasKnightwave 

### A clear and concise description of what the bug is

Schyster deviant only has option for one lvl of upgrade per section... brakes, eng, Trans, and suspension 

### Steps to Reproduce the Bug

Enter Benny's 
Attempt to upgrade vehicle 
Access to only one lvl of upgrade per part

### Expected Behavior

Access to full upgrades

### Screenshots/Videos

No screenshot available

**Comment by kingtortle** [comment]
Same for vigero

**Comment by xXJamieXx** [comment]
This is not a bug. It is how it works now.
