### ISSUE TITLE
[BUG] No payour for selling meat and veggies

### ISSUE THREAD

**Issue by RoseiiNaytool** [ParadoxGamingRP/bugs-and-suggestions#2236]
### Your Discord Name

Roseii

### A clear and concise description of what the bug is

When you go to the chicken factory and put in either meat or veggies, then sell them, it gives you no money. In the top right coner when you sale it doesn't show that you are given a +$ like usual

### Steps to Reproduce the Bug

1. Put in meat and/or veggies in chicken factory
2. sale meat or veggies
3. no money pay out

### Expected Behavior

To get the pay out amount for selling the produce to the chicken factory

### Screenshots/Videos

There really isn't a screen shot that I can give. there is also nothing in the F8 menu for an error when I look.

**Comment by emeraldleo1982** [comment]
Tested the animal plant as well, receiving nothing for meat/byproduct sold.
