### ISSUE TITLE
[BUG] Beehive

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#2237]
### Your Discord Name

ssara

### A clear and concise description of what the bug is

I placed a beehive and a house and it disappeared. This was before the storm. After the storm I tried to place one again but it just said I cant place another house because I already have one placed.

### Steps to Reproduce the Bug

Place a beehouse
Get it washed away
Try to place a new one
Don't

### Expected Behavior

Place a house
Be able to

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/98127638/ce39702f-5e42-4b6b-b54d-c76be0272d87)

**Comment by Nickeh15** [comment]
ive found also walking into them makes them go through the floor
