### ISSUE TITLE
[BUG] Dremmel

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#2244]
### Your Discord Name

ssara

### A clear and concise description of what the bug is

With the new economy and the lack of anywhere to repair it, it doesnt make sense for the dremmel to break after 3-4 uses. 
$750 should either give you more uses or have a place to buy some repairing for it that's not over the top expensive. 

### Steps to Reproduce the Bug

Dremmel
Dremmel
Dremmel
Dremmel
Don't dremmel no more

### Expected Behavior

Able to dremmel some more

### Screenshots/Videos

N/A

**Comment by Bac0nRamen** [comment]
you dont buy a dremmel each time. You craft a item that allows you to repair it pretty much
