### ISSUE TITLE
[BUG] Bike Shop Custom Shop Not Functioning

### ISSUE THREAD

**Issue by Drunkle716** [ParadoxGamingRP/bugs-and-suggestions#2245]
### Your Discord Name

MainCharacter716

### A clear and concise description of what the bug is

Bring a vehicle to the mod shop in the bike shop and it does not work.

### Steps to Reproduce the Bug

Pull bike into modshop
Hit E
Not customization menu

### Expected Behavior

You can customize a bike

### Screenshots/Videos

![FiveM_b3095_GTAProcess_hQzMe5jjpA](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/100391224/94ae1a34-5efc-4c4e-9ddd-902c253829c3)

### Log File

[CitizenFX_log_2024-05-28T172523.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/15474211/CitizenFX_log_2024-05-28T172523.log)

**Comment by lPrestonl** [comment]
To add to this, The Mod Shop doesn't work at NS or Bikini.
Same Error.

**Comment by lPrestonl** [comment]
I retract my statement. This has been fixed and should be working in Live server right now.
