### ISSUE TITLE
Cant speak with trucking guy

### ISSUE THREAD

**Issue by ZOIMBIE3** [ParadoxGamingRP/bugs-and-suggestions#2248]
### Your Discord Name

zoimbie.

### A clear and concise description of what the bug is

Unable to talk to trucking guy and obtain a job

### Steps to Reproduce the Bug

1. 3rd eye tucking guy
2. wont allow you to talk to him

### Expected Behavior

He will not let you talk to him.

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/119633434/8850769f-aec3-44ca-9164-85e577f70b46)

**Comment by Kromlec** [comment]
Fixed in live kind sir! thank you!
