### ISSUE TITLE
[BUG] The man won't paint my cara

### ISSUE THREAD

**Issue by SpiceF0x** [ParadoxGamingRP/bugs-and-suggestions#2250]
### Your Discord Name

spicedf0x

### A clear and concise description of what the bug is

I can't respray my car, but I **can** remove extras. What a lazy customs guy.

### Steps to Reproduce the Bug

1. Open menu
2. Go to repsray
3. Pick a beautiful colour
4. See it looks great
5. Exit menu
6. Click Purchase
7. Paint reverts
8. Cry

### Expected Behavior

1. Open menu
2. Go to repsray
3. Pick a beautiful colour
4. See it looks great
5. Exit menu
6. Click Purchase
7. Paint applies fully and dries
8. Smile

### Screenshots/Videos

https://streamable.com/2ytnxf

**Comment by JnKTechstuff** [comment]
Fixed
