### ISSUE TITLE
Echo doesn't work

### ISSUE THREAD

**Issue by WraithKildare** [ParadoxGamingRP/bugs-and-suggestions#2256]
### Your Discord Name

EmiDirano

### A clear and concise description of what the bug is

It's not really a bug. The Echo Ped is not working. The black shepherd and the dark faced one are working, but Echo's gray version is not working. I know we had this issue in the past. I tried to get it to work by setting it in dev with the V menu, but this time it won't stick. When I log into live, I can't use the gray striped version of Echo. When I change clothes, which is how I change peds before, it just changes the dog ped to different variations, but not the Gray one. Also, I can't sit again with control key. I know we had fixed that issue in the past and you guys were able to make that script work again. All the other commands on the dog script work except for sit which is the control key. 

### Steps to Reproduce the Bug

Tried to use dev and live server to fix it. Chris tried to fix it too. Not sure what to do. 

### Expected Behavior

Log in. use clothing changer to switch between Echo and Zeus ped models. 

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/2fXsIjVGMFXwvV/d1337BBEffKN?invite=cr-MSxsRTEsMzQ3OTM3MTAs

### Extra Notes (Optional)

This is absolutely and obviously not a priority, but thank you for looking into it at some point eventually. Appreciate it.

**Comment by JnKTechstuff** [comment]
This has been fixed and you can change colors under "Face Skins" on the ped menu now and it should work
