### ISSUE TITLE
[ENHANCEMENT] Map is kinda wonky 

### ISSUE THREAD

**Issue by RoguIsAwesome** [ParadoxGamingRP/bugs-and-suggestions#2262]
**Your Discord Name**
rogue_69

Its not a serious issue but it is a slight annoyance. The map isn't fixed on a allignment with the new HUD so it just looks weird and unorganised.

**Comment by emeraldleo1982** [comment]
The alignment of the map is tied to the screen safezone size which you can change in Setting > Display inside your game.
