### ISSUE TITLE
[ENHANCEMENT] Make Chickens Better

### ISSUE THREAD

**Issue by natashajoan** [ParadoxGamingRP/bugs-and-suggestions#2272]
**Your Discord Name**
ItsAhsatan

**Describe the annoyance**
So, we have done multiple runs of x5 chickens at the farm, and the give out for the eggs that Chicken provide, aren't consistent. This is more so an issue if you're rearing chickens for a business, for example at Glazed & Glorious, we use a lot of eggs, through recipes or for raw pasta. Here were the results from the runs we did. 

R1: 18 
R2 : 16
R3: 28
R4: 24
R5: 27
R6: 12
R7: 10

All the chickens per run were raised the same way, yet the numbers for eggs were pretty inconsistent. 

**To Reproduce**
[Steps to reproduce the annoyance]
1. Go to farm
2. Buy 5 chickens
3. Feed and water to perfection
4. Receive eggs
5. Repeat and normally receive less eggs than before
6. Be sad at lack of eggs

**Requested behavior**
For the chickens to give a more consistent amount of eggs per run, similar to Cows for Milk. Between 25-30 per run for x5 chickens, hopefully. 

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by xXJamieXx** [comment]
Seems you got pretty unlucky RNG but I've increased the drop chance for eggs so it should drop a bit more often.
