### ISSUE TITLE
[BUG] Fishing rod is not removing bait

### ISSUE THREAD

**Issue by agentspooky19** [ParadoxGamingRP/bugs-and-suggestions#2273]
### Your Discord Name

bby.spooky

### A clear and concise description of what the bug is

While fishing, I got my fishing rod and bait. Baited the rod as normal and noticed that after having already casted the rod multiple times, I've only used ONE bate. I don't know if this is because there is a "chance" you lose your bate or if this is unintentional. So I just wanted to make it aware.

### Steps to Reproduce the Bug

1. Get rod and bate the hook
2. Fish as normal (multiple times)
3. Check inventory and should show that only one bate has been used

### Expected Behavior

1. Get rod and bate the hook
2. Fish as normal
3. Bate should be removed per cast (Unless this is intentional)

### Screenshots/Videos

None

**Comment by xXJamieXx** [comment]
It is chance based.
