### ISSUE TITLE
[BUG] Repair Not Working in Tuner Shop

### ISSUE THREAD

**Issue by ColKing** [ParadoxGamingRP/bugs-and-suggestions#2274]
### Your Discord Name

Colt__

### A clear and concise description of what the bug is

When driving into the first two bays, we cannot use our F1 to repair the car like we used to be able too. 

### Steps to Reproduce the Bug

1. Drive into the first or second bay 
2. Open F1 menu and repair car
3. F1 menu repairs car so we can work on it 

### Expected Behavior

When driving into the first two bays, the expected behavior is too be able to repair the car. So that we are able to pop the hood and begin working on the engine. 

### Screenshots/Videos

no screen shot at this time

**Comment by lPrestonl** [comment]
The F1 repair was removed, use the modshop in your garage to repair.

**Comment by ColKing** [comment]
okay didn't know that but its going to be such an inconvenience when there are multiple cars needing repairs.
