### ISSUE TITLE
[BUG] Weaponized Vehicles Still Have Their Weapons

### ISSUE THREAD

**Issue by Skeletal-KC** [ParadoxGamingRP/bugs-and-suggestions#2281]
### Your Discord Name

skeletal_kc

### A clear and concise description of what the bug is

A few of the weaponized vehicles like the Buffalo STX still have their weapons available through the Benny's menu. Everything from Armor Plating to Mines and Machine guns. I checked a few, but obviously didn't go through every weaponized vehicle in every dealer.

### Steps to Reproduce the Bug

1. Take an STX to the Benny's inside the underground racing area.
2. Check the Benny's Menu
3. Weapons.

### Expected Behavior

Probably shouldn't have access to vehicular mines, and machine guns.

### Screenshots/Videos

![Screenshot (829)](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/122247151/9118bd2c-7fc5-4fb5-a12f-598058324a52)
![Screenshot (830)](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/122247151/97fa6585-eb03-4af9-979f-67ab2a8372ba)
![Screenshot (831)](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/122247151/eb245ed2-052e-4008-a680-d992d397d812)
![Screenshot (833)](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/122247151/28b0c41c-9b1c-473c-bfbe-97ed06b60b1f)
![Screenshot (834)](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/122247151/783514fd-1004-4960-aaf2-17e267bc2ced)
![Screenshot (835)](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/122247151/47b8cbcf-f545-4121-8fb5-515976739470)

**Comment by xXJamieXx** [comment]
This is known and we will be going through these and disabling the weapon options as they are brought to attention. To clarify though if you were to purchase them they should not actually be functional.

**Comment by lPrestonl** [comment]
Had a talk with the manufacture, The STX and 300r will no longer be made with these distasteful weapons on them starting tomorrow.
