### ISSUE TITLE
[BUG] Clothes make me Bleed

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#2296]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

Changing my clothes in the G&G wardrobe makes me bleed warm blood.

### Steps to Reproduce the Bug

1. Clock into G&G
2. Change clothes

### Expected Behavior

Perfect healthy self.

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/98053772/c3dd9441-f511-4c11-8566-8ad22dca255f)

**Comment by CorFinn** [comment]
This happens to peds as well. I was downed instantly at the changing spot in SADOT HQ while switching outfits.

**Comment by xXJamieXx** [comment]
Is this still an issue?

**Comment by SaraLef** [comment]
Yes, happened yesterday.

**Comment by SaraLef** [comment]
Adding^ HAppened when changed clothes in the garage at my house. Doesn't happen more at Kildare's at least.

**Comment by CorFinn** [comment]
Anecdotally, I don't think I remember it ever happening in my apartment, but it definitely does in the the Altas HQ, Red Rocket, SADOT, and VPD. 
It's not every time, and so far, I can find no pattern to it. 
I also don't get any F8 errors.
