### ISSUE TITLE
[BUG] Tools in Farming Deliveries Doesn't Pay

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#2301]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

Doing tools for the Delivery guy doesn't earn any money only reputation

### Steps to Reproduce the Bug

1. Fill up on rep
2. do other jobs from the same guy
3. Only get paid a flat amount from the other jobs not the tools.

### Expected Behavior

Get paid for each job.

### Screenshots/Videos

N/A

**Comment by Darahz** [comment]
You're right. It's a way to increase your relation to "quickly" up it and get more pay from the other jobs.
