### ISSUE TITLE
[ENHANCEMENT] Make Glass Great Again

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#2303]
**Your Discord Name**
ssara

**Describe the annoyance**
There's almost no usage of glass atm, is there a way to change some ingredients out for some things and add glass instead?

**Comment by SaraLef** [comment]
Posted a lil too quick heheheh. 
But maybe for parts at repairshops because they do fix the windows there as well. Or bongs? Coral detector? Tablet?

**Comment by Bac0nRamen** [comment]
added to mostly mechanic job items let me know if u have ideas for others
