### ISSUE TITLE
[BUG] Jugular lost it's mind

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#2304]
### Your Discord Name

jojosnmustard

### A clear and concise description of what the bug is

After the storm today the Jugular seems to have forgotten how to car properly. It's insanely quick, and once you hit last gear it rockets to 136 near instantly and the accelerator feels stuck, then the physics get wonky.

### Steps to Reproduce the Bug

1: Test drive Jugular
2: Pray

### Expected Behavior

Normal car behavior

### Screenshots/Videos

,

### Log File

No Log Output

**Comment by lPrestonl** [comment]
Fixed in dev. Will be fixed after restart tomorrow (6/3/2024)
