### ISSUE TITLE
[BUG]  Unable to get response when pressing "G" to attache to a PD call

### ISSUE THREAD

**Issue by KingySloth** [ParadoxGamingRP/bugs-and-suggestions#2305]
### Your Discord Name

Kingy Sloth

### A clear and concise description of what the bug is

When on Cop and a dispatch call comes in - pressing "G" to attach to the call does not gain a response. 
Have to press O and physically click attach. 

### Steps to Reproduce the Bug

1. Crime call comes in
2. Press "G" Key 
3. Does not give waypoint or attach to the call. 

### Expected Behavior

When pressing G - as per the prompt. Expect it to register attaching to the call and provide a waypoint. 

### Screenshots/Videos

I do not have a recording app set up also can get screenshots but dont know what that would achieve given the problem. 

### Extra Notes (Optional)

Have checked with others in city and they are having the same issue.

**Comment by KingySloth** [comment]
Sorry - processed too soon, Just been advised its E you have to press not G like shown on the call.

**Comment by xXJamieXx** [comment]
Did you check your keybinds, if E is working then its probably set to that...

**Comment by KingySloth** [comment]
dumb moment by me
