### ISSUE TITLE
Best buds Grow Basement is not working

### ISSUE THREAD

**Issue by ZOIMBIE3** [ParadoxGamingRP/bugs-and-suggestions#2313]
### Your Discord Name

zoimbie.

### A clear and concise description of what the bug is

Go down and try to grow weed at best buds and it says you can not grow here.

### Steps to Reproduce the Bug

1. Go down to best buds basement 
2. try to grow best buds weed
3. action is not possible

### Expected Behavior

Will not allow you to grow weed.

### Screenshots/Videos

https://r2.fivemanage.com/images/ObHIGZdTNYPj.png

### Log File

https://r2.fivemanage.com/images/PJH0Ab8QzmbS.png

**Comment by Bac0nRamen** [comment]
So we got it working but new problem we have now is the prop model for the plants wont show inside the interior when you plant
