### ISSUE TITLE
[BUG] Cargobob spawn

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#2320]
### Your Discord Name

jojosnmustard

### A clear and concise description of what the bug is

A cargobob spawns on the ground.

### Steps to Reproduce the Bug

1: Find Cargobob

### Expected Behavior

Not find cargobob?

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/29337315/6f21ec52-9c9d-4915-91da-0bea48c84cf7)

**Comment by Bac0nRamen** [comment]
Fixed Next restart
