### ISSUE TITLE
[BUG] Dispatch attach and detach buttons disappeared

### ISSUE THREAD

**Issue by Rottenquantity** [ParadoxGamingRP/bugs-and-suggestions#2324]
### Your Discord Name

unforgiven

### A clear and concise description of what the bug is

the attach and detach auctions no longer appear as seen in the below images

### Steps to Reproduce the Bug

be on duty as a job that gets dispatched calls,
To receive a dispatch call,
Open the menu and not be able to attach detached to it well on PD,

### Expected Behavior

be on duty as a job that gets dispatched calls,
To receive a dispatch call,
Open the menu and be able to attach detached to it well on PD,

### Screenshots/Videos

now
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/85376462/8e583b50-9ace-4cff-985a-f04bd48bd062)

before bug
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/85376462/db4b4147-e90e-4eba-a316-7ff45625a413)

**Comment by xXJamieXx** [comment]
You click on the icon next to the trash icon.
