### ISSUE TITLE
[BUG] Scuba tank not depleting 

### ISSUE THREAD

**Issue by NataliaGallo96** [ParadoxGamingRP/bugs-and-suggestions#2325]
### Your Discord Name

Carebear#9564

### A clear and concise description of what the bug is

i used it under water and the tank remains at 1800 after using it for a bit

### Steps to Reproduce the Bug

1. buy tank 
2. go scuba diving
3. look at oxygen level

### Expected Behavior

1. buy tank 
2. go scuba diving
3. look at oxygen level go lower

### Screenshots/Videos

![FiveM_b3095_GTAProcess_m032Ie9sSf](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/123715929/1217c071-7618-4c42-b337-f895e7559d72)

### Log File

[CitizenFX_log_2024-06-02T183600.log](https://github.com/user-attachments/files/15526553/CitizenFX_log_2024-06-02T183600.log)

**Comment by xXJamieXx** [comment]
It doesn't update until you take it off.
