### ISSUE TITLE
[BUG] Bees 3.0

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#2330]
### Your Discord Name

ssara

### A clear and concise description of what the bug is

After my falling out with the bees, I still cannot place a bee hive. It says that I already have a house and hive at the location where it poofed.

### Steps to Reproduce the Bug

Put a hive down
go away to get money for repairs
come back
its stolen but blip is still there
cant place one, you already have one

### Expected Behavior

be able to give Beekachu his home back.

### Screenshots/Videos

N/A

**Comment by kingtortle** [comment]
I've noticed after restart most of the time they come back

**Comment by SaraLef** [comment]
My bees took off on day 2 and never returned. Sad times.

**Comment by SaraLef** [comment]
Maybe if there was a way to respawn it like you do with cars, if it poofs
