### ISSUE TITLE
[ENHANCEMENT] Sender Banking Details

### ISSUE THREAD

**Issue by SpiceF0x** [ParadoxGamingRP/bugs-and-suggestions#2331]
**Your Discord Name**
spicedf0x

**Describe the annoyance**
When receiving a payment from someone you can't be sure who it's from. All you receive is a number 
https://r2.fivemanage.com/images/hxpTuhvJUhsC.png

As someone who receives a few bank transfers, this can be hard to distinguish who has paid.

**To Reproduce**
[Steps to reproduce the annoyance]
1. Receive a payment from an external source
2. Can't be 100% who has sent me money.

**Requested behavior**
Potentially have a name attached to the payment / the bank account if from a business account for wage payments.

I don't know if adding payment references / descriptions would also be feasible from the sender end to also add in the description too?

**Comment by xXJamieXx** [comment]
Doesn't show on phone due to limited space but if you go to a bank it shows you where its come from.
