### ISSUE TITLE
[BUG] sunrise speed 

### ISSUE THREAD

**Issue by L2unthinkable** [ParadoxGamingRP/bugs-and-suggestions#2334]
### Your Discord Name

L2unthinkable

### A clear and concise description of what the bug is

The sunrise is only driving at 105mph even tho I’ve upgraded the engine and transmission. Going slower than local cars

### Steps to Reproduce the Bug

Drive the sunrise

### Expected Behavior

I was expecting the car to drive much faster considering it was 75k

### Screenshots/Videos

Don’t have any

**Comment by Kromlec** [comment]
vehicle is tuned correctly, different lvl upgrades give different levels of performance.
