### ISSUE TITLE
[BUG] MDT wont add charges

### ISSUE THREAD

**Issue by Dez505** [ParadoxGamingRP/bugs-and-suggestions#2335]
### Your Discord Name

dez505

### A clear and concise description of what the bug is

when on cop and you are processing you put the charges in the MDT and it doesn't give you any recommended or the 20% time so you need to add everything up your self.

### Steps to Reproduce the Bug

1.  be a cop
2. arrest someone doing something stupid
3. start processing
4. charges don't add up 

### Expected Behavior

when you have charges in the MDT for it to add up 

### Screenshots/Videos

https://i.imgur.com/0qfSt1B.png

**Comment by BBstud44** [comment]
This just happened with me. It started out with it added up but after i save it then clicked on it again the recommended time/fine vanished

https://medal.tv/games/gta-v/clips/hZWDkjDpPIbAVsF-W/d1337aRvSIcQ?invite=cr-MSxDQzgsMjgwMjUyMTAs
