### ISSUE TITLE
[ENHANCEMENT] Make these flush pls

### ISSUE THREAD

**Issue by saberontop** [ParadoxGamingRP/bugs-and-suggestions#2336]
**Your Discord Name**
Fwsaber

**Describe the annoyance**
Square map and health/mic/hunger/thirst arent flush

**To Reproduce**
1. square map
2. 
3. 

**Requested behavior**
make the map flush with these so they don't overlap
**Screenshots**
![FiveM_b3095_GTAProcess_SDOuw8fKyg](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/124313620/a6974c38-6539-4581-b06a-4a32c3857aab)

**Additional context**
[Add any other context about the enhancement here]

**Comment by emeraldleo1982** [comment]
If you go in to your Display settings in city and adjust the Safezone Size, you can get it to look like the picture as a temporary fix.

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/29337315/d56e0fca-3fd9-40e8-99bb-bd73e9a1b179)
