### ISSUE TITLE
[BUG] I Crashed into an invisible building

### ISSUE THREAD

**Issue by Drunkle716** [ParadoxGamingRP/bugs-and-suggestions#2340]
### Your Discord Name

MainCharacter716

### A clear and concise description of what the bug is

There are still collisions over top Paradox Park, most likely from the building that used to be there.

### Steps to Reproduce the Bug

Fly over Paradox Park
Run into something you can't see

### Expected Behavior

Not run into something I can't see

### Screenshots/Videos

![FiveM_b3095_GTAProcess_74HV0i5m9i](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/100391224/3c09ce34-1894-435d-9b19-6604f5862b68)

### Log File

[CitizenFX_log_2024-06-04T040321.log](https://github.com/user-attachments/files/15542353/CitizenFX_log_2024-06-04T040321.log)
[CitizenFX_log_2024-06-04T040311.log](https://github.com/user-attachments/files/15542354/CitizenFX_log_2024-06-04T040311.log)
[CitizenFX_log_2024-06-04T021643.log](https://github.com/user-attachments/files/15542355/CitizenFX_log_2024-06-04T021643.log)

**Comment by CorFinn** [comment]
Heh heh heh....

Fixed next tsunami. Avoid for today.
