### ISSUE TITLE
[ENHANCEMENT] Make Terry's Boot Useful 

### ISSUE THREAD

**Issue by natashajoan** [ParadoxGamingRP/bugs-and-suggestions#2341]
**Your Discord Name**
ItsAhsatan

**Describe the annoyance**
So currently, Terry's boot you can obtain, isn't recyclable, but I have an idea. How about you use it instead, so you can search the boot and find something random in it each time, since it is Terry and the chance of finding them is rare. Maybe you find broken knives, a couple marked bills, lockpicks or other crim related objects. 

**Requested behavior**
[A clear and concise description of what you want to happen]

1. Obtain Terry's boot
2. Use in pockets "search boot"
3. Recieve random item from searching book

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by xXJamieXx** [comment]
The original intention was for it to be a cosmetic rare story item without a use really. People were asking for more random items like this for legacy sake. Not sure if I'd want to give it a practical purpose really.

**Comment by tusktheshrew** [comment]
Make it more Rare please. So that we have to get pairs.
