### ISSUE TITLE
[BUG] Opening Contacts for New People causes a Fatal Error

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#2346]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

New person flys in, they open their contacts, and they get a fatal error and they fly out and fly back in.

### Steps to Reproduce the Bug

1. Fly in first time
2. Get phone
3. Open phone contacts far right tab.

### Expected Behavior

No Fatal Error occured.

### Screenshots/Videos

N/A

**Comment by lPrestonl** [comment]
Any logs would be useful, or even a picture of this.

**Comment by tusktheshrew** [comment]
I was trying to help two people and they kept getting the same error over and over. I made the bug report for them.

**Comment by tusktheshrew** [comment]
i will try to get the picture for you.

**Comment by tusktheshrew** [comment]
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/98053772/4fa26640-c233-4f51-8dcd-6f1452ad6316)
