### ISSUE TITLE
[BUG] Locking vehicle

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#2348]
### Your Discord Name

ssara

### A clear and concise description of what the bug is

When you lock the car you end up in a loop of locking car emote. 

### Steps to Reproduce the Bug

Have a vehicle or keys
Lock said vehicle
Do the emote for infinity

### Expected Behavior

Not end up in the infinity loop

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/98127638/a759769a-4e75-4894-ad4a-ec5429b738f2)

**Comment by emeraldleo1982** [comment]
Can confirm on my end too, I keep pressing the keyfob over and over but it do nothing like the batteries are dead until i flex "Cancel Action" and lock it again. Only happens sometimes, not sure what triggers it yet.
