### ISSUE TITLE
[BUG] Chop shop bug

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#2353]
### Your Discord Name

jojosnmustard

### A clear and concise description of what the bug is

Took a car in to be salvaged for spare parts, but the guy decided he didn't want to I guess. It's been working fine up until so I'm not sure what changed or if this is a one-off thing.

### Steps to Reproduce the Bug

1: Find target car for Chop Shop
2: Take to chop shop
3: Enter Chop Shop
4: No choppy

### Expected Behavior

Chop shop let's you scrap the target vehicle.

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/29337315/ca2f4703-8105-4a3b-b44d-3b1f98adf4b0)

### Extra Notes (Optional)

I got that above picture for log output.

**Comment by xXJamieXx** [comment]
Hard to tell where the issue is here. Can you break off the parts but not hand them in? Can you not break off the parts? What car was it? Gotta provide the right info so it can be reproduced...

**Comment by emeraldleo1982** [comment]
IIRC I didn't get any 3rd eye options to remove the parts. I'll double check here in a bit and update.

**Comment by emeraldleo1982** [comment]
It seems to be working normally now, except for the 2 guys spawned inside each other but I assume that's what the qb delete commit was about for the chop shop.
