### ISSUE TITLE
[BUG] New crop recipes not available

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#2355]
### Your Discord Name

jojosnmustard

### A clear and concise description of what the bug is

Checked the cutting plank/food process and the new recipes for the cocoa, coffee, and fabric, are not available.

### Steps to Reproduce the Bug

1: They're not here!?

### Expected Behavior

1: They're here!!

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/29337315/fc6d4145-a40d-41e7-9101-340b7fbc176f)

### Log File

No Log Output

**Comment by Bac0nRamen** [comment]
What crafting bench is this?

**Comment by Bac0nRamen** [comment]
Figured it out next restart
