### ISSUE TITLE
[BUG] financing Paytime time left depleting too quick

### ISSUE THREAD

**Issue by NataliaGallo96** [ParadoxGamingRP/bugs-and-suggestions#2357]
### Your Discord Name

Carebear#9564

### A clear and concise description of what the bug is

Bought a Draugur around14 hours ago (real time) and maybe spent 4 hours in city and my payment playtime is 13 hours. i believe the payment time left is calculating the actual time since i bought it instead of the amount I spent in city. not sure if this effects other cars. 

### Steps to Reproduce the Bug

1. buy draugur
2. log off 
3. wake up a few hours later 
4. playtime is drastically low based on real life time

### Expected Behavior

1. buy draugur
2. log off 
3. wake up a few hours later 
4. payment time left is calculated based on playtime

### Screenshots/Videos

![FiveM_b3095_GTAProcess_iulHcsGiL3](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/123715929/fa4cff3d-1b29-4181-9985-f184744c6de7)

**Comment by xXJamieXx** [comment]
If you don't close the app and re-open it, it wont update.

**Comment by emeraldleo1982** [comment]
That's the thing, I do that, because it works that way with ever app.

**Comment by xXJamieXx** [comment]
Oh it also only updates on switching characters, disconnecting or making a payment.

**Comment by JnKTechstuff** [comment]
The app will now bring into consideration your current playtime to update the timer. So will the finance menu at the bank
