### ISSUE TITLE
[BUG] Manual Transmission Not Working

### ISSUE THREAD

**Issue by ColKing** [ParadoxGamingRP/bugs-and-suggestions#2358]
### Your Discord Name

Colt__

### A clear and concise description of what the bug is

Install a new manual transmission into the engine. The manual transmission stays in the car; however, when you park it and pull it back out it states that manual transmission is false within the F8.  Another thing tho is the only car so far these haven't worked in is the Pfister Comet Callista and Karin Sultan RS V8.   

### Steps to Reproduce the Bug

1. install manual transmission 
2. put motor back into car
3. states that the manual is true in F8
4. park car 
5. Pull car back out and F8 should state that manual transmission is true

### Expected Behavior

Install Manual Engine and Manual engine work after being parked 

### Screenshots/Videos

https://cdn.discordapp.com/attachments/1008943625339682816/1248378722004893760/image.png?ex=666372c9&is=66622149&hm=6137b40793db708f9a96ca3efff81f6919ed54ff9bb69f76ace4900dd7c36aa5& 
This is putting the Engine in 

https://cdn.discordapp.com/attachments/1008943625339682816/1248379268728094740/image.png?ex=6663734b&is=666221cb&hm=a88d273f506bf2e810ef0f19ece985ec4be73cd3ab6b8c63e4fe27ed37e07799& 
This is after taking it out of the parking spot

**Comment by JnKTechstuff** [comment]
Fixed
