### ISSUE TITLE
[BUG] This fabric smells funny

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#2365]
### Your Discord Name

jojosnmustard

### A clear and concise description of what the bug is

Went to check on my Cutting Plank to see if I could figure out how to make fabric from cotton, the only way I found to get it to hold together was with egg whites. I'm not sure I'm doing this right, cotton stuck in ceiling fan.

### Steps to Reproduce the Bug

1: Check cutting Plank
2: Fabric requires eggs
3: Fabric requires eggs!?!?

### Expected Behavior

Not need eggs for fabric.

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/29337315/f5ff67b3-7b93-40f8-b2af-8c1ab8535feb)

There's also this little issue, I can't figure out what I need to make cocoa mass.
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/29337315/ebac5ad2-9fd3-45c1-9c53-417b08413b81)

### Extra Notes (Optional)

Coffee grounds work fine.

**Comment by JnKTechstuff** [comment]
Fixed
