### ISSUE TITLE
Vehicle payments

### ISSUE THREAD

**Issue by ZOIMBIE3** [ParadoxGamingRP/bugs-and-suggestions#2368]
### Your Discord Name

zoimbie.

### A clear and concise description of what the bug is

When making the max payment on your vehicle it will not go though unless you use the payoff vehicle tool.

### Steps to Reproduce the Bug

1. Make max payment without using payoff vehicle tool
2. Payment will come out of your account
3. Payment will not go though
4. You will still ow the same amount on the vehicle

### Expected Behavior

Payment not to go though but to come out of your account when making max payment without using payoff vehicle tool. 

### Screenshots/Videos

https://r2.fivemanage.com/images/DEOsDKOaK3eF.png

**Comment by JnKTechstuff** [comment]
Fixed
