### ISSUE TITLE
[BUG] /transfercrpyto no working

### ISSUE THREAD

**Issue by baxepw** [ParadoxGamingRP/bugs-and-suggestions#2371]
### Your Discord Name

baxe666

### A clear and concise description of what the bug is

No longer able to /transfercrypto id amount. Unless it has changed and we are unaware

### Steps to Reproduce the Bug

1. Try to /transfercrypto
2. No crypto transferred 

### Expected Behavior

1. Try  /transfercrypto
2. Crypto transferred

### Screenshots/Videos

a

**Comment by Bac0nRamen** [comment]
Should be fixed already
