### ISSUE TITLE
[BUG] Manual Transmission

### ISSUE THREAD

**Issue by ColKing** [ParadoxGamingRP/bugs-and-suggestions#2378]
### Your Discord Name

Colt__

### A clear and concise description of what the bug is

Manual Transmission is installed in car and reads true in F8 console. However, it auto shifts the car. 

### Steps to Reproduce the Bug

1. Get in car with manual transmission 
2. Drive to first gear and should redline
3. Shift to next gear 

### Expected Behavior

You should be able to manually shift gears instead of it auto shifting 

### Screenshots/Videos

https://cdn.discordapp.com/attachments/1008943625339682816/1249820884550553772/image.png?ex=6668b1e7&is=66676067&hm=70b50f18c6aa2f33d972afd78eda08c7affe898e0e03fa04437bbd0e1adcc2d4&

**Comment by xXJamieXx** [comment]
Duplicate of #2370
