### ISSUE TITLE
[ENHANCEMENT] Make the Sunrise Great Again.

### ISSUE THREAD

**Issue by sukcurr** [ParadoxGamingRP/bugs-and-suggestions#2381]
suckurr#8985

The Sunrise is probably the slowest car in the server, please.

**To Reproduce**

1. Buy a Sunrise
2. Buy the performance upgrades from Bennys/Turbo
3. Drive the car, watch it struggle to go 105mph.

**Requested behavior**
[It is a rally sports car, it should not have any issue with all the upgrades hitting the top speeds of most civ cars in the server. The car is expensive as it is, with the upgrades I'm not sure why its not equal to its counterparts. ]

**Comment by Kromlec** [comment]
the car will go faster than 105. Bennies isn't the only upgrades out there.
