### ISSUE TITLE
[BUG] Personal Vehicle still gets impounded when going into interiors

### ISSUE THREAD

**Issue by ImPaulYo** [ParadoxGamingRP/bugs-and-suggestions#2385]
### Your Discord Name

imcarbon_yo

### A clear and concise description of what the bug is

yesterday when i went into reds clinic, i came out and my personal vehicle was gone and not F1 returnable. today i went into weed processing and my car was impounded again and not F1 returnable. last report was closed saying as long as i have keys, i can use F1. this still isnt reliable. but if i drive a local car ive stolen the car is F1 returnable. $400 impound each time on this new economy is a good chuck of money.

### Steps to Reproduce the Bug

1. park personal vehicle outside of interior
2. go in
3. come out and use f1 where car was parked

### Expected Behavior

tio be able to return my car, not only some-times but all the time. 

### Screenshots/Videos

N/A

### Extra Notes (Optional)

N/A

**Comment by xXJamieXx** [comment]
Let us know if this is still occurring after the recent changes.
