### ISSUE TITLE
[BUG] Swaps Not Working Due too Jackstands

### ISSUE THREAD

**Issue by ColKing** [ParadoxGamingRP/bugs-and-suggestions#2386]
### Your Discord Name

Colt__

### A clear and concise description of what the bug is

Every step to ordering a engine works, however, when it gets delivered with the new prop system, jackstands now drop the engine when you pick up the jackstand. Which causes the swap engine and normal engine to not be looked into anymore. 

### Steps to Reproduce the Bug

1. Order engine from laptop
2. Grab Jackstand and take out engine from car and move to the side
3. Grab new jackstand and pick up swapped engine 
4. Move jackstand with new swapped engine to the car
5. Install swapped billet parts and install new parts
6. Reinstall the engine into the car and check that engine sound works after parking 

### Expected Behavior

Expected behavior is that with I lift up the engine off the ground with a jackstand. Next is to pickup the jackstand with the engine hooked and move it to the car without it falling off the jackstand. 

### Screenshots/Videos

None

**Comment by kevstax** [comment]
This also affects normal engines when trying to move them it drops it.
