### ISSUE TITLE
[BUG] <short description>

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#2387]
### Your Discord Name

ssara

### A clear and concise description of what the bug is

crimes are a bit on the heavier side atm. lowjacks poppin off every 8-10 min, 

### Steps to Reproduce the Bug

be on cop
be overwhelmed

### Expected Behavior

have the right amount of calls for the units thats on

### Screenshots/Videos

https://r2.fivemanage.com/images/rLhBNWFZIx4x.png
https://r2.fivemanage.com/images/M6dRSiqR1YYo.png
https://r2.fivemanage.com/images/4atlEopJ5pdn.png

**Comment by BrotherDayZ** [comment]
Dont change a thing. You dont have to respond to every single call. Id rather have 30 calls to go to and choose which one to go to than wait around for something to happen. Let crims get some free crime done sometimes
