### ISSUE TITLE
[BUG] Schlagen GT missing upgrades

### ISSUE THREAD

**Issue by BigManBehavior** [ParadoxGamingRP/bugs-and-suggestions#2388]
### Your Discord Name

barelykaizen

### A clear and concise description of what the bug is

So not sure if it is bug is the right word but unsure what would be in all honesty, with it being a base GTA car and having customization already, for whatever reason none of that is available.

It is missing both cosmetics and performance upgrades.

Typically this car would have spoilers, liveries, other random things. But it seems to have none of those things anymore. However pre-wipe it did have them. Even the window tint doesn't actually work. These options are no longer even there, even performance mods are gone. Tint option is still there but does not change anything.

### Steps to Reproduce the Bug

1. Bug/Finance a Schlagen GT
2. Go to any shop anywhere
3. Become sad because everything is missing.

### Expected Behavior

I assumed it would have all the things it did pre wipe. However it has less than even most motorcycles now.

### Screenshots/Videos

ALL OPTIONS
https://gyazo.com/dd602b0072f48293c50e36ae0f672512

TINT APPLIED BUT NOT WORKING
https://gyazo.com/0b6e1a8cb997a949d3bbf3f4ae7815e0

### Extra Notes (Optional)

Just unsure if this was intended or what because you do pretty much nothing to this vehicle now.

### Log File

Unrelated but here.

[CitizenFX_log_2024-06-14T192200.log](https://github.com/user-attachments/files/15844413/CitizenFX_log_2024-06-14T192200.log)

**Comment by Kromlec** [comment]
seemed to be a modkit id mixup, fixed in dev!
