### ISSUE TITLE
[ENHANCEMENT] Moonshine

### ISSUE THREAD

**Issue by Dr3w5ski** [ParadoxGamingRP/bugs-and-suggestions#2389]
**Your Discord Name**
[drew6910]

**Describe the annoyance**
[Moonshine cost around 15k to start up. 5k for the still, 2500 for the water tank, and 500 for each moonshine mix. plus the watering can and the wood you have to buy to keep the fire going. It takes 1 hour and for the moonshine to fully brew. You have to sit there and tend to the fire and keep supplying water. So you really can't leave it unattended. You can only brew 10 at a time but its really not worth it due to the price you sell to the locals. The locals prices vary but 1 usually goes for 450-550. The locals may ask for 2 which vary as well but the highest ive seen is 1100 for 2. So in all it is really not worth it because the moonshine mix is 500 and when you brew it for an hour your pretty much just getting your money back or maybe even less than what you payed for the moonshine mix.]

**To Reproduce**
[Steps to reproduce the annoyance]
1. Buy all materials needed to brew
2. Brew the moonshine and tend to it
3. Sell to locals for the same price you payed for the mix

**Requested behavior**
Either lower the prices of moonshine mix or the locals buy them for more

**Screenshots**
https://cdn.discordapp.com/attachments/1126282991061172357/1251337651882168382/image.png?ex=666e3680&is=666ce500&hm=9cc578b97bfe26aa379db2857765fdcbf4904d92e92451d6f8786055a93ab906&

**Additional context**
[Add any other context about the enhancement here]

**Comment by tusktheshrew** [comment]
Moonshine when I was taught was never a local thing, it was more of an RP item to meet and drink with other people.

**Comment by Bac0nRamen** [comment]
Adjusted shop prices let me know if it needs more attention
