### ISSUE TITLE
[BUG] collisions at Sandy PD

### ISSUE THREAD

**Issue by Dez505** [ParadoxGamingRP/bugs-and-suggestions#2391]
### Your Discord Name

dez505

### A clear and concise description of what the bug is

at sandy PD there's an invisible wall in the middle of the cells hallway that makes it hard to have a shoot out in. theres also smaller collisions in the sandy PD motor pool.

### Steps to Reproduce the Bug

1. be at sandy pd
2. try and shoot in the cells hallway
3. bullets get stopped in mid air

### Expected Behavior

for there not to be a invisible wall

### Screenshots/Videos

https://r2.fivemanage.com/images/PV88wl0NA11f.png

**Comment by CorFinn** [comment]
Fixed in dev. Sent to team for push to Live.

**Comment by Bac0nRamen** [comment]
Next restart/Update
