### ISSUE TITLE
[ENHANCEMENT] Comet S2

### ISSUE THREAD

**Issue by omelette44** [ParadoxGamingRP/bugs-and-suggestions#2392]
greasy44

Comet S2 is in need of some TLC for the price point of 90k+ (At Kildares) and for the car it represents I believe it needs a buff either handling, speed or both honestly would love to see this car more usable and competitive. It's similar to where it was before the update if not worse and after running some tests against an RH5, which is _not_  a top car, and also racing it against people, it falls behind massively compared to others.

Drive Comet S2, be sad.

For the Comet S2 to have perhaps better acceleration, or perhaps better handling as it suffers from wheelspin even for the slower speeds its doing. 

I have driven this car a lot throughout the entirety of 3.0 and would love to finally race it properly.  :)

**Comment by omelette44** [comment]
After some more in depth testing, figured out that some better acceleration and brakes could help significantly .

**Comment by Kromlec** [comment]
made some tweeks that should be live tomorrow.

**Comment by Bac0nRamen** [comment]
Next restart/Update
