### ISSUE TITLE
[BUG] Hunting DNR bug

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#2393]
### Your Discord Name

jojosnmustard

### A clear and concise description of what the bug is

Pulled out my rifle, found the marked animal (nice touch on the blue marker btw) Shot it dead, but when I tried to harvest it I was met with "This animal has been tagged by the DNR, you cannot harvest it". I triple confirmed it was the right animal, so I moved on and tried again, only now when I pull out my rifle there's no more animals.

### Steps to Reproduce the Bug

1: Shoot proper animal
2: Can't skin
3: Can't continue hunting

### Expected Behavior

1: Kill Marked Animal
2: Be able to skin it
3: Continue pillaging the wildlife

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/i4ILVfbmojEMhcNRr/d1337iRqwgmt?invite=cr-MSxTeXIsMTUzNDM4NTc5LA

### Log File

No log output

**Comment by emeraldleo1982** [comment]
Update: Post Tsunami on 6/15 I tried again and it seems to work-ish, I was able to skin an animal it had a larva infestation though rip, then I was able to get 1 more animal to spawn. After skinning the 2nd animal no more will spawn in the area.

**Comment by NOVAH3X** [comment]
2nd this report. Got 2 to skin. 3rd to spawn was marked DNR. Waited 20mins in same area no respawn and green blip on DNR animal stayed. Moved a few miles away to hunt elsewhere and nothing will spawn. Put away and took out rifle a few times but wont refresh hunting spawner

**Comment by TeddyNM** [comment]
Adding to this. Shot the correct deer as it had the blue marker over it and was the one shown on the map but when I tried to skin got the DNR notice. After that one deer I couldn't get anything to spawn even with changing areas and logging out and back in. Couldn't get another until I completely restarted the game and same issue shot the correct animal, DNR notice and couldn't get another spawn after that. 
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/97271676/b50dba66-4c9d-4094-bc02-d635e69bd647)
![hunting](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/97271676/f928eb4a-6f8b-4bac-b14c-aee1223dd40d)
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/97271676/04392b1a-c72e-4205-b473-b3c169e9b672)
[CitizenFX_log_2024-06-17T231137.log](https://github.com/user-attachments/files/15878302/CitizenFX_log_2024-06-17T231137.log)
