### ISSUE TITLE
[BUG] Car staying way after falling asleep.

### ISSUE THREAD

**Issue by Martyfly200** [ParadoxGamingRP/bugs-and-suggestions#2394]
### Your Discord Name

Martyfly2005

### A clear and concise description of what the bug is

So I had left a vehicle at Alta last night and drove up to paleto and went to sleep. Woke up this morning and came back to alta and was able to respawn it.

### Steps to Reproduce the Bug

leave a vehicle
come back the next day and its there.

### Expected Behavior

it would be gone by then.

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/116933716/937d3b06-e8a9-4281-980d-e71ebcf28882)

**Comment by xXJamieXx** [comment]
If thats where you left it, thats where you left it, seems like its working as intended to me?
