### ISSUE TITLE
[BUG] Crab Pot

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#2395]
### Your Discord Name

jojosnmustard

### A clear and concise description of what the bug is

Found one of the crab pots at the shop and decided to tinker with it, can't figure out if it actually does anything though. Also can't seem to wrap my mind around what it looks like. Tried using it in deep and shallow water with the same results.

Missing Icon Imagery
Using it while in water doesn't do anything
Dropping it in the water doesn't do anything it seems
Trying to open it doesn't do anything

### Steps to Reproduce the Bug

1: Crab machine broke

### Expected Behavior

Be able to attract cute crab with Crab Pot

### Screenshots/Videos

N/A

### Log File

No Log Output

**Comment by Darahz** [comment]
This is not yet live :)
