### ISSUE TITLE
[BUG] Headpopsss

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#2396]
### Your Discord Name

ssara

### A clear and concise description of what the bug is

I always headpop at the same location up at Zancudo. Don't know what it is, doesnt matter what character. Always up here.

### Steps to Reproduce the Bug

Be there
Pop

### Expected Behavior

Be there
Not pop

### Screenshots/Videos

https://r2.fivemanage.com/images/2yT0hlbrD9vm.jpg

### Log File

[popafter.txt](https://github.com/user-attachments/files/15855528/popafter.txt)

**Comment by Bac0nRamen** [comment]
Fixed next restart I hope
