### ISSUE TITLE
[BUG] House was Already Searched

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#2400]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

When into house and came out with nothing, everything was already searched before I even got here.

### Steps to Reproduce the Bug

1. Get house after watching a person do a house
2.  Lockpick in
3. Search House
4. Go home with nothing

### Expected Behavior

A new house instanced.

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/98053772/88174cad-8dce-4342-acd5-e505edf36440)
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/98053772/803e8f5c-e632-424f-82b1-7a125fc58b02)

**Comment by Martyfly200** [comment]
Would like it say this is still an issue, just hit one today and it said Already searched.

**Comment by xXJamieXx** [comment]
Pushed some changes which might resolve this, check after restart today.
