### ISSUE TITLE
[BUG] turbo disappearing from my cars

### ISSUE THREAD

**Issue by tof-tof69** [ParadoxGamingRP/bugs-and-suggestions#2403]
### Your Discord Name

toftof

### A clear and concise description of what the bug is

a few days after getting turbo installed at bikinis i visited NS tuning to fix my car and after fixing it it appeared that my car doesn't have a turbo

### Steps to Reproduce the Bug

1- get turbo at bikinis
2- wreck car and get it fixed at NS tuning
3-turbo is gone from the car

### Expected Behavior

for the turbo to remain in my car

### Screenshots/Videos

none

### Extra Notes (Optional)

Olivia was the mechanic who installed turbo in my cars at bikini, 
a paragon (license plate: 4RC629LE)  and a cinquemila (license plate: SYN TOF)
and squeak was the mechanic who fixed my car at NS and found out that it didn't have a turbo

**Comment by SaraLef** [comment]
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/98127638/7619141a-aa91-4ad6-bead-4ec67ede3a59)
Proof of installment

**Comment by xXJamieXx** [comment]
Open a new bug report is this happens again.
