### ISSUE TITLE
[BUG] Hurt

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#2405]
### Your Discord Name

ssara

### A clear and concise description of what the bug is

The bleeding effect pops up when changing oufits at kildares.

### Steps to Reproduce the Bug

Change at Kildares
Start to bleed

### Expected Behavior

Change at kildares
Work as normal

### Screenshots/Videos

N/A

**Comment by tusktheshrew** [comment]
this also happens sometimes for the people changing at the Tuning Shop.

**Comment by natashajoan** [comment]
Also happens at G&G.

**Comment by BBstud44** [comment]
Also happens at our HQ. It seems to be an everywhere issue

**Comment by xXJamieXx** [comment]
Duplicate of #2296
