### ISSUE TITLE
[BUG] The new vehicle spawning 

### ISSUE THREAD

**Issue by omelette44** [ParadoxGamingRP/bugs-and-suggestions#2408]
### Your Discord Name

greasy44

### A clear and concise description of what the bug is

Car didn't load mods and is unable to be stored back into garage.

### Steps to Reproduce the Bug

Take car out garage
Park it
Take car back out of garage

### Expected Behavior

For my car to appear

### Screenshots/Videos

![Screenshot_249](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/131989733/f3b1b245-5f19-4f6a-9f1c-fd51cba3205c)

### Extra Notes (Optional)

- I didn't take it out quickly so i don't think you need to take the vehicle out twice ( like mentioned in steps to reproduce bug) that's just what i did.

- picture is related to when I try to park the car 

### Log File

[CitizenFX_log_2024-06-17T180545.log](https://github.com/user-attachments/files/15875318/CitizenFX_log_2024-06-17T180545.log)

**Comment by Bac0nRamen** [comment]
Make a modmail to fix ur mods if need be. All other issues was fixed
