### ISSUE TITLE
[BUG] dont get keys

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#2409]
### Your Discord Name

ssara

### A clear and concise description of what the bug is

pulling the slurp truck doesnt give you keeys

### Steps to Reproduce the Bug

pull out truck
get no keys

### Expected Behavior

get keys

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/98127638/a7a618c7-6cb0-4d4d-917b-cf1165b4e247)

**Comment by Bac0nRamen** [comment]
was fixed last restart. Make a modmail to get ur mods fixed if u have any missing
