### ISSUE TITLE
[BUG] Owned Cars being reverted to Stock/Key Delay

### ISSUE THREAD

**Issue by NOVAH3X** [ParadoxGamingRP/bugs-and-suggestions#2410]
### Your Discord Name

NOVA_H3X (Blaze Plissken)

### A clear and concise description of what the bug is

After the server restarts, loaded in. Pulled out my Truck. waited a minute and the truck appeared as stock. Did not recieve keys until about 1 minute later. Checked at Bennys and all mods, cosmetic and performance have been removed.

Returned to Alta, Pulled out my RH5 and same result. No mods and keys were delayed. Checked at Bennys and reverted to stock as well. 

### Steps to Reproduce the Bug

1. Wake Up
2. Go to Garage
3. pull out Vehicle
4. No Mods
5. Get Out of Vehicle
6. Try to re enter Vehicle, "Door is Locked"
7. Press L key. "You do not have keys for this vehicle"
8. Mash L key some more, Door Unlocks, "You have recieved Keys"

### Expected Behavior

1. Wake Up
2. Go to Garage
3. pull out Vehicle
4. Have Nice Day

### Screenshots/Videos

N/A

### Log File

[CitizenFX_log_2024-06-17T191540.log](https://github.com/user-attachments/files/15876248/CitizenFX_log_2024-06-17T191540.log)

**Comment by Bac0nRamen** [comment]
reach out in modmail to get ur mods fixed/
