### ISSUE TITLE
[BUG] Coke Lab

### ISSUE THREAD

**Issue by SamB1997** [ParadoxGamingRP/bugs-and-suggestions#2411]
### Your Discord Name

ayupdave

### A clear and concise description of what the bug is

Coke lab is unable to be taken rn. Once you breach the lab (I think the timer for the hack should be extended about 5-10 more seconds as its really hard rn) you cant take it. You can rekey it unlimited times but you cant actually claim the lab. 

### Steps to Reproduce the Bug

1. thermite lab
2. rekey lab
3. Nothing

### Expected Behavior

Be able to claim lab once it rekeys

### Screenshots/Videos

N/A

**Comment by Bac0nRamen** [comment]
I know multiple people who been using the labs past couple days and its been working. SO might of been just that day. If u get more issues or info just make a new report
