### ISSUE TITLE
OH HONEY HONEY

### ISSUE THREAD

**Issue by TeddyNM** [ParadoxGamingRP/bugs-and-suggestions#2412]
**Your Discord Name**
TeddyMercury

**Describe the annoyance**
I just can not seem to eat this delicious honey and would love to do so! 
**To Reproduce**
[Steps to reproduce the annoyance]
1. Try to put honey is mouth
2. Unsuccessful
3. Be Sad 

**Requested behavior**
I just want honey to be consumable so that it can become a more useful item than just taking it to the bee guy and hopefully inspire more rp around it 

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
Please Chris do this for your favorite HR manager :D

**Comment by emeraldleo1982** [comment]
It does look pretty tasty. Maybe someone will have a tasty beverage made with it or something ;)
