### ISSUE TITLE
[BUG] Cocaine

### ISSUE THREAD

**Issue by Terrylaughlin35** [ParadoxGamingRP/bugs-and-suggestions#2415]
### Your Discord Name

imtwobigdawg35#3143

### A clear and concise description of what the bug is

Turn the wet bring into a packaged brick. if you open this as soon as it is supposed to turn the wet brick into the packaged it will allow you to pull out the wet one as well as give you the packaged one. 

### Steps to Reproduce the Bug

1. wait for wet brick to get packaged
2. as soon as it completes pull out wet brick
3. open it back up and get packaged brick

### Expected Behavior

to not have a wet brick

### Screenshots/Videos

N/A

### Log File

[drugs.txt](https://github.com/user-attachments/files/15880222/drugs.txt)

**Comment by xXJamieXx** [comment]
You can't open it while its processing though?

**Comment by Terrylaughlin35** [comment]
so in the last 5 seconds keep opening the thing and the second it says complete you can open it and the wet brick is in there. you can pull it out then open it back up and pull the final product out as well
