### ISSUE TITLE
[BUG] assassination job bug

### ISSUE THREAD

**Issue by tof-tof69** [ParadoxGamingRP/bugs-and-suggestions#2416]
### Your Discord Name

toftof

### A clear and concise description of what the bug is

after picking an assassination target and taking the hostage and chopping them on the table you cant use the door to leave

### Steps to Reproduce the Bug

1- get a assassination mission
2- hit the target with your car and take them hostage
3- take them to room at postal 72 and place them on the table and take the trophy
4- third eye the door to try and leave but theres no option

### Expected Behavior

to be able to leave

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/i5VgKnSB68WIV08Mq/d13372lBKkeZ?invite=cr-MSxaQjksMjE5NjI3ODc2LA

**Comment by Bac0nRamen** [comment]
This still a issue?
