### ISSUE TITLE
[BUG] Bullet Proof Windows On The Buffalo STX

### ISSUE THREAD

**Issue by Skeletal-KC** [ParadoxGamingRP/bugs-and-suggestions#2418]
### Your Discord Name

skeletal_kc

### A clear and concise description of what the bug is

The old issue of the Buffalo STX having bullet proof windows has come back again apparently.

Makes no difference with or without the cosmetic plating on the side

### Steps to Reproduce the Bug

1. Get Buffalo STX
2. Shoot at Windows
3. Zero Penetration

### Expected Behavior

Windows probably shouldn't be bullet proof

### Screenshots/Videos

![Screenshot (911)](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/122247151/42aa9578-0b3e-42fe-9fce-b5977053d410)
![Screenshot (912)](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/122247151/a1894270-9729-4786-9242-69c020dbe544)

**Comment by Kromlec** [comment]
This is a known issue and being watched by staff for abuse. Not an easy fix for this car.
