### ISSUE TITLE
[ENHANCEMENT] Sentinel SG4

### ISSUE THREAD

**Issue by BjornK22** [ParadoxGamingRP/bugs-and-suggestions#2427]
**Your Discord Name**
Blitzd11

**Describe the annoyance**
Suspension needs softened badly due to it bouncing everywhere going over the smallest bumps. Acceleration is lackluster and should a bit better to compete with cars in its price range. More cars need the same suspension cars like the paragon, comet sr, or even the callista have. 

**To Reproduce**
[Steps to reproduce the annoyance]
1. 
2. 
3. 

**Requested behavior**
To be able to drive my car with way softer suspension so the cars isnt bouncing everywhere over curbs and bumps. Smooth rides are the best rides.
**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by Kromlec** [comment]
installed new coil overs all the way around. should ride much better now.
