### ISSUE TITLE
[ENHANCEMENT] Chop Upgrade shop

### ISSUE THREAD

**Issue by kevstax** [ParadoxGamingRP/bugs-and-suggestions#2428]
KevStax
[Enter your Discord name]

**Describe the annoyance**
so the car part upgrade place was moved and us Nismos have been looking for it for hours a day since the day it has been moved. most of us have looked over the majority of the city multiple times and are probably just blind and can not see it however it is becoming tiring. We were wondering if there was a way to make it so there is like a scavanger hunt to find it. Maybe you talk to a guy and he will send you notificaitons when searching if you are warmer or colder to finding the spot. I understand it has only been a few days but that's just our thoughts on it.

**Comment by xXJamieXx** [comment]
Just a misunderstanding. Should be good to find after restart.
