### ISSUE TITLE
[BUG] Repo notification

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#2431]
### Your Discord Name

jojosnmustard

### A clear and concise description of what the bug is

got a vehicle up for repo but the notification never goes away on the phone, making it impossible to see the top part of my phone icons, so now my vehicle and my phone are at risk if I don't make the payment lol

### Steps to Reproduce the Bug

1: Finance stuff
2: Be poor
3: Lose phone rights to 1/3rd of my phone

### Expected Behavior

Maybe a recurring reminder that a vehicle is up for repo.

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/29337315/698ba990-c8fe-40ea-88b7-e91e596aae45)

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/29337315/00b1a5f6-f13c-45cd-b7c0-07457aa70de8)

**Comment by Kromlec** [comment]
So we had it being intrusive so people can't say they didn't see it. But you can click the message and it will go away until you fly in again.

**Comment by emeraldleo1982** [comment]
Oh perfect, good to know thank you :)
