### ISSUE TITLE
[BUG] Bottom Ems text not showing up 

### ISSUE THREAD

**Issue by Martyfly200** [ParadoxGamingRP/bugs-and-suggestions#2435]
### Your Discord Name

Martyfly2005

### A clear and concise description of what the bug is

Cant see the airlift text or call for ems at the bottem of the screen might not be for everyone.

### Steps to Reproduce the Bug

Die and nothing shows up 

### Expected Behavior

for there to be the proper text to airlift at the bottom center of the screen

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/116933716/afa49366-eede-4971-9deb-03c679ddc618)

### Log File

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/116933716/13cc6147-b8b5-432e-8d63-bc15447e8c6a)

**Comment by Darahz** [comment]
The "error" is a phone thing. Are you experiencing this still? Cuz i think this was a one off thing
