### ISSUE TITLE
Buying/Financing a car issues

### ISSUE THREAD

**Issue by Malfoo** [ParadoxGamingRP/bugs-and-suggestions#2437]
### Your Discord Name

Malfo#2515

### A clear and concise description of what the bug is

When buying or financing a car it is giving you a local vehicle and not the vehicle you bought or financed, and if you go to impound it does not pull out your car.

### Steps to Reproduce the Bug

Buy or finance a vehicle look at plate given then look at the plate of the car you actually own

### Expected Behavior

Be given the correct owned vehicle

### Screenshots/Videos

Car given when I pressed financed at Kildares https://r2.fivemanage.com/images/h2jfvGUwFA7H.png
The actual car https://r2.fivemanage.com/images/b4vN90XcHenC.png
Car I was given when pulling from impound https://r2.fivemanage.com/images/3KGDQrxdK0Vd.png

**Comment by Bac0nRamen** [comment]
Think this was fixed?
