### ISSUE TITLE
[BUG] NS Tunning Hoist

### ISSUE THREAD

**Issue by jkaejkae888** [ParadoxGamingRP/bugs-and-suggestions#2451]
### Your Discord Name

jkaejkae888

### A clear and concise description of what the bug is

We can't pull out hoists to open NS tunning

### Steps to Reproduce the Bug

Press the button nothing shows except an f8 script error

### Expected Behavior

Hoist spawns

### Screenshots/Videos

https://imgur.com/tDCHrTE

**Comment by xXJamieXx** [comment]
Fixed in live.

**Comment by jkaejkae888** [comment]
it works
