### ISSUE TITLE
[BUG] House robbery

### ISSUE THREAD

**Issue by hacklv** [ParadoxGamingRP/bugs-and-suggestions#2452]
### Your Discord Name

gvido_b

### A clear and concise description of what the bug is

the house robberies are broken at least for me  because in 2 days iw done around 5-10 houses and iw gotten 70% of 1 house empty rest of it has been nothing good 

### Steps to Reproduce the Bug

1 get a lockpick 
2 go to the house 
3 brake in 
4 see as the most of the house turns out empty 

### Expected Behavior

gettin at least half of the house whit some sort of stuff it might be bad or good but at least half and same goes for the big houses

### Screenshots/Videos

https://cdn.discordapp.com/attachments/1028083496671002635/1254487385484427304/image.png?ex=6679abeb&is=66785a6b&hm=5cdb83d136bb6f61532bc41a2ab409657ae298adf0431e5338e6b094f03aea53&

### Extra Notes (Optional)

i know this might just be a skill issue as some people would say but i know some other people that has had the same issues whit houses as i haw

**Comment by jkaejkae888** [comment]
I find the high end houses have a much higher chance to get empty stuff my last 3 high end houses I got over 4,5 empty stuff

**Comment by xXJamieXx** [comment]
Fixed in live.
