### ISSUE TITLE
[BUG] Slurptruck doesnt always give keys

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#2455]
### Your Discord Name

ssara

### A clear and concise description of what the bug is

When taking the truck out you sometimes get the truck but no key

### Steps to Reproduce the Bug

Pull out truck
Don't get keys.
Lockpick truck

### Expected Behavior

Pull out truck
Get keys

### Screenshots/Videos

N/A

**Comment by Bac0nRamen** [comment]
Duplicate of #2433
