### ISSUE TITLE
[ENHANCEMENT] Jester rr/gpr

### ISSUE THREAD

**Issue by omelette44** [ParadoxGamingRP/bugs-and-suggestions#2456]
greasy44

Same car one just has a wide body and a slightly smaller price tag, would love to see the perform similar at least, one is a top competitor within the racing and also for any getaway while the other struggles at 90mph (would like this to perform like the other).

(widebody one is slow) 
![Screenshot_269](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/131989733/08a5ab70-9ed3-438a-b518-1617160d9b16)
![Screenshot_270](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/131989733/e261cc30-b44e-47b7-bd33-39bee8e63d6e)

**Comment by Kromlec** [comment]
made some tweaks to the GPR, will be live tomorrow.

**Comment by omelette44** [comment]
thank you
