### ISSUE TITLE
[BUG] NS Tuning bennys discount

### ISSUE THREAD

**Issue by kevstax** [ParadoxGamingRP/bugs-and-suggestions#2463]
### Your Discord Name

KevStax

### A clear and concise description of what the bug is

NS tuning and I'm gonna assume the other auto shops as well no longer have the 25% bennys discount at our shops.

### Steps to Reproduce the Bug

1. go to NS tuning bennys booth
2.  prices are same as regular bennys

### Expected Behavior

1. go to bennys booth
2.  25% off regular bennys price

### Screenshots/Videos

n.a

**Comment by Skeletal-KC** [comment]
The discount works but it's super finicky. Sometimes you have to leave and re-enter the shop, or park and unpark the car several times in order for the shop to recognize and apply the discount. The discount also will only show up once you are at the confirm purchase screen. The Prices listed in Benny's as well as in the bottom right corner will still show up as default pricing. I was told the latter at least is normal and a limitation of the menu itself.
