### ISSUE TITLE
[BUG] Slurpissues again

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#2468]
### Your Discord Name

ssara

### A clear and concise description of what the bug is

We still are having some issues where we pull out a local truck, you can see it on the plate where our trucks all have SLURP in the beginning and sometimes you get one that doesnt. 

### Steps to Reproduce the Bug

Pull out truck
WISHFUL THINKING INSHALLAH
Get the wrong truck

### Expected Behavior

Pull out truck
Get the right truck

### Screenshots/Videos

N/A

**Comment by SpiceF0x** [comment]
This is also happening for:

EMS vehicles
LEO vehicles
SADOT vehicles

Essentially:

Pull vehicle
Get vehicle
It is a local vehicle and you are not given the keys
Not replicated 100% of the time

**Comment by Dez505** [comment]
This also happens if you put someone in test drives at the bike shop or kildare's

**Comment by SaraLef** [comment]
So David pulled the truck out, no issues right after storm.
Then Token tried for 4 times - didn't work.
Then I tried for 5 times - didnt work.
