### ISSUE TITLE
[BUG] Registers isnt working

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#2470]
### Your Discord Name

ssara

### A clear and concise description of what the bug is

Registers arent opening

### Steps to Reproduce the Bug

Try to open drawer
Nope

### Expected Behavior

Try to open drawer
yep

### Screenshots/Videos

N/A

**Comment by Bac0nRamen** [comment]
This still a issue? Been working fine last day or so from what ive done and people have said
