### ISSUE TITLE
[BUG] <corner selling at 50% even with cops>

### ISSUE THREAD

**Issue by kevstax** [ParadoxGamingRP/bugs-and-suggestions#2486]
### Your Discord Name

KevStax

### A clear and concise description of what the bug is

even with cops available buyers are offering me 50% offers

### Steps to Reproduce the Bug

1. corner sell with cops on
2. get offered 50%

### Expected Behavior

1. corner sell with cops on
2.  get offered full price

### Screenshots/Videos

n/a

**Comment by kevstax** [comment]
Not even getting 50% offers with cops available right now. Got 2 offers of around 2 for $20

**Comment by emeraldleo1982** [comment]
> Not even getting 50% offers with cops available right now. Got 2 offers of around 2 for $20

That's normal as a lowball offer, are you also getting the higher offers?

**Comment by shannyshoez** [comment]
yeah i tried selling for an hour and got 50% offers. IE $500 max for 2 bags.
