### ISSUE TITLE
[ENHANCEMENT] Putting an anchor on the Aqua Blazer

### ISSUE THREAD

**Issue by BBstud44** [ParadoxGamingRP/bugs-and-suggestions#2489]
**Your Discord Name**
BBstud27

**Describe the annoyance**
when driving the Aqua Blazer on the water if you want to get off there is no option to throw an anchor down so it doesnt float away

**To Reproduce**
[Steps to reproduce the annoyance]
1.  Drive the Aqua Blazer on the water
2. Get off the vehicle
3. watch it float away

**Requested behavior**
It would be nice if it had an anchor so it doesnt just float far away from you whenever you get off it to do anything in the ocean

**Screenshots**
N/A

**Additional context**
N/A

**Comment by emeraldleo1982** [comment]
Would it also be possible to add a BOAT tag or something to them so they can be used for coral detecting, but still be sold by the bike shop?
