### ISSUE TITLE
[ENHANCEMENT] BARELY SEE NUMBER OF ITEMS IN POCKETS

### ISSUE THREAD

**Issue by NataliaGallo96** [ParadoxGamingRP/bugs-and-suggestions#2499]
**Your Discord Name**
carebear9696

**Describe the annoyance**
I can barely see how much of each item I have in my pockets

**To Reproduce**
[Steps to reproduce the annoyance]
1. open pockets

**Requested behavior**
Can we get the number of items size to increase 

**Screenshots**
![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/123715929/da4a96e1-374d-4f2a-8682-80d5e4f60013)

**Comment by Bac0nRamen** [comment]
UI reverted back to old
