### ISSUE TITLE
[BUG] Bee Hives

### ISSUE THREAD

**Issue by RoseiiNaytool** [ParadoxGamingRP/bugs-and-suggestions#2501]
### Your Discord Name

Roseii

### A clear and concise description of what the bug is

I am having to replace my bee hive way to often. It started out having to replace it like once every couple of days. It's been less than 24 hours without constant use and it is having me replace it again. These are $2500 every time you have to replace it. I have people that tell me they have had theirs over a week and haven't had to replace it. 

### Steps to Reproduce the Bug

1. Put down bee hive
2. repair beehive 1-3 times an hour
3. hive breaks WAY to soon

### Expected Behavior

To not have to replace my beehive all the time, it's REALLY expensive to have to replace it all the time, then the $300 per repair every time it needs repaired. 

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/84455462/25a8a903-011a-4c63-a923-d921d3572cd7)

**Comment by Bac0nRamen** [comment]
You should only be having to repair it and add bees to it. You dont have to keep buying them all the time unless u pick it up

**Comment by RoseiiNaytool** [comment]
Yeah it keeps making me completely replace the hive. Like I said, it was every two days, some people's hives last over a week before they have to replace it, now it's less than 24 hours and I have to replace the hive. not sure what the issue is. I don't see an error in the F8 menu to share here.

**Comment by SaraLef** [comment]
I've heard others have the same issue as well where they have to completely remove it because you cant do anything in the menu, its all gray'd out.

**Comment by emeraldleo1982** [comment]
Can confirm, it's happened once to me, and when you attempt to remove it it just sits there staring at you.. menacingly!

**Comment by RoseiiNaytool** [comment]
sometimes it will tell you to replace the queen, you try to replace it and it gives you what is in the picture above

**Comment by jkaejkae888** [comment]
I'm having the problem with the hive also

**Comment by corruptd3d** [comment]
I’m also having a problem with my hive like that

**Comment by CadieLudwig** [comment]
I am having problems with my Hive as well. It is saying inactive and wont let me take care of the hive anymore.
![4cdc7228fb99c6856b975931201a19bd](https://github.com/user-attachments/assets/c9d72b66-0eff-4b2c-b796-da255717afe0)
