### ISSUE TITLE
[BUG] Madrazo Inc invisible

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#2507]
### Your Discord Name

jojosnmustard

### A clear and concise description of what the bug is

If you happen to find yourself behind Madrazo Inc building, the building seems to turn transparent.

### Steps to Reproduce the Bug

1: Stand behind Madrazo's building

### Expected Behavior

Madrazo Inc not be so transparent

### Screenshots/Videos

![image](https://github.com/ParadoxGamingRP/bugs-and-suggestions/assets/29337315/fd72b676-eacf-428a-a5fd-d447c6fd66c1)

**Comment by Bac0nRamen** [comment]
its any of those interiors so madrazo and wolfs. Tried to fix it before but never figured it out

**Comment by Bac0nRamen** [comment]
Pushed a fix for this I think. Let me know
