### ISSUE TITLE
[BUG] getting stuck inside assassin room

### ISSUE THREAD

**Issue by ImPaulYo** [ParadoxGamingRP/bugs-and-suggestions#2511]
### Your Discord Name

imcarbon_yo

### A clear and concise description of what the bug is

for the assassination mission and you take the target hostage and bring into the room, you can not get out of the room unless the hostage is in your hands but the hostage disappears after you take out the body part.

### Steps to Reproduce the Bug

1. get assassin job
2. take target hostage
3. bring into room
4. cut out body part
5. try to exit

### Expected Behavior

to be able to leave lol

### Screenshots/Videos

none

**Comment by ImPaulYo** [comment]
also i was under the impression that tking the target to the room would result in better body parts but i get eye balls and finger nails, thus making me think that taking the target to the room is not worth it

**Comment by Norgman** [comment]
@ImPaulYo you usually do get better parts. its generally worth it.

I am also sad to be locked inside that room.

**Comment by Norgman** [comment]
I would like to add that it seems as long as you have the hostage in your arms, you can exit the kill room. (I didn't actually try, but the 3rd eye option actually popped up for me)
