### ISSUE TITLE
[BUG] Illegal fish buyer not removing pearls card

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#2512]
### Your Discord Name

jojosnmustard

### A clear and concise description of what the bug is

When selling exotic fishies to pearl, she checks your card, but never takes it. I feel like this is an important part of the cap on the farmability of illegal fishing.

### Steps to Reproduce the Bug

1: Sell fish to pearl with pearls card
2: Never lose card
3: Profit infinitely

### Expected Behavior

Pearl takes your membership card with some chance? If the sell fish box was made larger we could sell all our exotic fish in one go (40 slots since the fish don't stack? Inventory holds 36) which would make the card single use for selling and limit how often you could do illegal fishing to how many cards you can get ahold of, possibly creating a black market for pearls cards in the process.

### Screenshots/Videos

N/A

**Comment by Bac0nRamen** [comment]
its set to 85% chance that it will be taken. Maybe your just getting lucky?

**Comment by SaraLef** [comment]
Haven't had mine taken since she was in the cave thought it was by design.

**Comment by emeraldleo1982** [comment]
There's no way I've been that lucky as many times as I've sold to her since the wipe.

**Comment by tusktheshrew** [comment]
I have never got my card taken as well.

**Comment by Skeletal-KC** [comment]
Honestly I thought it was health based because the card has a health bar it just never decreases

**Comment by corruptd3d** [comment]
Think the health is just to prevent it stacking or something
