### ISSUE TITLE
[BUG] <Bravado Vulture Has Odd/Random Handling Behavior>

### ISSUE THREAD

**Issue by Skeletal-KC** [ParadoxGamingRP/bugs-and-suggestions#2514]
### Your Discord Name

skeletal_kc

### A clear and concise description of what the bug is

The Bravado Vulture seems to exhibit extremely random, and odd behavior when driving and while coming to a stop. While driving it will randomly behave as if it's on ice and understeer/skate across the pavement. It also exhibits the same behavior when at a stand still, sometimes it will randomly slide to the left or to the right as it seems that when coming to a stop, the left rear wheel will continue spin for a brief moment while the other 3 wheels have come to a stop. It also seems to act as if it can't decide whether it's AWD or RWD at random intervals, especially while going through a corner.

I think the Vulture needs to be heavily looked at for it's price bracket.

### Steps to Reproduce the Bug

1. Pull the vulture out of a parking space (sometimes it will skate around just from pulling it out))
2. Drive it around - it's behavior is very inconsistent, and odd.
3. Come to multiple complete stops, or slow downs, and watch the vehicle skate around.

### Expected Behavior

Vehicle should handle, and perform more predictably for it's price bracket

### Screenshots/Videos

Will try to get some clips and add them if I can.

**Comment by Bac0nRamen** [comment]
We are working on a major handling update soon.
