### ISSUE TITLE
House Robberies Broken

### ISSUE THREAD

**Issue by Malfoo** [ParadoxGamingRP/bugs-and-suggestions#2531]
### Your Discord Name

Malfo 

### A clear and concise description of what the bug is

Seems the house robberies loop is broken again. I took a job and was fine then some time past and I tried again when it turned night again job another job went inside the house and it said everything was searched already.

### Steps to Reproduce the Bug

Rob a house with the job
Get job again next time it is night
Try again unable to rob houses says already searched.

### Expected Behavior

To work

### Screenshots/Videos

n/a

**Comment by xXJamieXx** [comment]
Is it saying that before or after doing the skillcheck?

**Comment by Malfoo** [comment]
After

**Comment by xXJamieXx** [comment]
Consolidating into #2400
