### ISSUE TITLE
[BUG] Mobile business ping doesn't go away

### ISSUE THREAD

**Issue by NataliaGallo96** [ParadoxGamingRP/bugs-and-suggestions#2534]
### Your Discord Name

carebear9696

### A clear and concise description of what the bug is

I opened the business in error and a yellow ping appeared, I then closed it and the yellow ping remained their. Plus, everyone is seeing the yellow ping on their mini map that was awake during the time the business was open.

### Steps to Reproduce the Bug

1. open business
2. ping shows up
3. close business 
4. ping remains

### Expected Behavior

1. open business
2. ping shows up
3. close business 
4. ping goes away

### Screenshots/Videos

![image](https://github.com/user-attachments/assets/d78899b0-b3d9-47c3-b395-7f1c8057f339)
![image](https://github.com/user-attachments/assets/54ee5459-670b-465d-be54-af228a74e8d1)

**Comment by Darahz** [comment]
What business is this?

**Comment by lPrestonl** [comment]
Looks to be growex, I would know that van anywhere..
