### ISSUE TITLE
[ENHANCEMENT] Pearl eating too many cards

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#2537]
**Your Discord Name**
jojosnmustard

**Describe the annoyance**
Pearl is taking cards now as she should, but since the sell box is so small and she's taking the cards at such a high rate, we need 3-4 cards to sell 45 minutes of fishing to her since the illegal fish don't stack.

**To Reproduce**
[Steps to reproduce the annoyance]
1. Sell fish to pearl
2. Lose Card after 1 sale
3. Need more cards
4. Repeat

**Requested behavior**
[A clear and concise description of what you want to happen]
Could we increase the size of her sell box to 24 slots instead of 8? Or reduce the card loss rate to something manageable so we don't need multiple cards to sell 1 run of fish.

**Additional context**
This was tested with multiple people, out of 7 pearls cards we lost 6 after 1 sell of 8 fish each.

**Comment by Bac0nRamen** [comment]
We fixed pearl taking cards. so its set high for a bit so cards can get used up in server. Will be reduced soon
