### ISSUE TITLE
[BUG] House robbery issues

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#2538]
### Your Discord Name

ssara

### A clear and concise description of what the bug is

Tried to get a big house, got an email right away but no ping on the gps. 

### Steps to Reproduce the Bug

Get a big house
Get email
Get no location on map

### Expected Behavior

Get big house
Get email
Rob house

### Screenshots/Videos

![image](https://github.com/user-attachments/assets/1b8fa133-0c9b-4604-a1c7-e19e9b93d1b0)
![image](https://github.com/user-attachments/assets/cbd97371-e437-4351-ae75-56cac55e4e3a)

**Comment by SpiceF0x** [comment]
In addition to this, low end houses are no longer showing the skill check at the front door.

**Comment by Malfoo** [comment]
Just happened to me got the email no gps
