### ISSUE TITLE
[BUG] Parking meters

### ISSUE THREAD

**Issue by emeraldleo1982** [ParadoxGamingRP/bugs-and-suggestions#2540]
### Your Discord Name

jojosnmustard

### A clear and concise description of what the bug is

Not a bug persay.. but if you smash a parking meter, it remains smashable immediately after with no affect on tool durability. You make 11-15 dollars per 7 seconds with smashing the meter and a person could make 5500-7650 an hour just sitting there smashing the same meter.

### Steps to Reproduce the Bug

1: Smash
2: Smash
3: Smash
4: Smash

### Expected Behavior

A cooldown mechanism of some sort, or breaking the tool at an appropriate rate so you can still make some money over the cost of the tool.

### Screenshots/Videos

N/A

### Extra Notes (Optional)

Just trying to head this off before it becomes and issue and gets the mechanic killed.

**Comment by Darahz** [comment]
I have no idea how you mathed that, since it's impossible. I'll make it so you can't smash the same one over and over though

**Comment by emeraldleo1982** [comment]
I smashed the same one 3 times, then went to write the ticket, never would've guessed there'd be a cooldown after hitting 3 of them.
