### ISSUE TITLE
one of the Grain delivery job Destination Is inside a gang compound and chad's bar Parking lot

### ISSUE THREAD

**Issue by CROWSER75** [ParadoxGamingRP/bugs-and-suggestions#2552]
**Your Discord Name**
Crowser

one of the Grain delivery job Destination Is inside a gang compound and chad's bar Parking lot

https://cdn.discordapp.com/attachments/1021898580019130368/1263532112158658602/FiveM_b3095_GTAProcess_dJd1FvP2R2.jpg?ex=669a937a&is=669941fa&hm=53e9c791628f35c7b836442b51b44ce6be9ff84a85d4022f9a68c5ed90d8acde&

https://cdn.discordapp.com/attachments/1021898580019130368/1263532134371557416/FiveM_b3095_GTAProcess_c2ebYPFYfk.jpg?ex=669a9380&is=66994200&hm=0e15a0d45f4a85e3747e058570cd238a11bf1f712bf2539fa4833bb35d722afe&

**Comment by Darahz** [comment]
Chads parking lot is ok. But i've removed the other ones.
