### ISSUE TITLE
[BUG] Cannot use bats

### ISSUE THREAD

**Issue by jibbersh** [ParadoxGamingRP/bugs-and-suggestions#265]
**Your Discord Name**
Jibberish#2741

**Describe the bug**
You cannot pull a bat from your inventory and use it as a weapon, other weapons including broken ones can be pulled out and used.

**To Reproduce**
[Steps to reproduce the bug]
1. Buy a bat
2. Move it to a hotbar or try to use it manually
3. Be unable to hold the bat to use it

**Expected behavior**
To be able to swing a bat at ~people~ baseballs.

**Screenshots**
(https://medal.tv/games/gta-v/clips/dtyz7EvLhIqiC/d1337voqSgaS?invite=cr-MSxURGwsNDM3MDg3NjIs)

**Logs**
[Add your FiveM logs]

**Comment by GFaustini** [comment]
I have the same bug
