### ISSUE TITLE
[ENHANCEMENT] Bikini Tow Semi Fix

### ISSUE THREAD

**Issue by LitrlyD3ad** [ParadoxGamingRP/bugs-and-suggestions#313]
**Your Discord Name**
D3ad#0001
**Describe the annoyance**
Even since 2.0 the Bikini Tow Semi has been the only work vehicle we have had that doesn't have working lights, we are requesting the possibility of either getting lights added or having the semi replaced with a semi that has lights. The reason we want light is for crowd control, anytime we have the truck on scene it makes the locals freak out and hit things.

**To Reproduce**
[Steps to reproduce the annoyance]
1. Grab the truck
2. go on scene
3. get perma'ed by a local

**Requested behavior**
We would like useable light on the truck.

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by xXJamieXx** [comment]
Would need someone to add a lightbar to the model or find a similar model with a light bar attached. Easier said than done I'm afraid.

**Comment by LitrlyD3ad** [comment]
So actually me and copper was talking about it and im gonna have a go at putting the light bar on myself, testing it in my own server for optimization and then throwing it at you guys to take a look at, this will take some time so ill keep you posted.

**Comment by ithegreatgatsby** [comment]
I'm always looking for a new semi and such for tow.  I'm going to close this report but just know I'm always looking for a new truck and things to add.  Just reach out to me in the Bikini discord if you have any questions
