### ISSUE TITLE
[ENHANCEMENT] MDT Suggestions Megathread

### ISSUE THREAD

**Issue by xXJamieXx** [ParadoxGamingRP/bugs-and-suggestions#503]
The purpose of this issue is to provide a place to compile all suggestions for the MDT in order to avoid clogging up the issues list with a bunch of suggestions for the same system.

Now that the MDT is on a stable version and has been updated and bug tested I am ready to start adding new features as needed.

Please do not submit bugs here and instead open an individual bug report for the bug in question.

**Comment by xXJamieXx** [comment]
https://github.com/xXJamieXx/paradox-bugs/issues/498#issue-1269490479

**Comment by xXJamieXx** [comment]
https://github.com/xXJamieXx/paradox-bugs/issues/498

**Comment by M1ngh** [comment]
Hey Jamie, I just want to report a MDT bug that we can't clear Warrants, so basically I go on arrest reports, go on the warrant report. Remove the warrant save it and go back to my arrest report and when I go to profile the wanted still there and when I go back to the Warrant report the still marked as green

https://medal.tv/games/imported-clips/clips/oJSToHgoGSQPV/d1337zmluAgH?invite=cr-MSxpWm4sMzgwMzUxODEs

**Comment by OwlCherry** [comment]
If at all possible, could the administration and removal of gun licenses be automatically documented on the profile with date and by what officer to improve licensing process and documentation.

**Comment by xXJamieXx** [comment]
> I would like to suggest that the Warrant button could on the profile and u can remove it from there.

Are you suggesting a button to remove warrants from all of the reports that have it applied? I think you might be misunderstanding that each arrest/citation report can have the warrant tag checked so someone could have multiple warrants.

**Comment by PadawanPepsi** [comment]
https://i.imgur.com/JuC0Ii2.png        The Charges box use to show here but now it is hidden. If you click in the spot where it was before then you can still add charges but the actual box is missing now

**Comment by xXJamieXx** [comment]
> https://i.imgur.com/JuC0Ii2.png The Charges box use to show here but now it is hidden. If you click in the spot where it was before then you can still add charges but the actual box is missing now can we get the box back please

I didn't add it back because I didn't think it was particular necessary. Everyone knows where it is, does it actually make a difference?

**Comment by PadawanPepsi** [comment]
> > https://i.imgur.com/JuC0Ii2.png The Charges box use to show here but now it is hidden. If you click in the spot where it was before then you can still add charges but the actual box is missing now can we get the box back please
> 
> I didn't add it back because I didn't think it was particular necessary. Everyone knows where it is, does it actually make a difference?

I dont think it makes a diffrence. It was just noted in an academy that it was missing. Dident know if it was on purpose or not.

**Comment by PadawanPepsi** [comment]
A lot of the vehicles are no longer showing a picture in the DMV anymore

**Comment by PadawanPepsi** [comment]
maybe even all of them

**Comment by xXJamieXx** [comment]
Closing as not really being used. Open individual issues for MDT bugs/suggestions.
