### ISSUE TITLE
[BUG] Rob's Liquor Safe

### ISSUE THREAD

**Issue by DraconicRebel** [ParadoxGamingRP/bugs-and-suggestions#514]
### Your Discord Name

DraconicRebel#5942

### A clear and concise description of what the bug is

So when I was doing a Store Robbery I got the Rob's Liquor, when I got the sticky note, I was going to memorize the codes, but the safe just won't open for me to crack it. I got away however with little money although.

### Steps to Reproduce the Bug

N/A

### Expected Behavior

I expected it to have a wheel lock code to work, but sadly it doesn't work.

### Screenshots/Videos

Sadly, I didn't get any Screenshots or videos of the bug. But if I test it out again, I will surely do that.

### Extra Notes (Optional)

See if you can make the safe like the twenty four seven ones or something.

**Comment by xXJamieXx** [comment]
I believe this should be resolved.
