### ISSUE TITLE
[BUG] Scenes not working

### ISSUE THREAD

**Issue by Alikelp** [ParadoxGamingRP/bugs-and-suggestions#573]
### Your Discord Name

SwackyMan#7807

### A clear and concise description of what the bug is

Went to put up territory scenes around Vespucci. I placed 1 and then i could not place another. 

### Steps to Reproduce the Bug

Get to scene menu
place a scene
Go back to menu
try to place another but no words come up

### Expected Behavior

I expected to place another scene

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98968986/179422304-3d818e8d-c1bf-466c-9be5-8a995984139f.png)

### Log File

[Logs for Scene.txt](https://github.com/ParadoxGamingRP/paradox-bugs/files/9128431/Logs.for.Scene.txt)

**Comment by Weebait** [comment]
The Scenes specifically don't work around Little Seoul area

**Comment by natashajoan** [comment]
This seems to be happening everywhere, it became an issue when they were updated for indoors. It's almost like they only work near interiors or certain mapping objects. For example at Glazed & Glorious, I can use one, but if I step a few steps back I can no longer place the scene. 
![Screenshot (956)](https://user-images.githubusercontent.com/97318080/180662125-9623ed46-b711-4755-8262-ca3173b3d8c6.png)
![Screenshot (957)](https://user-images.githubusercontent.com/97318080/180662131-a4e89f6c-be8b-41dc-a4b7-d52ea2f84fcd.png)

**Comment by xXJamieXx** [comment]
This has now been fixed and is working as best as it can be now. If you're too close to an interior it will treat it as an interior scene so if it doesn't show the text when using the laser to place then it means you're too close to the interior and wont see it unless inside. While outside and far enough away from an interior it should show the text when placing which means it will show up outside.
