### ISSUE TITLE
[BUG] Wolfs paychecks are not being taken from business account

### ISSUE THREAD

**Issue by SpiceF0x** [ParadoxGamingRP/bugs-and-suggestions#576]
### Your Discord Name

spicedf0x#2127

### A clear and concise description of what the bug is

Each time Sugar Fox collects a paycheck having been on duty as Real Estate, the bank balance for Wolfs is not decreasing. I have also noticed there is not a paycheck being logged in #business-logs for it, so that might be linked :)

### Steps to Reproduce the Bug

1. Be on duty for real estate
2. Collect paycheck
3. Bank balance remains the same

### Expected Behavior

Wolfs bank balance to decrease when pay checks are collected

### Screenshots/Videos

na

**Comment by xXJamieXx** [comment]
Fixed.
