### ISSUE TITLE
[BUG] cant get keys for truck with personal plate

### ISSUE THREAD

**Issue by BullRiderMcGhee** [ParadoxGamingRP/bugs-and-suggestions#579]
### Your Discord Name

BullRiderMcGhee#3246

### A clear and concise description of what the bug is

take vehicle out of garage and i cant get keys to start it but i can unlock and lock it

### Steps to Reproduce the Bug

personalize plate
put in garage
take out
someone leaves me my key fob but throws my keys into the ocean

### Expected Behavior

be able to start and drive my truck

### Screenshots/Videos

N/A

### Extra Notes (Optional)

N/A

### Log File

[CitizenFX_log_2022-07-18T195201.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9136114/CitizenFX_log_2022-07-18T195201.log)

**Comment by xXJamieXx** [comment]
I believe we have resolve this issue now. If you could let us know if this is the case?
