### ISSUE TITLE
[BUG] Buying Ores from Ore Buyer, doesn't decrease the amount of ore in their storage.

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#580]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

When buying ore from the ore salesman downa at 174. The salesman replenishes from what you bought for ores.

### Steps to Reproduce the Bug

1. Go down to Ore Salesman
2. Buy Ore
3. See new number
4. Exit Menu
5. Enter Menu again, number same before you bought the ore.

### Expected Behavior

Ore is dynamic in the market, and corresponds with how much is in the ore salesman sell box.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98053772/179757729-e8fecb1c-0d45-44a7-846b-419459a3d499.png)

### Log File

[BuyingOre.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9141273/BuyingOre.txt)

**Comment by xXJamieXx** [comment]
Should be fixed.
