### ISSUE TITLE
[BUG] House Robbery got Triggered as soon as I got in

### ISSUE THREAD

**Issue by DraconicRebel** [ParadoxGamingRP/bugs-and-suggestions#581]
### Your Discord Name

DraconicRebel#5942

### A clear and concise description of what the bug is

When I went into the house, I went inside crouching the whole time, and all of the sudden when I went outside, I got caught by the police. I dont think this should have happen, not sure if this is a bug to do with the alarm trigger.

### Steps to Reproduce the Bug

1) Lockpick the house
2) Enter the house crouching
3) Crouch the whole time not to trigger the alarm
4) If the alarm is triggered, the police would be contacted.

### Expected Behavior

I lock pick the house to enter inside, crouch then, and then collect all the stuff and not get caught by the trigger alarm unless walking, running, sprinting or speed crouching.

### Screenshots/Videos

N/A

**Comment by JnKTechstuff** [comment]
Crimes have risk; we do not disclose what triggers alarms
