### ISSUE TITLE
[BUG] Ranched Out Hide and Seek

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#582]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

When standing by the wardrobe of the Ranched Out another person can walk through the void and go invisible from the person by the wardrobe sight.

### Steps to Reproduce the Bug

1. Have Person stand by wardrobe
2. Have 2nd person walk away from wardrobe
3. Have 2nd person walk back.

### Expected Behavior

Can see everyone in the home at any part of the house.

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/sZxNA_8mHZjI9/d1337tRQtlet?invite=cr-MSxmTkssNjIwNTkzNzQs
![image](https://user-images.githubusercontent.com/98053772/179790092-df9b4321-f159-47c1-af9b-4e153d1ad2c1.png)

**Comment by JnKTechstuff** [comment]
This is actually expected behavior to allow people to change clothes in a house with multiple people around and them not having their sight blocked. The same also happens at the entrance of the houses for raids!
