### ISSUE TITLE
[BUG] Can't pick up dropped items

### ISSUE THREAD

**Issue by pinkyhey** [ParadoxGamingRP/bugs-and-suggestions#584]
### Your Discord Name

henpinky#8453

### A clear and concise description of what the bug is

the bug i am having is i droped a item and when i went to pick it up it didnt apear in the droped box on the right 

### Steps to Reproduce the Bug

drop a item on the far right fishing dock on the map

### Expected Behavior

i expected to be able to pick the item nack up after droping it 

### Screenshots/Videos

![arrow](https://user-images.githubusercontent.com/48034230/179856862-a2a63799-7512-4084-a295-076a372799d2.PNG)
![none](https://user-images.githubusercontent.com/48034230/179856863-d2f64250-c75d-4005-b814-ddfd870a9f55.PNG)

**Comment by ithegreatgatsby** [comment]
can you let us know if this is still going on? Works fine for me as of today.  Please provide any extra info if you are still having issues

**Comment by ithegreatgatsby** [comment]
Going to go ahead and close this. If you still have this issue please open up a new report. Thanks!
