### ISSUE TITLE
[BUG] Bikini Automotive is mean

### ISSUE THREAD

**Issue by OwlCherry** [ParadoxGamingRP/bugs-and-suggestions#585]
### Your Discord Name

OwlCherry#6969

### A clear and concise description of what the bug is

So Other operators same rank and higher than me can all PULL an engine... however, it royally hates me

We have tried firing and rehiring..
Hard log out. 
New Hoist
Getting in and out of car

I am able to do everything once one of the GUYS pull the engine, but it will not allow MEEEEEEE.

I am able to open the engine and install it again, I am only missing the pull option

### Steps to Reproduce the Bug

1. Grab hoist
2. bring to car
3. third eye car and only get Impound, get in trunk and Seat menu. ONLY
4. other Tow op stands in exact same spot - able to get pull engine

### Expected Behavior

i should be allowed to pull engine too hmph

### Screenshots/Videos

https://streamable.com/h9631z

### Log File

[CitizenFX_log_2022-07-19T220315.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9145147/CitizenFX_log_2022-07-19T220315.log)

**Comment by Deadles** [comment]
She isn't the only one having this issue, I can do everything else except for extracting the engine from the hoist.  I tried taking a nap, clearing my cache and clocking in and out,  none of those things fixed it.  

Here is everything from My side in the clip and logs

https://medal.tv/games/gta-v/clips/t4Pt41BfdUtuu/d1337xDvSoJY?invite=cr-MSxqbnksMjc2NTExNzUs

[CitizenFX_log_2022-07-20T031713.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9146349/CitizenFX_log_2022-07-20T031713.log)

**Comment by xXJamieXx** [comment]
> She isn't the only one having this issue, I can do everything else except for extracting the engine from the hoist. I tried taking a nap, clearing my cache and clocking in and out, none of those things fixed it.
> 
> Side Note related to the tow trucks, The ambiance siren is on when the lights are on.
> 
> Steps to reproduce the issue 1 Turn the lights of the tow truck 2 Get out of the tow truck 3 Stand about 2 to 3 blocks away from the truck
> 
> Here is everything from My side in the clip and logs
> 
> https://medal.tv/games/gta-v/clips/t4Pt41BfdUtuu/d1337xDvSoJY?invite=cr-MSxqbnksMjc2NTExNzUs
> 
> [CitizenFX_log_2022-07-20T031713.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9146349/CitizenFX_log_2022-07-20T031713.log)

Siren issue should be put in as a separate issue.

**Comment by OwlCherry** [comment]
User error :P THANK YOU JAMIE :P
