### ISSUE TITLE
[BUG] Unlimited Parts

### ISSUE THREAD

**Issue by OwlCherry** [ParadoxGamingRP/bugs-and-suggestions#587]
### Your Discord Name

OwlCherry#6969

### A clear and concise description of what the bug is

So after a shit ton of issues on an Evo, we ended up being forced to garage the car and pulling it out due to a scuff issue, in attempts to salvage parts, we removed the components off the scuffed engine and stored them. when we went back into the engine AFTER all components were readily available to be taken AGAIN.

### Steps to Reproduce the Bug

1. open engine
2. remove ALL items
3. Close Engine
4. Reopen Engine
5. Able to gain all components again

### Expected Behavior

Once all components are removed, the engine should be empty, and not magically filled with parts again

### Screenshots/Videos

No Video

### Log File

[CitizenFX_log_2022-07-20T220219.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9155687/CitizenFX_log_2022-07-20T220219.log)

**Comment by Mac-ceo** [comment]
This has happend to me as well it doesn't happen every time

**Comment by xXJamieXx** [comment]
Should be fixed next restart.
