### ISSUE TITLE
[BUG] Invisible fishing chest in glove compartment

### ISSUE THREAD

**Issue by NateWolford** [ParadoxGamingRP/bugs-and-suggestions#588]
### Your Discord Name

Nate#7678

### A clear and concise description of what the bug is

I had a fishing chest full of exotic fish, I placed it into my glove box and when I checked the glove box again it was invisible, however the item is still in there, just not visible or accessible. I can't place anything into the glove compartment and it still says 25/25. I was assisted by a staff member (Mason) and was told to create this bug report. I will attach a picture of the glove box. I had about a few thousand dollars worth of fish in there if I remember correctly. 

### Steps to Reproduce the Bug

1. Enter the vehicle 
2. Check the glove compartment 
3. It will say 25/25, you can't add or remove anything from the glove box as it appears to be invisible

### Expected Behavior

The expected behavior is that I am able to remove the ice chest and take my fish out successfully, however it is invisible.

### Screenshots/Videos

![unknown](https://user-images.githubusercontent.com/55004498/180119437-95486771-53a3-42e8-9b23-b54f4700b2d0.png)

### Log File

[CitizenFX_log_2022-07-21T015700.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9155788/CitizenFX_log_2022-07-21T015700.log)

**Comment by xXJamieXx** [comment]
Not sure why this didn't fix for you, fixed it manually.
