### ISSUE TITLE
[Bug] 832 Tennis Court Unplayable

### ISSUE THREAD

**Issue by Weebait** [ParadoxGamingRP/bugs-and-suggestions#589]
### Your Discord Name

Weeb#5266

### A clear and concise description of what the bug is

While every tennis court in the city works for tennis the one at postal 832 which is the house I bought due to it having a tennis court doesn't it's not that it's broken it's simply that it doesn't count it as a court that you can initiate a game on

### Steps to Reproduce the Bug

N/A

### Expected Behavior

There be an option to attempt play at a tennis court

### Screenshots/Videos

N/A

**Comment by xXJamieXx** [comment]
Added next restart.
