### ISSUE TITLE
[BUG] Lancer EVO-9 cant be pulled out the garage after the 3am pst restart 

### ISSUE THREAD

**Issue by TheSecretx** [ParadoxGamingRP/bugs-and-suggestions#590]
### Your Discord Name

TheSecret#7441

### A clear and concise description of what the bug is

Lancer EVO-9 cant be pulled out of the garage. after the server restarted it's like the car doesn't exist..
when pulled out and nothing spawns.

### Steps to Reproduce the Bug

1. go to the garage its in
2. try to pull it out
3. its doesnt spawn.. it will stay in the garage

### Expected Behavior

the car will stay in the garage and will never spawn

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/84610357/180192680-36fc6469-8d7a-4053-9a85-a06cfb61e92f.png)

**Comment by xXJamieXx** [comment]
Followed your steps and was able to pull it out fine. Could you provide logs or more information to help reproduce this issue?

**Comment by TheSecretx** [comment]
> 

seems the bug is gone this can be closed
