### ISSUE TITLE
[BUG] Salary at Kildare Auto

### ISSUE THREAD

**Issue by daemon3698** [ParadoxGamingRP/bugs-and-suggestions#591]
### Your Discord Name

maddog3698#3698

### A clear and concise description of what the bug is

I am receiving a different salary than the other people who are set to the same position as I am.

### Steps to Reproduce the Bug

1. Clock in.
2. Wait for pay check
3. Get lower paycheck than Ricky

### Expected Behavior

1. Clock in.
2. Wait for Pay Check.
3. Get Same Paycheck as Ricky

### Screenshots/Videos

N/A

### Extra Notes (Optional)

I was told to make a bug report lol

**Comment by xXJamieXx** [comment]
Looks like the same paycheck to me?
![image](https://user-images.githubusercontent.com/11248045/180301902-ecf5a533-5ba1-4687-87ed-8bacb1c92dda.png)
![image](https://user-images.githubusercontent.com/11248045/180301958-16da397e-4a1a-4653-910b-21ce9c3b60ac.png)

**Comment by daemon3698** [comment]
So I am going to be honest. It was going on earlier. I was making 100 and Ricky was making 400 but I had a head pop and when I got back it fixed it but I didn't know how to close the report
