### ISSUE TITLE
[BUG] Gas Station not refilling

### ISSUE THREAD

**Issue by baxepw** [ParadoxGamingRP/bugs-and-suggestions#592]
### Your Discord Name

baxe#0666

### A clear and concise description of what the bug is

When trying to refill a vehicle that does not require methanol at pumps that offer methanol (Slurp and Go and the Drag Strip). As in car only takes unleaded. When trying to fill unleaded it says you dont have the correct fuel. Believe cars that require methanol can fill up fine.

### Steps to Reproduce the Bug

1. Go to pump that has both unleaded and Methanol
2. Attempt to refill with unleaded
3. Doesn't let you refill

### Expected Behavior

1. Go to pump that has both unleaded and Methanol
2. Attempt to refill with unleaded
3. Fills my tank up with unleaded

### Screenshots/Videos

https://imgur.com/MdZUZIj 
https://imgur.com/Da2lvtO

**Comment by xXJamieXx** [comment]
Fixed next restart.
