### ISSUE TITLE
[BUG] Unable to receive hunting license 

### ISSUE THREAD

**Issue by BCA-BRIGGS** [ParadoxGamingRP/bugs-and-suggestions#593]
### Your Discord Name

super raccoon#0001

### A clear and concise description of what the bug is

so i have attempted to receive my gun license from three officers and every time I go to the sale spot for hunting it tells me I don't have a valid license. 

### Steps to Reproduce the Bug

Get license 
go to sale spot 
need to get a license again 

### Expected Behavior

be able to receive my hunting license 

### Screenshots/Videos

N/A

### Log File

[CitizenFX_log_2022-07-21T225002.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9163802/CitizenFX_log_2022-07-21T225002.log)

**Comment by BCA-BRIGGS** [comment]
not sure if the logs can do anything here but thought it was best to give them :)

**Comment by xXJamieXx** [comment]
You do not have a hunting license. Weapons and hunting licenses are different.

**Comment by BCA-BRIGGS** [comment]
I have received both 
I have my weapons license I have been to get my hunting license and it doesn't work. they have tried giving me it three times as I knew I needed one to sell. I know they are different the cops give me my hunting license and it doesn't work for some reason

**Comment by BCA-BRIGGS** [comment]
sorry it was a typo on my behalf

**Comment by Petrovic247** [comment]
I have received multiple reports from civilians. Have tried myself and can confirm some people are unable to receive hunting licenses.

**Comment by BCA-BRIGGS** [comment]
appears to be fixed thank you :)

**Comment by xXJamieXx** [comment]
Updated MDT to hopefully improve the reliability of this. Glad to hear its fixed though.
