### ISSUE TITLE
[BUG] Extras not showing on Taurus in benneys

### ISSUE THREAD

**Issue by PadawanPepsi** [ParadoxGamingRP/bugs-and-suggestions#594]
### Your Discord Name

PadawanPepsi#6898

### A clear and concise description of what the bug is

I bought a tarus went to benneys to start modding it after i resprayed it and took the light bar off i reamembered that you have to put it in storage first.

i put it in storage took it out and then went back to benneys. I did not have a light bar on but i suddenly had a ram bar on the front.  going through all the extras i could take the ram bar off but the only thing that appeared to be changing was the spot lights on the car. Other then that i dident notice anything going on or off the car

### Steps to Reproduce the Bug

take a taurus to benneys and see if the extras are going on and off

### Expected Behavior

i should be able to toggle an extra on and off but i could only toggle the ram bar off once it was off it would not go back on no matter how many times i checked and unchecked.

### Screenshots/Videos

https://user-images.githubusercontent.com/96961442/180361188-46ea790f-2022-412a-8d01-b98c85b45ca2.mp4

### Log File

[CitizenFX_log_2022-07-22T013415.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9164610/CitizenFX_log_2022-07-22T013415.log)

**Comment by ithegreatgatsby** [comment]
After selecting the extras repair your car. Extras can be weird when you change them at bennys. You can remove some or add some and they wont show until you repair it or put it in a garage so you might of just got some extras confused. If you take a friend with you and you pick a extra they will see it in there eyes when you add or remove but you wont see the change till you repair it. Let us know if it still a problem

**Comment by PadawanPepsi** [comment]
so i tried fixing it and then messing with extras and same thing.

Is the fix to just have a second party there update extras and then in garage and out?

**Comment by PadawanPepsi** [comment]
yea just tried repairing after every extra and it worked thank you

**Comment by ithegreatgatsby** [comment]
Great! Let us know if anything else changes
