### ISSUE TITLE
[BUG] Cancelling Hunting Bait Doesn't allow you to place another.

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#597]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

Escaping from a hunting bait, disallows you to place another bait till a Hard logout.

### Steps to Reproduce the Bug

1. Start Placing Bait
2. Cancel Bait with ESC Key
3. Trying Placing another Bait.

### Expected Behavior

Allows Next Bait to be put Down

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98053772/180615656-270f4dce-4497-46f5-b5b9-72de66606a45.png)

### Extra Notes (Optional)

The Log file gives a script error.

### Log File

[HuntingBait.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9174253/HuntingBait.txt)

**Comment by xXJamieXx** [comment]
Fixed next restart.
