### ISSUE TITLE
[BUG] turbos getting taken by aliens

### ISSUE THREAD

**Issue by Mac-ceo** [ParadoxGamingRP/bugs-and-suggestions#598]
### Your Discord Name

mac_ceo#7021 Rilley Johnson

### A clear and concise description of what the bug is

So when installing a turbo into a car sometimes if you put it in the garage or leave it or something dont know what causes it it will randomly get removed

### Steps to Reproduce the Bug

not sure how to reproduce

### Expected Behavior

Place it into cars engine and is still there next time engine is removed from car

### Screenshots/Videos

i dont have any screen shot proof but ask cecil butler or billy brown 

### Log File

[CitizenFX_log_2022-07-23T173212.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9174413/CitizenFX_log_2022-07-23T173212.log)

**Comment by baxepw** [comment]
Can also confirm this multiple people have lost turbos and a nos system. As of now all turbos were lost in import cars but a nos system was lost in a regular gta car. so dont think it is import related. Also was able to hear the turbo up until the point of opening the engine up.

**Comment by Mac-ceo** [comment]
I lost a turbo in my gta car as well

**Comment by xXJamieXx** [comment]
Should be fixed.
