### ISSUE TITLE
[BUG] Dispatch Panel for LEO Removed

### ISSUE THREAD

**Issue by Petrovic247** [ParadoxGamingRP/bugs-and-suggestions#599]
### Your Discord Name

PretenderPatrol#5993

### A clear and concise description of what the bug is

No one can open their Dispatch panel after Tsunami. The keybinding is no longer in the settings either. 

### Steps to Reproduce the Bug

1. Tried opening dispatch, checked settings, no beans,
2. Holloway tried, same results.
3. K. Busta tried, same results.

### Expected Behavior

Press I and opens dispatch panel. In settings Open large ui should be available.

### Screenshots/Videos

https://i.imgur.com/krCMgk6.jpeg

**Comment by xXJamieXx** [comment]
Was disabled intentionally but its returned for now.
