### ISSUE TITLE
[BUG] breaking out of prison when airlifting

### ISSUE THREAD

**Issue by McEwann** [ParadoxGamingRP/bugs-and-suggestions#600]
### Your Discord Name

McEwan#4840

### A clear and concise description of what the bug is

When airlifting from prison with no time left to serve, you're teleported to sandyshores medical and get an indication you've broken out

### Steps to Reproduce the Bug

Go to prison
Run out of time
die and airlift

### Expected Behavior

Return to the infirmary 

### Screenshots/Videos

Screenshotted myself in sandy but accidentally screenshotted over it, mb

**Comment by Sly-Panda** [comment]
Fixed next update.
