### ISSUE TITLE
[BUG] Hunting Drop Rates

### ISSUE THREAD

**Issue by erniexhamer** [ParadoxGamingRP/bugs-and-suggestions#601]
### Your Discord Name

Ernie Hamer#5237

### A clear and concise description of what the bug is

It seems like, if you have one 3* red carcasse in your pocket and no other carcasses, the rate of drop for that type potentially increases.

### Steps to Reproduce the Bug

1. Have 1 3* Red carcass in inventory
2. Continue skinning animals

### Expected Behavior

I expect each drop to be equally weighted, or not have inventory affect the drop rate

### Screenshots/Videos

n/a

**Comment by madsskyy** [comment]
can confirm this bug

**Comment by xXJamieXx** [comment]
Theres actually no way that your theory could possibly be the case having looked at the code itself. Multiple people have tested this and the outcome is that its simply a case of random number generation going in your favor and nothing else.
