### ISSUE TITLE
[BUG] Airlifting breaks you out of prison

### ISSUE THREAD

**Issue by Weebait** [ParadoxGamingRP/bugs-and-suggestions#602]
### Your Discord Name

Weeb#5266

### A clear and concise description of what the bug is

If you airlift within the prison after you no longer need to serve any time it takes you to the sandy hospital and counts you as a runaway. If you get checked out of prison after you do not receive any of your items back.

### Steps to Reproduce the Bug

1. go to prison
2. serve your time
3. airlift

### Expected Behavior

If I airlift I am taken to boiling brook penitentiary and I get all my items upon exiting prison

### Screenshots/Videos

N/A

**Comment by madsskyy** [comment]
#600 is already on this topic so im gonna close this one so we dont have 2 of the same bug report open (:
