### ISSUE TITLE
[BUG] stuff staying in ssr registers even after customer paid

### ISSUE THREAD

**Issue by Mac-ceo** [ParadoxGamingRP/bugs-and-suggestions#603]
### Your Discord Name

mac_ceo#7021 Riley Johnson

### A clear and concise description of what the bug is

It seems to keep happening even after a custum has paid for the stuff in the register and has it in there pockets it seems to stay in the register still so it duplicates 

### Steps to Reproduce the Bug

1. place in ssr register {not sure about other places}
2. pay for item
3. check register and see they are still there {doesnt happen every time}

### Expected Behavior

once paid for its no longer in the register

### Screenshots/Videos

my body cam was off

### Log File

[CitizenFX_log_2022-07-24T113022.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9175810/CitizenFX_log_2022-07-24T113022.log) my logs

**Comment by ithegreatgatsby** [comment]
Is this still an issue? Business owners have a more direct way of contacting the dev team through the development discord. Please have the owners reach out there and make a scripting ticket for the issue

**Comment by Mac-ceo** [comment]
recorded 7:30am gmt 2/8/22 https://imgur.com/a/Q4tP14a

**Comment by ithegreatgatsby** [comment]
Going to go ahead and close this if you still have the issue going on please follow my previous comment for more direct help. Thanks!
