### ISSUE TITLE
[BUG] characters are gone, or turned to peds, items missing

### ISSUE THREAD

**Issue by iCLassYx** [ParadoxGamingRP/bugs-and-suggestions#605]
### Your Discord Name

iCLassYx#8576

### A clear and concise description of what the bug is

So mid gaming session, I wasn't able to access my closet and my outfits. 

I then flew out, flew back in and now "Jimmy" Is loading in as a ped and I cant get Jimmy back. 

### Steps to Reproduce the Bug

Character selection screen

Pick Jimmy

Loads in as ped under jimmy

### Expected Behavior

I expect to load in as jimmy class and be jimmy class, with all my outfits and everything under jimmy class

### Screenshots/Videos

![Danny Jimmy](https://user-images.githubusercontent.com/103862374/180666595-dffce9eb-039d-4199-8d38-054ec576640f.png)

### Log File

[Bug report 7-24.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9176752/Bug.report.7-24.txt)

**Comment by NightX43** [comment]
Having the same issue where my character does not pop up and it makes me spawn at different apartments like im creating a new character.

**Comment by CorFinn** [comment]
Might be part of the same issue, but Russell Fogg is gone completely.

https://i.imgur.com/0he4op8.jpeg

**Comment by NightX43** [comment]
Also when you try to get your tattoos back it gives you your other characters tattoos on. Also all my stuff are there just phone contacts and outfits get wiped.

**Comment by iCLassYx** [comment]
Update: My vehicles are gone, My outfits are gone, My contacts are gone and my apartment stash is gone. 

Jimmy the character is back, but all other things listed above are gone

**Comment by tusktheshrew** [comment]
![image](https://user-images.githubusercontent.com/98053772/180676557-c0332b31-1d13-45b7-81ec-411d21107d8e.png)
When trying to log in to Finn

**Comment by iCLassYx** [comment]
Issue is still the same post recent server reset
