### ISSUE TITLE
[BUG] golf course ped is mean

### ISSUE THREAD

**Issue by acqd** [ParadoxGamingRP/bugs-and-suggestions#607]
### Your Discord Name

acqd#4887

### A clear and concise description of what the bug is

whenever I go to the guy behind the golf course to start a house robbery, I make sure to have a tier 3 pelt in my inventory but when I talk to him he just says "no jobs currently available!", but hes been saying this for the past couple irl days so I think somethings up. Ive also seen other people having the same issue. 

### Steps to Reproduce the Bug

go to the house robbery guy with a tier 3 pelt, and talk to him with your third eye 

### Expected Behavior

hell say "no jobs currently available!" 

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/105875968/180827962-c7ffa610-8e23-4b87-9c5e-2ecf44cdb13a.png)

### Log File

[CitizenFX_log_2022-07-25T131745.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9183093/CitizenFX_log_2022-07-25T131745.log)

**Comment by xXJamieXx** [comment]
Should be fixed next restart.
