### ISSUE TITLE
[BUG] Invisible Blotches Within the Lupine Manor

### ISSUE THREAD

**Issue by Weebait** [ParadoxGamingRP/bugs-and-suggestions#608]
### Your Discord Name

Weeb#5266

### A clear and concise description of what the bug is

In certain areas of the lupine manor mostly just up the stairs and Tracy's room the character disappears and all audio from them cuts out. Has happened with everyone that has visited. If this is limited to me then it's the one at postal 823 though I don't see why mine would be special.

### Steps to Reproduce the Bug

1. Enter Lupine Manor
2. Go Upstairs
3. Disappear

### Expected Behavior

The house to act consistently at all times and for me not to vanish by going upstairs

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/tVG4TaGAOyVjc/d1337Vl1C0LF?invite=cr-MSxjRUgsNjQwMDIyMjQs

**Comment by Weebait** [comment]
As an addition when it rains in the city there are water puddles within the apartment and everything makes a wet sound as well as has a glossy look as if outside.

**Comment by JnKTechstuff** [comment]
This is due to the location of the house. You will have to move.
