### ISSUE TITLE
[BUG] Hunting

### ISSUE THREAD

**Issue by Mac-ceo** [ParadoxGamingRP/bugs-and-suggestions#609]
### Your Discord Name

mac_ceo#7021 Riley Johnson

### A clear and concise description of what the bug is

When having an drink ect when in the middle of placing a bait or skining an animal it will say error and then have to fly out to be able to hunt again

### Steps to Reproduce the Bug

1. begin to place down bait
2. have a drink
3. try to place ait get error message again 

### Expected Behavior

if drinking or doing somthing else in the middle of sking or placeing bait for it to stop then be able to replace it or skin after and not have it say error every time till u reset game

### Screenshots/Videos

no video evidence

### Log File

[CitizenFX_log_2022-07-26T113143.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9190870/CitizenFX_log_2022-07-26T113143.log)

belive its theses logs reach out if they are the wrong ones

**Comment by xXJamieXx** [comment]
I believe this should be fixed next restart if you could confirm.
