### ISSUE TITLE
[BUG] Jerry Can Gives Unlimited Gas

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#611]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

The Jerry Can can be used multiple times without emptying.

### Steps to Reproduce the Bug

1. Drive
2. Refuel with Can
3. Drive
4. Refuel with Can

### Expected Behavior

Jerry Can empties after use.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98053772/181384294-dd8d020f-4d74-4813-b6f8-6e1226eea1a0.png)
After Use

### Log File

[FuelJerryCan.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9204028/FuelJerryCan.txt)

**Comment by xXJamieXx** [comment]
Just followed your steps and lost ammo in my fuel can? Need more info on this. 
![image](https://user-images.githubusercontent.com/11248045/183251452-08b936e1-351f-4386-94a1-40556ef79cb2.png)

**Comment by tusktheshrew** [comment]
You can use the Jerry can and lose Ammo, but even when it gets close to 0, you can use it again and again.

**Comment by xXJamieXx** [comment]
Should be fixed next restart.
