### ISSUE TITLE
[BUG]  119 dealership wont sell car and only one car slot switches

### ISSUE THREAD

**Issue by PadawanPepsi** [ParadoxGamingRP/bugs-and-suggestions#614]
### Your Discord Name

PadawanPepsi#6898

### A clear and concise description of what the bug is

I switch a car to the one i wanted and at the top of the third eye menu it shows another car that is physically in front of me. 

I tried to buy the car in front of me with both money as cash and in bank and it wont sell and wont give me any alerts on why the sail fails

### Steps to Reproduce the Bug

go to postal 119 only car slot that switches is the bottom right. Pull out the compact peanut. Super cheap and try to buy it.

### Expected Behavior

should sell me the car. I am able to test drive it no problem but it wont sell it to me

### Screenshots/Videos

https://user-images.githubusercontent.com/96961442/181664770-5e740764-540d-4439-9a92-1901b2d9a20f.mp4

### Log File

[CitizenFX_log_2022-07-29T001615.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9215349/CitizenFX_log_2022-07-29T001615.log)

**Comment by xXJamieXx** [comment]
Peanut should be fixed. I'll check on the other issue with that being the only display vehicle that can be changed.

**Comment by JnKTechstuff** [comment]
Fixed
