### ISSUE TITLE
[ENHANCEMENT] New + Optimizing Haircuts

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#615]
**Your Discord Name**
Shrew#1219

**Describe the annoyance**
Looking through the hairstyles of both the females and males, I see some repetition in the same haircut while going through the hair numbers. I would like to see more personalization in this area, and like to see people wear different kinds of hair styles that fit more of their character. Haircuts I would like to see are like rebel female haircuts or for males some more types of shaggy hair for example.

**To Reproduce**
[Steps to reproduce the annoyance]
1.  Go to Barber Shop
2.  Look Through Options
3. See Repeats

**Requested behavior**
[A clear and concise description of what you want to happen] No copies of haircuts, and new haircuts to fill out the slots.

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]
![image](https://user-images.githubusercontent.com/98053772/181791927-7158e423-a675-4d55-9356-67380cfaca30.png)
![image](https://user-images.githubusercontent.com/98053772/181791979-6182a276-3252-4c0e-9f9e-ddf61c7f0776.png)

**Additional context**
[Add any other context about the enhancement here]

**Comment by ithegreatgatsby** [comment]
This will be sent to the clothing team and we can see what we can find that would work with the server

**Comment by JnKTechstuff** [comment]
Repition is also done by R* for some reason. Everything is double in there on purpose from the base game

**Comment by ithegreatgatsby** [comment]
We are looking into fixing addon hair so they don't clip-through hats. Once we get past that we will look into adding more but in the meantime I will close this out and add it to the clothing team list.
