### ISSUE TITLE
[BUG] Rockford Hills Headpops

### ISSUE THREAD

**Issue by Petrovic247** [ParadoxGamingRP/bugs-and-suggestions#616]
### Your Discord Name

PretenderPatrol#5993

### A clear and concise description of what the bug is

The hills have been a nightmare tonight. Tons of headpops. Going into the area is almost a guarantee. 

### Steps to Reproduce the Bug

1. Go to hills.
2. Pop 
3. Repeated twice personally tonight. With many others experiencing the same

### Expected Behavior

Drive in the hills

### Screenshots/Videos

N/a

### Log File

[CitizenFX_log_2022-07-23T205054.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9224717/CitizenFX_log_2022-07-23T205054.log)

**Comment by xXJamieXx** [comment]
Removed what we believe was causing the issue until we resolve the issue with the offending resource.
