### ISSUE TITLE
[BUG] house decorating issue "too far"

### ISSUE THREAD

**Issue by BOOPBAPBAM** [ParadoxGamingRP/bugs-and-suggestions#618]
### Your Discord Name

boopbapbam

### A clear and concise description of what the bug is

When trying to decorate my house it's saying im currently out of range when standing inside anywhere in the house

### Steps to Reproduce the Bug

1. f1
2. house interaction
3. decorate home 
4. then tells me i have gone out of range

### Expected Behavior

Just act as it did before the tsunami

### Screenshots/Videos

![Screenshot (13)](https://user-images.githubusercontent.com/110313829/182004603-9624d670-48dc-45ce-8783-6a5df0f6cac1.png)

**Comment by madsskyy** [comment]
this should have been fixed today. could you let us know if you're having the same issue still today?

**Comment by JnKTechstuff** [comment]
Fixed
