### ISSUE TITLE
[BUG] postal 500 crash

### ISSUE THREAD

**Issue by acqd** [ParadoxGamingRP/bugs-and-suggestions#620]
### Your Discord Name

acqd#4887

### A clear and concise description of what the bug is

randomly when I drive fast while in the postal 500's or the vinewood area my game crashes. Ill usually be going around 100 mph or faster and my game will just suddenly freeze and crash.

### Steps to Reproduce the Bug

drive over 100 mph while in the vinewood area.

### Expected Behavior

your game crashing 

### Screenshots/Videos

https://cdn.discordapp.com/attachments/840063536624697345/1003442113909899354/unknown.png
this is the crash message 

### Log File

[CitizenFX_log_2022-07-31T220434.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9229912/CitizenFX_log_2022-07-31T220434.log)

**Comment by ithegreatgatsby** [comment]
This seemed to be working better tonight.  Please open up a new bug report if you keep having issues in the area.
