### ISSUE TITLE
[BUG] rubber trees taking 45 minutes to grow

### ISSUE THREAD

**Issue by Stevet636** [ParadoxGamingRP/bugs-and-suggestions#622]
### Your Discord Name

Bigsmoke636#8648

### A clear and concise description of what the bug is

 I think the growing script for rubber tree's might be broken, each crop yield ( i've been doing 6 plants) take's roughly 45-50 minutes to grow with 90% soil fert, and when you get them up to 90% health and 100% growth they still only give one rubber per plant. not sure if this is intentional or not but want yall to know. I've tested this twice so far.

in the past they would take rought 20-25 minutes and getting them above 76% health all the way to 90% they would give 3 rubber per plant with same soil conditions. 

### Steps to Reproduce the Bug

grow rubber tree's 
time them between stages
harvest

### Expected Behavior

for the time & effort put in with the yield I was maybe excepting higher amount of rubber i.e health 70%+ 3 rubber, 75%+ 4 rubber  80%+ 5 rubber ect. 

### Screenshots/Videos

![Screenshot 2022-08-01 215950](https://user-images.githubusercontent.com/110437529/182275643-5f04462a-0593-4bfb-8ad7-034c35a206e0.png)

**Comment by SpiceF0x** [comment]
Added data:

The growth rate seems to be half, this is affecting the health of the crop overall. Even at 74% health I received 1 per tree. I grew Sugar successfully alongside and got 29 Sugar, 10 Rubber.

![image](https://user-images.githubusercontent.com/96963965/182422260-7d752087-6307-4fff-a1c4-db66e45714f3.png)

**Comment by JnKTechstuff** [comment]
Fixed: https://github.com/ParadoxGamingRP/Server-Development/pull/382
