### ISSUE TITLE
[ENHANCEMENT] Tv in court room to be usable

### ISSUE THREAD

**Issue by PadawanPepsi** [ParadoxGamingRP/bugs-and-suggestions#623]
**Your Discord Name**
PadawanPepsi#6898

**Describe the annoyance**
If we could get the TV in the court room to work as a TV then presenting evidence would be that more immersive in the court room

**Requested behavior**
To be able to utilize the TV through /pmms to play sound, video and pictures 

**Screenshots**
https://i.imgur.com/4pYahLE.png

**Comment by ithegreatgatsby** [comment]
We have put in a request to the person that made the town hall interior. Just kinda waiting to see if he comes out with a update with a tv of some kind in it

**Comment by ithegreatgatsby** [comment]
Played with this for a bit and figured something out. Its in live server now!
