### ISSUE TITLE
[BUG] /Try unsuccessful spelt incorrectly 

### ISSUE THREAD

**Issue by Deadles** [ParadoxGamingRP/bugs-and-suggestions#628]
### Your Discord Name

Deadles#7777

### A clear and concise description of what the bug is

Just a really minor thing but when using the /try the unsuccessful is spelt incorrectly.  The current way that it is spelt is "unccessful"

### Steps to Reproduce the Bug

1. use /try until you see the unsuccessful

### Expected Behavior

No expected behavior other than the spelling.

### Screenshots/Videos

https://i.imgur.com/BKWaUbF.png

**Comment by xXJamieXx** [comment]
Fixed next restart.
