### ISSUE TITLE
[BUG] House robbery location unusable

### ISSUE THREAD

**Issue by WillyHDT** [ParadoxGamingRP/bugs-and-suggestions#629]
### Your Discord Name

Will.#0928

### A clear and concise description of what the bug is

Hey, I started a house robbery and the house I was told to rob is one of the Ballers houses. So when I went to the front door it was unlocked and there were no items to steal. I went back to the front door but it was locked and so was the back door. I cant even lockpick the doors even though it is nearly midnight and I don't know what to do.

### Steps to Reproduce the Bug

change the location that house robberies spawn so that I dont have to rob an actual player owned house.

### Expected Behavior

I expected to rob a house that was not owned by a player and get caught by the owner of that house.

### Screenshots/Videos

![FiveM® by Cfx re -  Original  Paradox Gaming RP _ 3+ years _ discord gg_paradoxgaming 8_3_2022 2_26_39 PM](https://user-images.githubusercontent.com/110565752/182697052-4512c390-52fa-45f2-bd76-87e3bd49c69d.png)

**Comment by xXJamieXx** [comment]
Fixed.
