### ISSUE TITLE
[BUG] Tattoos not staying 

### ISSUE THREAD

**Issue by baxepw** [ParadoxGamingRP/bugs-and-suggestions#634]
### Your Discord Name

baxe#0666

### A clear and concise description of what the bug is

I have put tattoos on 3 times now and they stay on unless i change clothes or fly out.

### Steps to Reproduce the Bug

1. Go to tattoo shop 
2. Get sick tattoos 
3. Change clothes or go to sleep for the night
4. Wake up with no tattoos

### Expected Behavior

1. Go to tattoo shop 
2. Get sick tattoos 
3. Change clothes or go to sleep for the night
4. Wake up with tattoos

### Screenshots/Videos

NA

### Extra Notes (Optional)

I put logs from last night when i got the tattoos and when i woke up today let me know if I need to reapply and lose them and get new logs

### Log File

[CitizenFX_log_2022-08-05T000036.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9273949/CitizenFX_log_2022-08-05T000036.log)
[CitizenFX_log_2022-08-05T225059.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9273950/CitizenFX_log_2022-08-05T225059.log)

**Comment by xXJamieXx** [comment]
Should be fixed next restart.
