### ISSUE TITLE
[BUG] House props disappearing

### ISSUE THREAD

**Issue by LtNathan235** [ParadoxGamingRP/bugs-and-suggestions#635]
### Your Discord Name

Lnathan#2764

### A clear and concise description of what the bug is

All props in the house poof, happens randomly and unsure how to reproduce bug.

### Steps to Reproduce the Bug

Buy a house
set up props 
randomly wait for them to poof

### Expected Behavior

For everything in the house to not poof 

### Screenshots/Videos

![Uploading image.png…]()

**Comment by xXJamieXx** [comment]
Should be fixed.
