### ISSUE TITLE
[BUG] House Robberies Not Working

### ISSUE THREAD

**Issue by Drunkle716** [ParadoxGamingRP/bugs-and-suggestions#636]
### Your Discord Name

Drunkle716#7571

### A clear and concise description of what the bug is

Cannot get a house job no matter how many times you go back to the place with the right thing.

### Steps to Reproduce the Bug

1. Got to the place
2. Do the thing
3. "There are no jobs available"

### Expected Behavior

1. Go to the place
2. Do the thing
3. You get a house job

### Screenshots/Videos

https://i.imgur.com/F3LaADa.png
https://i.imgur.com/8TiaGO9.jpeg

### Log File

[CitizenFX_log_2022-08-06T172618.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9275499/CitizenFX_log_2022-08-06T172618.log)

**Comment by SpiceF0x** [comment]
Same issue:

I got the email advising I had a job 15 minutes after leaving the guy who likes to hand out robberies....
There was no GPS on my map, and no location marked.
The traded item remained in my pockie the whole time.

There **was** a log associated with the above in discord saying I've reserved one.

Every other time I got no jobs available, I am sad I can't rob people of their stuff :(

**Comment by xXJamieXx** [comment]
**Should** be fixed next restart...

**Comment by Drunkle716** [comment]
Tried again after restart and still the same issue.

**Comment by xXJamieXx** [comment]
> Tried again after restart and still the same issue.

Then clearly you visited when it was on cooldown...
