### ISSUE TITLE
[BUG] Bank Trucks Scuffed

### ISSUE THREAD

**Issue by natashajoan** [ParadoxGamingRP/bugs-and-suggestions#637]
### Your Discord Name

Natasha_ahsataN#7098

### A clear and concise description of what the bug is

I've been told by multiple people that they were having scuffed bank trucks lately, I thought they may have been a one off until last night when I had 3 in a row. 

Signal heard near Hookies, we fount the truck just up the road, stopped the guards, When I third eye'd the back doors, there was no option to place the thermite, was just acting like the normal trucks that drive throughout the city.  I tried the radio scanner again, no notification regarding the previous robbery, so we head to Paleto. 

Got the message in Paleto that it was heard, the truck drove a little then poofed. Tried the scanner again and that's when I got the message regarding the previous robbery heard. 

We waited a while after the cooldown, to try again. We tried a different location than the previous two, so we tried Harmony, Traffic heard, saw the truck, drivers were spooked so we had to follow down the road, shot the guards, went to thermite the back of the truck, same issue as the first truck, unable to thermite. Still able find another signal. 

### Steps to Reproduce the Bug

1. Scan for a signal
2. Signal heard
3. Shoot the guards
4. Go to thermite the back
5. No option to thermite the back doors
6. Still be able to scan for another frequency 

### Expected Behavior

I expect that when I find a truck, that I'm able to thermite the back doors and continue with the truck, then be unable to scan for another truck afterwards. 

### Screenshots/Videos

N/A

**Comment by iCLassYx** [comment]
Having a similar issue just now when we just tried.

**Comment by natashajoan** [comment]
Tried one again, scuffed. Shot the guards, couldn’t third eye the back doors. Tried scanner again, traffic of a robbery previously heard.

**Comment by ithegreatgatsby** [comment]
Need log files or screenshot F8 when you are trying to do it so the the scripting team has something to go by

**Comment by EmmettIsTRASH** [comment]
I've got this one from a truck earlier today if it helps

[CitizenFX_log_2022-08-19T001818.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9378423/CitizenFX_log_2022-08-19T001818.log)

**Comment by BrotherDayZ** [comment]
Tried one as well. We tried relocating the bank truck as well as looking all around the bank truck.

[CitizenFX_log_2022-08-25T041408.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9422266/CitizenFX_log_2022-08-25T041408.log)

**Comment by xXJamieXx** [comment]
Updates were pushed to resolve issues, open a new issue if there is still problems.
