### ISSUE TITLE
[BUG] Can't see scene outside

### ISSUE THREAD

**Issue by TheGraveyardShift** [ParadoxGamingRP/bugs-and-suggestions#638]
### Your Discord Name

TheGraveyardShift#6865

### A clear and concise description of what the bug is

I use scenes both inside and outside up at my pad. Lately I can only see them when im inside. When i walk out my door all scenes disappear.

### Steps to Reproduce the Bug

1. Go inside someplace with interior
2. place scene
3. walk outside

### Expected Behavior

I hope to be able to only see outside scenes outside and inside scenes inside.

### Screenshots/Videos

https://user-images.githubusercontent.com/104471236/183314529-13f3fd7c-cfe9-434d-9304-47072b7df02c.mp4

### Log File

[CitizenFX_log_2022-08-07T224215.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9277734/CitizenFX_log_2022-08-07T224215.log)

**Comment by xXJamieXx** [comment]
This can't be fixed unfortunately. That scene is too close to the interior so it treats it as inside. If you want to see it outside you'll have to place it further away.
