### ISSUE TITLE
[BUG] Can't delete items from house

### ISSUE THREAD

**Issue by madsskyy** [ParadoxGamingRP/bugs-and-suggestions#639]
### Your Discord Name

madsskyy #2165

### A clear and concise description of what the bug is

I can't delete items from my house, but I could yesterday. 

### Steps to Reproduce the Bug

1. Go into house
2. Open design menu
3. Go to my objects
4. Select an object
5. Delete it
6. Exit decorating menu
7. Item reappears

### Expected Behavior

Item disappears and is deleted

### Screenshots/Videos

[2022-08-07 19-10-01.zip](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9277745/2022-08-07.19-10-01.zip)

### Log File

[CitizenFX_log_2022-08-07T230352.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9277741/CitizenFX_log_2022-08-07T230352.log)

**Comment by madsskyy** [comment]
someone else's logs too whos having the same issue
[bug_report.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9277765/bug_report.txt)

**Comment by xXJamieXx** [comment]
Unable to be reproduced.
