### ISSUE TITLE
[BUG] Stairs / Flickering issue in Wolfs

### ISSUE THREAD

**Issue by SpiceF0x** [ParadoxGamingRP/bugs-and-suggestions#640]
### Your Discord Name

spicedf0x#2127

### A clear and concise description of what the bug is

When I go into the office with someone, people cannot see me and the probably generally happens around the stairs or going up/down the stairs. 

I have to ragdoll in order for them to see me properly and hear me again. I don't seem to have this issue with other people, or I'm yet to run into it so you're probably gonna say it's a me issue but I don't know how. 

I don't know if there's a prop that could have caused it, I don't remember it happening without this mapping? 

### Steps to Reproduce the Bug

1. Go into Wolfs with someone else
2. Use the stairs
3. Fade in and out of existence 

### Expected Behavior

Have people see me / hear me without having to ragdoll. 

### Screenshots/Videos

https://clips.twitch.tv/LittleModernSpiderDoritosChip--b7FORSsWz1JKx-H

### Log File

Not sure this will help..

[CitizenFX_log_2022-08-08T014331.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9278037/CitizenFX_log_2022-08-08T014331.log)

**Comment by ithegreatgatsby** [comment]
Confirmed this just need to figure out why it's doing it. I believe whoever enters first is the one that is invisible in the stare area

**Comment by ithegreatgatsby** [comment]
im gonna just close this im not sure why it does it but if it becomes a bigger issue ill try to look more into it or if the office gets used more often with more people inside
