### ISSUE TITLE
Able to collect pay check multiple times from trash

### ISSUE THREAD

**Issue by GusTheSmashBus** [ParadoxGamingRP/bugs-and-suggestions#641]
### Your Discord Name

GusTheSmashBus#0779

### A clear and concise description of what the bug is

Getting paid way more for trash jobs than you should be. Once you complete a trash job with a friend if they didn't get the truck and try to get paid before you it wont pay both of you but if you click on paycheck it acts like its not paying you but it is.

### Steps to Reproduce the Bug

1.Have a friend get a trash job and do it together 
2.You go try to get paid before friend.
3.Person that started job click on get pay check.

### Expected Behavior

Expected to get paid the regular amount. 

### Screenshots/Videos

Don't have any

### Log File

[CitizenFX_log_2022-08-07T232551.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9278594/CitizenFX_log_2022-08-07T232551.log)

**Comment by xXJamieXx** [comment]
Fixed.
