### ISSUE TITLE
[BUG] Bikini Auto - empty engine after benny's repair

### ISSUE THREAD

**Issue by andythewookie** [ParadoxGamingRP/bugs-and-suggestions#642]
### Your Discord Name

andythewookie#0798

### A clear and concise description of what the bug is

As per our instructions for pulling and engine, I repaired a customers car (Annis S-230) via benny's in the workshop. after some RP of pulling the engine out using the hoist the engine was empty of the usual components (block, camshaft, etc...) I explained to the customer that there was some issues and we could install the turbo at a later date. I then proceeded to test again on my own car (Annis ZR-300 euro import) to save upsetting any more customers and the results were the same no engine components. I tried doing a double repair from benny's and the problem still remained.

### Steps to Reproduce the Bug

Pull car into Bikini Auto Shop
Repair Via F1 menu (benny's)
pull engine with hoist
check for engine components
- no engine components push into parking and remove for engine to be replaced - 

### Expected Behavior

upon pulling an engine, we should be seeing the main engine components that every car needs block, head, camshaft, pistons, etc

### Screenshots/Videos

No Pictures taken feel free to contact myself on discord and i will happily stream the issue

### Log File

[CitizenFX_log_2022-08-08T100120.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9281516/CitizenFX_log_2022-08-08T100120.log)

**Comment by OwlCherry** [comment]
This also happened on a futo yesterday.

As per Chris instruction, I placed new components in, and it all saved as I double and triple checked.

Karin futo |  7JZ317YW 

![2Q6bPTm](https://user-images.githubusercontent.com/97353529/183414559-22a32969-48a1-4c23-9ce1-01905742014d.png)

![UfX4rEh](https://user-images.githubusercontent.com/97353529/183414724-073a9df2-eb14-44c3-80ba-79be99f3bc64.png)

**Comment by xXJamieXx** [comment]
Noticed an error that could have been causing this which I've fixed so let me know if its still happening.
