### ISSUE TITLE
[ENHANCEMENT] alter or change how afk is detecting afk people

### ISSUE THREAD

**Issue by stbadreturns** [ParadoxGamingRP/bugs-and-suggestions#643]
**Your Discord Name**
Stbadreturns#9043

**Describe the annoyance**
You can be doing things in city having a meeting ect where because the afk timer is so short you end up needed to break immersion and get up and physically walk around for it to detect it. 

**To Reproduce**

1. The detection only seems to be looking for character movement like W,A,S,D key even if your tabbed in and using voip it will still trigger the afk timer 

**Requested behavior**
I have a few ideas,
1. Remove it as a vip perk maybe? (Obviously if it's abused there other issues)
2. Make it so the afk detector can see that your talking and obviously not afk
3. Maybe extend the time of the afk timer so it happens less frequently?

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by xXJamieXx** [comment]
Detects if you're talking next restart.
