### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by anicedog97** [ParadoxGamingRP/bugs-and-suggestions#645]
### Your Discord Name

anicedog97#4516

### A clear and concise description of what the bug is

Went with my friend and talked to the trash local to start the job friend hotwired garbage truck to get keys and then we went and went from location to location until job was complete. once complete we returned to the trash depot and parked on the designated drop off and talked to the local to collect pay slip trying to finish the job when i noticed i wasnt able to we tried to adjust the truck but no matter where in the parking lot we moved it i was still unable to collect the pay slip or turn the truck in.,

### Steps to Reproduce the Bug

1. take trash job from local
2. have another person hotwire truck to get keys 
3. try to turn truck back in and collect pay slip

### Expected Behavior

be able to collect pay slip and get paid

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/110896699/183611660-adf03323-36eb-40a0-a83a-e8a588779fa2.png)
![image](https://user-images.githubusercontent.com/110896699/183611701-e4040cf9-6eba-4e3c-89b8-ef0e9ced3155.png)

### Log File

[CitizenFX_log_2022-08-09T091137.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9289033/CitizenFX_log_2022-08-09T091137.log)

**Comment by xXJamieXx** [comment]
@anicedog97 why would you hotwire the garbage truck? What?

**Comment by xXJamieXx** [comment]
You probably just had to get in the drivers seat and then try collecting again and it'd work. Sounds like user error to me.
