### ISSUE TITLE
[BUG] Bikini Automotive

### ISSUE THREAD

**Issue by RizzleMyNizzle** [ParadoxGamingRP/bugs-and-suggestions#646]
### Your Discord Name

RizzleMyNizzle#8454

### A clear and concise description of what the bug is

I had a buffalo stx that had no parts in the engine… I stored it in customer garage first, Benny repair, then pulled engine and car had no parts in engine. Had to craft all new parts for the engine.

### Steps to Reproduce the Bug

Stored in customer parking
Benny repair
Pulled engine

### Expected Behavior

For engine parts to be in the engine...

### Screenshots/Videos

![FiveM_b2699_GTAProcess_S78lj4tpH1](https://user-images.githubusercontent.com/106287551/183755264-3619be43-26c1-457b-bad8-317c4ed7074f.png)

In case that didnt work...
https://i.imgur.com/uwf8zKw.png

### Log File

[CitizenFX_log_2022-08-09T183658.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9294326/CitizenFX_log_2022-08-09T183658.log)
[CitizenFX_log_2022-08-09T183852.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9294327/CitizenFX_log_2022-08-09T183852.log)
[CitizenFX_log_2022-08-09T183919.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9294328/CitizenFX_log_2022-08-09T183919.log)

**Comment by ithegreatgatsby** [comment]
Has there been any other issues? I have not heard about anything else in a few days

**Comment by ithegreatgatsby** [comment]
Closing this till we start getting more info as to what has been pinned in automotive enouncements and then Once i get that info I will open up a scripting ticket
