### ISSUE TITLE
[BUG] Opening metal boxes and/or treasure chests while in car trunks may delete/overwrites plastic amount in car trunks

### ISSUE THREAD

**Issue by mjb328** [ParadoxGamingRP/bugs-and-suggestions#648]
### Your Discord Name

MJB328#5303

### Steps to Reproduce the Bug

1. use a mule
2. access a trunk
3. fill the trunk with items(to try and trigger glitch "accidentally tranfer/misclick with 5 empty water bottles and 1 radio)
4. put 4 empty bottle in the trunk leave 1 empty bottle in your pocket along with radio
5. now take the radio and place it where the 4 other bottle are in the mule trunk(simulate an accident/misclick)
6. when the 4 bottle are transferred to your pocket stack them with the 5th and put them in the trunk 
7. take the radio back out after u put the bottles back in. (take a screenshot of everything in the trunk along with the empty water bottles) before exiting the mule trunk
8. see was got deleted in the mule trunk(screenshot for reference)

### Expected Behavior

I expect items to not be deleted when I accidentally stack the wrong items to together in a mule trunk

### Screenshots/Videos

will try replicate asap.

### Log File

forgot to download before reset, but Ill provide some as soon as i can replicate it.

**Comment by mjb328** [comment]
its not metal metal boxes i think i found the cause and i have video but file too big

**Comment by ithegreatgatsby** [comment]
Upload video to youtube or streamable

**Comment by mjb328** [comment]
One bit of context the video doesn't show it cuz I preemptively recorded this but I lost my 12 flounders in my trunk and i believe it was because i switched the bass and cod think they were the same when trying to stack them. after the video cut off i go back into my mule trunk and the flounders are gone.

https://streamable.com/hy6jti

**Comment by ithegreatgatsby** [comment]
Make sure you are never in one inventory trying to open up another. So don't be in a trunk and then open up something like that metal box and such it can error out the scrips from the sounds of it. But other then that this cant really be reproduced on my end

**Comment by mjb328** [comment]
just happened again this time with empty water bottles and a radio, i lost an ice box but thank it was empty. for some reason my recording program wont work so i have no video of it.

**Comment by JnKTechstuff** [comment]
Spamming stuff open will continue to net in a loss of shit
