### ISSUE TITLE
[ENHANCEMENT] Decrease plastic bag creation time

### ISSUE THREAD

**Issue by Malfoo** [ParadoxGamingRP/bugs-and-suggestions#650]
**Your Discord Name**
Malfo#2515

**Describe the annoyance**
Speed up the process of making plastic bags. It is painstakingly slow. 

**To Reproduce**
[Steps to reproduce the annoyance]
1. Get plastic for bags
2. Use weed table to make bags
3. Currently takes forever for 50

**Requested behavior**
Honestly looking to have the time cut in half.

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by JnKTechstuff** [comment]
Fixed: https://github.com/ParadoxGamingRP/Server-Development/commit/c2060e7ea025778236f1097faf3438429879f3a8
