### ISSUE TITLE
[ENHANCEMENT] New Radio Proximity Feature is Rough

### ISSUE THREAD

**Issue by Petrovic247** [ParadoxGamingRP/bugs-and-suggestions#651]
**Your Discord Name**
PretenderPatrol#5993

**Describe the annoyance**
When radio are used in proximity of voip you cannot hear on the radio anymore. This leads to people on the very edge of the proximity that you cannot hear anything. This is an issue on robberies as there is often people on the edge of the someones voice.

**To Reproduce**
[Steps to reproduce the annoyance]
1.All Officer affected. Unsure on civs. 
2. 
3. 

**Requested behavior**
Back to the old way where radio took priority over voip.

**Comment by ithegreatgatsby** [comment]
We reverted back to a older version of the voice chat so is this issue still going on?

**Comment by Petrovic247** [comment]
Nope, been great since the revert.
