### ISSUE TITLE
[ENHANCEMENT] Be able to roll joints with dried weed

### ISSUE THREAD

**Issue by TheGraveyardShift** [ParadoxGamingRP/bugs-and-suggestions#654]
**Your Discord Name**
TheGraveyardShift#6865

**Describe the issue**
I try and combine the dried marijuana bud with rolling papers and nothing happens. I've tried with it bagged and still nothing.

**To Reproduce**
1. dry out buds
2. baggie buds
3. drag buds to rolling papers

**Requested behavior**
Would like to be able to roll personal doinks.

**Screenshots**
The rolling papers even say for cannabis rollin
 
![image](https://user-images.githubusercontent.com/104471236/184510901-70c67d8d-0696-4725-ae7b-33ba33582859.png)

https://user-images.githubusercontent.com/104471236/184510932-cf69539d-60c8-4750-9363-db6e1c1a816c.mov

**Comment by ithegreatgatsby** [comment]
This is not a bug and is not the intent of the weed growing script. This also would take away from the businesses. The point of weed growing right now is to just sell to locals as an added petty crime thing civs can do

**Comment by TheGraveyardShift** [comment]
Then will rolling papers be fazed out?
