### ISSUE TITLE
[BUG] PD as a Whole experiencing MDT/ Third Eye issues

### ISSUE THREAD

**Issue by StealthyRiot** [ParadoxGamingRP/bugs-and-suggestions#655]
### Your Discord Name

Stealthy_Riot#9382

### A clear and concise description of what the bug is

Appears to be random, but our ability to pull out the MDT stops working as well as being unable to pull out weapons, Also unable to cuff and experiencing a bunch of third eye issues. See video for specific details. May have started after I tried calling tow with my third eye? Log will be attached and the event occurs at the very end where I fly out. I believe it started within the past few days. 

This bug has been experienced by
-Holloway
-Busche
-Wallace
-Busta
-and more officers

### Steps to Reproduce the Bug

Unknown how to reproduce at this moment, will update as we get more info.
It appears to possibly be related to the new radios. 

### Expected Behavior

Expect to be able to use third eye for cuffing, putting people in a vehicle, tow, etc

### Screenshots/Videos

https://www.twitch.tv/videos/1562255325

### Log File

[CitizenFX_log_2022-08-14T200944.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9334530/CitizenFX_log_2022-08-14T200944.log)

**Comment by StealthyRiot** [comment]
Quick Update on the issue: It does appear to be related to our new radios. Usually when we are experiencing these issues, we are talking in city to each other with a "radio voice" even though we are not talking on the radio.

**Comment by ithegreatgatsby** [comment]
Trying to reproduce this but so far not been able to. Look to be only affecting LEO. Any extra info will be helpful thanks

**Comment by StealthyRiot** [comment]
> Trying to reproduce this but so far not been able to. Look to be only affecting LEO. Any extra info will be helpful thanks

We're going to keep trying to collect info. Most of the time it happens is shortly after exiting a vehicle. 

I've have had a couple people tell me it's still happening even after this evenings tsunami. 
-Officer Park
-Officer Romero

Going into your vehicle and exiting again seems to temporarily fix it. But I think it occurs more frequently till you fly out again

**Comment by StealthyRiot** [comment]
Another Video (From Yesterday) 
https://www.twitch.tv/videos/1564260302
Another Video (From Tonight) - 5 minute mark shows 3rd eye bug
https://www.twitch.tv/videos/1564275792
Log of the error (From Tonight) - Occurred near the VU
[CitizenFX_log_2022-08-17T015052.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9356127/CitizenFX_log_2022-08-17T015052.log)

**Comment by OwlCherry** [comment]
[CitizenFX_log_2022-08-17T175147.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9365151/CitizenFX_log_2022-08-17T175147.log)

**Comment by JnKTechstuff** [comment]
This should fix it: https://github.com/ParadoxGamingRP/Server-Development/commit/ef6e8725391cfb62837f3d7eae0a04258d0bef9b

**Comment by StealthyRiot** [comment]
I had 0 problems tonight and did not hear of any third eye complaints. I think this is fixed. Thank you!
