### ISSUE TITLE
[BUG] Prison Alerting after send off

### ISSUE THREAD

**Issue by StealthyRiot** [ParadoxGamingRP/bugs-and-suggestions#656]
### Your Discord Name

Stealthy_Riot#9382

### A clear and concise description of what the bug is

After sending a suspect to prison, occasionally the alarm goes off even though they are spawning within the Jail.

### Steps to Reproduce the Bug

1. Send a suspect to jail

### Expected Behavior

Suspect goes to jail without alarm alerting

### Screenshots/Videos

Can provide video if needed. Alarm went off immediately after sending them.

**Comment by baxepw** [comment]
I believe this happens when they are sent they headpop immediately and thats what sets off the alarm
