### ISSUE TITLE
[BUG] Lockpicking parking spot setting of Residential Alarm and Stolen Car

### ISSUE THREAD

**Issue by baxepw** [ParadoxGamingRP/bugs-and-suggestions#658]
### Your Discord Name

baxe#0666

### A clear and concise description of what the bug is

I was at NS Tuning and accidentally used my lock pick while standing on a parking spot for the garage. When I did cops showed up and said it set off a residential alarm. I did it again and it set off a stolen car alarm. Yes the parking spot was empty. 

### Steps to Reproduce the Bug

1. Stand on parking spot
2. Use lockpick
3. PD gets alerted of Residential alarm or stolen car

### Expected Behavior

Nothing happens when a lockpick is used over a parking spot

### Screenshots/Videos

https://streamable.com/8yo4jo

### Log File

[CitizenFX_log_2022-08-17T151738.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9364961/CitizenFX_log_2022-08-17T151738.log)

**Comment by OwlCherry** [comment]
[CitizenFX_log_2022-08-17T160136.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9365143/CitizenFX_log_2022-08-17T160136.log)
[CitizenFX_log_2022-08-17T175119.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9365145/CitizenFX_log_2022-08-17T175119.log)
[CitizenFX_log_2022-08-17T175147.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9365147/CitizenFX_log_2022-08-17T175147.log)

**Comment by xXJamieXx** [comment]
I imagine you completed a house robbery earlier and it appears it wasn't clearing the mission so that should be resolved after restart. As for the stolen car, there is a car pretty close which is what was triggering it. It wouldn't do the animation if there wasn't something close enough. I've lowered the range slightly.
