### ISSUE TITLE
[BUG] Pool tables cannot be interacted with

### ISSUE THREAD

**Issue by OwlCherry** [ParadoxGamingRP/bugs-and-suggestions#659]
### Your Discord Name

OwlCherry#6969

### A clear and concise description of what the bug is

Pool table is broken at Skull Island. Cant rack or play

### Steps to Reproduce the Bug

1. approach pool table with cue stick
2. Third eye to set normal or 8ball
3. Nothing happens 

### Expected Behavior

Should rack balls and play normally

### Screenshots/Videos

No Video

### Log File

[CitizenFX_log_2022-08-17T175147.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9366190/CitizenFX_log_2022-08-17T175147.log)
[CitizenFX_log_2022-08-17T175119.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9366191/CitizenFX_log_2022-08-17T175119.log)

**Comment by OwlCherry** [comment]
https://i.imgur.com/mhDshiF.png

**Comment by ithegreatgatsby** [comment]
Confirmed all tables https://cdn.discordapp.com/attachments/926424477049438258/1009577701776044124/s0f60asQwh.png

**Comment by JnKTechstuff** [comment]
> Confirmed all tables https://cdn.discordapp.com/attachments/926424477049438258/1009577701776044124/s0f60asQwh.png

unrelated

**Comment by xXJamieXx** [comment]
Was able to play. Need more info if this is still an issue.

**Comment by xXJamieXx** [comment]
Can't reproduce.
