### ISSUE TITLE
[BUG] No GPS in Camera Mode in Phoenix 1

### ISSUE THREAD

**Issue by SpiceF0x** [ParadoxGamingRP/bugs-and-suggestions#660]
### Your Discord Name

spicedf0x#2127

### A clear and concise description of what the bug is

I'm not 100% this is a bug, cos I swear there's times I've seen it and times I haven't. I'm reporting it in case.

There is no GPS available when in the camera, if it's not a bug, it would be useful for it to be a thing for comms to call out postals

### Steps to Reproduce the Bug

1. Use 'e' for camera mode on phoenix 1
2. no GPS showing

### Expected Behavior

GPS to show even when in camera mode, as you're still in a vehicle. Or, something to add to the lock-on for postals for call outs?

### Screenshots/Videos

![20220817235141_1](https://user-images.githubusercontent.com/96963965/185260282-4e0dd0fb-7358-46ff-ad91-67656e0ca998.jpg)

**Comment by xXJamieXx** [comment]
Fixed next restart.
