### ISSUE TITLE
[BUG] nightclub bouncer is mean

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#661]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

The nightclub won't let you stay in, even if you run in.

### Steps to Reproduce the Bug

1. Press E to enter club
2. The club kicks you back out.

### Expected Behavior

When you enter you can stay in the club.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98053772/185435061-acde17f2-08ca-429a-aa9d-d7636f2ba43c.png)
![image](https://user-images.githubusercontent.com/98053772/185435231-18087ede-8fae-4c9c-955f-81d2a1472440.png)

**Comment by ithegreatgatsby** [comment]
Confirmed, No Error's Could be due to removing the dancing peds on the inside

**Comment by xXJamieXx** [comment]
Fixed next restart.
