### ISSUE TITLE
[BUG] PD MotorPool Not Working

### ISSUE THREAD

**Issue by 211Walker** [ParadoxGamingRP/bugs-and-suggestions#662]
### Your Discord Name

tonytone883#4146

### A clear and concise description of what the bug is

After logging on duty as HC and going down to the motor pool, I am able to see every option other than open motorpool. 
Officers where unable to pull out cars, some could pull the out but don’t have keys, 

### Steps to Reproduce the Bug

1. on duty
2. third eye the motorpool guy
3. click on Open MotorPool
4. nothing happens

### Expected Behavior

1. on duty
2. third eye the motorpool guy
3. click on Open MotorPool
4. get MotorPool car

### Screenshots/Videos

https://imgur.com/u3ubdhP

**Comment by wallace296** [comment]
https://streamable.com/n3r4ba skip half way in video  PIU came out grey painted it has no tune on it. and we have to hotwire all of our cars in pd. state cars coming out with LSPD livery. 

Screen shots of f8 https://i.imgur.com/bFOaXSJ.jpeg

**Comment by BBstud44** [comment]
Hello this happened at 5:20pm PST on 8/19/2022 
Screen Shots:
https://i.imgur.com/TjSwClv.jpeg
https://i.imgur.com/MPVEQ0k.jpeg

**Comment by xXJamieXx** [comment]
Fixed.
