### ISSUE TITLE
[BUG] leg holster (holster 154 for men and 125 for women) doesn't work

### ISSUE THREAD

**Issue by Dez505** [ParadoxGamingRP/bugs-and-suggestions#663]
### Your Discord Name

Dez505#1103

### A clear and concise description of what the bug is

if you put on the leg holster and try to pull your gun your gun will pull like you don't have a holster on

### Steps to Reproduce the Bug

1. put on  holster 154 for men and 125 for women
2. pull out gun 

### Expected Behavior

gun pulls out like you dont have a holster

### Screenshots/Videos

N/a

**Comment by xXJamieXx** [comment]
Waiting for holster numbers then they will all be added again.

**Comment by Dez505** [comment]
its holster 154 for men and 125 for women

**Comment by xXJamieXx** [comment]
Fixed.
