### ISSUE TITLE
[ENHANCEMENT] Trunk size

### ISSUE THREAD

**Issue by Mac-ceo** [ParadoxGamingRP/bugs-and-suggestions#664]
**Your Discord Name**
mac_ceo#0001

**Describe the annoyance**
2 vehicles could be the same size or one could be smaller but have a larger trunk space for example the caracara 4x4 has 60 trunk space but the vision which has the same 'area/size trunk' has 120 to add the caracara 4x4 is a much larger truck in general

**To Reproduce**
[Steps to reproduce the annoyance]
1. look into caracar 4x4 trunk see 60 weight
2.look into bision trunk see 120
3. compare size find the the bision has more space but is the smaller vehicle

**Requested behavior**
trunks of cars and trucks ect to have larger trunk space so they are equal with each other

**Screenshots**
https://imgur.com/a/yYalxgx
https://imgur.com/a/DoIR0Wq
https://imgur.com/a/6rbKSL5
https://imgur.com/a/eGBzhAO

**Comment by ithegreatgatsby** [comment]
It's how GTA makes their vehicles. Cars that are classified as like industrial ETC. So not something that we could fix or worth changing since most of those vehicles are normally just used for storage and or driving to go fishing for a bit and then that's it.
