### ISSUE TITLE
[BUG] dying 

### ISSUE THREAD

**Issue by Mac-ceo** [ParadoxGamingRP/bugs-and-suggestions#665]
### Your Discord Name

mac_ceo#0001

### A clear and concise description of what the bug is

When getting downed the option for airlifting and the timer doesn't show up and the person cant be escorted 

### Steps to Reproduce the Bug

1.get downed
2. see no options on screen
3. get gett escorted

### Expected Behavior

when getting downed the options and text is shown on the screen and the person is able to get escorted 

### Screenshots/Videos

n/a

### Log File

[CitizenFX_log_2022-08-20T140024.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9387353/CitizenFX_log_2022-08-20T140024.log)

**Comment by xXJamieXx** [comment]
Temporary issue resolved with a relog.
