### ISSUE TITLE
[BUG] Can't swap boats at dealership

### ISSUE THREAD

**Issue by Cheag** [ParadoxGamingRP/bugs-and-suggestions#666]
### Your Discord Name

Cheag#7205

### A clear and concise description of what the bug is

im trying to buy a dinghy boat at the boat shop but it shows me the wrong boat

### Steps to Reproduce the Bug

1. go to the boat shop and third eye one of the boats (sometimes it doesnt work when you third eye it)
2. select any boats 
3. thats it

### Expected Behavior

i thought when i third eyed it. It would let me buy the boat i want. It doesnt matter which boat i select. It still shows up the same boat.

### Screenshots/Videos

i dont have any

### Extra Notes (Optional)

also only the boat on the left is changing when you select a boat on the right side

**Comment by xXJamieXx** [comment]
Fixed next restart.
