### ISSUE TITLE
[BUG] Changing plates wipes your trunk/glove

### ISSUE THREAD

**Issue by SpiceF0x** [ParadoxGamingRP/bugs-and-suggestions#667]
### Your Discord Name

spicedf0x#2127

### A clear and concise description of what the bug is

If you pay to change your license plate, then your glove box and trunk are wiped of its contents

### Steps to Reproduce the Bug

1. Get new car
2. Change plate at Bennys
3. Lose stuff in car

### Expected Behavior

It's still the same car, keep ya stuff. 

### Screenshots/Videos

no thank you

**Comment by xXJamieXx** [comment]
Fixed next restart.
