### ISSUE TITLE
[BUG] Methanol Fuel Can Has infinite Fuel 

### ISSUE THREAD

**Issue by wallace296** [ParadoxGamingRP/bugs-and-suggestions#668]
### Your Discord Name

Wallace316#5863

### A clear and concise description of what the bug is

When you use the Methanol fuel can it will always fill up the viper but never empty the can at all. 

### Steps to Reproduce the Bug

use methanol can on piu viper 
fill up viper
re pull out can it will either take out barely any fuel. or not any at all from the can itself 

### Expected Behavior

to empty the fuel can. 
when you fill it up it does not move either 

### Screenshots/Videos

Use the Orange Methanol fuel can. it is like how the jerry can was

**Comment by xXJamieXx** [comment]
Unable to reproduce.
