### ISSUE TITLE
[ENHANCEMENT] Schafter V12 Car

### ISSUE THREAD

**Issue by irvs17** [ParadoxGamingRP/bugs-and-suggestions#669]
### Your Discord Name

Irvs17 (EU)#2996

### A clear and concise description of what the bug is

I cannot buy the Schafter V12, Anywhere but i can by the Original Schafter and the LWB

### Steps to Reproduce the Bug

You cant because the car does no exist in the server

### Expected Behavior

N/A

### Screenshots/Videos

N/A

### Extra Notes (Optional)

Please add this car at a slightly lower price that the LWB perhaps 13,000

**Comment by xXJamieXx** [comment]
This was added.
