### ISSUE TITLE
[BUG] PIU Engine Gets Replaced with Default Engine

### ISSUE THREAD

**Issue by BrotherDayZ** [ParadoxGamingRP/bugs-and-suggestions#671]
### Your Discord Name

BDZ#0001

### A clear and concise description of what the bug is

PIU Engine when pulling it out the car switches to default. This issue is persistent with server restarts. Engine needs to be swapped out by Emily each time we want to use it. 

### Steps to Reproduce the Bug

1. Go to Motorpool
2. Pull out the Dodge Viper
3. Engine doesnt sound very pretty and the performance sucks cause its using the wrong engine.

### Expected Behavior

Car to go vroom vroom

### Screenshots/Videos

N/A

**Comment by JnKTechstuff** [comment]
Fixed last night
