### ISSUE TITLE
[BUG] Cant craft weed bags

### ISSUE THREAD

**Issue by stefanr50** [ParadoxGamingRP/bugs-and-suggestions#672]
### Your Discord Name

Daddy stefan#8048

### A clear and concise description of what the bug is

I bought a weed table placed it in my apartment and when i tried to craft some weed bags it said you don't have the right items but i did have 126 plastic and when i tried crafting it my inventory disappeared i have crafted before this is the first time hapening

### Steps to Reproduce the Bug

I don't know but it didn't work for me the weed bags here are some pictures and tjust so you now i put  quantity in the middl
![Screenshot_37](https://user-images.githubusercontent.com/111882593/186167538-247c1aa3-c800-440e-bbc2-a305343b6298.png)
![Screenshot_35](https://user-images.githubusercontent.com/111882593/186167552-b21b9d52-12c5-477f-abc9-44e0d2cd1f15.png)
![Uploading Screenshot_34.png…]()
![Uploading Screenshot_33.png…]()
![Uploading Screenshot_32.png…]()

e

### Expected Behavior

To craft a weed bag

### Screenshots/Videos

![Screenshot_37](https://user-images.githubusercontent.com/111882593/186167776-0ff0aa92-aab3-4a53-8113-9f89d8e658a5.png)
![Uploading Screenshot_35.png…]()
![Uploading Screenshot_34.png…]()
![Uploading Screenshot_33.png…]()
![Uploading Screenshot_32.png…]()

### Log File

[CitizenFX_log_2022-08-23T123417.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9402840/CitizenFX_log_2022-08-23T123417.log)
[CitizenFX_log_2022-08-23T123359.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9402843/CitizenFX_log_2022-08-23T123359.log)
Its one of this two

**Comment by stefanr50** [comment]
my friend just tried it id doesn't work for him too

**Comment by JnKTechstuff** [comment]
Fixed: https://github.com/ParadoxGamingRP/Server-Development/commit/34f4164e5d9430b97e8b74faaf4ba58be06751ab
