### ISSUE TITLE
[ENHANCEMENT] House view permissions [MDT]

### ISSUE THREAD

**Issue by SpiceF0x** [ParadoxGamingRP/bugs-and-suggestions#673]
**Your Discord Name**
spicedf0x#2127

**Describe the annoyance**
**Every citizen** can see where every other citizen lives. This is not reflective of society and should only be able to be seen by selected individuals. I honestly believe this is stopping some people buying a house form the conversations I've had. 

**To Reproduce**
1. Go to town hall
2. Search a name
3. See every property they own

**Requested behavior**
Houses to be shown only to the following on the MDT for privacy purposes.
- Judges
- Lawyers
- CID
- High Command / Marshals

**Comment by xXJamieXx** [comment]
Deferred until MDT restyle is finished.

**Comment by xXJamieXx** [comment]
I either fixed this before or this was never an issue, I can't remember but they don't know up now.

**Comment by xXJamieXx** [comment]
Nope? 
![image](https://user-images.githubusercontent.com/11248045/190501745-b5db214c-e663-495b-a9d4-753226d2bc90.png)

**Comment by SpiceF0x** [comment]
![20220915214159_1](https://user-images.githubusercontent.com/96963965/190504710-f299f1d1-3901-45f0-b336-5f935a4c76f6.jpg)
 in live 👀
