### ISSUE TITLE
[BUG] Storage Locker not accessible

### ISSUE THREAD

**Issue by natashajoan** [ParadoxGamingRP/bugs-and-suggestions#674]
### Your Discord Name

Natasha_ahsataN#7098

### A clear and concise description of what the bug is

I went to the storage facility in the city, purchased a storage locker, when I went to access it by clicking it from the menu, nothing pops up, but my cursor moves around like I'm in the inventory. If I enter the locker ID, a message pops up in the top right saying "You cannot open this". There is nothing in F8 after I do either of these. 

### Steps to Reproduce the Bug

1. Purchase a storage locker
2. Try to open via the list, unable to open it
3. Try open by ID, get the "you cannot open this" message in the top right

### Expected Behavior

Be able to open the storage locker from either the list or via ID.

### Screenshots/Videos

![Screenshot (1410)](https://user-images.githubusercontent.com/97318080/186187189-7e714ec9-ffa7-40b2-87a6-065fee3a07f2.png)
![Screenshot (1411)](https://user-images.githubusercontent.com/97318080/186187234-4ccf18f5-e207-4d58-a959-c23775709c92.png)

### Extra Notes (Optional)

Sugar tried to purchase and she get's the same issue, so it can be replicated.

**Comment by SpiceF0x** [comment]
My screenshot when I tried to access Rileys, but purchasing my own I get the above behaviour.
![20220823153345_1](https://user-images.githubusercontent.com/96963965/186187680-bf2cb71e-db66-4b9a-9df6-ceddfe203018.jpg)

**Comment by JnKTechstuff** [comment]
Fixed: https://github.com/ParadoxGamingRP/Server-Development/commit/0f3df4d988d6835d05ac8eec1a4c9407bc5b33c0
