### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by stefanr50** [ParadoxGamingRP/bugs-and-suggestions#675]
### Your Discord Name

Daddy stefan#8048

### A clear and concise description of what the bug is

I have grown marijuana yesterday and when i picked it it was half dry in my inventory now the fresh marijuana plants are not drying up i have kept them in my inventory for 11 hours of total play time

### Steps to Reproduce the Bug

grow weed
pick it
and let it sit in your inventory

### Expected Behavior

I expected to dry so i can make baggies

### Screenshots/Videos

![Screenshot_39](https://user-images.githubusercontent.com/111882593/186221377-94312abe-45c3-47cf-9ae9-d4f92667646f.png)

### Extra Notes (Optional)

![Screenshot_40](https://user-images.githubusercontent.com/111882593/186227137-51c6f1c0-b8db-4fdf-afdd-08323f79d93e.png)

### Log File

[CitizenFX_log_2022-08-23T122348.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9408498/CitizenFX_log_2022-08-23T122348.log)
[CitizenFX_log_2022-08-23T122420.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9408499/CitizenFX_log_2022-08-23T122420.log)
[CitizenFX_log_2022-08-23T123359.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9408500/CitizenFX_log_2022-08-23T123359.log)
[CitizenFX_log_2022-08-23T123417.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9408501/CitizenFX_log_2022-08-23T123417.log)
[CitizenFX_log_2022-08-23T141658.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9408502/CitizenFX_log_2022-08-23T141658.log)
[CitizenFX_log_2022-08-23T141727.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9408503/CitizenFX_log_2022-08-23T141727.log)
[CitizenFX_log_2022-08-23T114207.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9408514/CitizenFX_log_2022-08-23T114207.log)
[CitizenFX_log_2022-08-23T114326.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9408523/CitizenFX_log_2022-08-23T114326.log)
[CitizenFX_log_2022-08-23T114428.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9408531/CitizenFX_log_2022-08-23T114428.log)

**Comment by JnKTechstuff** [comment]
Fixed: https://github.com/ParadoxGamingRP/Server-Development/commit/0860b8201a820009dc69a98d57b4854f96b422c5
