### ISSUE TITLE
Searching not working 

### ISSUE THREAD

**Issue by M1ngh** [ParadoxGamingRP/bugs-and-suggestions#676]
### Your Discord Name

Minghee#0876

### A clear and concise description of what the bug is

When u search a  suspect the suspect invetory gets blurry, i tryed to clock off clock back in and take a nap and didnt work.

Tryed to search other officers and also didnt work , they try to search me and same thing.

### Steps to Reproduce the Bug

Search the suspect and suspect inventory gets empty and blurry

### Expected Behavior

Search suspect and you should be able to see his pokets.

### Screenshots/Videos

![FiveM_b2699_GTAProcess_orVCZSKtjO](https://user-images.githubusercontent.com/107653844/186222417-9088c659-e29f-429a-a8d6-2d820dfa77d1.png)
![FiveM_b2699_GTAProcess_LfUWc5OaIX](https://user-images.githubusercontent.com/107653844/186222545-a40d2fbb-1f82-4302-97d0-d575a0869b98.png)
![FiveM_b2699_GTAProcess_Oi5pLgaLqJ](https://user-images.githubusercontent.com/107653844/186222601-6310bfab-d79e-4ef5-8e5b-60d367d9ef97.png)

### Log File

[CitizenFX_log_2022-08-23T165805.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9409071/CitizenFX_log_2022-08-23T165805.log)

**Comment by JnKTechstuff** [comment]
Fixed: https://github.com/ParadoxGamingRP/Server-Development/commit/0860b8201a820009dc69a98d57b4854f96b422c5
