### ISSUE TITLE
[BUG] Can't craft weed bags and plants aren't drying

### ISSUE THREAD

**Issue by vyberyt** [ParadoxGamingRP/bugs-and-suggestions#677]
### Your Discord Name

VyberYT#7147

### A clear and concise description of what the bug is

Basically when I picked the plants about 4 hours ago they aren't drying since then, and also I have tried to craft the bags for the weed, but they wont and says i dont have the required items. Even though I still have 211 plastic.

### Steps to Reproduce the Bug

Grow weed then pick it
Look in pockets and it still wont dry
Try to craft baggies

### Expected Behavior

Weed should be drying and baggies should be able to be crafted

### Screenshots/Videos

![Proof1](https://user-images.githubusercontent.com/111221191/186256785-d52b917f-c5a4-4d98-9efc-3f39c64ec012.png)
![Proof2](https://user-images.githubusercontent.com/111221191/186256806-288230a6-4021-45b5-99a9-174be085af6d.png)
![proof3](https://user-images.githubusercontent.com/111221191/186256818-2b49b390-1289-485a-ae8f-d162c640ee8c.png)
![Proof4](https://user-images.githubusercontent.com/111221191/186256855-8879f7c4-0d09-4b76-a6f0-8183b84585c4.png)

### Extra Notes (Optional)

Hopefully i will be able to craft the weed in the bags if the first things get resolved as well

### Log File

I have two one from when the problem first arised when I picked it and one from right now. Both added in order of occurence.
[CitizenFX_log_2022-08-23T144306.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9410392/CitizenFX_log_2022-08-23T144306.log)
[CitizenFX_log_2022-08-23T200754.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9410393/CitizenFX_log_2022-08-23T200754.log)

**Comment by SUMDIOR** [comment]
Same thing happening to me since yesterday.
