### ISSUE TITLE
[BUG] No pay for garbage

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#679]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

Did a short run with someone else and neither of us got any money. Don't know if it was too short or if it's a bug.

### Steps to Reproduce the Bug

1. Get a garbage truck.
2. Do a short job.
3. Man did not want to pay, he wants free labour.

### Expected Behavior

To be payed for doing a job.

### Screenshots/Videos

N/A

### Log File

[sdas.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9411116/sdas.txt)

**Comment by xXJamieXx** [comment]
Closing stale ticket due to no response.
