### ISSUE TITLE
[BUG] Jerry can no refill

### ISSUE THREAD

**Issue by baxepw** [ParadoxGamingRP/bugs-and-suggestions#681]
### Your Discord Name

baxe#0666

### A clear and concise description of what the bug is

After buying a jerry can you can not refill them at gas pumps

### Steps to Reproduce the Bug

1. Buy Jerry can
2. Try to refill at pump
3. No option to refill

### Expected Behavior

1. Buy Jerry can
2. Try to refill
3. Jerry can refills as it used to

### Screenshots/Videos

https://i.imgur.com/WYMxPH9.png

**Comment by xXJamieXx** [comment]
Fixed next restart.
