### ISSUE TITLE
[ENHANCEMENT] Unique phone backgrounds per character

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#682]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

I was on my crim yesterday and put up a background on my phone. Today it's on Olivia as well. 

### Steps to Reproduce the Bug

1. Set a background on character
2. Change character
3. see the same picture

### Expected Behavior

Have different backgrounds on different characters. 

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98127638/186491528-451a1fa9-e426-4059-aa42-574908e8d352.png)
This is on Olivias phone now, on that picture its Indica.

**Comment by xXJamieXx** [comment]
Unless this gets changed by the phone devs, unfortunately we wont be changing this as it would take too much work to do.

**Comment by xXJamieXx** [comment]
Will leave this open until that is determined.
