### ISSUE TITLE
[BUG] Unable to transfer keys

### ISSUE THREAD

**Issue by SpiceF0x** [ParadoxGamingRP/bugs-and-suggestions#684]
### Your Discord Name

spicedf0x#2127

### A clear and concise description of what the bug is

When using the citizen ID on the new phone, there is no error and it doesn't work to transfer keys. I realise this may just not have been set up yet! It just acts as if you are doing nothing. 

This did work when I tested it on the old phone, no problem. 

I do have a couple people interested in selling their houses for when this can be, though. 

### Steps to Reproduce the Bug

1. Go to Home app on phone
2. Go to transfer house
3. Enter citizen ID
4. No bueno

### Expected Behavior

Be able to transfer keys to allow for sale of houses. 

### Screenshots/Videos

None.

### Log File

[CitizenFX_log_2022-08-24T215935.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9420799/CitizenFX_log_2022-08-24T215935.log)

**Comment by xXJamieXx** [comment]
Fixed.
