### ISSUE TITLE
[BUG] Crafting table went poof

### ISSUE THREAD

**Issue by TheGraveyardShift** [ParadoxGamingRP/bugs-and-suggestions#685]
### Your Discord Name

TheGraveyardShift#6865

### A clear and concise description of what the bug is

 I was finishing up some crafting on a table and went to put it away. My pockets were too full to hold the table so it poofed. Normally it just falls to the ground put now it just disappears. 

### Steps to Reproduce the Bug

1. Craft with table
2. Have pockets full
3. Try and put table in pockets

### Expected Behavior

For it to show up on the ground

### Screenshots/Videos

table should be right there 
![image](https://user-images.githubusercontent.com/104471236/186587708-775c1e91-2dec-41b1-8f85-c917661a6d8c.png)

### Log File

[CitizenFX_log_2022-08-25T044757.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9421819/CitizenFX_log_2022-08-25T044757.log)

**Comment by CecilButler** [comment]
this also happened at smoke on the water as well our pockets were to full and the items we tried crafting didnt drop to the floor they just poofed, i know this is a separate thing but i looks to be the same issue with a different set of circumstances

**Comment by xXJamieXx** [comment]
Fixed next restart. https://github.com/ParadoxGamingRP/Server-Development/commit/c8a21f12a3f9c68a78b040c3733e6ba62c7bdfb8
