### ISSUE TITLE
Weed Plants not drying 

### ISSUE THREAD

**Issue by LtNathan235** [ParadoxGamingRP/bugs-and-suggestions#687]
### Your Discord Name

Lnathan#2764

### A clear and concise description of what the bug is

Weed plants do not dry over time, they will stay at the same moisture percentage and nothing will change.

### Steps to Reproduce the Bug

Harvest weed plants
Wait for them to dry
Notice they will not dry

### Expected Behavior

Have the plants dry out over time and not stay moist

### Screenshots/Videos

none

### Extra Notes (Optional)

none

**Comment by mjb328** [comment]
Obviously not a dev but I will say this, they were bugged for me as well couple days ago.  After the PM reset yesterday I pulled a couple plants outta my stash and they showed sign of drying but only just starting so I put them back in. Next day only the 2 plants they I test check had dried. I think any plant grown and harvest before then all need to be pull from the stashes to "refresh" the dry cycle then they begin drying again but that just my experience.

**Comment by xXJamieXx** [comment]
@LtNathan235 can you confirm the above theory by pulling them out and putting them back in and then check later and see if anything changes?

**Comment by LtNathan235** [comment]
I can confirm that I have tried that and it does not work.

**Comment by LtNathan235** [comment]
I just logged on to see and it seems as everything has dried after
pulling in and out of inventory, took multiple days and attempts to work
though
