### ISSUE TITLE
[BUG] Tattoos transfer

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#688]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

I have these tattoos on my other char, this one is supposed to have no tattoos for now,

### Steps to Reproduce the Bug

1. Have tattoos on a character
2. Log out and log in to another character
3. The character has been at the tattoo place without you and has the exact same ones.

### Expected Behavior

I expected my other character not to have the tattoos

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98127638/186749202-9b5eaacd-c33c-4f05-95e8-3fcaeafd9d90.png)

**Comment by xXJamieXx** [comment]
Fixed.
