### ISSUE TITLE
[BUG] CID motorpool errors

### ISSUE THREAD

**Issue by Kromlec** [ParadoxGamingRP/bugs-and-suggestions#689]
### Your Discord Name

Kromlec#3389

### A clear and concise description of what the bug is

CID is unable to pull out the CID Taurus.

### Steps to Reproduce the Bug

Go to motorpool
Pull out Taurus
Pulls out Trooper taurus and doesn't give keys

### Expected Behavior

Should be able to pull vehicle from the CID motorpool

### Screenshots/Videos

https://i.imgur.com/sNIBAdc.png

### Extra Notes (Optional)

The Taurus at the top also doesn't reset fuel properly and I don't think we are supposed to have access to the Viper.

### Log File

[CID LOG.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9428328/CID.LOG.txt)

**Comment by xXJamieXx** [comment]
Fixed.
