### ISSUE TITLE
[BUG] Fishing Ice chest is currently broken

### ISSUE THREAD

**Issue by Northingbud** [ParadoxGamingRP/bugs-and-suggestions#690]
### Your Discord Name

North#6863

### A clear and concise description of what the bug is

Upon purchasing a brand new ice chest from the leisure shop you will be notified that "The lock is seized" like on the OLD variant of the ice chests, other working ice chests still exist but brand newly purchased ones do not work currently for whatever reason.

### Steps to Reproduce the Bug

1.) Purchase ice chest.
2.) Try to use.

### Expected Behavior

Ice box no work when should.

### Screenshots/Videos

I feel it's pretty self-explanatory, no images or anything needed.

**Comment by MagicMyers** [comment]
[CitizenFX_log_2022-08-26T181822.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9436488/CitizenFX_log_2022-08-26T181822.log)

Haven't got the logs for it, but also happened twice last night, admin took the broken boxes with them.

**Comment by xXJamieXx** [comment]
Fixed next restart.
