### ISSUE TITLE
[BUG] Saving barbers details saves whole outfit

### ISSUE THREAD

**Issue by SpiceF0x** [ParadoxGamingRP/bugs-and-suggestions#691]
### Your Discord Name

spicedf0x#2127

### A clear and concise description of what the bug is

I decided to lighten up my hair in general, so resaved my hair to all of my outfits, however this completely overwrote all saved outfits with the hair and the clothes I was in at the time.

### Steps to Reproduce the Bug

1. Decide you want to save a different hair to an outfit
2. Go to barbers and find hair
3. Pick outfit
4. It saves both barber and outfit details on the save

### Expected Behavior

I feel like when this first came in the save of hair to each outfit was independent of the clothes you were wearing, so you could be in a different outfit rather than switching between all outfits to resave your hair on multiple outfits. 

It's weird that both the barber and clothes gets saved at the barber when you pick an outfit to save the barber selection to.

### Screenshots/Videos

Can see the ones I chose to change my hair on versus the ones I didnt:

https://streamable.com/h0ho3h

**Comment by JnKTechstuff** [comment]
Did you put an outfit name?

**Comment by SpiceF0x** [comment]
Yeah, if you try to change the hair not in the correct outfit it rewrites
the whole outfit and not just the barber part of it. So I went through and
applied the same hair on 12ish outfits, but it also resaved the outfit to
what I was currently standing in.

**Comment by JnKTechstuff** [comment]
Pretty sure thats how we made it work

**Comment by xXJamieXx** [comment]
Just the way its designed, would take a lot of work to separate it and I'm not willing to do that at the risk of losing data.
