### ISSUE TITLE
[BUG] Infinite Hunting bait bag

### ISSUE THREAD

**Issue by andythewookie** [ParadoxGamingRP/bugs-and-suggestions#692]
### Your Discord Name

andythewookie#0798

### A clear and concise description of what the bug is

Hunting bait bag in quick access slot, only uses bait bag uses when broken there is no alert to broken item and the bait bag becomes infinite uses can keep using over and over without broken item message

### Steps to Reproduce the Bug

buy hunting bait
place hunting bait 5 times till item shows in inventory as broken
do not move from pocket keep using number for access slot to keep placing bait

### Expected Behavior

5 use item should show broken item message and not allow to place anymore baits till item is switched over for new bait bag

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/yhdQt3TUsX6Kh/d1337kASJnzC?invite=cr-MSxKWnAsNDM2ODM0MTQs

**Comment by andythewookie** [comment]
This also happens with hunting knifes and that would leave me to believe its possibly the same with any times that have a number of uses on it

**Comment by xXJamieXx** [comment]
Fixed next restart. https://github.com/ParadoxGamingRP/Server-Development/commit/3407509ce63d9663ca581d62c284028a4de44a06
