### ISSUE TITLE
[BUG] Can re-use all the things that has a durabilty

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#693]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

Everything that has a durabilty is still usable even when red. I tested it on both my hunting knife and my hunting baits. 

### Steps to Reproduce the Bug

1. Empty the bag and use the knife to it fullest
2. Keep using it even when they are red

### Expected Behavior

Expected the knife and hunting bait being unusable

### Screenshots/Videos

N/A

**Comment by xXJamieXx** [comment]
Duplicate of #692
