### ISSUE TITLE
[BUG] Garbage Job Blueprints

### ISSUE THREAD

**Issue by x2Andrew** [ParadoxGamingRP/bugs-and-suggestions#694]
### Your Discord Name

g unit#3667

### A clear and concise description of what the bug is

I have been doing multiple garbage runs and had a message pop up 3 times that i have picked up a blueprint off the ground. I have checked my inventory/crafting table/and the floor. I have got the message that i have recieved the blueprint 3 times as of writing this.

### Steps to Reproduce the Bug

Start Garbage Job
Do multiple trash runs until randomly recieving a notifications you get the blueprint

### Expected Behavior

No blueprint is given.

### Screenshots/Videos

![Screenshot_13](https://user-images.githubusercontent.com/112222923/187008968-4130ee32-e9f8-4568-bdb2-f3542cf3508d.png)
![Uploading Screenshot_12.png…]()

**Comment by x2Andrew** [comment]
![Screenshot_12](https://user-images.githubusercontent.com/112222923/187009101-6e646f27-72cb-4b63-880d-e9600957e6eb.png)

**Comment by x2Andrew** [comment]
[CitizenFX_log_2022-08-26T100151.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9437095/CitizenFX_log_2022-08-26T100151.log)
[CitizenFX_log_2022-08-26T091629.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9437096/CitizenFX_log_2022-08-26T091629.log)

**Comment by xXJamieXx** [comment]
Fixed next restart.

**Comment by TheGraveyardShift** [comment]
We are still not receiving blueprints i dont think
