### ISSUE TITLE
[ENHANCEMENT] Megaphone/Microphone

### ISSUE THREAD

**Issue by Mac-ceo** [ParadoxGamingRP/bugs-and-suggestions#695]
**Your Discord Name**
mac_ceo#0001

**Describe the annoyance**
When hosting events or large gatherings in like open areas like the galaxy nightclub or out side people cant always hear you I think IF POSSIBLE a microphone would be so useful 

**To Reproduce**
[Steps to reproduce the annoyance]
1. Have a load of people in a large area 
2. People can't hear you when speaking 
3. 

**Requested Behaviour**
Be an item in pockets and you take it out a prop shows up you press your ptt button and you are louder if it was to be more realistic it could play out of speakers in a certain range

**Comment by xXJamieXx** [comment]
Added microphone zones and megaphones for cops, mobile loud speakers not available to civs right now.
