### ISSUE TITLE
[BUG] Can't craft plastic

### ISSUE THREAD

**Issue by stefanr50** [ParadoxGamingRP/bugs-and-suggestions#696]
### Your Discord Name

Daddy stefan#8048

### A clear and concise description of what the bug is

I was drinking some bottles and i tried to recycle them and it wouldn't let me i will send a video

### Steps to Reproduce the Bug

Get some water bottles
Drink them
try to recycle them

### Expected Behavior

I was expecting to get plastic as always

### Screenshots/Videos

![Screenshot_75](https://user-images.githubusercontent.com/111882593/187042921-d0cd6344-4340-447f-b3c2-deb11ee8cebe.png)

### Extra Notes (Optional)

I can't upload a video but try it

### Log File

[CitizenFX_log_2022-08-27T173923.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9438469/CitizenFX_log_2022-08-27T173923.log)

**Comment by ShaymusSavage** [comment]
Can confirm, just tried this and was not able to get plastic.

**Comment by madsskyy** [comment]
This feature was removed. You cannot recycle water bottles any more.
