### ISSUE TITLE
[BUG] Bank trucks not working properly 

### ISSUE THREAD

**Issue by iCLassYx** [ParadoxGamingRP/bugs-and-suggestions#697]
### Your Discord Name

iCLassYx#8576

### A clear and concise description of what the bug is

Bank trucks are not appearing when you get the radio traffic heard signal. 

### Steps to Reproduce the Bug

Drive around

Scan for truck

Get correct signal

guards are floating through the earth or the truck is no where to be found. 

### Expected Behavior

Expected behavior 

locate truck

kill guards

thermite doors

### Screenshots/Videos

https://user-images.githubusercontent.com/103862374/187044945-95e2c11b-30bc-4c6b-a9f3-252314939bbc.mp4

### Log File

  2621594] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "mailItem". This is a FATAL ERROR in
[   2621594] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2621594] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2621594] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "mailItem__withFallback". This is a FATAL ERROR in
[   2621594] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2621594] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2621594] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "selectedMail". This is a FATAL ERROR in
[   2621594] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2621594] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2621594] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "mailModalVisible". This is a FATAL ERROR in
[   2621594] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2621594] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2621594] [b2699_GTAProce]        CrBrowserMain/ Successfully loaded external app "npwd_qb_mail" (webpack-internal:///67212:11215)
[   2621610] [b2699_GTAProce]        CrBrowserMain/ Successfully loaded external app "npwd_qb_services" (webpack-internal:///67212:11215)
[   2621625] [b2699_GTAProce]        CrBrowserMain/ Successfully loaded external app "npwd_qb_garage" (webpack-internal:///67212:11215)
[   2634125] [b2699_GTAProce]             MainThrd/ TRUCK SYNC:	767	313	723	1142	92
[   2634125] [b2699_GTAProce]             MainThrd/ GetNetworkObject: no object by ID 0
[   2636563] [b2699_GTAProce]             MainThrd/ ^1[ParadoxWeather] Change Weather: OVERCAST
[   2636563] [b2699_GTAProce]             MainThrd/ 
[   2636563] [b2699_GTAProce]             MainThrd/ ^7^1[ParadoxWeather] Change Wind Value: 3.1
[   2636578] [b2699_GTAProce]             MainThrd/ 
[   2636578] [b2699_GTAProce]             MainThrd/ ^7^1[ParadoxWeather] Weather in transistion [CLOUDS]->[OVERCAST] for 60.1 seconds.
[   2636578] [b2699_GTAProce]             MainThrd/ ^70.59	cirrocumulus
[   2696672] [b2699_GTAProce]             MainThrd/ ^1[ParadoxWeather] Weather is ending transistion. [OVERCAST]->[OVERCAST]
[   2773828] [b2699_GTAProce]        CrBrowserMain/ ^7Error with Permissions-Policy header: Unrecognized feature: 'ch-ua-bitness'. (:0)
[   2773828] [b2699_GTAProce]        CrBrowserMain/ Error with Permissions-Policy header: Unrecognized feature: 'ch-ua-full-version-list'. (:0)
[   2901766] [b2699_GTAProce]        CrBrowserMain/ Uncaught (in promise) TypeError: Failed to fetch (@npwd/resources/html/index.html#/:0)
[   2901766] [b2699_GTAProce]        CrBrowserMain/ Uncaught (in promise) TypeError: Failed to fetch (@npwd/resources/html/index.html#/:0)
[   2901766] [b2699_GTAProce]        CrBrowserMain/ Uncaught (in promise) TypeError: Failed to fetch (@npwd/resources/html/index.html#/:0)
[   2901766] [b2699_GTAProce]        CrBrowserMain/ Uncaught (in promise) TypeError: Failed to fetch (@npwd/resources/html/index.html#/:0)
[   2901766] [b2699_GTAProce]        CrBrowserMain/ Uncaught (in promise) TypeError: Failed to fetch (@npwd/resources/html/index.html#/:0)
[   2901766] [b2699_GTAProce]        CrBrowserMain/ Uncaught (in promise) TypeError: Failed to fetch (@npwd/resources/html/index.html#/:0)
[   2901766] [b2699_GTAProce]        CrBrowserMain/ Uncaught (in promise) TypeError: Failed to fetch (@npwd/resources/html/index.html#/:0)
[   2901766] [b2699_GTAProce]        CrBrowserMain/ Uncaught (in promise) TypeError: Failed to fetch (webpack-internal:///54567:7)
[   2901766] [b2699_GTAProce]        CrBrowserMain/ Uncaught (in promise) TypeError: Failed to fetch (webpack-internal:///54567:7)

**Comment by xXJamieXx** [comment]
Should be fixed.
