### ISSUE TITLE
[BUG] The tennis court at 832 tracks court wrong

### ISSUE THREAD

**Issue by Weebait** [ParadoxGamingRP/bugs-and-suggestions#698]
### Your Discord Name

Weeb#5266

### A clear and concise description of what the bug is

The court at 832 has a tiny serving area that only allows you to move a couple steps in either direction and even if you serve less than half way up the court it considers it an out and stops play completely. I believe the playable area might need to be resized. You can also notice this in the fact that to begin you have to stand at nearly the center of the court while with all the other ones it's towards the left corner.

### Steps to Reproduce the Bug

Play on the tennis court

### Expected Behavior

The entire tennis court to be playable and to be able to move when serving the ball.

### Screenshots/Videos

N/A

### Extra Notes (Optional)

To my knowledge this is the only court that acts like this

**Comment by xXJamieXx** [comment]
Fixed next restart.
