### ISSUE TITLE
Diving Barely works

### ISSUE THREAD

**Issue by Gritsychan** [ParadoxGamingRP/bugs-and-suggestions#699]
**Your Discord Name**
[Enter your Discord name]
Grits
**Describe the annoyance**
[A clear and concise description of what the the annoying mechanic that should be resolved is]
When you dive Its near impossible to get all the question marks Ive seen 5 people be in one circle not able to find the last one for like 20-30 minutes. plus It barely gives plastic for the time spent doing it plus its very easy to get robbed out there.
**To Reproduce**
[Steps to reproduce the annoyance]
1. Just go diving and you will see how broken it is
2. 
3. 

**Requested behavior**
[A clear and concise description of what you want to happen]
I want the diving to actually give good plastic gains and i want it to work properly, searching for a question mark for 30 minutes for plastic just isnt good RP
**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by xXJamieXx** [comment]
Should be fixed.
