### ISSUE TITLE
[BUG] MDT profile duplication

### ISSUE THREAD

**Issue by OwlCherry** [ParadoxGamingRP/bugs-and-suggestions#700]
### Your Discord Name

OwlCherry#6969

### A clear and concise description of what the bug is

every persons profile is duplicated 4 times for the same individual.

### Steps to Reproduce the Bug

1. search a person
2. locate 4 identical profiles 

### Expected Behavior

should only show each profile once 

### Screenshots/Videos

https://i.imgur.com/jx0yu8C.png

### Log File

[CitizenFX_log_2022-08-28T220437.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9440584/CitizenFX_log_2022-08-28T220437.log)

**Comment by xXJamieXx** [comment]
Fixed.

**Comment by OwlCherry** [comment]
Jamie this is still an issue as of today

**Comment by Dez505** [comment]
this is still an issue as of today
