### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by xsheppardx** [ParadoxGamingRP/bugs-and-suggestions#702]
### Your Discord Name

Sheppard#2354

### A clear and concise description of what the bug is

Was out hunting in chilad mountains when a bank truck drove by, doors were all closed... and then a bag showed up to press e on to collect it... now the bag is stuck on me, and i never interacted with the vehicle or the contents.

### Steps to Reproduce the Bug

hunting in chliad mountains
placing bait
bank truck drove by
menu opened to hit e to collect money
bag stuck on me
/b0 command wont remove bag

### Expected Behavior

pick up bag

### Screenshots/Videos

![NvCI8V](https://user-images.githubusercontent.com/112357496/187102051-5bebaa32-1ddd-49e4-911c-e7f5980fb913.jpg)

### Log File

[CitizenFX_log_2022-08-28T220553.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9440801/CitizenFX_log_2022-08-28T220553.log)

**Comment by JnKTechstuff** [comment]
"I did something stupid and it broke"

K?
