### ISSUE TITLE
[ENHANCEMENT] /me log's

### ISSUE THREAD

**Issue by Tobjaks** [ParadoxGamingRP/bugs-and-suggestions#703]
**Your Discord Name**
tobjak#4191

**Describe the annoyance**

During many scenes /me's can get lost or hard to see due to different circumstances. Not to say the least when for example patients wants to RP out injuries inside of vehicles. 

**Requested behavior**
I would love to see some kind of /me log that you easily could clear out with /clear aswell. That way you could focus more on the RP part rather then remembering and focusing on the small duration of time you have with the /me's. 

**Screenshots**
The screenshot is from the biggest Swedish RP server. Something like this would be wonderful.

https://imgur.com/a/GRqEgc6

Thank you guys for all the hard work!

**Comment by JnKTechstuff** [comment]
No I will not add /mes into chat like a 2017 server. We will look into maybe an option for something else

**Comment by Mac-ceo** [comment]
> No I will not add /mes into chat like a 2017 server. We will look into maybe an option for something else

I like this idea but like you said a different way is it possible to have it pop up like when you pot a ball in pool like small box on the side of the screen  for people in a certain range

**Comment by JnKTechstuff** [comment]
Added
