### ISSUE TITLE
[BUG] Unable to access extras on personal Taurus at Custom shops

### ISSUE THREAD

**Issue by Drunkle716** [ParadoxGamingRP/bugs-and-suggestions#704]
### Your Discord Name

Drunkle716#7571

### A clear and concise description of what the bug is

When going into the custom shop, I am unable to access any customization menus.

### Steps to Reproduce the Bug

1. Go to custom shop
2. Cannot access any customization after pressing E

### Expected Behavior

1. Go to custom shop
2. Press E
3. press enter on extra menu and make changes to vehicle

### Screenshots/Videos

https://youtu.be/Oz88Pq5eL_o

**Comment by Drunkle716** [comment]
I actually can't change any vehicle at a custom shop. Just tested on another character with a test drive car.

**Comment by Drunkle716** [comment]
I also can't use the tattoo shop

**Comment by xXJamieXx** [comment]
Reset your keybinds to default.

**Comment by Drunkle716** [comment]
It worked. Thank you for your help.

**Comment by Drunkle716** [comment]
FiveM keybinds or F8 as well

Sent from Yahoo Mail on Android 
 
  On Thu, Sep 1, 2022 at 7:45 AM, ***@***.***> wrote:   


Reset your keybinds to default.
