### ISSUE TITLE
[BUG] Can't anchor the boat

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#705]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

You cant throw anchor, the boat will still float away. We were 2 that tried this.

### Steps to Reproduce the Bug

Get a boat
Drive the boat out
Anchor it and see it float away

### Expected Behavior

To be able to throw in the anchor and the boat to stay in its location.

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/yLygJbtmRSmfq/d1337IJ8UNDm?invite=cr-MSxZczcsNDU3NjU0MzAs

**Comment by xXJamieXx** [comment]
Fixed next restart.
