### ISSUE TITLE
[BUG] Can't interact with corals

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#706]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

Tried to pick the corals, can't thirdeye it. We were 2 people that tried.

### Steps to Reproduce the Bug

Go diving
Jump in water and search for coral
Find coral and thirdeye it - nothing except a purple eye shows. Can't click.

### Expected Behavior

Being able to pick up the coral 

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/yLx00Mefp8qzu/d1337hONbJIa?invite=cr-MSxJaEQsNDU3NjU0MzAs

**Comment by vyberyt** [comment]
Does it need more info since my issue is now a reference to it?

**Comment by xXJamieXx** [comment]
Fixed next restart.
