### ISSUE TITLE
[BUG] Tattoos is still transfering to other char when doing logout

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#707]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

I did a F8 logout from my tattooed character to my non-tattoed character and they all transfered to that one. 

### Steps to Reproduce the Bug

Have a tattooed and a non tattooed character
Be on the tattooed one first and do a F8 logout
Log in on the one without tattoos and see that one having tattoos.

### Expected Behavior

To log in on my character without tattoos.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98127638/187296039-118e3512-db63-4768-8117-cdbb8aff07a7.png)

**Comment by xXJamieXx** [comment]
Fixed next restart.
