### ISSUE TITLE
[BUG] Flecca deposit boxes not drilling 

### ISSUE THREAD

**Issue by Baljeet00** [ParadoxGamingRP/bugs-and-suggestions#708]
### Your Discord Name

Baljeet#1738

### A clear and concise description of what the bug is

Unable to drill deposit boxes. Let us drill one but from there the other ones wouldn't work. The third eye lit up but when I pressed drill nothing would happen. Also drill was not broke.

### Steps to Reproduce the Bug

hack the bank doors
Thermite the door
Try to drill the deposit boxes

### Expected Behavior

I would expect it to let us drill after doing one and not breaking the drill.

### Screenshots/Videos

none

### Extra Notes (Optional)

f8 quit once in the bank to try and fix the issue. That's why there are 2 sets of logs.

### Log File

[CitizenFX_log_2022-08-29T231130.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9448523/CitizenFX_log_2022-08-29T231130.log)
[CitizenFX_log_2022-08-29T231107.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9448524/CitizenFX_log_2022-08-29T231107.log)

**Comment by ColKing** [comment]
This happened to me yesterday when I tried to hit one as well. Here is a video https://medal.tv/games/gta-v/clips/yGSyD-VxoHEPs/d1337QaKAAmn?invite=cr-MSw3dm4sNjY1NDAzMDcs .

**Comment by natashajoan** [comment]
No video from my side, but this has also happened to us last night, the first one of the right could be drilled and none of the others.

**Comment by JnKTechstuff** [comment]
Fixed with v2
