### ISSUE TITLE
[BUG] REPLACE ME WITH YOUR BUG TITLE

### ISSUE THREAD

**Issue by Vaderdddd** [ParadoxGamingRP/bugs-and-suggestions#709]
### Your Discord Name

Vader#3443

### A clear and concise description of what the bug is

Bank truck goes under ground with guards at grapeseed spot we don't know if its happening anywhere else though.

### Steps to Reproduce the Bug

1Get bank truck in grapeseed
2 Find the gaurds underground going up and down

### Expected Behavior

Get bank truck
Thermite door
kill guards 
get money

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/yPa0SRGKHXJ6k/d1337pRU9KiK?invite=cr-MSxNaVYsNjQwNTcwODgs

### Log File

[CitizenFX_log_2022-08-28T165914.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9450051/CitizenFX_log_2022-08-28T165914.log)

**Comment by JnKTechstuff** [comment]
Script worked as intended because your client failed to create the bank truck probably due to your client having a lag issue
