### ISSUE TITLE
[BUG] WEBSITE being alble to see replys when on hidden 

### ISSUE THREAD

**Issue by Mac-ceo** [ParadoxGamingRP/bugs-and-suggestions#710]
### Your Discord Name

mac_ceo#0001

### A clear and concise description of what the bug is

So I don't know if it'd just a one time glitch but when I watched my vip application it it sent me an email with what the reply said  with it it might  be because sugar opened replys to say its pending the  closed it again to say wait till 8th but I'm not sure adam told me to make a bug report

### Steps to Reproduce the Bug

1. Fill in vip application [not sure with others]
2. Watch the application 
3. Staff or who ever reply 
4. Email sent

### Expected Behavior

The hidden replys should be sent to your email when watched

### Screenshots/Videos

![Screenshot_20220830-123108_Samsung Internet](https://user-images.githubusercontent.com/103427821/187404140-328270ee-c4d7-4ddb-803c-a8ec8d2fce64.jpg)
![Screenshot_20220830-123056_Gmail](https://user-images.githubusercontent.com/103427821/187404218-a1301b6b-4b93-4e36-ae26-209d9e2626bb.jpg)

### Log File

No logs website

**Comment by xXJamieXx** [comment]
Blame Sugar for user error.
