### ISSUE TITLE
[BUG] Coral Seller Currently Not Buying Coral

### ISSUE THREAD

**Issue by ShaymusSavage** [ParadoxGamingRP/bugs-and-suggestions#712]
### Your Discord Name

Shaymus#1460

### A clear and concise description of what the bug is

Unable to sell coral at Coral Seller. 

### Steps to Reproduce the Bug

1. Travel to Coral Seller (Del Perro)
2. Get Coral in inventory. (Dendrogyra, Antipatharia)
3. Go to Coral Seller
4. Third Eye Seller.
5. Click Sell Coral

### Expected Behavior

Sell Coral, Remove coral from inventory, get money from coral.

### Screenshots/Videos

https://i.imgur.com/adxrKKa.png

### Log File

[CitizenFX_log_2022-08-30T224106.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9457852/CitizenFX_log_2022-08-30T224106.log)

**Comment by xXJamieXx** [comment]
Fixed next restart.
