### ISSUE TITLE
[BUG] store registers not working ?

### ISSUE THREAD

**Issue by ArtistYSL** [ParadoxGamingRP/bugs-and-suggestions#713]
### Your Discord Name

ArtistYSL#0839

### A clear and concise description of what the bug is

i was in the middle of a robbery and nor the safe or the registers were getting unlocked i got the paper code from the first register and i went to put in the safe and it didnt work it didnt give me an option to do it or the 3rd eye didnt work and i went to pick the 2nd register and it wasnt working i tried changing the inventory slot for it and it didnt work 
1 register is about 3k or 4k 
and 1 safe is about 12 or 15 k each its very unfortunate i just want the money for it because i already had a hostage i had a get away plan 

### Steps to Reproduce the Bug

stop letting multiple heist glitch

### Expected Behavior

get my money back for it 

### Screenshots/Videos

it said clip was too big but i have it

**Comment by madsskyy** [comment]
try zipping the video and attaching it here please

**Comment by ArtistYSL** [comment]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by xXJamieXx** [comment]
Can't reproduce this.
