### ISSUE TITLE
[BUG] pulling large vehicles out at von crastenburg

### ISSUE THREAD

**Issue by SketchyNath** [ParadoxGamingRP/bugs-and-suggestions#715]
### Your Discord Name

SketchyNath

### A clear and concise description of what the bug is

The parking at the Von Crastenburg apartments needs to be adjusted slightly.
Every time I have pulled out a vehicle it clips to the wall and smashes all the windows.
This happens more with lager vehicles like pick-up's and SUV's

### Steps to Reproduce the Bug

1. Have a larger vehicle (Bison, Baller..Etc...)
2. Park it in Von Crastenburg apartments (Postal 590)
3. Bring out said vehicle from parking and the windows will smash

### Expected Behavior

Parking slightly moved so vehicles don't clip to the walls and smash everytime you bring them out

### Screenshots/Videos

https://imgur.com/a/JkpQEBv

### Log File

Log file is empty. Cannot transfer.

**Comment by xXJamieXx** [comment]
The windows smashing is simply because you stored the vehicle damaged. I've moved the parking spots slightly though away from the walls next restart.
