### ISSUE TITLE
[BUG] Marketplace listings not being deleted

### ISSUE THREAD

**Issue by SpiceF0x** [ParadoxGamingRP/bugs-and-suggestions#716]
### Your Discord Name

spicedf0x#2127

### A clear and concise description of what the bug is

The ad may be showing up for other people, but it's not showing up for me to delete and repost after flying back in. So I get an error that I can't post an ad with another of the same title. 

### Steps to Reproduce the Bug

1. Logout or quit without deleting the ad
2. Fly back in, looks like it's gone
3. Attempt to repost and you can't. :(

### Expected Behavior

I wanna repost the ad, please if I can't see it there.

### Screenshots/Videos

https://i.imgur.com/hDQWEpl.jpeg

**Comment by xXJamieXx** [comment]
Fixed in dev. Waiting to push with other phone updates.
