### ISSUE TITLE
[BUG] Selling Inventory Of Coral Only Gives $1

### ISSUE THREAD

**Issue by ShaymusSavage** [ParadoxGamingRP/bugs-and-suggestions#717]
### Your Discord Name

Shaymus#1460

### A clear and concise description of what the bug is

When attempting to sell an inventory of Coral, I was given $1 instead of the correct amount for every coral after the inventory was checked.

### Steps to Reproduce the Bug

1. Get inventory of coral. (30 of each)
2. Go to Coral Seller
3. Sell Coral
4. Receive $1

### Expected Behavior

1. Get inventory of coral. (30 of each, The Blue and White coral)
2. Go to Coral Seller
3. Sell Coral
4. Receive the correct amount per each coral.

### Screenshots/Videos

https://i.imgur.com/dJ95Dup.png

It was hard to get a screenshot or video as this was not expected. 

### Log File

[CitizenFX_log_2022-09-01T000457.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9465866/CitizenFX_log_2022-09-01T000457.log)

**Comment by xXJamieXx** [comment]
Fixed.
