### ISSUE TITLE
[BUG] Blue Prints Scuff

### ISSUE THREAD

**Issue by SpicyWB** [ParadoxGamingRP/bugs-and-suggestions#718]
### Your Discord Name

Spicy#5426

### A clear and concise description of what the bug is

Unable to learn blue prints after receiving them

### Steps to Reproduce the Bug

get a blueprint
use it
it dont work

### Expected Behavior

I learn that shit

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/z53r7yoatqMq8/d1337bUWx4eq?invite=cr-MSxlTEosNDQ0ODc0NTAs

https://i.imgur.com/73JTEBh.png

**Comment by JnKTechstuff** [comment]
Fixed https://github.com/ParadoxGamingRP/Server-Development/commit/16f7d96108f5d6a80ea28ee845f5afebcf1fff44
