### ISSUE TITLE
[BUG]  broken car/bike dealerships

### ISSUE THREAD

**Issue by andythewookie** [ParadoxGamingRP/bugs-and-suggestions#724]
### Your Discord Name

andythewookie#0798

### A clear and concise description of what the bug is

Broken car/bike dealerships cant search cars

### Steps to Reproduce the Bug

go to dealership, try to swap vehicles

### Expected Behavior

able to swap vehicles

### Screenshots/Videos

none

**Comment by xXJamieXx** [comment]
Should be fixed.
