### ISSUE TITLE
[BUG] glitched movie theatre

### ISSUE THREAD

**Issue by spookylucy** [ParadoxGamingRP/bugs-and-suggestions#726]
### Your Discord Name

Spookylucy31#7775

### A clear and concise description of what the bug is

Sometimes when you go to the movie theatre at postal 575, there won't be any interior, it seems to be glitched as if you've fallen through the map, and its just a complete white space with no way to find doors etc. 
This happened to me 3 times now where I wasn't able to see the interior

### Steps to Reproduce the Bug

log out/quit the game whilst being inside the venue
log out/quit in the apartment nearby, spawn inside your apartment, leave and arrive at the movie theatre 

### Expected Behavior

i expect to be able to see the interior, i initially decided to log out in the bathroom of the venue and come back in to see if i can see the interior but instead i could only see doors, the bar and the theatre screen but everything else was white. 
so i was told by another player that was having the same issue to drive around the block and come back and that actually managed to get the full interior back. three people including myself were having this issue. 

### Screenshots/Videos

![Screenshot (1122)](https://user-images.githubusercontent.com/112810641/188314856-dbf1058d-53c8-48e9-a1d5-dc011c29c0b6.png)
![Screenshot (1076)](https://user-images.githubusercontent.com/112810641/188314964-7ae33927-c3e5-45da-9db6-fd3a44f9001c.png)

### Log File

[CitizenFX_log_2022-09-04T005227.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9484734/CitizenFX_log_2022-09-04T005227.log)

**Comment by xXJamieXx** [comment]
I'll see if the mapping team has any ideas on this but it'll be VERY LOW priority as they have other projects to work on.

In the meantime just don't logout inside the movie theatre.

**Comment by xXJamieXx** [comment]
Just a quirk with interiors and logging out. My best advice is to avoid logging out inside interiors to prevent these issues. I will be closing this as we wont be pushing a specific fix for it.
