### ISSUE TITLE
[BUG] Contender auto impounds upon removal of garage

### ISSUE THREAD

**Issue by OwlCherry** [ParadoxGamingRP/bugs-and-suggestions#728]
### Your Discord Name

OwlCherry#6969

### A clear and concise description of what the bug is

every time I store my contender in the garage at Arcadius - when I go to remove it from garage, it gives me keys then immediately sends to impound

### Steps to Reproduce the Bug

1. store contender at arcadius
2. fly out
3. fly in later and try to pull out
4. gains keys and no car - have to go to impound.

### Expected Behavior

should give you the car and not charge you 700 bucks for impound

### Screenshots/Videos

n/a

### Log File

[CitizenFX_log_2022-09-05T001326.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9485761/CitizenFX_log_2022-09-05T001326.log)

**Comment by JnKTechstuff** [comment]
Too big to be pulling from there
