### ISSUE TITLE
[BUG] anything requiring overlay has a potent to crash.

### ISSUE THREAD

**Issue by OwlCherry** [ParadoxGamingRP/bugs-and-suggestions#729]
### Your Discord Name

OwlCherry#6969

### A clear and concise description of what the bug is

Have not been able to duplicate on demand, however tonight i have had 3 instances where opening inventory / phone causes black boxes to appear all over the screen and cause the HUD to malfuction thus not allowing you to move, use /logout or anything like that forcing you to f8 quit

### Steps to Reproduce the Bug

1. Open phone / inventory.
2. have an "episode"
3. see black blocks all over your screen 
4. HUD options go away
5. unable to use text box, inventory, phone etc forcing an f8 quit.

### Expected Behavior

to use everything as normal without forcing you to restart.

### Screenshots/Videos

will supply if i can get it to happen on camera

### Log File

[CitizenFX_log_2022-09-05T003502.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9486268/CitizenFX_log_2022-09-05T003502.log)
[CitizenFX_log_2022-09-05T002701.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9486269/CitizenFX_log_2022-09-05T002701.log)

**Comment by OwlCherry** [comment]
https://i.imgur.com/XvGrvUa.jpeg

**Comment by JnKTechstuff** [comment]
Honestly think this is a just you issue
