### ISSUE TITLE
[BUG] Twitter notification settings not being respected

### ISSUE THREAD

**Issue by WraithKildare** [ParadoxGamingRP/bugs-and-suggestions#730]
### Your Discord Name

EmiDirano

### A clear and concise description of what the bug is

My phone won't stop giving me Twitter notification sounds and pop-ups. Despite having the volume all the way down and being only mentions, I'm getting almost all notifications. 

### Steps to Reproduce the Bug

We tried people not @ing people and I'll see it. We tried @ing random people and I could see it. 
I tried clearing my cache 
I tried napping
I tried resetting my phone multiple times
I won't stop

### Expected Behavior

I would like my phone to stop notifying me for every single damn tweet that comes through twitter. I can't carry a phone, it is too annoying and it won't stop. 

### Screenshots/Videos

https://i.imgur.com/Y3gDu3S.jpg

### Extra Notes (Optional)

I don't know what else to do at this point. Help me!

**Comment by JnKTechstuff** [comment]
This can happen if you never setup a twitter profile.
