### ISSUE TITLE
[BUG] items disappearing from car

### ISSUE THREAD

**Issue by Maiko2342** [ParadoxGamingRP/bugs-and-suggestions#731]
### Your Discord Name

Maiko#9728

### A clear and concise description of what the bug is

item disappearing from inventory

### Steps to Reproduce the Bug

get the item from the car and put it in your inventory

### Expected Behavior

item will still be in your inventory but it randomly disapears

### Screenshots/Videos

none my GeForce experience was not on but hopefully the logs can help

### Extra Notes (Optional)

i have no idea how this is possible and im scared to put stuff in and out of my car now 

### Log File

[CitizenFX_log_2022-09-06T202323.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9503265/CitizenFX_log_2022-09-06T202323.log)
[CitizenFX_log_2022-09-07T032805.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9503266/CitizenFX_log_2022-09-07T032805.log)
[CitizenFX_log_2022-09-07T032819.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9503267/CitizenFX_log_2022-09-07T032819.log)
[CitizenFX_log_2022-09-07T053829.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9503268/CitizenFX_log_2022-09-07T053829.log)
[CitizenFX_log_2022-09-07T053845.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9503269/CitizenFX_log_2022-09-07T053845.log)
[CitizenFX_log_2022-09-07T055142.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9503270/CitizenFX_log_2022-09-07T055142.log)
[CitizenFX_log_2022-09-07T055157.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9503271/CitizenFX_log_2022-09-07T055157.log)
[CitizenFX_log_2022-09-07T060330.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9503272/CitizenFX_log_2022-09-07T060330.log)
[CitizenFX_log_2022-09-07T060347.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9503273/CitizenFX_log_2022-09-07T060347.log)

**Comment by madsskyy** [comment]
question: what kind of car was it?

**Comment by JnKTechstuff** [comment]
Due to the incoherent nature of this issue it will be closed for one that is coherent
