### ISSUE TITLE
[BUG] store robbery not giving notif

### ISSUE THREAD

**Issue by KingBr0** [ParadoxGamingRP/bugs-and-suggestions#732]
### Your Discord Name

kingbro#6467

### A clear and concise description of what the bug is

Hello, when i tried to reserve a robbery and interact with the guy, nothing shows up. Also my friend has this same issue.

### Steps to Reproduce the Bug

1. Go to the Store Robbery guy
2. 3rd Eye on him
3. Interact
4. Nothing shows up

### Expected Behavior

It should get you a message on your phone saying something like: Your robbery is at xxx. On your gps it should be well visible where the location is

### Screenshots/Videos

https://user-images.githubusercontent.com/106405499/188932753-9639e1d8-585b-4666-884b-e6108b438e65.mp4

**Comment by madsskyy** [comment]
this was fixed a couple days ago (:
