### ISSUE TITLE
[BUG] SAR heli / PHO-1 rappel causes lengthy ragdoll

### ISSUE THREAD

**Issue by Dez505** [ParadoxGamingRP/bugs-and-suggestions#734]
### Your Discord Name

Dez505#1103

### A clear and concise description of what the bug is

when up in medevac and you rappel when you get to the ground you fall over and you are rag dog for about 30 secs

### Steps to Reproduce the Bug

1. go up about 50-100 FT in either heli
2. hit X to rappel
3. rag dog for 30 secs 

### Expected Behavior

rag dog after rappelling from heli 

### Screenshots/Videos

N/A

**Comment by madsskyy** [comment]
is this still an issue?

**Comment by Dez505** [comment]
yes it is

**Comment by JnKTechstuff** [comment]
Fixed: https://github.com/ParadoxGamingRP/Server-Development/commit/5d1450c74e328e3e63c64f6f405057fd974ca1ca
