### ISSUE TITLE
Paycheck at $0.00 when I went to collect it. 

### ISSUE THREAD

**Issue by RoseiiNaytool** [ParadoxGamingRP/bugs-and-suggestions#735]
### Your Discord Name

Roseii/Sen #7904

### A clear and concise description of what the bug is

I don't know if it showed collecting my work paycheck while working, $125.00 each time for working at Glazed and Glorious. When I went to pick up my paycheck at the bank it said $0. When I tried again to collect it 20 minutes after hurricane all I got was a $25.00 unemployment check. Yes I was logged in and working the whole time. 

### Steps to Reproduce the Bug

1. Signed in.
2. work
3. sign out
4. go to collect paycheck
5. $0 collected

### Expected Behavior

All I expected to happen was to collect my paycheck for working

### Screenshots/Videos

I don't have any video's and can't find screen shots for the game on my computer anymore. 

### Extra Notes (Optional)

I wasn't sure which logs you needed or which one would show you the errors and time I was clocked in and worked, so I put the logs I have for the day down below. Thank you for helping! 

### Log File

[CitizenFX_log_2022-09-08T163217.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9531049/CitizenFX_log_2022-09-08T163217.log)
[CitizenFX_log_2022-09-08T163254.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9531050/CitizenFX_log_2022-09-08T163254.log)
[CitizenFX_log_2022-09-08T220610.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9531051/CitizenFX_log_2022-09-08T220610.log)
[CitizenFX_log_2022-09-08T220649.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9531052/CitizenFX_log_2022-09-08T220649.log)

**Comment by xXJamieXx** [comment]
I see you and others being paid for the job in the past few days so this was probably just a temporary issue.

**Comment by RoseiiNaytool** [comment]
It started working right when I logged back in to work, but I lost hours worth of working and just wanted to get paid for it. Sorry I just saw the reply for it. I was told to report it here.
