### ISSUE TITLE
[BUG] Dremmel not fixing?

### ISSUE THREAD

**Issue by SpiceF0x** [ParadoxGamingRP/bugs-and-suggestions#736]
### Your Discord Name

spicedf0x#2127

### A clear and concise description of what the bug is

Used multiple steel bits to fix my dremmel and it's just not working? 

### Steps to Reproduce the Bug

1. Use steel bit 
2. Animal of fixing goes through
3. Dremmel still broken 75% of the time so far

### Expected Behavior

A fixed dremmel

### Screenshots/Videos

https://streamable.com/o5iv2n

**Comment by JnKTechstuff** [comment]
In the video you failed to do the one thing I needed you to do...

Repair the drill and look at it in your inventory...

**Comment by JnKTechstuff** [comment]
Fixed
