### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by sveelazquez** [ParadoxGamingRP/bugs-and-suggestions#737]
### Your Discord Name

Sergio V#1754

### A clear and concise description of what the bug is

After the latest server update (09/10) my fishing box has glitched and I can not open it. Nor can I put something in it.  It also doesn’t have the squares that show you have things

### Steps to Reproduce the Bug

Glitch

### Expected Behavior

To be able to work properly 

### Screenshots/Videos

![C7E35752-6CD5-4DD2-A771-BD37769F5A3C](https://user-images.githubusercontent.com/113056983/189244519-0d05a3d9-921f-4b84-a699-b8153c3621af.png)

**Comment by xXJamieXx** [comment]
Unable to reproduce this. You probably just have an old broken box and need to buy a new one.
