### ISSUE TITLE
[ENHANCEMENT] Update Tattoos to the latest DLC

### ISSUE THREAD

**Issue by natashajoan** [ParadoxGamingRP/bugs-and-suggestions#738]
**Your Discord Name**
Natasha_ahsataN#7098

**Describe the annoyance**
Twas simply wondering if the tattoos could get updated to the latest DLC, because there’s some sick tattoos that I know people would love to have :) 

**To Reproduce**
1. Update tattoos to the latest DLC
2. Get tattoos
3. Look gr8

**Requested behavior**

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by xXJamieXx** [comment]
Added next restart.
