### ISSUE TITLE
[BUG] Car parts job giving wrong car names

### ISSUE THREAD

**Issue by M1ngh** [ParadoxGamingRP/bugs-and-suggestions#739]
### Your Discord Name

Minghee#0876

### A clear and concise description of what the bug is

I was doing the Car parts job and i got a Annis Sandking, Sankings are from Vapid. i try to deliver the Sandking SWB and was not the right veichle was unable to find the XL until filling the report

### Steps to Reproduce the Bug

1. give message for Annis Sandking
2. deliver a Sandking SBW
3. is not the right car

### Expected Behavior

Expect behavior is giving the correct information on the job email

### Screenshots/Videos

![FiveM_b2699_GTAProcess_WeGwGsBnk4](https://user-images.githubusercontent.com/107653844/189408315-4dd1c675-ba0b-46d2-a6ed-4eb48ed28903.png)
![FiveM_b2699_GTAProcess_v6X4OOo4wq](https://user-images.githubusercontent.com/107653844/189409557-6eebd3d6-642a-4baf-acfc-e2ffa3d35a90.png)
![FiveM_b2699_GTAProcess_sduh7iKXSj](https://user-images.githubusercontent.com/107653844/189409566-3ae5dfa0-a153-4d5c-a3c2-df12b1eabf4a.png)

**Comment by xXJamieXx** [comment]
Should be fixed next restart.
