### ISSUE TITLE
[BUG] Weedplants poofs

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#740]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

Was planting weed, and when I had done maybe 11 seeds all of them poofed. 

### Steps to Reproduce the Bug

Plant seed, feed and water it as normal
Nothing else
Poof

### Expected Behavior

Being able to plant my seeds and they not poofing. 

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/AbkDpzKxIDDd8/d1337oL2uH6G?invite=cr-MSw3dkUsNDU3NjU0MzAs

### Log File

[CitizenFX_log_2022-09-09T164723.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9537666/CitizenFX_log_2022-09-09T164723.log)

**Comment by CecilButler** [comment]
im having the same issues with my seeds at smoke on the water

**Comment by xXJamieXx** [comment]
Should be fixed.
