### ISSUE TITLE
[ENHANCEMENT] Changing Garbage to give materials to Combat the Plastic Shortage

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#742]
**Your Discord Name**
Shrew#1219

**Describe the annoyance**
With the bottles not coming back in the recycling plant, there is a shortage of ways to get plastic which is a hinderance to weed selling, and businesses that use plastics as one of their ingredients.

**To Reproduce**
[Steps to reproduce the annoyance]
1.  Try Diving after an hour someone got only 10 plastic
2.  Try Garbage
3.  Try hunting or farming than recycling, Hunting bag and fertilizers only give 1 plastic.

**Requested behavior**
Change Garbage of instead of giving a lot of cash, to giving materials from the bags, like plastic, metal scrap and GLASS.

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by xXJamieXx** [comment]
Not planned at this time.
