### ISSUE TITLE
[BUG] misstacking item in mule trunk causing either a random item or last touched to be deleted

### ISSUE THREAD

**Issue by mjb328** [ParadoxGamingRP/bugs-and-suggestions#749]
### Your Discord Name

MJB328#5303

### A clear and concise description of what the bug is

I was moving fish from my pockets to my mule trunk and accidentally stacked a couple bass onto a stack of cod. This caused the stack of cod to transfer to my pockets. Since i've experienced this glitch multiple times i knew it would deleted something so i tried to move my more valuable ice boxes in my trunk to my pockets but i couldn't. after exiting the mule trunk the last item i touched, an icebox (17/20) full of tiger shark was deleted. Idk what in the scripts causes the item to be deleted but it is triggered by mistacking/swapping items from trunk to pockets

### Steps to Reproduce the Bug

1. put 4 iceboxes, 10 cod and 5 bass in a mule trunk leave 5 bass in you pockets
2. take the 5 bass and stack them onto the 10 cod. dont exit trunk
3. after the 5 bass and 10 cod swap places moving an ice box note all trunk item placements.
4. after moving an icebox exit then re-eneter trunk. either a random item or the icebox that was last touched may be gone.

### Expected Behavior

That misstacking/swapping items from pockets to trunk shouldn't be deleting items from the trunk.

### Screenshots/Videos

[will replicate later](https://streamable.com/f6bwbj)

### Log File
[trunksbug.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9544344/trunksbug.txt)

**Comment by JnKTechstuff** [comment]
This is what happens when people continuously min/max shit by using box trucks now to store all their shit.

Should just leave it so you guys actually play

**Comment by mjb328** [comment]
I don't use as storage for random stuff and let it sit in garage all day i use it to do jobs in bulk so I dont have make of make tons of trip in a Bison. The trunk set up was just to show what my trunk would look like when I'm out fishing. If not fishing with it I empty it out and for whatever job I need it for next.

**Comment by JnKTechstuff** [comment]
Possibly fixed: https://github.com/ParadoxGamingRP/Server-Development/commit/d1129a3c6d85caafdd4230e179eb4902649449a1
