### ISSUE TITLE
[BUG] has permit, can't buy gun

### ISSUE THREAD

**Issue by wyfuwsehifse** [ParadoxGamingRP/bugs-and-suggestions#750]
### Your Discord Name

lucky#5298

### A clear and concise description of what the bug is

i have a gun permit but i cant buy a gun

### Steps to Reproduce the Bug

wfwwfwfw

### Expected Behavior

u cant buy guns

### Screenshots/Videos

wfwf

### Extra Notes (Optional)

fwfw

### Log File

[CitizenFX_log_2022-09-11T214801.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9544573/CitizenFX_log_2022-09-11T214801.log)
[CitizenFX_log_2022-09-11T220048.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9544574/CitizenFX_log_2022-09-11T220048.log)
[CitizenFX_log_2022-09-11T220121.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9544575/CitizenFX_log_2022-09-11T220121.log)
[CitizenFX_log_2022-09-11T221414.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9544576/CitizenFX_log_2022-09-11T221414.log)
[CitizenFX_log_2022-09-11T221510.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9544577/CitizenFX_log_2022-09-11T221510.log)
[CitizenFX_log_2022-09-11T221936.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9544578/CitizenFX_log_2022-09-11T221936.log)
[CitizenFX_log_2022-09-11T222004.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9544579/CitizenFX_log_2022-09-11T222004.log)
[CitizenFX_log_2022-09-11T233443.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9544580/CitizenFX_log_2022-09-11T233443.log)
[CitizenFX_log_2022-09-11T233717.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9544581/CitizenFX_log_2022-09-11T233717.log)
[CitizenFX_log_2022-09-12T000336.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9544582/CitizenFX_log_2022-09-12T000336.log)
[CitizenFX_log_2022-09-12T000520.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9544583/CitizenFX_log_2022-09-12T000520.log)
[CitizenFX_log_2022-09-12T030843.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9544585/CitizenFX_log_2022-09-12T030843.log)
[CitizenFX_log_2022-09-12T030932.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9544586/CitizenFX_log_2022-09-12T030932.log)

**Comment by xXJamieXx** [comment]
You didn't provide the required information so we cannot continue with this bug report.
