### ISSUE TITLE
[BUG] Radar Stuck

### ISSUE THREAD

**Issue by o7JStreet** [ParadoxGamingRP/bugs-and-suggestions#752]
### Your Discord Name

BayHarbourButcher#6820

### A clear and concise description of what the bug is

Once you jump into a police vehicle whether it's your personal or a shared motorpool, for some people it intends to freeze on the menu when you are attempting to set the radar up forcing you to have to restart your game, this does not fix the issue either.

### Steps to Reproduce the Bug

Ctrl + M
Toggle Radar
Should freeze you but I know only a few experience this issue.

### Expected Behavior

You should be able to toggle the radar and set it up accordingly, whether you are adjusting it or not without having it freeze

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/AI6DOVos0mkWD/d13370zuf7ga?invite=cr-MSxPRXksMjM4MzMzNzYs

### Log File

[radar bug.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9556990/radar.bug.txt)

**Comment by JnKTechstuff** [comment]
Probably a bind you changed

**Comment by JnKTechstuff** [comment]
No response in 7 days; assumed fixed
