### ISSUE TITLE
[BUG] Cruisers Stops Actions of Radio, Unlocking/Locking, etc

### ISSUE THREAD

**Issue by David-5634** [ParadoxGamingRP/bugs-and-suggestions#762]
### Your Discord Name

TheAdmiral#3351

### A clear and concise description of what the bug is

Multiple individuals in the LSPD and BCSO are having issues when they are in the cruisers. Outside of the cruiser everything works fine, however, the minute you get in the cruiser the radio doesn't work, can't open inventory, can't open doors or bollards of the bay, and the CAD gets stuck open or freezes up. We originally had issues with the personal stash but that was fixed now having issues while sitting in the cruiser; nothing works. 

### Steps to Reproduce the Bug

1. Get in your cruiser
2. Open inventory
3. Open the garage door or bollards
4. Open CAD

### Expected Behavior

Hopefully get this fixed 

### Screenshots/Videos

N/A

**Comment by StealthyRiot** [comment]
Appears to be related to our lights/sirens. If I flick my lights/sirens on and off, I can usually get the MRPD gate to lock/unlock.

**Comment by JnKTechstuff** [comment]
Fixed on live: https://github.com/ParadoxGamingRP/Server-Development/commit/306221dd5d26790a35e0f088467f61838aa9d8c7
