### ISSUE TITLE
[BUG] EMS teleports at pillbox

### ISSUE THREAD

**Issue by ithegreatgatsby** [ParadoxGamingRP/bugs-and-suggestions#764]
### Your Discord Name

Chris

### A clear and concise description of what the bug is

all the teleports at pillbox do not work.   Morgue helipad and basement teleports do not work, Been told it was a issue a couple days ago and then it worked for a time period or whatever and now today they are not working again.

### Steps to Reproduce the Bug

Go to teleports and try to third eye them  nothing shows up purple etc nothing in f8 

### Expected Behavior

be able to teleport into the correct areas

### Screenshots/Videos

n/a

**Comment by ithegreatgatsby** [comment]
it started working again but then tonight they stopped again. Happen after the core was restarted so that might be the issue?

**Comment by xXJamieXx** [comment]
Likely happened because of a resource restarting or similar. Not an issue that needs fixing.
