### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Umbreona** [ParadoxGamingRP/bugs-and-suggestions#766]
### Your Discord Name

Umbreona#3294

### A clear and concise description of what the bug is

couldnt pick up weed table when placed outside near the place you purchase it

### Steps to Reproduce the Bug

buy table
drive over wood bridge to shed
place table
cant pick up

### Expected Behavior

i expected to be able to pick up the table

### Screenshots/Videos

https://www.youtube.com/watch?v=VTx5HuIIG5E

**Comment by JnKTechstuff** [comment]
Already been fixed, check before making bug reports

**Comment by Umbreona** [comment]
if its already been fixed why did it just happen?
