### ISSUE TITLE
[BUG] Bank not paying out shift money.

### ISSUE THREAD

**Issue by Burnsy19** [ParadoxGamingRP/bugs-and-suggestions#769]
### Your Discord Name

Burnsy#2499

### A clear and concise description of what the bug is

After doing a shift at Bikini Tow, I went to collect my paycheck from the bank. Upon collecting my paycheck it comes up saying that I have been payed $0

### Steps to Reproduce the Bug

1) Complete a shift at Bikini Tow.
2) Head to bank.
3) Collect paycheck.

### Expected Behavior

Expect to be payed the correct amount for the shift and not $0

### Screenshots/Videos

https://i.imgur.com/RCeKiBq.png

**Comment by xXJamieXx** [comment]
Unable to reproduce this issue and will therefore be closing it.
