### ISSUE TITLE
[ENHANCEMENT] Police Vehicle Enhancement

### ISSUE THREAD

**Issue by OwlCherry** [ParadoxGamingRP/bugs-and-suggestions#771]
**Your Discord Name**
OwlCherry#6969

**Describe the annoyance**
CID Durango. comes out currently with HC livery and all extra's. 

**To Reproduce**
1.  pull out of motor pool
2.  get white HC durango

**Requested behavior**
Pulling out of the motorpool, I'd like for it to have dark tint on windows. Stone Silver colour (pearlescent) with extra's 2 and 3 only

**Screenshots**
![image](https://user-images.githubusercontent.com/97353529/190724449-07e16d68-d60a-4785-91d8-8c6d376adefa.png)

**Additional context**
[Add any other context about the enhancement here]

**Comment by JnKTechstuff** [comment]
You don't have a CID Durango
