### ISSUE TITLE
[BUG] no dealerships in city

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#772]
### Your Discord Name

Ssara#7821 

### A clear and concise description of what the bug is

There are no dealerships in city, went around and couldn't see them and not located in the map. 

### Steps to Reproduce the Bug

Go to a dealership
That's it. 

### Expected Behavior

Be able to buy a car, but there was no dealership 

### Screenshots/Videos

N/a

**Comment by xXJamieXx** [comment]
Fixed.
