### ISSUE TITLE
[BUG] All Furniture inside my house dissapeared.

### ISSUE THREAD

**Issue by natashajoan** [ParadoxGamingRP/bugs-and-suggestions#773]
### Your Discord Name

Natasha_ahsataN#7098

### A clear and concise description of what the bug is

I entered my house after Tsunami and all my furniture has disappeared, I tried the exiting the house and re-entering and even re-logging, and still nothing. 
I checked my Garage Interior and Emily checked her Ranching Out interior, and all the furniture is in those, so it seems to be an issue with just my house. I did notice something mentioning Michael in the f8 once I entered the house. 

### Steps to Reproduce the Bug

1.  I'm not too sure, since Scout has the same interior and nothing happened to her house. 

### Expected Behaviour

To go into my house and see all the furniture I have placed over many hours. 

### Screenshots/Videos

n/a

### Log File

[CitizenFX_log_2022-09-17T221719.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9592763/CitizenFX_log_2022-09-17T221719.log)

**Comment by JnKTechstuff** [comment]
Rare occurrence which can happen in extremes cases in people with slower hardware in which the data received is not received in time. 

Idk how fix this
