### ISSUE TITLE
[BUG] $0 truck payout, in debt because of tattoo

### ISSUE THREAD

**Issue by sahiiiie** [ParadoxGamingRP/bugs-and-suggestions#774]
### Your Discord Name

sahiiiie#1630

### A clear and concise description of what the bug is

I was doing garbage/sanitation runs and received a $0 payout, I also accidentally went into debt buying a tattoo however, I did not have enough money in my account to purchase the tattoo. 

### Steps to Reproduce the Bug

I'm not quite sure, I just did a sani run and accidentally clicked purchase on a right arm tattoo, I believe it was the wolf arm tattoo 

### Expected Behavior

For the tattoo, I just didn't expect it to go through without enough funds in the account. I'm quite new to the city, so I'm unsure if this is a bug or not. 

For the pay out, I believe the payout should've been $136 for three stops? 

### Screenshots/Videos

![Screenshot 2022-09-18 031548](https://user-images.githubusercontent.com/113827410/190894988-2797fba6-b4a9-44dc-9dea-31191a13c13a.png)

**Comment by sahiiiie** [comment]
Update: It only happens if I complete the entire run. If I stop the run early, I get paid correctly.

**Comment by xXJamieXx** [comment]
Tattoo issue fixed next restart. Will look at garbage soon enough.

**Comment by xXJamieXx** [comment]
Unable to reproduce this. Completed a route fully and got paid, then completed only 3 stops and got paid.

Full route:
![image](https://user-images.githubusercontent.com/11248045/198845996-90b19940-4353-4514-ab46-693d52cf4319.png)

Partial route:
![image](https://user-images.githubusercontent.com/11248045/198846211-f7a3c51e-ba19-4a29-9c48-de090f0536af.png)

Are you still experiencing this issue?

**Comment by xXJamieXx** [comment]
Closing stale issue due to no response.
