### ISSUE TITLE
[ENHANCEMENT] AR Slings

### ISSUE THREAD

**Issue by SpicyWB** [ParadoxGamingRP/bugs-and-suggestions#778]
**Your Discord Name**
[Spicy#5426]

Jake please. We want these. They are not ugly they are sexy and make us look cool. No but for real I know this has been a very popular thing the pd has talked about and wanted. At first it could just be pd to have them but eventually could work towards all AR's AK's Uzi's Tommy's and whatever else is to come.

**Screenshots**
[can add screenshots once im not on my my phone but I'm pretty sure you
Know what they look like]

**Comment by JnKTechstuff** [comment]
No
