### ISSUE TITLE
[BUG] <Unable to give water to any animals>

### ISSUE THREAD

**Issue by drugfree420** [ParadoxGamingRP/bugs-and-suggestions#779]
### Your Discord Name

drug_free#8790

### A clear and concise description of what the bug is

When attempting to give water to the chickens it gives you and error saying " 'watering' is not a valid emote." after you go through the waiting bar it then says "no emote to cancel." Tested it with a cow also and the same thing happens. After the whole cycle has ran through the hydration does not go up on the animal nor does it take any water bottle or water from the can.

### Steps to Reproduce the Bug

1. Purchase a animal from the rancher.
2. Attempt to give the animal water.
3. Get the error saying there is not valid emote.
4. Animal is still thirsty and watering can is still 100% full.

### Expected Behavior

Be able to give animals the water and their hydration go up when doing so.

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/By30nyAIJpO3K/d1337teO2jiT?invite=cr-MSxFUDYsMjM3OTE0MjMs

https://medal.tv/games/gta-v/clips/By8Hpmn1NAVt1/d1337rC6JwQh?invite=cr-MSxEencsMjM3OTE0MjMs

**Comment by JnKTechstuff** [comment]
Fixed
