### ISSUE TITLE
[BUG] <short description>

### ISSUE THREAD

**Issue by Vader37** [ParadoxGamingRP/bugs-and-suggestions#784]
### Your Discord Name

Vader3#3443

### A clear and concise description of what the bug is

I have keys to someone else’s house but can’t spawn there. We have tried flying out in and taking keys and giving them back but still doesn’t work.

### Steps to Reproduce the Bug

Get keys 
Fly out
Fly in 
Can’t spawn there 

### Expected Behavior

Get keys 
Fly out
Fly in 
Spawn there 

### Screenshots/Videos

None

**Comment by JnKTechstuff** [comment]
My response has more effort than this bug report
