### ISSUE TITLE
[BUG] Able to pull out non-impounded cars

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#788]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

I am on tow right now, got a call for car. Found a bike on the way, picked it up. When I was putting the bike on my tow truck the guy came by on the same bike. 
I've also had a Bison do the same thing where it says on the app its impounded, buts its not so they are able to pull out another one. I do not know if its intended or not. 

### Steps to Reproduce the Bug

Leave your car anywhere where it doesnt despawn
Wait till app says impounded or end up in hospital
Pull out car from impound, head to location and find another car.

### Expected Behavior

Be able to not pull out car until its impounded would be amazing. I think maybe that's how it was supposed to be cause now I see people out and about on cars that are supposed to be impounded but are not.

### Screenshots/Videos

N/A

**Comment by xXJamieXx** [comment]
Fixed. https://github.com/ParadoxGamingRP/Server-Development/commit/15e4da00d02ec7e3fd56b1b575e85b3cf3f552c4
