### ISSUE TITLE
[BUG] Cannot spawn into house with keys

### ISSUE THREAD

**Issue by Vaderdddd** [ParadoxGamingRP/bugs-and-suggestions#789]
### Your Discord Name

Vader#3443

### A clear and concise description of what the bug is

Cant spawn in at a house i have keys to. We have tried taking them and giving them back but still does not work.

### Steps to Reproduce the Bug

Get keys 
Fly out
Fly in
Cant spawn at house

### Expected Behavior

Get keys fly out and fly in and be able to spawn at house you have keys to

### Screenshots/Videos

![Capture](https://user-images.githubusercontent.com/112463114/191628328-21e5389f-89f1-459f-8c07-6ee173ba1187.PNG)

![Capture](https://user-images.githubusercontent.com/112463114/191628656-c0ca43bb-db27-4a30-811c-aecf10f7bf9a.PNG)

### Log File

[CitizenFX_log_2022-09-21T233934.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9621040/CitizenFX_log_2022-09-21T233934.log)

**Comment by JnKTechstuff** [comment]
Unable to replicate and havent seen since
