### ISSUE TITLE
[ENHANCEMENT] Davis PD

### ISSUE THREAD

**Issue by wallace296** [ParadoxGamingRP/bugs-and-suggestions#792]
**Your Discord Name**
Wallace316#5863

**Describe the annoyance**
Davis PD needs the following things to be used as a proper Police Dept, High Command wants us to use the dept more 

1. ATM
2. Fingerprinting station (as of now we have some weird one that doesnt work like mrpd its a fingerprint ink test)
3. all the cell locks are flipped

**Comment by ithegreatgatsby** [comment]
moved to dev tickets
