### ISSUE TITLE
Paycheck Didn't Register To Account 

### ISSUE THREAD

**Issue by MagicMyers** [ParadoxGamingRP/bugs-and-suggestions#793]
### Your Discord Name

MrSpooksAhoy #5937

### A clear and concise description of what the bug is

I collected my paycheck, I got a notification that I had collected $2335 I believe it was, but the money was not added to account and did not show up on my statement at the atm. 

### Steps to Reproduce the Bug

Unsure as Finn said he had no problem with his, but Impactlegacy95 and also Zen Holiday had the same problem. 

### Expected Behavior

I would expect that the money would not be added to the accounts of anyone affected by this bug. 

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/BT6En0pdAYN1V/d1337Paq2Tnk?invite=cr-MSxjRDIsMTA4MzgyMjMxLA

### Extra Notes (Optional)

Only that it doesn't appear to happening to everyone, just a few people. 

### Log File

[CitizenFX_log_2022-09-22T220757.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9630194/CitizenFX_log_2022-09-22T220757.log)

**Comment by xXJamieXx** [comment]
Unable to reproduce this issue and will therefore be closing it.
