### ISSUE TITLE
[BUG] Rusty Rebel not available at lowend dealership

### ISSUE THREAD

**Issue by Kromlec** [ParadoxGamingRP/bugs-and-suggestions#799]
### Your Discord Name

Kromlec#3389

### A clear and concise description of what the bug is

When you try to swap the cars at the low end dealership to the rusty rebel it doesn't appear.

### Steps to Reproduce the Bug

Go to low end dealer
try to swap car to rusty rebel
no rusty rebel

### Expected Behavior

Should be able to buy rusty rebel not a pos Vulcar

### Screenshots/Videos

n/a

### Log File

[rusty rebel.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9637976/rusty.rebel.txt)

**Comment by ithegreatgatsby** [comment]
This was added awhile ago
