### ISSUE TITLE
[ENHANCEMENT] MRPD Clothing Store

### ISSUE THREAD

**Issue by xaroht** [ParadoxGamingRP/bugs-and-suggestions#803]
**Your Discord Name**
thørax#0098

**Describe the annoyance**
Annoying people running into the clothing store 

**To Reproduce**
[Steps to reproduce the annoyance]
1.  Be a cop.
2. want to change drip
3. some obnoxious asshole comes in screaming some dumb shit

**Requested behavior**
for me to be able to cycle through police issued uniforms at a police station.

The very same as it was in 2.0.

This would improve the quality of my life greatly because it is greatly convenient to be able to quickly change at MRPD.

**Comment by xaroht** [comment]
I mean to make outfits, like 2.0

**Comment by ithegreatgatsby** [comment]
We did away with having full clothing stores in PD EMS etc due to it making more RP sense to go to a store to buy clothing. So not looking to add those in PD or hospitals at this time. I would recommend just using less popular clothing stores. Thanks!
