### ISSUE TITLE
[ENHANCEMENT] Expand pig farming functionality to make pigs more widely farmed

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#806]
**Your Discord Name**
Shrew#1219

**Describe the annoyance**
Pigs are not as ranched like the cows with milk and chicken with eggs. A possible solution is mushrooms with pigs which can open up a lot of stuff for other people like magic mushrooms or penicillin. Mushrooms could also then be used in recipes for restaurants as well. Even to the point of truffle chocolate to name an example.

**To Reproduce**
[Steps to reproduce the annoyance]
1.  Get carrots
2.  Farm Pigs
3.  Only get Pork

**Requested behavior**
To gather a new source which is Mushrooms

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by ShaymusSavage** [comment]
If you are referring to the production of Psyilocybin, it is usually acquired from Cow Manure at certain times in the morning. 
This would be a cool idea for that kind of production.

**Comment by ithegreatgatsby** [comment]
Next update/restart
