### ISSUE TITLE
[BUG] Katie at lower pillbox releases patients sometimes

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#807]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

On 2 occasions we've had issues with the nurse, Katie, at lower pillbox doesnt fully send the suspect through, using the fancy stretcher. 

### Steps to Reproduce the Bug

Have a suspect
Head to lower Pillbox
Put them with Katie, nurse at lower
See them run away from upper without them being in the treatment room

### Expected Behavior

Be able to take suspects to lower and check them in

### Screenshots/Videos

No sir, no pictures

**Comment by xXJamieXx** [comment]
Can we confirm they actually didn't get sent through or is it just a timing issue? I noticed some talk about not having fully determined the exact process of this so can we get an update on whether this is actually the outlined issue or perhaps just user erorr?

**Comment by SaraLef** [comment]
I can confirm, I had an officer inside patient room when sending up a suspect.
Someone was talking about texture budget with the suspects. They were not in the room. One suspect said he ended up in the abyss and went back in to pillbox to wait. Another suspect fled because of it.

**Comment by ithegreatgatsby** [comment]
A lot of us never had issues. and it's been very 1 off when this happens. My guess is texture loss issues and textures not loading fast enough for some. but we dont have any issues with the other check in locations
