### ISSUE TITLE
[BUG] Getting Charged Impound Fees on Personal PD Vehicle

### ISSUE THREAD

**Issue by Drunkle716** [ParadoxGamingRP/bugs-and-suggestions#809]
### Your Discord Name

Drunkle716#7571

### A clear and concise description of what the bug is

Went to get my personal cruiser out of impound and was charged $1500 for it which is not the norm.

### Steps to Reproduce the Bug

1. Get PD personal car from impound.
2. Pay $1500

### Expected Behavior

1. Get PD personal car from impound.
2. Not pay for it.

### Screenshots/Videos

https://i.imgur.com/senSY2z.png

**Comment by xXJamieXx** [comment]
Cops should pay for impound just like everyone else. I have lowered the cost slightly though.
