### ISSUE TITLE
[BUG] Pumpkins in the Farmer's Market

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#810]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

Tried selling pumpkins to the Farmer's Market and it came up as 0$ profit, but it didn't take the pumpkins or give any profit.

### Steps to Reproduce the Bug

1. Farm Pumpkins
2. Give Pumpkins in crop deposit
3. Sell Pumpkins

### Expected Behavior

Selling to the farming buyer will give profit for pumpkins grown.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98053772/192600817-2d73972d-87ce-4137-9461-ef2ad8a3a428.png)

**Comment by xXJamieXx** [comment]
This issue has been fixed and will be pushed in the next restart.
