### ISSUE TITLE
[BUG] Truck Robbery Spawns Trucks in a Pile You Can't Rob

### ISSUE THREAD

**Issue by Drunkle716** [ParadoxGamingRP/bugs-and-suggestions#811]
### Your Discord Name

Drunkle716#7571

### A clear and concise description of what the bug is

While attempting to find a bank truck using the radio scanner. Traffic was heard but a pile of unrobbable bank trucks was the only thing found. 

### Steps to Reproduce the Bug

1. Use radio scanner to scan for bank trucks.
2. Have it say traffic heard.
3. Find a pile of unrobbable bank trunks.  

### Expected Behavior

1. Use radio scanner to scan for bank trucks.
2. Have it say traffic heard.
3. Find a bank truck you can rob.

### Screenshots/Videos

https://i.imgur.com/Ty6S82D.jpeg
https://i.imgur.com/n5n9Pyi.jpeg

### Log File

[CitizenFX_log_2022-09-28T011339.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9661125/CitizenFX_log_2022-09-28T011339.log)
[CitizenFX_log_2022-09-27T220258.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9661126/CitizenFX_log_2022-09-27T220258.log)

**Comment by SpicyWB** [comment]
https://medal.tv/games/gta-v/clips/CV4PDBCS4ulkT/d1337UhR66z1?invite=cr-MSx3ajQsNDQ0ODc0NTAs Still an ongoing issue. Truck spawns with every scan. Unable to thermite and no guards. Logs will be added soon by Thorax
https://i.imgur.com/Gb3jqjK.jpeg 
https://i.imgur.com/kr0d4HT.jpeg

**Comment by xaroht** [comment]
[CitizenFX_log_2022-09-28T111211.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688120/CitizenFX_log_2022-09-28T111211.log)
[CitizenFX_log_2022-09-28T190317.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688121/CitizenFX_log_2022-09-28T190317.log)
[CitizenFX_log_2022-09-28T220144.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688122/CitizenFX_log_2022-09-28T220144.log)
[CitizenFX_log_2022-09-29T001431.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688123/CitizenFX_log_2022-09-29T001431.log)
[CitizenFX_log_2022-09-29T171520.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688124/CitizenFX_log_2022-09-29T171520.log)
[CitizenFX_log_2022-09-29T171959.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688125/CitizenFX_log_2022-09-29T171959.log)
[CitizenFX_log_2022-09-29T191720.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688126/CitizenFX_log_2022-09-29T191720.log)
[CitizenFX_log_2022-09-29T202608.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688127/CitizenFX_log_2022-09-29T202608.log)
[CitizenFX_log_2022-09-29T215931.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688128/CitizenFX_log_2022-09-29T215931.log)
[CitizenFX_log_2022-09-29T224524.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688129/CitizenFX_log_2022-09-29T224524.log)
[CitizenFX_log_2022-09-30T011745.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688130/CitizenFX_log_2022-09-30T011745.log)
[CitizenFX_log_2022-09-30T021344.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688131/CitizenFX_log_2022-09-30T021344.log)
[CitizenFX_log_2022-09-30T021514.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688132/CitizenFX_log_2022-09-30T021514.log)
[CitizenFX_log_2022-09-30T104351.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688133/CitizenFX_log_2022-09-30T104351.log)
[CitizenFX_log_2022-09-30T193114.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688134/CitizenFX_log_2022-09-30T193114.log)
[CitizenFX_log_2022-09-30T194731.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688135/CitizenFX_log_2022-09-30T194731.log)
[CitizenFX_log_2022-09-30T215944.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688136/CitizenFX_log_2022-09-30T215944.log)
[CitizenFX_log_2022-09-23T220028.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688137/CitizenFX_log_2022-09-23T220028.log)
[CitizenFX_log_2022-09-24T001709.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688138/CitizenFX_log_2022-09-24T001709.log)
[CitizenFX_log_2022-09-24T013042.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688139/CitizenFX_log_2022-09-24T013042.log)
[CitizenFX_log_2022-09-24T013652.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688140/CitizenFX_log_2022-09-24T013652.log)
[CitizenFX_log_2022-09-24T014306.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688141/CitizenFX_log_2022-09-24T014306.log)
[CitizenFX_log_2022-09-24T092538.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688142/CitizenFX_log_2022-09-24T092538.log)
[CitizenFX_log_2022-09-24T100008.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688143/CitizenFX_log_2022-09-24T100008.log)
[CitizenFX_log_2022-09-24T100313.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688144/CitizenFX_log_2022-09-24T100313.log)
[CitizenFX_log_2022-09-24T150706.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688145/CitizenFX_log_2022-09-24T150706.log)
[CitizenFX_log_2022-09-24T194821.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688146/CitizenFX_log_2022-09-24T194821.log)
[CitizenFX_log_2022-09-24T215257.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688147/CitizenFX_log_2022-09-24T215257.log)
[CitizenFX_log_2022-09-24T215728.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688148/CitizenFX_log_2022-09-24T215728.log)
[CitizenFX_log_2022-09-24T215755.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688149/CitizenFX_log_2022-09-24T215755.log)
[CitizenFX_log_2022-09-24T234424.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688150/CitizenFX_log_2022-09-24T234424.log)
[CitizenFX_log_2022-09-24T234450.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688151/CitizenFX_log_2022-09-24T234450.log)
[CitizenFX_log_2022-09-25T101104.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688152/CitizenFX_log_2022-09-25T101104.log)
[CitizenFX_log_2022-09-25T115237.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688153/CitizenFX_log_2022-09-25T115237.log)
[CitizenFX_log_2022-09-25T173539.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688154/CitizenFX_log_2022-09-25T173539.log)
[CitizenFX_log_2022-09-25T175443.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688155/CitizenFX_log_2022-09-25T175443.log)
[CitizenFX_log_2022-09-25T205857.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688156/CitizenFX_log_2022-09-25T205857.log)
[CitizenFX_log_2022-09-25T220358.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688157/CitizenFX_log_2022-09-25T220358.log)
[CitizenFX_log_2022-09-26T005616.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688158/CitizenFX_log_2022-09-26T005616.log)
[CitizenFX_log_2022-09-27T102228.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688159/CitizenFX_log_2022-09-27T102228.log)
[CitizenFX_log_2022-09-27T102341.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688160/CitizenFX_log_2022-09-27T102341.log)
[CitizenFX_log_2022-09-28T102556.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9688161/CitizenFX_log_2022-09-28T102556.log)

**Comment by xaroht** [comment]
[CitizenFX_log_2022-10-12T200923.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790092/CitizenFX_log_2022-10-12T200923.log)
[CitizenFX_log_2022-10-12T204353.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790093/CitizenFX_log_2022-10-12T204353.log)
[CitizenFX_log_2022-10-12T220257.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790094/CitizenFX_log_2022-10-12T220257.log)
[CitizenFX_log_2022-10-12T221710.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790095/CitizenFX_log_2022-10-12T221710.log)
[CitizenFX_log_2022-10-12T225031.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790096/CitizenFX_log_2022-10-12T225031.log)
[CitizenFX_log_2022-10-13T014108.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790097/CitizenFX_log_2022-10-13T014108.log)
[CitizenFX_log_2022-10-13T031020.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790098/CitizenFX_log_2022-10-13T031020.log)
[CitizenFX_log_2022-10-13T215148.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790099/CitizenFX_log_2022-10-13T215148.log)
[CitizenFX_log_2022-10-13T220042.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790100/CitizenFX_log_2022-10-13T220042.log)
[CitizenFX_log_2022-10-13T220700.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790101/CitizenFX_log_2022-10-13T220700.log)
[CitizenFX_log_2022-10-13T235529.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790102/CitizenFX_log_2022-10-13T235529.log)
[CitizenFX_log_2022-10-14T000014.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790103/CitizenFX_log_2022-10-14T000014.log)
[CitizenFX_log_2022-10-14T002222.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790104/CitizenFX_log_2022-10-14T002222.log)
[CitizenFX_log_2022-10-14T183150.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790105/CitizenFX_log_2022-10-14T183150.log)
[CitizenFX_log_2022-10-07T193112.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790106/CitizenFX_log_2022-10-07T193112.log)
[CitizenFX_log_2022-10-07T220846.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790107/CitizenFX_log_2022-10-07T220846.log)
[CitizenFX_log_2022-10-08T220123.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790108/CitizenFX_log_2022-10-08T220123.log)
[CitizenFX_log_2022-10-09T055221.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790109/CitizenFX_log_2022-10-09T055221.log)
[CitizenFX_log_2022-10-09T183918.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790110/CitizenFX_log_2022-10-09T183918.log)
[CitizenFX_log_2022-10-09T195358.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790111/CitizenFX_log_2022-10-09T195358.log)
[CitizenFX_log_2022-10-09T220035.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790112/CitizenFX_log_2022-10-09T220035.log)
[CitizenFX_log_2022-10-09T222254.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790113/CitizenFX_log_2022-10-09T222254.log)
[CitizenFX_log_2022-10-09T223915.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790114/CitizenFX_log_2022-10-09T223915.log)
[CitizenFX_log_2022-10-10T210546.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790115/CitizenFX_log_2022-10-10T210546.log)
[CitizenFX_log_2022-10-10T213242.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790116/CitizenFX_log_2022-10-10T213242.log)
[CitizenFX_log_2022-10-10T215049.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790117/CitizenFX_log_2022-10-10T215049.log)
[CitizenFX_log_2022-10-11T174115.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790118/CitizenFX_log_2022-10-11T174115.log)
[CitizenFX_log_2022-10-11T215938.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790119/CitizenFX_log_2022-10-11T215938.log)
[CitizenFX_log_2022-10-11T215946.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790120/CitizenFX_log_2022-10-11T215946.log)
[CitizenFX_log_2022-10-11T233456.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790121/CitizenFX_log_2022-10-11T233456.log)
[CitizenFX_log_2022-10-11T233911.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9790122/CitizenFX_log_2022-10-11T233911.log)

**Comment by xaroht** [comment]
https://i.imgur.com/BlSJQAT.png
https://i.imgur.com/aZYcKU8.png
https://i.imgur.com/kFlKW1y.jpeg

**Comment by xXJamieXx** [comment]
Is this still an issue?

**Comment by Drunkle716** [comment]
Based on what I've seen, truck robberies are working again.
