### ISSUE TITLE
[BUG] Fishing Chest allows non-fish items and duplicates when storing non-fish items

### ISSUE THREAD

**Issue by Terrylaughlin35** [ParadoxGamingRP/bugs-and-suggestions#816]
### Your Discord Name

Terry Laughlin#3143

### A clear and concise description of what the bug is

I stored some random things from my pockets into a fishing chest. I went to sleep with it last night and when i came back today everything that was in the fishing chest duplicated to my inventory.

### Steps to Reproduce the Bug

1. store random stuff into Fishing chest
2. sleep unsure for how long or if it has to be after a tsunami
3. have duplicates

### Expected Behavior

to not have duplicate items in inventory

### Screenshots/Videos

https://i.imgur.com/tlDZJn6.png

### Extra Notes (Optional)

I would love to be able to keep storing random items in the chest because it is very useful! :)

### Log File

[fishing chest duplicates.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9691059/fishing.chest.duplicates.txt)

**Comment by xXJamieXx** [comment]
Should not be able to store anything other than fish within the chest.
