### ISSUE TITLE
[BUG] Cop Sirens are Not Working Properly 

### ISSUE THREAD

**Issue by ColKing** [ParadoxGamingRP/bugs-and-suggestions#818]
### Your Discord Name

Colt#2757

### A clear and concise description of what the bug is

When using the cop cars and you press E to unlock the locks to the gate it uses the sirens. We do not have the option of either go lights or sirens right now when press E it does both.  

### Steps to Reproduce the Bug

1. Press Q for Lights 
2. Press Left ALT for Sirens 
3. Press E for horn and locks 

### Expected Behavior

The expected behavior is to press Q for lights and Left ALT for sirens. At this moment we can not cycle and can only press E for both.

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/DeMdZwpakEJtN/d1337OvnKsua?invite=cr-MSxIUTksNjY1NDAzMDcs

**Comment by xXJamieXx** [comment]
Should be fixed.
