### ISSUE TITLE
[BUG] Name can't be found in MDT

### ISSUE THREAD

**Issue by TwentyManager20** [ParadoxGamingRP/bugs-and-suggestions#820]
### Your Discord Name

blackout #2761

### A clear and concise description of what the bug is

so I was trying to get my gun license so I approached a cop who tried to help me get it when I gave him my ID he couldn't find me in the the system he said to make a report in government(meaning discord) and  when I did he texted me through discord on my ticket saying their is a bug and the devs need to look into it

### Steps to Reproduce the Bug

> I have no clue how it started

### Expected Behavior

I don't know what happened

### Screenshots/Videos

I don't have any 

### Extra Notes (Optional)

if you look at my ticket you can se which officer I was talking to.

### Log File

I can't find but it was 9: 30 pm and Sunday real life time 3:26 in game

**Comment by xXJamieXx** [comment]
Unable to reproduce and left the server.
