### ISSUE TITLE
[BUG] Pillbox door not locking

### ISSUE THREAD

**Issue by Nalyd24** [ParadoxGamingRP/bugs-and-suggestions#823]
### Your Discord Name

Nalyd#7153

### A clear and concise description of what the bug is

Locks are not working as you can still walk through the doors. happening to other people as well. 

### Steps to Reproduce the Bug

1. walk through the locked door.
2. be on the other side of the locked door

### Expected Behavior

not be able to walk through the locked door

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/DqnOPLQowD2xX/d1337mwapLI3?invite=cr-MSxGYW4sNjExOTUyNzUs

**Comment by JnKTechstuff** [comment]
@ithegreatgatsby can you look into this and see if its a door settings issue? Looks like the lock isn't engaged as the door is not registered as closed enough

**Comment by ithegreatgatsby** [comment]
Made some changes we will see if it fixes issues

**Comment by ithegreatgatsby** [comment]
Closing, Please reopen if its still a issue
