### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by KyleIvermee** [ParadoxGamingRP/bugs-and-suggestions#824]
### Your Discord Name

KyleIvermee#2412

### A clear and concise description of what the bug is

All in all im not sure whenever we are in the postal 500 range i experience frame drops then lots of headaches or sometimes i just freeze and crash it was closer to los santos customs

### Steps to Reproduce the Bug

1. Drive around 500 range closer to Los santos Customs
2. When you start to experience Frame drops, lag, stuttering stay around that area
3. Then you may Crash

### Expected Behavior

Headaches, Lag, Frame Drops, Stuttering

### Screenshots/Videos

N/A

### Log File

[Window Title]
Error GTA5_b2699.exe!sub_140532844 (0xd5)

[Main Instruction]
GTA5_b2699.exe!sub_140532844 (0xd5)

[Content]
An error at GTA5_b2699.exe!sub_140532844 (0xd5) caused FiveM to stop working. A crash report is being uploaded to the FiveM developers.

Legacy crash hash: music-december-michigan
Stack trace:
  GTA5_b2699.exe!sub_140532844 (0xd5)
  GTA5_b2699.exe!sub_14162DE7C (0x9c)
  GTA5_b2699.exe!sub_14162DD78 (0xbd)
  GTA5_b2699.exe!sub_141608A70 (0x6c)
  GTA5_b2699.exe!sub_141609428 (0x25)
  GTA5_b2699.exe!sub_141611F10 (0x159)
  GTA5_b2699.exe!StartAddress (0xfd)

[^] Hide details  [Save information] [Close]

[Expanded Information]
Crash signature: GTA5_b2699.exe+532919
Report ID: si-12f141805d684bbc9ad2e86f72f9cfc9
You can press Ctrl-C to copy this message and paste it elsewhere.

**Comment by JnKTechstuff** [comment]
Temp fixed and full fix comes with paintball update
