### ISSUE TITLE
[BUG] Polyzone overlap in Prison

### ISSUE THREAD

**Issue by PatrykX904** [ParadoxGamingRP/bugs-and-suggestions#830]
### Your Discord Name

Help Me Choose A Name#0175

### A clear and concise description of what the bug is

Whenever you try to do the clean bunk job for prison the pry open section overlaps the option to clean the bunk so therefor people need to abort job and go do the other jobs.

### Steps to Reproduce the Bug

1. Get a prison job
2. Go to bunk to clean
3. Pry open section overlaps it not being able to clean the bunk

### Expected Behavior

The expected behavior should be that people should be able to clean the bunk without the pry open bunk section overlapping it.

### Screenshots/Videos

![Bug](https://user-images.githubusercontent.com/81855046/194643967-7a94980b-f0fd-438a-b419-3b8cef2df25c.png)

**Comment by ithegreatgatsby** [comment]
this should be fixed now
