### ISSUE TITLE
[ENHANCEMENT] Clothing

### ISSUE THREAD

**Issue by Mac-ceo** [ParadoxGamingRP/bugs-and-suggestions#831]
**Your Discord Name**
mac_ceo#4908

**Describe the annoyance**
There are no Plain vests which look nice like the plain police vest we had for a few weeks what I recommend is some vest like that which are plain for CIVS or Crims

**To Reproduce**
N/A
**Requested behavior**
N/A

**Screenshots**
![20221008153715_1](https://user-images.githubusercontent.com/103427821/194713540-fdfdfe48-4f6f-4a91-be34-8812329b55d0.jpg)

 like this but plain
![vest palinnnnn](https://user-images.githubusercontent.com/103427821/194713504-99892c2d-0322-4aa1-a1e9-9517f7e77a9a.PNG)
in
**Additional context**
[Add any other context about the enhancement here]

**Comment by ithegreatgatsby** [comment]
No these are for Leo only and not civs there never should of been plain textures so that was fixed
