### ISSUE TITLE
[BUG] Tow repair not working correctly

### ISSUE THREAD

**Issue by RizzleMyNizzle** [ParadoxGamingRP/bugs-and-suggestions#835]
### Your Discord Name

RizzleMyNizzle#8454

### A clear and concise description of what the bug is

When you do a roadside repair using the tow vehicle menu, afterward if you hit anything it goes red immediately. 

### Steps to Reproduce the Bug

Wreck car till red engine and will not run.  Do a repair in tow vehicle menu and hit a road sign, it breaks engine.

### Expected Behavior

For the repair to stick and not have to call tow again for repair after one minute of already repairing it.

### Screenshots/Videos

https://user-images.githubusercontent.com/106287551/194973951-1526fc63-f5bd-4347-8b76-373ed606190f.MOV

**Comment by RizzleMyNizzle** [comment]
Just tested it and it’s still doing the same thing

**Comment by xXJamieXx** [comment]
Is this still an issue?

**Comment by xXJamieXx** [comment]
Closing stale ticket due to no response.
