### ISSUE TITLE
paintball teleporting

### ISSUE THREAD

**Issue by Terrylaughlin35** [ParadoxGamingRP/bugs-and-suggestions#836]
### Your Discord Name

Terry Laughlin#3143

### A clear and concise description of what the bug is

Go down while playing paintball then get carried out to go to the hospital. once through the gate you will fall through the world and wake up in Paleto.

### Steps to Reproduce the Bug

1. go down while playing paintball
2. have someone carry you outside of the gate 
3. fall through the world

### Expected Behavior

to be carried to a hospital and not go down from getting shot with paintballs.

### Screenshots/Videos

https://i.imgur.com/C9XIdN7.jpeg

### Log File

[fly from paintball to paleto.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9750498/fly.from.paintball.to.paleto.txt)

**Comment by xXJamieXx** [comment]
Fixed paintball gun doing damage which should reduce the frequency of going down while in the arena. All other methods of going down are preventable by the player so unless any other issues are found I will be considering this issue resolved for now.
