### ISSUE TITLE
[BUG] hunger nor thirst went down all day

### ISSUE THREAD

**Issue by Flora45** [ParadoxGamingRP/bugs-and-suggestions#837]
### Your Discord Name

Flora#8531

### A clear and concise description of what the bug is

I hopped on the server around 2:00pm, it is now 4:00am and my hunger nor thirst has gone down once. 

### Steps to Reproduce the Bug

1. Log into server
2. see no decrease of hunger or thirst 

### Expected Behavior

Hunger and thirst level should go down throughout gameplay. 

### Screenshots/Videos

None

**Comment by xXJamieXx** [comment]
Fixed.
