### ISSUE TITLE
[BUG] PD AR Range 

### ISSUE THREAD

**Issue by Petrovic247** [ParadoxGamingRP/bugs-and-suggestions#838]
### Your Discord Name

PretenderPatrol#5993

### A clear and concise description of what the bug is

PD AR's range is less than the AK47. Unsure on exact range that damage dips off.

### Steps to Reproduce the Bug

Got fucked on in gunfight
Went back to see if I was trash
2 different PD AR's hit for the same damage.

### Expected Behavior

Equal range is cool.

### Screenshots/Videos

https://www.twitch.tv/videos/1621837503

### Extra Notes (Optional)

Plz

**Comment by JnKTechstuff** [comment]
Fixed next restart
