### ISSUE TITLE
[BUG] Radio Scanner not saying "traffic heard" 

### ISSUE THREAD

**Issue by Flora45** [ParadoxGamingRP/bugs-and-suggestions#839]
### Your Discord Name

Flora#8531

### A clear and concise description of what the bug is

I have seen a couple of bugs about the trucks themselves. But through the duration of 3 days trying the radio scanner all you hear is a bit of static and that's it. I have used mine about 40 times and it's the same thing. Could be because bank trucks on hault but I wanted to make sure it wasn't another bug. 

### Steps to Reproduce the Bug

1. Use radio scanner
2. hear nothing but short static
3. No "Traffic heard" 

### Expected Behavior

1. Use radio scanner
2. Hear "Traffic heard" 

### Screenshots/Videos

https://user-images.githubusercontent.com/79613077/195513243-d8c59ae2-24b1-4ba2-a6cd-e54176924d74.mp4

### Log File

[CitizenFX_log_2022-10-13T003341.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9771191/CitizenFX_log_2022-10-13T003341.log)

**Comment by JnKTechstuff** [comment]
lol

not a bug
