### ISSUE TITLE
[BUG] Can't seem to take pics.

### ISSUE THREAD

**Issue by SpiceF0x** [ParadoxGamingRP/bugs-and-suggestions#840]
### Your Discord Name

spicedf0x#2127

### A clear and concise description of what the bug is

Try to take picture with phone and won't save for some reason, times out. Circle keeps going round and round.

### Steps to Reproduce the Bug

1. Pull out phone.
2. Click on camera app
3. Take desired pic
4. Little round thing just spins

### Expected Behavior

Pic saves to gallery properly

### Screenshots/Videos

![20221013204656_1](https://user-images.githubusercontent.com/96963965/195695419-951930e9-ec56-4349-a32d-76ef29d40620.jpg)

**Comment by xXJamieXx** [comment]
Is this still an issue?

**Comment by SpiceF0x** [comment]
Yeah, still same error in f8

**Comment by xXJamieXx** [comment]
Need more info because its working for myself and many others.

**Comment by SpiceF0x** [comment]
It's happening on both Sugar and Spice, so across all accounts. It's happening consistently. It happened after the imgur - discord change. The upload just fails so no pictures are taken.

**Comment by SpiceF0x** [comment]
https://streamable.com/s4toyl

this is as it happens, tho i don't think its of much more use than the info I've provided....

**Comment by xXJamieXx** [comment]
Is this happening to anyone else?
