### ISSUE TITLE
[BUG] House decorating issues

### ISSUE THREAD

**Issue by FayeBlackheart** [ParadoxGamingRP/bugs-and-suggestions#841]
### Your Discord Name

Faye Blackheart#7984

### A clear and concise description of what the bug is

Hi there, so I had submitted a ticket on Discord a while back about problems with decorating my house at 842, which has the Lupine Manor interior.    I am unable to delete some items that I set out.  Specifically, I was looking at different beds trying to choose one and now I can't delete them.  When I go to delete them, they show as being removed from the scene while I'm in decorate mode, but as soon as I close decorate mode, they reappear.  Now I have 3 beds in the master bedroom, one of them nearly blocked the doorway, and the other two are overlapping another.  I gave it a couple days, as recommended by the admins, but those items are still there and it has been about a week.  The second issue is there is an NPC spawning in that same master bedroom, shown in a floating/sitting position in the middle of one of the beds.  The NPC character is different each time we enter the house and the only way to get him out of the room is to go into decorate mode, try to delete a bed (unsuccessfully), and close decorate mode.  At that point, he vanishes.  Admins asked me to submit these bugs here. 

### Steps to Reproduce the Bug

1.  Go into the Lupine Manor house at 842 in Paradox (not sure if others have this problem, but it can certainly be reproduced at 842) master bedroom (the one with the walk-in closet);
2.  Place out several beds (or just observe the 3 beds already out at 842 in Paradox);
3.  Delete the beds;
4.  Close decorate mode;
5.  The beds will reappear immediately;
6.  Relogging does not resolve the issue, and my roommates see the same thing;
7.  Not sure how to "reproduce" the spawning of the NPC in that same room, but he is there everyday.

### Expected Behavior

I should be able to go into decorate mode, my objects, and remove beds and they disappear from the home.  I also should not see an NPC floating/sitting in the bedroom every day.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/115768950/195763343-048ccff3-3470-489d-85d8-29dbf8ca87ad.png)

### Log File

I followed those instructions, but I don't have a log file located where the instructions say I should.  If you really need this, I'll need help finding it, as Google didn't help.

**Comment by ithegreatgatsby** [comment]
#861 #886 #1289 all bug reports have to do with housing items decorating in general. This will be the main report that gets updated when the new housing script gets released
