### ISSUE TITLE
[ENHANCEMENT] ZL1 Badges

### ISSUE THREAD

**Issue by Zugzies** [ParadoxGamingRP/bugs-and-suggestions#844]
### Your Discord Name

Zugzies#8238

### A clear and concise description of what the bug is

I own a Zl1 in the paradox 3,0 server, the front badge of the car is black with a chrome trim, but the rear badge is a normal Chevy badge. I'm not a car enthusiast but it was weird to me seeing this so i looked into it. Almost every zL1 I saw on the internet had 2 black and chrome Chevy badges. I'm not sure if this is something you guys know or have looked into but I filled out a support ticket and they sent me here.

### Steps to Reproduce the Bug

.

### Expected Behavior

.

### Screenshots/Videos

.

**Comment by ithegreatgatsby** [comment]
Not really something worth fixing. Will look into other  camaro  options for the server though
