### ISSUE TITLE
[BUG] very difficult to get on bicycle 

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#845]
### Your Discord Name

Ssara#7821 

### A clear and concise description of what the bug is

When trying to get on your bicycle it takes a while before doing so. Doesn't matter if its locked, not locked, with L or bicycle lock. 

### Steps to Reproduce the Bug

Buy a bike
Get off the bike or park it
Try to get on bike again. 

### Expected Behavior

Be able to ride my new super bike to work, but I cannot get on it. 

### Screenshots/Videos

N/a atm

**Comment by xXJamieXx** [comment]
@SaraLef is this still an issue?
