### ISSUE TITLE
[BUG] Ammunation not giving correct items

### ISSUE THREAD

**Issue by Gasoaa** [ParadoxGamingRP/bugs-and-suggestions#847]
### Your Discord Name

Gasoa#6137

### A clear and concise description of what the bug is

I want to buy a hunting rifle. I go to ammunation and go get a rifle and rifle ammo. Instead, I get SNS pistols and a sig as a replacement for those items I want to buy. It didn't charge me the same amount as the rifle and ammo. Charged me the same amount as 5 SNS and 1 sig

### Steps to Reproduce the Bug

1. Go to ammunation 
2. Buy a hunting rifle and hunting rifle ammo
3. Get a Sig instead hunting rifle, get an sns instead of rifle ammo

### Expected Behavior

Get a hunting rifle and hunting rifle ammo and not get 5 SNS and 1 sig pistol 

### Screenshots/Videos

https://user-images.githubusercontent.com/115909266/196015857-d170e527-0489-4556-81e3-8ff961af7783.mp4

**Comment by xXJamieXx** [comment]
Unable to reproduce this issue and will therefore be closing it.
Closing stale issue due to no response.
