### ISSUE TITLE
[BUG] Engine damaging incorrectly

### ISSUE THREAD

**Issue by Flora45** [ParadoxGamingRP/bugs-and-suggestions#850]
### Your Discord Name

Flora#8531

### A clear and concise description of what the bug is

After the last restart (10/17/22 scheduled restart at 13:25) I got back on the server and my car was not accelerating correctly and topping out at 100mph. When usually the car accelerates quick and ends up at around 120+mph. Also I will get in it and it will have a yellow light with no damage done to the vehicle. 

### Steps to Reproduce the Bug

1. get in car
2. observe slower than usual speeds

### Expected Behavior

1.Get in car
2. Observe usual speeds

### Screenshots/Videos

https://user-images.githubusercontent.com/79613077/196249545-40d78fc8-550a-4157-918e-2bf676c48f80.mp4

### Log File

[CitizenFX_log_2022-10-17T172638.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9803305/CitizenFX_log_2022-10-17T172638.log)

**Comment by xXJamieXx** [comment]
Is this still an issue?

**Comment by xXJamieXx** [comment]
Consolidating into #851
