### ISSUE TITLE
[BUG] Tattoos transfer over to other characters again

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#852]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

Olivia's tattoos ended up on Indica when I logged in on Olivia first and did a F8 logout and then in on Indica.

### Steps to Reproduce the Bug

Have tattoos on character 1
Log in to character 1
Do F8 logout
Log in to character 2 without tattos
See both have the same tattoos

### Expected Behavior

For My other character not to have any tattoos

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98127638/196424510-895398e6-d591-4426-be7a-d7fc5f17c5a1.png)
This is what my second character has that I've never put on her.

**Comment by xXJamieXx** [comment]
Is this still an issue?

**Comment by xXJamieXx** [comment]
Closing stale issue due to no response.
