### ISSUE TITLE
[ENHANCEMENT] Report button on ADVERTISEMENT APP 

### ISSUE THREAD

**Issue by RoguIsAwesome** [ParadoxGamingRP/bugs-and-suggestions#853]
Rogue#5265

So its not a really big annoyance but its just a bit triggering , so when i want to make a ad on the ad app , I try to click on the create new post button but the report button is just in the way sometimes when there is posts on the app and i accidently hit it , Which then causes me to get warned ig lmao , This kinda happens due to my high dpi since its my own personal preference. 

[Steps to reproduce the annoyance]
1. Go on the App
2. Accidently miss your click and hit report
3.  Hold the L by getting a warning

I wish the dev team could try to make it so like its the twitter report thing where you have to click on the drop down menu to report it other than just a report button that sends a report straightaway . They could also add " Are you sure you want to report this post? " Question when u accidently hit it.

**Comment by xXJamieXx** [comment]
Already submitted a request for the phone devs to add a confirmation to this. Waiting for their response.
