### ISSUE TITLE
[BUG] Spawning outside prison when sent

### ISSUE THREAD

**Issue by kevstax** [ParadoxGamingRP/bugs-and-suggestions#854]
### Your Discord Name

KevStax#7186

### A clear and concise description of what the bug is

When I got sent to jail I get put on the wrong side of the jail around where car's drive in. It says I need tools to get into the jail but all I want to do is access the checkout area.

### Steps to Reproduce the Bug

1. Get Sent to jail

### Expected Behavior

Free access to the interior of the jail to access the kitchen and all chores.

### Screenshots/Videos

https://i.imgur.com/u6CCSHQ.jpeg

**Comment by ithegreatgatsby** [comment]
Not sure why you spawned their sense its not even a location to set to be spawned at.  And we have not had any other reports on this

**Comment by xXJamieXx** [comment]
Added in a safety check to maybe prevent this. However this is almost certainly caused by slow connection/old PC hardware and isn't something we will spend more time fixing.
