### ISSUE TITLE
[ENHANCEMENT] Be able to smoke the weed you grow

### ISSUE THREAD

**Issue by PatrykX904** [ParadoxGamingRP/bugs-and-suggestions#856]
**Your Discord Name**
Help Me Choose A Name#0175

**Describe the annoyance**
[A clear and concise description of what the the annoying mechanic that should be resolved is]

To be able to smoke your own weed you grow

**To Reproduce**
[Steps to reproduce the annoyance]
1. Grow weed
2. Have an option to make it into a joint to make it smoke-able

**Requested behavior**
[A clear and concise description of what you want to happen]
Have the option to either put the weed into a baggie (to sell to locals) or be able to make it into a joint and smoke it

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by Darahz** [comment]
Not gonna be added. Thank you for the idea tho
