### ISSUE TITLE
[BUG] Boosting drop off location in stab city

### ISSUE THREAD

**Issue by Flora45** [ParadoxGamingRP/bugs-and-suggestions#859]
### Your Discord Name

Flora#8531

### A clear and concise description of what the bug is

I was boosting a car when I found the drop off location to be inside of stab city. Which is gated and cannot be entered upon by non-owners of the area. I tried going behind it to get close to the drop off location but no luck. 

### Steps to Reproduce the Bug

1. boost a car
2. see the drop off location is in stab city

### Expected Behavior

1. boost car
2. find the location somewhere that is able to be entered 

### Screenshots/Videos

![FiveM® by Cfx re -  Original  Paradox Gaming RP _ 3+ years _ discord gg_paradoxgaming 23_10_2022 07_29_26](https://user-images.githubusercontent.com/79613077/197390355-2ca11235-15ed-4f57-81c1-a51b5912dd0f.png)
![FiveM® by Cfx re -  Original  Paradox Gaming RP _ 3+ years _ discord gg_paradoxgaming 23_10_2022 07_39_37](https://user-images.githubusercontent.com/79613077/197390363-bbe36aed-a3c6-4493-8789-a8f06f7aced1.png)

### Extra Notes (Optional)

I think it would be cool if the respective gang/owners of the area would need a cut to enter, but that is up to their discretion. 

### Log File

[CitizenFX_log_2022-10-23T100348.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9846457/CitizenFX_log_2022-10-23T100348.log)

**Comment by JnKTechstuff** [comment]
lol

**Comment by JnKTechstuff** [comment]
Should be fixed
