### ISSUE TITLE
[BUG] Multiple People's House Furniture Showing In My Objects List and Unable To Delete

### ISSUE THREAD

**Issue by MagicMyers** [ParadoxGamingRP/bugs-and-suggestions#861]
### Your Discord Name

MrSpooksAhoy #5937

### A clear and concise description of what the bug is

When going into Decorate Mode and trying to move/delete 1 of my own items from the list, I have lots of items listed belonging to other people who I have visited, 1 of which gave me keys, the other did not as far as I'm aware. None of the properties are near each other, so that wouldn't be the cause I don't think. I could not remove their items from my list and it's made it nearly impossible to amend my own items. I have placed 2 lights, 2 tables and bed, rug and tv, so only 7 items should be in my list, but as you will see in the clip, there are 20 plus, maybe more listed that aren't mine. 

### Steps to Reproduce the Bug

Enter Decorate Mode - My Objects List

### Expected Behavior

Hopefully, you'll see items from other properties. 

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/FYeUmi_Rfrvje/d1337W5hY0HD?invite=cr-MSxvYm0sMTA4MzgyMjMxLA

### Log File

[CitizenFX_log_2022-10-25T005552.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9856647/CitizenFX_log_2022-10-25T005552.log)
[CitizenFX_log_2022-10-25T005618.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9856648/CitizenFX_log_2022-10-25T005618.log)

**Comment by ithegreatgatsby** [comment]
refer to #841 for all future updates with anything housing/decorating
