### ISSUE TITLE
[BUG] Pool table in Open Road not working

### ISSUE THREAD

**Issue by mjb328** [ParadoxGamingRP/bugs-and-suggestions#864]
### Your Discord Name

MJB328#5303

### A clear and concise description of what the bug is

The pool table in Open Road occasionally bugs out and refuses to set up a any games of pool. It might be caused by starting a game of pool without setting up first.

### Steps to Reproduce the Bug

Go to open Road after the most recent reset and set up a game of pool

If it does set up, play till you clear the table.

Once the table it cleared select "play turn" without setting up table for the next game.

Afterward try and set up and see it it bugs out or not.

### Expected Behavior

Be able to play pool 

### Screenshots/Videos

https://streamable.com/dvgsfo

### Extra Notes (Optional)

Idk how you'd structure the code but if doing "Play Turn" before anything is set up is causing the issue maybe change it to where "play turn" doesn't come up till a game is actually set up. That way people can't accidentally glitch it when the try to setup.

### Log File

   1890484] [b2699_GTAProce]             MainThrd/ 
[   1890484] [b2699_GTAProce]             MainThrd/ 
[   1890484] [b2699_GTAProce]             MainThrd/ 
[   1897969] [b2699_GTAProce]             MainThrd/ 
[   1897969] [b2699_GTAProce]             MainThrd/ 
[   1897969] [b2699_GTAProce]             MainThrd/ 
[   1945437] [b2699_GTAProce]             MainThrd/ 
[   1945437] [b2699_GTAProce]             MainThrd/ 
[   1945437] [b2699_GTAProce]             MainThrd/ 
[   2093562] [b2699_GTAProce]             MainThrd/ 
[   2093562] [b2699_GTAProce]             MainThrd/ 
[   2093562] [b2699_GTAProce]             MainThrd/ 
[   2119625] [b2699_GTAProce]             MainThrd/ 
[   2133344] [b2699_GTAProce]        CrBrowserMain/ Uncaught (in promise) TypeError: Failed to fetch (@npwd/resources/html/index.html#/marketplace:0)
[   2133344] [b2699_GTAProce]        CrBrowserMain/ Uncaught (in promise) TypeError: Failed to fetch (@npwd/resources/html/index.html#/marketplace:0)
[   2133344] [b2699_GTAProce]        CrBrowserMain/ Uncaught (in promise) TypeError: Failed to fetch (@npwd/resources/html/index.html#/marketplace:0)
[   2135594] [b2699_GTAProce]             MainThrd/ GetNetworkObject: no object by ID 1192
[   2140031] [b2699_GTAProce]             MainThrd/ 
[   2140031] [b2699_GTAProce]             MainThrd/ 
[   2140031] [b2699_GTAProce]             MainThrd/ 
[   2160031] [b2699_GTAProce]             MainThrd/ 
[   2160031] [b2699_GTAProce]             MainThrd/ 
[   2160031] [b2699_GTAProce]             MainThrd/ 
[   2170125] [b2699_GTAProce]             MainThrd/ 
[   2252375] [b2699_GTAProce]             MainThrd/ seatbelt check
[   2288125] [b2699_GTAProce]             MainThrd/ ^2[DEBUG]: ^3(prdx_farming) ^2Trying to remove plant object 7287656
[   2294625] [b2699_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @rcore_pool/client/editable_control.lua:80: attempt to index a nil value (field '?')^7
[   2294625] [b2699_GTAProce]             MainThrd/ ^3> handler^7 (^5@rcore_pool/client/editable_control.lua^7:80)
[   2295062] [b2699_GTAProce]             MainThrd/ 
[   2295062] [b2699_GTAProce]             MainThrd/ 
[   2295062] [b2699_GTAProce]             MainThrd/ 
[   2296703] [b2699_GTAProce]             MainThrd/ 
[   2296703] [b2699_GTAProce]             MainThrd/ 
[   2296703] [b2699_GTAProce]             MainThrd/ 
[   2300062] [b2699_GTAProce]             MainThrd/ 
[   2300062] [b2699_GTAProce]             MainThrd/ 
[   2300062] [b2699_GTAProce]             MainThrd/ 
[   2301578] [b2699_GTAProce]             MainThrd/ 
[   2301578] [b2699_GTAProce]             MainThrd/ 
[   2301578] [b2699_GTAProce]             MainThrd/ 
[   2302125] [b2699_GTAProce]             MainThrd/ ^2[DEBUG]: ^3(prdx_farming) ^2Trying to remove plant object 4362946
[   2321390] [b2699_GTAProce]             MainThrd/ ^2[DEBUG]: ^3(prdx_farming) ^2Trying to remove plant object 6884426
[   2419281] [b2699_GTAProce]             MainThrd/ GetNetworkObject: no object by ID 1532
[   2426422] [b2699_GTAProce]             MainThrd/ 
[   2426422] [b2699_GTAProce]             MainThrd/ 
[   2426422] [b2699_GTAProce]             MainThrd/ 
[   2427640] [b2699_GTAProce]             MainThrd/ 
[   2427640] [b2699_GTAProce]             MainThrd/ 
[   2427640] [b2699_GTAProce]             MainThrd/ 
[   2431890] [b2699_GTAProce]             MainThrd/ 
[   2431890] [b2699_GTAProce]             MainThrd/ 
[   2431890] [b2699_GTAProce]             MainThrd/ 
[   2434250] [b2699_GTAProce]             MainThrd/ 
[   2434250] [b2699_GTAProce]             MainThrd/ 
[   2434250] [b2699_GTAProce]             MainThrd/ 
[   2435500] [b2699_GTAProce]             MainThrd/ 
[   2435500] [b2699_GTAProce]             MainThrd/ 
[   2435515] [b2699_GTAProce]             MainThrd/ 
[   2446781] [b2699_GTAProce]             MainThrd/ 
[   2446797] [b2699_GTAProce]             MainThrd/ 
[   2446797] [b2699_GTAProce]             MainThrd/ 
[   2477750] [b2699_GTAProce]             MainThrd/ 
[   2497719] [b2699_GTAProce]             MainThrd/ 
[   2497719] [b2699_GTAProce]             MainThrd/ 
[   2497719] [b2699_GTAProce]             MainThrd/ 
[   2499625] [b2699_GTAProce]             MainThrd/ 
[   2499625] [b2699_GTAProce]             MainThrd/ 
[   2499625] [b2699_GTAProce]             MainThrd/ 
[   2500344] [b2699_GTAProce]             MainThrd/ 
[   2500344] [b2699_GTAProce]             MainThrd/ 
[   2500344] [b2699_GTAProce]             MainThrd/ 
[   2501640] [b2699_GTAProce]             MainThrd/ 
[   2501640] [b2699_GTAProce]             MainThrd/ 
[   2501640] [b2699_GTAProce]             MainThrd/ 
[   2519984] [b2699_GTAProce]             MainThrd/ 
[   2519984] [b2699_GTAProce]             MainThrd/ 
[   2519984] [b2699_GTAProce]             MainThrd/ 
[   2520640] [b2699_GTAProce]             MainThrd/ 
[   2520640] [b2699_GTAProce]             MainThrd/ 
[   2520640] [b2699_GTAProce]             MainThrd/ 
[   2521969] [b2699_GTAProce]             MainThrd/ 
[   2521969] [b2699_GTAProce]             MainThrd/ 
[   2521969] [b2699_GTAProce]             MainThrd/ 
[   2531578] [b2699_GTAProce]             MainThrd/ ^2[DEBUG]: ^3(prdx_farming) ^2Trying to remove plant object 7566031
[   2548344] [b2699_GTAProce]             MainThrd/ ^2[DEBUG]: ^3(prdx_farming) ^2Trying to remove plant object 1748460
[   2563609] [b2699_GTAProce]             MainThrd/ ^2[DEBUG]: ^3(prdx_farming) ^2Trying to remove plant object 8279931
[   2567078] [b2699_GTAProce]             MainThrd/ 
[   2581390] [b2699_GTAProce]             MainThrd/ WEATHER UPDATE:	CLEAR
[   2584875] [b2699_GTAProce]             MainThrd/ ^2[DEBUG]: ^3(prdx_farming) ^2Trying to remove plant object 9098852
[   2590578] [b2699_GTAProce]             MainThrd/ 
[   2590578] [b2699_GTAProce]             MainThrd/ 
[   2590578] [b2699_GTAProce]             MainThrd/ 
[   2603156] [b2699_GTAProce]             MainThrd/ ^2[DEBUG]: ^3(prdx_farming) ^2Trying to remove plant object 5767974
[   2606562] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "defaultHouseItems". This is a FATAL ERROR in
[   2606562] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2606562] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2606562] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "houseItem". This is a FATAL ERROR in
[   2606562] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2606562] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2606562] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "houseItem__withFallback". This is a FATAL ERROR in
[   2606562] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2606562] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2606562] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "defaultMyKeys". This is a FATAL ERROR in
[   2606562] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2606562] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2606562] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "myKeys". This is a FATAL ERROR in
[   2606562] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2606562] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2606562] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "myKeys__withFallback". This is a FATAL ERROR in
[   2606562] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2606562] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2606562] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "selectedHouse". This is a FATAL ERROR in
[   2606562] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2606562] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2606562] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "houseListModal". This is a FATAL ERROR in
[   2606562] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2606562] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2606562] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "modalType". This is a FATAL ERROR in
[   2606562] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2606562] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2606578] [b2699_GTAProce]        CrBrowserMain/ Successfully loaded external app "npwd_qb_housing" (@npwd/resources/html/6019.js:1)
[   2606578] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "defaultMailItems". This is a FATAL ERROR in
[   2606578] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2606578] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2606578] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "mailItem". This is a FATAL ERROR in
[   2606578] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2606578] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2606578] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "mailItem__withFallback". This is a FATAL ERROR in
[   2606578] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2606578] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2606578] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "selectedMail". This is a FATAL ERROR in
[   2606578] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2606578] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2606578] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "mailModalVisible". This is a FATAL ERROR in
[   2606578] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2606578] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2606578] [b2699_GTAProce]        CrBrowserMain/ Successfully loaded external app "npwd_qb_mail" (@npwd/resources/html/6019.js:1)
[   2606594] [b2699_GTAProce]        CrBrowserMain/ Successfully loaded external app "npwd_qb_garage" (@npwd/resources/html/6019.js:1)
[   2606609] [b2699_GTAProce]        CrBrowserMain/ Successfully loaded external app "npwd_qb_services" (@npwd/resources/html/6019.js:1)
[   2622312] [b2699_GTAProce]             MainThrd/ ^2[DEBUG]: ^3(prdx_farming) ^2Trying to remove plant object 2987517
[   2646859] [b2699_GTAProce]             MainThrd/ 
[   2648906] [b2699_GTAProce]             MainThrd/ 
[   2648906] [b2699_GTAProce]             MainThrd/ 
[   2648906] [b2699_GTAProce]             MainThrd/ 
[   2650562] [b2699_GTAProce]             MainThrd/ 
[   2650562] [b2699_GTAProce]             MainThrd/ 
[   2650562] [b2699_GTAProce]             MainThrd/ 
[   2651172] [b2699_GTAProce]             MainThrd/ ^2[DEBUG]: ^3(prdx_farming) ^2Trying to remove plant object 8632415
[   2678437] [b2699_GTAProce]             MainThrd/ ^2[DEBUG]: ^3(prdx_farming) ^2Trying to remove plant object 2810828
[   2738578] [b2699_GTAProce]             MainThrd/ ^2[DEBUG]: ^3(prdx_farming) ^2Trying to remove plant object 4113474
[   2759469] [b2699_GTAProce]             MainThrd/ ^2[DEBUG]: ^3(prdx_farming) ^2Trying to remove plant object 2273788
[   2760969] [b2699_GTAProce]             MainThrd/ 
[   2760969] [b2699_GTAProce]             MainThrd/ 
[   2760969] [b2699_GTAProce]             MainThrd/ 
[   2762031] [b2699_GTAProce]             MainThrd/ 
[   2762031] [b2699_GTAProce]             MainThrd/ 
[   2762031] [b2699_GTAProce]             MainThrd/ 
[   2763703] [b2699_GTAProce]             MainThrd/ 
[   2763703] [b2699_GTAProce]             MainThrd/ 
[   2763703] [b2699_GTAProce]             MainThrd/ 
[   2782234] [b2699_GTAProce]             MainThrd/ ^2[DEBUG]: ^3(prdx_farming) ^2Trying to remove plant object 1605710
[   2844765] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "defaultHouseItems". This is a FATAL ERROR in
[   2844765] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2844765] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2844765] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "houseItem". This is a FATAL ERROR in
[   2844765] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2844765] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2844765] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "houseItem__withFallback". This is a FATAL ERROR in
[   2844781] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2844781] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2844781] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "defaultMyKeys". This is a FATAL ERROR in
[   2844781] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2844781] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2844781] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "myKeys". This is a FATAL ERROR in
[   2844781] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2844781] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2844781] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "myKeys__withFallback". This is a FATAL ERROR in
[   2844781] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2844781] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2844781] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "selectedHouse". This is a FATAL ERROR in
[   2844781] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2844781] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2844781] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "houseListModal". This is a FATAL ERROR in
[   2844781] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2844781] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2844781] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "modalType". This is a FATAL ERROR in
[   2844781] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2844781] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2844781] [b2699_GTAProce]        CrBrowserMain/ Successfully loaded external app "npwd_qb_housing" (@npwd/resources/html/6019.js:1)
[   2844797] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "defaultMailItems". This is a FATAL ERROR in
[   2844797] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2844797] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2844797] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "mailItem". This is a FATAL ERROR in
[   2844797] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2844797] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2844797] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "mailItem__withFallback". This is a FATAL ERROR in
[   2844797] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2844797] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2844797] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "selectedMail". This is a FATAL ERROR in
[   2844797] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2844797] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2844797] [b2699_GTAProce]        CrBrowserMain/ Duplicate atom key "mailModalVisible". This is a FATAL ERROR in
[   2844797] [b2699_GTAProce]        CrBrowserMain/       production. But it is safe to ignore this warning if it occurred because of
[   2844797] [b2699_GTAProce]        CrBrowserMain/       hot module replacement. (@npwd_qb_housing/web/dist/804.js:1)
[   2844797] [b2699_GTAProce]        CrBrowserMain/ Successfully loaded external app "npwd_qb_mail" (@npwd/resources/html/6019.js:1)
[   2844812] [b2699_GTAProce]        CrBrowserMain/ Successfully loaded external app "npwd_qb_services" (@npwd/resources/html/6019.js:1)
[   2844828] [b2699_GTAProce]        CrBrowserMain/ Successfully loaded external app "npwd_qb_garage" (@npwd/resources/html/6019.js:1)
[   2854859] [b2699_GTAProce]             MainThrd/ ^2[DEBUG]: ^3(prdx_farming) ^2Trying to remove plant object 6606934
[   2871562] [b2699_GTAProce]             MainThrd/ 
[   2871562] [b2699_GTAProce]             MainThrd/ 
[   2871562] [b2699_GTAProce]             MainThrd/ 
[   2875640] [b2699_GTAProce]             MainThrd/ GetNetworkObject: no object by ID 0
[   2875640] [b2699_GTAProce]             MainThrd/ GetNetworkObject: no object by ID 0
[   2875640] [b2699_GTAProce]             MainThrd/ GetNetworkObject: no object by ID 0
[   2875640] [b2699_GTAProce]             MainThrd/ GetNetworkObject: no object by ID 0
[   2890437] [b2699_GTAProce]             MainThrd/ ^2[DEBUG]: ^3(prdx_farming) ^2Trying to remove plant object 2638299
[   2921734] [b2699_GTAProce]             MainThrd/ ^2[DEBUG]: ^3(prdx_farming) ^2Trying to remove plant object 9251873
[   2957453] [b2699_GTAProce]             MainThrd/ 
[   2957453] [b2699_GTAProce]             MainThrd/ 
[   2957453] [b2699_GTAProce]             MainThrd/ 
[   2968031] [b2699_GTAProce]             MainThrd/ 
[   2968031] [b2699_GTAProce]             MainThrd/ 
[   2968031] [b2699_GTAProce]             MainThrd/ 
[   2971906] [b2699_GTAProce]             MainThrd/ ^2[DEBUG]: ^3(prdx_farming) ^2Trying to remove plant object 4142159
[   3008719] [b2699_GTAProce]             MainThrd/ 
[   3008719] [b2699_GTAProce]             MainThrd/ 
[   3008719] [b2699_GTAProce]             MainThrd/ 
[   3008890] [b2699_GTAProce]             MainThrd/ ^2[DEBUG]: ^3(prdx_farming) ^2Trying to remove plant object 6764050
[   3010344] [b2699_GTAProce]             MainThrd/ 
[   3010344] [b2699_GTAProce]             MainThrd/ 
[   3010344] [b2699_GTAProce]             MainThrd/ 
[   3029390] [b2699_GTAProce]             MainThrd/ ^2[DEBUG]: ^3(prdx_farming) ^2Trying to remove plant object 9535443
[   3134328] [b2699_GTAProce]        CrBrowserMain/ Uncaught (in promise) TypeError: Failed to fetch (@npwd/resources/html/index.html#/calculator:0)
[   3134328] [b2699_GTAProce]        CrBrowserMain/ Uncaught (in promise) TypeError: Failed to fetch (@npwd/resources/html/index.html#/calculator:0)
[   3161531] [b2699_GTAProce]             MainThrd/ 
[   3161531] [b2699_GTAProce]             MainThrd/ 
[   3161531] [b2699_GTAProce]             MainThrd/ 
[   3170734] [b2699_GTAProce]             MainThrd/ 
[   3170734] [b2699_GTAProce]             MainThrd/ 
[   3170734] [b2699_GTAProce]             MainThrd/ 
[   3180547] [b2699_GTAProce]             MainThrd/ 
[   3180547] [b2699_GTAProce]             MainThrd/ 
[   3180547] [b2699_GTAProce]             MainThrd/ 
[   3300172] [b2699_GTAProce]             MainThrd/ ^2[DEBUG]: ^3(prdx_farming) ^2Trying to remove plant object 8836237
[   3323031] [b2699_GTAProce]             MainThrd/ ^2[DEBUG]: ^3(prdx_farming) ^2Trying to remove plant object 1735177
[   3341625] [b2699_GTAProce]             MainThrd/ ^2[DEBUG]: ^3(prdx_farming) ^2Trying to remove plant object 2002307
[   3364015] [b2699_GTAProce]             MainThrd/ ^2[DEBUG]: ^3(prdx_farming) ^2Trying to remove plant object 1840903
[   3385281] [b2699_GTAProce]             MainThrd/ ^2[DEBUG]: ^3(prdx_farming) ^2Trying to remove plant object 7502770
[   3402859] [b2699_GTAProce]             MainThrd/ 
[   3402859] [b2699_GTAProce]             MainThrd/ 
[   3402859] [b2699_GTAProce]             MainThrd/ 
[   3403500] [b2699_GTAProce]             MainThrd/ 
[   3403500] [b2699_GTAProce]             MainThrd/ 
[   3403500] [b2699_GTAProce]             MainThrd/ 
[   3403703] [b2699_GTAProce]             MainThrd/ ^2[DEBUG]: ^3(prdx_farming) ^2Trying to remove plant object 2742998
[   3404906] [b2699_GTAProce]             MainThrd/ 
[   3404906] [b2699_GTAProce]             MainThrd/ 
[   3404906] [b2699_GTAProce]             MainThrd/ 
[   3405515] [b2699_GTAProce]             MainThrd/ 
[   3405515] [b2699_GTAProce]             MainThrd/ 
[   3405515] [b2699_GTAProce]             MainThrd/ 
[   3406875] [b2699_GTAProce]             MainThrd/ 
[   3406875] [b2699_GTAProce]             MainThrd/ 
[   3406875] [b2699_GTAProce]             MainThrd/ 
[   3408187] [b2699_GTAProce]             MainThrd/ 
[   3408187] [b2699_GTAProce]             MainThrd/ 
[   3408187] [b2699_GTAProce]             MainThrd/ 
[   3409734] [b2699_GTAProce]             MainThrd/ 
[   3409734] [b2699_GTAProce]             MainThrd/ 
[   3409734] [b2699_GTAProce]             MainThrd/ 
[   3411172] [b2699_GTAProce]             MainThrd/ 
[   3411172] [b2699_GTAProce]             MainThrd/ 
[   3411172] [b2699_GTAProce]             MainThrd/ 
[   3415531] [b2699_GTAProce]             MainThrd/ 
[   3415531] [b2699_GTAProce]             MainThrd/ 
[   3415531] [b2699_GTAProce]             MainThrd/ 
[   3421328] [b2699_GTAProce]             MainThrd/ ^2[DEBUG]: ^3(prdx_farming) ^2Trying to remove plant object 1700546
[   3422219] [b2699_GTAProce]             MainThrd/ 
[   3422219] [b2699_GTAProce]             MainThrd/ 
[   3422219] [b2699_GTAProce]             MainThrd/ 
[   3422828] [b2699_GTAProce]             MainThrd/ 
[   3422828] [b2699_GTAProce]             MainThrd/ 
[   3422828] [b2699_GTAProce]             MainThrd/ 
[   3424109] [b2699_GTAProce]             MainThrd/ 
[   3424109] [b2699_GTAProce]             MainThrd/ 
[   3424109] [b2699_GTAProce]             MainThrd/ 
[   3438890] [b2699_GTAProce]             MainThrd/ ^2[DEBUG]: ^3(prdx_farming) ^2Trying to remove plant object 3596875

**Comment by ithegreatgatsby** [comment]
Works fine. It's just some times if you press play pool before you rack it scuffs the script out for a bit. Just make sure you are setting up a game before hitting play
