### ISSUE TITLE
[BUG] Bikini Tow trailers won't store

### ISSUE THREAD

**Issue by Kromlec** [ParadoxGamingRP/bugs-and-suggestions#865]
### Your Discord Name

Kromlec#3389

### A clear and concise description of what the bug is

The following issues are happening with the trailers that you pull out from Bikini Tow.

Lowboy trailer- Has no tow vehicle menu and can't store it at HQ with the NPC.
Car hauler - Has no tow vehicle menu and can't store it at HQ with the NPC.
Single car trailer - DOES have tow vehicle menu but can't store it at HQ with the NPC.
Flatbed trailer - DOES have tow vehicle menu but can't store it at HQ with the NPC.

### Steps to Reproduce the Bug

Pull these trailers out at bikini tow and attempt to third eye for the tow menu and talk with NPC to try and store them.

### Expected Behavior

Should be able to impound the trailers so we don't have to use scuff impound and be able to store them at HQ.

### Screenshots/Videos

Have no pics or videos. Can attempt to record if needed.

### Log File

[bikini trailers.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9892392/bikini.trailers.txt)

**Comment by xXJamieXx** [comment]
This issue has been fixed and will be pushed in the next restart.
