### ISSUE TITLE
[BUG] Unable to install motors at Bikini Automotive

### ISSUE THREAD

**Issue by Kromlec** [ParadoxGamingRP/bugs-and-suggestions#866]
### Your Discord Name

Kromelc#3389

### A clear and concise description of what the bug is

When attempting to install engine into cars the engine fails to install, the wait bar goes down but the engine doesn't get installed and the vehicle can't be driven. You also are not able to put away the engine hoist after pulling it out. Both R and Y just set it down.

### Steps to Reproduce the Bug

Pull engine from car
Attempt to reinstall engine
Engine install wait time goes down but doesn't install.

### Expected Behavior

Engine should get installed into vehicle.

### Screenshots/Videos

No screenshot.

### Log File

[Biki auto.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9892500/Biki.auto.txt)

**Comment by ithegreatgatsby** [comment]
Is this still an issue after last night's restart?
