### ISSUE TITLE
[BUG] Treasure chest not deleting

### ISSUE THREAD

**Issue by Martyfly200** [ParadoxGamingRP/bugs-and-suggestions#867]
### Your Discord Name

Martyfly2005

### A clear and concise description of what the bug is

Duplication bug 

### Steps to Reproduce the Bug

Go fishing of pier
collect treasure chest
collect key 
open treasure chest 
close out chest 
open inventory then you can open the chest again

### Expected Behavior

you would usually open it once then it would disappear.

### Screenshots/Videos

no video

### Extra Notes (Optional)

I cant seem to open logs so if someone else were to be able to try this bug it would be greatly appreciated.

### Log File

no file please someone try to recreate as im new to pc

**Comment by SushiiPlays** [comment]
https://user-images.githubusercontent.com/110682189/198814597-8472f37b-0020-40cc-b587-908ed30bfd3c.mp4

**Send in by publisher of bug report to mod ticket**

**Comment by xXJamieXx** [comment]
This issue has been fixed and will be pushed in the next restart.
