### ISSUE TITLE
[BUG] Hunting doesnt work

### ISSUE THREAD

**Issue by PatrykX904** [ParadoxGamingRP/bugs-and-suggestions#868]
### Your Discord Name

Help Me Choose A Name#0175

### A clear and concise description of what the bug is

Whenever I place a hunting bait down the animal doesnt spawn after a real long while then when I try to place down another bait it says ERROR and also wastes 20% of the hunting bait still.

### Steps to Reproduce the Bug

1. Place hunting bait down
2. Wait a really long time for an animal 
3. Animal doesnt come by
4. Try to place bait down again
5. In the top right it says ERROR
6. Just like that you've waste 20% of your hunting bait

### Expected Behavior

Be able to place down a hunting bait and have the animal come to the bait so I can make money from hunting

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/81855046/198832279-37774cd0-2a9e-43a9-b2e5-d7fce9b12701.png)

**Comment by xXJamieXx** [comment]
This issue has been fixed and will be pushed in the next restart.
