### ISSUE TITLE
[BUG] Headpops in Zancudo tunnel

### ISSUE THREAD

**Issue by Flora45** [ParadoxGamingRP/bugs-and-suggestions#870]
### Your Discord Name

Flora#8531

### A clear and concise description of what the bug is

I along with many others have experienced a great volume of head pops around the Zancudo Tunnel area. Today specifically 
My head popped 3 times back-to-back whilst inside the tunnel. Not 100% sure on what's causing it.

### Steps to Reproduce the Bug

1. drive through Zancudo tunnel
2. experince head pops 

### Expected Behavior

1. Dive through Zancudo tunnel
2. Experience no Head pops

### Screenshots/Videos

![FiveM® by Cfx re -  Original  Paradox Gaming RP _ 3+ years _ discord gg_paradoxgaming 29_10_2022 17_24_08](https://user-images.githubusercontent.com/79613077/198852928-09c02b3c-478c-4f10-9282-55433fa84eb6.png)

### Extra Notes (Optional)

none

### Log File

[CitizenFX_log_2022-10-29T194722.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9894610/CitizenFX_log_2022-10-29T194722.log)

**Comment by ithegreatgatsby** [comment]
Closing for now. I made some changes let me know if that fixes anything.
