### ISSUE TITLE
[ENHANCEMENT] Wallet System & Hats

### ISSUE THREAD

**Issue by SwickMachine** [ParadoxGamingRP/bugs-and-suggestions#873]
**Your Discord Name**
SwickMachine#6355

**Wallets**
I have two ideas so instead of making two different tickets, I am just going to make one. 

There was some talk in the general chat about insurance and how it could be implemented. This brought a much broader idea to mind and that would be wallets. These would be purchaseable at clothing stores by peeking the desk and buying one. 

The idea being you could have your..
- ID - Just a safe place to keep it instead of just floating around in your pockets. 
- Debit card -  Used at ATM's, resturaunts, mechanic shops, etc registers around the city. Must be obtained from the bank. If you do not have one on you or in your wallet, you are not able to access funds.
- Insurance cards - With the original idea in general chat, to add on to it, medical prices should be higher to promote more EMS/Hospital RP. With the addition to these new cards, an insurance card can be bought from the hospital. If you have this insurance card in your pockets or in your wallet, you will be charged a set discount for services for an extended period of time. This card will degrade over the set time and will need to be repurchased once expired. 
- Business Loyalty Cards - These can be handed out as lotalty cards for discounts at business around the city. Discount would be applied to customers bill by the person ringing them up. These would just be flashable cards with the persons name on them similar to an ID and have them degrade over time similar to insurance cards. 
- Business Cards - This can be done various different ways including stackable cards you can hand people or just another flashable object. 

From there, various businesses could spring up including ideas like someone who can print pictures which can be held in the wallets, someone who could make custom wallets and give you custom designs, people to design the business cards themselves, etc.   

**Hats**
Have hats added to the "mask maker" down by the beach. Having the ability to switch between a racing helmet and a hat, two different styles of hats, etc. similar to switching masks would be a great addition.

**Comment by JnKTechstuff** [comment]
Only problem is people seem to constantly scuff themselves by spamming shit which we have seen with other containers inside the inventory (IE: fishing ice boxes). So part of me thinks this is a bad idea

**Comment by SwickMachine** [comment]
Completely understandable! Was just a suggestion based off of a community idea.

**Comment by unforgiven8233** [comment]
maybe in stead have it to /wallet with like a 30 sec cooldown to open as a safe spot to store the cards only and to use them you have to pull them out of your wallet just like irl
