### ISSUE TITLE
[BUG] can turn on lights and sirens from the out side of the car

### ISSUE THREAD

**Issue by Dez505** [ParadoxGamingRP/bugs-and-suggestions#877]
### Your Discord Name

Dez505#1103

### A clear and concise description of what the bug is

when you get out of a public safety vehicle you can hit "Q" to turn on lights and hit "ALT" to turn on your sirens 

### Steps to Reproduce the Bug

1. step out of a public safety vehicle 
2. hit "Q"
3. hit "ALT"

### Expected Behavior

lights and sirens turn on

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/GGuPE5s9bO4Hh/d1337N8HgRbP?invite=cr-MSxFWE4sMzQ3OTM3MTAs

**Comment by xXJamieXx** [comment]
Combining with #879
