### ISSUE TITLE
[BUG] Police vehicle issues

### ISSUE THREAD

**Issue by Terrylaughlin35** [ParadoxGamingRP/bugs-and-suggestions#879]
### Your Discord Name

Terry Laughlin #3143

### A clear and concise description of what the bug is

Pulling out a cruiser removes the extras whether it be a motorpool cruiser or a personal. We are also able to control lights and sirens while outside of the vehicle

### Steps to Reproduce the Bug

1. pull out a cruiser
2. notice extras gone
3 step out and hit q for lights and alt for sirens 
4. notice they turn on while outside the vehicle

### Expected Behavior

For extras to stay on car and not to be able to turn on lights and sirens while outside of the car

### Screenshots/Videos

wasn't currently able to get video 

### Log File

[police cruiser issues.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9905755/police.cruiser.issues.txt)

**Comment by Dez505** [comment]
https://medal.tv/games/gta-v/clips/GGx5A0LUdWJDb/d1337xBDFto0?invite=cr-MSxGU00sMzQ3OTM3MTAs
