### ISSUE TITLE
[BUG] Waking up in wrong apartment

### ISSUE THREAD

**Issue by Clintyrichy** [ParadoxGamingRP/bugs-and-suggestions#880]
### Your Discord Name

Jumpenny#4194

### A clear and concise description of what the bug is

Waking up in other people's apartments even though I closed the game while in mine. To be honest I often forget to use character logout. But only yesterday in today, when i didn't use character logout, and instead closed the game manually with alt f4, when I logged back in, i had woken up in someone else's apartment. It has happened twice now. Again, I have logged out this way for months, but this is the first 2 times have ever woken up in the wrong apartment. I was able to tell because the first time there was somebody home, and the second time there were items on the ground that couldn't have been mine.

### Steps to Reproduce the Bug

Closing the game while in your own apartment
Do not use character logout, close the game any other way.
Log back in to the server
Wake up in someone else's apartment

### Expected Behavior

I never saw the first moments of the game opening either time, but a lot of times when I do see it, my character falls through the floor before then appearing in his own apartment. I think i may possibly be clipping into other people's apartments when I fall through the floor like this?

### Screenshots/Videos

I was not recording at the time, and don't think i should attempt to recreate it, but if the team wants me to i could record it and try to recreate the bug

### Extra Notes (Optional)

I have not recorded the bug, and am a bit apprehensive to try to recreate it (im sure you can tell why lol) But if it would help the team I could record myself attempting to do it again.

### Log File

I don't have any logs related to the event.

**Comment by JnKTechstuff** [comment]
Pretty sure this was that fucked up night
