### ISSUE TITLE
[BUG] Boss menu not working

### ISSUE THREAD

**Issue by ImCarbonYo** [ParadoxGamingRP/bugs-and-suggestions#884]
### Your Discord Name

Carbon#7678

### A clear and concise description of what the bug is

Can not access the boss menu

### Steps to Reproduce the Bug

go to computer
third eye
click on boss actions
nothing happens

### Expected Behavior

a menu for my business or gang

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/117232239/199351811-8efc15fd-30d7-4535-a37e-4888027c9b7d.png)

**Comment by xXJamieXx** [comment]
Fixed. Next time actually put a title for the issue? smh
