### ISSUE TITLE
[BUG] House Decorating

### ISSUE THREAD

**Issue by agentspooky19** [ParadoxGamingRP/bugs-and-suggestions#886]
### Your Discord Name

AgentSpooky#6204

### A clear and concise description of what the bug is

When in decoration mode multiple items were placed and saved. Upon exiting the decoration mode everything disappeared even with leaving the house, closing down fivem and restarting my PC. There are also items that I went to remove and it has the option however once destroying the item it is still in the furniture list. I am able to move and place things just unable to get the items I place to stay and the items I want to remove to be removed. I did have a Moderator come and assist and they had the same issue. I had a ticket in place ticket#12157 and they had placed notes in as well when they attempted. 

### Steps to Reproduce the Bug

Open decoration mode and attempt to remove items. It wasn't all items I had issues with on removing. However there were specific items that wouldn't destroy.

### Expected Behavior

I expected the items I had saved in place to remain where I had put them. But once saving and exiting decoration mode everything disappeared and a few items refused to destroy. 

### Screenshots/Videos

![Screenshot (185)](https://user-images.githubusercontent.com/117245051/199381095-f83fc986-7670-4104-9aab-f2736a98ebaa.png)
![Screenshot (186)](https://user-images.githubusercontent.com/117245051/199381096-50f580db-7a70-4a3a-ba72-72b8fab41610.png)
![Screenshot (187)](https://user-images.githubusercontent.com/117245051/199381112-95360c19-2b86-46b0-beae-b1639fcbb385.png)

### Log File

[CitizenFX_log_2022-11-02T014859.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9915412/CitizenFX_log_2022-11-02T014859.log)

**Comment by Drunkle716** [comment]
![FiveM_b2699_GTAProcess_GBTG2U2B2q](https://user-images.githubusercontent.com/100391224/201806110-17903aec-a02d-4cd0-87c5-1d185209f76d.jpg)

Still unable to delete those specific items permanently

**Comment by ithegreatgatsby** [comment]
refer to #841 for all future updates with anything housing/decorating
