### ISSUE TITLE
[BUG] MDT not saving profile 

### ISSUE THREAD

**Issue by RizzleMyNizzle** [ParadoxGamingRP/bugs-and-suggestions#889]
### Your Discord Name

RizzleMyNizzle#8454

### A clear and concise description of what the bug is

The MDT is not working. When you give a license and hit save, it is not saving it. 

See video below

### Steps to Reproduce the Bug

Select license
Save profile
Not saving

### Expected Behavior

Save that I gave license

### Screenshots/Videos

https://user-images.githubusercontent.com/106287551/199598728-886a98b8-879a-466a-80f5-a2f08aada68f.mp4

### Log File

[CitizenFX_log_2022-11-02T202159.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9924036/CitizenFX_log_2022-11-02T202159.log)
[CitizenFX_log_2022-11-02T203051.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9924037/CitizenFX_log_2022-11-02T203051.log)

**Comment by RizzleMyNizzle** [comment]
Oops I should have added it those this report... https://github.com/ParadoxGamingRP/bugs-and-suggestions/issues/888

**Comment by xXJamieXx** [comment]
Combining with #888
