### ISSUE TITLE
[BUG] /me does not work in offices

### ISSUE THREAD

**Issue by ShaymusSavage** [ParadoxGamingRP/bugs-and-suggestions#890]
### Your Discord Name

Shaymus#1460

### A clear and concise description of what the bug is

While in an office at Arcadius Towers at 389, if someone uses /me posts, they will show up on the office name (As seen in the picture) versus above the person's character.

### Steps to Reproduce the Bug

1. Go into Office at Arcadius Towers (Postal 389)
2. Type /me something
3. Look at the office's name above the reception desk.

### Expected Behavior

/me's should appear normally above the character.

### Screenshots/Videos

https://i.imgur.com/onkOYq5.jpeg

**Comment by JnKTechstuff** [comment]
Not a bug, just how things work in offices to have the working signage
