### ISSUE TITLE
[ENHANCEMENT] Farming

### ISSUE THREAD

**Issue by unforgiven8233** [ParadoxGamingRP/bugs-and-suggestions#894]
**Your Discord Name**
[Forgotten#0031]

**Describe the annoyance**
When it is raining and you are farming you still have to water your plants even know the ground is soaked 

**To Reproduce**
[Steps to reproduce the annoyance]
1. Wait till it rains 
2. Go farming
3.  Realize you still need to water your plants 

**Requested behavior**
when raining have your plants water level not decrease

**Comment by unforgiven8233** [comment]
Inanition to this if you farm in irrigated land you should not have to water the plant as it would already be watered 
![image_2022-11-07_074446823](https://user-images.githubusercontent.com/85376462/200313809-698b5292-877c-44de-9b63-0a327ef140e3.png)

**Comment by JnKTechstuff** [comment]
No thats just defeating the purpose of the systems in place
