### ISSUE TITLE
[BUG] Heli with no tail or blades

### ISSUE THREAD

**Issue by Terrylaughlin35** [ParadoxGamingRP/bugs-and-suggestions#896]
### Your Discord Name

Terry Laughlin#3143

### A clear and concise description of what the bug is

Go to pull the heli out and it has no blades or tail.

### Steps to Reproduce the Bug

1. go to pull heli out
2. pull heli out
3. have no tail or blades from impound or garage

### Expected Behavior

to be able to fly with a tail and blades

### Screenshots/Videos

unable to provide video

### Log File

[heli screw up.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9945177/heli.screw.up.txt)

**Comment by ithegreatgatsby** [comment]
I doubt this is a bug.  Heli blades and such are extras and with other people having issues with the extras this could be it. I would have a staff member no clip it to the customs shop and add back the extras and then save it in the garage. Let us know after that

**Comment by Terrylaughlin35** [comment]
We had to noclip it to a customs shop and get the blades and tail back on. If you take them off and put them back on before you park it there seems to be no issues with getting it out. It is only if you dont put them back on before parking.

**Comment by Asaineur** [comment]
ill try that too!

**Comment by Terrylaughlin35** [comment]
that did not fix it pulled it out again today with no tail or blades. I am unsure how to fix the issue

**Comment by CorFinn** [comment]
More info: 

Terry was able to store his heli in a personal garage (helipad in sandy, which is open to aircraft) and pulled it out fully formed. 

I then attempted to store the same heli in the Flying Beaver Aviation parking (a shared business garage) just in front of the Sandy Airfield hangar. It came out with no extras, missing essential parts. 

Could garage type be affecting it somehow?

**Comment by Terrylaughlin35** [comment]
No garage type isn't the issue Terry owns a personal helicopter and when I pull it out of a personal garage or even impound it comes out with no blades or tail.
