### ISSUE TITLE
[ENHANCEMENT] Increase copper smelting output from 4 to 6

### ISSUE THREAD

**Issue by mjb328** [ParadoxGamingRP/bugs-and-suggestions#898]
**Your Discord Name**
MJB328#5303
**Describe the annoyance**
I'm trying to start up a material/ manufacturing company in city. Right now I buy my ores from the local to save my workers time as an incentive. Another big incentive to my workers is decent % of the profit of the materials sold. With that said copper has the smallest profit margins of four being, copper, iron, aluminum, and steel.  For example I buy one copper ore for 25 it yields 4 at a price point of 12 per ore it come out to 48. After cover ore cost that only a $23 profit margin per-ore. Now local prices dictate the buy and sell window is 9-15. I do my best to meet in the middle. For copper that'd be $12. This way I'm not making the minimum and a customer isn't paying the maximum like they would from a local. All I ask is an increase of 2 on the copper output.

[Steps to reproduce the annoyance]
1. 
2. 
3. 

**Requested behavior**
2 more copper ingots per ore thats all.

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by JnKTechstuff** [comment]
No its balanced to more than this
