### ISSUE TITLE
[BUG] Boosting contracts not spawning in the car that the contract was for

### ISSUE THREAD

**Issue by WillyHDT** [ParadoxGamingRP/bugs-and-suggestions#900]
### Your Discord Name

Will.#0928

### A clear and concise description of what the bug is

I have been having an issue with an area that my boosting contracts have been giving me. My friend and I have looked everywhere we possibly could for about 30 minutes and couldn't find the car. I'm thinking the car isn't spawning in this area because of it being the 2nd time happening and the contract being for different cars.

### Steps to Reproduce the Bug

1. Make sure the car will spawn in that zone 
2. Have a few spots for the car to spawn in at so that we don't second guess if it can spawn multiple places.

### Expected Behavior

I expect the car that the contract tells me to look for to be in the circle that it has given me and expect to look in the same few spots that way I don't second guess and think I could have missed the car or it hasn't spawned.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/110565752/200975415-4a6d5734-d3fc-4aa5-a8f4-cbe368c34308.png)

**Comment by JnKTechstuff** [comment]
maybe uu just can't find it? Never been an issue for months and the spawns weren't changed.
