### ISSUE TITLE
[BUG] Jewelry Making Precision Cut

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#903]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

Making a precision cut for a diamond ring only made 1 ring.

### Steps to Reproduce the Bug

1. get diamond
2. get ring
3. make diamond ring on anvil
4. get precision cut.

### Expected Behavior

Makes 2 diamond rings not 1.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98053772/201153317-3bfd01a2-a526-4973-ab82-cafa788e553b.png)

**Comment by Darahz** [comment]
Alright. Should be taken care of!
