### ISSUE TITLE
[BUG] Can't buy tattoos

### ISSUE THREAD

**Issue by Zapp2G** [ParadoxGamingRP/bugs-and-suggestions#904]
### Your Discord Name

Zapp2G#9791

### A clear and concise description of what the bug is

cannot buy tattoos, both stores (tattoo parlor and skull island) 

### Steps to Reproduce the Bug

walk into tattoo shop
try to buy tattoo

### Expected Behavior

wont do anything

### Screenshots/Videos

https://user-images.githubusercontent.com/117957879/201242280-e337d0a6-a1e7-40e0-bf3a-44836a4b88e1.mp4

### Log File

[CitizenFX_log_2022-11-03T025630.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9985766/CitizenFX_log_2022-11-03T025630.log)
all i could find for anything relating to logs

**Comment by xXJamieXx** [comment]
Should be fixed.
