### ISSUE TITLE
[BUG] Bearcat Head Pop

### ISSUE THREAD

**Issue by SpiceF0x** [ParadoxGamingRP/bugs-and-suggestions#906]
### Your Discord Name

spicedf0x#2127

### A clear and concise description of what the bug is

Whenever someone goes near the bearcat they instantly head pop, can't even get in it. 

### Steps to Reproduce the Bug

1. Pull out bearcat
2. Walk to bearcat
3. Headpop

### Expected Behavior

To stay alive in city

### Screenshots/Videos

https://streamable.com/vz2227

### Log File

[CitizenFX_log_2022-11-11T105150.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/9989622/CitizenFX_log_2022-11-11T105150.log)

**Comment by Northingbud** [comment]
Issue fixed next restart - described issue was in regards to the vehiclelayouts.meta file not being read for the vehicle by the lua. this was due to a tail at the end of the file "_bcat" causing it not to be picked up. Should be resolved next restart,
