### ISSUE TITLE
[BUG] Opening race tablet gives you nitrous 

### ISSUE THREAD

**Issue by Flora45** [ParadoxGamingRP/bugs-and-suggestions#912]
### Your Discord Name

Flora#8531

### A clear and concise description of what the bug is

If you press X after a few seconds of opening and closing your racing tablet it will give you a short-lived boost of nitrous. My current car has no nitrous whatsoever. Not sure on what's causing the bug but it's something that players can definitely abuse. 

### Steps to Reproduce the Bug

1. Open race tablet
2. close race tablet
3. Press X a few seconds after tablet is closed
4. Observe a short amount of nitrous given to your car

### Expected Behavior

1. Open race tablet
2. Close race tablet
3. Not receive any amount of nitrous 

### Screenshots/Videos

The video File is too big, if you would like me to send it via discord I can. 

### Log File

[CitizenFX_log_2022-11-14T064931.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10001231/CitizenFX_log_2022-11-14T064931.log)

**Comment by Flora45** [comment]
Update on this. If you just spam your x muscle, it will give you nitrous without having any installed on your car. Will send a video shortly.

**Comment by Flora45** [comment]
https://streamable.com/9mek3e As you can see I have no nitrous installed. I literally just spam X and I get boost.

**Comment by JnKTechstuff** [comment]
Bruh @Northingbud you have a car with native NOS. Not a scripting issue this is a model issue.

**Comment by Northingbud** [comment]
All vehicles that had the Nitrous on modparts should have had that removed from their carcols meta files to not have that, there shouldn't be anything with default nitrous.

**Comment by Northingbud** [comment]
Must have been reverted, this is one of the cars that was previously fixed. carcols should be fixed to not have it after restart looking into other vehicles.
