### ISSUE TITLE
[BUG] CVPI Handling

### ISSUE THREAD

**Issue by LitrlyD3ad** [ParadoxGamingRP/bugs-and-suggestions#913]
### Your Discord Name

D3ad#2545

### A clear and concise description of what the bug is

when the CVPI is in the air it seems to be unbalanced and uncontrollably starts to "roll" towards the right, this wouldn't be a issue if jumps wasn't a regular escape tactic for most crims. When the CVPI chases a crim and they take a jump 9/10 the cvpi will flip bc of this issue. 

### Steps to Reproduce the Bug

1. pull out a CVPI
2. take a jump or get even somewhat airborn
3. profit

### Expected Behavior

to be a bit frontward heavy due to the engine, not act like i have the entire PD's ego in my passenger seat (thats a joke, or is it)

### Screenshots/Videos

[https://i.imgur.com/7KNJ9PR.png](url)

**Comment by EmmettIsTRASH** [comment]
I've already been working on this, so I should hopefully have the vehicle fixed up and working much better soon.

**Comment by EmmettIsTRASH** [comment]
Should be drastically better for next restart :)

**Comment by LitrlyD3ad** [comment]
Thanks for your work, ill hope in later today and give it a drive and lmk how it feels :)
