### ISSUE TITLE
[ENHANCEMENT] PHX-1 Spotlight

### ISSUE THREAD

**Issue by LitrlyD3ad** [ParadoxGamingRP/bugs-and-suggestions#914]
**Your Discord Name**
D3ad#2545

**Describe the annoyance**
I would like the development team to consider trying to add back the spotlight feature to the air support helicopters toolbelt, One that follows the camera that locks onto cars that the second pilot uses in a chase, I feel it could not only make locating criminals a bit easier, aswell as showing ground units where a suspect is, but it could also add a "cool factor" for criminals when they are on the run. Being a criminal and being on the run and having a giant fuck you spotlight on you while you run away from police not only sounds badass, but it would just add a little more to a extreme "fugitive on the run scene". I believe back when we had it before it would cause issues but id like to see at least a attempt to bring it back. 

**To Reproduce**
[Steps to reproduce the annoyance]
1. get into PHX-1
2. chase someone
3. no giant fuck you spotlight
4. sadge

**Requested behavior**
to have a giant fuck you spotlight to make crims shit their pants

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by JnKTechstuff** [comment]
No its too taxing on clients to deal with syncing a giant bright as sun light
