### ISSUE TITLE
[ENHANCEMENT] Locker keys

### ISSUE THREAD

**Issue by unforgiven8233** [ParadoxGamingRP/bugs-and-suggestions#915]
**Your Discord Name**
Forgotten#0031

**Describe the annoyance**
When unloading a large amount of items into or out of the locker having to type in the id and passcode each time take quite a bit where if the owner could /givelocker (id) and that player then can open it as if they were the owner

**To Reproduce**
[Steps to reproduce the annoyance]
1. have someone else buy a locker
2. enter it 10-15 times
3. get annoyed

**Requested behavior**
be able to open shared lockers with out entering the passcode every time

**Comment by JnKTechstuff** [comment]
No if you want that buy a house or warehouse or something. Storage lockers are setup this way for a reason.
