### ISSUE TITLE
[BUG] Milky picture do be gone

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#922]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

The picture of the milk has gon byebye. 

### Steps to Reproduce the Bug

Have milk in stash or pockets
No picture for people

### Expected Behavior

See the beautiful milk box

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98127638/202158392-ee224c29-6b9e-4a9e-9071-93d78d0f266a.png)

**Comment by JnKTechstuff** [comment]
Bruh why does milk hate me
