### ISSUE TITLE
[BUG] Holsters changing when relogging 

### ISSUE THREAD

**Issue by SushiiPlays** [ParadoxGamingRP/bugs-and-suggestions#925]
### Your Discord Name

sushiiplays#0120

### A clear and concise description of what the bug is

I regularly use necklace 125 and 130 holsters, however when I relog most times it automatically switches to the holster without to working version. These versions it switches too is necklace 126 and 127. This only happens after relogging.

### Steps to Reproduce the Bug

Have a gun in your pockets while wearing Necklace 125 or 130
Relog 
Pull out your weapon

### Expected Behavior

The gun to be pulled in a quick draw, normal time would be 1-2 seconds to pull. The holster switches to a empty version thus taking 2-3 seconds to pull after relogging.

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/IGzYtwOCVnOaE/d13378NmAmXm?invite=cr-MSw1eFksMTE2NjU1NTA2LA 
![20221116143409_1](https://user-images.githubusercontent.com/110682189/202278497-66441f1c-7b10-4675-9ed7-33ea5a77b00c.jpg)
![20221115172114_1](https://user-images.githubusercontent.com/110682189/202278650-b95ba9fc-c016-49a9-9258-821c11374251.jpg)
(Second photo is one from the first session before relogging where I have a working holster with a gun inside)

### Log File

[CitizenFX_log_2022-11-16T190550.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10025176/CitizenFX_log_2022-11-16T190550.log)

**Comment by JnKTechstuff** [comment]
Is it more likely you pull out a gun and then log out or log out and accidentally pull it out causing it to be gone when your player data saves? Because otherwise in a technical standpoint it makes little to no sense how it could happen

**Comment by ithegreatgatsby** [comment]
Cant reproduce. Open a new bug report if you still have issues
