### ISSUE TITLE
[BUG] Crosshair Bug?

### ISSUE THREAD

**Issue by xaroht** [ParadoxGamingRP/bugs-and-suggestions#926]
### Your Discord Name

thørax#0098

### A clear and concise description of what the bug is

When in cover (using Q) your GTA crosshair appears.

### Steps to Reproduce the Bug

1. Have gun out
2. Go into cover by pressing Q
3. Crosshair should appear on screen

### Expected Behavior

For crosshair only to appear when you are ADS'd

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/IHyIm0OOg1zFj/d1337D6oSsfu?invite=cr-MSwxSmksMjc2ODk4MzYs

https://i.imgur.com/kcdLfVi.png

**Comment by JnKTechstuff** [comment]
That is not the default GTA crosshair and is actually our crosshair. It just opens now when the R* one would to be more consistent. The way to tell if its a default one is if it turns red on a ped
