### ISSUE TITLE
[BUG] Corner Selling

### ISSUE THREAD

**Issue by SpiceF0x** [ParadoxGamingRP/bugs-and-suggestions#928]
### Your Discord Name

spicedf0x#2127

### A clear and concise description of what the bug is

I've tried selling weed two days running now and only able to make two deals both days. I am being noticed, but no-one else is walking up to make a deal. I'll test this again at 6pm restart.

There's nothing in F8, I've tried moving spots. I've tried restarting in the same area. I've tried logging out. I've tried F8 quit. I've tried dropping the weed and picking it up. I've tried putting it in my stash and repocketing it.

### Steps to Reproduce the Bug

1. Start selling
2. Wait to get noticed
3. Make two deals
4. No one else notices me :(
5. Wait forever
6. Feel sad and unloved

### Expected Behavior

Make multiple deals until all my drugs are gone and the locals are high

### Screenshots/Videos

n/a

**Comment by JnKTechstuff** [comment]
Should be working now?
