### ISSUE TITLE
[BUG] Car color changed

### ISSUE THREAD

**Issue by PatrykX904** [ParadoxGamingRP/bugs-and-suggestions#929]
### Your Discord Name

Help Me Choose A Name#0175

### A clear and concise description of what the bug is

So when I logged back on to play some paradox I took my car out and the color changed. The color normally was white and black but it changed to a dark blue and black

### Steps to Reproduce the Bug

1. Have a car that is a whatever color
2. Park it
3. Car color changes

### Expected Behavior

When I park my car and I take it out the car color should be the same

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/81855046/202799609-fec4fae9-6364-4104-a3fe-141fade71f91.png)

**Comment by JnKTechstuff** [comment]
A one time issue is not a reproducible bug
