### ISSUE TITLE
Extra toggle fixing body damage[BUG] 

### ISSUE THREAD

**Issue by RedDarthMawl** [ParadoxGamingRP/bugs-and-suggestions#932]
### Your Discord Name

RedDarthMawl#9096

### A clear and concise description of what the bug is

I came across this bug when putting a vehicle on a slam truck

### Steps to Reproduce the Bug

1. Get a slam truck
2. put a vehicle on the slam truck forwards and strap it down
3. unstrap it and it bounces off

### Expected Behavior

We expect it not to jump off the slam truck

### Screenshots/Videos

Uploading 2022-11-18 22-11-34_Trim.mp4…

### Log File

it wasnt my vehicles so i cant provide logs sorry

**Comment by JnKTechstuff** [comment]
Just something that can happen and nothing we can really do about it
