### ISSUE TITLE
[BUG] unable to buy ores/jewelry 

### ISSUE THREAD

**Issue by unforgiven8233** [ParadoxGamingRP/bugs-and-suggestions#933]
### Your Discord Name

Forgotten#0031

### A clear and concise description of what the bug is

In the foundry you could buy ore for $25 each and cant now 
and the jewelry buy menu wont show any items to buy 
the only thing i saw in server commits was the moving of the npc
nothing about the removal of ores/jewelry

### Steps to Reproduce the Bug

1. go to the foundry and open the buy ores option and try to buy iron/gold/copper/bauxite ore

or 

1. go to the jewelry dealer and try to buy a uncut diamond 

### Expected Behavior

1. be able to buy the ore

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/85376462/202833427-68c6f065-f199-43cb-a4a3-4e0581b62ec5.png)
![image](https://user-images.githubusercontent.com/85376462/202833437-6e547750-7a5f-43fd-b3a6-722f07b23cef.png)

![image](https://user-images.githubusercontent.com/85376462/202833892-3bbee781-8cf3-4545-b714-3add707de83c.png)

**Comment by JnKTechstuff** [comment]
They were removed because people abused them
