### ISSUE TITLE
[ENHANCEMENT] VIN Scratching vehicles

### ISSUE THREAD

**Issue by C9Roxas** [ParadoxGamingRP/bugs-and-suggestions#934]
**Your Discord Name**
Buzzard#1111

**VIN Scratching**
Would love to see a mechanic as both crim and cop, where someone could VIN scratch a vehicle. To prevent hoarding or destroying a vehicle market, I was thinking of only getting 1 scratch a week to use on a car, and being limited to only 1 VIN scratch in your garage at a time. I think this would bring, personally, a lot more to the table RP wise when catching someone and investigating their cars and handling these illegal vehicles, and as a crim, having to be extremely careful with a car that you only get one chance in or else its permanently police impounded when discovered.

**Comment by ithegreatgatsby** [comment]
This could come in the future as the racing/car scene develops story
