### ISSUE TITLE
[ENHANCEMENT] SNOWBALLS!!

### ISSUE THREAD

**Issue by Flora45** [ParadoxGamingRP/bugs-and-suggestions#936]
**Your Discord Name**
Flora#8531

**Describe the annoyance**
0 annoyances! I just saw recently they added a snowball script to the forums. I'm sure it's been around but I just saw this one specifically. Here is the link https://forum.cfx.re/t/snowballs/55932

**To Reproduce**
none

**Requested behavior**
1. Pick up snoball 
2. Throw snowball

**Screenshots**
none

**Additional context**

**Comment by JnKTechstuff** [comment]
Added
