### ISSUE TITLE
[BUG] Phone Key App Doesn't Work

### ISSUE THREAD

**Issue by Weebait** [ParadoxGamingRP/bugs-and-suggestions#937]
### Your Discord Name

Weeb#5266

### A clear and concise description of what the bug is

Whenever I press on the phone app for housing and press on the keys tab my app seemingly "crashes". It gives me a teal blue screen with a reload button which doesn't go away. This effectively makes it impossible to access the app and remove anyone.

### Steps to Reproduce the Bug

1.  Click on the phone app
2. It doesn't work

### Expected Behavior

When I click on the phone app I am able to use the keys app and remove people

### Screenshots/Videos

N/A but can get the picture if needed

**Comment by Weebait** [comment]
https://i.imgur.com/44FDFCd.png

**Comment by ithegreatgatsby** [comment]
Cant reproduce this. Is this still an issue? could be connection issues
