### ISSUE TITLE
[BUG] Bank Job Drill Doesnt Drill

### ISSUE THREAD

**Issue by Grim1delta** [ParadoxGamingRP/bugs-and-suggestions#939]
### Your Discord Name

Bedlam#7368

### A clear and concise description of what the bug is

Bank job drill is unable to move forward and back while drilling, locking you into the animation and preventing you from drilling boxes. Re logging locks you out of safe deposit boxes and locks you into vault.

### Steps to Reproduce the Bug

1. Get to part of bank where you drill boxes
2. Speed up drill and push into lock
3. Get Stuck

### Expected Behavior

To be able to drill deposit boxes and get cash or at least cancel the animation and try again.

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/JBFyiqw6pFAXz/d1337w3cnhWj?invite=cr-MSx1ZW8sMTQwNjYxNTU0LA

**Comment by Flora45** [comment]
I can confirm this bug as well. The drill will speed up and slow down but will not go up nor down. As far as getting stuck in the animation I tried everything to get out of it. I ended up relogging and that worked but of course I lost the bank job and was stuck in vault.

**Comment by JnKTechstuff** [comment]
Should be fixed
