### ISSUE TITLE
[BUG] PD Weapon repair not showing up 

### ISSUE THREAD

**Issue by unforgiven8233** [ParadoxGamingRP/bugs-and-suggestions#943]
### Your Discord Name

Forgotten#0031

### A clear and concise description of what the bug is

when i go to the bench and pull a weapon out to repair nothing show up

### Steps to Reproduce the Bug

1. go to mrpd
2. clock on duty
3. go to the bench
4. pull a weapon out
5. nothing shows up

### Expected Behavior

being able to repair weapons

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/85376462/203873603-ee1d29af-296d-4c9c-bcee-adad69e9f292.png)

### Extra Notes (Optional)

I have went off duty then back on duty
and reloged

**Comment by Darahz** [comment]
![image](https://user-images.githubusercontent.com/35222814/205442979-78cbfe81-ffee-468a-8ca3-ab08b1a6300b.png)
Is this something that happens anymore?

**Comment by unforgiven8233** [comment]
it randomly does not show up

**Comment by ithegreatgatsby** [comment]
I also tested this and it works fine for me. And we have had no other reports on this
