### ISSUE TITLE
[BUG] <NOS Bottles not working>

### ISSUE THREAD

**Issue by kevstax** [ParadoxGamingRP/bugs-and-suggestions#944]
### Your Discord Name

KevStax#7186

### A clear and concise description of what the bug is

Whenever I attempt to use a nos bottle on my car it takes the bottle out of my pockets and my NOS lines are still empty. You also lose your bottle entirely.

### Steps to Reproduce the Bug

1. Get in car
2. use nos bottle

### Expected Behavior

Use NOS bottle and the bar on the bottom of the screen gets filled. The bottle still stays in my pockets but is now empty.

### Screenshots/Videos

N/A

**Comment by ithegreatgatsby** [comment]
I cant reproduce this but I know there are very random times when this happens. We will have to look more into it
