### ISSUE TITLE
[BUG] Esperanto Taxis Repairs and Pushing

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#945]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

Till works on Taxis, but repairs and pushing the Taxi is not available.

### Steps to Reproduce the Bug

1. Third Eye the Car
2. No Push Option
3. Try Repair Kit
4. No Repairs Done.

### Expected Behavior

Repaired and be able to push.

### Screenshots/Videos

![BKj36hq](https://user-images.githubusercontent.com/98053772/204071055-74f274f3-40a1-4eb9-af64-167bdc4eb324.png)

**Comment by JnKTechstuff** [comment]
Push is going to be gone that's just a product of how shit works. The fixing things is irrelevant to the 3rd eye menu.
