### ISSUE TITLE
[BUG] New Loading Screen Loads Twice

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#949]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

Sometimes when I try loading into the game, the loading screen stays on the screen, while its ready for the character selection. Causing me to shut down the game and reload in. This is not the first time this has happened.

### Steps to Reproduce the Bug

1. Load into game.

### Expected Behavior

Going to be at the character screen each time.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98053772/204136839-c14d533c-fef7-43d7-92f8-34db509d8ce4.png)

**Comment by JnKTechstuff** [comment]
Yeah idk about this one but nothing I changed will do this
