### ISSUE TITLE
[BUG] Trash is trash

### ISSUE THREAD

**Issue by dustydustybunny** [ParadoxGamingRP/bugs-and-suggestions#951]
### Your Discord Name

DustBunny#0091

### A clear and concise description of what the bug is

Doing the trash job. Three of us on one job, using one truck. Finished all our routes, went back to finish the job. Neither of us could get our payslip because we kept getting the error "the person who started the route is required to collect the pay", Even though all three of us finished and one of us started the route. The leader was unable to cancel the route early. The leader was unable to finish/get payslip. All three of us worked trash for two plus hours, and have not received payment. 

### Steps to Reproduce the Bug

three people do trash, finish all your routes go to get payout.

### Expected Behavior

sends you on endless routes

### Screenshots/Videos

![ApplicationFrameHost_xK3xD7KLcK](https://user-images.githubusercontent.com/119283247/204208881-bbde7b25-76b9-40d8-bb58-603183b93c6f.png)

![ApplicationFrameHost_Hd6iUcIXUo](https://user-images.githubusercontent.com/119283247/204208886-87b98099-2add-4e90-9ef9-e7b23d89c7cb.png)

### Extra Notes (Optional)

We would like to see if we could get a refund/payout for the lost time. We spent over 2 hours doing trash.

**Comment by JnKTechstuff** [comment]
idk why we still have this script tbh
