### ISSUE TITLE
[BUG] Snowballs give cops 10-13 calls

### ISSUE THREAD

**Issue by pulsevr34** [ParadoxGamingRP/bugs-and-suggestions#952]
### Your Discord Name

Pulse+#5769

### A clear and concise description of what the bug is

Everytime someone throws a snowball cops get a shots fired call. pretty simple

### Steps to Reproduce the Bug

1. pick up snowball
2. throw snowball
3. shots fired

### Expected Behavior

no shtos fired for snowballs

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/97071437/204364119-c4711c50-5c78-40d7-b09e-6ef71b4b3b76.png)
Nott much to show, no logs or anything in f8 menu but it says its a pistol everytime

### Extra Notes (Optional)

N/A

### Log File

n/A

**Comment by JnKTechstuff** [comment]
This was fixed day of
