### ISSUE TITLE
[BUG] Blazer Aqua Has Pew Pew Guns :) 🔫

### ISSUE THREAD

**Issue by SpiceF0x** [ParadoxGamingRP/bugs-and-suggestions#953]
### Your Discord Name

spicedf0x#2127

### A clear and concise description of what the bug is

The Blazer Aqua has an aim crosshair dot and you can shoot guns, you get a drive by shooting notification on MDT.

guns are bad :( 

### Steps to Reproduce the Bug

1. Get on Blazer
2. Get a crosshair
3. Shoot guns pew pew

### Expected Behavior

Have no guns on a aquatic quad... I mean I don't mind...

### Screenshots/Videos

https://streamable.com/swile9

![image](https://user-images.githubusercontent.com/96963965/204379371-890b1e14-d094-473f-8764-622667a9b096.png)

**Comment by ithegreatgatsby** [comment]
just gonna remove it from the shops since you are the only one who owns one from what i can see in the mdt
