### ISSUE TITLE
[BUG] Paleto Bay impound

### ISSUE THREAD

**Issue by WickedlyLunar** [ParadoxGamingRP/bugs-and-suggestions#954]
### Your Discord Name

WickedlyLunar#1219

### A clear and concise description of what the bug is

I was up in Paleto Bay at Postal 3025 trying to pull my Surfer Van out of the Impound that is located there. I go to third eye the local with the clipboard and go to remove my van. It withdraws the $30 but does not teleport me to where my van should be. I attempted this three times before submitting a ticket. Attempted it a fourth time when asked and still the same result.

### Steps to Reproduce the Bug

1. Go to postal 3025's impound.
2. Third eye the local/npc at the impound desk.
3. Pull out vehicle (in my case the surfer van)

### Expected Behavior

I expected to pull my van out of impound like usual at the other locations.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/119532596/204886043-2f1fe6a6-ee6e-4aaa-8937-ef1fb594dbdc.png)

### Log File

[CitizenFX_log_2022-11-30T173701.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10126567/CitizenFX_log_2022-11-30T173701.log)
[CitizenFX_log_2022-11-30T182258.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10126568/CitizenFX_log_2022-11-30T182258.log)

**Comment by SpiceF0x** [comment]
Across more than one user 
![FiveM_b2699_GTAProcess_GQUKYEtxVb](https://user-images.githubusercontent.com/96963965/204894473-65f0b1c0-a870-4f9e-b0ee-7d2538cf56da.png)
https://streamable.com/uaxhqs

**Comment by ithegreatgatsby** [comment]
Test this again. Works fine for me it could of just been something that day

**Comment by ithegreatgatsby** [comment]
Seems to just of been a issue that day and has been working since.
