### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Truebeauty143** [ParadoxGamingRP/bugs-and-suggestions#955]
### Your Discord Name

True Beauty#0143

### A clear and concise description of what the bug is

Ice boxes are not allowing me to pull anything out when I do the icebox pulls it back into it. I have tried on several iceboxes and I have also had others try. Also when trying to move anything in the icebox (OCD Sorry) it moves them back to where they were before or it says its kinda fishy you are trying to put x item in a icebox. 

### Steps to Reproduce the Bug

Honestly just fix it so that I can get my fish out haha

### Expected Behavior

That I would be able to pull my fish out to sell them. 

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/KpQOc3eYA9-JU/d1337kKANLHi?invite=cr-MSxZRE4sNjYwNDc5NjMs

**Comment by JnKTechstuff** [comment]
Fixed
