### ISSUE TITLE
[BUG] GoPostal don't sell anything to civs

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#957]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

Trying to buy from either the ore-dealer or go-postal lady and it's not opening anything.

### Steps to Reproduce the Bug

Go to go-postal lady
Open her catalogue
She aint having none

### Expected Behavior

Be able to buy carbon for 15$ a pop

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98127638/205166817-d73fc791-d496-4aac-be4b-5f52a9b8d54a.png)

**Comment by JnKTechstuff** [comment]
Fixed
