### ISSUE TITLE
[BUG] Currently checking under the Christmas tree gives you multiple gifts 

### ISSUE THREAD

**Issue by JonnieSlay** [ParadoxGamingRP/bugs-and-suggestions#958]
### Your Discord Name

yeaaaaa#9829

### A clear and concise description of what the bug is

I checked the Christmas tree when i got an email, and then right before flying out. Both times I was given a Christmas gift. It was all under the same session. 

I don't think its meant to give you 2 gifts per session. 

### Steps to Reproduce the Bug

1. Get the email for the Christmas gift. 
2. Check to see if you have a gift under the tree. Get gift 1. 
3. Check to see if there are more gifts under the tree. Get gift 2. 

### Expected Behavior

It should only give you 1 gift from my understanding. 
I don't know how many gifts are under my tree but I am sure it might be more. 

### Screenshots/Videos

I didn't want to do it again as I don't want to be seen as abusing this new feature. But its easily re-creatable.

**Comment by JnKTechstuff** [comment]
Fixed
