### ISSUE TITLE
Military Kit Recycling 

### ISSUE THREAD

**Issue by Terrylaughlin35** [ParadoxGamingRP/bugs-and-suggestions#961]
### Your Discord Name

Terry Laughlin#3143

### A clear and concise description of what the bug is

You are unable to recycle Military kits and get any material from them once they are used up.

### Steps to Reproduce the Bug

1. go to scrapyard
2. put military kits in there
3. recycle
4. nothing happens

### Expected Behavior

to be able to get a small portion of what it takes to make them back.

### Screenshots/Videos

unable

### Log File

[recycling.txt](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10149742/recycling.txt)

**Comment by ithegreatgatsby** [comment]
added next update
