### ISSUE TITLE
[BUG] Unable To Update Twitter Profile

### ISSUE THREAD

**Issue by ShaymusSavage** [ParadoxGamingRP/bugs-and-suggestions#962]
### Your Discord Name

Shaymus#1460

### A clear and concise description of what the bug is

After attempting to update and save my twitter profile, I have unable to complete that. 
This has resulted in me unable to change name or picture on Twitter.

### Steps to Reproduce the Bug

1. Enter something into the Twitter Profile.
2. Press Save

### Expected Behavior

Be able to change name and twitter image. 

### Screenshots/Videos

https://i.imgur.com/IbvYHmj.png

**Comment by ithegreatgatsby** [comment]
This all works fine on my end. Just try to use the other links as listed above and I will be closing this

**Comment by ShaymusSavage** [comment]
I have attempted both a discord and an Imgur link with no luck. 
https://i.imgur.com/KaLN6yI.png
I have also attempted to use a picture from my phone with no luck. It would not change my name or picture.
