### ISSUE TITLE
[BUG] Can't interact inside of Integrity Way Apartment

### ISSUE THREAD

**Issue by lPrestonl** [ParadoxGamingRP/bugs-and-suggestions#963]
### Your Discord Name

Preston#1337

### A clear and concise description of what the bug is

I went to go get my Christmas present, however when I entered my Integrity Way Apartment that I was "locked in." Not sure if this is only Integrity Way or other apartments as well. I also have not tried to reproduce this bug. Nothing in the apartment was able to be interacted with(Stash, Wardrobe, Door to leave, etc). No added models other than the base apartment were in there either. I've attached a screenshot of the error that occurred in my console the second I walked in, as well as my full session CFX_Log.

### Steps to Reproduce the Bug

1. Enter the Apartment 
2. Realize everything isn't in the house and that you can't interact with anything.
3. Panic.

### Expected Behavior

To have a nice home to come too, with a lit and put up christmas tree.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/35425544/206374860-0ca979cf-31ff-486a-a097-ae8833d96d88.png)

### Log File

[CitizenFX_log_2022-12-08T053330.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10182719/CitizenFX_log_2022-12-08T053330.log)

**Comment by SwickMachine** [comment]
I have had this happen to me as well. Figured it might have been a one time instance. To add to this, after logging out and back in, I was given the option to buy my apartment at Marathon even though I owned it. Logged out once more and it was back to normal.

**Comment by xXJamieXx** [comment]
Seems to be an inconsistent edge case that isn't worth investigating right now.
