### ISSUE TITLE
[BUG] Hats

### ISSUE THREAD

**Issue by BrotherDayZ** [ParadoxGamingRP/bugs-and-suggestions#964]
### Your Discord Name

BDZ#0001

### A clear and concise description of what the bug is

Hats have 2 issues.

1. when you give them the money, the correct animation appears to take off the hat however your character will take off his mask instead.
2. When putting on the hat, it will not save the correct texture.

### Steps to Reproduce the Bug

1.buy a hat
2.takes off mask instead of taking off hat
3. put back on the hat from in your pocket
4. its the wrong color hat.

### Expected Behavior

The correct hat

### Screenshots/Videos

Hat#55
https://i.imgur.com/DYwBrES.jpeg
https://i.imgur.com/BbxlqY2.jpeg

**Comment by ithegreatgatsby** [comment]
this should be fixed
