### ISSUE TITLE
[BUG] Festival Bus Can't Play Music

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#965]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

Festival Bus used to play music from the vehicle itself on the outside, but doesn't anymore. Also props go through the top to the bottom of the bus.

### Steps to Reproduce the Bug

1. Try to use PMMS system for music
2. Try to make prop that can play music from PMMS.

### Expected Behavior

Props stick on the top, and music is allowed to be played from the Festival Bus.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98053772/206592350-56e59a9f-ce33-455a-b26b-2172eccf1367.png)

**Comment by ithegreatgatsby** [comment]
Make sure you unclick the Redbox on cars https://cdn.discordapp.com/attachments/926424477049438258/1050837963300425909/hi3lvEsCkz.png.
The prop issue could just be a eye issue as I can replicate that

**Comment by JnKTechstuff** [comment]
Operator error, learn how to use PMMS properly

**Comment by tusktheshrew** [comment]
3 different People, including Otto and Jon Cord could not play it outside the car.
