### ISSUE TITLE
[BUG] Bottle (S) cannot be stacked

### ISSUE THREAD

**Issue by erniexhamer** [ParadoxGamingRP/bugs-and-suggestions#966]
### Your Discord Name

Ernie Hamer#5237

### A clear and concise description of what the bug is

It appears that the bottles are supposed to stack, as they are in piles up to 5 when picked up, but the stacks cannot be combined once in pockets

### Steps to Reproduce the Bug

1. go metal detecting
2. collect Bottle

### Expected Behavior

I expect them to be stackable items

### Screenshots/Videos

https://i.imgur.com/XYsqz1P.jpeg

**Comment by ithegreatgatsby** [comment]
This will be fixed when some other updates get pushed either tonight or next couple days
