### ISSUE TITLE
[BUG]  Tow Impound not working

### ISSUE THREAD

**Issue by Stasik824** [ParadoxGamingRP/bugs-and-suggestions#967]
### Your Discord Name

Stasi#8723

### A clear and concise description of what the bug is

When towing a car, we are unable to Impound the car using the tow menu.

In the 3rd eye under Tow Option (i think thats what its called) and impound car. 

a Noti comes that it was successful, yet it was still visible. 

### Steps to Reproduce the Bug

walk up to the car you want to impound, Use your 3rd eye to pull up the tow menu, click impound car

### Expected Behavior

a Noti comes that it was successful, yet it was still visible. 

### Screenshots/Videos

I will need to get a video for this.

**Comment by ithegreatgatsby** [comment]
You dont use f1. You use third eye

**Comment by Stasik824** [comment]
yes sorry i messed up, it is the 3rd eye when this happens.

**Comment by Stasik824** [comment]
https://medal.tv/games/gta-v/clips/LLiPGDxIbsgKC/d1337C45zBtQ?invite=cr-MSw0V0IsOTE4NjEyMjAs

**Comment by ithegreatgatsby** [comment]
can not replicate. I will leave open a bit to see if you are still having issues
