### ISSUE TITLE
[BUG] Weed Bag Recycle = 1 Plastic 

### ISSUE THREAD

**Issue by JonnieSlay** [ParadoxGamingRP/bugs-and-suggestions#969]
### Your Discord Name

yeaaaaa#9829

### A clear and concise description of what the bug is

So currently 1 plastic = 10 baggies.
If you recycle 1 baggie you get back 1 plastic. 

This doesn't make much sense and I believe was an overthought because in you can turn 1 plastic into 10 by turning them into bags and then back to plastic. 

### Steps to Reproduce the Bug

1. Craft 1 plastic into 10 baggies.
2. Recycling 10 baggies gets you 10 plastic. 

### Expected Behavior

I don't think 1 baggie should return 1 plastic. If anything 10 baggies should return back 1 plastic. Somebody could abuse this and get an infinite amount of plastic. 

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/LFnv9bmZAlkGM/d1337HDYJxew?invite=cr-MSxuUlksMTUzNzcyODUwLA

https://medal.tv/games/gta-v/clips/LFlkIlCX7FtGB/d13375Pr2FXT?invite=cr-MSxlYmUsMTUzNzcyODUwLA

**Comment by JnKTechstuff** [comment]
Fixed!
