### ISSUE TITLE
[BUG] <Inventory trunk dupe>

### ISSUE THREAD

**Issue by tommytwoshotty** [ParadoxGamingRP/bugs-and-suggestions#972]
### Your Discord Name

Tommytwoshotty#0666

### A clear and concise description of what the bug is

I removed items from my trunk inventory on my truck. when i came back later to put items in the truck the items i took out were still there. 

### Steps to Reproduce the Bug

1.Open trunk inventory
2. grab items from trunk that you want
3. Come back a bit later items still exist in trunk

### Expected Behavior

When grab items from trunk or glove box items should disappear from trunk or glove box permanently and not be around later

### Screenshots/Videos

![FiveM_b2699_GTAProcess_iiA6SViBHV](https://user-images.githubusercontent.com/92126060/206936102-62a26ffa-0467-4738-aee8-6ffb6f14618d.png)

### Log File

[CitizenFX_log_2022-12-11T234015.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10203586/CitizenFX_log_2022-12-11T234015.log)

**Comment by JnKTechstuff** [comment]
Random bug
