### ISSUE TITLE
[BUG] No paychecks

### ISSUE THREAD

**Issue by Martyfly200** [ParadoxGamingRP/bugs-and-suggestions#974]
### Your Discord Name

Martyfly2005

### A clear and concise description of what the bug is

I've been Working at the Open Road and Glazed and Glorious and have not received any paycheck the notification won't even pop up and when I went to go collect my paycheck at the bank, I would not receive any money. Others have also told me that it doesn't work but most people tell me they do get paychecks.
EDIT: I get normal paychecks though like the 25 dollar ones
### Steps to Reproduce the Bug

go to open road or GnG and sign in
no paychecks pop up at all while working and while not working 
going to pick up paycheck receive nothing

### Expected Behavior

to receive a pop up of getting paycheck.

### Screenshots/Videos

No screenshots

**Comment by SaraLef** [comment]
Was clocked on wolfs for a few hours and didn't get a paycheck either. Did maybe 3-4 hours today.

**Comment by natashajoan** [comment]
I know what the issue is, the salaries aren't sticking again, they have reset to 0 at Glazed & Glorious and at Kildare, and have to be set every Tsunami, again.

**Comment by SaraLef** [comment]
Paycheck is reset every tsunami for Wolfs, don't know the other businesses.

**Comment by SpiceF0x** [comment]
This is still resetting to 0 every tsunami, pretty sure for every business.

**Comment by xXJamieXx** [comment]
Can't reproduce on Dev

**Comment by xXJamieXx** [comment]
Found the issue and fixed next restart.
