### ISSUE TITLE
[ENHANCEMENT] Book Sizes for Less Resolutions

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#975]
**Your Discord Name**
Shrew#1219

**Describe the annoyance**
People with less than the 1920x1080 can not see the entire book due the book being cropped off their screen.

**To Reproduce**
[Steps to reproduce the annoyance]
1.  Go to a lesser resolution
2.  Open Book
3.  Try to flip pages.

**Requested behavior**
Seeing the entire book based centered on whichever resolution you are on.

**Screenshots**
![image](https://user-images.githubusercontent.com/98053772/207693172-6fc17bf2-7335-4973-b9a5-9c6c8ba0be4a.png)

**Additional context**
[Add any other context about the enhancement here]

**Comment by JnKTechstuff** [comment]
Mark this
![image](https://user-images.githubusercontent.com/7122547/207740633-bc915e38-68c1-4c26-8af9-7f5884521508.png)
