### ISSUE TITLE
[BUG] Open Road Bags not working

### ISSUE THREAD

**Issue by KNO-1** [ParadoxGamingRP/bugs-and-suggestions#976]
### Your Discord Name

Kno#1221

### A clear and concise description of what the bug is

The Open Road bag does not work as intended. When trying to bag someone they're not getting the blackout effect nor is the prop on their head, and the bag gets used.

### Steps to Reproduce the Bug

1. Purchase an Open Road Bag.
2. Place bag on someone's head. 
3. The bag does not go on their head and they can still see. 

### Expected Behavior

1. Purchase an Open Road Bag.
2. Place bag on someone's head. 
3. The person gets bagged and they cannot see until they remove the bag. 

### Screenshots/Videos

![Capture](https://user-images.githubusercontent.com/113763661/207696122-9eff7a07-50f9-4b3a-8f8c-8562e52dcfec.PNG)

**Comment by ithegreatgatsby** [comment]
Closing this.   This will be dealt with in the ticket paul opened in the dev discord. Thanks
