### ISSUE TITLE
[ENHANCEMENT] PC 855 GATE 

### ISSUE THREAD

**Issue by JonnieSlay** [ParadoxGamingRP/bugs-and-suggestions#981]
**Your Discord Name**
[yeaaaaa#9829]

**Describe the annoyance**
[I own the property over at 855, and there is a fixed gate. Granted I was aware of that gate when I initially purchased the property. I would like to request if possible to remove that gate from that property as its made my vehicles sometimes spawn in between it and go crazy]

**To Reproduce**
[Steps to reproduce the annoyance]
1. Go to 855. 
2. Try to go through gate
3.  It doesnt open up

**Requested behavior**
[Just possibly remove it ? Attached would be the gate removal resource:

https://mega.nz/file/1KcUTTiZ#_IMtRrnHMZXOQoUTtPUeDFMxNt-v0FT7fLRmC_PP20U

 ]

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[If we can't remove it, I completely understand, but it would make my experience if i had that driveway opened up to my property ]

Thanks in advance,

**Comment by JonnieSlay** [comment]
The resource I attached is just that 1 single fixed closed gate over at 855.

**Comment by ithegreatgatsby** [comment]
We do not do custom mapping for player owns. If we do it for all we would have to do edits for everyone and we simply dont have the time as well as don't need to add more edited ymap
