### ISSUE TITLE
[ENHANCEMENT] Add Repair Kits to recycling

### ISSUE THREAD

**Issue by natashajoan** [ParadoxGamingRP/bugs-and-suggestions#982]
**Your Discord Name**
its_ahsatan@7098

**Describe the annoyance**
Sick of going to the fekin recycling place and seeing at least 1 repair kit sat in the box cos they can't be recycled, there was 3 the other day! 

**To Reproduce**
[Steps to reproduce the annoyance]
1. Broken repair kit
2. Take to recycle
3. Be actually able to recycle the fekin thing

**Requested behavior**
[A clear and concise description of what you want to happen]
Be able to recycle the repair kits, pls n fanks 

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by ithegreatgatsby** [comment]
next update
