### ISSUE TITLE
[ENHANCEMENT] Add single rose and bouquet to prop menu

### ISSUE THREAD

**Issue by natashajoan** [ParadoxGamingRP/bugs-and-suggestions#983]
**Your Discord Name**
its_ahsatan#7098

**Describe the annoyance**
Add flowers to the prop menu, it's especially good for funerals, so people can lay a rose down, also good for other scenes.

**To Reproduce**
[Steps to reproduce the annoyance]
1. 
2. 
3. 

**Requested behavior**
[A clear and concise description of what you want to happen]

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by Darahz** [comment]
Added Rose and Bouquet. Thank you!
