### ISSUE TITLE
[BUG] SOTW items

### ISSUE THREAD

**Issue by SaraLef** [ParadoxGamingRP/bugs-and-suggestions#986]
### Your Discord Name

ssara#7821

### A clear and concise description of what the bug is

So the mushrooms have no effects and the Legion Diesel doesn't heal anymore like it used to.

### Steps to Reproduce the Bug

buy a shroom
eat it
you think its a chantarell

buy a legion
smoke it
you see colours and feel warm inside, but your health will stay the same

### Expected Behavior

Be able to smell colours with the shroomies
Be able to feel better with the Legion

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/N6iiru0wqvNog/d1337JItJSy4?invite=cr-MSxibHEsNDU3NjU0MzAs

**Comment by ithegreatgatsby** [comment]
fixed after the restart. reverted mushrooms to old effect since the one i picked only NVE users could see
