### ISSUE TITLE
[ENHANCEMENT] Be able to change our eye colour 

### ISSUE THREAD

**Issue by natashajoan** [ParadoxGamingRP/bugs-and-suggestions#987]
**Your Discord Name**
its_ahsatan#7098

**Describe the annoyance**
I know I say this for a lot of people, but we would all like to have the option to change our eye colour again like we could in 2.0. It brings a lot more to making each persons character individual and unique. 

**To Reproduce**
[Steps to reproduce the annoyance]
1. 
2. 
3. 

**Requested behavior**
[A clear and concise description of what you want to happen]

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by xXJamieXx** [comment]
A little Christmas gift for you :)
