### ISSUE TITLE
[BUG] Carbon Doesn't Stack

### ISSUE THREAD

**Issue by tusktheshrew** [ParadoxGamingRP/bugs-and-suggestions#988]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

While Mining the Carbon from each rock doesn't stack for each other.

### Steps to Reproduce the Bug

1. Go to mine
2. Mine Carbon Rock
3. Look at Inventory
4. Mine 2nd Carbon Rock
5. Look at Inventory

### Expected Behavior

Carbon stacks together in one slot

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98053772/209026321-d4cbd80b-d9aa-4175-9172-2f6cf4bec8ee.png)

**Comment by Darahz** [comment]
Fixed
