### ISSUE TITLE
[BUG] Cant corner sell when PD is around

### ISSUE THREAD

**Issue by PatrykX904** [ParadoxGamingRP/bugs-and-suggestions#991]
### Your Discord Name

Help Me Choose A Name#0175

### A clear and concise description of what the bug is

Whenever I try to corner sell when theres PD around it will not let me.

### Steps to Reproduce the Bug

1. Try corner selling when PD is around
2. Tells you Streets are too clean no buyers around

### Expected Behavior

Be able to corner sell when PD is around

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/81855046/209203439-9f192773-abab-49db-bd27-8fac248fe418.png)
![image](https://user-images.githubusercontent.com/81855046/209203475-8bb66e61-15f9-4f60-a461-087616cf8e68.png)

**Comment by xXJamieXx** [comment]
Should be fixed.
