### ISSUE TITLE
[BUG] <No paycheck at open road after working a few hours>

### ISSUE THREAD

**Issue by tommytwoshotty** [ParadoxGamingRP/bugs-and-suggestions#994]
### Your Discord Name

tommytwoshotty#0666

### A clear and concise description of what the bug is

After working many hours at the Open road bar N Grill  i went to the bank to collect my paycheck. Much to my surprise there was no paycheck to be had. If this helps at all i was in jail a hour or so before i opened the bar.

### Steps to Reproduce the Bug

1. Work at Open road bar n grill clocked in
2. Go to big bank to collect paycheck 
3. Paycheck says $0

### Expected Behavior

Work at bar and get money

### Screenshots/Videos

[Un](https://i.imgur.com/VWARZEj.png)

### Extra Notes (Optional)

None

### Log File

[CitizenFX_log_2022-12-27T234925.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/10312898/CitizenFX_log_2022-12-27T234925.log)

**Comment by ithegreatgatsby** [comment]
still a issue?

**Comment by tommytwoshotty** [comment]
Not since the big update happened
