### ISSUE TITLE
[BUG] Mesa R roof does not stay on after parking

### ISSUE THREAD

**Issue by ShaymusSavage** [ParadoxGamingRP/bugs-and-suggestions#996]
### Your Discord Name

Shaymus#1460

### A clear and concise description of what the bug is

Canis Mesa R does not keep "Extra 1" or roof when it is parked and removed from the garage. 

### Steps to Reproduce the Bug

1. Drive Canis Mesa R to garage to customize.
2. Add "Extra 1" (The roof)
3. Go find a parking space and park the Mesa R.
4. Pull the Mesa R from the parking spot.
5. Roof (Extra 1) will be missing from the vehicle.

### Expected Behavior

Have the roof (Extra 1) remain on the vehicle when it is pulled from the parking spot.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/3319344/209898536-c759d6af-8baa-4f3f-9b07-4df1f6e5a2e8.png)
![image](https://user-images.githubusercontent.com/3319344/209898586-a2cd10f9-a06a-49a4-a08b-18e06f542bf9.png)

**Comment by ithegreatgatsby** [comment]
been some changes to how extras are saved. Please let me know if this is still on going
