### ISSUE TITLE
[ENHANCEMENT] Maybe be able to send Emails to people VIA Email app in city

### ISSUE THREAD

**Issue by PatrykX904** [ParadoxGamingRP/bugs-and-suggestions#997]
**Your Discord Name**
[Help Me Choose A Name#0175]

**Describe the annoyance**
[0 Annoyances just wondering on if its possible to send emails to people with the email app in the city]

**To Reproduce**
[Steps to reproduce the annoyance]
1. Go into email app on phone
2. Not being able to send an email to someone

**Requested behavior**
[Make it so theres a + button maybe and then make a section of where it would say Insert Persons Email: and then under that Message: then be able to send it to the person]

**Screenshots**

**Comment by ithegreatgatsby** [comment]
Right now we only use emails for script based notifications or staff events. we may re visit this request in the future
